### ISSUE TITLE
OpenWRT 22.03-rc3 Package archive gone missing.

### ISSUE THREAD

**Issue by PsychoGame** [openwrt/openwrt#10012]
Dear OpenWRT developers/maintainers.

After just having set-up my routers with OpenWRT 22.03-rc3 for testing this release, I noticed the package archives of rc2/rc3 are both gone as of today.
I see that rc1 still is online, but then I would need to downgrade everything again, to make my set-up work due to the fact that I need to install nfs kernel stuff, which is not compatible between these releases due to kernel upgrades.
Why has the rc3 been pulled actually, I would have expected the earlier package archives to be pulled offline if clean-up was the purpose.

**Comment by jow-** [comment]
rc2 and rc3 have never been officially released and got pulled due to major bugs on certain targets.
