### ISSUE TITLE
Reduce fstab start priority to 16 instead to 40, needs to start before dnsmasq

### ISSUE THREAD

**Issue by schuettecarsten** [openwrt/openwrt#10027]
I placed the dhcp.leases file to an external USB drive. Unfortunately, dnsmasq starts before fstab mounted the USB device, because dnsmasq start priority is 19, and fstab 40. So, I suggest to reduce the fstab priority to 16 and make sure that external file systems are mounted before services try to access it.

I use imagebuilder to create my images, I do not see an option to change the priority during my build process.

**Comment by neheb** [comment]
Fixed: https://github.com/openwrt/openwrt/commit/f83e927b8744c0642fd61245935c4bb20e0b6f33

Please close.
