### ISSUE TITLE
firewall4 disappears when deselecting IPv6

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/openwrt#10034]
In a clean build from source, I haven't been able to select firewall4 as it disappears when disabling IPv6.

**Comment by pepe2k** [comment]
@castillofrancodamian this is not a bug, `firewall4` depends on IPv6 support (you can follow dependencies).

Cheers,
Piotr

**Comment by castillofrancodamian** [comment]
And there is no alternative?

**Comment by champtar** [comment]
Just put a rule to drop IPv6 traffic ?

**Comment by castillofrancodamian** [comment]
The idea was to remove possibly everything that has to do with IPv6 and related configuration as well. I don't expect to use IPv6 any time soon. It also saves space.

**Comment by champtar** [comment]
Maintaining the option to disable IPv6 is a huge amount of work, not that much people uses it, and even just disabling IPv6 at runtime breaks some software, so expect this option to just disappear in a future release.
