### ISSUE TITLE
MicroSD card not identified with device MikroTik RB760iGS (hEX S)

### ISSUE THREAD

**Issue by cmonty14** [openwrt/openwrt#10044]
Hello,
I'm running OpenWrt 21.02.3 on [this](https://openwrt.org/toh/mikrotik/rb760igs) router _MikroTik RB760iGS (hEX S)_.

There's limited storage that could be extended by MicroSD card.

However, any MicroSD card I put in the slot is not identified.
USB type A slot is working w/o issues.

I assume a specific driver is required for MicroSD card to work.

Can you please advise which driver / package must be installed?

These kernel modules are installed already:
```
root@eddie:~# lsmod | grep usb
nls_base                5296  1 usbcore
scsi_mod               86192  3 uas,usb_storage,sd_mod
usb_common              2704  4 ehci_platform,xhci_plat_hcd,xhci_hcd,usbcore
usb_storage            42272  1 uas
usbcore               141312  9 ehci_platform,ehci_fsl,ehci_hcd,uas,usb_storage,xhci_plat_hcd,xhci_pci,xhci_mtk,xhci_hcd

```

**Comment by pepe2k** [comment]
@cmonty14 please, install `kmod-sdhci` which should provide support for the SD card.

Cheers,
Piotr
