### ISSUE TITLE
Intel igc driver needed for default installs

### ISSUE THREAD

**Issue by txcanyon** [openwrt/openwrt#10064]
As built, the igc driver is not included by default on x86 builds. There have been a ton of new embedded devices with i225 multi-gigabit connections, with many more on the horizon. While there are workarounds that are pretty simple to get around this limitation, and given the upward trend towards 2.5gbs network connections this would be a beneficial driver to add. If you want to add the realtek 8125 driver as well, I'm sure some folks out there may be able to take advantage of it.

**Comment by shdf2** [comment]
i aggre with @txcanyon 
actualy i have to use the online builder : 
https://chef.libremesh.org/?version=21.02.3&target=x86%2F64&id=generic
and click _customize_ + add **kmod-igc** to the list.
That's easy when you know it...which is not necessarily the case for everyone
