### ISSUE TITLE
does openwrt 19.07.10 support rtl8811cu?

### ISSUE THREAD

**Issue by liuhong785738008** [openwrt/openwrt#10093]
I tried to run OpenWRT-19.07.10 on MT7628, but I had a lot of problems compiling RTL8811cu, do you provide the related driver?

**Comment by pepe2k** [comment]
@liuhong785738008 this is a bug trucker only, for support requests, please use our Forum and/or Wiki or other channels (mailing lists, IRC). For example: https://forum.openwrt.org/t/how-to-add-drivers-for-rtl8811cu-to-openwrt/59984

Cheers,
Piotr
