### ISSUE TITLE
firewall4 postrouting does not see outgoing packets

### ISSUE THREAD

**Issue by WeSTManCoder** [openwrt/openwrt#10092]
postrouting does not see outgoing packets

root@OpenWrt:~# tcpdump -n -i br-lan port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on br-lan, link-type EN10MB (Ethernet), capture size 262144 bytes
08:46:36.373409 IP 192.168.1.100.14071 > 192.168.1.1.53: 36044+ A? ads.adfox.ru. (30)
08:46:36.373885 IP 192.168.1.1.53 > 192.168.1.100.14071: 36044 1/0/0 A 77.88.21.179 (46)

nft list ruleset:
table ip routing {
        chain postrouting {
                type nat hook postrouting priority srcnat - 1; policy accept;
                udp sport 53 counter packets 0 bytes 0
        }
}

counter = 0 packets, but packet sended

Linux OpenWrt 5.10.120 #0 SMP Sun Jun 19 10:40:30 2022 mips GNU/Linux
OpenWrt SNAPSHOT r19859-36e46c3c13 / LuCI Master git-22.167.28356-8effea5

Firewall4 last updated on openwrt master
please fix this problem, thanks

**Comment by jow-** [comment]
Type nat is only for natting, not for filtering and postrouting does not catch outbound traffic, only forwarded flows. The chosen chain is simply not adequate for your apparent use case (matching egress DNS).

**Comment by WeSTManCoder** [comment]
> Type nat is only for natting, not for filtering and postrouting does not catch outbound traffic, only forwarded flows. The chosen chain is simply not adequate for your apparent use case (matching egress DNS).

i want change ip src.
192.168.1.1:53 to 192.168.1.1:54
im using SNAT
nft add rule ip routing postrouting udp sport 53 snat 192.168.1.1:54

this rule does not see outgoing packets. Can you suggest something?
