### ISSUE TITLE
wndap660 switch port to physical label and indicator LED mapping incorrect

### ISSUE THREAD

**Issue by tim-seoss** [openwrt/openwrt#10111]
WNDAP 660  OpenWrt 22.03.0-rc4, r19426-2b1941e47d

Viewing the 'Network' -> 'Switch' config page in LuCI:

- The LuCI `LAN 1` port corresponds to the port physically labelled `🖧2` at the rear of the device.
- The LuCI `LAN 2` port corresponds to the port physically labelled `🖧1` at the rear of the device.

When a patch cord is attached to the port labelled `🖧1` on the device, the LED labelled `🖧2` illuminates.
When a patch cord is attached to the port labelled `🖧2` on the device, no changes are seen on any LEDs.

I've only checked the LED behaviour with a with a 1000baseT device attached.

**Comment by neheb** [comment]
Was this an issue with ar71xx (19.07)?

**Comment by tim-seoss** [comment]
> Was this an issue with ar71xx (19.07)?

@neheb Although this access point has ath9k radios, the SoC is PowerPC 460 (APM82181), rather than MIPS, and it's always used Device Tree.

I haven't checked to see if this is a regression vs earlier released tho'.  I'll try and check that later today.

**Comment by tim-seoss** [comment]
The LED behaviour is correct in 21.02.3 and also in 19.07.9.  It only seems to be broken in 22.03.0-rc4.

On all three releases, the LuCI `LAN 1` port is mapped to `🖧2` and vice versa.

I suppose it could be argued that fixing this could be a breaking change for some people, however in the default config both ports are configured as LAN ports, and also an upgrade from an earlier release to 22.03 requires writing the factory image (not sysupgrade due to partition sizing requirements), so I think pre 22.03 would be a good time to make this fix.  Any thoughts?

**Comment by tim-seoss** [comment]
Hi @chunkeey firstly, thanks for your work porting OpenWRT to the WNDAP660! Any thoughts on the above?

**Comment by tim-seoss** [comment]
The current downloadable snapshot `netgear_wndap660-initramfs-kernel.bin	10bba3a0bee879a378f73e2a1a90a07f91f5a852bc6c4983b71599a7b97295d3	7225.7 KB	Fri Jun 24 11:34:11 2022` shows the same behavour as 22.03.0-rc4.

**Comment by tim-seoss** [comment]
Confirmed fixed, thanks!
