### ISSUE TITLE
LUCI wifi scan not working for 2.4 Mhz on ath79 for OpenWrt 22.03

### ISSUE THREAD

**Issue by humaita-github** [openwrt/openwrt#10158]
Hi,

I have successfully been runnnig OpenWrt 22.03 on my "TP-Link Archer C7 V5". However, in LUCI both in RC1 and in RC4 wifi scan is not working for 2.4 Mhz. I can connect to 2.4Mhz wifi. And I can scan and connect to 5Ghz wifi, but no scanning in 2.4Mhz. LUCI just says "Starting wireless scan...", then nothing happens, then it says "No data". Channel analysis does not work on 2.4Mhz either. On all versions of OpenWrt 21.02 this was not a problem. When starting wifi scan, there is no new entry in system log. 

In the forum, an additional user mentioned the same problem for RC1: _"Installed on TP-Link CPE220 V3 (ath79/generic) from 21.2.3. Everything seems to work except wireless scan/channel analysis. LUCI seems to freeze when starting to scan for wireless, and it takes about 20 seconds to go back to normal after refreshing webpage."_

**Update 1:** Scanning in CLI does work
- Using "iw dev wlan1 scan" takes around 5 seconds to complete
- Using "iwinfo wlan1 scan" takes around 25 seconds to complete > Is this maybe a time-out issue?

**Update 2:** The console of my webbrowser  says
    Uncaught (in promise) Error: XHR request timed out
    at Object.handleReadyStateChange (luci.js?v=git-22.140.66268-ef99568:69:20)

**Update 3:** The problem is still present in RC5

**Update 4:** The problem is still present in RC6. Also, the problem also appears on  "D-Link DIR-505"

**Update 5:** The problem is still present in the final release 22.03.0 (r19685-512e76967f)

**Comment by sven3** [comment]
I got the exact same issue. TL-WR1043ND v1, also ath79.

**Comment by ManuLinares** [comment]
Same here, can't scan from luci web. but from CLI there is no issue.

```
| Model            	| TP-Link CPE220 v3                                                         	|
|------------------	|---------------------------------------------------------------------------	|
| Architecture     	| Qualcomm Atheros QCA9533 ver 2 rev 0                                      	|
| Target Platform  	| ath79/generic                                                             	|
| Firmware Version 	| OpenWrt SNAPSHOT r20212-beeb49740b / LuCI Master git-22.208.55978-37422e8 	|
| Kernel Version   	| 5.10.134                                                                  	|

```

**Comment by NickolaySmirnov** [comment]
Same here on Raspberry Pi 3A+, web scan is broken, cli scan works

```
Model			Raspberry Pi 3 Model A Plus Rev 1.0
Architecture		ARMv8 Processor rev 4
Target Platform		bcm27xx/bcm2710
Firmware Version	OpenWrt 22.03.0 r19685-512e76967f / LuCI openwrt-22.03 branch git-22.245.77528-487e58a
Kernel Version		5.10.138

```

**Comment by dbareiro** [comment]
Hi!

I can confirm that this issue is still present to date, tested on a TL-WDR3600 device. Is there an estimated date to publish the patch?

Thanks in advance.

Regards,
Daniel

**Comment by sven3** [comment]
> Is there an estimated date to publish the patch?

What patch are you referring to?

**Comment by ManuLinares** [comment]
> > Is there an estimated date to publish the patch?
> 
> What patch are you referring to?

my patch, https://github.com/openwrt/luci/pull/5934

**Comment by dbareiro** [comment]
Hi, @sven3.

> What patch are you referring to?

I was referring to whether there is a release date planned for new versions of the related packages including the patch that solves the problem mentioned in this issue. Although I have not seen in this thread any comment on whether there is any previous work on said patch.

Kind regards,
Daniel

**Comment by dbareiro** [comment]
Hi, @ManuLinares 

Thanks for sharing your patch here: https://github.com/openwrt/luci/pull/5934

I see you posted it on August 15th but it seems they haven't generated a new version of the packages including it yet.

Regards,
Daniel

**Comment by sven3** [comment]
The patch @ManuLinares mentioned (and deleted) here has absolutely nothing to do with the problem mentioned here, so it won't help.

**Comment by ManuLinares** [comment]
> The patch @ManuLinares mentioned (and deleted) here has absolutely nothing to do with the problem mentioned here, so it won't help.

I misread the title, and commented wrongly. So I deleted the comment almost immediately.

**Comment by humaita-github** [comment]
Hi, this bug still exists in OpenWrt v22.03.1 released on 12. October 2022.

**Comment by humaita-github** [comment]
Hi, this bug still exists in OpenWrt v22.03.2 released on 17. October 2022.

**Comment by AzimsTech** [comment]
Same issue. 
Techdata: [D-Link DIR-842 C2](https://openwrt.org/toh/hwdata/d-link/d-link_dir-842_c2)

![image](https://user-images.githubusercontent.com/12103851/204085554-768c412a-e3d3-4350-9d37-d6389942f429.png)

**Comment by humaita-github** [comment]
Hi, this problem also affects CPE210 v3.

**Comment by ManuLinares** [comment]
> Hi, this problem also affects CPE210 v3.

Indeed, it is still not working. 

```
| Model            	| TP-Link CPE220 v3                                                         	|
|------------------	|---------------------------------------------------------------------------	|
| Architecture     	| Qualcomm Atheros QCA9533 ver 2 rev 0                                      	|
| Target Platform  	| ath79/generic                                                             	|
| Firmware Version 	| OpenWrt SNAPSHOT r21123-641e4f2f04 / LuCI Master git-22.299.72136-a98e2ea     |
| Kernel Version   	| 5.15.74                                                                  	|

```

**Comment by sven3** [comment]
I opened a bug request in the luci bug tracker because I think that this is a better place for this to get fixed. I quoted your devices and version experience there.
