### ISSUE TITLE
openwrt-21.02 x86_64 View configuration changes interface style is messy

### ISSUE THREAD

**Issue by zzwtsy** [openwrt/openwrt#10170]
The following text is translated by Google   
The legends of "Options changed" and "Options removed" in Figure 1 are inconsistent with the legends of "Add Node", delete the "<var>" at the red arrow at the bottom arrow to make them consistent
[picture1](https://github.com/zzwtsy/images/blob/main/img/pic01.png)
The second column in picture 2 (uci add shadowsocksr servers # =cfg064a8f) lacks borders and margins compared to other columns, adding "<var>" code at the red arrow below the picture can make them consistent
[picture2](https://github.com/zzwtsy/images/blob/main/img/pic02.png)

**Comment by BKPepe** [comment]
Your issue seems to be related to LuCI. Translations are maintained in the [Weblate](https://hosted.weblate.org/projects/openwrt/) and anyone can contribute there.
