### ISSUE TITLE
Does rtl8811cu work well on openwrt21.02?

### ISSUE THREAD

**Issue by liuhong785738008** [openwrt/openwrt#10199]
I have a router for MT7628 and I connect an RTL8811cu chipset to the MT7628 using USB. I used the driver you provided, and I can use WIFI through RTL8811cu, but I am not satisfied with the fact that I have to restart the system after configuring WIFI each time to take effect. Could you help me?
Thanks!

**Comment by tapper82** [comment]
Hi this is one for the Forums. Pleas close.

**Comment by liuhong785738008** [comment]
@tapper82 ok
