### ISSUE TITLE
is the md5sum of iperf2/iperf-2.0.9.tar.gz wrong?

### ISSUE THREAD

**Issue by timcoote** [openwrt/openwrt#102]
I tried a build today and it kept failing on iperf2. The md5sum in packages/network/utils/iperf/Makefile for iperf2/iperf-2.0.9.tar.gz is: 1bb3a1d98b1973aee6e8f171933c0f61. However, all of the versions that I can find have an md5sum of: 351b018b71176b8cb25f20eef6a9e37c. 

Is this a bug?  If it is, how did it get through the build process and how can we test for such failures automatically?

**Comment by psyborg55** [comment]
yes, it seems to be. i've just replaced md5sum in makefile with 351b018b71176b8cb25f20eef6a9e37c and it built successfully.
