### ISSUE TITLE
cameo-tag.py broken

### ISSUE THREAD

**Issue by plappermaul** [openwrt/openwrt#10204]
Last second script changes after sending pull request and commiting it via  https://github.com/openwrt/openwrt/commit/f9e840b65700e1cdff6d066d39c163bac936d046 broke it. UIMAGE_CRC_OFF is not defined.

**Comment by plappermaul** [comment]
@svanheule more than cosmetic changes from you ...

**Comment by svanheule** [comment]
That was not intentional, my apologies! I'll fix it right away.

**Comment by svanheule** [comment]
Fixed with commit ebfe66e494e5 "scripts: fix CAMEO tag generator"

Again, my apologies for breaking your script. I should better than not to properly test a commit...
