### ISSUE TITLE
Question: Procd Custom mount point '/mnt/usb'

### ISSUE THREAD

**Issue by arky** [openwrt/openwrt#10210]
When you connect a USB device to openwrt, they are mounted with device node name (e.g. /dev/sda1, /dev/sdb2). Is it possible to mount them at custom mount /mnt/usb and /mnt/usb2 instead.

The solution I seek is for instances you don't know the device that would be automounted. Otherwise this could be handled with custom fstab entries. Thanks!

**Comment by arky** [comment]
Alternatively is it possible to create a symlink /mnt/usb point to the first automounted USB device instead.

Thanks

**Comment by jow-** [comment]
Please use the forum or mailing lists for support qustions.
