### ISSUE TITLE
luci-app-wireguard: Invalid Error Message, Refresh

### ISSUE THREAD

**Issue by arrmo** [openwrt/openwrt#10216]
Hi,

I have noticed that if I have WireGuard configured, but handshake has not occurred, the status shows,
```
No WireGuard interfaces configured
```

But that's not really correct. It's not connected (vs. not configured). Perhaps update this wording? I don't mind updating it, if you'd prefer.

I have also noticed, that in this state refresh is not really updating. If it connects ... you have to manually refresh. This one seems a bit more odd. Any reason why it wouldn't refresh? And it seems that state changes are what cause this to not refresh properly?

Thanks!

**Comment by arrmo** [comment]
Sure, NP! Is there a way to transfer it there? I admit, I wasn't sure quite where to open it.

Thanks!

**Comment by f00b4r0** [comment]
There isn't. Best close here and open anew there. Thanks!

**Comment by arrmo** [comment]
Will do! Just one thing ... move to packages, or https://github.com/openwrt/luci/issues?

Thanks!

**Comment by f00b4r0** [comment]
> Will do! Just one thing ... move to packages, or https://github.com/openwrt/luci/issues?

The latter, good catch, my bad!
Thanks

**Comment by arrmo** [comment]
Done!
