### ISSUE TITLE
[22.03.0-rc5 armvirt-64] Lxc container on raspberry pi 4: wget Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ntaken** [openwrt/openwrt#10239]
Running 22.03.0-rc5 with image armvirt-64 with lxc on raspberry pie 4 i get the error:

```
~ # wget
Illegal instruction (core dumped)
```

wget works fine on same set up with 21.02.3.

**Comment by gmiranda** [comment]
I can confirm this issue. It's very annoying since it prevents from downloading anything via opkg.

**Comment by ntaken** [comment]
Works again in 22.03.0-rc6.
