### ISSUE TITLE
government intruder in a NAT in my router

### ISSUE THREAD

**Issue by microlaser** [openwrt/openwrt#10259]
I have am running openwrt on a linksys 8300 and when I run nmap the mac address for the router doesn't match the hardware.  I think that there could be a man in the middle inside a nat based on the mac address mismatch.  I wanted to make sure this is not normal for the mac address for a linksys to not match.  The first device should be the router. I have labeled the devices in all caps, and the mac addresses match, I have two linksys routers and one has the right Belkin mac, and one does not have the correct mac address. I have been a whistleblower and I believe my government is spying on me.  

root@michael-GS60-2PC-Ghost:/home/michael# nmap -Pn 192.168.1.1/24
Starting Nmap 7.80 ( https://nmap.org ) at 2022-07-12 05:28 EDT
Nmap scan report for 192.168.1.1
Host is up (0.0012s latency).
Not shown: 997 closed ports
PORT    STATE SERVICE
53/tcp  open  domain
80/tcp  open  http
443/tcp open  https
MAC Address: E8:9F:80:AD:98:E3 (Unknown)

THIS SHOULD BE THE ROUTER

Nmap scan report for 192.168.1.151
Host is up (0.00081s latency).
All 1000 scanned ports on 192.168.1.151 are filtered
MAC Address: 14:98:77:7A:97:6F (Unknown)

THIS IS A MAC

Nmap scan report for 192.168.1.165
Host is up (0.0010s latency).
All 1000 scanned ports on 192.168.1.165 are closed
MAC Address: C4:41:1E:AE:9B:09 (Belkin International)

THIS IS A SECOND ROUTER

Nmap scan report for 192.168.1.179
Host is up (0.00058s latency).
All 1000 scanned ports on 192.168.1.179 are closed
MAC Address: 64:00:6A:71:4C:EA (Dell)

THIS IS A LINUX BOX

Nmap scan report for 192.168.1.213
Host is up (0.0000040s latency).
All 1000 scanned ports on 192.168.1.213 are closed

THIS IS A LINUX BOX

Nmap done: 256 IP addresses (5 hosts up) scanned in 42.42 seconds
root@michael-GS60-2PC-Ghost:/home/michael#

**Comment by jow-** [comment]
The OUI prefix E8:9F:80 is allocated to Belkin International Inc. (cross check at https://www.wireshark.org/tools/oui-lookup.html)

Also OpenWrt increments the MAC address by one for some interfaces (see https://github.com/openwrt/openwrt/blob/master/target/linux/ipq40xx/base-files/lib/preinit/05_set_iface_mac_ipq40xx.sh#L19)
