### ISSUE TITLE
`kmod-gpio-button-hotplug` @22.03: Compilation fails with `make: No rule to make target '[...]/linux-5.10.127/.config', needed by '[...]gpio-button-hotplug/.built'.  Stop.`

### ISSUE THREAD

**Issue by felixbecker2** [openwrt/openwrt#10254]
### Maintainer:

*(Not specified in `package/kernel/gpio-button-hotplug/Makefile`.)*

### Environment:

* Building for Xunlog OrangePi Plus (sun8i):  
  `grep ^CONFIG_TARGET .config`:
  ```
  CONFIG_TARGET_sunxi=y
  CONFIG_TARGET_sunxi_cortexa7=y
  CONFIG_TARGET_sunxi_cortexa7_DEVICE_xunlong_orangepi-plus=y
  CONFIG_TARGET_BOARD="sunxi"
  CONFIG_TARGET_SUBTARGET="cortexa7"
  CONFIG_TARGET_PROFILE="DEVICE_xunlong_orangepi-plus"
  CONFIG_TARGET_ARCH_PACKAGES="arm_cortex-a7_neon-vfpv4"
  [...]
  ```
* OpenWrt version:
  - Git branch `openwrt-22.03` from `git://git.openwrt.org/openwrt/openwrt.git`,
  - initially checked out on 2022-07-05,
  - latest `git pull` and `./scripts/feeds update -a && ./scripts/feeds update -a` on 2022-07-12, ca. 18:00 UTC  
    *(I give up on posting latest commit date and hash, since `git log` gives me some old dates, and I don't know how I can make `git log` printing out the last operation. I don't know much about `git`.)*
* Building on GNU/Linux on x86_64-architecture (Distribution: [Artix Linux](http://artixlinux.org)).
* OpenWrt configuration: [`config.txt`](https://github.com/openwrt/openwrt/files/9095713/config.txt).
* `grep -i gpio-button-hotplug .config`:  
  ```
  CONFIG_PACKAGE_kmod-gpio-button-hotplug=m
  ```

### Description:

Compilation of `kmod-gpio-button-hotplug` fails with  
`make[2]: *** No rule to make target '/[...]/openwrt-22.03/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/linux-5.10.127/.config', needed by '/[...]/openwrt-22.03/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/gpio-button-hotplug/.built'.  Stop.`:

After a `make package/kernel/gpio-button-hotplug/clean`, output of `make -j1 V=sc package/kernel/gpio-button-hotplug/compile` shows:
```
make[2]: Entering directory '/[...]/openwrt-22.03/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/[...]/openwrt-22.03/scripts/config'
make[1]: Entering directory '/[...]/openwrt-22.03'
make[2]: Entering directory '/[...]/openwrt-22.03/package/kernel/gpio-button-hotplug'
make[2]: *** No rule to make target '/[...]/openwrt-22.03/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/linux-5.10.127/.config', needed by '/[...]/openwrt-22.03/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/gpio-button-hotplug/.built'.  Stop.
make[2]: Leaving directory '/[...]/openwrt-22.03/package/kernel/gpio-button-hotplug'
time: package/kernel/gpio-button-hotplug/compile#0.27#0.12#0.36
    ERROR: package/kernel/gpio-button-hotplug failed to build.
make[1]: *** [package/Makefile:116: package/kernel/gpio-button-hotplug/compile] Error 1
make[1]: Leaving directory '/[...]/openwrt-22.03'
make: *** [/[...]/openwrt-22.03/include/toplevel.mk:230: package/kernel/gpio-button-hotplug/compile] Error 2
```

*I don't know what goes wrong here. It happend when I wanted to compile `gnutls`, `kmod-gpio-button-hotplug` seems to be compiled as a dependency. But it just popped up now, previously I could compile `gnutls` (with the same `gnutls` configuration options). I did some `git pull` and `./scripts/feeds update -a && ./scripts/feeds update -a` in between, though, as well as manual compilation of `kmod-`-packages (`package/kernel/*`) and `-firmware`-packages (`package/firmware/*`). I am hesitating to do a `make dirclean`, since compilation on my machine takes a day or so, after which the repository will be outdated again. Could this be a spurious error due to missing `make dirclean`, or is it a "real" issue?*

**Comment by felixbecker2** [comment]
I close this issue since it is not clear enough for me what is going on to bother the community.

**Comment by shi156** [comment]
hello,did you solve the problem?

**Comment by geak** [comment]
Any updates? A get the same issue with SNAPSHOT on macOS :(
