### ISSUE TITLE
Microchip sama5D27 som1 EK bootstrap and u-boot bootloaders failed to detect SDMMC0 - SD card

### ISSUE THREAD

**Issue by DennisDNguy** [openwrt/openwrt#10276]
Since OpenWRT v21.02.0 version, Microchip sama5D27 som1 EK bootstrap and u-boot bootloaders failed to detect SDMMC0 - SD card.

The AT19 sama5D27 som1 EK bootstrap and u-boot bootloaders were working until OpenWRT v19.07.9 version. The bootloaders versions that were working are: AT91Bootstrap 3.8.1 and U-Boot 2017.03 linux4Sam_5.8

The AT91Bootstrap v3.9.3 and u-boot v2020.01 failed to detect SDMMC0 - SD card. 

Following are the error messages:
RomBOOT
AT91Bootstrap 3.9.3 (2022-04-16)
SDHC: fix in place for SAMA5D2 SoM VDDSDMMC over-consumption errata
SD/MMC: Image: Read file u-boot.bin to 0x23f00000
MMC: ADMA supported
SDHC: Error: No Card Inserted
*** FATFS: f_open, filename: [u-boot.bin]: error
SD/MMC: Failed to load image

Files are in the microSD card:
![image](https://user-images.githubusercontent.com/5569521/179062932-10270ffa-f43b-41aa-b1cb-5a1e12afe905.png)

**Comment by claudiubeznea** [comment]
@DennisDNguy: this seems like an AT91Bootstrap issue. Could you please present your issue at [1]? Once a resolution is found we can take the proper action for OpenWrt, too.

[1] https://github.com/linux4sam/at91bootstrap

**Comment by DennisDNguy** [comment]
@claudiubeznea The issue happened to both AT91Bootstrap BOOT.bin and u-boot

**Comment by claudiubeznea** [comment]
@DennisDNguy : it seems you're right, defconfig for bootstrap has been changed in commits:
0b7c66c93b30 ("at91bootstrap: add sama5d27_som1_eksd1_uboot as default defconfig")
adc69febc0e2d ("uboot-at91: changed som1 ek default defconfigs")

It should have been using SDMMC0 related defconfig.

**Comment by DennisDNguy** [comment]
@claudiubeznea Which repository should I checkout and test? 
Is it: git clone https://git.openwrt.org/openwrt/openwrt.git
git checkout master
Thanks and regards

**Comment by DennisDNguy** [comment]
I checked out the master branch from: git clone https://git.openwrt.org/openwrt/openwrt.git
Configured:
Target System (Microchip (Atmel AT91))
Subtarget (SAMA5 boards(Cortex-A5))
Target Profile (Microchip SAMA5D27 SOM1 Ek)

But got the following error:
AT91Bootstrap 4.0.3 (2022-07-28 15:46:33)

SDHC: fix in place for SAMA5D2 SiP VDDSDMMC over-consumption errata
SD/MMC: Image: Read file u-boot.bin to 0x23f00000
MMC: ADMA supported
*** FATFS: f_open, filename: [u-boot.bin]: error
SD/MMC: Failed to load image

**Comment by claudiubeznea** [comment]
@DennisDNguy : repository https://git.openwrt.org/openwrt/openwrt.git with patches in this pull request on top: https://github.com/openwrt/openwrt/pull/10347

**Comment by DennisDNguy** [comment]
@claudiubeznea I checked out the lasted master branch from repository https://git.openwrt.org/openwrt/openwrt.git
I still get the error:
AT91Bootstrap 4.0.3 (2022-08-05 16:31:24)

SDHC: fix in place for SAMA5D2 SiP VDDSDMMC over-consumption errata
SD/MMC: Image: Read file u-boot.bin to 0x23f00000
MMC: ADMA supported
SDHC: Error: No Card Inserted
*** FATFS: f_open, filename: [u-boot.bin]: error
SD/MMC: Failed to load image

I checked the local:
dnguyen@1C6WXT2:~/owrt220300master/openwrt$ git pull
Already up to date.
dnguyen@1C6WXT2:~/owrt220300master/openwrt$ git branch
* master
dnguyen@1C6WXT2:~/owrt220300master/openwrt$ git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
dnguyen@1C6WXT2:~/owrt220300master/openwrt$

**Comment by DennisDNguy** [comment]
I removed the following from target/linux/at91/image/sama5.mk and got the below error:
  $(if $(findstring sama5d27-som1-ek,$@), \
      mcopy -i $@.boot \
          $(BIN_DIR)/u-boot-$(DEVICE_DTS:at91-%=%)_mmc1/u-boot.bin \
          ::u-boot.bin
      mcopy -i $@.boot \
          $(BIN_DIR)/at91bootstrap-$(DEVICE_DTS:at91-%=%)sd1_uboot/at91bootstrap.bin \
          ::BOOT.bin,


mcopy -i /home/dnguyen/owrt220300master/openwrt/build_dir/target-arm_cortex-a5+vfpv4_musl_eabi/linux-at91_sama5/tmp/openwrt-at91-sama5-microchip_sama5d27-som1-ek-ext4-sdcard.img.gz.boot /home/dnguyen/owrt220300master/openwrt/bin/targets/at91/sama5/u-boot-sama5d27_som1_ek_mmc/u-boot.bin ::u-boot.bin
mcopy -i /home/dnguyen/owrt220300master/openwrt/build_dir/target-arm_cortex-a5+vfpv4_musl_eabi/linux-at91_sama5/tmp/openwrt-at91-sama5-microchip_sama5d27-som1-ek-ext4-sdcard.img.gz.boot /home/dnguyen/owrt220300master/openwrt/bin/targets/at91/sama5/at91bootstrap-sama5d27_som1_eksd_uboot/at91bootstrap.bin ::BOOT.bin
/home/dnguyen/owrt220300master/openwrt/bin/targets/at91/sama5/at91bootstrap-sama5d27_som1_eksd_uboot/at91bootstrap.bin: No such file or directory
make[5]: *** [Makefile:81: /home/dnguyen/owrt220300master/openwrt/build_dir/target-arm_cortex-a5+vfpv4_musl_eabi/linux-at91_sama5/tmp/openwrt-at91-sama5-microchip_sama5d27-som1-ek-ext4-sdcard.img.gz] Error 1

**Comment by DennisDNguy** [comment]
@claudiubeznea I checked out the latest master branch from repository https://git.openwrt.org/openwrt/openwrt.git 

AT91Bootstrap 4.0.3 (2022-08-05 16:31:24)

SDHC: fix in place for SAMA5D2 SiP VDDSDMMC over-consumption errata
SD/MMC: Image: Read file u-boot.bin to 0x23f00000
MMC: ADMA supported
SDHC: Error: No Card Inserted
*** FATFS: f_open, filename: [u-boot.bin]: error
SD/MMC: Failed to load image

**Comment by DennisDNguy** [comment]
@claudiubeznea I got following error, after changing: package/boot/at91bootstrap/Makefile, package/boot/uboot-at91/Makefile, and target/linux/at91/image/sama5.mk files:
mcopy -i /home/dnguyen/owrt220300master/openwrt/build_dir/target-arm_cortex-a5+vfpv4_musl_eabi/linux-at91_sama5/tmp/openwrt-at91-sama5-microchip_sama5d27-som1-ek-ext4-sdcard.img.gz.boot /home/dnguyen/owrt220300master/openwrt/build_dir/target-arm_cortex-a5+vfpv4_musl_eabi/linux-at91_sama5/microchip_sama5d27-som1-ek-fit-zImage.itb ::microchip_sama5d27-som1-ek-fit.itb
mcopy -i /home/dnguyen/owrt220300master/openwrt/build_dir/target-arm_cortex-a5+vfpv4_musl_eabi/linux-at91_sama5/tmp/openwrt-at91-sama5-microchip_sama5d27-som1-ek-ext4-sdcard.img.gz.boot /home/dnguyen/owrt220300master/openwrt/bin/targets/at91/sama5/at91bootstrap-sama5d27_som1_eksd1_uboot/at91bootstrap.bin ::BOOT.bin
/home/dnguyen/owrt220300master/openwrt/bin/targets/at91/sama5/at91bootstrap-sama5d27_som1_eksd1_uboot/at91bootstrap.bin: No such file or directory

**Comment by DennisDNguy** [comment]
Today August 07, 2022, I downloaded the 22.03.0 rc6:
https://downloads.openwrt.org/snapshots/targets/at91/sama5/openwrt-at91-sama5-microchip_sama5d27-som1-ek-ext4-sdcard.img.gz
![image](https://user-images.githubusercontent.com/5569521/183317177-1f5c3ec0-de9a-4b5e-988c-8885e62d8cae.png)
But still got the error:
AT91Bootstrap 3.10.4 (2022-08-06 19:32:35)

SDHC: fix in place for SAMA5D2 SoM VDDSDMMC over-consumption errata
SD/MMC: Image: Read file u-boot.bin to 0x23f00000
MMC: ADMA supported
SDHC: Error: No Card Inserted
*** FATFS: f_open, filename: [u-boot.bin]: error
SD/MMC: Failed to load image

**Comment by DennisDNguy** [comment]
@hauke @claudiubeznea 
I compared: package/boot/at91bootstrap/Makefile, package/boot/uboot-at91/Makefile, and target/linux/at91/image/sama5.mk files, between v19.07.3 and v21.02.3 and later,
The defines and usage did not changes. There was no change in those 3 files that related to SD/MMC0/1, both used sama5d27_som1_eksd1, sama5d27_som1_ek_mmc1.
The issue could be somewhere else.

**Comment by DennisDNguy** [comment]
How can we find the changes that related to the SD/MMC0/1 between v19.07.9 and v21.02.0 openWRT version?

**Comment by DennisDNguy** [comment]
Did the following changes apply to v21.02.0 version? (Did not apply up to 19.07.10?)
@DennisDNguy : it seems you're right, defconfig for bootstrap has been changed in commits:
0b7c66c ("at91bootstrap: add sama5d27_som1_eksd1_uboot as default defconfig")
adc69fe ("uboot-at91: changed som1 ek default defconfigs")

It should have been using SDMMC0 related defconfig. I'm having a look.

**Comment by DennisDNguy** [comment]
I made some progress. I changed the target/linux/at91/image/sama5.mk and being able to build and load the image onto the micro SD card. The bootstrap and uboot can see the SD/MMC0.
However, it failed to find the kernel.
AT91Bootstrap 4.0.3 (2022-08-09 11:57:39)

SDHC: fix in place for SAMA5D2 SiP VDDSDMMC over-consumption errata
SD/MMC: Image: Read file u-boot.bin to 0x23f00000
MMC: ADMA supported
SD: Card Capacity: High or Extended
SD: Specification Version 3.0X
SD/MMC: Done to load image

<debug_uart>


U-Boot 2022.01-linux4sam-2022.04-OpenWrt-r20266-cf110404e3 (Aug 09 2022 - 11:57:39 +0000)

CPU: SAMA5D27 1G bits DDR2 SDRAM
Crystal frequency:       24 MHz
CPU clock        :      492 MHz
Master clock     :      164 MHz
DRAM:  128 MiB
MMC:   sdio-host@a0000000: 0, sdio-host@b0000000: 1
Loading Environment from FAT... OK
In:    serial@f8020000
Out:   serial@f8020000
Err:   serial@f8020000
Net:   eth0: ethernet@f8008000
Hit any key to stop autoboot:  0
MMC: no card present
Couldn't find partition mmc 1:1
Can't set block device
Wrong Image Format for bootm command
**ERROR: can't get kernel image!**
=>

**Comment by DennisDNguy** [comment]
@claudiubeznea Could you please help to solve the following error:
Wrong Image Format for bootm command
ERROR: can't get kernel image!
Thanks,
Dennis

**Comment by DennisDNguy** [comment]
@claudiubeznea 
Which u-boot default arguments should I set to launch the kernel image?

Below are u-boot messages:
U-Boot 2020.01-linux4sam-2020.04 (Apr 16 2022 - 12:59:34 +0000)
CPU: SAMA5D27 1G bits DDR2 SDRAM
Crystal frequency:    24 MHz
CPU clock    :   492 MHz
Master clock   :   164 MHz
DRAM: 128 MiB
MMC:  sdio-host@a0000000: 0, sdio-host@b0000000: 1
Loading Environment from FAT... OK
In:  serial@f8020000
Out:  serial@f8020000
Err:  serial@f8020000
Net:  eth0: ethernet@f8008000
Hit any key to stop autoboot: 0
MMC: no card present

Wrong Image Format for bootm command
ERROR: can't get kernel image!

=> printenv
board=microchip_sama5d27-som1-ek
board_name=atmel,sama5d27-som1-ek
bootargs=console=ttyS0,115200 earlyprintk root=/dev/mmcblk1p2 rw rootwait rootfstype=ext4
bootargsd2=console=ttyS0,115200 earlyprintk root=/dev/mmcblk1p2 rw rootwait rootfstype=ext4
bootargsxx=console=ttyS0,115200 earlyprintk root=/dev/mmcblk0p2 rw rootwait rootfstype=ext4
bootcmd=run setbootargs; run fatload_mmc; bootm 0x21000000
bootdelay=1
ethact=gmac0
ethaddr=e8:eb:1b:35:92:7c
fatload_mmc=if test ${board_name} = atmel,sama5d2-xplained || test ${board_name} = atmel,sama5d27-som1-ek; then fatload mmc 1:1 0x21000000 ${board}-fit.itb; else fatload mmc 0:1 0x21000000 ${board}-fit.itb; fi
fdtcontroladdr=27b6a468
setbootargs=if test ${board_name} = atmel,sama5d2-xplained || test ${board_name} = atmel,sama5d27-som1-ek; then setenv bootargs ${bootargsd2}; else setenv bootargs ${bootargsxx}; fi
stderr=serial@f8020000
stdin=serial@f8020000
stdout=serial@f8020000

Environment size: 936/16380 bytes
=>

Thanks,
Dennis

**Comment by DennisDNguy** [comment]
@hauke @claudiubeznea 
I made a step further, the kernel started but it stopped after 2 seconds.
After the u-boot ran, I entered the 2 following commands to load the kernel:
=> fatload mmc 0 0x21000000 microchip_sama5d27-som1-ek-fit.itb
4588332 bytes read in 287 ms (15.2 MiB/s)
=> bootm 0x21000000

The kernel started but stopped at:
[    2.145930] mmc0: new ultra high speed SDR104 SDHC card at address 0001
[    2.155480] mmcblk0: mmc0:0001 SD32G 28.9 GiB
[    2.163118]  mmcblk0: p1 p2

Do I need to configure any kernel setting?
I only change these 3 file to configure the SD/MMC0
package/boot/at91bootstrap/Makefile
package/boot/uboot-at91/Makefile
target/linux/at91/image/sama5.mk files

Thanks,
Dennis

**Comment by claudiubeznea** [comment]
@DennisDNguy : can you check the bootargs and make sure you have root=/dev/mmcblk0p2? I missed to change the target/linux/at91/image/uboot-env.txt to proper sdmmc.

PS: sorry for late delay in response I've been out of office for a while.

**Comment by DennisDNguy** [comment]
@claudiubeznea 
it was:
bootargsd2=console=ttyS0,115200 earlyprintk root=/dev/mmcblk1p2 rw rootwait rootfstype=ext4
changed to
bootargsd2=console=ttyS0,115200 earlyprintk root=/dev/mmcblk0p2 rw rootwait rootfstype=ext4
The kernel could finish the boot up.

The u-boot still can not load the kernel. Which settings/arguments do I need to change?
The u-boot stopped at:
 AT91Bootstrap 4.0.3 (2022-08-21 16:52:52)

SDHC: fix in place for SAMA5D2 SiP VDDSDMMC over-consumption errata
SD/MMC: Image: Read file u-boot.bin to 0x23f00000
MMC: ADMA supported
SD: Card Capacity: High or Extended
SD: Specification Version 3.0X
SD/MMC: Done to load image

<debug_uart>


U-Boot 2022.01-linux4sam-2022.04-OpenWrt-r20375-d6994c53cd (Aug 21 2022 - 16:52:52 +0000)

CPU: SAMA5D27 1G bits DDR2 SDRAM
Crystal frequency:       24 MHz
CPU clock        :      492 MHz
Master clock     :      164 MHz
DRAM:  128 MiB
MMC:   sdio-host@a0000000: 0, sdio-host@b0000000: 1
Loading Environment from FAT... OK
In:    serial@f8020000
Out:   serial@f8020000
Err:   serial@f8020000
Net:   eth0: ethernet@f8008000
Hit any key to stop autoboot:  0
MMC: no card present
Couldn't find partition mmc 1:1
Can't set block device
Wrong Image Format for bootm command
ERROR: can't get kernel image!
=>

Thanks,
Dennis

**Comment by DennisDNguy** [comment]
@claudiubeznea 
It looks some statements from the uboot.env file of the device did not run correctly.
Text from the device's uboot.env
bootcmd=run setloadaddr; run setbootargs; run fatload_mmc; bootm ${loadaddr}

I attached the uboot.env of the device:
[uboot.zip](https://github.com/openwrt/openwrt/files/9417964/uboot.zip)

**Comment by DennisDNguy** [comment]
@claudiubeznea 
I found the setting "mmc 0:1" in target/linux/at91/image/uboot-env.txt
fatload_mmc=if test ${board_name} = atmel,sama5d2-xplained || test ${board_name} = atmel,sama5d27-som1-ek || test ${board_name} = microchip,sama7g5ek; then fatload mmc 0:1 ${loadaddr} ${board}-fit.itb; else fatload **mmc 0:1** ${loadaddr} ${board}-fit.itb; fi

**Comment by claudiubeznea** [comment]
@DennisDNguy : great news. So, with this, all good on your side, right?

**Comment by DennisDNguy** [comment]
@claudiubeznea This issue is resolved.
Thanks,
