### ISSUE TITLE
TP-Link Archer VR2600 v1 - Labelled LAN ports on router do not match Switch port numbering

### ISSUE THREAD

**Issue by bill888uk** [openwrt/openwrt#10275]
I flashed 21.02.3 vr2600**v** image to a vr2600 v1 (UK model) and discovered a very minor bug with labelling of the ports.

Labelled LAN port - Switch port (LuCI) - Switch port (/etc/config/network)
LAN**1**  -  LAN 4  -  4
LAN**2**  -  LAN 3  -  3
LAN**3**  -  LAN 2  -  2
LAN**4**  -  LAN 1  -  1

**Update**:  Actually, the wiki page does show a table of LAN and switch port number are inverted. 
https://openwrt.org/toh/tp-link/archer_vr2600_v1#switch_ports_for_vlans

ie. should this be reported as a LuCI bug?

**Comment by chunkeey** [comment]
puh, I think you are on to something.

The original commit for the VR2600 ae79c41286f0d9a97f2641450240ecac5465677d starts with:
> "This router is similar to the C2600. "

And a similiar issue with the C2600 was addressed by:
5889f92f7de2cbd3369826c7834e695e4f5db4be which reordered the ports in the way you describe.
From what I can tell, to fix the numbering it would just require moving the VR2600 to follow C2600 port setup again.

If you are not afraid of compiling and resetting the configuration then this patch should fix the port numbering.

---
```
diff --git a/target/linux/ipq806x/base-files/etc/board.d/02_network b/target/linux/ipq806x/base-files/etc/board.d/02_network
index dc9c11e4ba..dbff854731 100644
--- a/target/linux/ipq806x/base-files/etc/board.d/02_network
+++ b/target/linux/ipq806x/base-files/etc/board.d/02_network
@@ -27,8 +27,7 @@ compex,wpq864 |\
 netgear,d7800 |\
 netgear,r7500 |\
 netgear,r7500v2 |\
-qcom,ipq8064-ap148 |\
-tplink,vr2600v)
+qcom,ipq8064-ap148)
 	ucidef_add_switch "switch0" \
 		"1:lan" "2:lan" "3:lan" "4:lan" "6@eth1" "5:wan" "0@eth0"
 	;;
@@ -61,7 +60,8 @@ nec,wg2600hp3)
 	;;
 netgear,r7800 |\
 netgear,xr500 |\
-tplink,c2600)
+tplink,c2600 |\
+tplink,vr2600v)
 	ucidef_add_switch "switch0" \
 		"1:lan:4" "2:lan:3" "3:lan:2" "4:lan:1" "6@eth1" "5:wan" "0@eth0"
 	;;
```
---
If you want to test this without resetting/losing your configuration and are comfortable with SSH'ing into the router and editing the ```/etc/board.json``` (maybe best to make a backup of that file). Then follow along.

The gist is that you add a ```"index" : Number``` property to each lan port in the the ```/etc/board.json```  file.
The index property "remaps" the switch port and it will show up in Luci at the position you write in there (from 1 to 4).

Look for the "switch0" node (This is from a different device I removed some indents there)

```
"switch0": {
	"enable": true,
	"reset": true,
	"ports": [
                ....
		{
			"index": 4,     <-- that comma is needed so it remains a valid JSON.
                                            This tells Luci+Friends that this is LAN is labeled Port 4
			"num": 1,       <-- the switch chip internal number for the port
			"role": "lan"   <-- only the LAN-Ports (make sure that this matches)
		},
		{
			"index": 3,  <---  same here, add "3" to tell Luci+Friends that this is Port 3
			"num": 2,
			"role": "lan",
		},
                ... continue with num 3 and num 4. They get "index": 2, and "index": 1, .
```
once you saved the changes, you can simply reload the Luci switch page. Your changes should show up instantly.

**Comment by bill888uk** [comment]
Thank you. 

I can confirm editing the board.json file has resolved the LuCI issue for my vr2600

Before
```
		"switch0": {
			"enable": true,
			"reset": true,
			"ports": [
				{
					"num": 1,
					"role": "lan"
				},
				{
					"num": 2,
					"role": "lan"
				},
				{
					"num": 3,
					"role": "lan"
				},
				{
					"num": 4,
					"role": "lan"
				},

```

After editing, by adding **"index": X,** for each LAN port:
```
	"switch": {
		"switch0": {
			"enable": true,
			"reset": true,
			"ports": [
				{
					"index": 4,
					"num": 1,
					"role": "lan"
				},
				{
					"index": 3,
					"num": 2,
					"role": "lan"
				},
				{
					"index": 2,
					"num": 3,
					"role": "lan"
				},
				{
					"index": 1,
					"num": 4,
					"role": "lan"
				},
```

**Comment by bill888uk** [comment]
I briefly tested latest 22.03 snapshot with 'default' openwrt settings.  

I can confirm the port numbering issue within LuCI swconfig menu is fixed with the new commit.

Thank you.
