### ISSUE TITLE
CURLOPT_SSLVERSION error after update to 22.03-SNAPSHOT r19555

### ISSUE THREAD

**Issue by MrBridgeSix** [openwrt/openwrt#10308]
After updating to OpenWrt 22.03-SNAPSHOT r19555 I'm getting this error: `https-dns-proxy[5090]: [F] 1658229960.298536 https-dns-proxy-2021-11-22/src/https_client.c:317 A92D: CURLOPT_SSLVERSION error 4: Error`

Probably related to libcurl4.

**Comment by neheb** [comment]
not relevant here but rather here: https://github.com/openwrt/packages

Will be fixed in a day. Please close.
