### ISSUE TITLE
 Firmware Selector - Request Build - Does not Work.

### ISSUE THREAD

**Issue by shark873** [openwrt/openwrt#10344]
![image](https://user-images.githubusercontent.com/10945499/181353654-79dd1691-6a51-4d7b-8574-095ff5c5f243.png)

As we can see on the imagem above, when requesting an image it does not work...

The only package added was **kmod-igc**.

**Comment by jow-** [comment]
Apparently the server was overloaded, should work again.

**Comment by KosmiK2001** [comment]
Time to open back...
Now, its frozen on 80% image build...endles 80%.... :-(
