### ISSUE TITLE
libwolfssl5.4.0.ee39414e is missing in 22.03-rc5

### ISSUE THREAD

**Issue by fire-burner** [openwrt/openwrt#10365]
I have just installed the 22.03-rc5 on my Archer C50v1 (https://openwrt.org/toh/hwdata/tp-link/tp-link_archer_c50_v1), which is ramips/mt7620 and packages are in mipsel_24kc.
When trying to install wpad-mesh-wolfssl, I get the following error, that the dependency libwolfssl5.4.0.ee39414e cannot be found.
I am also not able to locate it here https://downloads.openwrt.org/releases/22.03.0-rc5/packages/mipsel_24kc/base/
However libwolfssl-benchmark_5.4.0-stable-3_mipsel_24kc.ipk is available here.
In the 22.03-rc5 image libwolfssl5.3.0.ee39414e is integrated, which I am also not able to locate neither in base, luci nor the packages repository.

Error:
```
opkg install wpad-mesh-wolfssl
Unknown package 'wpad-mesh-wolfssl'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libwolfssl5.4.0.ee39414e for wpad-mesh-wolfssl
 * pkg_hash_fetch_best_installation_candidate: Packages for wpad-mesh-wolfssl found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package wpad-mesh-wolfssl.
```
I have just checked another target and was also not able to locate libwolfssl5.4.0.ee39414e in the repository

**Comment by aparcar** [comment]
This issue was fixed via rc6
