### ISSUE TITLE
How does openwrt populate IPv6 default route without receiving router advertisements?

### ISSUE THREAD

**Issue by shotahino** [openwrt/openwrt#10393]
Apologies for the lack of more details. But it appears that openwrt can populate IPv6 default route for it without receiving router advertisements.  This is reported on IPv6 + PPPoE setup. 

openwrt appears to have IPv6 connectivity despite it not seeing RAs. In the packet capture, I see openwrt sent router solicitation 3 times (, which I believe is in accordance with RFC2461), but there are no RAs. So, I am wondering what mechanism openwrt uses to populate default route so it has IPv6 connectivity.

Note that the segment I am looking at is between upstream network and openwrt router. I am _not_ looking at downstream clients.

**Comment by jow-** [comment]
Via PPPoE IPV6CP. Please don't use the issue tracker for support questions.

**Comment by shotahino** [comment]
@jow- Thanks. Posted a question in the openwrt forum - https://forum.openwrt.org/t/how-does-openwrt-set-ipv6-default-route-without-receiving-ras-from-upstream/133916
