### ISSUE TITLE
Support for TP-Link Archer AX73 | AX5400

### ISSUE THREAD

**Issue by K4LCIFER** [openwrt/openwrt#10424]
Does OpenWRT support [this](https://www.tp-link.com/us/home-networking/wifi-router/archer-ax73/) router yet? If not, is it currently under development?

**Comment by mrkiko** [comment]
Hi!
This device is not supported.
BTW, unfortunately the probability of supporting devices like the AX5400 is quite low (due to Broadcom).

**Comment by ynezz** [comment]
This is issue tracker, please use https://forum.openwrt.org for such questions, thanks.
