### ISSUE TITLE
X550 cannot autoneg on 2.5Gbps, on 22.03 with 5.10 kernel. But works well on 21.02.03 with 5.4 Kernel

### ISSUE THREAD

**Issue by Shinwar** [openwrt/openwrt#10459]
logs of 5.10 kernel ixgbe

> [    6.429543] ixgbe: Intel(R) 10 Gigabit PCI Express Network Driver
> [    6.430022] ixgbe: Copyright (c) 1999-2016 Intel Corporation.
> [    6.430722] ixgbe d5f3:00:00.0: can't derive routing for PCI INT B
> [    6.431192] ixgbe d5f3:00:00.0: PCI INT B: no GSI
> [    7.128849] ixgbe d5f3:00:00.0: Multiqueue Enabled: Rx Queue count = 12, Tx Queue count = 12 XDP Queue count = 0
> [    7.227091] ixgbe d5f3:00:00.0: 31.504 Gb/s available PCIe bandwidth (8.0 GT/s PCIe x4 link)
> [    7.338871] ixgbe d5f3:00:00.0: MAC: 4, PHY: 0, PBA No: H86377-005
> [    7.339559] ixgbe d5f3:00:00.0: 9c:69:b4:62:1e:14
> [    7.486511] ixgbe d5f3:00:00.0 eth3: no netdev found for vf serial:32199
> [    7.501344] ixgbe d5f3:00:00.0: Intel(R) 10 Gigabit Network Connection
> [    7.502413] ixgbe a687:00:00.0: can't derive routing for PCI INT A
> [    7.503080] ixgbe a687:00:00.0: PCI INT A: no GSI
> [    8.188504] ixgbe a687:00:00.0: Multiqueue Enabled: Rx Queue count = 12, Tx Queue count = 12 XDP Queue count = 0
> [    8.287099] ixgbe a687:00:00.0: 31.504 Gb/s available PCIe bandwidth (8.0 GT/s PCIe x4 link)
> [    8.398889] ixgbe a687:00:00.0: MAC: 4, PHY: 0, PBA No: H86377-005
> [    8.399589] ixgbe a687:00:00.0: 9c:69:b4:62:1e:15
> [    8.546535] ixgbe a687:00:00.0 eth4: no netdev found for vf serial:32236
> [    8.561377] ixgbe a687:00:00.0: Intel(R) 10 Gigabit Network Connection
> [   10.194047] ixgbe d5f3:00:00.0: registered PHC device on eth3
> [   10.402313] ixgbe a687:00:00.0: registered PHC device on eth4
> [   13.852735] ixgbe a687:00:00.0 eth4: NIC Link is Up 1 Gbps, Flow Control: RX/TX
> [   16.681411] ixgbe d5f3:00:00.0 eth3: NIC Link is Up 1 Gbps, Flow Control: RX/TX

and logs of 5.4  kernel ixgbe

> [    6.195931] ixgbe: Intel(R) 10 Gigabit PCI Express Network Driver - version 5.1.0-k
> [    6.196390] ixgbe: Copyright (c) 1999-2016 Intel Corporation.
> [    6.197028] ixgbe d5f3:00:00.0: can't derive routing for PCI INT B
> [    6.198604] ixgbe d5f3:00:00.0: PCI INT B: no GSI
> [    6.881108] ixgbe d5f3:00:00.0: Multiqueue Enabled: Rx Queue count = 12, Tx Queue count = 12 XDP Queue count = 0
> [    6.979944] ixgbe d5f3:00:00.0: 31.504 Gb/s available PCIe bandwidth (8 GT/s x4 link)
> [    7.091479] ixgbe d5f3:00:00.0: MAC: 4, PHY: 0, PBA No: H86377-005
> [    7.091938] ixgbe d5f3:00:00.0: 9c:69:b4:62:1e:14
> [    7.237214] ixgbe d5f3:00:00.0 eth3: no netdev found for vf serial:32199
> [    7.251504] ixgbe d5f3:00:00.0: Intel(R) 10 Gigabit Network Connection
> [    7.252567] ixgbe a687:00:00.0: can't derive routing for PCI INT A
> [    7.253288] ixgbe a687:00:00.0: PCI INT A: no GSI
> [    7.932332] ixgbe a687:00:00.0: Multiqueue Enabled: Rx Queue count = 12, Tx Queue count = 12 XDP Queue count = 0
> [    8.031515] ixgbe a687:00:00.0: 31.504 Gb/s available PCIe bandwidth (8 GT/s x4 link)
> [    8.143487] ixgbe a687:00:00.0: MAC: 4, PHY: 0, PBA No: H86377-005
> [    8.144050] ixgbe a687:00:00.0: 9c:69:b4:62:1e:15
> [    8.290445] ixgbe a687:00:00.0 eth4: no netdev found for vf serial:32236
> [    8.305270] ixgbe a687:00:00.0: Intel(R) 10 Gigabit Network Connection
> [  512.006592] ixgbe d5f3:00:00.0: registered PHC device on eth3
> [  512.197558] ixgbe a687:00:00.0: registered PHC device on eth4
> [  917.784906] ixgbe a687:00:00.0 eth4: NIC Link is Up 1 Gbps, Flow Control: RX/TX
> [  933.398694] ixgbe d5f3:00:00.0 eth3: NIC Link is Up 2.5 Gbps, Flow Control: RX/TX

**Comment by hauke** [comment]
OpenWrt does not apply any patches on ixgbe, I would suggest to report this regression to the upstream kernel maintainers, this is probably a general problem in the upstream kernel. They can fix it in the Linux stable tree and then OpenWrt will get it automatically.

**Comment by hauke** [comment]
OpenWrt does not apply any patches on ixgbe, I would suggest to report this regression to the upstream kernel maintainers, this is probably a general problem in the upstream kernel. They can fix it in the Linux stable tree and then OpenWrt will get it automatically.

**Comment by abhishek-rawal** [comment]
@Shinwar : I haven't looked into the commits between 5.4 and 5.10 src of ixgbe upstream code. However, the [readme.md of ixgbe](https://downloadmirror.intel.com/738735/readme.txt) says : `By default, devices based on the Intel(R) Ethernet Controller x550 do not advertise 2.5 Gbps or 5 Gbps.` You might have to advertise it : `# ethtool -s <ifname> advertise 0x800000000000`

**Comment by Shinwar** [comment]
> @Shinwar : I haven't looked into the commits between 5.4 and 5.10 src of ixgbe upstream code. However, the [readme.md of ixgbe](https://downloadmirror.intel.com/738735/readme.txt) says : `By default, devices based on the Intel(R) Ethernet Controller x550 do not advertise 2.5 Gbps or 5 Gbps.` You might have to advertise it : `# ethtool -s <ifname> advertise 0x800000000000`

Tried this command and X550 can autoneg to 2.5Gbps again, Thanks
According to https://github.com/torvalds/linux/commit/a296d665eae1e8ec6445683bfb999c884058426a ixgbe of kernel 5.10  introduced suppression of the advertisement of NBASE-T speeds by default. Now X550 in linux works as stupid as it worked in windows

**Comment by shenlijun** [comment]
https://github.com/shenlijun/openwrt-x550-nbase-t
