### ISSUE TITLE
tplink c60 v3 OEM firmware 1.2.0 , it seems to unsupported 

### ISSUE THREAD

**Issue by ChangAnCN** [openwrt/openwrt#10454]
it's OEM firmware version 1.2.0
i'm already try everything i can do.(tftp, uart, etc.)  it's just not work.
is the latest OEM firmware of c60 v3 supported?

**Comment by mrkiko** [comment]
Hi!
Some more informations would be needed: maybe you can provide a dump of the UART output trying with TFTP and/or u-boot commands?

**Comment by ChangAnCN** [comment]
I asked others in the forum and found that this method could not be used to flush the firmware in the latest version..
I got a new tplink C7, it work good, openwrt is the best!!
thanks your reply, have a good day!
