### ISSUE TITLE
18.06.9 Cannot update list + can't install wireguard* packages

### ISSUE THREAD

**Issue by oti4500** [openwrt/openwrt#10519]
I cannot install Wireguard (and the dependecies, mips_24kc packages) to TP-link TL-WR740N with OpenWRT 18.06.9. I have connected wirelessly as WAN connection ('Client mode' wireless), so I can connect to Internet.

I tried to the update list, because i searching wireguard* pacakges, but I got this message:

Downloading http://downloads.openwrt.org/releases/18.06.9/targets/ar71xx/tiny/packages/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/releases/18.06.9/targets/ar71xx/tiny/packages/Packages.gz

Downloading http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/base/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/base/Packages.gz

Downloading http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/luci/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/luci/Packages.gz

Downloading http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/packages/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/packages/Packages.gz

Downloading http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/routing/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/routing/Packages.gz

Downloading http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/telephony/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/telephony/Packages.gz

I tried manually install these packages:
https://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/base/wireguard_1.0.20200611-1_mips_24kc.ipk

https://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/base/wireguard-tools_1.0.20191226-1_mips_24kc.ipk

I got this message:
Collected errors:
 * wfopen: https://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/base/wireguard-tools_1.0.20191226-1_mips_24kc.ipk: No such file or directory.
 * pkg_init_from_file: Failed to extract control file from https://downloads.openwrt.org/releases/18.06.9/packages/mips_24kc/base/wireguard-tools_1.0.20191226-1_mips_24kc.ipk.

While wrote this wiki about wireguard for 18.06.X: https://openwrt.org/packages/pkgdata_owrt18_6/wireguard, no have links.

I must have install Wireguard packages, because i must have this device as wireguard vpn client.

**Comment by jow-** [comment]
Those URLs do work here, likely a local configuration issue on your router, such as defunct DNS. The `wfopn` error is expected as opkg in 18.09 does not support https URLs, use http ones instead.
