### ISSUE TITLE
Tools: broken xxd download link

### ISSUE THREAD

**Issue by KernelErr** [openwrt/openwrt#10555]
Hi, while trying to build Openwrt, I found that download link of xxd seems to be broken. Should we update the link or host the file by the official?

![image](https://user-images.githubusercontent.com/45716019/187326538-00254458-7d7b-4fee-bf6c-5177d6f60744.png)

https://github.com/openwrt/openwrt/blob/c6d6306827e9296faad26981996825ce3e90259d/tools/xxd/Makefile#L8

I found one online with a matching SHA256 hash.

[xxd-1.10.tar.gz](https://github.com/openwrt/openwrt/files/9448781/xxd-1.10.tar.gz)

**Comment by wasdqwerdf** [comment]
in tag v21.03.0，the error is still there

**Comment by ynezz** [comment]
> in tag v21.03.0，the error is still there

Thanks for reminder, I've just prepared following backports:

* 21.02 https://github.com/openwrt/openwrt/pull/10711
* 22.03 https://github.com/openwrt/openwrt/pull/10709

**Comment by ynezz** [comment]
> Thanks for reminder, I've just prepared following backports:

Both are merged now.

**Comment by thagabe** [comment]
Hopefully this will be merged soon and new releases for 21.02 and 22.03 will be out soon.

**Comment by ynezz** [comment]
> Hopefully this will be merged soon

Should be merged, so the fix is just one `git pull` away.

> and new releases for 21.02 and 22.03 will be out soon.

AFAIK this affects only folks compiling from sources, so they shouldn't have a problem to do `git pull` or `git cherry-pick` to get the fix. Or do I miss something here?

**Comment by xiaopang0v0** [comment]
In fact, this source is not invalid, it just blocks http access.
Just change http to https to download normally
