### ISSUE TITLE
How to make my openwrt system support Ethernet Controller I226-V?

### ISSUE THREAD

**Issue by Misaka15535** [openwrt/openwrt#10567]
i225-v is supported in the new version, and it seems that the old version can also be achieved by installing kmod-igc. What about i226-v?

**Comment by pkgadd** [comment]
Is this a question or a bug report (this is a bugtracker, not a support channel)?

While details vary a bit on the exact hardware (I226-V vs. I226-LM vs. I226-IT), I226-V should be supported in kernel v5.10 (22.03~) but not v5.4 (21.02.x).

**Comment by lutao114** [comment]
5.4.238 内核，openwrt21.02版本，已经安装了kmod-igc，依然无法驱动i226，是内核版本的原因吗
