### ISSUE TITLE
OpenWRT 22.03.0 Custom Build Prevents luci from Listening

### ISSUE THREAD

**Issue by Ryan-Goldstein** [openwrt/openwrt#10629]
For TP-LINK WR902AC v1, customizing the firmware to remove ppp and ppp-mod-pppoe, causes luci to not listen for connections.

1. Go to https://firmware-selector.openwrt.org/?version=22.03.0&target=ath79%2Fgeneric&id=tplink_tl-wr902ac-v1
2. Expand `Customize installed packages`
3. Delete `ppp ppp-mod-pppoe`
4. Press `REQUEST BUILD`
5. Download the `SYSUPGRADE` build and flash over the standard 22.03.0 using luci’s sysupgrade.
6. When the router boots up, navigating to the gateway IP results in a failed connection.

Flashing the standard 22.03.0 sysupgrade build through ssh restores luci functionality.

**Comment by jow-** [comment]
The customized package list does not contain "luci" or "luci-ssl" by default, you do need to add it.
