### ISSUE TITLE
22.03 lantiq xrx200 passwordless ssh not working.

### ISSUE THREAD

**Issue by mbunal** [openwrt/openwrt#10652]
in 21.02 everting was working properly. after upgrade to 22.03, passwordless ssh is not working anymore. is there a workaround for this?

**Comment by zorun** [comment]
Please post the version of your SSH client (`ssh -V`), the output of `ssh -v root@$your_router`, and specify which kind of SSH key you are using. Dropbear is probably more strict now.

**Comment by mbunal** [comment]
i just remove and install again dropbear. and it working. anyway thanks...
