### ISSUE TITLE
On TP Link Archer C50 V4 Wi-Fi is disabled by default 

### ISSUE THREAD

**Issue by erayrafet** [openwrt/openwrt#10660]
Running 22.03, after a reset, Wi-Fi comes disabled by default. Wired Ethernet connection is required to configure the router settings. It's tricky with modern laptops not having Ethernet ports.

**Edit:** _Upon doing further research, seems like this is the way OpenWRT is set up by default for security reasons. Though, I'd rather have the convenience of wifi enabled by default. Anyone flashing a custom router firmware would know better to set up passwords._

**Comment by musashino205** [comment]
I recommend building a custom image with customized config files.
see: https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem#custom_files

**Comment by erayrafet** [comment]
> I recommend building a custom image with customized config files. see: https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem#custom_files

I am very new to OpenWRT, so kinda seems complicated with a very high chance of risk. If I build my own image once, then upgrade with an official build, my default conf with wifi will be gone, right?

**Comment by castillofrancodamian** [comment]
Yes.

**Comment by Openwrtfunboy** [comment]
Buy usb-ethernet adapter. It cost 2$ if u buy used.

**Comment by Openwrtfunboy** [comment]
Easiest way for you bro
