### ISSUE TITLE
Linksys EA8300 USB Device not loading drivers

### ISSUE THREAD

**Issue by Admiral-AI** [openwrt/openwrt#10681]
My router information:
Model | Linksys EA8300 (Dallas)
Architecture | ARMv7 Processor rev 5 (v7l)
Target Platform | ipq40xx/generic
Firmware Version | OpenWrt 21.02.3 r16554-1d4dea6d4f / LuCI openwrt-21.02 branch git-22.083.69138-0a0ce2a
Kernel Version | 5.4.188

I have been trying to add a external USB drive for SFTP access, the drives reads and writes as expected and the speeds are normal. However whenever I restart the router, the drive does not auto remount even with fstab preconfigured. Several others have had the same issue here: [https://forum.openwrt.org/t/linksys-ea8300-usb-drive-auto-mount-on-reboot/79868/3](url). I have done some diagnostics below:

dmesg upon adding the drive:
> [ 2023.050096] usb 1-1: new high-speed USB device number 5 using xhci-hcd

lsusb shows device on bus 1
> root@OpenWrt:~# lsusb
> Bus 002 Device 001: ID 1d6b:0003 Linux 5.4.188 xhci-hcd xHCI Host Controller
> Bus 004 Device 001: ID 1d6b:0003 Linux 5.4.188 xhci-hcd xHCI Host Controller
> Bus 001 Device 005: ID 152d:0562 SSK SSK Storage
> Bus 001 Device 001: ID 1d6b:0002 Linux 5.4.188 xhci-hcd xHCI Host Controller
> Bus 003 Device 001: ID 1d6b:0002 Linux 5.4.188 xhci-hcd xHCI Host Controller

lsubs -t shows no driver for the drive at device 5:
> root@OpenWrt:~# lsusb -t
> /:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/0p, 5000M
> /:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 480M
> /:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 5000M
> /:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 480M
>     |__ Port 1: Dev 5, If 0, Class=, Driver=, 480M

confirmed usb drivers for all variations of usb are loaded
> root@OpenWrt:~# opkg list-installed | grep usb
> kmod-usb-core - 5.4.188-1
> kmod-usb-dwc3 - 5.4.188-1
> kmod-usb-dwc3-qcom - 5.4.188-1
> kmod-usb-ehci - 5.4.188-1
> kmod-usb-ledtrig-usbport - 5.4.188-1
> kmod-usb-ohci - 5.4.188-1
> kmod-usb-ohci-pci - 5.4.188-1
> kmod-usb-storage - 5.4.188-1
> kmod-usb-uhci - 5.4.188-1
> kmod-usb2 - 5.4.188-1
> kmod-usb2-pci - 5.4.188-1
> kmod-usb3 - 5.4.188-1
> libusb-1.0-0 - 1.0.24-4
> usbids - 0.359-1
> usbutils - 013-2

info on usb "hub"
> root@OpenWrt:~# hub-ctrl -v
> Hub #0 at 002:001
>  INFO: ganged switching.
>  WARN: Port indicators are NOT supported.
>  Hub Port Status:
> Hub #1 at 004:001
>  INFO: ganged switching.
>  WARN: Port indicators are NOT supported.
>  Hub Port Status:

trying to control ports:

> root@OpenWrt:~# hub-ctrl -h 0 -p 0

> root@OpenWrt:~# hub-ctrl -h 1 -p 0
> failed to control.
> : Broken pipe

**Comment by MissionControlFreak** [comment]
Edit: may possibly be due to NTFS, going to try EXT
