### ISSUE TITLE
F9K1109v1 to boot on 21.02 ,22.03 and recent trunk but got it work for trunk

### ISSUE THREAD

**Issue by nicefile** [openwrt/openwrt#10787]
I think F9K1109v1 should be removed from supported devices due problem with booting images <1.5MB (info in toh)
21.02.02 is 1.7MB
22.03 is 2MB
There will  be no permanent solution unless bootloader change .
Fallowing changes made me boot recent trunk.
rt3883.mk
+$(Device/uimage-lzma-loader)
+KERNEL := kernel-bin | append-dtb | lzma -d10 | uImage lzma

in .config file kernel strip was nesesery. Final image is now 1.8MB and boot my device .

Also last stable image that boot is 19.07.10 as is <1.5MB . My device is marked F9K1103v1 on it's backplate.

**Comment by xabolcs** [comment]
See related issue: #10968
