### ISSUE TITLE
how can i change gpio1_mode use by register with my c project

### ISSUE THREAD

**Issue by xjlovelearning** [openwrt/openwrt#10826]
somebody say linux has a "reg" tool to use,but i can not find it

**Comment by 981213** [comment]
Closed because we use GitHub issues as a bug tracker for reporting bugs of the OpenWrt project and this isn't a bug.
BTW there's no such a "reg" tool in linux. There's a reg tool in the proprietary SDK from Mediatek which can only be used within that SDK itself.
