### ISSUE TITLE
OpenWrt for TP-Link AX50

### ISSUE THREAD

**Issue by ethersloth** [openwrt/openwrt#10861]
I know OpenWRT doesn't currently support this router but I think it's possible since the firmware it currently runs is based on OpenWRT. I've done a lot of searching around and it looks like those who have attempted before me gave up. I don't expect someone else to do this for me, I just need to know where to start, what to google, etc. I can get to the point where I have make menuconfig open but I think this device requires the xrx500 subtarget and it's not in the dropdown. Please help.

**Comment by pkgadd** [comment]
This is a bugtracker, not a wishlist collection for new hardware support. If you want to see it supported, you'll either have to do the porting work yourself or hope for someone else wanting to do this work.

Aside from that, chances for Maxlinear (ex-Intel, ex-lantiq) WAV654A0 wireless to work are just about zero, the older WAV300 has been around for about a decade now and remains unsupportable as well.

**Comment by ethersloth** [comment]
I was planning on doing the porting work, just looking for advice on where to start.

**Comment by pkgadd** [comment]
As mentioned, the wireless side is very unlikely to ever be supportable. GRX350 SOC support isn't available in OpenWrt either, so you'd have 'quite a lot' of efforts in front of you (you might find hints about previous work on this on the forum, albeit that is more targeted at modem support in combination with other (ipq4019) SOCs in mind); expect month+ of work.
