### ISSUE TITLE
.github/workflows/tools.yml: push-tools-container will fail when github username contains uppercase letters

### ISSUE THREAD

**Issue by InsaneKnight** [openwrt/openwrt#10880]
@aparcar 
The current workflow defined in .github/workflows/tools.yml will fail on forked repositories of contributers whose github username contains uppercase letters.

More specifically, `push-tools-container` will fail on the step `Build and push`, as seen in [my case](https://github.com/InsaneKnight/openwrt/actions/runs/3172298911/jobs/5166849589#logs).

A workaround mentioned in https://github.com/orgs/community/discussions/27086 may be useful.

**Comment by aparcar** [comment]
Mind creating a PR?

**Comment by InsaneKnight** [comment]
Done in #10883.

**Comment by Ansuel** [comment]
Fixed with c27b439
