### ISSUE TITLE
ujail: failed to load the .dynamic section from binary

### ISSUE THREAD

**Issue by zonyitoo** [openwrt/openwrt#10933]
If run a static-linked library with `proc_add_jail`, it will fail with `ujail: failed to load the .dynamic section from ...`

Example script:

```bash
if [ -x /sbin/ujail -a -e ${SHADOWSOCKS_CAPABILITIES_CONFIG_PATH} ]; then
            procd_add_jail shadowsocks log
            procd_set_param user shadowsocks
            procd_set_param group shadowsocks
            procd_set_param capabilities ${SHADOWSOCKS_CAPABILITIES_CONFIG_PATH}
            procd_set_param no_new_privs 1
            procd_set_param command ${SHADOWSOCKS_COMMAND}
fi
```

Specifically the value of `SHADOWSOCKS_COMMAND` is: `/usr/local/bin/sslocal -c /usr/local/etc/shadowsocks.json --log-without-time --log-config /usr/local/etc/shadowsocks.log.yaml --udp-max-associations 4192 --outbound-fwmark 255`, which is a static-linked binary:

```
$ ldd /usr/local/bin/sslocal
ldd: /usr/local/bin/sslocal: Not a valid dynamic program
```

It works while running directly with `/sbin/ujail`:

```
$ /sbin/ujail -U shadowsocks -c -C /etc/capabilities/shadowsocks.json -n shadowsocks -- /usr/local/bin/sslocal -c /usr/local/etc/shadowsocks.json --log-without-time --log-config /usr/local/etc/shadowsocks.log.yaml --udp-max-associations 4192 --outbound-fwmark 255
```

But fail exactly the same when I added `-r` or `-w`:

```
$ /sbin/ujail -r /usr/local/etc/shadowsocks.json -U shadowsocks -c -C /etc/capabilities/shadowsocks.json -n shadowsocks -- /usr/local/bin/sslocal -c /usr/local/etc/shadowsocks.json --log-without-time --log-config /usr/local/etc/shadowsocks.log.yaml --udp-max-associations 4192 --outbound-fwmark 255
jail: failed to load the .dynamic section from /usr/local/bin/sslocal
jail: failed to load dependencies
```

I just took a glance on the source code, I found that the error was reported when `add_2paths_and_deps` was called:

```c
		case 'r':
			opts.namespace |= CLONE_NEWNS;
			tmp = strchr(optarg, ':');
			if (tmp) {
				*(tmp++) = '\0';
				add_2paths_and_deps(optarg, tmp, 1, 0, 0);
			} else {
				add_path_and_deps(optarg, 1, 0, 0);
			}
			break;
		case 'w':
			opts.namespace |= CLONE_NEWNS;
			tmp = strchr(optarg, ':');
			if (tmp) {
				*(tmp++) = '\0';
				add_2paths_and_deps(optarg, tmp, 0, 0, 0);
			} else {
				add_path_and_deps(optarg, 0, 0, 0);
			}
			break;
```

It will try to search the `.dynamic` section in `elf_load_deps`, which shouldn't be existed in a static-linked binary.

```c
	if (elf_find_section(map, PT_DYNAMIC, &dyn_offset, &dyn_size, NULL)) {
		ERROR("failed to load the .dynamic section from %s\n", path);
		return -1;
	}
```

Why it is required to search the `.dynamic` section when starting processes via `procd_add_jail`? What did `procd` passed to `-r` or `-w`?

**Comment by zonyitoo** [comment]
Proposal: If `PT_DYNAMIC` could not be found in ELF, just give up and `return 0`.

**Comment by champtar** [comment]
> Why it is required to search the `.dynamic` section when starting processes via `procd_add_jail`? What did `procd` passed to `-r` or `-w`?

This is a bug. ujail only mounts what's strictly required. To make it easier it parse elf file to find dependencies, but it seems you're the first one to use ujail with a static binary.

**Comment by zonyitoo** [comment]
> > Why it is required to search the `.dynamic` section when starting processes via `procd_add_jail`? What did `procd` passed to `-r` or `-w`?
> 
> This is a bug. ujail only mounts what's strictly required. To make it easier it parse elf file to find dependencies, but it seems you're the first one to use ujail with a static binary.

lol. Please make a fix release.

**Comment by zonyitoo** [comment]
Could I make a PR? How to contribute to https://git.openwrt.org/?p=project/procd.git

**Comment by zonyitoo** [comment]
Failed to send patch with `git send-email`, couldn't see my email on list: https://patchwork.ozlabs.org/project/openwrt/list/?state=%2A&param=4&page=1&archive=both. NEED HELP.

**Comment by zonyitoo** [comment]
```patch
 jail/elf.c | 16 ++++++++--------
 1 file changed, 8 insertions(+), 8 deletions(-)

diff --git a/jail/elf.c b/jail/elf.c
index 176d046..978fc6e 100644
--- a/jail/elf.c
+++ b/jail/elf.c
@@ -236,18 +236,18 @@ int elf_load_deps(const char *path, const char *map)
  unsigned long load_offset, load_vaddr;
  unsigned long interp_offset;
 
- if (elf_find_section(map, PT_LOAD, &load_offset, NULL, &load_vaddr)) {
- ERROR("failed to load the .load section from %s\n", path);
- return -1;
+ if (elf_find_section(map, PT_INTERP, &interp_offset, NULL, NULL) == 0) {
+ add_path_and_deps(map+interp_offset, 1, -1, 0);
  }
 
- if (elf_find_section(map, PT_DYNAMIC, &dyn_offset, &dyn_size, NULL)) {
- ERROR("failed to load the .dynamic section from %s\n", path);
- return -1;
+ if (elf_find_section(map, PT_LOAD, &load_offset, NULL, &load_vaddr)) {
+ DEBUG("failed to load the .load section from %s\n", path);
+ return 0;
  }
 
- if (elf_find_section(map, PT_INTERP, &interp_offset, NULL, NULL) == 0) {
- add_path_and_deps(map+interp_offset, 1, -1, 0);
+ if (elf_find_section(map, PT_DYNAMIC, &dyn_offset, &dyn_size, NULL)) {
+ DEBUG("failed to load the .dynamic section from %s\n", path);
+ return 0;
  }
 
  int clazz = map[EI_CLASS];
-- 
2.38.0
```

**Comment by zonyitoo** [comment]
Oh, found it: https://patchwork.ozlabs.org/project/openwrt/patch/mailman.24702.1665327237.4154159.openwrt-devel@lists.openwrt.org/

**Comment by zonyitoo** [comment]
@champtar Sorry to bother. I sent the patch 1 week ago, but the status of the patch remain "New". What can I do to push it forward?

**Comment by zonyitoo** [comment]
Ping @dangowrt

**Comment by dangowrt** [comment]
Please submit a patch to the mailing list or open a pull request here on github.

**Comment by zonyitoo** [comment]
I have already submitted a patch [patchwork.ozlabs.org/project/openwrt/patch/mailman.24702.1665327237.4154159.openwrt-devel@lists.openwrt.org](https://patchwork.ozlabs.org/project/openwrt/patch/mailman.24702.1665327237.4154159.openwrt-devel@lists.openwrt.org/).

The source code is not in this repo, so I couldn't open a PR in this repo.

**Comment by dangowrt** [comment]
Oh sorry, I wasn't aware of that. I have now picked up your patch and applied it.
https://github.com/openwrt/openwrt/commit/047d471317b70f00005d03e6f6d21cb403fb6c42
