### ISSUE TITLE
Is mass-upgrades of packages properly supported by OpenWrt?

### ISSUE THREAD

**Issue by olekstomek** [openwrt/openwrt#10952]
The question arises from this issue:: https://github.com/openwrt/luci/issues/5515

**Comment by ynezz** [comment]
This isn't a bug. Please continue the discussion in the OpenWrt forum as this seems more like a general support question.

**Comment by olekstomek** [comment]
OK, I asked [here](https://forum.openwrt.org/t/is-mass-upgrades-of-packages-properly-supported-by-openwrt/139622).

BDW, I found: [Upgrading packages may cause serious problems, including soft-bricking your device!](https://openwrt.org/meta/infobox/upgrade_packages_warning)
