### ISSUE TITLE
ipq806x Linksys EA8500 snapshot: Ethernet switch is dead

### ISSUE THREAD

**Issue by paulcarroty** [openwrt/openwrt#10983]
No connection, zero packets rx/tx, on lan and wan.

**Comment by jaharon** [comment]
I can confirm that this only happens with kernel 5.15.
@Ansuel this happened even before the recent move to 5.15 as the default kernel.
I'm available to debug over wifi (still works) or serial.

**Comment by Ansuel** [comment]
@jaharon thanks for the report... can you provide a boot log and a 
`cat  /sys/kernel/debug/devices_deferred`

**Comment by jaharon** [comment]
Sure,

`cat /sys/kernel/debug/devices_deferred` is empty

Bootlog: [ea8500_5.15_boot.log](https://github.com/openwrt/openwrt/files/9855481/ea8500_5.15_boot.log)

**Comment by Ansuel** [comment]
```
[    3.308228] mdio_bus 37000000.mdio-mii: MDIO device at address 0 is missing.
[    3.309036] mdio_bus 37000000.mdio-mii: MDIO device at address 4 is missing.
```

internal mdio is not working o.o or probably some pin are fked up?

**Comment by Ansuel** [comment]
@jaharon can you also provide a bootlog from 5.10?

**Comment by janaz** [comment]
I had exactly the same issue with kernel 5.15 and found this bug report. Downgrading to kernel v5.10 fixed the problem for me. Here's my 5.10 bootlog 
[ea8500-bootlog-5.10.txt](https://github.com/openwrt/openwrt/files/9855666/ea8500-bootlog-5.10.txt)

**Comment by jaharon** [comment]
Here's mine:
[ea8500_5.10_boot.log](https://github.com/openwrt/openwrt/files/9855802/ea8500_5.10_boot.log)

**Comment by Ansuel** [comment]
can you guys test a custom image? or that would require times?

**Comment by jaharon** [comment]
Can do, but If you have a public branch with patches, I can also test that.

**Comment by jaharon** [comment]
@Ansuel Didn't work
[ea8500_5.15_patch1_boot.log](https://github.com/openwrt/openwrt/files/9855970/ea8500_5.15_patch1_boot.log)


```diff --git a/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts b/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
index 1c6a4bdacd..da779d7b3e 100644
--- a/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
+++ b/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
@@ -10,8 +10,6 @@
        };

        aliases {
-               mdio-gpio0 = &mdio0;
-
                led-boot = &led_power;
                led-failsafe = &led_power;
                led-running = &led_power;

**Comment by Ansuel** [comment]
@jaharon can you replace gmac1 and gmac2 node with the following values? (keep the alias removed)
```
&gmac1 {
	status = "okay";

	phy-mode = "rgmii";
	qcom,id = <1>;
	qcom,phy_mdio_addr = <4>;
	qcom,poll_required = <1>;
	qcom,rgmii_delay = <0>;
	qcom,phy_mii_type = <0>;
	qcom,emulation = <0>;
	qcom,irq = <255>;
	mdiobus = <&mdio0>;

	fixed-link {
		speed = <1000>;
		full-duplex;
	};
};

&gmac2 {
	status = "okay";

	phy-mode = "sgmii";
	qcom,id = <2>;
	qcom,phy_mdio_addr = <0>;	/* none */
	qcom,poll_required = <0>;	/* no polling */
	qcom,rgmii_delay = <0>;
	qcom,phy_mii_type = <1>;
	qcom,emulation = <0>;
	qcom,irq = <258>;
	mdiobus = <&mdio0>;

	fixed-link {
		speed = <1000>;
		full-duplex;
	};
};
```

The configuration in ea8500 is very different from standard... wonder if they did something stupid and didn't connect the internal mdio controller to the switch in some way... if this doesn't work then we have to revert to the slower bitbang driver... (so the solution is always there... it's just strange...)

**Comment by jaharon** [comment]
@Ansuel  Same.
[ea8500_5.15_patch2_boot.log](https://github.com/openwrt/openwrt/files/9856087/ea8500_5.15_patch2_boot.log)



I appreciate the time and effort into supporting this non standard router.
If you have other things to check before (or after) going back to bitbang let me know, even if it is just exploratory.

```diff --git a/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts b/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
index 1c6a4bdacd..c4b9ffb663 100644
--- a/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
+++ b/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
@@ -10,8 +10,6 @@
        };

        aliases {
-               mdio-gpio0 = &mdio0;
-
                led-boot = &led_power;
                led-failsafe = &led_power;
                led-running = &led_power;
@@ -113,16 +111,39 @@
 };

 &gmac1 {
+       status = "okay";
+
+       phy-mode = "rgmii";
+       qcom,id = <1>;
        qcom,phy_mdio_addr = <4>;
        qcom,poll_required = <1>;
        qcom,rgmii_delay = <0>;
+       qcom,phy_mii_type = <0>;
        qcom,emulation = <0>;
+       qcom,irq = <255>;
+       mdiobus = <&mdio0>;
+
+       fixed-link {
+               speed = <1000>;
+               full-duplex;
+       };
 };

-/* LAN */
 &gmac2 {
+       status = "okay";
+
+       phy-mode = "sgmii";
+       qcom,id = <2>;
        qcom,phy_mdio_addr = <0>;       /* none */
        qcom,poll_required = <0>;       /* no polling */
        qcom,rgmii_delay = <0>;
+       qcom,phy_mii_type = <1>;
        qcom,emulation = <0>;
+       qcom,irq = <258>;
+       mdiobus = <&mdio0>;
+
+       fixed-link {
+               speed = <1000>;
+               full-duplex;
+       };
 };

**Comment by Ansuel** [comment]
@jaharon there is one thing to test but it's really strange... imho it's just not connected but ok i'm preparing a patch for swconfig to test that...

**Comment by Ansuel** [comment]
@jaharon actually now that i notice it... on 5.10 we already had the mdio internal thing and it worked correctly... interesting.... also the error is from mdio not from swconfig so wonder if there is something wrong there?

**Comment by Ansuel** [comment]
@jaharon can you give me output of `ls /sys/class/mdio_bus/37000000.mdio-mii`

**Comment by jaharon** [comment]
@Ansuel 
5.10
```
ls /sys/class/mdio_bus/37000000.mdio-mii
37000000.mdio-mii:00  37000000.mdio-mii:04  device                of_node               statistics            subsystem             uevent
```
5.15 - with patch2
```
ls /sys/class/mdio_bus/37000000.mdio-mii
device      of_node     statistics  subsystem   uevent
```
Let me know if you want me to check it with no patches.

**Comment by Ansuel** [comment]
@jaharon i need to investigate this with a clear mind and here is 3 am... hope it's ok for you if we can continue this tomorrow.

thanks for helpming me bisecting this

**Comment by Ansuel** [comment]
@jaharon `cat /sys/class/mdio_bus/37000000.mdio-mii/statistics/*`

**Comment by Ansuel** [comment]
anyway i would first test if gpio bitbang works just to understand if there is a regression in the mdio driver or in the system itself.

you need to add this to mdio node

```
		compatible = "virtual,mdio-gpio";
		gpios = <&qcom_pinmux 1 GPIO_ACTIVE_HIGH>,
			<&qcom_pinmux 0 GPIO_ACTIVE_HIGH>;
```

**Comment by jaharon** [comment]
@Ansuel 

[mdio_stats_5_15.txt](https://github.com/openwrt/openwrt/files/9863188/mdio_stats_5_15.txt)
[mdio_stats_5_10.txt](https://github.com/openwrt/openwrt/files/9863189/mdio_stats_5_10.txt)

The switch still does not work with the following patch and `/sys/class/mdio_bus/37000000.mdio-mii/statistics/*` does not exist:
```diff --git a/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts b/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
index 1c6a4bdacd..191ff4d3b4 100644
--- a/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
+++ b/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
@@ -107,6 +107,10 @@
 };

 &mdio0 {
+       compatible = "virtual,mdio-gpio";
+       gpios = <&qcom_pinmux 1 GPIO_ACTIVE_HIGH>,
+               <&qcom_pinmux 0 GPIO_ACTIVE_HIGH>;
+
        phy4: ethernet-phy@4 {
                reg = <4>;
        };
```

**Comment by Ansuel** [comment]
@jaharon with the virtual mdio can you give me also the bootlog?

**Comment by jaharon** [comment]
@Ansuel Sure
[ea8500_5.15_virtual_mdio_boot.log](https://github.com/openwrt/openwrt/files/9863357/ea8500_5.15_virtual_mdio_boot.log)

**Comment by robimarko** [comment]
It would be good to compare GPIO levels on 5.10 and 5.15, maybe this thing has reset GPIO for the switch

**Comment by Ansuel** [comment]
@robimarko yep that is also my idea... we are silently changing a gpio and the switch is stuck in reset... but any idea how to check that from a running system ?

**Comment by robimarko** [comment]
You can just `cat /sys/kernel/debug/gpio` that will give you all of the GPIO-s and their level

**Comment by jaharon** [comment]
[ea8500_gpios_5.10.txt](https://github.com/openwrt/openwrt/files/9870208/ea8500_gpios_5.10.txt)
[ea8500_gpios_5.15.txt](https://github.com/openwrt/openwrt/files/9870209/ea8500_gpios_5.15.txt)


```diff

diff ea8500_gpios_5.10.txt ea8500_gpios_5.15.txt
6c6
<  gpio2   : in  high func0 2mA pull down
---
>  gpio2   : in  low  func0 2mA pull down
56c56
<  gpio52  : in  low  func2 8mA no pull
---
>  gpio52  : in  high func2 8mA no pull
63,64c63,64
<  gpio59  : in  low  func2 8mA no pull
<  gpio60  : in  low  func2 8mA no pull
---
>  gpio59  : in  high func2 8mA no pull
>  gpio60  : in  high func2 8mA no pull
66,67c66,67
<  gpio62  : in  low  func2 8mA no pull
<  gpio63  : out low  func0 12mA no pull
---
>  gpio62  : in  high func2 8mA no pull
>  gpio63  : out high func0 12mA no pull
```

**Comment by Ansuel** [comment]
we don't have gpio2 in ipq8064 dtsi but aside from gpio63 every other is related to rgmii2... thing we got him?

**Comment by robimarko** [comment]
Well, toggle it during runtime and check with mdio tools if there is something on MDIO bus after that

**Comment by robimarko** [comment]
@jaharon Any chance you can build a image with `kmod-mdio-netlink` and `mdio-tools`?

That would allow toggling the GPIO2 by exporting it in `/sys/class/gpio` and then toggling

**Comment by jaharon** [comment]
@robimarko 
```
ls /sys/class/gpio/
export       gpiochip443  unexport
```
```
echo "445" > /sys/class/gpio/export

echo "out" > /sys/class/gpio/gpio445/direction

echo "1" > /sys/class/gpio/gpio445/value

cat /sys/kernel/debug/gpio
...
 gpio2   : out high func0 2mA pull down
...
```
Still not seeing anything in
```
ls /sys/class/mdio_bus/37000000.mdio-mii
device      of_node     statistics  subsystem   uevent
```

**Comment by robimarko** [comment]
Kernel will not reprobe the MDIO devices, that is why you need mdio-tools to be able to see whats on the MDIO bus when you want

**Comment by jaharon** [comment]
I ran this before and after the gpio2 change, and the output is the same:
```
mdio

37000000.mdio-mii
fixed-0
```
```
mdio 37000000.mdio-mii

 DEV      PHY-ID  LINK
 ```
 ```
mdio fixed-0

 DEV      PHY-ID  LINK 
 ```

**Comment by Ansuel** [comment]
@jaharon you should really restore each gpio to 5.10 value and not just gpio2

**Comment by jaharon** [comment]
I could not change gpio63:
```
echo "506" > /sys/class/gpio/export
ash: write error: Resource busy
```
All the rest were easy to change
```diff
diff ea8500_gpios_5.10.txt ea8500_gpios_5.15_manual_gpio_change.txt
6c6
<  gpio2   : in  high func0 2mA pull down
---
>  gpio2   : out high func0 2mA pull down
56c56
<  gpio52  : in  low  func2 8mA no pull
---
>  gpio52  : out low  func0 8mA no pull
63,64c63,64
<  gpio59  : in  low  func2 8mA no pull
<  gpio60  : in  low  func2 8mA no pull
---
>  gpio59  : out low  func0 8mA no pull
>  gpio60  : out low  func0 8mA no pull
66,67c66,67
<  gpio62  : in  low  func2 8mA no pull
<  gpio63  : out low  func0 12mA no pull
---
>  gpio62  : out low  func0 8mA no pull
>  gpio63  : out high func0 12mA no pull
```
[ea8500_gpios_5.15_manual_gpio_change.txt](https://github.com/openwrt/openwrt/files/9875868/ea8500_gpios_5.15_manual_gpio_change.txt)

No change using the mdio command.

**Comment by robimarko** [comment]
Can you enable `CONFIG_KERNEL_DEVMEM`, `CONFIG_BUSYBOX_CUSTOM` and `CONFIG_BUSYBOX_CONFIG_DEVMEM`.

Then run the following script: https://raw.githubusercontent.com/marxfang/ipq807x-spf100-cs/master/chipcode/NHSS.QSDK.10.0/apss_proc/out/proprietary/QSDK-Base/gpio-debug/qca/feeds/qca-platform-utils/gpio-debug/files/gpio-debug-ipq806x.sh

Make sure to pass the all argument, so: `./gpio-debug-ipq806x.sh all`

That will tell us if the desired pinmuxing is actually being set

**Comment by jaharon** [comment]
@robimarko NP - [ea8500_gpio-debug_5_15.txt](https://github.com/openwrt/openwrt/files/9881183/ea8500_gpio-debug_5_15.txt)

**Comment by robimarko** [comment]
@jaharon Any chance you can do the same with 5.10?

Honestly, MDIO pins that set no pull-up on are weird

**Comment by jaharon** [comment]
@robimarko [ea8500_gpio-debug_5_10.txt](https://github.com/openwrt/openwrt/files/9881512/ea8500_gpio-debug_5_10.txt)
no diff between ea8500_gpio-debug_5_10.txt and ea8500_gpio-debug_5_15.txt

**Comment by robimarko** [comment]
@jaharon Thanks for the patience, but nothing looks out of the ordinary.

I am running out of ideas

**Comment by jaharon** [comment]
@robimarko I understand. Thanks heaps!

**Comment by Ansuel** [comment]
@jaharon I'm pretty busy in these days so I would ask you if you can use a stable 22.03 image while i think of possible cause... think for now i will have to flag the target as broken but this definitely have to be fixed. Hope it's not a problem for you.

**Comment by jaharon** [comment]
@Ansuel All good. Ping me if you need me.

**Comment by robimarko** [comment]
@jaharon Can you send me the 5.10 and 5.15 images so I dont have to build them myself?

I want to compare the generated DTB-s

**Comment by jaharon** [comment]
@robimarko Sure, emailed them to you.

**Comment by jaharon** [comment]
@robimarko This might be beneficial:

I used ```device-tree-compiler```  
to convert 
```build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/image-qcom-ipq8064-ea8500.dtb```
 to
  ```image-qcom-ipq8064-ea8500.dts```

using 
```i="image-qcom-ipq8064-ea8500.dtb";  dtc -I dtb -O dts "$i" -o "`echo $i | sed -e s'/\.dtb/\.dts/'`"```

[image-qcom-ipq8064-ea8500_5_10.dts.txt](https://github.com/openwrt/openwrt/files/9895269/image-qcom-ipq8064-ea8500_5_10.dts.txt)

[image-qcom-ipq8064-ea8500_5_15.dts.txt](https://github.com/openwrt/openwrt/files/9895270/image-qcom-ipq8064-ea8500_5_15.dts.txt)

The diff is quite large 
[ea8500_dts_diff_5_10_vs_5_15.txt](https://github.com/openwrt/openwrt/files/9895289/ea8500_dts_diff_5_10_vs_5_15.txt)

**Comment by paulcarroty** [comment]
Thanks all for digging in, found something strange in latest dts diff:

```
< 			mdio0_pins {
< 				phandle = <0x28>;
---
> 			mdio0-pins {
> 				phandle = <0x2d>;
```


```
< 	smem {
< 		compatible = "qcom,smem";
< 		memory-region = <0x2d>;
< 		hwlocks = <0x2e 0x03>;
< 	};
```

**Comment by robimarko** [comment]
You cant really diff directly as a lot of nodes got reordered, I looked at the 5.15 vs 5.10 and only difference I could spot is SPC got disabled, but that doesn't really have anything to do with MDIO.

**Comment by Ansuel** [comment]
@paulcarroty @jaharon I wonder if you guys can do something crazy... I can build a fw for each kernel version from 5.10 to 5.15 but i need to ask you guys if you can test them...

Is it a problem or it's too much to ask? Ideally they should be tested with initramfs so serial can be required (but we can sort a way to make it optional)

I would really like to fix this as currently also EA7500 is broken (as I suspected and I was right with also disabling that on master)

**Comment by jaharon** [comment]
@Ansuel Not a problem. Send away.

**Comment by Ansuel** [comment]
@jaharon sooo you can test initramfs with serial? Just confirming that if i can send initramfs or factory image

**Comment by jaharon** [comment]
@Ansuel I have a serial setup. It might take me some time to setup a tftp server and find the right boot command (been a while), but I'm sure that I'll get it done over the weekend.

**Comment by Ansuel** [comment]
@jaharon ok i will prepare the image... for the command and the tool it's easy i can pass you the command and the tool is just tftpd64

Would be fun if things magically works with a tftp image and problem is just a custom thing in the linksys bootloader than now conflicts with 5.15

**Comment by paulcarroty** [comment]
I can get the serial connect too, but it's complicated a bit 'cause no headers. By the way, this is not the first EA8500 switch issue: https://github.com/openwrt/openwrt/issues/7379, https://github.com/openwrt/openwrt/pull/2047

**Comment by Ansuel** [comment]
@jaharon @paulcarroty can you test the 2 commit present here?
https://git.openwrt.org/?p=openwrt/staging/ansuel.git;a=shortlog;h=refs/heads/fix-eax500

**Comment by jaharon** [comment]
@ansuel The switch is not working.

New boot log
[ea8500_5.15_boot_with_new_patches.log](https://github.com/openwrt/openwrt/files/9993275/ea8500_5.15_boot_with_new_patches.log)


```
ls /sys/class/mdio_bus/37000000.mdio-mii
device      of_node     statistics  subsystem   uevent
```


The gpios diff doesn't read to me as I expected with this patch:
```diff
diff a8500_gpios_5.15.txt ea8500_gpios_5.15_with_new_patches.txt
67c67
<  gpio63  : out high func0 12mA no pull
---
>  gpio63  : out high func0 10mA pull down
```

The new dts
[image-qcom-ipq8064-ea8500_5_15_with_new_patches.dts.txt](https://github.com/openwrt/openwrt/files/9993292/image-qcom-ipq8064-ea8500_5_15_with_new_patches.dts.txt)


dts diff 
[dts_diff_5_15_VS_5_15_with_new_patches.txt](https://github.com/openwrt/openwrt/files/9993298/dts_diff_5_15_VS_5_15_with_new_patches.txt)




The patches I've used in my build box:
generic: ar8327: add optional gpio reset support
ipq806x: fix non working switch for eax500 devices

**Comment by Ansuel** [comment]
Nice! we are on something!

```
[   21.371873] ipq806x-gmac-dwmac 37200000.ethernet: Failed to reset the dma
[   21.371913] ipq806x-gmac-dwmac 37200000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   21.377722] ipq806x-gmac-dwmac 37200000.ethernet eth0: __stmmac_open: Hw setup failed
```

**Comment by Ansuel** [comment]
@jaharon how you installed this? sysupgrade and softreboot? can you try to power cycle the device?

**Comment by jaharon** [comment]
@Ansuel

I sysupgraded from the web interface, after the initial reboot I grabbed all the data. I then did a power cycle and checked the switch.

I now did a soft reboot to the second partition with 5.15 (plus patches), no switch with 
```ipq806x-gmac-dwmac 37200000.ethernet: Failed to reset the dma``` in the log.
I then power cycled the router (5 seconds power off and then on), no switch and same message in the logs.

**Comment by Ansuel** [comment]
btw i'm analyzing the linksys GPL source and yes i found the gpio63 thing and also ea7500 is just ea8500 with less thing... the source of 7500 is based on the source of ea8500 so I was right with the idea that they are based on the same hw design from linksys...

**Comment by Ansuel** [comment]
@jaharon can you check one thing? what are the leds state while the fw is booting? at some time ethernet leds should all power on and then off... (that means we are correctly resetting the switch)

**Comment by jaharon** [comment]
@Ansuel with 5.10 during boot *all* the ethernet leds turn on and off and then work as expected.
With 5.15 with the last 2 patches, *some* lights flicker at boot time, very briefly, then all leds turn off and stay off.

**Comment by jaharon** [comment]
> @Ansuel with 5.10 during boot _all_ the ethernet leds turn on and off and then work as expected. With 5.15 with the last 2 patches, _some_ lights flicker at boot time, very briefly, then all leds turn off and stay off.

I tested this with a soft reboot and a full power cycle, same results.

**Comment by jaharon** [comment]
@Ansuel No switch. Seem like the same behavior, some lights flicker at boot time, very briefly, then all leds turn off and stay off.
```diff
--- a/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-eax500.dtsi
+++ b/target/linux/ipq806x/files-5.15/arch/arm/boot/dts/qcom-ipq8064-eax500.dtsi
@@ -18,7 +18,7 @@
                        pins = "gpio63";
                        function = "gpio";
                        drive-strength = <12>;
-                       bias-pull-up;
+                       bias-disable;
                };
        };
 };
 ```
[ea8500_5.15_boot_with_new_patches_with_bias-disable.log](https://github.com/openwrt/openwrt/files/10009000/ea8500_5.15_boot_with_new_patches_with_bias-disable.log)

**Comment by antoinedeschenes** [comment]
I also have an EA8500 to test on, I noticed that ddwrt disables the whole pcie2 device in the dts file, might be worth taking a look at how they handle gpio63

**Comment by Ansuel** [comment]
@antoinedeschenes can you link that? i'm checking ddwrt and they don't disable pcie2 in dts

**Comment by antoinedeschenes** [comment]
> @antoinedeschenes can you link that? i'm checking ddwrt and they don't disable pcie2 in dts

Only in 4.14 it seems https://github.com/mirror/dd-wrt/blob/392b45a1dcd4c99d65104360da1ed9daa149b42e/src/linux/universal/linux-4.14/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts#L387

**Comment by RadioOperator** [comment]
Thanks for you all works on this problem, I'm still waiting it solved.

Question: using the new 5.15 kernel driver set, which ipq8064 router is working no such problem, TP-LINK C2600?

**Comment by antoinedeschenes** [comment]
> Thanks for you all works on this problem, I'm still waiting it solved.
> 
> Question: using the new 5.15 kernel driver set, which ipq8064 router is working no such problem, TP-LINK C2600?

Honestly performance is down by 2x on my NBG6817 on master with 5.15 compared to 22.03.x, I'd stay on that release unless you want to try debugging it. I don't know if the problem is the kernel upgrade or another change though.

**Comment by RadioOperator** [comment]
> it's getting problematic with remote debugging... the 2 linksys router used an hack to handle the switch reset and now that became a problem... ideally it should have been handled correctly back in the days but mhe now we have to fix it for once

This means EA8500 is a special hw, different with the others, and the kernel 5.10+patches could handle it well, thanks.
It seems the problem repeated again when every time kernel upgrade.

**Comment by RadioOperator** [comment]
Hi @jaharon @antoinedeschenes @Ansuel ,
I didn't find `gpio63` in `qcom-ipq8064-eax500.dtsi` file, but I find it in `qcom-ipq8064.dtsi`:
![Capture](https://user-images.githubusercontent.com/27762920/202760078-1fb80b10-bdb6-43e5-840c-732d0aa5a037.JPG)
The v5.10 code has `output-low;` line than v5.15, how to patch this line into the file for testing.

**Comment by jaharon** [comment]
@RadioOperator 
I've used the information from https://forum.openwrt.org/t/gpio-in-sys-class-leds/31506/33 and https://openwrt.org/docs/guide-developer/toolchain/use-patches-with-buildsystem#adding_or_editing_toolchain_patches
and created the following patch:

```target/linux/ipq806x/patches-5.15/104-v6.0-09-ARM-dts-qcom-ipq8064-gpio63-output-low.patch```
```patch
--- a/arch/arm/boot/dts/qcom-ipq8064.dtsi
+++ b/arch/arm/boot/dts/qcom-ipq8064.dtsi
@@ -539,6 +539,7 @@
 					function = "pcie3_rst";
 					drive-strength = <12>;
 					bias-disable;
+					output-low;
 				};
 			};

```

I didn't see any changes in gpio levels and the switch didn't work.

**Comment by RadioOperator** [comment]
Hi @jaharon, thanks and got it, still no effect.

**Comment by RadioOperator** [comment]
Hi All, I have done a patch file to backport the ipq8064 driver to v5.10, near 95% same as the working v5.10:
[140-qcom-ipq8064.dtsi-back510-test.patch.txt](https://github.com/openwrt/openwrt/files/10048331/140-qcom-ipq8064.dtsi-back510-test.patch.txt)
But, the problem still there!

**Comment by RadioOperator** [comment]
Hi @Ansuel , after check many times ipq8064 dts driver files for EA8500, I believe the problem should be in the kernel part patch files. the new patch files for v5.15, something different or missing when transfers from v5.10. Need your help to find it, I could test on it. Thanks.

**Comment by Ansuel** [comment]
If someone wants a quick fix I need the device sent. If that can't be done
we need to wait and I have to produce some testing kernel to understand if
it's a problem with the version. Something I need to try is bsckport the
proposed fix for 5.15 to 5.10 and see if it does work just to make sure
that code is correct.

Il Gio 24 Nov 2022, 16:02 Jack Wang ***@***.***> ha scritto:

**Comment by Ansuel** [comment]
A dear user decided to send me a ea8500 so i'm waiting for it to come to my home to fix this and ea7500 :D

**Comment by Ansuel** [comment]
Still waiting for the device to arrive

Il Lun 2 Gen 2023, 12:23 eginnc ***@***.***> ha scritto:

**Comment by paulcarroty** [comment]
@Ansuel have you got the router?

**Comment by Ansuel** [comment]
@paulcarroty yep worked on it yesterday and today and I'm just pushing the fix... just polishing it, adding explaination and a final test :D

**Comment by jaharon** [comment]
Confirmed working.
Great outcome. Thanks for spending time on this!

**Comment by antoinedeschenes** [comment]
Good to know that spare router finally arrived and turned out to be useful
