### ISSUE TITLE
Missing CI in OpenWrt 21.02 branch

### ISSUE THREAD

**Issue by BKPepe** [openwrt/openwrt#10980]
There is a missing GitHub Actions for OpenWrt 21.02. I think, it might be valuable to backport it there as it is still supported version from OpenWrt 22.03 and OpenWrt master

cc: @Ansuel

**Comment by Ansuel** [comment]
Any action in particular? Or your idea is to backport all of them?

Il Sab 15 Ott 2022, 14:33 Josef Schlehofer ***@***.***> ha
scritto:

**Comment by BKPepe** [comment]
At least the formal check would be nice, but of course, having more is always better than nothing.

**Comment by BKPepe** [comment]
Closing as it was implemented. See the referenced things. :arrow_up:
