### ISSUE TITLE
kmod-wireguard not available in any repository 

### ISSUE THREAD

**Issue by javykhan** [openwrt/openwrt#10999]
Hi
I am using robimarko OpenWRT snapshot in REDMI AX6. I need wireguard as VPN server on this router but its missing kernel module kmod-wireguard. Any help/guide on this?

**Comment by castiel652** [comment]
compile it yourself.
AX6 is not officially supported yet.

**Comment by ynezz** [comment]
This isn't a bug. Please continue the discussion in the [OpenWrt forum](https://forum.openwrt.org/) as this seems more like a general support question.
