### ISSUE TITLE
How to install odhcpd

### ISSUE THREAD

**Issue by noraworld** [openwrt/openwrt#11018]
I would like to install odhcpd, but I can't.

```
git clone git@github.com:openwrt/odhcpd.git
cd odhcpd
cmake .
```

It worked well until this point.

However, when I try to execute `make`, it fails.

```
[ 12%] Building C object CMakeFiles/odhcpd.dir/src/odhcpd.c.o
/home/ubuntu/odhcpd/src/odhcpd.c:43:10: fatal error: libubox/uloop.h: No such file or directory
   43 | #include <libubox/uloop.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/odhcpd.dir/build.make:76: CMakeFiles/odhcpd.dir/src/odhcpd.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/odhcpd.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

I'm very new to this kind of project, so I would be grateful if you could teach me in a way that's easy to understand as much as possible.

**Comment by ynezz** [comment]
This isn't a bug. Please continue the discussion in the [OpenWrt forum](https://forum.openwrt.org/) as this seems more like a general support question.
