### ISSUE TITLE
fw4: Whether the syn_flood firewall rules are incorrect

### ISSUE THREAD

**Issue by CallMeR** [openwrt/openwrt#11031]
I was very interested in the Nftables used by the latest version of OpenWrt, and did some experiments, the firewall that is currently exported by command `nft -s list ruleset` is as follows  

```nft
table inet fw4 {
	chain input {
		type filter hook input priority filter; policy accept;
		iifname "lo" accept comment "!fw4: Accept traffic from loopback"
		ct state established,related accept comment "!fw4: Allow inbound established and related flows"
		ct state invalid drop comment "!fw4: Drop flows with invalid conntrack state"
		tcp flags syn / fin,syn,rst,ack jump syn_flood comment "!fw4: Rate limit TCP syn packets"
		iifname "br-lan" jump input_lan comment "!fw4: Handle lan IPv4/IPv6 input traffic"
		iifname { "eth2", "pppoe-wan" } jump input_wan comment "!fw4: Handle wan IPv4/IPv6 input traffic"
	}
...
}
```

When I try to import the nft rules to another Debian 11 server, I get an error  
`Error: syntax error, unexpected string, expecting number`

<img width="871" alt="image" src="https://user-images.githubusercontent.com/11908641/196980414-b55ed996-4c72-4bb5-b922-50dd30fbfc85.png">

I found the corresponding iptables firewall record, the command is as follows  

`-A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -m comment --comment "fw3" -j syn_flood`

And convert it into the syntax supported by nftables:

`iptables-translate -A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -m comment --comment "fw3" -j syn_flood`  

The results show that the correct syntax should look like this

```nft
table inet fox_firewalls {
	chain input {
		...
		tcp flags & (fin|syn|rst|ack) == syn jump syn_flood comment "!fw4: Rate limit TCP syn packets"
	        ...
	}
}
```
So which is the real correct one, `syn / fin,syn,rst,ack` **or** `& (fin|syn|rst|ack) == syn` ?

**Comment by dave14305** [comment]
Use `fw4 -q print` to see what firewall4 is emitting. It is different than the nft output.

**Comment by brada4** [comment]
Debian sid accepts both syntax variations. You can compile new nft version temporarily on old versions of debian to make import happen.

**Comment by jow-** [comment]
Not an OpenWrt issue. Please use the forum for support questions.
