### ISSUE TITLE
22.03.2 libmbim and its dependant packages had disappeared from release repositories and from the manifest

### ISSUE THREAD

**Issue by syp1975** [openwrt/openwrt#11055]
* Name the tree/revision/version: release 22.03.02
* Name the affected device: x86_64
* What does it do that it should not do / what does it not do that it should do: image builder now fails to build an image that includes libmbim mbim-tools modemmanager luci-proto-modemmanager, while downloading packages it outputs "unknown package xxx".
* Steps to reproduce: download image builder for this release and build an image including those said packages
* What you have already done to workaround/fix the problem: switching to snapshot
* Any additional info you think is important: those packages were there last week, I had been able to build images with the same release and already having those packages.

diff of the snapshot packages manifest (https://downloads.openwrt.org/snapshots/packages/x86_64/packages/Packages.manifest) vs the manifest of the 22.02.3 release (https://downloads.openwrt.org/releases/22.03.2/packages/x86_64/packages/Packages.manifest), you can see that libmbim and all the packages that depend on it are gone:
```
*** "22.03.2 packages.manifest" 2022-10-22 08:12:14.432305511 +0200
--- "snapshot packages.manifest"        2022-10-22 08:11:52.200207926 +0200

...

***************
*** 25649,25668 ****
--- 25928,25965 ----
  Section: libs
  SourceDateEpoch: 1627557662
  Maintainer: Jan Pavlinec <jan.pavlinec1@gmail.com>
  Architecture: x86_64
  Installed-Size: 13440
  Filename: libmaxminddb_1.6.0-1_x86_64.ipk
  Size: 14193
  SHA256sum: 9c42448d4a67f3ce3a4aaab85cc3ba5af5b730aaf7efe3bd70d8361c4db54927
  Description:  The libmaxminddb library provides functions for working MaxMind DB files.
  
+ Package: libmbim
+ Version: 1.26.4-2
+ Depends: libc, glib2
+ Source: feeds/packages/libs/libmbim
+ SourceName: libmbim
+ License: LGPL-2.0-or-later
+ LicenseFiles: COPYING.LIB
+ Section: libs
+ SourceDateEpoch: 1655341666
+ Maintainer: Nicholas Smith <nicholas@nbembedded.com>
+ Architecture: x86_64
+ Installed-Size: 134828
+ Filename: libmbim_1.26.4-2_x86_64.ipk
+ Size: 135415
+ SHA256sum: 1f09c87c850b73fe72e5bc745795f2af2c1f9d370f111110880195338536b363
+ Description:  Helper library to talk to MBIM enabled modems.
+  Add mbim-utils for extra utilities.
+ 
  Package: libmcrypt
  Version: 2.5.8-2
  Depends: libc
  Source: feeds/packages/libs/libmcrypt
  SourceName: libmcrypt
  License: LGPL-2.1-or-later
  LicenseFiles: COPYING.LIB
  Section: libs
  SourceDateEpoch: 1607400704
  CPE-ID: cpe:/a:mcrypt:libmcrypt

...

```

**Comment by ynezz** [comment]
Check https://openwrt.org/bugs#issue_trackers, this bug report looks like it should've been filled in https://github.com/openwrt/packages/issues.
