### ISSUE TITLE
make defconfig error on master branch

### ISSUE THREAD

**Issue by ecrasy** [openwrt/openwrt#11087]
Here is what i did:
1. clean clone master
2. update feeds & install feeds
3. make defconfig

LOG below:
Collecting package info: done
tmp/.config-package.in:59702:error: recursive dependency detected!
tmp/.config-package.in:59702:	symbol PACKAGE_libwebsockets-openssl is selected by PACKAGE_libwebsockets-mbedtls
tmp/.config-package.in:59686:	symbol PACKAGE_libwebsockets-mbedtls depends on PACKAGE_libwebsockets-openssl
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

#
# configuration written to .config
#

**Comment by stintel** [comment]
This is a warning, not an error. If it's still a problem, report it in [the issue tracker of the packages feed](https://github.com/openwrt/packages/issues), where the libwebsockets package resides.
