### ISSUE TITLE
Rockchip (NanoPi R2S and R4S) Kernel 5.15 Configuration Not Retained After Sysupgrade

### ISSUE THREAD

**Issue by eginnc** [openwrt/openwrt#11197]
As of migration to 5.15 on master snapshot, the NanoPi R2S and R4S do not retain their configuration settings after a squashfs sysupgrade.  This is reported to be caused by the size of the kernel increasing above the space required for it.

A PR [here](https://github.com/openwrt/openwrt/pull/11012) intended to address this issue by increasing available space was closed without implementation due to lack of consensus on whether to fix by increasing available space or using compression, thus leaving this issue unresolved.

With the preceding PR closed without resolution, this issue is opened to report the problem continues.

**Comment by kmarzic** [comment]
Hi,
I was using this tip from the forum to keep configuration after re-flash:
https://forum.openwrt.org/t/nanopi-r4s-rk3399-r6s-rk3588s-4g-is-a-great-new-openwrt-device/79143/1224
