### ISSUE TITLE
rules.mk: grep --max-count usage in commitcount isn't portable

### ISSUE THREAD

**Issue by pktpls** [openwrt/openwrt#11200]
```
grep: unrecognized option: max-count=1
BusyBox v1.35.0 (2022-07-06 19:09:49 UTC) multi-call binary.

Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A|B|C N] { PATTERN | -e PATTERN... | -f FILE... } [FILE]...
```

On Alpine. This seems to be from `commitcount` in rules.mk - so it's not terrible and breaking something important, but I thought I'd file it anyway.

**Comment by Ansuel** [comment]
@pktpls hi i notice this... an easy solution is to use -m that should be just the short version of --max-count... 

Can you try to replace --max-count with -m ?
