### ISSUE TITLE
Missing  packages in MF286D

### ISSUE THREAD

**Issue by obsy** [openwrt/openwrt#11235]
@Leo-PL https://github.com/openwrt/openwrt/commit/3e15a54bb0ef470e19a36dfbbd97c1bc9b363b99 splits the code between MF286D and MF289F. But ```DEVICE_PACKAGES:= ipq-wifi-zte_mf286d``` should be ```DEVICE_PACKAGES += ipq-wifi-zte_mf286d```, allowing other default packages to be included in the image.

**Comment by Leo-PL** [comment]
@obsy thanks for noticing - opening a PR to fix it right away.
