### ISSUE TITLE
Upgrading package source from that written back in 2017

### ISSUE THREAD

**Issue by nsmith1024** [openwrt/openwrt#11241]
Hello,

Im using an OpenWRT package, but the source in there is version from 2017, how do i tell it to use the latest, or a later version of the source code that goes into a package?

For example if it was using ffmpeg in a package that was a version that was written from back in 2017, and i want to use the new features from 2022, how would i upgrade the package source to use the most recent version.

ffmpeg is just an example, seems there are several packages in there that was written years ago, I want to update it to the latest version, and put that into the image build.

Thanks

**Comment by pkgadd** [comment]
This is a bugtracker for the OpenWrt project, not a support forum - and you're cross-posting anyways https://forum.openwrt.org/t/update-a-package-written-back-in-2017-to-a-newer-version/142698/.
