### ISSUE TITLE
Luci crash on latest stable version

### ISSUE THREAD

**Issue by Ntemis** [openwrt/openwrt#11315]
192.168.1.1 brings this log
/usr/lib/lua/luci/dispatcher.lua:431: /etc/config/luci seems to be corrupt, unable to find section 'main'

**Comment by jow-** [comment]
Please ensure that the `rpcd` service is running.

**Comment by Ntemis** [comment]
It is

**Comment by Ntemis** [comment]
Anyway updated to latest ~head 
![image](https://user-images.githubusercontent.com/2123893/203391731-567f9138-c2e6-49ed-8b01-a0c7b81618c4.png)
