### ISSUE TITLE
Does OpenWRT OS access the flash after it boots?

### ISSUE THREAD

**Issue by nsmith1024** [openwrt/openwrt#11310]
Hello,

Im using OpenWRT OS on some custom hardware that only has 1 SPI, the same SPI connected to the boot flash.

I need to use those SPI pins in my application after the OS finishes booting up.

So im wondering if OpenWRT OS ever accesses the SPI after it boots, or does it just use it during boot to read the OS from the flash into RAM where it runs.

The reason im asking is that my application needs to disable the SPI after booting so that i can use those pins for something else.

Thanks

**Comment by pkgadd** [comment]
Please don't [cross-post](https://forum.openwrt.org/t/does-openwrt-use-the-spi-after-booting/143470), and keep in mind that this is a bug tracker, not a support forum.
