### ISSUE TITLE
kmod-usb-dwc2 is required for FRITZ!Box 7430

### ISSUE THREAD

**Issue by lustmue** [openwrt/openwrt#11326]
The default image for FRITZ!Box 7430 does not include support for the built in USB interface. @lmadam20, the author who added support for this device to OpenWrt, helped me to fix this issue by suggesting that I install kmod-usb-dwc2. I suggest that you include this module in the default image for FRITZ!Box 7430.

**Comment by Spudz76** [comment]
Here is the quite simple patch that does what you requested.

[fritz7430_usb_dwc2.patch.txt](https://github.com/openwrt/openwrt/files/10079276/fritz7430_usb_dwc2.patch.txt)

**Comment by lustmue** [comment]
Wow, that was quick. @adschm, you committed the initial support for this device. Do you want to review this related patch, too?

**Comment by abajk** [comment]
@lustmue @Spudz76 One of you should open a new PR, to get the proposed changes merged.

**Comment by Spudz76** [comment]
PR has been merged into `master`
