### ISSUE TITLE
A dependency error occurs when adding ipsec

### ISSUE THREAD

**Issue by sjkhsl** [openwrt/openwrt#11330]
Adding luci-app-ipsec-server or luci-app-ipsec-vpnd will cause recursive dependency problems, and there is no option in luci-applications!

luci-app-ipsec-server Link ：https://github.com/kiddin9/openwrt-packages/tree/master/luci-app-ipsec-server
luci-app-ipsec-vpnd Link : https://github.com/kiddin9/openwrt-packages/tree/master/luci-app-ipsec-vpnd

**Comment by stintel** [comment]
Please don't use our bugtracker for problems in packages in unsupported feeds. Use [their issue tracker](https://github.com/kiddin9/openwrt-packages/issues) instead.
