### ISSUE TITLE
Newest OpenWRT builds for TP-Link Archer C5 v4 -- Missing option in 'menuconfig'

### ISSUE THREAD

**Issue by MartinVonReichenberg** [openwrt/openwrt#11369]
Hello,
Is there any chance on getting the latest build of **OpenWRT** for TP-Link **Archer C5 v4** _(MediaTek MT7620A)_
?_?

```Firmware Version:3.16.0 0.9.1 v600c.0 Build 191107 Rel.15316n Hardware Version:Archer C5 v4 00000004```

![Screenshot from 2022-11-28 14-53-36](https://user-images.githubusercontent.com/110736521/204294700-e373e3b9-b3fc-4fa8-b586-1a5fc25f6c0a.png)
As you can see, there is a missing option in `'menuconfig'`, the option for **C5 v4** is missing, but there is option for **C5 v1** . . . . . 

P.S.:
There is an already existing [**fork**](https://github.com/benwht/openwrt) containing **BINaries** for Archer C5 v4 . . .

**Comment by 981213** [comment]
Hi!
This device isn't supported in the mainline openwrt yet.
You can continue using the fork for this particular device if you want.

**Comment by namiltd** [comment]
Look at https://github.com/openwrt/openwrt/pull/4327

**Comment by luizluca** [comment]
> Look at #4327

The best luck for c5v4 is to get supported using upstream DSA driver. For that, we need #12738. There is simply too much kernel  backports to make it work safely with older kernels.

@namiltd , I noticed you are already playing with 6.1.

**Comment by namiltd** [comment]
[luizluca](https://github.com/luizluca) Yes, but without DSA at the moment. I'm also waiting for my patches to be merged to make kernel 6.1 work.
