### ISSUE TITLE
希望在21.02版本中添加mt7921 ap模式支持

### ISSUE THREAD

**Issue by liuxichi** [openwrt/openwrt#11374]
谢谢各位对openwrt贡献，希望在5.4内核下的21.02版本用上mt7921的ap模式。

**Comment by 981213** [comment]
Hi!
We don't do feature backports on stable releases. You can just use 22.03 if you want mt7921 support.

**Comment by liuxichi** [comment]
> 你好！ 我们不会在稳定版本上进行功能反向移植。如果你想要 mt7921 支持，你可以只使用 22.03。
> 
> OpenWrt稳定版本都不会再增加任何新功能。如果你需要mt7921支持，你可以选择更新到22.03。

谢谢回复！
