### ISSUE TITLE
Cant sysupgrade

### ISSUE THREAD

**Issue by javykhan** [openwrt/openwrt#11384]
I am trying sysupgrade on robimarko snapshot already installed on Redmi AX6 but it doesn’t change anything. Just booting with installed release.

tried restarting router and stopping wpad but its didn’t work. Any idea how to fix this.

**Comment by brada4** [comment]
You will have better luck asking right there https://github.com/robimarko/openwrt/issues

**Comment by robimarko** [comment]
This is not in OpenWrt proper yet, so please see the forum thread:
https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-ax3600
