### ISSUE TITLE
tplink-wdr4310-v1 replaces the flash (W25Q512JVFIQ SOIC-16)

### ISSUE THREAD

**Issue by KIM-PUSS** [openwrt/openwrt#11410]
### **tplink-wdr4310-v1 replaces the flash (W25Q512JVFIQ SOIC-16).** 
After modifying the dts, it cannot be compiled. What should I do to compile it correctly?
 It is correct and feasible to compile and support 16M (W25Q128) flash.

1. vi target/linux/ath79/dts/ar9344_tplink_tl-wdr4310-v1-64.dts

`// SPDX-License-Identifier: GPL-2.0-or-later OR MIT
/dts-v1/;
#include "ar9344_tplink_tl-wdr4300.dtsi"
/ {
        model = "TP-Link TL-WDR4310 v1 (64M)";
        compatible = "tplink,tl-wdr4310-v1", "qca,ar9344";
};
&spi {
        num-cs = <1>;
        status = "okay";
        flash@0 {
                compatible = "jedec,spi-nor";
                reg = <0>;
                spi-max-frequency = <25000000>;
                partitions {
                        compatible = "fixed-partitions";
                        #address-cells = <1>;
                        #size-cells = <1>;
                        uboot: partition@0 {
                                label = "u-boot";
                                reg = <0x000000 0x020000>;
                                read-only;
                        };
                        partition@20000 {
                                compatible = "tplink,firmware";
                                label = "firmware";
                                reg = <0x020000 0x3f40000>;
                        };
                        /delete-node/ partition@7f0000;
                        art: partition@3ff0000 {
                                label = "art";
                                reg = <0x3ff0000 0x010000>;
                                read-only;
                        };
                };
        };
};
`

2.  vi target/linux/ath79/image/generic-tp-link.mk
`define Device/tplink_tl-wdr4310-v1
  $(Device/tplink-8mlzma)
  SOC := ar9344
  DEVICE_MODEL := TL-WDR4310
  DEVICE_VARIANT := v1
  DEVICE_PACKAGES := kmod-usb2 kmod-usb-ledtrig-usbport
  TPLINK_HWID := 0x43100001
  SUPPORTED_DEVICES += tl-wdr4300
endef
TARGET_DEVICES += tplink_tl-wdr4310-v1`

3. vi target/linux/ath79/generic/base-files/etc/hotplug.d/firmware/10-ath9k-eeprom
`tplink,tl-wdr4310-v1|\
        tplink,tl-wdr4310-v1-64|\`

**Comment by pkgadd** [comment]
That is not a bug (OpenWrt works on original hardware without modifications just fine) and this is a bug tracker, not a support forum.
