### ISSUE TITLE
[regression] Out of memory on boot

### ISSUE THREAD

**Issue by crackcraft** [openwrt/openwrt#11425]
Fail to run 22, 21 releases on [ZyXEL Keenetic v1](https://openwrt.org/toh/hwdata/zyxel/zyxel_keenetic) with Out of memory error.

[openwrt-21.02.5-ramips-rt305x-zyxel_keenetic-initramfs-kernel.bin.log](https://github.com/openwrt/openwrt/files/10149376/openwrt-21.02.5-ramips-rt305x-zyxel_keenetic-initramfs-kernel.bin.log)
[openwrt-22.03.1-ramips-rt305x-zyxel_keenetic-initramfs-kernel.bin.log](https://github.com/openwrt/openwrt/files/10149377/openwrt-22.03.1-ramips-rt305x-zyxel_keenetic-initramfs-kernel.bin.log)
[openwrt-22.03.2-ramips-rt305x-zyxel_keenetic-initramfs-kernel.bin.log](https://github.com/openwrt/openwrt/files/10149378/openwrt-22.03.2-ramips-rt305x-zyxel_keenetic-initramfs-kernel.bin.log)

19.07.9 release is ok
[openwrt-19.07.9-ramips-rt305x-kn-initramfs-kernel.bin.log](https://github.com/openwrt/openwrt/files/10149380/openwrt-19.07.9-ramips-rt305x-kn-initramfs-kernel.bin.log)

**Comment by pkgadd** [comment]
One of the reasons why [32 MB RAM devices](https://openwrt.org/supported_devices/432_warning) are explicitly no longer supported, not a bug, not (really) fixable either.
