### ISSUE TITLE
Ath79/tiny - dynamic inclusion of commit f579b85 (ath79: add low_mem to tiny image) - support to WPA8630P v2.0 dropped since 22.03.1

### ISSUE THREAD

**Issue by pstlr78** [openwrt/openwrt#11462]
Since the introduction of commit **f579b85 (ath79: add low_mem to tiny image)** (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=f579b8538b72ed4ea9b53e7ed1cffe651e90ffeb), more flash space is required for the benefit of better (RAM) memory utilisation in low flash memory devices.

However, neither all ath79/tiny devices have low RAM capacity (to make this commit pragmatically beneficial) nor all of them have plenty of flash space (which is the main reason of existence of the ath79/tiny branch itself). There are devices such as the TP-LINK WPA8630P v2.x, in which support suddenly stopped after and including OpenWrt release version 22.03.1 due to (marginal) flash size limitation (6MB), highly likely due to the introduction of this commit. 22.03.**0** however installs fine on the same device. This device has plenty of RAM size though (128MB), making the RAM optimization benefit of this commit less important for this device.

**Suggestion**: If this is possible, the aforementioned commit should **dynamically** be part of the release **sysupgrade** image, depending on the additional criterion of the flash size of the target device (i.e. >8MB) . There should not exist a "blanket" policy affecting every target. Alternatively, some size reduction measures should be taken by default either at this commit level or at the release sysupgrade image level for this device.

I also understand that one of the main fundamental aspects/values of the OpenWrt project is to maintain or extend support to as many devices as possible.

**Comment by jow-** [comment]
There is no possibility to dynamically include this as it results in differently compiled binaries.
