### ISSUE TITLE
PPP package conflict with ppp-multilink when opkg_install

### ISSUE THREAD

**Issue by Taomrli** [openwrt/openwrt#11543]
linux kernel version is 5.4.195

Collected errors:

check_data_file_clashes: Package ppp-multilink wants to install file /etc/ppp/chap-secrets But that file is already provided by package * ppp
check_data_file_clashes: Package ppp-multilink wants to install file /etc/ppp/filter But that file is already provided by package * ppp
check_data_file_clashes: Package ppp-multilink wants to install file /etc/ppp/options But that file is already provided by package * ppp
check_data_file_clashes: Package ppp-multilink wants to install file /etc/ppp/resolv.conf But that file is already provided by package * ppp
check_data_file_clashes: Package ppp-multilink wants to install file /lib/netifd/ppp-down But that file is already provided by package * ppp
check_data_file_clashes: Package ppp-multilink wants to install file /lib/netifd/ppp-up But that file is already provided by package * ppp
check_data_file_clashes: Package ppp-multilink wants to install file /lib/netifd/ppp6-up But that file is already provided by package * ppp
check_data_file_clashes: Package ppp-multilink wants to install file /lib/netifd/proto/ppp.sh But that file is already provided by package * ppp
check_data_file_clashes: Package ppp-multilink wants to install file /usr/sbin/pppd But that file is already provided by package * ppp
opkg_install_cmd: Cannot install package ppp-multilink.
The opkg install command failed with code 255.

How can I fix it?

**Comment by jow-** [comment]
Please use the forum or mailing lists for support questions.
