### ISSUE TITLE
Version 22.03 mwan3 does not take effect when using source address rules. Is there a solution?

### ISSUE THREAD

**Issue by sjkhsl** [openwrt/openwrt#11596]
### Describe the bug

Version 22.03 mwan3 does not take effect when using source address rules. Is there a solution?
How to cancel nftables, use iptables as firewall rules？

### OpenWrt version

r21563-9ed1830bdc

### OpenWrt target/subtarget

x86/64

### Device

j4125

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by stintel** [comment]
This is not a bug. For support, please ask our community.
