### ISSUE TITLE
vlan device will not been created when it only used by trelay

### ISSUE THREAD

**Issue by rhjdvsgsgks** [openwrt/openwrt#11627]
### Describe the bug

vlan device will not been created when it only used by trelay.
such as i have a eth0.2 vlan device. usually it not been created unless some interface using it. that's make sense. but when i configured trelay to use it. it still not been created. and i need to create a unmanaged dummy interface to make it appear. otherwise trelay will not works due the device is missing

### OpenWrt version

r19523-bfd070e7fa

### OpenWrt target/subtarget

ramips/mt7620

### Device

some mt7620 device

### Image kind

Official downloaded image

### Steps to reproduce

1. create a new vlan "device", such as eth0.2
2. don't create any "interface" using it
3. configure trelay to bridge it with any other "device", such as wlan1
4. start trelay

### Actual behaviour

eth0.2 not exist in the output of `ip a`
due this. trelay unable to start

### Expected behaviour

eth0.2 created after configured it in trelay config

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
This is due to the way netifd works. Devices will only be created if they have at least one interface using them. Create a dummy proto none interface for eth0.2 to solve this.
