### ISSUE TITLE
ipv6 dns bug

### ISSUE THREAD

**Issue by f4nff** [openwrt/openwrt#11657]
### Describe the bug

```
config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option dhcpv4 'server'
	option leasetime '24h'
	option ra 'server'
	option ra_default '2'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'
	list ra_flags 'home-agent'
	option force '1'
	list dns '2001:4860:4860::8888'
```

```
config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option dhcpv4 'server'
	option leasetime '24h'
	option ra 'server'
	option ra_default '2'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'
	list ra_flags 'home-agent'
	option force '1'
	list dns '2001:4860:4860::8888'
	list dhcp_option '6,8.8.8.8'
```

如果不设置	list dhcp_option '6,8.8.8.8' ，	list dns '2001:4860:4860::8888' 是生效的，
如果设置 list dhcp_option '6,8.8.8.8'  ，	list dns '2001:4860:4860::8888' 不生效，
两个配置不能共存。

### OpenWrt version

r19803-9a599fee93

### OpenWrt target/subtarget

x86/64

### Device

	BROUNION R86S

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by f4nff** [comment]
```
	list dns '2001:4860:4860::8888'
	list dhcp_option '6,8.8.8.8'
```
两者不能共存，只能生效其中一个。

**Comment by f4nff** [comment]
**odhcp6c | 2022-08-05-7d21e8d8-18
odhcpd | 2022-03-22-860ca900-1
odhcpd-ipv6only | 2022-03-22-860ca900-1**

**Comment by f4nff** [comment]
```
config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option dhcpv4 'server'
	option leasetime '24h'
	option ra 'server'
	option ra_default '2'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'
	list ra_flags 'home-agent'
	option force '1'
	list dns '2001:4860:4860::8888'
	list dhcp_option '6,8.8.8.8'
```

如果这样配置，windows 获取不到ipv6 dns
<img width="311" alt="image" src="https://user-images.githubusercontent.com/19538878/210159544-d767142a-2315-41c3-aac8-d8c760a75d06.png">

**Comment by Spudz76** [comment]
My guess is providing the `dhcp_option 6` replaces any previous convenience setting like `list dns` (which just defines option 6, but a different way).

Either use always `dns` or always `dhcp_option 6`, do not mix.

```
	list dns '2001:4860:4860::8888'
	list dns '8.8.8.8'
```
or
```
	list dhcp_option '6,2001:4860:4860::8888'
	list dhcp_option '6,8.8.8.8'
```

**Comment by jow-** [comment]
Configuration issue

**Comment by f4nff** [comment]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/19538878/210193286-75ef7e33-e662-4787-8011-6dfa5d762142.png">

**Comment by f4nff** [comment]
```
config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option dhcpv4 'server'
	option leasetime '24h'
	option ra 'server'
	option ra_default '2'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'
	list ra_flags 'home-agent'
	option force '1'
	list dhcp_option '6,8.8.8.8'
	list dhcp_option '6,2001:4860:4860::8888'
```
这样设置之后，依然获取不到dns ipv6

<img width="308" alt="image" src="https://user-images.githubusercontent.com/19538878/210193374-d1698361-470d-4175-9d0a-a0129a1fdaef.png">

**Comment by f4nff** [comment]
```
config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option dhcpv4 'server'
	option leasetime '24h'
	option ra 'server'
	option ra_default '2'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'
	list ra_flags 'home-agent'
	option force '1'
	list dns '2001:4860:4860::8888'
	list dns '8.8.8.8'
```

我这样设置之后，lan口直接挂掉，

你应该压根就没有去测试，

**Comment by f4nff** [comment]
@jow-   bug依然存在，并没有得到解决。

**Comment by Spudz76** [comment]
I thought additional DNS servers all went here:
![image](https://user-images.githubusercontent.com/2391234/210253236-2bb17acf-513d-4c32-b287-63b961a502ad.png)

**Comment by f4nff** [comment]
[Spudz76](https://github.com/Spudz76)



```
	list dns '2001:4860:4860::8888'
	list dns '8.8.8.8'
```
or

```
	list dhcp_option '6,2001:4860:4860::8888'
	list dhcp_option '6,8.8.8.8'
```

两种方法都不可以，

**Comment by Spudz76** [comment]
Yes, but try putting them both in luci under network->interfaces->lan->advanced where shown, instead of any of that

**Comment by f4nff** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/19538878/210326970-56ab6fce-923f-4bd8-8a47-a77c34efb345.png">

![image](https://user-images.githubusercontent.com/19538878/210326981-650d0ec7-9109-42ce-84a5-026e494c79c3.png)


放在这里一样不可以，

**Comment by f4nff** [comment]
你有测试过ipv6 dns ？
