### ISSUE TITLE
Unable to install wireguard-tools. kmod-wireguard Is missing

### ISSUE THREAD

**Issue by naltabra** [openwrt/openwrt#11658]
### Describe the bug

Same problem in shell or Luci
![DBDC793F-9D6D-41D1-968A-B4590370A8E5](https://user-images.githubusercontent.com/79868582/210136741-b2d0c9e2-ac5a-4292-87e1-3cf548b21d0c.jpeg)

### OpenWrt version

r0-9594846

### OpenWrt target/subtarget

ipq807x/generic

### Device

Ax3600

### Image kind

Official downloaded image

### Steps to reproduce

Image https://openwrt.org/inbox/toh/xiaomi/xiaomi_ax3600

in Luci install package wireguard-tools. kmod-wireguard Is missing

### Actual behaviour

Install stops

### Expected behaviour

. kmod-wireguard should have been installed

### Additional info

This is image created by Robimarko and present at openwrt.com

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by obsy** [comment]
No, ipq807x is not supported by OpenWrt. Someone posted links to Robimarko's image.

**Comment by brada4** [comment]
OP got help via proper channel
https://github.com/robimarko/openwrt/issues/91
