### ISSUE TITLE
ipq806x: Major traffic speed regression on Netgear R7800 after upgrading to kernel 5.15

### ISSUE THREAD

**Issue by gentoo-root** [openwrt/openwrt#11676]
### Describe the bug

I have a test setup, in which my laptop is connected to the router via Wi-Fi (ath10k-ct, 5 Ghz, up to 866 Mbit/s), and also to its WAN port via Ethernet (1 Gbit/s). I'm running an iperf3 test, sending data from the laptop to the router over Wi-Fi, forwarding (and NATing) them to the WAN port, then receiving them on my laptop over Ethernet.

Before commit bb451eccaa51bb7d57fd837ef586a8a0d1ab91b1, I got speed around 500 Mbit/s, which I could tune up to 680–710 Mbit/s by moving the eth0 and eth1 interrupts to the second CPU. After this commit, the speed dropped to 150–200 Mbit/s (tuning the IRQ affinity doesn't help). Building from master with this commit reverted restores the good speed. Which makes me think something broke between kernel versions 5.10 and 5.15, or some OpenWrt-specific patch might be missing.

Flow offloading (software flowtables) is enabled, but disabling it doesn't seem to have any measurable effect.

CPU 0 is at 100% utilization (by ksoftirqd/0) during the test, both on kernel 5.10 and kernel 5.15.

Any ideas what could go wrong with the kernel upgrade?

### OpenWrt version

r21626-045baca10b

### OpenWrt target/subtarget

ipq806x/generic

### Device

Netgear R7800

### Image kind

Self-built image

### Steps to reproduce

Configure the router to use static IP 10.42.0.2/24 and gateway 10.42.0.1 for WAN.

Run on the router (optionally, to get better speed on kernel 5.10):

```
cat /proc/interrupts # Note which IRQs are used for eth0 and eth1, let's say, it's IRQ 37 and 38.
echo 2 > /proc/irq/37/smp_affinity
echo 2 > /proc/irq/38/smp_affinity
```

Create a Wi-Fi network on the router and connect the laptop to this network.

Run on the laptop:

```
ip netns add test
ip link set eth0 netns test
ip netns exec test ip link set eth0 up
ip netns exec test ip addr replace 10.42.0.1/24 dev eth0
ip netns exec test iperf3 -s
```

Connect the Ethernet port of the laptop to the WAN port of the router.

Run on the laptop:

```
iperf3 -c 10.42.1 -t 0
```

Watch the transfer speed.

### Actual behaviour

Kernel 5.10: speed is about 700 Mbit/s with the IRQ affinity tuning (500 Mbit/s without).

Kernel 5.15: speed is about 150–200 Mbit/s, regardless of the IRQ affinity tuning.

CPU 0 utilization is 100%.

### Expected behaviour

Speed should be good (700 Mbit/s) on kernel 5.15.

### Additional info

Reverting commit bb451eccaa51bb7d57fd837ef586a8a0d1ab91b1 (essentially downgrading the kernel to 5.10) fixes the speed.

### Diffconfig

```text
CONFIG_TARGET_ipq806x=y
CONFIG_TARGET_ipq806x_generic=y
CONFIG_TARGET_ipq806x_generic_DEVICE_netgear_r7800=y
CONFIG_BUILD_PATENTED=y
CONFIG_BUSYBOX_DEFAULT_PIE=y
CONFIG_CLEAN_IPKG=y
# CONFIG_FSTOOLS_UBIFS_EXTROOT is not set
# CONFIG_KERNEL_CC_STACKPROTECTOR_REGULAR is not set
CONFIG_KERNEL_CC_STACKPROTECTOR_STRONG=y
CONFIG_KERNEL_STACKPROTECTOR_STRONG=y
# CONFIG_KERNEL_SWAP is not set
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_NGHTTP2=y
CONFIG_LIBCURL_NO_SMB="!"
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_WOLFSSL=y
CONFIG_LUA_ECO_DEFAULT_OPENSSL=y
CONFIG_LUA_ECO_OPENSSL=y
# CONFIG_LUA_ECO_WOLFSSL is not set
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_OPTIMIZE_SPEED=y
CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_OPENVPN_openssl_ENABLE_DEF_AUTH=y
CONFIG_OPENVPN_openssl_ENABLE_FRAGMENT=y
CONFIG_OPENVPN_openssl_ENABLE_IPROUTE2=y
CONFIG_OPENVPN_openssl_ENABLE_LZ4=y
CONFIG_OPENVPN_openssl_ENABLE_LZO=y
CONFIG_OPENVPN_openssl_ENABLE_MULTIHOME=y
CONFIG_OPENVPN_openssl_ENABLE_PF=y
CONFIG_OPENVPN_openssl_ENABLE_PORT_SHARE=y
CONFIG_OPENVPN_openssl_ENABLE_SMALL=y
CONFIG_PACKAGE_6in4=y
CONFIG_PACKAGE_ddns-scripts=y
CONFIG_PACKAGE_ddns-scripts-services=y
CONFIG_PACKAGE_ethtool-full=y
CONFIG_PACKAGE_firewall=y
# CONFIG_PACKAGE_firewall4 is not set
CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_https-dns-proxy=y
CONFIG_PACKAGE_ip-tiny=y
CONFIG_PACKAGE_ip6tables-mod-nat=y
CONFIG_PACKAGE_ip6tables-nft=y
CONFIG_PACKAGE_iperf3=y
CONFIG_PACKAGE_ipset=y
CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
CONFIG_PACKAGE_iptables-mod-ipopt=y
CONFIG_PACKAGE_iptables-nft=y
# CONFIG_PACKAGE_jansson is not set
CONFIG_PACKAGE_kmod-ip6tables=y
CONFIG_PACKAGE_kmod-ipt-conntrack=y
CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-ipopt=y
CONFIG_PACKAGE_kmod-ipt-ipset=y
CONFIG_PACKAGE_kmod-ipt-nat=y
CONFIG_PACKAGE_kmod-ipt-nat6=y
CONFIG_PACKAGE_kmod-ipt-offload=y
CONFIG_PACKAGE_kmod-ipt-raw=y
CONFIG_PACKAGE_kmod-iptunnel=y
CONFIG_PACKAGE_kmod-iptunnel4=y
CONFIG_PACKAGE_kmod-mii=y
CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-ipt6=y
CONFIG_PACKAGE_kmod-nf-nat6=y
CONFIG_PACKAGE_kmod-nft-compat=y
# CONFIG_PACKAGE_kmod-nft-fib is not set
# CONFIG_PACKAGE_kmod-nft-nat is not set
# CONFIG_PACKAGE_kmod-nft-offload is not set
CONFIG_PACKAGE_kmod-sched-core=y
CONFIG_PACKAGE_kmod-sit=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_kmod-usb-net=y
CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
CONFIG_PACKAGE_kmod-usb-net-rndis=y
CONFIG_PACKAGE_libcap-ng=y
CONFIG_PACKAGE_libcares=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libev=y
CONFIG_PACKAGE_libip4tc=y
CONFIG_PACKAGE_libip6tc=y
CONFIG_PACKAGE_libiperf3=y
CONFIG_PACKAGE_libipset=y
CONFIG_PACKAGE_libiptext=y
CONFIG_PACKAGE_libiptext-nft=y
CONFIG_PACKAGE_libiptext6=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblzo=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnetfilter-conntrack=y
CONFIG_PACKAGE_libnfnetlink=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_libpcre=y
CONFIG_PACKAGE_librt=y
CONFIG_PACKAGE_libstdcpp=y
# CONFIG_PACKAGE_libucode is not set
CONFIG_PACKAGE_libustream-openssl=y
# CONFIG_PACKAGE_libustream-wolfssl is not set
CONFIG_PACKAGE_libuuid=y
CONFIG_PACKAGE_libxml2=y
CONFIG_PACKAGE_libxtables=y
CONFIG_PACKAGE_miniupnpd-iptables=y
CONFIG_PACKAGE_mwan3=y
# CONFIG_PACKAGE_nftables-json is not set
CONFIG_PACKAGE_nginx-all-module=y
CONFIG_PACKAGE_nginx-ssl-util=y
CONFIG_PACKAGE_nginx-util=y
CONFIG_PACKAGE_openssl-util=y
CONFIG_PACKAGE_openvpn-easy-rsa=y
CONFIG_PACKAGE_openvpn-openssl=y
# CONFIG_PACKAGE_openwrt-keyring is not set
# CONFIG_PACKAGE_opkg is not set
CONFIG_PACKAGE_socat=y
CONFIG_PACKAGE_tc-tiny=y
CONFIG_PACKAGE_tcpdump=y
CONFIG_PACKAGE_terminfo=y
# CONFIG_PACKAGE_ucode is not set
# CONFIG_PACKAGE_usign is not set
CONFIG_PACKAGE_vim-full=y
CONFIG_PACKAGE_wpad-basic-openssl=y
# CONFIG_PACKAGE_wpad-basic-wolfssl is not set
CONFIG_PACKAGE_xtables-legacy=y
CONFIG_PACKAGE_xtables-nft=y
CONFIG_PACKAGE_zlib=y
CONFIG_PCRE_JIT_ENABLED=y
CONFIG_PKG_ASLR_PIE_ALL=y
# CONFIG_PKG_ASLR_PIE_REGULAR is not set
# CONFIG_PKG_CC_STACKPROTECTOR_REGULAR is not set
CONFIG_PKG_CC_STACKPROTECTOR_STRONG=y
# CONFIG_PKG_FORTIFY_SOURCE_1 is not set
CONFIG_PKG_FORTIFY_SOURCE_2=y
# CONFIG_SIGNATURE_CHECK is not set
# CONFIG_SIGNED_PACKAGES is not set
CONFIG_SOCAT_SSL=y
# CONFIG_TARGET_ROOTFS_INITRAMFS is not set
# CONFIG_WPA_WOLFSSL is not set
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by Ansuel** [comment]
Hi I already had some similar report about this... but it's a real PITA to bisect... 

Can you by chance remove the wifi from the testing env?

I have some speculation the regression is in wifi or something from wifi to the network stack...

I should still have patch to produce testing image from 5.10 to 5.15... I think you can build images right? If you want I can pass you the kernel patches so we can test them

**Comment by Ansuel** [comment]
@gentoo-root i had some fun times with 5.10 to 5.15 before so I ported enough patch to have working intermediate kernel for openwrt... they are tested with a very simple config and initramfs but they should be enough to al least find what kernel version trigger the problem...

my speculation about wifi comes from the fact that yes ath10-ct is out of tree but it's all based on mac80211 and I wonder if something changed there that affected wifi speed to the point of causing this massive regression

**Comment by Ansuel** [comment]
But for now I would wait for the ethernet test

**Comment by Ansuel** [comment]
Ok so the problem is also on ethernet traffic... this makes testing easier since I can build image with no wifi support. Is it a problem for you?

**Comment by Ansuel** [comment]
less patch to care... lighter image. The less variables we have the better.

It could be that the wifi problem gets fixes indirectly by sorting this out for ethernet.

**Comment by Ansuel** [comment]
@gentoo-root Hi, i finally had time to start compiling the images...

I'm compiling them and drop a zip here with all the images... feel free to ask the sources.
I'm compiling 5.11 5.12 5.13 and 5.14 images. I would ask you if you can do the same exact test in search of the regression.

**Comment by Ansuel** [comment]
https://we.tl/t-DP8TYWjVal Here the compiled images... very light

**Comment by dhewg** [comment]
> Is there any standard way to build the `perf` tool for OpenWrt?

Enable:
```
Prompt: Compile the kernel with performance events and counters
Location:
  -> Global build settings
    -> Kernel build options
```

and then you'll find perf under `Development`

**Comment by Ansuel** [comment]
@gentoo-root Think I will create a repo with the patch! And yes I will reupload the images.

**Comment by Ansuel** [comment]
@gentoo-root patch are here https://github.com/Ansuel/openwrt/tree/ipq806x-bisect-intermediate

check the last commit on how to change the kernel version of the image... 

This is the config that you should use... https://gist.github.com/Ansuel/c60ae7e30ca68ff7db4710f7e818ac8b Should produce a very minimal image with ethernet working

**Comment by Ansuel** [comment]
Please use initramfs with serial this way you don't have to reset the
config or risk a brick!

Il Dom 12 Feb 2023, 17:59 Maxim Mikityanskiy ***@***.***> ha
scritto:

**Comment by Ansuel** [comment]
@gentoo-root eh your way may be time consuming but should give better testing

Anyway did you got the image working with swconfig package installed?

**Comment by Ansuel** [comment]
@gentoo-root the driver is still there... just evolved... 
This disabled cache scaling 60fc93b35935a88b1e31d853a0abacf0847d8de4 since it does cause stability problem... Can you test by reverting this and checking if regression is fixed?

**Comment by Ansuel** [comment]
> Does it have something to do with occasional reboots of the device? Is the old krait-cpufreq driver also affected?

afaik yes but major problem is that it's hard to track no we never manage to get clear data if one thing is better than other

**Comment by nicklowe** [comment]
@Ansuel

Disabling cache scaling for all by default, for what seem to be relatively infrequent stability issues, may not strike the right balance given the performance impact penalty, which is incurred all the time. For those, such as myself, who need this throughput performance, this blocks updating without recompiling.

In my opinion, the performance implication is significant and impactful enough here to suggest not disabling by default via a compile time parameter.

Best,

Nick

**Comment by sppmasterspp** [comment]
I just wonder if I properly understand the performance drop with krait driver disabled. I have fiber 1Gbps/700Mbps and I don't see any performance drop (LAN/WLAN) when I do the usual speed tests no matter if the krait driver was disabled by Ansuel. I use NSS master build with kernel 5.15 on R7800.
Is a speed test (with speedtest.net) from WAN to LAN enough to see this performance drop.

**Comment by didi-home** [comment]
Just want to chime in here and say that the combination of
packet_steering = 1, flow_offloading = 1, irq_balance daemon on OpenWrt 22.03.5 r20134-5f15225c1e / Netgear Nighthawk X4S R7800 gives me linespeed back.

Without the options < 650Mbps, now 1019Mbps (no lineperf, just web speedtest)

**Comment by ezplanet** [comment]
I confirm the issue. Please see my findings and comments here:
https://forum.openwrt.org/t/netgear-r7800-23-05-rc2-poor-gigabit-network-performance/169035

An OpenWRT router should provide max network performance out of the box, without requiring and configuration tweaks.

**Comment by tapper82** [comment]
@ezplanet  Nail hit on head!

**Comment by olemmela** [comment]
I tested network performance by running iperf3 on the ipq806x node. Sending traffic caused high CPU usage and the speed was significantly lower (250Mbits) than the wirespeed (1Gbits).
I did compile image with kernel performance profiling included and run perf record command during tests.
It revealed that hrtimer was calling raw_spin_unlock_irqrestore which was using most of the CPU cycles.

After that it was pretty easy to spot the upstream commit https://github.com/torvalds/linux/commit/d5a05e69ac6e4c431c380ced2b534c91f7bc3280 where hrtimer was added to the driver.

**Comment by Ansuel** [comment]
And reverting that patch makes the perf increase?

Il Lun 21 Ago 2023, 17:04 Oskari Lemmelä ***@***.***> ha
scritto:

**Comment by olemmela** [comment]
Packet steering and irq balance have difference wifi performance. Without them wifi speed was around 450/450Mbits (after reverting hrtimer) but after enabling both 600/600Mbits. I don't have R7800, but I tested this with tp-link C2600 hardware.

For ethernet line speed those steering and irq balance are not needed.

I suppose extra cpu cycles are useful for wifi performance. 600/600Mbits is close to max 866Mbits 802.11ac phy rate.

**Comment by nbd168** [comment]
Nice find! I sent an email to netdev and the author of the regression with the following:

> Based on tests by OpenWrt users, it seems that this one is causing a significant performance regression caused by wasting lots of CPU cycles re-arming the hrtimer on every single packet. More info:
https://github.com/openwrt/openwrt/issues/11676#issuecomment-1690492666 
> 
> My suggestion for fixing this properly would be:
> - keep a separate timestamp for last tx packet
> - do not modify the timer if it's scheduled already
> - in the timer function, check the last tx timestamp and re-arm the timer if necessary.
> 
> This should significantly reduce the number of wasted CPU cycles, even when accounting for the additional overhead of hrtimer vs regular timer.
>
> Felix

**Comment by egc112** [comment]
See also pull request #13323

**Comment by holocronology** [comment]
Same issue, R7500v2.

**Comment by nicklowe** [comment]
@nbd168 Could/should this be chased up? https://www.spinics.net/lists/netdev/msg933225.html
Can we put in place a temporary solution in the interim?

**Comment by nicklowe** [comment]
Latest update seems here: https://lore.kernel.org/netdev/20230907-stmmac-coaloff-v2-1-38ccfac548b9@axis.com/

**Comment by ezplanet** [comment]
@frapperies' commit solves the problem for my Linksys EA8500 and Netgear R7800

**Comment by Ansuel** [comment]
@ezplanet yes as it's for snapshot can you test there?
