### ISSUE TITLE
ath10k-ct

### ISSUE THREAD

**Issue by Oozil** [openwrt/openwrt#11719]
### Describe the bug

Please there is a problem with the latest commit, which is that I was able to do 4.9GHz channels and 5.9GHz channels, but it has not yet appeared except through the iw phy command, but it appeared about my use of the ath10k-4.19 version, but this is very old and has problems

### OpenWrt version

master

### OpenWrt target/subtarget

wireless

### Device

atcher c7 v2

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
This sounds like a support request and is too vague to act upon. Please try gathering more feedback and assistance in gathering relevant details in the forum and consider opening a new bug report once you have tangible, actionable information.
