### ISSUE TITLE
Failed to compile ath10k-ct with older versions 

### ISSUE THREAD

**Issue by Oozil** [openwrt/openwrt#11741]
### Describe the bug

Failed to compile ath10k-ct with older versions such as ath10k-4.19 what's wrong

### OpenWrt version

master

### OpenWrt target/subtarget

ath79

### Device

atcher c7 v2

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by stintel** [comment]
As suggested in https://github.com/openwrt/packages/issues/20247, reach out to our community.
