### ISSUE TITLE
add support for Xiaomi Mi Router 4A Gigabit Edition v2

### ISSUE THREAD

**Issue by e323w** [openwrt/openwrt#11746]
### Describe the bug

hello!

please add support for `Xiaomi Mi Router 4A Gigabit Edition v2`
(I do not want to do it myself due to the requirement to disclose personal data in 'Signed-off-by', I'm so sorry)

you can use this [branch](https://github.com/e323w/openwrt-xiaomi-r4ag-v2/tree/r4agv2) as a base for a pull request (it is based on this [work](https://github.com/Ser9ei/xiaomi-r4agv2-openwrt_patch))

device is the same as `Xiaomi Mi Router 4A Gigabit Edition`, except of:

- 5 GHz wifi is MT7663
- addresses of leds, wifi and eth ports are slightly changed
- at the end of the flash, another `Config` partition was added, I'm not sure if we should preserve it, but I did it
- patch `ramips: mt7621-dts: mux phy0/4 to gmac1` does not seem to work for this device. with him on the `wan` port there is only Tx traffic, but no Rx. so I didn't add it

in this branch, I split `mt7621_xiaomi_mi-router-4a-3g-v2.dtsi` into two files: `mt7621_xiaomi_mi-router-4a-common.dtsi` (with common nodes for all 4a* devices) and original `mt7621_xiaomi_mi-router-4a-3g-v2.dtsi` (with only 4a-v1 and 3g-v2 specific nodes). it was possible to use the original file, but then the configuration for v2 would use hacks, including deleting nodes, so why I added this division.

I am currently using a build based on this branch and it seems to be working as expected
(btw, I'm not sure that the power adjustment for 5 GHz wifi works. at least I did not notice a difference in signal strength at different values)

thank you!

### OpenWrt version

master

### OpenWrt target/subtarget

ramips/mt7621

### Device

Xiaomi Mi Router 4A Gigabit Edition v2

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by stintel** [comment]
Not a bug. Please use the dedicated feature request category in the forum if you do not want to contribute this yourself.

**Comment by Neustradamus** [comment]
@e323w: You account is not public, it is not possible to see https://github.com/e323w/openwrt-xiaomi-r4ag-v2.
