### ISSUE TITLE
ath10k-4.19 to ath10k-5.13 error compile in snapshot code

### ISSUE THREAD

**Issue by Oozil** [openwrt/openwrt#11754]
### Describe the bug

drivers/usb/core/message.c:2284:33: warning: 'struct usb_cdc_parsed_header' declared inside parameter list will not be visible outside of this definition or declaration
 2284 | int cdc_parse_cdc_header(struct usb_cdc_parsed_header *hdr,
      |                                 ^~~~~~~~~~~~~~~~~~~~~
drivers/usb/core/message.c: In function 'cdc_parse_cdc_header':
drivers/usb/core/message.c:2301:34: error: invalid application of 'sizeof' to incomplete type 'struct usb_cdc_parsed_header'
 2301 |         memset(hdr, 0x00, sizeof(struct usb_cdc_parsed_header));
      |                                  ^~~~~~
drivers/usb/core/message.c:2302:12: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2302 |         hdr->phonet_magic_present = false;
      |            ^~
drivers/usb/core/message.c:2332:28: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2332 |                         hdr->usb_cdc_country_functional_desc =
      |                            ^~
drivers/usb/core/message.c:2345:28: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2345 |                         hdr->usb_cdc_acm_descriptor =
      |                            ^~
drivers/usb/core/message.c:2358:28: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2358 |                         hdr->usb_cdc_call_mgmt_descriptor =
      |                            ^~
drivers/usb/core/message.c:2364:28: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2364 |                         hdr->usb_cdc_dmm_desc =
      |                            ^~
drivers/usb/core/message.c:2384:28: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2384 |                         hdr->usb_cdc_ncm_desc = (struct usb_cdc_ncm_desc *)buffer;
      |                            ^~
drivers/usb/core/message.c:2390:28: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2390 |                         hdr->usb_cdc_mbim_desc = (struct usb_cdc_mbim_desc *)buffer;
      |                            ^~
drivers/usb/core/message.c:2395:28: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2395 |                         hdr->usb_cdc_mbim_extended_desc =
      |                            ^~
drivers/usb/core/message.c:2398:22: error: 'CDC_PHONET_MAGIC_NUMBER' undeclared (first use in this function)
 2398 |                 case CDC_PHONET_MAGIC_NUMBER:
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/core/message.c:2398:22: note: each undeclared identifier is reported only once for each function it appears in
drivers/usb/core/message.c:2399:28: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2399 |                         hdr->phonet_magic_present = true;
      |                            ^~
drivers/usb/core/message.c:2415:12: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2415 |         hdr->usb_cdc_union_desc = union_header;
      |            ^~
drivers/usb/core/message.c:2416:12: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2416 |         hdr->usb_cdc_header_desc = header;
      |            ^~
drivers/usb/core/message.c:2417:12: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2417 |         hdr->usb_cdc_mdlm_detail_desc = detail;
      |            ^~
drivers/usb/core/message.c:2418:12: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2418 |         hdr->usb_cdc_mdlm_desc = desc;
      |            ^~
drivers/usb/core/message.c:2419:12: error: invalid use of undefined type 'struct usb_cdc_parsed_header'
 2419 |         hdr->usb_cdc_ether_desc = ether;
      |            ^~
make[6]: *** [scripts/Makefile.build:289: drivers/usb/core/message.o] Error 1
make[5]: *** [scripts/Makefile.build:552: drivers/usb/core] Error 2
make[4]: *** [scripts/Makefile.build:552: drivers/usb] Error 2
make[3]: *** [Makefile:1903: drivers] Error 2
make[3]: Leaving directory '/home/Oozil/Music/openwrt-24-12-2022-k5.15.85/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.15.85'
make[2]: *** [Makefile:112: /home/Oozil/Music/openwrt-24-12-2022-k5.15.85/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_nand/ath10k-ct-2019-06-13-f0aa8130/.built] Error 2
make[2]: Leaving directory '/home/Oozil/Music/openwrt-24-12-2022-k5.15.85/openwrt/package/kernel/ath10k-ct'
time: package/kernel/ath10k-ct/compile#3.46#1.12#4.49
    ERROR: package/kernel/ath10k-ct failed to build.
make[1]: *** [package/Makefile:116: package/kernel/ath10k-ct/compile] Error 1
make[1]: Leaving directory '/home/Oozil/Music/openwrt-24-12-2022-k5.15.85/openwrt'
make: *** [/home/Oozil/Music/openwrt-24-12-2022-k5.15.85/openwrt/include/toplevel.mk:231: package/kernel/ath10k-ct/compile] Error 2

### OpenWrt version

snapshot

### OpenWrt target/subtarget

ath79

### Device

archer c7 v2

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by stintel** [comment]
As suggested in https://github.com/openwrt/packages/issues/20247, reach out to our community.
