### ISSUE TITLE
dnsmasq cannot read dhcp-hostsfile

### ISSUE THREAD

**Issue by yaotthaha** [openwrt/openwrt#11801]
### Describe the bug

I have set ```dhcp-hostsfile``` in ```/etc/dnsmasq.conf```, but when I reload dnsmasq, syslog shows 
```
daemon.err dnsmasq[1]: cannot read ***/dnsmasq.conf: no such file or directory.```
```
My file exists and has permission 666 (rw-rw-rw-)

### OpenWrt version

r20028-43d71ad93e

### OpenWrt target/subtarget

ramips/mt7621

### Device

Newifi-D2

### Image kind

Official downloaded image

### Steps to reproduce

```
cat <<-EOF >> /etc/dnsmasq.conf
dhcp-hostsfile=/tmp/as-dnsmasq.conf
dhcp-option=tag:as,3,10.0.0.3
dhcp-option=tag:as,6,10.0.0.3
EOF
```
```
cat <<-EOF > /tmp/as-dnsmasq.conf
7a:xx:xx:xx:xx:xx,set:as
8b:xx:xx:xx:xx:xx,set:as
EOF
```
```
service dnsmasq restart
```
```
logread
```
```
cat <<-EOF > /tmp/as-dnsmasq.conf
7a:xx:xx:xx:xx:xx,set:as
8b:xx:xx:xx:xx:xx,set:as
63:xx:xx:xx:xx:xx,set:as
EOF
```
```
service dnsmasq reload
```
```
logread
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by yaotthaha** [comment]
This may be related to this issue: #10625

**Comment by dave14305** [comment]
Looks like a ujail issue for sure, but the preferred method would be to set the `dhcphostsfile` option in uci. However, it still doesn’t look like dnsmasq.init will add that path as a ujail mount. So still needs some fixing.

**Comment by yaotthaha** [comment]
I solve this problem. It need to add ```list dhcpscript '/somewhere'``` in ```/etc/config/dhcp```

**Comment by af3556** [comment]
FYI this indeed was a ujail issue, and as of OpenWRT 25.12.4 setting the dhcphostsfile option via uci works (the init script sorts out jail visitation rights):
```
uci set dhcp.@dnsmasq[0].dhcphostsfile='/etc/dhcp-hosts'
```
