### ISSUE TITLE
Multiple OpenSSL vulnerabilities

### ISSUE THREAD

**Issue by ichfybji** [openwrt/openwrt#119]
The CC OpenSSL packages are now massively outdated, upstream releases 1.0.2h, 1.0.2i and 1.0.2j have been ignored. See https://github.com/openwrt/openwrt/commit/2933b2f1224d0274de4e298ee7e6afdb2dbd180e

Keeping OpenSSL updated is _not_ optional

**Comment by ichfybji** [comment]
Developers: Please comment on why this is seemingly a non-issue to you instead of deleting the issue.

**Comment by wigyori** [comment]
Please see 29fcc94c9acf1f789ad25fc460fb46aa740b68a0 . A package build is in-flight.
