### ISSUE TITLE
Disable ipv6 support

### ISSUE THREAD

**Issue by 8680** [openwrt/openwrt#11926]
### Describe the bug

`Global build settings`  can't find `enable ipv6 support` this option，How to Disable ipv6 support?

### OpenWrt version

master

### OpenWrt target/subtarget

rockchip

### Device

R2S

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
This option has been discontinued and is not supported anymore.

**Comment by 8680** [comment]
> This option has been discontinued and is not supported anymore.

may I ask how to close ipv6

**Comment by jow-** [comment]
Please use the forum for general configuration support.
