### ISSUE TITLE
PPPoE trickling WAN errors since move to 22.03.3

### ISSUE THREAD

**Issue by mash8336** [openwrt/openwrt#11939]
### Describe the bug

1-3% error rate on WAN since upgrade

Clearly visible on my [WAN monitor](https://www.thinkbroadband.com/broadband/monitoring/quality/share/abe62ae49a17b1c3d7a8ba6ed2672966f5ddaaa4)

### OpenWrt version

r20028-43d71ad93e

### OpenWrt target/subtarget

lantiq/xrx200

### Device

BT Home Hub 5A

### Image kind

Official downloaded image

### Steps to reproduce

Errors are constant

### Expected behaviour

Error free as was the case on 19.07.10

### Additional info

Don't know if relevant but I've completely disable ipv6 and DHCP services

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by mash8336** [comment]
I reverted back to 19.07.10, errors now gone. Everything backed up so can swap back if you need some debugs etc.
![image](https://user-images.githubusercontent.com/44288297/216854115-59cc0b5b-25f5-4abf-92ea-33abefe890de.png)

**Comment by mash8336** [comment]
It's packet loss not latency, while playing PUBG the packet loss constantly bobs between 0 and 3 %

I'll try these settings but may have to wait to the weekend as is a bit of a pain...

![image](https://user-images.githubusercontent.com/44288297/216984817-c3f40059-a01a-4050-9045-78451074afd9.png)

**Comment by daverof** [comment]
> It's packet loss not latency

No, your test is only for incoming ICMP pings which are not prioritised with your current setup, which is presenting itself as "loss", but none of your normal packets are experiencing loss - unless you've tested for that independently.

**Comment by mash8336** [comment]
I "test" with PUBG every evening for an hour or two, equally affected as far as I can tell

PUBG has data quality stats constantly running on the screen during the games, time of day or local broadband load seems to not affect the values.

**Comment by daverof** [comment]
Some people have reported a better outcome when reverting to 22.03.2, so I recommend trying it on your next test.

**Comment by mash8336** [comment]
Upgraded to 22.03.2, restored the 22.03.3 archive and it's now running error free.

Unless you need some more information from my setup I'll stay with 22.03.2 and live with that for a while.

**Comment by abajk** [comment]
Packet loss happens over wired or wireless connectivity?

**Comment by mash8336** [comment]
Wired, waste of time fault finding in wireless.

Graphs above are monitored from the Internet excluding my internal LAN components entirely.
