### ISSUE TITLE
Incorrect interface byte count

### ISSUE THREAD

**Issue by flaleo** [openwrt/openwrt#11957]
### Describe the bug

Interface stats appear to be incorrect, byte count growing too slowly.
I tried downloading a 10GB file and the interface byte count increased by less than 1GB more.

### OpenWrt version

r20028-43d71ad93e

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Linksys E8450 (UBI)

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by LGA1150** [comment]
Is hardware flow offloading enabled?

**Comment by flaleo** [comment]
Yes, both hardware and software

**Comment by LGA1150** [comment]
If hardware offload is enabled, packets no longer pass through CPU so the packet statistics (on the CPU side) will be incorrect.
You can use `ethtool -S <interface name>` to poll statistics from the hardware.
