### ISSUE TITLE
can not add domain

### ISSUE THREAD

**Issue by tn4417** [openwrt/openwrt#12000]
### Describe the bug

![image](https://user-images.githubusercontent.com/46041558/218482693-6ead5705-4a4a-4360-bc5b-f9390eace753.png)

domain ftp.vn-zoom.com can not added.
error:

root@OpenWrt:~# ipset add "tn4417host" 'ftp.vn-zoom.com'
ipset v7.15: Syntax error: cannot parse ftp.vn: resolving to IPv4 address failed

### OpenWrt version

r20028-43d71ad93e

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link TL-WR1043ND v3

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
DNS resolve issue, not a bug
