### ISSUE TITLE
23.03.3 can't update software list

### ISSUE THREAD

**Issue by weskerjiang** [openwrt/openwrt#12013]
### Describe the bug

I can't update list from luci even can't update from ssh using opkg update,still shows the error message

Executing package manager
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/targets/ath79/nand/packages/Packages.gz
*** Failed to download the package list from https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/targets/ath79/nand/packages/Packages.gz

Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/base/Packages.gz
*** Failed to download the package list from https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/base/Packages.gz

Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/luci/Packages.gz
*** Failed to download the package list from https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/luci/Packages.gz

Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/packages/Packages.gz
*** Failed to download the package list from https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/packages/Packages.gz

Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/routing/Packages.gz
*** Failed to download the package list from https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/routing/Packages.gz

Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/telephony/Packages.gz
*** Failed to download the package list from https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/telephony/Packages.gz
Errors
Failed to send request: Operation not permitted
Failed to send request: Operation not permitted
Failed to send request: Operation not permitted
Failed to send request: Operation not permitted
Failed to send request: Operation not permitted
Failed to send request: Operation not permitted
Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_core https://downloads.openwrt.org/releases/22.03.3/targets/ath79/nand/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_base https://downloads.openwrt.org/releases/22.03.3/packages/mips_24kc/base). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_luci https://downloads.openwrt.org/releases/22.03.3/packages/mips_24kc/luci). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_packages https://downloads.openwrt.org/releases/22.03.3/packages/mips_24kc/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_routing https://downloads.openwrt.org/releases/22.03.3/packages/mips_24kc/routing). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_telephony https://downloads.openwrt.org/releases/22.03.3/packages/mips_24kc/telephony). Skipping.
 * opkg_download: Failed to download https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/targets/ath79/nand/packages/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/base/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/luci/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/packages/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/routing/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/packages/mips_24kc/telephony/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.
The opkg update command failed with code 6.

### OpenWrt version

23.03.3

### OpenWrt target/subtarget

/etc/opkg/distfeed

### Device

netgear wndr4300

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ynezz** [comment]
> opkg_download: Check your network settings and connectivity.

It works here just fine

```
$ curl --head https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.3/targets/ath79/nand/packages/Packages.gz
HTTP/2 200 
server: nginx/1.18.0
date: Wed, 15 Feb 2023 20:34:32 GMT
content-type: application/octet-stream
content-length: 89709
last-modified: Wed, 04 Jan 2023 23:36:31 GMT
etag: "63b60d7f-15e6d"
strict-transport-security: max-age=31536000
x-tuna-mirror-id: neomirrors
accept-ranges: bytes
```
