### ISSUE TITLE
openssl fails to build on powerpc targets

### ISSUE THREAD

**Issue by MoetaYuko** [openwrt/openwrt#12048]
### Describe the bug

build fails after upgrading to 3.0:

https://downloads.openwrt.org/snapshots/faillogs/powerpc_464fp/base/openssl/
https://downloads.openwrt.org/snapshots/faillogs/powerpc_8548/base/openssl/

cc: @cotequeiroz 

### OpenWrt version

snapshot

### OpenWrt target/subtarget

powerpc

### Device

official sdk

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by cotequeiroz** [comment]
Hi. Thanks for the report. I mixed up Linux arch with OpenWrt `s/ppc/powerpc/`.

 I’m running a build for ppc at the moment—in case there’s something else causing a failure—and will send a fix in about 9 hours. Arc is not building either, and I finished testing the fix for it already.

**Comment by pkgadd** [comment]
https://github.com/openwrt/openwrt/pull/12046
