### ISSUE TITLE
Xiaomi 4c 300mbps router but 40mhz bandwith is unsupported

### ISSUE THREAD

**Issue by xiv3r** [openwrt/openwrt#12080]
### Describe the bug

It only got 20mhz with max of 72.2 Mbit/s rate also 40mhz bandwith is unsupported...

### OpenWrt version

r20028-43d71ad93e

### OpenWrt target/subtarget

ramips/mt76x8

### Device

Xiaomi mi router 4c

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
40MHz bandwidth by default is available only if no other AP is around aka greenfield.
You are unlikely to get any transfer speed improvement forcing 40MHz in busy area, usually it even gets worse.
In addition you need 2-antenna client to have 300Mbps rate (or 3-antenna in both ends for 450)
