### ISSUE TITLE
ubnt_unifi-ap-lr: eth0 should be WAN, not LAN

### ISSUE THREAD

**Issue by selfhoster1312** [openwrt/openwrt#12083]
### Describe the bug

Trying to flash Unifi AP-LR. On first boot eth0 is considered a LAN interface where DHCP server is enabled. However, this device only has a single RJ45 port so treating it as LAN and serving DHCP requests will pollute the existing network with broken DHCP answers.

As the device only has one port, it should be treated as WAN and not respond to DHCP queries. I don't know if that's standard for other boards, but eth0 should probably be configured as DHCP client by default so that it can be reached/configured on the network after flashing.

Doing so would enable to clean up the [docs page](https://openwrt.org/toh/ubiquiti/unifi_ap) for this device which is filled with various configuration advice on how to counteract eth0 being treated as LAN by default.

### OpenWrt version

r22130-524704e677

### OpenWrt target/subtarget

ath79/generic

### Device

Ubiquiti UniFi AP LR

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by obsy** [comment]
All devices with one port are treated as lan. Since Wi-Fi is disabled, setting this port as wan would make it impossible to access the router. Just set it up as you need. 
Not a bug.

**Comment by selfhoster1312** [comment]
That makes sense. I'll have to build my own images then. Thanks!
