### ISSUE TITLE
[binutils] Recent update of binutils to 2.40 has unmet dependency

### ISSUE THREAD

**Issue by VA1DER** [openwrt/openwrt#12144]
### Describe the bug

A [recent commit](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=a03076cc392b67c8342aac2017f8ac903c983e59) updated binutils to 2.40.  The `readelf` tool in binutils now has a dependency on libmsgpackc.so.2.  The build system, however, needs to be told of the dependency or it will not build.  This has broken all-userland-package builds for the last four days and binutils has now disappeared off all snapshot targets.

Recommend making the already-existing msgpack-c library a dependency for binutils:

```
--- a/package/devel/binutils/Makefile	2023-03-09 10:55:18.596795808 -0400
+++ b/package/devel/binutils/Makefile	2023-03-09 11:01:24.780701544 -0400
@@ -53,11 +53,11 @@
 
 define Package/binutils
   SECTION:=devel
   CATEGORY:=Development
   TITLE:=binutils
-  DEPENDS:=+objdump +ar
+  DEPENDS:=+objdump +ar +msgpack-c
   ALTERNATIVES:=200:/usr/bin/strings:/usr/bin/binutils-strings
 endef
 
 define Package/objdump
   SECTION:=devel
```

### OpenWrt version

MASTER

### OpenWrt target/subtarget

All

### Device

All

### Image kind

Official downloaded image

### Steps to reproduce

make package/binutils/compile

### Actual behaviour

The build system recognizes the unmet dependency for libmsgpack-c upon building binutils and fails with that error.

### Expected behaviour

Compiles.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by VA1DER** [comment]
@hauke @nbd168 Sorry, forgot to tag you in the report.

**Comment by trippleflux** [comment]
Checkout this [PR](https://github.com/openwrt/openwrt/pull/12141). I think it should fix it.

I was also having the same issue for binutils and libbfd and added +msgpack-c into both of them but it will failed at the end of the OpenWrt X86_64 build process mentioning something about binutils and msgpack-c (didn't saved the log).

I think that PR is more proper way to fix it.

**Comment by VA1DER** [comment]
Disabling msgpack [inactivates the ability for readelf to display messagepack comments](https://marc.info/?l=binutils&m=164737371819901).  msgpack-c is a 10kilobyte lib, and it's already an available package.  Is there a reason why not to make binutils dependent on it?

**Comment by VA1DER** [comment]
PTBs didn't agree.  Fixed by https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=d9a00c5e2d54443bacddba5ce382ccc690156c81
