### ISSUE TITLE
TP Link WA901ND Targets

### ISSUE THREAD

**Issue by jwsi** [openwrt/openwrt#122]
Hi,

Trying to build for my WA901ND v4 and when I target WA901N/ND in make menuconfig and proceed to compile, no images specific to any version of this device are produced. Instead I get files ending in .squashfs and some other generic files.
Advice?

Help would be much appreciated.
James

**Comment by tt33415366** [comment]
The generated images is too large?

**Comment by jwsi** [comment]
Well I originally thought that so I stripped out packages like LuCi etc...
and just went with a stock build but still no luck.

James
