### ISSUE TITLE
mtd write /tmp/factory.bin /dev/mtd2 Could not open mtd device: mtd2

### ISSUE THREAD

**Issue by shripadrayewar** [openwrt/openwrt#12216]
### Describe the bug

In the openwrt19 , mtd write /tmp/factory.bin /dev/mtd2 can be used, but in openwrt21.05 it will report an error

mtd write /tmp/factory.bin /dev/mtd2
Could not open mtd device: mtd2

as well as https://github.com/openwrt/openwrt/issues/9849 referenced from this issues,
i tried  mtd -r write /tmp/factory.bin factory
but it is also not working

### OpenWrt version

r0-f7c460685b

### OpenWrt target/subtarget

ramips/mt7621

### Device

PBR-M1

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Once openwrt is installed you should use sysupgrade.

Factory image is with vendor headers to load via vendor upgrade tool like web or tftp.

**Comment by shripadrayewar** [comment]
Hi Brada,
Im using sysupgrade for firmware upgrade, but need to write mac address on factory bock.
our vendor is providing 1 script to write mac address on factory block, but while writing its giving error.
same script to write mac on factory block is working perfectly on wrt 18 & 19. 
attaching script for reference
looking forward for your help on the issue.
[write_mac.txt](https://github.com/openwrt/openwrt/files/11021293/write_mac.txt)

**Comment by brada4** [comment]
Look for`brick` [here](https://openwrt.org/toh/meraki/mr16)

**Comment by shripadrayewar** [comment]
Thanks, 
Will test it out tomorrow

**Comment by shripadrayewar** [comment]
Issue resolved
Issue was with DTS file, on DTS file, permission was read only for mtd block
