### ISSUE TITLE
mac80211: ath11k: sync with ath-next: Xiaomi AX9000 QCN9024 160MHz issue

### ISSUE THREAD

**Issue by dick902** [openwrt/openwrt#12229]
### Describe the bug

After apply mac80211: ath11k sync with ath-next update on Xiaomi AX9000
The PCI Wifi QCN9024 is missing 160MHz Wifi option.

 

### OpenWrt version

r22344-ca330cac92

### OpenWrt target/subtarget

ipq807x/generic

### Device

Xiaomi AX9000

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by Gost6** [comment]
The qnap qhora-301w also is affected, missing option for 160mhz  channels width.

**Comment by robimarko** [comment]
This should fix it #12274

**Comment by Soromeister** [comment]
Confirmed fixed in build `r22475-936df715de`

**Comment by dick902** [comment]
Confirm fixed r22475-936df715de
