### ISSUE TITLE
uclient-fetch does not send Content-Length

### ISSUE THREAD

**Issue by axet** [openwrt/openwrt#12318]
### Describe the bug

using uclient-fetch with --post-data="string" causing server to crash due to Content-Length header is missing.

### OpenWrt version

22.03.3

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link TL-WR842N/ND v2

### Image kind

Self-built image

### Steps to reproduce

root@OpenWrt:~# wget -O- --post-data="kkk" http://10.10.5.4/apply.cgi?formPasswordAuth
Downloading 'http://10.10.5.4/apply.cgi?formPasswordAuth'
Connecting to 10.10.5.4:80
(null)                   0   - stalled -
Connection reset prematurely

### Actual behaviour

Using tcpdump you can see here is no Content-Length:

      POST /apply.cgi?formPasswordAuth HTTP/1.1
      Host: 10.10.5.4
      User-Agent: uclient-fetch
      Content-Type: application/x-www-form-urlencoded
      Transfer-Encoding: chunked

Using wget it shows Content-Length:

      POST /apply.cgi?formPasswordAuth HTTP/1.1
      Host: 10.10.5.4
      User-Agent: Wget/1.21.3
      Accept: */*
      Accept-Encoding: identity
      Connection: Keep-Alive
      Content-Type: application/x-www-form-urlencoded
      Content-Length: 3

### Expected behaviour

Based on https://www.rfc-editor.org/rfc/rfc2616#section-14.13 Content-Length is required header field.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
It sends zero-length chunk, meaning message ends there and no size needed to be specifid.

**Comment by axet** [comment]
@brada4

> Applications SHOULD use this field to indicate the transfer-length of the message-body, unless this is prohibited by the rules in [section-4.4](https://www.rfc-editor.org/rfc/rfc2616#section-4.4)

Message body is a post data of course.
