### ISSUE TITLE
RB750gr3 22.03.3 reboot command does nothing

### ISSUE THREAD

**Issue by jsalatiel** [openwrt/openwrt#12341]
### Describe the bug

Reboot command does nothing on RB750GR3 running 22.03.3-ramips-mt7621-mikrotik_routerboard-750gr3.
Reboot on luci also does nothing.
reboot -f  via SSH works.

### OpenWrt version

r20028-43d71ad93e

### OpenWrt target/subtarget

ramips/mt7621

### Device

MikroTik RouterBOARD 750Gr3

### Image kind

Official downloaded image

### Steps to reproduce

Install
run reboot using SSH or via Luci

### Actual behaviour

Does nothing

### Expected behaviour

The system should be rebooted

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by giorgiga** [comment]
I have 23.3.04 and it works for me (sorry, I skipped 20.3.03 so I can't verify).

Does your router behave as expected if you upgrade to .04?

````
~ $ ssh root@192.168.10.1


BusyBox v1.35.0 (2023-04-08 16:10:34 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 22.03.4, r20123-38ccc47687
 -----------------------------------------------------
root@router:~# reboot
root@router:~# Connection to 192.168.10.1 closed by remote host.
$ ssh root@192.168.10.1


BusyBox v1.35.0 (2023-04-08 16:10:34 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 22.03.4, r20123-38ccc47687
 -----------------------------------------------------
root@router:~# uptime
 21:10:41 up 0 min,  load average: 1.15, 0.29, 0.10
````
