### ISSUE TITLE
mac80211: ath11k: No actual 160MHz support

### ISSUE THREAD

**Issue by Soromeister** [openwrt/openwrt#12358]
### Describe the bug

While 160MHz is selectable in the OpenWRT option, the radio will actually function at 80MHz. This is easily revealed when doing a scan via WiFi Scanner app since it doesn't take the full spectrum, only half of it.

### OpenWrt version

r22528-0c53801968

### OpenWrt target/subtarget

ipq807x/generic

### Device

Xiaomi AX9000

### Image kind

Official downloaded image

### Steps to reproduce

On Radio3, configure a WiFi for 160MHz. Name it a unique name.
Reboot router.
Open the WiFi Scanner app on phone.
Notice the width of the signal only covers 80MHz

### Actual behaviour

Signal of the AP is 80MHz instead of 160MHz. Noticeable in both the `Channel Graph` (width is half of what is supposed to be) and the `Access Points` list, being advertised as 80MHz.

### Expected behaviour

Signal of the AP should be 160MHz.

### Additional info

Config extract:
```
config wifi-device 'radio3'
	option type 'mac80211'
	option path 'soc/20000000.pci/pci0000:00/0000:00:00.0/0000:01:00.0'
	option channel 'auto'
	option channels '64, 60, 56, 52, 48, 44, 40, 36'
	option band '5g'
	option htmode 'HE160'
	option country 'US'
	option distance 'auto'
	option cell_density '3'

config wifi-iface 'default_radio3'
	option device 'radio3'
	option network 'lan'
	option mode 'ap'
	option ssid 'WiFi Name'
	option encryption 'sae-mixed'
	option isolate '1'
	option ifname 'r3-gaming'
	option skip_inactivity_poll '1'
	option disassoc_low_ack '0'
	option key 'P@ssw0rd'
	option time_advertisement '2'
	option time_zone 'CET-1CEST,M3.5.0,M10.5.0/3'
```

### Diffconfig

```text
-ash: ./scripts/diffconfig.sh: not found
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by AlexeiGHub** [comment]
On my Redmi AX6 with clients(ax200 and smarphone) wich support 160MHz all OK 2400MBit/sec.

**Comment by st7105** [comment]
AX3600 same problem after ath11-next sync commit.
