### ISSUE TITLE
The latest stable version of openwrt-22.03.4 prompts an error when compiling!

### ISSUE THREAD

**Issue by openwrtdiy** [openwrt/openwrt#12362]
### Describe the bug

kokang@virtual-machine:~/openwrt-22.03.4$ make menuconfig
WARNING: Makefile 'package/feeds/luci/luci-app-apinger/Makefile' has a dependency on 'apinger-rrd', which does not exist

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

### OpenWrt version

openwrt-22.03.4

### OpenWrt target/subtarget

x86

### Device

x86

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
You need to run feeds scripts after switching to branch.
