### ISSUE TITLE
[22.03] asus ax53u: no led indicators found on wifi (2.4 and 5GHz)

### ISSUE THREAD

**Issue by saber716rus** [openwrt/openwrt#12380]
### Describe the bug

updated to 22.03.4,  but the setup is wrong. I tried to configure it, but the configuration does not lead to anything.

### OpenWrt version

r20123-38ccc47687

### OpenWrt target/subtarget

ramips/mt7621

### Device

ASUS RT-AX53U

### Image kind

Official downloaded image

### Steps to reproduce

try to configure the LED indicators via Luci 

### Actual behaviour

![Screenshot_2023-04-12-21-17-10-905_ru yandex searchplugin](https://user-images.githubusercontent.com/22714555/231548544-8283d468-ec55-486f-9149-c42d7993b971.jpg)
![Screenshot_2023-04-12-21-17-03-603_ru yandex searchplugin](https://user-images.githubusercontent.com/22714555/231548557-5b99fdce-159c-4e50-950b-e3280b913d17.jpg)
these are the settings and non-working indicators

### Expected behaviour

successfully configured indicators, via luci

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by lukasz1992** [comment]
1. 22.03 branch of mt76 does not have needed patches backported
2. openwrt 22.03 does not use latest commit of 22.03 branch of mt76

**Comment by saber716rus** [comment]
> 1. 22.03 branch of mt76 does not have needed patches backported
> 2. openwrt 22.03 does not use latest commit of 22.03 branch of mt76

when will this problem be fixed?

**Comment by Znevna** [comment]
It's fixed in master. You can use firmware selector to build an image with LuCI included.

**Comment by saber716rus** [comment]
as I understand it, it will be updated to the snapshot version. Right? How is the upgrade and when is the fix ported to the stable release?

**Comment by saber716rus** [comment]
when will there be a fix in the stable branch?

**Comment by saber716rus** [comment]
as soon as there is a fix, I will close it. How often is the stable openwrt branch published?

**Comment by Djfe** [comment]
Usually ~4 times a year, I think.
Last ones were in April and January.
The next thing is going to be openwrt 23 release probably and that will also include a full update of the wifi driver.
There might be another small 22 release for fixing booting on ipq40xx targets. but it's highly unlikely they'd update the wifi driver for that/include more backports

**Comment by saber716rus** [comment]
> Usually ~4 times a year, I think.
> Last ones were in April and January.
> The next thing is going to be openwrt 23 release probably and that will also include a full update of the wifi driver.
> There might be another small 22 release for fixing booting on ipq40xx targets. but it's highly unlikely they'd update the wifi driver for that/include more backports

looks like you were right. The commit seems to have hit version 23.05.

**Comment by Djfe** [comment]
you may lose the issue now
