### ISSUE TITLE
[FeatureRequest] There is no 4k sectors alignment when writing the firmware img to SSD. This is not good for SSD.

### ISSUE THREAD

**Issue by fannwong001** [openwrt/openwrt#12395]
### Describe the bug

There is no 4k or 2k sectors alignment when writing the firmware img to SSD.
Now the first partition's start sector number is 512 sectors. And the second partition's start sector number is not a multiple of 2048 sectors either.Though it is a multiple of 4096 bytes, but it will cause slow performance.
Both the legacy and efi ext4 firmware exist.

### OpenWrt version

r22493-5a8741aee9

### OpenWrt target/subtarget

x86/64

### Device

ASUS

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
I used fdisk against current releases and snapshot and ext4 partitions are nicely 4K aligned. Only efiboot is stuffed before 512 1/2k blocks and turns out rather small.

**Comment by Mijzelf** [comment]
> Now the first partition's start sector number is 512
512 is a multiple of 8.

**Comment by fannwong001** [comment]
> > Now the first partition's start sector number is 512
> 
> 512 is a multiple of 8.

Sorry, I made a mistake and I have modified it.

**Comment by brada4** [comment]
Dear, to optimally support 4kB sectors - partition should start at position divisible by eight (512 octet sectors), which is true for all published images, and your bug report. 
```
fdisk -l openwrt-x86-64-generic-ext4-combined.img 
Disk openwrt-x86-64-generic-ext4-combined.img: 120.5 MiB, 126353408 bytes, 246784 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xcc856286

Device                                    Boot Start    End Sectors  Size Id Type
openwrt-x86-64-generic-ext4-combined.img1 *      512  33279   32768   16M 83 Linux
openwrt-x86-64-generic-ext4-combined.img2      33792 246783  212992  104M 83 Linux
```

**Comment by fannwong001** [comment]
> Dear, to optimally support 4kB sectors - partition should start at position divisible by eight (512 octet sectors), which is true for all published images, and your bug report. 
> 
> ```
> 
> fdisk -l openwrt-x86-64-generic-ext4-combined.img 
> 
> Disk openwrt-x86-64-generic-ext4-combined.img: 120.5 MiB, 126353408 bytes, 246784 sectors
> 
> Units: sectors of 1 * 512 = 512 bytes
> 
> Sector size (logical/physical): 512 bytes / 512 bytes
> 
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> Disklabel type: dos
> 
> Disk identifier: 0xcc856286
> 
> 
> 
> Device                                    Boot Start    End Sectors  Size Id Type
> 
> openwrt-x86-64-generic-ext4-combined.img1 *      512  33279   32768   16M 83 Linux
> 
> openwrt-x86-64-generic-ext4-combined.img2      33792 246783  212992  104M 83 Linux
> 
> ```
> 
> 

That is 4k bytes alignment, but not 4k sectors alignment. 4k sectors is better.

**Comment by Mijzelf** [comment]
> That is 4k bytes alignment, but not 4k sectors alignment. 4k sectors is better
Why? Virtually every filesystem uses clusters of 4k bytes. So why would the start address of the containing partition matter, as long as it's 4k byte aligned?

**Comment by Spudz76** [comment]
Because of eraseblocks, and secondarily sometimes how the mapper chip does its banking layout.  Also every SSD optimization howto says it must be at least on 4K, which yes 512 satisfies.  Some prefer 1MB alignment of partition starts (which, 2048 satisfies, and the default for every current partition software).  Misalignment could cause the mapper chip having to read two physical flash blocks to get 4K, or erase and rewrite two physical flash blocks to update 4K, leading to degraded speed and wasted write cycles and cache churn where it might get more cache-hits without the wasted reads.

On a magnetic disk I usually set gdisk to align by 8 since it definitely doesn't care about 1MB-aligned striping.  The 1MB comes from the blocksize of some SSD underlying flash layout / striping across the chips / what type of chips they are / etc.

**Comment by fannwong001** [comment]
> Because of eraseblocks, and secondarily sometimes how the mapper chip does its banking layout.  Also every SSD optimization howto says it must be at least on 4K, which yes 512 satisfies.  Some prefer 1MB alignment of partition starts (which, 2048 satisfies, and the default for every current partition software).  Misalignment could cause the mapper chip having to read two physical flash blocks to get 4K, or erase and rewrite two physical flash blocks to update 4K, leading to degraded speed and wasted write cycles and cache churn where it might get more cache-hits without the wasted reads.
> 
> 
> 
> On a magnetic disk I usually set gdisk to align by 8 since it definitely doesn't care about 1MB-aligned striping.  The 1MB comes from the blocksize of some SSD underlying flash layout / striping across the chips / what type of chips they are / etc.
> 
> 
> 
> edit: (I have not heard of aligning to 4096 start == 2MB)

2048 or 4096 perform better, just test result.

**Comment by brada4** [comment]
You can re-create overlay partition in different place, or better create additional partitions for data as manufacturer recommends. Writes in filesystem will happen at 4k offsets in 4k blocks anyway.

**Comment by fannwong001** [comment]
> You can re-create overlay partition in different place, or better create additional partitions for data as manufacturer recommends. Writes in filesystem will happen at 4k offsets in 4k blocks anyway.

I find that it costs more cpu when install the openwrt to ssd than usb device.

**Comment by brada4** [comment]
Would not be a big waste to align /overlay to 2MB mimicking Windows, but the alignment requirement >4kB is not something generally hinted by SSD manufacturers. Can you get some measurements either relocating /overlay or adding aligned-your-way partition after one you have (along with SSD name from dmesg/lsblk etc)?

**Comment by fannwong001** [comment]
> Would not be a big waste to align /overlay to 2MB mimicking Windows, but the alignment requirement >4kB is not something generally hinted by SSD manufacturers. Can you get some measurements either relocating /overlay or adding aligned-your-way partition after one you have (along with SSD name from dmesg/lsblk etc)?

Sorry I can not. I have replaced the ssd with a usb device. ssd is now used for other functions. I do not want to mess around anymore.

**Comment by Spudz76** [comment]
> alignment requirement >4kB is not something generally hinted by SSD manufacturers

Yeah and ~5K mile oil changes aren't hinted by vehicle manufacturers either but your stuff will burn out right around the end of warranty (which the manufacturer loves, right?) unless you ignore their propaganda and do the science yourself.  Just because something works for the warranty target doesn't mean it's ideal.

**Comment by brada4** [comment]
Following analogy you are suggesting to cut off one cylinder for oil economy. Show that improves acceleration and maintains top speed.

**Comment by Spudz76** [comment]
No, my analogy is perfect. :)  You spend more money to protect the longevity, just like "spending" some space for longevity (and a couple MB is not even as expensive as new oil 3x as often as "manufacturer suggested", we're not wasting two thirds of an SSD).

**Comment by Spudz76** [comment]
Internal 4kb alignment doesn't matter if the device underneath the mapper chip is in 1MB stripes.  You still must align the partition starts to 1MB then for optimal treatment of the eraseblocks and such.  SSDs don't generally advertise their actual layout and just be lazy and say 4kb which isn't technically true but might be functionally true.
