### ISSUE TITLE
Zyxel XGS1250-12 Switch does not advertize 2500baseT Full and 5000baseT Full on port 9,10 and 11

### ISSUE THREAD

**Issue by chapichapo** [openwrt/openwrt#12507]
### Describe the bug

On the Zyxel XGS1250-12 Switch, after installing OpenWRT 22.03.4, the switch does not advertise 2500baseT Full and 5000baseT Full on port 9,10 and 11 although those ports support those speed. This is preventing the switch to connect at those speed even if the linked device support those speed and the link gets downgraded to 1000baseT Full.
Note: as a temporary workaround, by using ethtool, the default advertised link speed can be changed.

### OpenWrt version

22.03.4

### OpenWrt target/subtarget

realtek/rtl930x

### Device

Zyxel XGS1250-12 Switch

### Image kind

Official downloaded image

### Steps to reproduce

Install OpenWRT on a Zyxel XGS1250-12 Switch and connect a device that supports 2500baseT Full or 5000baseT on port 9,10 and 11.

### Actual behaviour

The switch will downgrade the link to 1000baseT.

### Expected behaviour

The link should use 2500baseT Full or 5000baseT as supported by the device connected.

### Additional info

Running ethtool to change the advertised speed allows the link to run at full speed.

Example, after running:
```
ethtool -s lan10 advertise 0x1800000001020
```
The speed is upgraded:
```
root@x:~# ethtool lan10
Settings for lan10:
	Supported ports: [ ]
	Supported link modes:   100baseT/Half 100baseT/Full 
	                        1000baseT/Full 
	                        10000baseT/Full 
	Supported pause frame use: Symmetric Receive-only
	Supports auto-negotiation: Yes
	Supported FEC modes: Not reported
	Advertised link modes:  1000baseT/Full 
	                        10000baseT/Full 
	                        2500baseT/Full 
	                        5000baseT/Full 
	Advertised pause frame use: No
	Advertised auto-negotiation: Yes
	Advertised FEC modes: Not reported
	Link partner advertised link modes:  10baseT/Half 10baseT/Full 
	                                     100baseT/Half 100baseT/Full 
	                                     1000baseT/Full 
	                                     2500baseT/Full 
	Link partner advertised pause frame use: Symmetric Receive-only
	Link partner advertised auto-negotiation: Yes
	Link partner advertised FEC modes: Not reported
	Speed: 2500Mb/s
	Duplex: Full
	Port: Twisted Pair
	PHYAD: 25
	Transceiver: external
	Auto-negotiation: on
	MDI-X: Unknown
	Supports Wake-on: d
	Wake-on: d
	Link detected: yes
```

Supported Link Modes should also be corrected as the supported link modes does not list those modes.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by LGA1150** [comment]
See #11812
