### ISSUE TITLE
Please add nftables raw table support

### ISSUE THREAD

**Issue by brada4** [openwrt/openwrt#12522]
### Describe the bug

nftables raw table support is not present, while legacy iptables support for raw tables is visible in form of kmod. 
Please bring NFT functionality in line with historical iptables

### OpenWrt version

r20134-5f15225c1e

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link Archer C7 v5

### Image kind

Official downloaded image

### Steps to reproduce

```
iptables-nft -t raw -A PREROUTING -i lo -j CT --notrack
nft 'add rule ip raw PREROUTING iifname "lo" counter notrack'
```

### Actual behaviour

```
root@OpenWrt:~# iptables-nft -t raw -A PREROUTING -i lo -j CT --notrack
iptables v1.8.7 (nf_tables): unknown option "--notrack"
Try `iptables -h' or 'iptables --help' for more information.
root@OpenWrt:~# nft 'add rule ip raw PREROUTING iifname "lo" counter notrack'
Error: Could not process rule: No such file or directory
add rule ip raw PREROUTING iifname "lo" counter notrack
            ^^^
```

### Expected behaviour

Rule is added and loopback connections are no longer tracked.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by dave14305** [comment]
```
nft add rule inet fw4 raw_prerouting iifname "lo" counter notrack
```
Does this work for you?

**Comment by brada4** [comment]
Thanks a million.
Functional side is fully covered, to update title to reflect merely cosmetic problem.

Permanent integration as follows.

`/etc/nftables.d/20-notrack.nft`
```
chain user_pre_raw_prerouting {
         type filter hook prerouting priority raw - 1; policy accept;
         iifname "lo" counter notrack;
}
```

**Comment by brada4** [comment]
Rules are added to nicely named tables, but conntrack state is created ignoring notrack statement.

**Comment by swestlake** [comment]
i noticed today when try to add **prerouting** in /etc/config/firewall(an include section), it doesn't get honored. however the include can work with the option chain 'dstnat' which is another priority of prerouting..

added section in /etc/config/firewall:
config include
  option type 'nftables'
  option path '/root/fw4-includes/chainpre_dstnat_1.nft'
\#  option chain 'prerouting' -- is an issue
  option position 'chain-pre' 
  option chain 'dstnat'

(OpenWrt 22.03.5, r20134-5f15225c1e)

**Comment by brada4** [comment]
No effect.

```
        chain dstnat {
                type nat hook prerouting priority dstnat; policy accept;
                iifname "lo" counter packets 0 bytes 0 notrack
        }
```
`nc 127.1 12345`
```
    [NEW] tcp      6 120 SYN_SENT src=127.0.0.1 dst=127.0.0.1 sport=39516 dport=12345 [UNREPLIED] src=127.0.0.1 dst=127.0.0.1 sport=12345 dport=39516
[DESTROY] tcp      6 src=127.0.0.1 dst=127.0.0.1 sport=39516 dport=12345 packets=1 bytes=60 [UNREPLIED] src=127.0.0.1 dst=127.0.0.1 sport=12345 dport=39516 packets=1 bytes=40
```

**Comment by brada4** [comment]
The support is there, just one has to install and load respextive xt_ kmod alongside nftables.

**Comment by TrayHard** [comment]
>          type filter hook prerouting priority raw - 1; policy accept;

How you made that work? It gets me an error when I try to do this:

<img width="752" alt="Screenshot 2023-11-21 at 14 10 15" src="https://github.com/openwrt/openwrt/assets/7497789/740f3104-1b40-45d6-978f-1eb463a8cd0e">

**Comment by brada4** [comment]
```
chain notrackI {
        type filter hook prerouting priority raw; policy accept;
        iif "lo" notrack
}

chain notrackO {
        type filter hook output priority raw; policy accept;
        oif "lo" notrack
}
```

**Comment by brada4** [comment]
save in /etc/nftables.d/99-local.nft
