### ISSUE TITLE
[22.03.5, TYPO] Old version mentioned in release details

### ISSUE THREAD

**Issue by dfateyev** [openwrt/openwrt#12526]
### Describe the bug

There are small typos in 22.03.5 release description: older 22.03.4 version mentioned instead of the current one:

https://github.com/openwrt/openwrt/releases/tag/v22.03.5

![image](https://user-images.githubusercontent.com/727201/236121240-de7f7d45-0d20-4f50-a0d8-5290c6937e87.png)

@aparcar only a small typo fix is needed there.

### OpenWrt version

22.03.5

### OpenWrt target/subtarget

All

### Device

All

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by aparcar** [comment]
Thanks, fixed!
