### ISSUE TITLE
Device CJ-Hello HYC-G920 not available in downloads.

### ISSUE THREAD

**Issue by momothefox** [openwrt/openwrt#12530]
### Describe the bug

Device added before 22.03.4 is out 
#12230 

available snapshot only 
https://firmware-selector.openwrt.org/?version=SNAPSHOT&target=ramips%2Fmt7621&id=hanyang_hyc-g920

not seen in 22.03.4 or 5 

### OpenWrt version

22.03.4

### OpenWrt target/subtarget

ramips

### Device

CJ-Hello HYC-G920

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Device support is not backported typically as per policy
https://openwrt.org/docs/guide-developer/device-support-policies#device_support_backports

**Comment by momothefox** [comment]
@brada4  Can you please define what is missing?

**Comment by brada4** [comment]
The backport? You have to wait for next major release like 23.x or 24.x whatever that will be.

**Comment by momothefox** [comment]
Thanks @brada4

**Comment by brada4** [comment]
You can follow developments here:
https://openwrt.org/docs/guide-developer/releases/goals/23.xx

**Comment by momothefox** [comment]
@Ahmed5871205  check out #12568

**Comment by momothefox** [comment]
@Ahmed5871205  check out #12568
