### ISSUE TITLE
 the main branch and master branch?

### ISSUE THREAD

**Issue by ilxp** [openwrt/openwrt#12717]
### Describe the bug

What is the difference between the main branch and the master branch?

### OpenWrt version

master

### OpenWrt target/subtarget

main

### Device

x86

### Image kind

Official downloaded image

### Steps to reproduce

What is the difference between the main branch and the master branch?

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by tapper82** [comment]
They are the same. Just too names for the same thing.

**Comment by ptpt52** [comment]
This is truly a foolish act, renaming the default branch of Git from "master" to "main" in the name of so-called political correctness.

**Comment by tapper82** [comment]
We had a vote about it. The vote past.

**Comment by tapper82** [comment]
One of the OpenWrt devs pleas close this. Thanks.

**Comment by ilxp** [comment]
It is best to have only one name for the same branch, main or master.Just choose one

**Comment by ynezz** [comment]
https://lists.openwrt.org/pipermail/openwrt-adm//2023-February/002318.html

> Change the git server side to automatically update the 'master' 
branch, whenever an update is pushed to 'main'.
It's important to have a long transition period in order to avoid 
breaking downstream users' workflows.

**Comment by ilxp** [comment]
i see。
“3. Developers simply change their git configs to always push to 'main'

Once this change is well established, we can look into removing 
'master', but we should definitely take our time with that.”

**Comment by lynxthecat** [comment]
OpenWrt is supposedly inclusive, but it's OK for one of the main developers to have an avatar that mocks Christianity.

**Comment by lynxthecat** [comment]
The OpenWrt developers [voted in favour of this politically correct change](https://openwrt.org/voting/2023-02-27) on the basis of fostering inclusivity, and see discussion with apparent justification [here](https://lists.openwrt.org/pipermail/openwrt-adm/2023-March/thread.html), but sadly it's apparently OK for [one of the developers to have an avatar that might be offensive to Christians](https://forum.openwrt.org/u/ansuel/summary).
