### ISSUE TITLE
ramips: reg db needs update for Country Egypt 5GHz band

### ISSUE THREAD

**Issue by momothefox** [openwrt/openwrt#12722]
### Describe the bug

This is the current reg db set for EG 
```
:~# iw reg get
global
country EG: DFS-ETSI
        (2402 - 2483 @ 40), (N/A, 20), (N/A)
        (5150 - 5250 @ 80), (N/A, 23), (N/A), NO-OUTDOOR, AUTO-BW
        (5250 - 5330 @ 80), (N/A, 20), (0 ms), NO-OUTDOOR, DFS, AUTO-BW
```
Although according to NTRA Wireless LANs (5150 - 5350) MHz 

### OpenWrt version

22.03.5

### OpenWrt target/subtarget

ramips

### Device

MT7615DN

### Image kind

Self-built image

### Additional info

[https://www.tra.gov.eg/wp-content/uploads/2021/11/EGY-NTRA-June21-NFAT.pdf](url)
Pages 108-110 

[https://www.tra.gov.eg/wp-content/uploads/2021/11/EGY-NTRA-June21-Chart.pdf](url)
SHF Band 

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

![bandicam 2023-05-25 10-41-38-839](https://github.com/openwrt/openwrt/assets/25464943/e91bdea1-ddd0-4754-858a-20a382cb7017)
![bandicam 2023-05-25 10-42-37-375](https://github.com/openwrt/openwrt/assets/25464943/74477e0f-f9ec-4052-a547-55558fa3b686)
![bandicam 2023-05-25 10-42-48-846](https://github.com/openwrt/openwrt/assets/25464943/fb6c9a11-b0c6-471b-a504-a36517aa3f74)

**Comment by robimarko** [comment]
Its not an OpenWrt bug, if the regulatory rules are out of date then you should submit the updated ones to wireless-regdb.
https://wireless.wiki.kernel.org/en/developers/regulatory/wireless-regdb

**Comment by momothefox** [comment]
Thank You @robimarko
