### ISSUE TITLE
x86: syntax error in 01_leds

### ISSUE THREAD

**Issue by obsy** [openwrt/openwrt#12750]
### Describe the bug

Syntax error in line https://github.com/openwrt/openwrt/blob/main/target/linux/x86/base-files/etc/board.d/01_leds#L22 - missing "\\"  after c191c2d46f0080b8c6e6aee76b30ae9cf50d6e3e

Also please fix this in 23.05-snapshot

CC: @stangri  @chunkeey 

### OpenWrt version

snapshot

### OpenWrt target/subtarget

x86/64

### Device

generic pc

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by stangri** [comment]
My bad, PR for the fix has been sent!
