### ISSUE TITLE
 TP-Link TL-WR1043ND v1 no wireless after upgrade 

### ISSUE THREAD

**Issue by gb-rd** [openwrt/openwrt#12780]
### Describe the bug

No wireless after upgrade to 22.03.05 from 19.07.10 with config reset.
WiFI works fine after downgrade back to 19.07.10.
Seems bug in checksum calculation of ART: hexdump shows swapped every 2 bytes.

### OpenWrt version

r16279-5cc0535800

### OpenWrt target/subtarget

 . /etc/openwrt_release && echo $DISTRIB_TARGET

### Device

TP-Link TL-WR1043ND v1

### Image kind

Official downloaded image

### Steps to reproduce

Do sysupgrade to firmware with ath79 driver

### Actual behaviour

Wireless driver fails to start

### Additional info
Hardware mod: 64MB RAM, 16MB SPI flash (ART moved to the end of flash)

dmesg:
[    0.000000] Linux version 5.4.143 (builder@buildhost) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r16279-5cc0535800)) #0 Tue Aug 31 22:20:08 2021
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019374 (MIPS 24Kc)
[    0.000000] MIPS: machine is TP-Link TL-WR1043ND v1
[    0.000000] SoC: Atheros AR9132 rev 2
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] On node 0 totalpages: 16384
[    0.000000]   Normal zone: 144 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 16384 pages, LIFO batch:3
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 16240
[    0.000000] Kernel command line: console=ttyS0,115200 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 57280K/65536K available (5250K kernel code, 193K rwdata, 688K rodata, 1220K init, 205K bss, 8256K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] random: get_random_bytes called from 0x8065fa28 with crng_init=0
[    0.000000] CPU clock: 400.000 MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 9556302233 ns
[    0.000012] sched_clock: 32 bits at 200MHz, resolution 5ns, wraps every 10737418237ns
[    0.007916] Calibrating delay loop... 265.98 BogoMIPS (lpj=531968)
[    0.050057] pid_max: default: 32768 minimum: 301
[    0.054908] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.062222] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.075682] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.085451] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.092388] pinctrl core: initialized pinctrl subsystem
[    0.100870] NET: Registered protocol family 16
[    0.135121] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    0.149505] clocksource: Switched to clocksource MIPS
[    0.155890] thermal_sys: Registered thermal governor 'step_wise'
[    0.156342] NET: Registered protocol family 2
[    0.166998] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.175296] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.183739] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.191417] TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.198477] TCP: Hash tables configured (established 1024 bind 1024)
[    0.205032] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.211626] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.218961] NET: Registered protocol family 1
[    0.223393] PCI: CLS 0 bytes, default 32
[    0.232283] workingset: timestamp_bits=14 max_order=14 bucket_order=0
[    0.249412] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.255302] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.281886] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.293031] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.302860] printk: console [ttyS0] disabled
[    0.307269] 18020000.uart: ttyS0 at MMIO 0x18020000 (irq = 9, base_baud = 12500000) is a 8250
[    0.315810] printk: console [ttyS0] enabled
[    0.324230] printk: bootconsole [early0] disabled
[    0.356586] spi-nor spi0.0: w25q128 (16384 Kbytes)
[    0.361511] 3 fixed-partitions partitions found on MTD device spi0.0
[    0.367912] Creating 3 MTD partitions on "spi0.0":
[    0.372765] 0x000000000000-0x000000020000 : "u-boot"
[    0.379118] 0x000000020000-0x0000007f0000 : "firmware"
[    0.385927] 2 tplink-fw partitions found on MTD device firmware
[    0.391927] Creating 2 MTD partitions on "firmware":
[    0.396939] 0x000000000000-0x0000001f5c4b : "kernel"
[    0.403222] 0x0000001f5c4c-0x0000007d0000 : "rootfs"
[    0.409487] mtd: device 3 (rootfs) set to be root filesystem
[    0.415316] 1 squashfs-split partitions found on MTD device rootfs
[    0.421565] 0x000000510000-0x0000007d0000 : "rootfs_data"
[    0.428227] 0x0000007f0000-0x000000800000 : "art"
[    0.435166] Realtek RTL8366RB ethernet switch driver version 0.2.4
[    0.441583] rtl8366rb rtl8366rb: cannot find mdio node phandle
[    0.553525] rtl8366rb rtl8366rb: using GPIO pins 18 (SDA) and 19 (SCK)
[    0.560277] rtl8366rb rtl8366rb: RTL5937 ver. 3 chip found
[    0.773006] libphy: rtl8366rb: probed
[    0.778885] libphy: Fixed MDIO Bus: probed
[    1.103583] ag71xx 19000000.eth: connected to PHY at fixed-0:00 [uid=00000000, driver=Generic PHY]
[    1.113632] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode: rgmii
[    1.120315] i2c /dev entries driver
[    1.127129] NET: Registered protocol family 10
[    1.137544] random: fast init done
[    1.142475] Segment Routing with IPv6
[    1.146410] NET: Registered protocol family 17
[    1.151002] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    1.164060] 8021q: 802.1Q VLAN Support v1.8
[    1.170723] hctosys: unable to open rtc device (rtc0)
[    1.182839] VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
[    1.197536] Freeing unused kernel memory: 1220K
[    1.202101] This architecture does not have kernel memory protection.
[    1.208580] Run /sbin/init as init process
[    2.111740] init: Console is alive
[    2.115551] init: - watchdog -
[    3.543601] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    3.603523] usbcore: registered new interface driver usbfs
[    3.609211] usbcore: registered new interface driver hub
[    3.614709] usbcore: registered new device driver usb
[    3.627896] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    3.636545] ehci-fsl: Freescale EHCI Host controller driver
[    3.644058] ehci-platform: EHCI generic platform driver
[    3.649715] ehci-platform 1b000100.usb: EHCI Host Controller
[    3.655491] ehci-platform 1b000100.usb: new USB bus registered, assigned bus number 1
[    3.663535] ehci-platform 1b000100.usb: irq 3, io mem 0x1b000100
[    3.685546] ehci-platform 1b000100.usb: USB 2.0 started, EHCI 1.00
[    3.693006] hub 1-0:1.0: USB hub found
[    3.697348] hub 1-0:1.0: 1 port detected
[    3.705425] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    3.723462] init: - preinit -
[    5.541280] random: jshn: uninitialized urandom read (4 bytes read)
[    5.981747] random: jshn: uninitialized urandom read (4 bytes read)
[    6.245419] random: jshn: uninitialized urandom read (4 bytes read)
[    6.619064] urandom_read: 3 callbacks suppressed
[    6.619075] random: jshn: uninitialized urandom read (4 bytes read)
[    7.303570] eth0: link up (1000Mbps/Full duplex)
[    7.313617] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    7.329664] IPv6: ADDRCONF(NETDEV_CHANGE): eth0.1: link becomes ready
[    7.416036] random: procd: uninitialized urandom read (4 bytes read)
[   11.652328] jffs2: notice: (559) jffs2_build_xattr_subsystem: complete building xattr subsystem, 24 of xdatum (7 unchecked, 13 orphan) and 27 of xref (5 dead, 9 orphan) found.
[   11.669770] mount_root: switching to jffs2 overlay
[   11.678245] overlayfs: upper fs does not support tmpfile.
[   11.691617] urandom-seed: Seeding with /etc/urandom.seed
[   11.845840] eth0: link down
[   11.876248] procd: - early -
[   11.879462] procd: - watchdog -
[   12.485671] procd: - watchdog -
[   12.490431] procd: - ubus -
[   12.597317] random: ubusd: uninitialized urandom read (4 bytes read)
[   12.607086] random: ubusd: uninitialized urandom read (4 bytes read)
[   12.627307] procd: - init -
[   14.050500] kmodloader: loading kernel modules from /etc/modules.d/*
[   14.165092] Loading modules backported from Linux version v5.10.42-0-g65859eca4dff
[   14.172801] Backport generated by backports.git v5.10.42-1-0-gbee5c545
[   14.250441] xt_time: kernel timezone is -0000
[   14.581403] PPP generic driver version 2.4.2
[   14.598582] NET: Registered protocol family 24
[   14.778322] ath: phy0: Bad EEPROM checksum 0x0
[   14.782821] ath: phy0: Unable to initialize hardware; initialization status: -22
[   14.790274] ath9k 180c0000.wmac: failed to initialize device
[   14.796052] ath9k: probe of 180c0000.wmac failed with error -22
[   14.894041] kmodloader: done loading kernel modules from /etc/modules.d/*
[   15.027225] urngd: v1.0.2 started.
[   15.316847] random: crng init done
[   36.676323] eth0: link up (1000Mbps/Full duplex)
[   36.773607] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   36.784668] br-lan: port 1(eth0.1) entered blocking state
[   36.790343] br-lan: port 1(eth0.1) entered disabled state
[   36.796289] device eth0.1 entered promiscuous mode
[   36.801171] device eth0 entered promiscuous mode
[   36.810886] br-lan: port 1(eth0.1) entered blocking state
[   36.816396] br-lan: port 1(eth0.1) entered forwarding state
[   37.702158] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
(Release notes) Sysupgrade from 19.07 to 22.03 is not supported
Upgrade to v21 then to v22, reset restoring configuration backup if direct upgrade did not work at both steps.

**Comment by Djfe** [comment]
@gb-rd could you take backup of your "art" partition please? (can be done in LuCI)
Please zip and then upload it here :)

**Comment by brada4** [comment]
It is not v1 hardware, v4 or v5 has 16/64 as in dmesg.

**Comment by gb-rd** [comment]
[1043.mtd5.zip](https://github.com/openwrt/openwrt/files/11618999/1043.mtd5.zip)
Thanks for support!

**Comment by Djfe** [comment]
uhm
I missed this line
> Hardware mod: 64MB RAM, 16MB SPI flash (ART moved to the end of flash)

You need to compile openwrt yourself then.
Even openwrt 2023 should run fine with your hardware mod, but you need to patch your dts file so it actually fits your new spi layout.

Something like this:
https://github.com/openwrt/openwrt/blob/main/target/linux/ath79/dts/ar9132_tplink_tl-wr1043nd-v1.dts
```
@@ -104,12 +104,12 @@
                        partition@20000 {
                                compatible = "tplink,firmware";
                                label = "firmware";
-                               reg = <0x020000 0x7D0000>;
+                               reg = <0x020000 0xFD0000>;
                        };

-                       art: partition@7F0000 {
+                       art: partition@FF0000 {
                                label = "art";
-                               reg = <0x7F0000 0x010000>;
+                               reg = <0xFF0000 0x010000>;
                                read-only;
                        };
                };
```

Currently the checksum fails rightfully because it loads data from the middle of your flash.
We could add a new dts file for modified hardware if you are interested, but I'm not sure how common this mod of your 1043 is.

**Comment by gb-rd** [comment]
Yes, sorry for the inattention.
I haven't made build since 2019 because downloaded images worked well without any fixes and my flash able me to install additional packages. 
I have never edited dts before, just read standard 4/8MB flash, extend image to 16MB, move art to the end and write it.
Something changed in partition definitions, unfortunately I don't have previous configs.

I flashed my build with edited dts and saw art in the right place, but other looks not good:

[    0.362883] 3 fixed-partitions partitions found on MTD device spi0.0
[    0.369381] OF: Bad cell count for /ahb/spi@1f000000/flash@0/partitions
[    0.376123] OF: Bad cell count for /ahb/spi@1f000000/flash@0/partitions
[    0.383540] OF: Bad cell count for /ahb/spi@1f000000/flash@0/partitions
[    0.390321] OF: Bad cell count for /ahb/spi@1f000000/flash@0/partitions
[    0.397282] Creating 3 MTD partitions on "spi0.0":
[    0.402176] 0x000000000000-0x000000020000 : "u-boot"
[    0.414401] 0x000000020000-0x000000ff0000 : "firmware"
[    0.421512] 2 tplink-fw partitions found on MTD device firmware
[    0.427507] Creating 2 MTD partitions on "firmware":
[    0.432596] 0x000000000000-0x000000237bf1 : "kernel"
[    0.437599] mtd: partition "kernel" doesn't end on an erase/write block -- force read-only
[    0.449610] 0x000000237bf4-0x000000fd0000 : "rootfs"
[    0.454641] mtd: partition "rootfs" doesn't start on an erase/write block boundary -- force read-only
[    0.465389] mtd: setting mtd3 (rootfs) as root device
[    0.470626] 1 squashfs-split partitions found on MTD device rootfs
[    0.476857] 0x000000560000-0x000000fd0000 : "rootfs_data"
[    0.485982] 0x000000ff0000-0x000001000000 : "art"

to compare, from my backup:
Wed Jan 29 16:30:23 2020 kern.warn kernel: [    0.623375] m25p80 spi0.0: found w25q128, expected m25p80
Wed Jan 29 16:30:23 2020 kern.info kernel: [    0.640122] m25p80 spi0.0: w25q128 (16384 Kbytes)
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.645183] 5 tp-link partitions found on MTD device spi0.0
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.650832] Creating 5 MTD partitions on "spi0.0":
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.655656] 0x000000000000-0x000000020000 : "u-boot"
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.662413] 0x000000020000-0x0000001a53fc : "kernel"
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.669971] 0x0000001a53fc-0x000000ff0000 : "rootfs"
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.675968] mtd: device 2 (rootfs) set to be root filesystem
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.681788] 1 squashfs-split partitions found on MTD device rootfs
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.688052] 0x000000410000-0x000000ff0000 : "rootfs_data"
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.696186] 0x000000ff0000-0x000001000000 : "art"
Wed Jan 29 16:30:23 2020 kern.notice kernel: [    0.702753] 0x000000020000-0x000000ff0000 : "firmware"

Before that I flashed image without edited dts, with defconfig for my target with the same result and restored backup with spi programmer. Is there any way to fix addressing from console (UART)?

Summary:
1) images from my old buildroot or from image selector with ar71xx driver are OK;
2) with updated buildroot my build bricks device and from online build loses my art partition.

Should I edit all the partitions or there is another way to get compatibility back like in older versions?

[logs_and_edited_dts.zip](https://github.com/openwrt/openwrt/files/11622210/logs_and_edited_dts.zip)

**Comment by Djfe** [comment]
your new log doesn't include anything snout your wifi chipset. does wifi work?

jffs2 realizes that the image created by the makefiles is still for an 8mib device but extends the partition to the size defined in the dts. Future sysupgrades should work just fine. unless they need to be bigger than your current IMAGE_SIZE 8000k
```
[   58.154891] jffs2_scan_eraseblock(): End of filesystem marker found at 0x0
[   58.189631] jffs2_build_filesystem(): unlocking the mtd device... 
[   58.189665] done.
[   58.197822] jffs2_build_filesystem(): erasing all blocks after the end marker... 
```

`IMAGE_SIZE := 16064k`
should be right here

**Comment by Djfe** [comment]
> Is there any way to fix addressing from console (UART)?

what issue?

> with updated buildroot my build bricks device and from online build loses my art partition.
> 
> Should I edit all the partitions or there is another way to get compatibility back like in older versions?

the dts build should be fine, I think

when did you brick your device and which build(root)?
Yeah the build supplied by openwrt explicitly supports 8mib flash only. But it doesn't loose/delete the art partition, it just doesn't know where it actually is.

I'm fairly certain you need to set partitions explicitly unlike in earlier versions (but I haven't worked with openwrt for long and don't know the old system used before dts)

ram mods are way easier than flash mods.
they don't need any code modification. Linux detects ramsize on it's own these days.
But partitions are more or less arbitrary. openwrt could import mtd offsets from oem uboot or set it's own. that's about it. (there is no partition table like you see on x86)

**Comment by Djfe** [comment]
Great :) So now you can write to the fs?
You are right IMAGE_SIZE has to be 16192k, I made a mistake during calculation, I just checked.

About OpenWrt 2023:
It's very likely to work, since there's barely a difference to current master right now, because they just branched.
2023 hasn't even had a release candidate, yet.

If your problem has been solved, then you may close this issue.

**Comment by gb-rd** [comment]
Thank you a lot!!!
