### ISSUE TITLE
MT7620N WIFI not work

### ISSUE THREAD

**Issue by Edwardzhangyuhang** [openwrt/openwrt#128]
I have build the image for mt7620n
And wifi driver do not work
Through the dmesg, I found 
[    8.929788] ieee80211 phy0: rt2x00_set_rt: Info - RT chipset 5390, rev 0500 detected
[    8.937810] ieee80211 phy0: rt2800_init_eeprom: Error - Invalid RF chipset 0xffff detected
[    8.946271] ieee80211 phy0: rt2x00lib_probe_dev: Error - Failed to allocate device

Did the trunk do not support this chip or some configeration I do not enable?

**Comment by gmzhuo** [comment]
Looks like factory data is invalid.

**Comment by Edwardzhangyuhang** [comment]
So what I can do to fix it?

**Comment by gmzhuo** [comment]
Reflash factory mtd with correct factory data,and adjust wifi parameter.

**Comment by Edwardzhangyuhang** [comment]
Thanks
so where can i get the correct factory data, I have no idea of that.

**Comment by gmzhuo** [comment]
You can copy it from another machine, but the RF parameter is not right,you need a device to test and correct it.
