### ISSUE TITLE
Revert 32MB disablement on build bot.

### ISSUE THREAD

**Issue by brada4** [openwrt/openwrt#12887]
### Describe the bug

#12672 disables build on all 32MB devices, some (ath79 below) have 28MB usable RAM after boot wile others 24MB (mt76 miwifi), 22.03 boots into a single AP using 23 MB on more modern device.
I would ask specifically to enable build for TL-WR1043ND v1 adding zram-swap to extend lifetime of once most popular router. But then really say some next release space stretching measures may not help.
That would be similar to offering luci-less build in fw selector for 8MB devices. You know it keeps working but also adds clear sign to get new one. Perceived wifi slowness while clicking LuCI would be another kind of that.

### OpenWrt version

-

### OpenWrt target/subtarget

-

### Device

-

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ynezz** [comment]
Sorry, but it has been discussed ad nauseam, its already a [support nightmare](https://github.com/openwrt/openwrt/issues/10888) in 22.03, certainly would like to avoid that with 23.05.

**Comment by brada4** [comment]
Excuse me - what does invalid instruction emitted by compiler has to do with memory in device?
