### ISSUE TITLE
 missing dependencies:libc.so

### ISSUE THREAD

**Issue by 275761919** [openwrt/openwrt#129]
I compile openwrt-trunk with external toolchain:
- toolchain-arm_cortex-a9_gcc-5.3.0_musl-1.1.14_eabi

First, I setup the `use the external toolchain` options.
This my `.config` :
```
CONFIG_TARGET_NAME="arm-openwrt-linux-muslgnueabi"
CONFIG_TOOLCHAIN_PREFIX="arm-openwrt-linux-muslgnueabi-"
CONFIG_TOOLCHAIN_ROOT="workspace/openwrt/toolchain-arm_cortex-a9_gcc-5.3.0_musl-1.1.14_eabi"
CONFIG_TOOLCHAIN_LIBC="musl"
CONFIG_TOOLCHAIN_BIN_PATH="./usr/bin ./bin"
CONFIG_TOOLCHAIN_INC_PATH="./usr/include ./include"
CONFIG_TOOLCHAIN_LIB_PATH="./usr/lib ./lib"
```
Then I type the `make package/compile V=s`, and there will be the following error:
```
Package libnl-tiny is missing dependencies for the following libraries:
libc.so
```
Need I to patch something?

**Comment by lperkov** [comment]
This is a common problem with external toolchain. Usually as a workaround I place libc.so into base-files package.
