### ISSUE TITLE
[23.05-rc1] 802.11s mesh broken and causes wireless to slow (MT76)

### ISSUE THREAD

**Issue by soxrok2212** [openwrt/openwrt#12905]
### Describe the bug

Hardware:
- 2x Redmi AX6000 (MT76)
- 1x XDR-6086 (MT76)

WPAD:
- wpad-mesh-openssl

On my 5GHz network, I have several VAPs, along with one mesh node. On 22.03, bandwidth was completely normal. I updated to 23.05 a few days ago and noticed the bandwidth on 5GHz is less than 1/3 of 22.03 when the 802.11s node is enabled (2x2@80MHz ~170mbit/s).

Disabling the mesh node restores the wireless speeds to normal (2x2@80MHz ~700mbit/s).

It does not matter if there is an associated node or not, speeds still slow significantly.

It also appears that the mesh nodes do not associate at all.

### OpenWrt version

r23069-e2701e0f33

### OpenWrt target/subtarget

mediatek/filogic

### Device

TP-Link TL-XDR6086, Xiaomi Redmi AX6000

### Image kind

Self-built image

### Steps to reproduce

1. create a wireless network and mesh node on the same radio and run a speed test (iperf3 works, as well as a WAN-based test).
2. observe slow speed
3. remove the mesh node on that radio and run an speed test
4. observe much faster speed

### Actual behaviour

Enabling an 802.11s mesh node on a radio hosting other networks significantly slows wireless speeds since 23.05. 22.03 never exhibited this behavior.

The mesh nodes also do not appear to ever associate.

### Expected behaviour

Enabling an 802.11s mesh node on a radio hosting other networks does not cause significant speed drops and connects to other nodes normally.

### Diffconfig

```text
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_tplink_tl-xdr6086=y
CONFIG_BATMAN_ADV_BATMAN_V=y
CONFIG_BATMAN_ADV_BLA=y
CONFIG_BATMAN_ADV_DAT=y
CONFIG_BATMAN_ADV_MCAST=y
CONFIG_HTOP_LMSENSORS=y
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_MBEDTLS=y
CONFIG_LIBCURL_NGHTTP2=y
CONFIG_LIBCURL_NO_SMB="!"
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_UNIX_SOCKETS=y
CONFIG_NFS_KERNEL_SERVER_V4=y
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_IDEA=y
CONFIG_OPENSSL_WITH_MDC2=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SEED=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_OPENSSL_WITH_WHIRLPOOL=y
CONFIG_PACKAGE_batctl-default=y
CONFIG_PACKAGE_block-mount=y
CONFIG_PACKAGE_ca-certificates=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_ddns-scripts=y
CONFIG_PACKAGE_ddns-scripts-services=y
CONFIG_PACKAGE_ethtool-full=y
CONFIG_PACKAGE_hd-idle=y
CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_iptables-mod-ipopt=y
CONFIG_PACKAGE_iptables-nft=y
CONFIG_PACKAGE_kmod-asn1-decoder=y
CONFIG_PACKAGE_kmod-asn1-encoder=y
CONFIG_PACKAGE_kmod-batman-adv=y
CONFIG_PACKAGE_kmod-crypto-arc4=y
CONFIG_PACKAGE_kmod-crypto-cbc=y
CONFIG_PACKAGE_kmod-crypto-cts=y
CONFIG_PACKAGE_kmod-crypto-ecb=y
CONFIG_PACKAGE_kmod-crypto-kpp=y
CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y
CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y
CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y
CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y
CONFIG_PACKAGE_kmod-crypto-user=y
CONFIG_PACKAGE_kmod-dax=y
CONFIG_PACKAGE_kmod-dm=y
CONFIG_PACKAGE_kmod-dnsresolver=y
CONFIG_PACKAGE_kmod-fs-exportfs=y
CONFIG_PACKAGE_kmod-fs-nfs=y
CONFIG_PACKAGE_kmod-fs-nfs-common=y
CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=y
CONFIG_PACKAGE_kmod-fs-nfs-v4=y
CONFIG_PACKAGE_kmod-fs-nfsd=y
CONFIG_PACKAGE_kmod-ifb=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-ipopt=y
CONFIG_PACKAGE_kmod-keys-encrypted=y
CONFIG_PACKAGE_kmod-keys-trusted=y
CONFIG_PACKAGE_kmod-lib-crc16=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nft-bridge=y
CONFIG_PACKAGE_kmod-nft-compat=y
CONFIG_PACKAGE_kmod-nft-netdev=y
CONFIG_PACKAGE_kmod-oid-registry=y
CONFIG_PACKAGE_kmod-random-core=y
CONFIG_PACKAGE_kmod-sched-cake=y
CONFIG_PACKAGE_kmod-sched-core=y
CONFIG_PACKAGE_kmod-scsi-core=y
CONFIG_PACKAGE_kmod-tpm=y
CONFIG_PACKAGE_kmod-udptunnel4=y
CONFIG_PACKAGE_kmod-udptunnel6=y
CONFIG_PACKAGE_kmod-usb-storage=y
CONFIG_PACKAGE_kmod-usb-storage-extras=y
CONFIG_PACKAGE_kmod-wireguard=y
CONFIG_PACKAGE_libblkid=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libdevmapper=y
CONFIG_PACKAGE_libiptext=y
CONFIG_PACKAGE_libiptext-nft=y
CONFIG_PACKAGE_libiptext6=y
CONFIG_PACKAGE_libkeyutils=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_libmount=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_librt=y
CONFIG_PACKAGE_libsmartcols=y
CONFIG_PACKAGE_libtirpc=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libustream-mbedtls=m
CONFIG_PACKAGE_libustream-openssl=y
CONFIG_PACKAGE_libuuid=y
CONFIG_PACKAGE_libwrap=y
CONFIG_PACKAGE_libxtables=y
CONFIG_PACKAGE_lsblk=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_luci-app-ddns=y
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-hd-idle=y
CONFIG_PACKAGE_luci-app-nft-qos=y
CONFIG_PACKAGE_luci-app-sqm=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-light=y
CONFIG_PACKAGE_luci-lua-runtime=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-batman-adv=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-proto-wireguard=y
CONFIG_PACKAGE_luci-ssl-openssl=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_nfs-kernel-server=y
CONFIG_PACKAGE_nfs-kernel-server-utils=y
CONFIG_PACKAGE_nfs-utils-libs=y
CONFIG_PACKAGE_nft-qos=y
CONFIG_PACKAGE_openssl-util=y
CONFIG_PACKAGE_rpcbind=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-rrdns=y
CONFIG_PACKAGE_rpcd-mod-ucode=y
CONFIG_PACKAGE_sqm-scripts=y
CONFIG_PACKAGE_tc-tiny=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_trusted-firmware-a-mt7986-spim-nand-ddr4=y
CONFIG_PACKAGE_ucode-mod-html=y
CONFIG_PACKAGE_ucode-mod-lua=y
CONFIG_PACKAGE_ucode-mod-math=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_PACKAGE_wireguard-tools=y
CONFIG_PACKAGE_wpad-basic-mbedtls=m
CONFIG_PACKAGE_wpad-mesh-openssl=y
CONFIG_PACKAGE_xtables-nft=y
CONFIG_RPCBIND_LIBWRAP=y
CONFIG_RPCBIND_RMTCALLS=y
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by rmccask** [comment]
I am having a similar problem with a couple of Linksys E8450 (UBI) and wpad-mesh-mbedtls.

**Comment by visualage** [comment]
To add another data point, my Netgear WAX202 has exactly the same issue. I tried wpad-mesh-mbedtls, wpad-mesh-openssl, and even the full blown wpad-openssl and wpad-mbedtls. None works. I also tried meshing 22.03 with 23.05. Looks like 23.05 is able to receive packets successfully from 22.03 via mesh connections, but not able to transmit successfully. Here is the result of `iw dev mesh0 station dump` on 23.05 side:

```
Station xx:xx:xx:xx:xx:xx (on mesh0)
	inactive time:	30 ms
	rx bytes:	1318623
	rx packets:	9897
	tx bytes:	485905
	tx packets:	2947
	tx retries:	0
	tx failed:	590
	rx drop misc:	24939
	signal:  	-57 [-59, -61] dBm
	signal avg:	-57 [-58, -62] dBm
	Toffset:	9645888375 us
	tx bitrate:	6.0 MBit/s
	tx duration:	15493845 us
	rx bitrate:	864.8 MBit/s 80MHz HE-MCS 8 HE-NSS 2 HE-GI 0 HE-DCM 0
	rx duration:	45338 us
	last ack signal:-57 dBm
	avg ack signal:	-56 dBm
	airtime weight: 256
	mesh llid:	0
	mesh plid:	0
	mesh plink:	ESTAB
	mesh airtime link metric: 1823
	mesh connected to gate:	no
	mesh connected to auth server:	no
	mesh local PS mode:	ACTIVE
	mesh peer PS mode:	ACTIVE
	mesh non-peer PS mode:	ACTIVE
	authorized:	yes
	authenticated:	yes
	associated:	yes
	preamble:	long
	WMM/WME:	yes
	MFP:		yes
	TDLS peer:	no
	DTIM period:	2
	beacon interval:100
	connected time:	216 seconds
	associated at [boottime]:	37.622s
	associated at:	1686539830911 ms
	current time:	1686540047263 ms
```

No alarming errors in `logread`:

```
Sun Jun 11 20:17:10 2023 kern.info kernel: [   37.291622] br-lan: port 7(mesh0) entered blocking state
Sun Jun 11 20:17:10 2023 kern.info kernel: [   37.297009] br-lan: port 7(mesh0) entered forwarding state
Sun Jun 11 20:17:10 2023 daemon.notice wpa_supplicant[1585]: mesh0: CTRL-EVENT-CONNECTED - Connection to 00:00:00:00:00:00 completed [id=0 id_str=]
Sun Jun 11 20:17:10 2023 daemon.notice wpa_supplicant[1585]: mesh0: MESH-GROUP-STARTED ssid="xxxxxxxx" id=0
Sun Jun 11 20:17:10 2023 kern.info kernel: [   37.473581] br-lan: port 5(phy1-ap0) entered blocking state
Sun Jun 11 20:17:10 2023 kern.info kernel: [   37.479200] br-lan: port 5(phy1-ap0) entered forwarding state
Sun Jun 11 20:17:10 2023 daemon.notice netifd: Network device 'phy1-ap0' link is up
Sun Jun 11 20:17:10 2023 daemon.notice wpa_supplicant[1585]: mesh0: new peer notification for xx:xx:xx:xx:xx:xx
Sun Jun 11 20:17:10 2023 daemon.notice wpa_supplicant[1585]: mesh0: new peer notification for xx:xx:xx:xx:xx:xx
Sun Jun 11 20:17:10 2023 daemon.notice wpa_supplicant[1585]: mesh0: mesh plink with xx:xx:xx:xx:xx:xx established
Sun Jun 11 20:17:10 2023 daemon.notice wpa_supplicant[1585]: mesh0: MESH-PEER-CONNECTED xx:xx:xx:xx:xx:xx
```

**Comment by visualage** [comment]
Also, the snapshot version on Jun 11 does not work as well. Same problem as 23.05.

**Comment by soxrok2212** [comment]
> It seems this could be mt76 specific.

There haven't been any changes in MT76 since may.

**Comment by brada4** [comment]
Do some network survey like channel report in luci - maybe while you were installing snapshot your neighbour bought their 5GHz router.

**Comment by visualage** [comment]
> Do some network survey like channel report in luci - maybe while you were installing snapshot your neighbour bought their 5GHz router.

Extremely unlikely since when I downgraded to 22.03, it goes back to normal.

**Comment by soxrok2212** [comment]
> Extremely unlikely since when I downgraded to 22.03, it goes back to normal.

I think that was a bot account, you can safely ignore it.

**Comment by soxrok2212** [comment]
Seems to be related to an MT76 change: https://forum.openwrt.org/t/wireless-client-mode-broken-on-wax206-post-r22866/162406/8?u=soxrok2212

**Comment by soxrok2212** [comment]
Ping @nbd168 here too. See above post.

**Comment by visualage** [comment]
23.05.0-rc2 did not solve the problem, even though there are a bunch of commits to [openwrt/mt76](https://github.com/openwrt/mt76)

**Comment by soxrok2212** [comment]
https://github.com/openwrt/mt76/commit/1377f586c6f520a6d032053a2e9c0ebc8b277e9b and https://github.com/openwrt/mt76/commit/d7d7479b00e9a5f4d14ebef6e147a5ce0406962d seem to have fixed 802.11s, but the VAPs are still seeing <170mbit/s

**Comment by visualage** [comment]
> [openwrt/mt76@1377f58](https://github.com/openwrt/mt76/commit/1377f586c6f520a6d032053a2e9c0ebc8b277e9b) and [openwrt/mt76@d7d7479](https://github.com/openwrt/mt76/commit/d7d7479b00e9a5f4d14ebef6e147a5ce0406962d) seem to have fixed 802.11s, but the VAPs are still seeing <170mbit/s

On my WAX202, I don't see VAP <170mbit/s with mesh. I can easily reach 200mbit/s. My mesh only has two nodes.

**Comment by soxrok2212** [comment]
I just re-built and re-tested `23.05-SNAPSHOT r23247-a70d030fb3`. Still can't get over 170mbit/s on a VAP. As soon as the mesh node is disabled, speeds return to perfectly normal.

**Comment by neheb** [comment]
@soxrok2212 please try https://forum.openwrt.org/t/802-11ax-worse-than-802-11ac-with-mt76-driver/126466/562

**Comment by soxrok2212** [comment]
I don't think it's related to that. It just appears that everything but the mesh node on the radio gets limited to 20MHz instead of the 80MHz I have it set to. Otherwise, I'm very aware of that tx issue.

**Comment by soxrok2212** [comment]
Running today's snapshot (r23286-b607cd30c7) and still seeing TX limited to 20MHz for VAP clients when a mesh node is on the same radio as other VAPs, but other mesh nodes are fine. Checked with 802.11ac mode and same behavior.

Possibly related to https://github.com/openwrt/openwrt/issues/13128? @nbd168 any ideas?

**Comment by brada4** [comment]
> limited to 20MHz instead of the 80MHz

40MHz is guaranteed to be supported by any AC device, so this is major regression in 5GHz that beams also to 2.4GHz.

**Comment by soxrok2212** [comment]
Closing as part of this has been fixed. Update for the still problematic part: https://github.com/openwrt/openwrt/issues/13153
