### ISSUE TITLE
23.05.0-rc1: mediatek: Image Builder fails with unresolved dependency of libubox20220927 for mtd

### ISSUE THREAD

**Issue by ahuse** [openwrt/openwrt#12931]
### Describe the bug

The Image Builder for 23.05.0-rc1 fails with an unresolved dependency. This occurs on my own linux VM as well as using OpenWRT firmware selector.

```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libubox20220927 for mtd
 * pkg_hash_fetch_best_installation_candidate: Packages for mtd found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package mtd.
make[2]: *** [Makefile:186: package_install] Error 255
make[1]: *** [Makefile:141: _call_image] Error 2
make: *** [Makefile:259: image] Error 2
```

### OpenWrt version

r23069-e2701e0f33

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Linksys E8450 (UBI)

### Image kind

Official downloaded image

### Actual behaviour

Using Image Builder with this command.

`make image PROFILE="linksys_e8450-ubi" BIN_DIR="/root/images"`

### Expected behaviour

Should build without a problem. This was possible a few day ago.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ynezz** [comment]
This is going to be fixed with `23.05.0-rc2`, so until then you can use [23.05-SNAPSHOT](https://downloads.openwrt.org/releases/23.05-SNAPSHOT/targets/mediatek/mt7622/openwrt-imagebuilder-23.05-SNAPSHOT-mediatek-mt7622.Linux-x86_64.tar.xz) which should work.
