### ISSUE TITLE
who has MTK SDK4.0-openwrt-linux-4.9.92 or raeth driver doc for MT7622?

### ISSUE THREAD

**Issue by leidemon** [openwrt/openwrt#12949]
### Describe the bug

who has MTK SDK4.0-openwrt-linux-4.9.92; or raeth driver doc for MT7622?

### OpenWrt version

17.01

### OpenWrt target/subtarget

MT7622

### Device

MT7622

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by musashino205** [comment]
This is not a bug of OpenWrt, please ask on the Forum or other place.

https://forum.openwrt.org/
