### ISSUE TITLE
boot fails if /var or /var/run is removed

### ISSUE THREAD

**Issue by M95D** [openwrt/openwrt#12989]
### Describe the bug

If /var is (accidentally) removed, the system fails to boot. This is unexpected, as var normally only holds temporary files that don't survive reboot.

The same thing happens if /var, the symlink, is removed and an empty /var directory is created without /var/run inside, or /var/run is removed from a normal /var directory.

### OpenWrt version

current snapshot

### OpenWrt target/subtarget

This is a procd issue; all targets are affected.

### Device

all devices

### Image kind

Self-built image

### Steps to reproduce

Remove /var and reboot.
-or-
Have a normal /var directory and remove /var/run.

### Actual behaviour

procd: - early -
procd: - watchdog -
procd: - watchdog -
procd: - ubus -
procd: - ubus - failed to chown(/var/run/ubus)
... and it freezes.

### Expected behaviour

1) If /var is required to boot a minimally usable system (which I think should **not** be the case, see 2), preinit should create it if it doesn't exist, and all the necessary subdirs too.

The correct way to do it would be to remember how the image was built (CONFIG_TARGET_ROOTFS_PERSIST_VAR enabled or not) and create a symlink or a dir according to that.
The quick and dirty way would be to always make a symlink.

2) procd should use /tmp/run instead of /var/run.

As described here: https://openwrt.org/docs/techref/procd , procd (or is it preinit? - the text is ambiguous) "create some required folder, /tmp/{run,lock,state}". Those directories really are created in /tmp very early; that part of the article is probably not outdated. This means that procd tries to use the wrong dir: /var/run instead of /tmp/run.

### Additional info

Thank you.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html
Maybe approach spec wih separate /run?
