### ISSUE TITLE
Any wpad other than basic prevents wifi authentication in client mode

### ISSUE THREAD

**Issue by bassmannate** [openwrt/openwrt#12991]
### Describe the bug

Removing wpad-basic-mbedtls and installing any other wpad package more than basic (wpad-mesh-openssl, wpad-openssl, wpad-mesh-wolfssl, wpad-wolfssl, wpad-mesh-mbedtls, etc.) appears to prevent wireless authentication in client mode on 2.4 and 5ghz bands.

Wifi can scan and select the ssid but will not connect and behaves like it does when you don't have the correct encryption key.

Edited to pull actual version number from the gui

### OpenWrt version

OpenWrt 23.05.0-rc1 r23069-e2701e0f33 / LuCI openwrt-23.05 branch git-23.118.79121-6fb185f
--

<br class="Apple-interchange-newline">

### OpenWrt target/subtarget

ipq40xx/generic

### Device

Linksys MR8300 (Dallas)

### Image kind

Official downloaded image

### Steps to reproduce

From fresh install, remove wpad-basic-mbedtls and install wpad-mbedtls or any other package listed above. Reboot. Connect to wifi with wpa2 authentication.

### Actual behaviour

client mode will no longer authenticate and finish connecting. It does not matter if the client was connected before wpad package was changed before or after initially connecting.

### Expected behaviour

It is expected that the wifi client mode would connect and authenticate, allowing connectivity to the host network.

### Additional info

When trying to add a master mode to any radio, it hangs and just never enables when WPA2 is enabled.

Some info isn't available as I've rolled back to 22.03 for functionality. I can switch back over to grab a few things if needed since this router is a dual firmware model.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Please clarify - does it hang when enabling master and station mode both at once or jjst station is enough?

**Comment by bassmannate** [comment]
Here's what I'm getting on my wireless. The client has WPA2 encryption. The master on the second 5G radio has no encryption so it looks like I was wrong. Wifi will not come completely up with anything other than basic wpad. In this particular instance, I have wpad-mesh-wolfssl installed. Also, the client is not automatically changing to the correct channel like it normally does. That access point is actually on channel 120, I believe. Even manually changing it to match does not work.
![wifi1](https://github.com/openwrt/openwrt/assets/16216783/15e70f79-4353-4c02-8a7b-ad06b8f4f12b)

**Comment by brada4** [comment]
Thanks, i was just curious aboit setup sice i have similar extender setup working like now.
