### ISSUE TITLE
[23.05.0] 802.11s (mesh) use only 20MHz BW (2.4 GHz)

### ISSUE THREAD

**Issue by csharper2005** [openwrt/openwrt#13112]
### Describe the bug

2.4 GHz 802.11s (mesh) use only 20MHz BW to connect to the corresponding router (even if 40 MHz (HT40, HE40) is configured).

Test cases:
Router 1 | Router 2 | Band | Release | Affected | Tested-by
-- | -- | -- | -- | -- | --
Mercusys MR90X v1     MediaTek MT7986     mediatek/filogic | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 2.4 GHz | SNAPSHOT     r23566-37ff916af7 | Yes,   20 MHz BW | @csharper2005
Mercusys MR90X v1     MediaTek MT7986     mediatek/filogic | TP-Link   EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | 2.4 GHz | SNAPSHOT     r23566-37ff916af7 | Yes,   20 MHz BW | @csharper2005
TP-Link EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 2.4 GHz | SNAPSHOT     r23566-37ff916af7 | Yes,   20 MHz BW | @csharper2005
TP-Link EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 2.4 GHz | 23.05.0-rc2     r23228-cd17d8df2a | Yes,   20 MHz BW | @csharper2005
TP-Link EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 2.4 GHz | 23.05-SNAPSHOT     r23274-b32a4bc33f | Yes,   20 MHz BW | @csharper2005
Asus OnHub     Qualcomm IPQ8064 | Netgear   Nighthawk X4S R7800     Qualcomm IPQ8065 | 2.4 GHz | SNAPSHOT     r23579-1c56801dd2 | Yes,   20 MHz BW | @csharper2005
Dynalink     Qualcomm Atheros IPQ8074 | Xiaomi   AX3200 Mediatek     MT7915E     MT7622 | 2.4 GHz |   | Yes,   20 MHz BW | @xabolcs
Mercusys MR90X v1     MediaTek MT7986     mediatek/filogic | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 5 GHz | SNAPSHOT     r23566-37ff916af7 | Not affected | @csharper2005
Mercusys MR90X v1     MediaTek MT7986     mediatek/filogic | TP-Link   EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | 5 GHz | SNAPSHOT     r23566-37ff916af7 | Not affected | @csharper2005
TP-Link EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 5 GHz | SNAPSHOT     r23566-37ff916af7 | Not affected | @csharper2005
D-Link DIR-860L B1     MediaTek MT76x2E     ramips/mt7621 | Xiaomi   AX3200     Mediatek MT7915E     MT7622 | 5 GHz | 23.05-SNAPSHOT     r23273-50507f5af3 | Not affected | @xabolcs
Dynalink DL-WRX36     Qualcomm Atheros IPQ8074 | D-Link   DIR-860L B1     MediaTek MT76x2E     ramips/mt7621 | 5 GHz | SNAPSHOT     r23566-37ff916af7 | Not affected | @xabolcs
TP-Link EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 2.4 GHz | 22.03.5 | Not affected | @csharper2005
TP-Link EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 5 GHz | 22.03.5 | Not affected | @csharper2005
TP-Link EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 5 GHz | 23.05.0-rc2     r23228-cd17d8df2a | Not affected | @csharper2005
TP-Link EC330-G5u v1     MediaTek MT7615E     ramips/mt7621 | WiFire   S1500.NBN     MediaTek MT7602E/MT7612E     ramips/mt7621 | 5 GHz | 23.05-SNAPSHOT     r23274-b32a4bc33f | Not affected | @csharper2005

### OpenWrt version

r23228-cd17d8df2a, r23566-37ff916af7, r23579-1c56801dd2

### OpenWrt target/subtarget

mediatek/filogic, ramips/mt7621, ipq806x/chromium, ipq806x/generic

### Device

Mercusys MR90X v1, WiFire S1500,NBN, WiFire S1500.NBN, ASUS OnHub, Netgear Nighthawk X4S R7800

### Image kind

Official downloaded image

### Steps to reproduce

1. Configure 40 MHz BW for 2.4:
```
	option htmode 'HE40'
	option noscan '1'
```
2. Make sure that clients connects using 40 MHz BW
3. Configure 802.11s:
```
config wifi-iface 'wifinet4'
	option device 'radio0'
	option mode 'mesh'
	option encryption 'sae'
	option mesh_id 'xxxx'
	option mesh_fwding '1'
	option mesh_rssi_threshold '0'
	option key '********************'
	option network 'lan'
	option skip_inactivity_poll '1'
	option disassoc_low_ack '0'
```

### Actual behaviour

802.11s connection has 20 MHz BW.

### Expected behaviour

802.11s connection has 40 MHz BW for 2.4 band

### Additional info

802.11s node is enabled:
```
# iwinfo phy0-mesh0
phy0-mesh0 ESSID: "xxxx"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Mesh Point  Channel: 1 (2.412 GHz)  HT Mode: HT20
          Center Channel 1: 1 2: unknown
          Tx-Power: 27 dBm  Link Quality: 59/70
          Signal: -51 dBm  Noise: -92 dBm
          Bit Rate: 1.0 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ax/b/g/n
          Hardware: embedded [MediaTek MT7986]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0

# iwinfo phy0-ap0 info
phy0-ap0  ESSID: "xxxx"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Master  Channel: 1 (2.412 GHz)  HT Mode: HE20
          Center Channel 1: 1 2: unknown
          Tx-Power: 27 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: -92 dBm
          Bit Rate: unknown
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ax/b/g/n
          Hardware: embedded [MediaTek MT7986]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0
```
802.11s node is disabled:
```
phy0-ap0  ESSID: "xxxx"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Master  Channel: 1 (2.412 GHz)  HT Mode: HE40
          Center Channel 1: 3 2: unknown
          Tx-Power: 27 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: -92 dBm
          Bit Rate: unknown
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ax/b/g/n
          Hardware: embedded [MediaTek MT7986]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0
```

Corresponding router (TP-Link EC330-G5u v1, ramips/mt7621) is not affected if 802.11s is enabled. HT40 works fine:
```
# iwinfo phy0-mesh0 info
phy0-mesh0 ESSID: "xxxx"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Mesh Point  Channel: 1 (2.412 GHz)  HT Mode: HT20
          Center Channel 1: 1 2: unknown
          Tx-Power: 20 dBm  Link Quality: 66/70
          Signal: -44 dBm  Noise: -84 dBm
          Bit Rate: 288.9 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11b/g/n
          Hardware: 14C3:7615 7615:14C3 [MediaTek MT7615E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0

# iwinfo phy0-ap0 info
phy0-ap0  ESSID: "xxxx"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Master  Channel: 1 (2.412 GHz)  HT Mode: HT40
          Center Channel 1: 3 2: unknown
          Tx-Power: 20 dBm  Link Quality: 70/70
          Signal: -32 dBm  Noise: -83 dBm
          Bit Rate: 300.0 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11b/g/n
          Hardware: 14C3:7615 7615:14C3 [MediaTek MT7615E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by hauke** [comment]
Please try a openwrt 23.05 snapshot build, multiple fixes were backported for mt76 after 23.05.0-rc2, see 649d9e359005377b9efc445466db58f54a547875 and a70d030fb33c246c3eb222beccbd69c427b3a66f

**Comment by csharper2005** [comment]
@hauke https://github.com/openwrt/openwrt/commit/649d9e359005377b9efc445466db58f54a547875 and https://github.com/openwrt/openwrt/commit/a70d030fb33c246c3eb222beccbd69c427b3a66f were cherry-picked from the main branch. I tried the latest snapshot r23566-37ff916af7 (Sat Jul 15 09:58:38 2023 @downloads.openwrt.org). 
Clients can use 40MHz:
![image](https://github.com/openwrt/openwrt/assets/82600916/0be18f9b-f871-477e-9f1d-9b5a5061c6db)
Mesh are 20MHz only:
![image](https://github.com/openwrt/openwrt/assets/82600916/525c931d-cdc6-4c0d-86cc-339058590617)
Does it make sense to check the 23.05-snapshot if the issue shows up in the main too?

**Comment by csharper2005** [comment]
I noticed that 5 GHz mesh is also 20 MHz only. So, the issue is band independent.

**Comment by csharper2005** [comment]
Some additional cases when 802.11s (mesh) use only 20MHz BW:
- mediatek/filogic (Mercusys MR90X v1, MediaTek MT7986) - ramips/mt7621 (WiFire S1500.NBN, MediaTek MT7602E)
- ramips/mt7621 (TP-Link EC330-G5u v1, MediaTek MT7615E) - ramips/mt7621 (WiFire S1500.NBN, MediaTek MT7602E)

**Comment by xabolcs** [comment]
I'm unable to reproduce with D-Link DIR-860L B1 (with 22.03.5 and 23.05-SNAPSHOT at `r23274-b32a4bc33f`) + Xiaomi AX3200 (with 23.05-SNAPSHOT, `r23273-50507f5af3`,MT7622, MT7915E) on 5 GHz mesh at channel 36.

I know, it's not `mediatek/filogic` but still `mt76`. I could change the DIR-860L to Dynalink DL-WRX36 in the 5 GHz mesh with AX3200, if it makes sense. Should I give it a try?

(Offtopic, but trying to reproduce this issue, I got a some `MAC error detected` errors on the DIR-860L. :shrug: 
```
Sat Jul 15 20:14:13 2023 kern.info kernel: [ 2483.547746] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
Sat Jul 15 20:14:13 2023 kern.info kernel: [ 2483.558778] mt76x2e 0000:01:00.0: Build: 1
Sat Jul 15 20:14:13 2023 kern.info kernel: [ 2483.566991] mt76x2e 0000:01:00.0: Build Time: 201607111443____
Sat Jul 15 20:14:13 2023 kern.info kernel: [ 2483.596554] mt76x2e 0000:01:00.0: Firmware running!
Sat Jul 15 20:14:13 2023 kern.info kernel: [ 2483.608327] ieee80211 phy0: Hardware restart was requested
```
)

**Comment by csharper2005** [comment]
> I'm unable to reproduce with D-Link DIR-860L B1 (with 22.03.5 and 23.05-SNAPSHOT at `r23274-b32a4bc33f`) + Xiaomi AX3200 (with 23.05-SNAPSHOT, `r23273-50507f5af3`,MT7622, MT7915E) on 5 GHz mesh at channel 36.

Thanks for the test! Did you reach an 80 MHz BW 802.11s connection between the routers?

> I know, it's not mediatek/filogic but still mt76. I could change the DIR-860L to Dynalink DL-WRX36 in the 5 GHz mesh with AX3200, if it makes sense. Should I give it a try?

Yes, please. I have only 20 MHz link even between 2 mt7621 routers.

> (Offtopic, but trying to reproduce this issue, I got a some `MAC error detected` errors on the DIR-860L.

Oh, mt7602? How familiar. :) The possible solution - https://github.com/openwrt/openwrt/blob/main/target/linux/ramips/dts/mt7621_sercomm_s1500.dtsi#L214

**Comment by xabolcs** [comment]
> Did you reach the 80 MHz BW 802.11s connection between the routers?

Sure, without problem.
From DIR-860L point of view:
```
mesh0     ESSID: "mesh"
          Access Point: XX:XX:XX:XX:XX:XX
          Mode: Mesh Point  Channel: 36 (5.180 GHz)  HT Mode: VHT80
          Center Channel 1: 42 2: unknown
          Tx-Power: 20 dBm  Link Quality: 39/70
          Signal: -71 dBm  Noise: unknown
          Bit Rate: 390.0 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ac/n
          Hardware: 14C3:7662 14C3:7662 [MediaTek MT76x2E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0

phy1-ap0  ESSID: "ap"
          Access Point: XX:XX:XX:XX:XX:XX
          Mode: Master  Channel: 3 (2.422 GHz)  HT Mode: HT40
          Center Channel 1: 5 2: unknown
          Tx-Power: 10 dBm  Link Quality: 70/70
          Signal: -37 dBm  Noise: unknown
          Bit Rate: 132.7 MBit/s
          Encryption: WPA2 PSK (CCMP)
          Type: nl80211  HW Mode(s): 802.11b/g/n
          Hardware: 14C3:7662 14C3:7662 [MediaTek MT76x2E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy1

```

The same mesh part from AX3200:
```
mesh0     ESSID: "mesh"
          Access Point: XX:XX:XX:XX:XX:XX
          Mode: Mesh Point  Channel: 36 (5.180 GHz)  HT Mode: VHT80
          Center Channel 1: 42 2: unknown
          Tx-Power: 20 dBm  Link Quality: 38/70
          Signal: -72 dBm  Noise: unknown
          Bit Rate: 117.0 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ac/ax/n
          Hardware: 14C3:7915 14C3:7915 [MediaTek MT7915E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: wl1

```



And here is the link from Dynalink DL-WRX36 - while `iperf3`-ing:
```
mesh0     ESSID: "mesh"
          Access Point: DE:AD:BE:EF:XX:XX
          Mode: Mesh Point  Channel: 36 (5.180 GHz)  HT Mode: VHT80
          Center Channel 1: 42 2: unknown
          Tx-Power: 18 dBm  Link Quality: 30/70
          Signal: -80 dBm  Noise: -110 dBm
          Bit Rate: 324.2 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ac/ax/n
          Hardware: embedded [Qualcomm Atheros IPQ8074]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0

```
Without stress it reports 6 mbps for `iwinfo`, also on LuCI. :roll_eyes: 
![image](https://github.com/openwrt/openwrt/assets/568751/9ae395be-afe5-4a57-b28d-e4cc791ea900)

From AX3200 point of view:
```
mesh0     ESSID: "mesh"
          Access Point: XX:XX:XX:XX:XX:XX
          Mode: Mesh Point  Channel: 36 (5.180 GHz)  HT Mode: VHT80
          Center Channel 1: 42 2: unknown
          Tx-Power: 20 dBm  Link Quality: 34/70
          Signal: -76 dBm  Noise: unknown
          Bit Rate: 408.3 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ac/ax/n
          Hardware: 14C3:7915 14C3:7915 [MediaTek MT7915E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: wl1

```
![image](https://github.com/openwrt/openwrt/assets/568751/784eb7ed-b7ca-4c67-a985-add92b1ca2d2)

**Comment by csharper2005** [comment]
@xabolcs thanks again. I added all test results to the issue description. And I tested again. Looks like it affects 2.4 GHz only. 20 MHz on 5 GHz in my previous tests was due to power saving when idle.

**Comment by csharper2005** [comment]
> Please try a openwrt 23.05 snapshot build

23.05-SNAPSHOT r23274-b32a4bc33f. Issue exists with 2.4 band. I added this result to the issue description.

It would be good to test on non-mt76 platforms (e.g. Qualcomm).

**Comment by xabolcs** [comment]
> It would be good to test on non-mt76 platforms (e.g. Qualcomm).

I tried mesh on 2.4 band on the Dynalink, but it didn't came up with 40 Mhz wide  (ie. `HT40`, `HE40`) band mode:
```
wpa_supplicant[1864]: Could not select hw_mode and channel. (-3)
```

Will check the logs from AX3200 too.

**Comment by csharper2005** [comment]
> I tried mesh on 2.4 band on the Dynalink, but it didn't came up with 40 Mhz wide

Got the same error when selecting channel 13. You can try channel 1 or 9.

**Comment by xabolcs** [comment]
Thanks for the hint! Far better now!

Dynalink:
```
mesh0     ESSID: "mesh"
          Access Point: XX:XX:XX:XX:XX:XX
          Mode: Mesh Point  Channel: 9 (2.452 GHz)  HT Mode: HT20
          Center Channel 1: 9 2: unknown
          Tx-Power: 14 dBm  Link Quality: 48/70
          Signal: -62 dBm  Noise: -104 dBm
          Bit Rate: 1.0 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ax/b/g/n
          Hardware: embedded [Qualcomm Atheros IPQ8074]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy1

```

AX3200:
```
mesh0     ESSID: "mesh"
          Access Point: XX:XX:XX:XX:XX:XX
          Mode: Mesh Point  Channel: 9 (2.452 GHz)  HT Mode: HT20
          Center Channel 1: 9 2: unknown
          Tx-Power: 20 dBm  Link Quality: 52/70
          Signal: -58 dBm  Noise: -85 dBm
          Bit Rate: 288.9 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11b/g/n
          Hardware: embedded [MediaTek MT7622]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: wl0

```

Looks like it's really 2g only. And it's not only for `mt76`!

(Offtopic here, but with ath (from 9 to 11) I got only low transmission power in mesh mode. :shrug:  The max. is 14 dBm in 2g and 18 dBm in 5g mode ... Of course in `ap` mode it's all ok!)

**Comment by csharper2005** [comment]
> Looks like it's really 2g only. And it's not only for `mt76`!

Yeah, the best driver in the world is not to blame. :) The issue exists between 2 Qualcomms:
Asus OnHub Qualcomm IPQ8064 | Netgear Nighthawk X4S R7800 Qualcomm IPQ8065
-- | --

> wpa_supplicant[1864]: Could not select hw_mode and channel. (-3)

I think we need open a separate issue for this error.

**Comment by raenye** [comment]
Sharing my datapoint.

- 2.4GHz: mesh is HT20, AP is HT40
- 5GHz: both mesh and AP are VHT80

#### Device 1
Xiaomi Redmi AX6S (mt7622bv/mt7975an), identical to AX3200
snapshot r23682+8-1eb67cb070

```
# iwinfo
mesh0     ESSID: "xxxx"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Mesh Point  Channel: 9 (2.452 GHz)  HT Mode: HT20
          Center Channel 1: 9 2: unknown
          Tx-Power: 1 dBm  Link Quality: 48/70
          Signal: -62 dBm  Noise: -88 dBm
          Bit Rate: 13.0 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11b/g/n
          Hardware: embedded [MediaTek MT7622]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: wl0

mesh1     ESSID: "xxxx-5"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Mesh Point  Channel: 36 (5.180 GHz)  HT Mode: VHT80
          Center Channel 1: 42 2: unknown
          Tx-Power: 14 dBm  Link Quality: 45/70
          Signal: -65 dBm  Noise: -92 dBm
          Bit Rate: 195.1 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ac/ax/n
          Hardware: 14C3:7915 14C3:7915 [MediaTek MT7915E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: wl1
```
#### Device 2
D-Link DAP-1620-B1 (mt7621at/mt7615dn DBDC)
snapshot r23658+8-e3dd5ee02b

```
# iwinfo
mesh0     ESSID: "xxxx"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Mesh Point  Channel: 9 (2.452 GHz)  HT Mode: HT20
          Center Channel 1: 9 2: unknown
          Tx-Power: 5 dBm  Link Quality: 41/70
          Signal: -69 dBm  Noise: unknown
          Bit Rate: 13.0 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11b/g/n
          Hardware: 14C3:7615 7615:14C3 [MediaTek MT7615E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0

mesh1     ESSID: "xxxx-5"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Mesh Point  Channel: 36 (5.180 GHz)  HT Mode: VHT80
          Center Channel 1: 42 2: unknown
          Tx-Power: 14 dBm  Link Quality: 40/70
          Signal: -71 dBm  Noise: -85 dBm
          Bit Rate: 468.0 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ac/n
          Hardware: 14C3:7615 7615:14C3 [MediaTek MT7615E]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy1
```

**Comment by csharper2005** [comment]
23.05.0 - issue is still alive

**Comment by Writter77** [comment]
In my Xiaomi AX3200 does not switch to 40MHz. If there is a force 40MHz also does not switch to 40MHz. I have 20MHz all the time. How to fix it?

**Comment by raenye** [comment]
@Writter77 are you talking about mesh (802.11s)? If not, your issue is not related to this one.

**Comment by Writter77** [comment]
I'm not talking about mesh Despite this, the problem also occurs on ordinary openwrt without mesh

**Comment by raenye** [comment]
So please avoid writing about your problem in an issue specific to mesh points, even if the symptoms seem similar.
Your problem is probably due to misconfiguration, and it's better to ask about it in the forum or over discord.

**Comment by exidler** [comment]
OpenWrt 23.05.0 release: `OpenWrt 23.05.0 r23497-6637af95aa` build with official builder with customized packages list
WPAD: wpad-wolfssl
HW: BPI-R3 (mediatek/filogic)

2.4 Ghz HT40 does not work in mesh mode.
Tried 1, 6 channel. WPA3-SAE and no-encryption too. 
No luck, only 20Mhz

5Ghz mesh - 80Mhz works fine!

```
mesh   ESSID: "xxxx"
          Access Point: C2:1B:30:B9:2B:D8
          Mode: Mesh Point  Channel: 6 (2.437 GHz)  HT Mode: HT20
          Center Channel 1: 6 2: unknown
          Tx-Power: 23 dBm  Link Quality: 56/70
          Signal: -54 dBm  Noise: -92 dBm
          Bit Rate: 258.0 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ax/b/g/n
          Hardware: embedded [MediaTek MT7986]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0
```

```
config wifi-device 'radio0'
	option type 'mac80211'
	option path 'platform/soc/18000000.wifi'
	option channel '6'
	option band '2g'
	option htmode 'HE40'
	option noscan '1'
	option cell_density '0'
	option txpower '23'

config wifi-iface 'wifinet5'
	option device 'radio0'
	option mode 'mesh'
	option encryption 'sae'
	option mesh_id 'xxxx'
	option mesh_fwding '1'
	option mesh_rssi_threshold '0'
	option network 'lan'
	option key 'xxxx'
```

**Comment by csharper2005** [comment]
@Ansuel we found a root cause for 22.03.5 [here](https://forum.openwrt.org/t/openwrt-23-05-0-first-stable-release/174239/361). 

The `23.05` and `main` issue looks much more complex. `noscan=1` is in place. https://github.com/openwrt/openwrt/issues/13128 seems to be related. Likely this started after https://github.com/openwrt/openwrt/commit/304423a4ff841129f1b6b7504c83dd11c1f71c84.
```
cat wpa_supplicant-phy0-mesh0.conf
country=**
network={

        ssid="2400"
        key_mgmt=SAE
        mode=5
        mesh_fwding=1
        mesh_rssi_threshold=0
        fixed_freq=1
        frequency=2452
        ht40=1
        disable_vht=1
        noscan=1
        sae_password="*************"
        beacon_int=100
}
```

**Comment by Ansuel** [comment]
@csharper2005 can you by chance provide the change done for 22.03?

**Comment by Ansuel** [comment]
I found the problem! @csharper2005 can you compile a testing image?

**Comment by csharper2005** [comment]
> I found the problem! @csharper2005 can you compile a testing image?

Great news! I can. Please let me know what should be patched and which branch.
