### ISSUE TITLE
mtk7621 build syncconfig error

### ISSUE THREAD

**Issue by lushangkan** [openwrt/openwrt#13124]
### Describe the bug

Building mt7621 openwrt-23.05 branch error in WSL Ubuntu 22.04

Error log: [log](https://pastebin.com/akYchFHs)

Error Log Summary: 
```
Register multiple callbacks to ct events (NF_CONNTRACK_CHAIN_EVENTS) [N/y/?] (NEW) make[7]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[6]: *** [Makefile:628: syncconfig] Error 2
make[5]: *** [Makefile:748: include/config/auto.conf.cmd] Error 2
```

### OpenWrt version

openwrt-23.05/57e7188

### OpenWrt target/subtarget

ramips/mt7621

### Device

Xiaomi redmi AC2100

### Image kind

Self-built image

### Diffconfig

```text
https://pastebin.com/DvVNcqMb
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by john-tho** [comment]
> `NF_CONNTRACK_CHAIN_EVENTS`
> [x] I am reporting an issue for OpenWrt, not an unsupported fork.

This looks like it comes from a downstream fork? In that case, it is not an OpenWrt issue.

**Comment by lushangkan** [comment]
Tried to compile in [github action ](https://github.com/lushangkan/openwrt-mt7621/actions/runs/5573313273/jobs/10180420957), but still failed
