### ISSUE TITLE
Accidentally deleted the package libnl-tiny2023-04-02

### ISSUE THREAD

**Issue by KoRn0509** [openwrt/openwrt#13179]
### Describe the bug

Accidentally deleted the package libnl-tiny2023-04-02 now I can't log in via ssh, does not accept the password. Also the web interface says that Not Found Xiaomi AX6S 23.05.0-rc2 Is it possible to restore without resetting?

### OpenWrt version

23.05.0-rc2

### OpenWrt target/subtarget

23.05.0-rc2

### Device

Xiaomi AX6S

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
You have to reset since "deletion: happened in overlay filesystem the files are intact in the initial root filesystem.

**Comment by jow-** [comment]
Use the forums or mailing lists for support questions.
