### ISSUE TITLE
mediatek/filogic sysupgrade not work after 54dc1cd commit

### ISSUE THREAD

**Issue by dick902** [openwrt/openwrt#13173]
### Describe the bug

sysupgrade error and report target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh Line 43 error

### OpenWrt version

r23627-dcdcfc1511

### OpenWrt target/subtarget

mediatek/filogic

### Device

TP-Link TL-XDR6088

### Image kind

Self-built image

### Steps to reproduce

flash firmware in Luci GUI or use sysupgrade command. 

### Actual behaviour

report target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh Line 43 error.
Flash firmware not proceed at all even use -F

### Expected behaviour

proceed firmware flash

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ynezz** [comment]
Fixed via edd146c9202a5ef1195eafeb9e9e51f3de34c229
