### ISSUE TITLE
msm8996.dsti problem occurred when compiling 6.1 kernel under ax6！

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/openwrt#13230]
### Describe the bug

![image](https://github.com/openwrt/openwrt/assets/45259624/54fd9b1b-7651-4182-bfdf-4cdd0b0c0e0f)

### OpenWrt version

master branch

### OpenWrt target/subtarget

main

### Device

AX6: 6.1 kernel

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
This is completely irrelevant to OpenWrt, that SoC isn't even supported.
Its an upstream issue and just a warning in the end.

**Comment by zxlhhyccc** [comment]
> This is completely irrelevant to OpenWrt, that SoC isn't even supported. Its an upstream issue and just a warning in the end.

This warning was not available in the previous 5.15 kernel!

**Comment by robimarko** [comment]
But again, its completely irrelevant as the SoC is not used at all, why bother patch it?

**Comment by zxlhhyccc** [comment]
> But again, its completely irrelevant as the SoC is not used at all, why bother patch it?

Mainly compilation time to see uncomfortable!

**Comment by robimarko** [comment]
Thats not a good reason, we are not going to carry patches for unused SoC-s.

**Comment by hauke** [comment]
Please check if this is also a problem in upstream kernel and try to get it fixed there.

This SoC is not used in OpenWrt, so this warning is not relevant for OpenWrt.
