### ISSUE TITLE
AX210 pci-e wireless card doesn't work

### ISSUE THREAD

**Issue by HeHeHeeeeee** [openwrt/openwrt#13251]
### Describe the bug

I use EXSI8 passthrough the AX210 pci-e wireless card, but found it doesn't work.
1.I have downloaded iwlwifi-firmware-ax210, kmod-iwlwifi package and wireless-tools package.
2. ifconfig can't find my wireless card.
3. I turn to Network and found that there is no option named wireless
4. I use official image and download iwlwifi-firmware-ax210, kmod-iwlwifi package, but can't find /etc/config/wireless files. And when I built image myself, there is /etc/config/wireless with no content in it.
5. So what should I do? I can't use WIFI now.

### OpenWrt version

r23228-cd17d8df2a

### OpenWrt target/subtarget

x86/64

### Device

VMware, Inc. VMware20,1

### Image kind

Official downloaded image

### Steps to reproduce

Just boot

### Actual behaviour

dmesg info:

[    0.000000] Linux version 5.15.118 (builder@buildhost) (x86_64-openwrt-linux-musl-gcc (OpenWrt GCC 12.3.0 r23228-cd17d8df2a) 12.3.0, GNU ld (GNU Binutils) 2.40.0) #0 SMP Mon Jun 26 11:20:39 2023
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz root=PARTUUID=150ec62c-2527-2a0b-e2d5-0346afe96102 rootwait console=tty0 console=ttyS0,115200n8 noinitrd
--------------------------------------
etc.....
--------------------------------------
[    3.592697] kmodloader: loading kernel modules from /etc/modules.d/*
[    3.603480] e1000: Intel(R) PRO/1000 Network Driver
[    3.605518] e1000: Copyright (c) 1999-2006 Intel Corporation.
[    3.606880] ixgbe: Intel(R) 10 Gigabit PCI Express Network Driver
[    3.607434] ixgbe: Copyright (c) 1999-2016 Intel Corporation.
[    3.608210] i2c_dev: i2c /dev entries driver
[    3.609129] Loading modules backported from Linux version v6.1.24-0-g0102425ac76b
[    3.609712] Backport generated by backports.git v5.15.92-1-44-gd6ea70fafd36
[    3.610896] e1000e: Intel(R) PRO/1000 Network Driver
[    3.611460] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    3.612558] Intel(R) 2.5G Ethernet Linux Driver
[    3.613101] Copyright(c) 2018 Intel Corporation.
[    3.616582] Intel(R) Wireless WiFi driver for Linux
[    3.618697] iwlwifi 0000:02:01.0: enabling device (0000 -> 0002)
[    3.620940] iwlwifi 0000:02:01.0: Direct firmware load for iwlwifi-ty-a0-gf-a0-72.ucode failed with error -2
[    3.621634] iwlwifi 0000:02:01.0: Falling back to sysfs fallback for: iwlwifi-ty-a0-gf-a0-72.ucode
[    3.631509] PPP generic driver version 2.4.2
[    3.633941] iwlwifi 0000:02:01.0: Direct firmware load for iwlwifi-ty-a0-gf-a0-71.ucode failed with error -2
[    3.634636] iwlwifi 0000:02:01.0: Falling back to sysfs fallback for: iwlwifi-ty-a0-gf-a0-71.ucode
[    3.635498] NET: Registered PF_PPPOX protocol family
[    3.638388] kmodloader: done loading kernel modules from /etc/modules.d/*
[    3.639200] iwlwifi 0000:02:01.0: Direct firmware load for iwlwifi-ty-a0-gf-a0-70.ucode failed with error -2
[    3.639876] iwlwifi 0000:02:01.0: Falling back to sysfs fallback for: iwlwifi-ty-a0-gf-a0-70.ucode
[    3.641561] iwlwifi 0000:02:01.0: Direct firmware load for iwlwifi-ty-a0-gf-a0-69.ucode failed with error -2
[    3.643941] iwlwifi 0000:02:01.0: Falling back to sysfs fallback for: iwlwifi-ty-a0-gf-a0-69.ucode
[    3.645480] iwlwifi 0000:02:01.0: Direct firmware load for iwlwifi-ty-a0-gf-a0-68.ucode failed with error -2
[    3.646327] iwlwifi 0000:02:01.0: Falling back to sysfs fallback for: iwlwifi-ty-a0-gf-a0-68.ucode
[    3.647891] iwlwifi 0000:02:01.0: Direct firmware load for iwlwifi-ty-a0-gf-a0-67.ucode failed with error -2
[    3.648612] iwlwifi 0000:02:01.0: Falling back to sysfs fallback for: iwlwifi-ty-a0-gf-a0-67.ucode
[    3.651750] iwlwifi 0000:02:01.0: api flags index 2 larger than supported by driver
[    3.654249] iwlwifi 0000:02:01.0: TLV_FW_FSEQ_VERSION: FSEQ Version: 0.63.2.2
[    3.656028] iwlwifi 0000:02:01.0: loaded firmware version 66.f1c864e0.0 ty-a0-gf-a0-66.ucode op_mode iwlmvm
[    3.656759] iwlwifi 0000:02:01.0: Detected Intel(R) Wi-Fi 6 AX210 160MHz, REV=0x420
[    3.657429] thermal thermal_zone0: failed to read out thermal zone (-61)
[    4.705837] iwlwifi 0000:02:01.0: SecBoot CPU1 Status: 0x7e9c, CPU2 Status: 0xb03
[    4.708070] iwlwifi 0000:02:01.0: WFPM_LMAC1_PD_NOTIFICATION: 0x0
[    4.708679] iwlwifi 0000:02:01.0: HPM_SECONDARY_DEVICE_STATE: 0x42
[    4.709271] iwlwifi 0000:02:01.0: WFPM_MAC_OTP_CFG7_ADDR: 0x0
[    4.709818] iwlwifi 0000:02:01.0: WFPM_MAC_OTP_CFG7_DATA: 0x0
[    4.710410] iwlwifi 0000:02:01.0: UMAC PC: 0xc0081848
[    4.710960] iwlwifi 0000:02:01.0: LMAC PC: 0x4d0cce
[    4.711488] iwlwifi 0000:02:01.0: WRT: Collecting data: ini trigger 13 fired (delay=0ms).
[    4.956719] iwlwifi 0000:02:01.0: Start IWL Error Log Dump:
[    4.958838] iwlwifi 0000:02:01.0: Transport status: 0x00000042, valid: 6
[    4.959420] iwlwifi 0000:02:01.0: Loaded firmware version: 66.f1c864e0.0 ty-a0-gf-a0-66.ucode
[    4.960024] iwlwifi 0000:02:01.0: 0x00000084 | NMI_INTERRUPT_UNKNOWN
[    4.960620] iwlwifi 0000:02:01.0: 0x002002F0 | trm_hw_status0
[    4.961190] iwlwifi 0000:02:01.0: 0x00000000 | trm_hw_status1
[    4.961723] iwlwifi 0000:02:01.0: 0x004DA722 | branchlink2
[    4.962255] iwlwifi 0000:02:01.0: 0x004D0CCE | interruptlink1
[    4.962800] iwlwifi 0000:02:01.0: 0x004D0CCE | interruptlink2
[    4.963315] iwlwifi 0000:02:01.0: 0x004D94DA | data1
[    4.963793] iwlwifi 0000:02:01.0: 0x01000000 | data2
[    4.964303] iwlwifi 0000:02:01.0: 0x00000000 | data3
[    4.964801] iwlwifi 0000:02:01.0: 0x00000000 | beacon time
[    4.965315] iwlwifi 0000:02:01.0: 0x000EB97F | tsf low
[    4.965821] iwlwifi 0000:02:01.0: 0x00000000 | tsf hi
[    4.966268] iwlwifi 0000:02:01.0: 0x00000000 | time gp1
[    4.966752] iwlwifi 0000:02:01.0: 0x000FF986 | time gp2
[    4.968906] iwlwifi 0000:02:01.0: 0x00000001 | uCode revision type
[    4.969417] iwlwifi 0000:02:01.0: 0x00000042 | uCode version major
[    4.969929] iwlwifi 0000:02:01.0: 0xF1C864E0 | uCode version minor
[    4.970430] iwlwifi 0000:02:01.0: 0x00000420 | hw version
[    4.970880] iwlwifi 0000:02:01.0: 0x18C89002 | board version
[    4.971312] iwlwifi 0000:02:01.0: 0x8004FC12 | hcmd
[    4.971726] iwlwifi 0000:02:01.0: 0x00020000 | isr0
[    4.972149] iwlwifi 0000:02:01.0: 0x00000000 | isr1
[    4.972568] iwlwifi 0000:02:01.0: 0x00F00002 | isr2
[    4.972951] iwlwifi 0000:02:01.0: 0x00C0000C | isr3
[    4.973333] iwlwifi 0000:02:01.0: 0x00000000 | isr4
[    4.973697] iwlwifi 0000:02:01.0: 0x00000000 | last cmd Id
[    4.974074] iwlwifi 0000:02:01.0: 0x004D94DA | wait_event
[    4.974453] iwlwifi 0000:02:01.0: 0x00000000 | l2p_control
[    4.974841] iwlwifi 0000:02:01.0: 0x00000000 | l2p_duration
[    4.975200] iwlwifi 0000:02:01.0: 0x00000000 | l2p_mhvalid
[    4.975559] iwlwifi 0000:02:01.0: 0x00000000 | l2p_addr_match
[    4.975957] iwlwifi 0000:02:01.0: 0x00000009 | lmpm_pmg_sel
[    4.976296] iwlwifi 0000:02:01.0: 0x00000000 | timestamp
[    4.976641] iwlwifi 0000:02:01.0: 0x001C0000 | flow_handler
[    4.977023] iwlwifi 0000:02:01.0: Start IWL Error Log Dump:
[    4.979040] iwlwifi 0000:02:01.0: Transport status: 0x00000042, valid: 7
[    4.979410] iwlwifi 0000:02:01.0: 0x20000066 | NMI_INTERRUPT_HOST
[    4.979755] iwlwifi 0000:02:01.0: 0x00000000 | umac branchlink1
[    4.980095] iwlwifi 0000:02:01.0: 0x8045DFC6 | umac branchlink2
[    4.980416] iwlwifi 0000:02:01.0: 0x8047FAB6 | umac interruptlink1
[    4.980748] iwlwifi 0000:02:01.0: 0x8047FAB6 | umac interruptlink2
[    4.981076] iwlwifi 0000:02:01.0: 0x01000000 | umac data1
[    4.981390] iwlwifi 0000:02:01.0: 0x8047FAB6 | umac data2
[    4.981706] iwlwifi 0000:02:01.0: 0x00000000 | umac data3
[    4.982005] iwlwifi 0000:02:01.0: 0x00000042 | umac major
[    4.982305] iwlwifi 0000:02:01.0: 0xF1C864E0 | umac minor
[    4.982601] iwlwifi 0000:02:01.0: 0x000FFA95 | frame pointer
[    4.982908] iwlwifi 0000:02:01.0: 0xC088625C | stack pointer
[    4.983208] iwlwifi 0000:02:01.0: 0x00000000 | last host cmd
[    4.983508] iwlwifi 0000:02:01.0: 0x00000400 | isr status reg
[    4.983818] iwlwifi 0000:02:01.0: IML/ROM dump:
[    4.984086] iwlwifi 0000:02:01.0: 0x00000B03 | IML/ROM error/state
[    4.984450] iwlwifi 0000:02:01.0: 0x00007E9C | IML/ROM data1
[    4.984811] iwlwifi 0000:02:01.0: 0x00000090 | IML/ROM WFPM_AUTH_KEY_0
[    4.985180] iwlwifi 0000:02:01.0: Fseq Registers:
[    4.985461] iwlwifi 0000:02:01.0: 0x60000000 | FSEQ_ERROR_CODE
[    4.985778] iwlwifi 0000:02:01.0: 0x80440003 | FSEQ_TOP_INIT_VERSION
[    4.986163] iwlwifi 0000:02:01.0: 0x00080009 | FSEQ_CNVIO_INIT_VERSION
[    4.986506] iwlwifi 0000:02:01.0: 0x0000A652 | FSEQ_OTP_VERSION
[    4.986820] iwlwifi 0000:02:01.0: 0x00000002 | FSEQ_TOP_CONTENT_VERSION
[    4.987172] iwlwifi 0000:02:01.0: 0x4552414E | FSEQ_ALIVE_TOKEN
[    4.989184] iwlwifi 0000:02:01.0: 0x00400410 | FSEQ_CNVI_ID
[    4.989509] iwlwifi 0000:02:01.0: 0x00400410 | FSEQ_CNVR_ID
[    4.989822] iwlwifi 0000:02:01.0: 0x00400410 | CNVI_AUX_MISC_CHIP
[    4.990168] iwlwifi 0000:02:01.0: 0x00400410 | CNVR_AUX_MISC_CHIP
[    4.990500] iwlwifi 0000:02:01.0: 0x00009061 | CNVR_SCU_SD_REGS_SD_REG_DIG_DCDC_VTRIM
[    4.990894] iwlwifi 0000:02:01.0: 0x00000061 | CNVR_SCU_SD_REGS_SD_REG_ACTIVE_VDIG_MIRROR
[    4.991298] iwlwifi 0000:02:01.0: Failed to start RT ucode: -110
[    4.991638] iwlwifi 0000:02:01.0: WRT: Collecting data: ini trigger 13 fired (delay=0ms).
[    8.182097] iwlwifi 0000:02:01.0: Failed to run INIT ucode: -110
[    8.195833] iwlwifi 0000:02:01.0: retry init count 0
----------------------
etc......
----------------------
[   11.041275] iwlwifi 0000:02:01.0: retry init count 1
----------------------
etc......
----------------------
[   13.845881] iwlwifi 0000:02:01.0: retry init count 2

### Expected behaviour

I wish I can use my AX210 pci-e wireless card.

### Additional info

![{C85IOFN6`C9@N5)R~WA4RD](https://github.com/openwrt/openwrt/assets/100530448/9ef4278f-c31c-4e9b-ba21-da0503ef89cd)

ifconfig info:

br-lan    Link encap:Ethernet  HWaddr 00:0C:29:61:EC:9A
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fd38:b3b:14e9::1/60 Scope:Global
          inet6 addr: fe80::20c:29ff:fe61:ec9a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7019 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18752 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:872700 (852.2 KiB)  TX bytes:5625785 (5.3 MiB)

eth0      Link encap:Ethernet  HWaddr 00:0C:29:61:EC:9A
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:93933 errors:0 dropped:41 overruns:0 frame:0
          TX packets:18752 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:29468274 (28.1 MiB)  TX bytes:5625785 (5.3 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:88 errors:0 dropped:0 overruns:0 frame:0
          TX packets:88 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:9718 (9.4 KiB)  TX bytes:9718 (9.4 KiB)

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
This is timeout connecting firmware on the card after that is loaded:
```
 [ 4.991298] iwlwifi 0000:02:01.0: Failed to start RT ucode: -110
```
Likely it has to do with virtualisation reset domains, power save or IRQ virtualisation, PCIE address spaces not mapped in same order as normal host.

Please check web documentation if you are close to being compatible. No wifi adapters supported by vmware at all.

**Comment by HeHeHeeeeee** [comment]
> This is timeout connecting firmware on the card after that is loaded:
> 
> ```
>  [ 4.991298] iwlwifi 0000:02:01.0: Failed to start RT ucode: -110
> ```
> 
> Likely it has to do with virtualisation reset domains, power save or IRQ virtualisation, PCIE address spaces not mapped in same order as normal host.
> 
> Please check web documentation if you are close to being compatible. No wifi adapters supported by vmware at all.
> 
> One thing to check is if device brings up or fails same in a supported guest OS - e.g Fedora or Ubuntu and approach "official support channels"

Thanks for your reply, it seems not to do with power save or PCIE mapping.  I have limited knowledge and can't test the other reason may conduce to this situation. I think the most possible reason conduce to this is about EXSI system, then I will try using PVE system to test if I can use it successfully. Thanks again. If other people have the same question, I will appreciate it if you can discuss it in this issue.

**Comment by brada4** [comment]
https://www.rdcloudcompute.com/2021/09/manage-esxi-using-wifi-enable-wifi-networking-for-esxi-lab-use-only.html#comment-1466
Problem lies outside vm operating system.

**Comment by HeHeHeeeeee** [comment]
> https://www.rdcloudcompute.com/2021/09/manage-esxi-using-wifi-enable-wifi-networking-for-esxi-lab-use-only.html#comment-1466 Problem lies outside vm operating system.

As I mentioned before, I have download kmod-iwlwifi. I tried to update the maximum version which can be detected by openwrt system was iwlwifi-ty-a0-gf-a0-72.ucode, but it had no effect. Scrutinizing the log we can find the system actually find the wifi driver.
[ 4.959420] iwlwifi 0000:02:01.0: Loaded firmware version: 66.f1c864e0.0 ty-a0-gf-a0-66.ucode

**Comment by HeHeHeeeeee** [comment]
Then I add AX210 pci-e wireless card to the other virtual machine, Ubuntu Server 22.04 on EXSI8 and find the same error. The kernel version is 5.15.x too, so will the linux kernel version to low conduce this error? But I find the AX210 support minimum kernel version is 5.1.

**Comment by HeHeHeeeeee** [comment]
> I sent refetence that it is hit and miss attaching wifi adapter to a vm. Even windows fails to connect some not mentioned adapter, while other one works reliably. With supported guest you are eligible to ask esxii support. May happen they share some trick that works for openwrt.

Thanks for your advice, and I transferred to the PVE platform and found that wireless can be used. It seems that it is indeed an issue with EXSI

**Comment by Delitants** [comment]
Was this card fully enabled for AP mode with 2.4/5/6 bands? Why ticket issue got closed as completed without details?
