### ISSUE TITLE
[23.05] DNAT rule: not defaulting to adress family any

### ISSUE THREAD

**Issue by ahuse** [openwrt/openwrt#13252]
### Describe the bug

Hi,

i setup port forwarding (redirecting) of external port `123` to internal port `51820` of my openwrt device for better accessing my wireguard server in difficult environments. I set it up via LUCI which resulted in the following config in `/etc/config/firewall`:

```
config redirect
	option target 'DNAT'
	option name 'Redirect-Wireguard'
	list proto 'udp'
	option src 'wan'
	option src_dport '123'
	option dest_port '51820'
```

This config worked for IPv4, but not for IPv6. To get IPv6 working i had to add `option family 'any'`. I was not exptecting this because the `Restrict to address family`-option in LUCI was set to 'automatic' and this should default to `any` in UCI, right? I am on 23.05-snapshot.

### OpenWrt version

r23334-11b0c43671

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Linksys E8450 (UBI)

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
This is intentional to not accidentally expose IPv6 for users migrating from fw3.

I'll change the LuCI wording to be more explicit.
