### ISSUE TITLE
Problem with the USB port not working in the snapshot image of fortigate 50e.

### ISSUE THREAD

**Issue by odkrys** [openwrt/openwrt#13412]
### Describe the bug

fortinet_fg-50e-squashfs-sysupgrade.bin / Mon Sep 4 05:09:15 2023

As the title says, the USB port does not work.
It works in rc3.

@musashino205 
Hello again.
Could you please test it?
The USB port also does not work in the image you uploaded in the previous problem.

### OpenWrt version

r23880-8554a4a7e3

### OpenWrt target/subtarget

mvebu/cortexa9

### Device

Fortinet FortiGate 50E

### Image kind

Official downloaded image

### Additional info

syslog after booting.

[rc3.txt](https://github.com/openwrt/openwrt/files/12512043/rc3.txt)
[snapshot.txt](https://github.com/openwrt/openwrt/files/12512044/snapshot.txt)

### Diffconfig

rc3
```
kernel: [    8.923046] 0x000000a50000-0x000002000000 : "rootfs_data"
```
snapshot
```
kernel: [    8.769543] 0x000000a00000-0x000002000000 : "rootfs_data"
```

rc3
```
kernel: [  112.632602] mount_root: switching to jffs2 overlay
```
snapshot
```
mount_root: failed to sync jffs2 overlay
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by odkrys** [comment]
I reverted two commits, and now the usb works on my 6.1 test kernel.

https://github.com/openwrt/openwrt/commit/3eebb91317c64864b86cea21ae07ab84d4f4bcc1
https://github.com/openwrt/openwrt/commit/5356462ce54734afd32fce83ad118c58cfeb2a55

**Comment by musashino205** [comment]
Adding ```fw_devlink=permissive" to bootargs may be available as a workaround.
ex.: https://github.com/musashino-build/openwrt/commit/a5970eb031edc9be473710254fb74f5cba14bb20

**Comment by mpratt14** [comment]
https://github.com/openwrt/openwrt/pull/11302 is rebased and ready for testing again

note the last commit "strict as default". if you still have issues try dropping that last commit
