### ISSUE TITLE
Sysupgrade to 23.05-rc3 breaks mt7915

### ISSUE THREAD

**Issue by roydalpra** [openwrt/openwrt#13436]
### Describe the bug

After the sysupgrade to 03.5 -rc3 the mt7915 on my belkin 3200 was replaced by a generic entry and would not start. I think the following log entries may be relevant.  7.353267] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[    7.365796] mt7915e 0000:01:00.0: assign IRQ: got 146
[    7.370919] mt7915e 0000:01:00.0: enabling device (0000 -> 0002)
[    7.377031] mt7915e 0000:01:00.0: enabling bus mastering
[    7.502002] mtk-pcie 1a143000.pcie: msi#0 address_hi 0x0 address_lo 0x44d6d0c0
[    7.541930] urngd: v1.0.2 started.
[    7.552090] mt7915e 0000:01:00.0: Direct firmware load for mediatek/mt7915_rom_patch.bin failed with error -2
[    7.562036] mt7915e 0000:01:00.0: Falling back to sysfs fallback for: mediatek/mt7915_rom_patch.bin
[    8.167129] mt7915e: probe of 0000:01:00.0 failed with error -12
[    8.197586] PPP generic driver version 2.4.2

### OpenWrt version

OpenWrt 23.05.0-rc3 r23389-5deed175a5 / LuCI openwrt-23.05 bran

### OpenWrt target/subtarget

Mediatek/mt7622

### Device

LInksys E8450 (UBI)

### Image kind

Official downloaded image

### Additional info

Device is actually belkin rt3200 but is displayed as Linksys E8450 (UBI). 

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by philwiffen** [comment]
Are you building a custom image?

If so, there's a difference between 22.03 and 23.05, that I found when moving from 22.03 to 23.05-rc3

23.05 needs these:` kmod-mt7622-firmware kmod-mt7915-firmware`

Whereas 22.03 needed these:` kmod-mt7615-firmware kmod-mt7615e kmod-mt7915e`

Once I used` kmod-mt7622-firmware kmod-mt7915-firmware`, wifi was working again

**Comment by DragonBluep** [comment]
Not a bug. You just need a clean installation instead of using the `Attendedsysupgrade Server`.
