### ISSUE TITLE
 ipv4 routing rules are invalid

### ISSUE THREAD

**Issue by dongc123** [openwrt/openwrt#13458]
### Describe the bug

The ipv4 routing rule is invalid. Please tell me how to configure and use this ipv4 routing rule.
![微信截图_20230915164602](https://github.com/openwrt/openwrt/assets/109882914/0aa55aff-e505-43d0-aee9-5244757eb83b)
![微信截图_20230915164631](https://github.com/openwrt/openwrt/assets/109882914/00d7d718-7adf-4398-96dc-58809966d2f6)

### OpenWrt version

OpenWrt 23.05.0-rc3 r23389-5deed175a5

### OpenWrt target/subtarget

x86/64

### Device

x86/64

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by dongc123** [comment]
The IP address 172 is for testing. By capturing packets with tcpdump, you can see that the data does not go out from the iptv port.

**Comment by brada4** [comment]
`ip ro sh` (wipe 2 middle bytes of recognisable public IP addresses)

It is absolutely unlikely that iptv multicast  network will be globally routable as for the web browser.

Default routing table (last field) should be main (254) if you do not have any pbr like mwan enabled.

**Comment by brada4** [comment]
First things first - lets learn to operate putty:
Run `ip ro sh`
Then select the output and sommand WITHOUT RIGHT CLICK
Now start text block with 3 backticks \`\`\`
Paste text that putty marked and copied.
Finish with 3 more backticks.

I would take exactly opposite approach - try to get route right with command line `ip route` then try to repeat experiment in luci.
Manual is here https://www.linux.org/docs/man8/ip-route.html , default `ip` is from busybox and it excludes some corner-case options, but those implemented follow the manual.

You understand iptv network uses IP addresses in its private range and probably filters all other addresses off.

**Comment by dongc123** [comment]
Thanks

**Comment by brada4** [comment]
But show the routing table, more eyes see better like overlapping routes or not bound to interface etc.

**Comment by LGA1150** [comment]
Do NOT set `传入接口名称`. Packets originating from your router are not from `lan`.

**Comment by jow-** [comment]
User configuration issue
