### ISSUE TITLE
[MT7628] Xiaomi Router 4A kernel panic when using aireplay-ng (2.4 Ghz)

### ISSUE THREAD

**Issue by ShredRum** [openwrt/openwrt#13586]
### Describe the bug

Hello. I put the router into monitor mode, then try to deauthenticate via mac, after which the router immediately reboots

I'm not sure if this is a kernel panic, but I found a similar report here
https://github.com/openwrt/openwrt/issues/5102
https://github.com/openwrt/mt76/issues/504
https://github.com/openwrt/mt76/issues/504

Also, I don’t know where it’s better to publish the issue, in mt76 or here, so forgive me if I’m confused.
I'm ready to check this in more detail if you provide me with information on how to record a log/dump. Thank you.

### OpenWrt version

r24054-fe10f97439

### OpenWrt target/subtarget

ramips/mt76x8

### Device

Xiaomi Mi Router 4A (100M International Edition)

### Image kind

Official downloaded image

### Steps to reproduce

1. Install aircrack-ng and airmon-ng
2. Switch the access point to monitor mode (airmon-ng start)
3. Run aireplay-ng -0 100 -a DC:2C:6E:44:D5:83 wlan0mon --ignore-negative-one

### Actual behaviour

The device will freeze and reboot; only the line will appear in the terminal

04:59:26  Sending DeAuth (code 7) to broadcast -- BSSID: [DC:2C:6E:44:D5:83]

### Expected behaviour

Sending deauthentication packets to a given MAC without failure

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Try `logread -f` while crashing the router.
Victim model likely absolutely required to continue.

**Comment by ShredRum** [comment]
> Try `logread -f` while crashing the router. Victim model likely absolutely required to continue.

After the crash, nothing new appears. But after switching the adapter to monitor mode, I see repeated spam in the terminal with the lines

Mon Oct 2 22:44:27 2023 daemon.err hostapd: Failed to set beacon parameters

**Comment by ShredRum** [comment]
Also the problem does NOT occur with the 5GHz network

**Comment by ShredRum** [comment]
Since this problem most likely relates to a specific driver, I decided to close this issue and move it to the appropriate discussion.
https://github.com/openwrt/mt76/issues/825
