### ISSUE TITLE
Bug: [23.05.0-rc4] mt76/mt7921: AP fail to start after reboot

### ISSUE THREAD

**Issue by davidngrc** [openwrt/openwrt#13642]
### Describe the bug

I am on proxmox 7.4-17 with Kernel Linux 5.15.116-1-pve
I have only one wifi card passthrough to this x64 system, which is a 
MediaTek Model: MT7921
AW-XB468NF REV0A
the AP mode works fine, but after I reboot OpenWrt, the AP will not associate with the m2 card anymore.
I need to manually disable the AP in the UI, and then re-enable it, then the wifi works.

root@OpenWrt:~# lspci
`01:00.0 Network controller: MEDIATEK Corp. MT7921 802.11ax PCI Express Wireless Network Adapter`

root@OpenWrt:~# iw list
Wiphy phy0
	wiphy index: 0
	max # scan SSIDs: 4
	max scan IEs length: 482 bytes
	max # sched scan SSIDs: 10
	max # match sets: 16
	Retry short limit: 7
	Retry long limit: 4
	Coverage class: 0 (up to 0m)
	Device supports AP-side u-APSD.
	Device supports T-DLS.
	Available Antennas: TX 0x3 RX 0x3
	Configured Antennas: TX 0x3 RX 0x3
	Supported interface modes:
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
		 * P2P-client
		 * P2P-GO
	Band 1:
		Capabilities: 0x9ff
			RX LDPC
			HT20/HT40
			SM Power Save disabled
			RX Greenfield
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			No DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: No restriction (0x00)
		HT TX/RX MCS rate indexes supported: 0-15
		HE Iftypes: managed
			HE MAC Capabilities (0x08011a000040):
				+HTC HE Supported
				Trigger Frame MAC Padding Duration: 2
				OM Control
				Maximum A-MPDU Length Exponent: 3
				A-MSDU in A-MPDU
			HE PHY Capabilities: (0x2270ce120dc0b306423f00):
				HE40/2.4GHz
				242 tone RUs/2.4GHz
				Device Class: 1
				LDPC Coding in Payload
				HE SU PPDU with 1x HE-LTF and 0.8us GI
				NDP with 4x HE-LTF and 3.2us GI
				STBC Tx <= 80MHz
				STBC Rx <= 80MHz
				Full Bandwidth UL MU-MIMO
				Partial Bandwidth UL MU-MIMO
				DCM Max Constellation: 2
				DCM Max Constellation Rx: 2
				SU Beamformee
				Beamformee STS <= 80Mhz: 3
				Ng = 16 SU Feedback
				Ng = 16 MU Feedback
				Codebook Size SU Feedback
				Codebook Size MU Feedback
				Triggered CQI Feedback
				Partial Bandwidth Extended Range
				PPE Threshold Present
				Power Boost Factor ar
				HE SU PPDU & HE PPDU 4x HE-LTF 0.8us GI
				20MHz in 40MHz HE PPDU 2.4GHz
				DCM Max BW: 1
				Longer Than 16HE SIG-B OFDM Symbols
				Non-Triggered CQI Feedback
				TX 1024-QAM
				RX 1024-QAM
				RX Full BW SU Using HE MU PPDU with Compression SIGB
				RX Full BW SU Using HE MU PPDU with Non-Compression SIGB
			HE RX MCS and NSS set <= 80 MHz
				1 streams: MCS 0-11
				2 streams: MCS 0-11
				3 streams: not supported
				4 streams: not supported
				5 streams: not supported
				6 streams: not supported
				7 streams: not supported
				8 streams: not supported
			HE TX MCS and NSS set <= 80 MHz
				1 streams: MCS 0-11
				2 streams: MCS 0-11
				3 streams: not supported
				4 streams: not supported
				5 streams: not supported
				6 streams: not supported
				7 streams: not supported
				8 streams: not supported
			PPE Threshold 0x39 0x1c 0xc7 0x71 0x1c 0x07 
		EHT Iftypes: managed
			EHT MAC Capabilities (0x0000):
			EHT PHY Capabilities: (0x0000000000000000):
			EHT MCS/NSS: (0x):
			EHT bw=20 MHz, max NSS for MCS 0-7: Rx=0, Tx=0
			EHT bw=20 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
			EHT bw=20 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
			EHT bw=20 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
		HE Iftypes: AP
			HE MAC Capabilities (0x00011a081044):
				+HTC HE Supported
				BSR
				OM Control
				Maximum A-MPDU Length Exponent: 3
				BQR
				A-MSDU in A-MPDU
				OM Control UL MU Data Disable RX
			HE PHY Capabilities: (0x0220ce120000a000000c00):
				HE40/2.4GHz
				LDPC Coding in Payload
				NDP with 4x HE-LTF and 3.2us GI
				STBC Tx <= 80MHz
				STBC Rx <= 80MHz
				Full Bandwidth UL MU-MIMO
				Partial Bandwidth UL MU-MIMO
				DCM Max Constellation: 2
				DCM Max Constellation Rx: 2
				Partial Bandwidth Extended Range
				PPE Threshold Present
				TX 1024-QAM
				RX 1024-QAM
			HE RX MCS and NSS set <= 80 MHz
				1 streams: MCS 0-11
				2 streams: MCS 0-11
				3 streams: not supported
				4 streams: not supported
				5 streams: not supported
				6 streams: not supported
				7 streams: not supported
				8 streams: not supported
			HE TX MCS and NSS set <= 80 MHz
				1 streams: MCS 0-11
				2 streams: MCS 0-11
				3 streams: not supported
				4 streams: not supported
				5 streams: not supported
				6 streams: not supported
				7 streams: not supported
				8 streams: not supported
			PPE Threshold 0x39 0x1c 0xc7 0x71 0x1c 0x07 
		EHT Iftypes: AP
			EHT MAC Capabilities (0x0000):
			EHT PHY Capabilities: (0x0000000000000000):
			EHT MCS/NSS: (0x):
			EHT bw=20 MHz, max NSS for MCS 0-7: Rx=0, Tx=0
			EHT bw=20 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
			EHT bw=20 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
			EHT bw=20 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
		Frequencies:
			* 2412 MHz [1] (20.0 dBm)
			* 2417 MHz [2] (20.0 dBm)
			* 2422 MHz [3] (20.0 dBm)
			* 2427 MHz [4] (20.0 dBm)
			* 2432 MHz [5] (20.0 dBm)
			* 2437 MHz [6] (20.0 dBm)
			* 2442 MHz [7] (20.0 dBm)
			* 2447 MHz [8] (20.0 dBm)
			* 2452 MHz [9] (20.0 dBm)
			* 2457 MHz [10] (20.0 dBm)
			* 2462 MHz [11] (20.0 dBm)
			* 2467 MHz [12] (20.0 dBm) (no IR)
			* 2472 MHz [13] (20.0 dBm) (no IR)
			* 2484 MHz [14] (20.0 dBm) (no IR)
	Band 2:
		Capabilities: 0x9ff
			RX LDPC
			HT20/HT40
			SM Power Save disabled
			RX Greenfield
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			No DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: No restriction (0x00)
		HT TX/RX MCS rate indexes supported: 0-15
		VHT Capabilities (0x339071b2):
			Max MPDU length: 11454
			Supported Channel Width: neither 160 nor 80+80
			RX LDPC
			short GI (80 MHz)
			TX STBC
			SU Beamformee
			MU Beamformee
			RX antenna pattern consistency
			TX antenna pattern consistency
		VHT RX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT RX highest supported: 0 Mbps
		VHT TX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT TX highest supported: 0 Mbps
		VHT extended NSS: supported
		HE Iftypes: managed
			HE MAC Capabilities (0x08011a000040):
				+HTC HE Supported
				Trigger Frame MAC Padding Duration: 2
				OM Control
				Maximum A-MPDU Length Exponent: 3
				A-MSDU in A-MPDU
			HE PHY Capabilities: (0x4470ce120dc0b306423f00):
				HE40/HE80/5GHz
				242 tone RUs/5GHz
				Device Class: 1
				LDPC Coding in Payload
				HE SU PPDU with 1x HE-LTF and 0.8us GI
				NDP with 4x HE-LTF and 3.2us GI
				STBC Tx <= 80MHz
				STBC Rx <= 80MHz
				Full Bandwidth UL MU-MIMO
				Partial Bandwidth UL MU-MIMO
				DCM Max Constellation: 2
				DCM Max Constellation Rx: 2
				SU Beamformee
				Beamformee STS <= 80Mhz: 3
				Ng = 16 SU Feedback
				Ng = 16 MU Feedback
				Codebook Size SU Feedback
				Codebook Size MU Feedback
				Triggered CQI Feedback
				Partial Bandwidth Extended Range
				PPE Threshold Present
				Power Boost Factor ar
				HE SU PPDU & HE PPDU 4x HE-LTF 0.8us GI
				20MHz in 40MHz HE PPDU 2.4GHz
				DCM Max BW: 1
				Longer Than 16HE SIG-B OFDM Symbols
				Non-Triggered CQI Feedback
				TX 1024-QAM
				RX 1024-QAM
				RX Full BW SU Using HE MU PPDU with Compression SIGB
				RX Full BW SU Using HE MU PPDU with Non-Compression SIGB
			HE RX MCS and NSS set <= 80 MHz
				1 streams: MCS 0-11
				2 streams: MCS 0-11
				3 streams: not supported
				4 streams: not supported
				5 streams: not supported
				6 streams: not supported
				7 streams: not supported
				8 streams: not supported
			HE TX MCS and NSS set <= 80 MHz
				1 streams: MCS 0-11
				2 streams: MCS 0-11
				3 streams: not supported
				4 streams: not supported
				5 streams: not supported
				6 streams: not supported
				7 streams: not supported
				8 streams: not supported
			PPE Threshold 0x39 0x1c 0xc7 0x71 0x1c 0x07 
		EHT Iftypes: managed
			EHT MAC Capabilities (0x0000):
			EHT PHY Capabilities: (0x0000000000000000):
			EHT MCS/NSS: (0x):
			EHT bw <= 80 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
			EHT bw <= 80 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
			EHT bw <= 80 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
		HE Iftypes: AP
			HE MAC Capabilities (0x00011a081044):
				+HTC HE Supported
				BSR
				OM Control
				Maximum A-MPDU Length Exponent: 3
				BQR
				A-MSDU in A-MPDU
				OM Control UL MU Data Disable RX
			HE PHY Capabilities: (0x0420ce120000a000000c00):
				HE40/HE80/5GHz
				LDPC Coding in Payload
				NDP with 4x HE-LTF and 3.2us GI
				STBC Tx <= 80MHz
				STBC Rx <= 80MHz
				Full Bandwidth UL MU-MIMO
				Partial Bandwidth UL MU-MIMO
				DCM Max Constellation: 2
				DCM Max Constellation Rx: 2
				Partial Bandwidth Extended Range
				PPE Threshold Present
				TX 1024-QAM
				RX 1024-QAM
			HE RX MCS and NSS set <= 80 MHz
				1 streams: MCS 0-11
				2 streams: MCS 0-11
				3 streams: not supported
				4 streams: not supported
				5 streams: not supported
				6 streams: not supported
				7 streams: not supported
				8 streams: not supported
			HE TX MCS and NSS set <= 80 MHz
				1 streams: MCS 0-11
				2 streams: MCS 0-11
				3 streams: not supported
				4 streams: not supported
				5 streams: not supported
				6 streams: not supported
				7 streams: not supported
				8 streams: not supported
			PPE Threshold 0x39 0x1c 0xc7 0x71 0x1c 0x07 
		EHT Iftypes: AP
			EHT MAC Capabilities (0x0000):
			EHT PHY Capabilities: (0x0000000000000000):
			EHT MCS/NSS: (0x):
			EHT bw <= 80 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
			EHT bw <= 80 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
			EHT bw <= 80 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
		Frequencies:
			* 5180 MHz [36] (20.0 dBm)
			* 5200 MHz [40] (20.0 dBm)
			* 5220 MHz [44] (20.0 dBm)
			* 5240 MHz [48] (20.0 dBm)
			* 5260 MHz [52] (20.0 dBm) (no IR, radar detection)
			* 5280 MHz [56] (20.0 dBm) (no IR, radar detection)
			* 5300 MHz [60] (20.0 dBm) (no IR, radar detection)
			* 5320 MHz [64] (20.0 dBm) (no IR, radar detection)
			* 5500 MHz [100] (20.0 dBm) (no IR, radar detection)
			* 5520 MHz [104] (20.0 dBm) (no IR, radar detection)
			* 5540 MHz [108] (20.0 dBm) (no IR, radar detection)
			* 5560 MHz [112] (20.0 dBm) (no IR, radar detection)
			* 5580 MHz [116] (20.0 dBm) (no IR, radar detection)
			* 5600 MHz [120] (20.0 dBm) (no IR, radar detection)
			* 5620 MHz [124] (20.0 dBm) (no IR, radar detection)
			* 5640 MHz [128] (20.0 dBm) (no IR, radar detection)
			* 5660 MHz [132] (20.0 dBm) (no IR, radar detection)
			* 5680 MHz [136] (20.0 dBm) (no IR, radar detection)
			* 5700 MHz [140] (20.0 dBm) (no IR, radar detection)
			* 5720 MHz [144] (20.0 dBm) (no IR, radar detection)
			* 5745 MHz [149] (20.0 dBm) (no IR)
			* 5765 MHz [153] (20.0 dBm) (no IR)
			* 5785 MHz [157] (20.0 dBm) (no IR)
			* 5805 MHz [161] (20.0 dBm) (no IR)
			* 5825 MHz [165] (20.0 dBm) (no IR)
			* 5845 MHz [169] (disabled)
			* 5865 MHz [173] (disabled)
			* 5885 MHz [177] (disabled)
	valid interface combinations:
		 * #{ managed, P2P-client } <= 2, #{ AP, P2P-GO } <= 1,
		   total <= 2, #channels <= 2
	HT Capability overrides:
		 * MCS: ff ff ff ff ff ff ff ff ff ff
		 * maximum A-MSDU length
		 * supported channel width
		 * short GI for 40 MHz
		 * max A-MPDU length exponent
		 * min MPDU start spacing
	max # scan plans: 1
	max scan plan interval: 65535
	max scan plan iterations: 0
	Supported extended features:
		* [ RRM ]: RRM
		* [ SET_SCAN_DWELL ]: scan dwell setting
		* [ BEACON_RATE_LEGACY ]: legacy beacon rate setting
		* [ BEACON_RATE_HT ]: HT beacon rate setting
		* [ BEACON_RATE_VHT ]: VHT beacon rate setting
		* [ FILS_STA ]: STA FILS (Fast Initial Link Setup)
		* [ CQM_RSSI_LIST ]: multiple CQM_RSSI_THOLD records
		* [ CONTROL_PORT_OVER_NL80211 ]: control port over nl80211
		* [ ACK_SIGNAL_SUPPORT ]: ack signal level support
		* [ TXQS ]: FQ-CoDel-enabled intermediate TXQs
		* [ CAN_REPLACE_PTK0 ]: can safely replace PTK 0 when rekeying
		* [ AIRTIME_FAIRNESS ]: airtime fairness scheduling
		* [ AQL ]: Airtime Queue Limits (AQL)
		* [ CONTROL_PORT_NO_PREAUTH ]: disable pre-auth over nl80211 control port support
		* [ SCAN_FREQ_KHZ ]: scan on kHz frequency support
		* [ CONTROL_PORT_OVER_NL80211_TX_STATUS ]: tx status for nl80211 control port support
		* [ BEACON_RATE_HE ]: HE beacon rate support (AP/mesh)

here is the dmsg after reboot, but in the GUI, it show MT7921 is not associated with any AP
[    4.642988] e1000e: Intel(R) PRO/1000 Network Driver
[    4.643480] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    4.644444] Intel(R) 2.5G Ethernet Linux Driver
[    4.644900] Copyright(c) 2018 Intel Corporation.
[    4.654261] PPP generic driver version 2.4.2
[    4.654870] NET: Registered PF_PPPOX protocol family
[    4.686939] mt7921e 0000:01:00.0: ASIC revision: 79610010
[    4.776746] kmodloader: done loading kernel modules from /etc/modules.d/*
[    4.777837] mt7921e 0000:01:00.0: HW/SW Version: 0x8a108a10, Build Time: 20230526130917a
[    4.777837] 
[    4.788561] mt7921e 0000:01:00.0: WM Firmware Version: ____010000, Build Time: 20230526130958
[    4.991406] 8021q: adding VLAN 0 to HW filter on device eth0
[    4.991989] br-lan: port 1(eth0) entered blocking state
[    4.992494] br-lan: port 1(eth0) entered disabled state
[    4.993027] device eth0 entered promiscuous mode
[    4.993690] br-lan: port 1(eth0) entered blocking state
[    4.994195] br-lan: port 1(eth0) entered forwarding state

I then disabled the AP in UI, there is no new dmsg
then I enable the same AP again, then the MT7921 is associated with AP correctly.
here is the dmsg after I enable the AP
[  482.016393] br-lan: port 2(phy0-ap0) entered blocking state
[  482.017024] br-lan: port 2(phy0-ap0) entered disabled state
[  482.017615] device phy0-ap0 entered promiscuous mode
[  482.567802] br-lan: port 2(phy0-ap0) entered blocking state
[  482.568976] br-lan: port 2(phy0-ap0) entered forwarding state
[  482.570194] br-lan: port 2(phy0-ap0) entered disabled state
[  483.153391] IPv6: ADDRCONF(NETDEV_CHANGE): phy0-ap0: link becomes ready
[  483.154634] br-lan: port 2(phy0-ap0) entered blocking state
[  483.155178] br-lan: port 2(phy0-ap0) entered forwarding state

### OpenWrt version

r23482-7fe85ce1f2

### OpenWrt target/subtarget

x86/64

### Device

QEMU Standard PC (Q35 + ICH9, 2009)

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
`iwinfo`
`/etc/config/wireless` (key option removed)
`logread -e hostapd`
And please attach files bigger than screen.

**Comment by davidngrc** [comment]
I try to use the "add code" function here, it just not display nicely, not sure why.

the command you want me to run, I attached it here.
[after_reboot_no_network.txt](https://github.com/openwrt/openwrt/files/12847994/after_reboot_no_network.txt)

[then_disable_ap_then_enable_ap.txt](https://github.com/openwrt/openwrt/files/12847996/then_disable_ap_then_enable_ap.txt)

**Comment by brada4** [comment]
add regulatory domain like `option country 'GB'` to radio section. 

Ir simply cannot start on any channel unless receiving something first in global least-common-capability "region"

**Comment by brada4** [comment]
Another try:
in /etc/modules.d find file containing module
`grep mt7921e /etc/modules.d/*`
Then after module name add the only parameter - supposedly `mt7921e disable_aspm=Y`
And try rebooting. (It should have been more evident if you attached full dmesg initially)
If it magically starts working just add the respective filename to /etc/sysupgrade.conf to keep setting over sysupgrade or auc.

**Comment by brada4** [comment]
Also you might need to power off the card completely to change country code.

**Comment by davidngrc** [comment]
vim /etc/modules.d/mt7921e:mt7921e
before content was empty, then add content mt7921e disable_aspm=Y

root@OpenWrt:~# grep mt7921e /etc/modules.d/*
/etc/modules.d/mt7921e:mt7921e disable_aspm=Y

I power off, and pull the AC wall plug, so there is no power on the PC and the wifi card inside.
re-plugin the AC wall plug, computer on, proxmox on, start openwrt vm
AP did not start.
then I get this full demsg
[full_dmesg.txt](https://github.com/openwrt/openwrt/files/12849394/full_dmesg.txt)

**Comment by davidngrc** [comment]
I notice I might do something wrong, so 
vim /etc/modules.d/mt7921e:mt7921e
change content to 
disable_aspm=Y

reboot, AP still not associate with m2 card.

root@OpenWrt:~# grep mt7921e /etc/modules.d/*
show no output

root@OpenWrt:~# cat /etc/modules.d/mt7921e
disable_aspm=Y

here is the dmesg after I run above command.
[full_dmesg v2.txt](https://github.com/openwrt/openwrt/files/12849448/full_dmesg.v2.txt)

**Comment by brada4** [comment]
You need to have line in that file in place of module name alone:

`mt7921e disable_aspm=Y`

**Comment by brada4** [comment]
Explanation - you disabled module loading, no worries yet.

In dmesg:
```
 extended config space not accessible
```
Which is usually characteristic of a virtualisation.

Does it come up after power off/on of a VM?

**Comment by brada4** [comment]
It is how proxmox and bios set the device.  Like around ACPI/APIC/PM....

If machine powerswitch fixes the problem -  it is fixable in domain.xml
<on_reboot>restart</on_reboot>

**Comment by davidngrc** [comment]
I am on another proxmox server, inside a ubuntu vm, 
then using this ubuntu to ssh into that openwrt vm, 
doing all the vim in the ssh.

the proxmox is newly setup, all and bios are in default.

**Comment by brada4** [comment]
It is how proxmox sets up devices according to bios first.
Then VM tries to  set them up, but does not see some config parts.
Then on shutdown it may not reset device from VM the way BIOS would reset it completely.
It is a lot of moving parts to sync up.

**Comment by davidngrc** [comment]
I removed proxmox, and install openwrt-23.05.0-rc4-x86-64-generic-ext4-combined.img.gz to a usb drive.
and boot that usb in the same PC.

without country code and without disable_aspm=Y
the AP is up after reboot.

so this is related to proxmox.
but I think many people will use proxmox with openwrt, so could you guys help?
or I close this issue?

---------

in proxmox, I use command
# nano /etc/modprobe.d/vfio.conf
options vfio-pci ids=14c3:7961    #m2 mt7921 wifi card

# lspci -nnk
03:00.0 Network controller [0280]: MEDIATEK Corp. Device [14c3:7961]
	Subsystem: AzureWave Device [1a3b:4682]
	Kernel driver in use: vfio-pci
	Kernel modules: mt7921e

as you can see, it already using vfio-pci, so passthrough should not be a problem.
but still got this reboot issue.

**Comment by brada4** [comment]
You isolated problem to poxmox, there is not much Openwrt can do.
You can  try to change pcie slots and bios settings around acpi/apic/power, it may work differently.
Already suggested to map reboot to domain restart you did not consider or try.

**Comment by davidngrc** [comment]
my bad, I am new to this, 
I search the keywork on "proxmox domain.xml"
there is no result, andbI nerver hear

**Comment by brada4** [comment]
quite frankly no idea, with normal libvirt/qemu/kvm that gives same machine/bios string one does `virsh edit vm-name`  and that way achieves VM poweroff and clean start in place of reboot inside running vm.

**Comment by davidngrc** [comment]
When VM openwrt rebooting, there is no dmesg on proxmox, so no idea how to trace the proxmox problem.
However, I found a temp solution here
https://forum.openwrt.org/t/fixing-disabled-radio-on-reboot/142113
since I only got 1 m2 wifi card, so the radio index is 0
vim /etc/rc.local
`/sbin/wifi down radio0
sleep 1
/sbin/wifi up radio0
exit 0
`

**Comment by doublep21** [comment]
@davidngrc sorry for the offtopic , can you use 2.4ghz and 5ghz bands at the same time in ap mode?
