### ISSUE TITLE
USB does not work on compex wpj563

### ISSUE THREAD

**Issue by alex-pnzv** [openwrt/openwrt#13650]
### Describe the bug

Hi, I have compex wpj563 router with connected kingston usb flash drive that works on openwrt 19.07.6 without any problem. After updating to OpenWrt 22.03.5 router does not detect connected usb devices at all. I installed all the packages from the [manual](https://openwrt.org/docs/guide-user/storage/usb-installing)  but it did not help, the router does not see the connected flash drive. Please help with this problem.

### OpenWrt version

r20134-5f15225c1e

### OpenWrt target/subtarget

ath79/generic

### Device

Compex WPJ563

### Image kind

Official downloaded image

### Additional info

> [    0.000000] Linux version 5.10.176 (builder@buildhost) (mips-openwrt-linux-musl-gcc (OpenWrt GCC 11.2.0 r20134-5f15225c1e) 11.2.0, GNU ld (GNU Binutils) 2.37) #0 Thu Apr 27 20:28:15 2023
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019750 (MIPS 74Kc)
[    0.000000] MIPS: machine is Compex WPJ563
[    0.000000] SoC: Qualcomm Atheros QCA956X ver 1 rev 0
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] On node 0 totalpages: 32768
[    0.000000]   Normal zone: 288 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 32768 pages, LIFO batch:7
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32480
[    0.000000] Kernel command line: console=ttyS0,115200n8 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 121092K/131072K available (5884K kernel code, 605K rwdata, 748K rodata, 1200K init, 210K bss, 9980K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] CPU clock: 775.000 MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 4932285024 ns
[    0.000008] sched_clock: 32 bits at 387MHz, resolution 2ns, wraps every 5541893118ns
[    0.008281] Calibrating delay loop... 385.84 BogoMIPS (lpj=1929216)
[    0.074811] pid_max: default: 32768 minimum: 301
[    0.079804] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.087522] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.097718] dyndbg: Ignore empty _ddebug table in a CONFIG_DYNAMIC_DEBUG_CORE build
[    0.108117] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.118526] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.125794] pinctrl core: initialized pinctrl subsystem
[    0.135285] NET: Registered protocol family 16
[    0.140727] thermal_sys: Registered thermal governor 'step_wise'
[    0.190160] clocksource: Switched to clocksource MIPS
[    0.203001] NET: Registered protocol family 2
[    0.207804] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.216202] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.225116] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.233217] TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.240659] TCP: Hash tables configured (established 1024 bind 1024)
[    0.247484] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.254428] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.262070] NET: Registered protocol family 1
[    0.266686] PCI: CLS 0 bytes, default 32
[    0.276534] workingset: timestamp_bits=14 max_order=15 bucket_order=1
[    0.286918] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.293124] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.305148] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.315540] pinctrl-single 1804002c.pinmux: 544 pins, size 68
[    0.322663] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.331541] printk: console [ttyS0] disabled
[    0.336108] 18020000.uart: ttyS0 at MMIO 0x18020000 (irq = 9, base_baud = 1562500) is a 16550A
[    0.345249] printk: console [ttyS0] enabled
[    0.354314] printk: bootconsole [early0] disabled
[    0.379877] spi-nor spi0.0: mx25l12805d (16384 Kbytes)
[    0.385300] 3 fixed-partitions partitions found on MTD device spi0.0
[    0.391923] OF: Bad cell count for /ahb/spi@1f000000/flash@0/partitions
[    0.398774] OF: Bad cell count for /ahb/spi@1f000000/flash@0/partitions
[    0.406141] OF: Bad cell count for /ahb/spi@1f000000/flash@0/partitions
[    0.413054] OF: Bad cell count for /ahb/spi@1f000000/flash@0/partitions
[    0.420098] Creating 3 MTD partitions on "spi0.0":
[    0.425093] 0x000000000000-0x000000030000 : "u-boot"
[    0.434635] 0x000000030000-0x000000ff0000 : "firmware"
[    0.441123] 2 uimage-fw partitions found on MTD device firmware
[    0.447247] Creating 2 MTD partitions on "firmware":
[    0.452431] 0x000000000000-0x000000230000 : "kernel"
[    0.459828] 0x000000230000-0x000000fc0000 : "rootfs"
[    0.465821] mtd: setting mtd3 (rootfs) as root device
[    0.471946] 1 squashfs-split partitions found on MTD device rootfs
[    0.478345] 0x0000005e0000-0x000000fc0000 : "rootfs_data"
[    0.484868] 0x000000ff0000-0x000001000000 : "art"
[    1.214186] switch0: Atheros AR8337 rev. 2 switch registered on mdio.0
[    1.871690] ag71xx 19000000.eth: connected to PHY at mdio.0:00 [uid=004dd036, driver=Atheros AR8216/AR8236/AR8316]
[    1.882958] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode: sgmii
[    1.889779] i2c /dev entries driver
[    1.894274] leds-gpio leds: Led green:sig4 renamed to green:sig4_1 due to name collision
[    1.903746] NET: Registered protocol family 10
[    1.916447] Segment Routing with IPv6
[    1.920406] NET: Registered protocol family 17
[    1.925083] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    1.938498] 8021q: 802.1Q VLAN Support v1.8
[    1.943670] PCI host bridge /ahb/pcie-controller@18250000 ranges:
[    1.949994]  MEM 0x0000000012000000..0x0000000013ffffff
[    1.955443]   IO 0x0000000000000000..0x0000000000000000
[    1.961026] PCI host bridge to bus 0000:00
[    1.965274] pci_bus 0000:00: root bus resource [mem 0x12000000-0x13ffffff]
[    1.972405] pci_bus 0000:00: root bus resource [io  0x0000]
[    1.978159] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    1.985180] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    1.993417] pci 0000:00:00.0: [168c:003c] type 00 class 0x028000
[    1.999652] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x001fffff 64bit]
[    2.006725] pci 0000:00:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    2.013724] pci 0000:00:00.0: supports D1 D2
[    2.018978] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
[    2.025866] pci 0000:00:00.0: BAR 0: assigned [mem 0x12000000-0x121fffff 64bit]
[    2.033453] pci 0000:00:00.0: BAR 6: assigned [mem 0x12200000-0x1220ffff pref]
[    2.053347] VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
[    2.067249] Freeing unused kernel memory: 1200K
[    2.071966] This architecture does not have kernel memory protection.
[    2.078627] Run /sbin/init as init process
[    2.082864]   with arguments:
[    2.082868]     /sbin/init
[    2.082872]   with environment:
[    2.082875]     HOME=/
[    2.082879]     TERM=linux
[    2.788912] init: Console is alive
[    2.792932] init: - watchdog -
[    4.118726] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    4.172767] usbcore: registered new interface driver usbfs
[    4.178501] usbcore: registered new interface driver hub
[    4.184132] usbcore: registered new device driver usb
[    4.196526] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.205866] fsl-ehci: Freescale EHCI Host controller driver
[    4.213256] ehci-platform: EHCI generic platform driver
[    4.219008] ehci-platform 1b000000.usb: EHCI Host Controller
[    4.224927] ehci-platform 1b000000.usb: new USB bus registered, assigned bus number 1
[    4.233162] ehci-platform 1b000000.usb: irq 13, io mem 0x1b000000
[    4.260194] ehci-platform 1b000000.usb: USB 2.0 started, EHCI 1.00
[    4.267392] hub 1-0:1.0: USB hub found
[    4.272068] hub 1-0:1.0: 1 port detected
[    4.292026] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    4.302183] init: - preinit -
[    5.915227] random: jshn: uninitialized urandom read (4 bytes read)
[    6.327045] random: jshn: uninitialized urandom read (4 bytes read)
[    6.489696] random: jshn: uninitialized urandom read (4 bytes read)
[    7.830961] Atheros AR8216/AR8236/AR8316 mdio.0:00: Port 3 is up
[    7.839012] eth0: link up (1000Mbps/Full duplex)
[    7.950107] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    7.962942] IPv6: ADDRCONF(NETDEV_CHANGE): eth0.1: link becomes ready
[    8.006838] random: procd: uninitialized urandom read (4 bytes read)
[   12.404792] jffs2: notice: (516) jffs2_build_xattr_subsystem: complete building xattr subsystem, 21 of xdatum (20 unchecked, 1 orphan) and 28 of xref (1 dead, 0 orphan) found.
[   12.424835] mount_root: switching to jffs2 overlay
[   12.437796] overlayfs: upper fs does not support tmpfile.
[   12.453586] urandom-seed: Seeding with /etc/urandom.seed
[   12.598750] eth0: link down
[   12.623204] procd: - early -
[   12.626518] procd: - watchdog -
[   13.377938] procd: - watchdog -
[   13.382811] procd: - ubus -
[   13.488232] random: ubusd: uninitialized urandom read (4 bytes read)
[   13.497426] random: ubusd: uninitialized urandom read (4 bytes read)
[   13.504582] random: ubusd: uninitialized urandom read (4 bytes read)
[   13.514773] procd: - init -
[   14.799634] random: jshn: uninitialized urandom read (4 bytes read)
[   14.838752] random: ubusd: uninitialized urandom read (4 bytes read)
[   14.870498] random: ubus: uninitialized urandom read (4 bytes read)
[   15.241995] kmodloader: loading kernel modules from /etc/modules.d/*
[   15.251003] urngd: v1.0.2 started.
[   15.626013] random: crng init done
[   15.629544] random: 24 urandom warning(s) missed due to ratelimiting
[   15.713435] SCSI subsystem initialized
[   15.765596] ehci-pci: EHCI PCI platform driver
[   15.790111] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[   15.798142] ohci-platform: OHCI generic platform driver
[   15.818436] uhci_hcd: USB Universal Host Controller Interface driver
[   15.827391] ohci-pci: OHCI PCI platform driver
[   15.842607] Loading modules backported from Linux version v5.15.92-0-ge515b9902f5f
[   15.850489] Backport generated by backports.git v5.15.92-1-0-gdfe0f60c
[   15.902336] usbcore: registered new interface driver usb-storage
[   16.177969] PPP generic driver version 2.4.2
[   16.185625] NET: Registered protocol family 24
[   16.202603] usbcore: registered new interface driver uas
[   16.260074] ath: EEPROM regdomain: 0x0
[   16.260086] ath: EEPROM indicates default country code should be used
[   16.260090] ath: doing EEPROM country->regdmn map search
[   16.260105] ath: country maps to regdmn code: 0x3a
[   16.260112] ath: Country alpha2 being used: US
[   16.260116] ath: Regpair used: 0x3a
[   16.271646] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   16.273549] ieee80211 phy0: Atheros AR9561 Rev:0 mem=0xb8100000, irq=2
[   16.293600] kmodloader: done loading kernel modules from /etc/modules.d/*
[   35.859400] eth0: link up (1000Mbps/Full duplex)
[   35.873411] br-lan: port 1(eth0.1) entered blocking state
[   35.879002] br-lan: port 1(eth0.1) entered disabled state
[   35.884917] device eth0.1 entered promiscuous mode
[   35.889877] device eth0 entered promiscuous mode
[   35.900259] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   35.938161] br-lan: port 1(eth0.1) entered blocking state
[   35.943793] br-lan: port 1(eth0.1) entered forwarding state

> lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M

> cat /sys/kernel/debug/usb/devices
T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480  MxCh= 1
B:  Alloc=  0/800 us ( 0%), #Int=  0, #Iso=  0
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev= 5.10
S:  Manufacturer=Linux 5.10.176 ehci_hcd
S:  Product=EHCI Host Controller
S:  SerialNumber=1b000000.usb
C:* #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=  0mA
I:* If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub
E:  Ad=81(I) Atr=03(Int.) MxPS=   4 Ivl=256ms

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Do you have voltage tester to measure persistent 5V between USB sidemost pins i.e if it is powered. Or something like usb mouse or eqally cheap that lights up when powered?
No fault on your side. Your router supports USB 2.0 only, you have no effect from USB1.1 or USB 3.0 or UAS drivers. They are safe to remove.

**Comment by xback** [comment]
@alex-pnzv 

Can you try this patch?

```
From c4d592eac979c1bf441a99c086c98b6a2ba2e84b Mon Sep 17 00:00:00 2001
From: Koen Vandeputte <koen.vandeputte@citymesh.com>
Date: Wed, 11 Oct 2023 15:53:24 +0200
Subject: [PATCH] ath79: wpj563: enable 2nd usb controller

testpatch

Signed-off-by: Koen Vandeputte <koen.vandeputte@citymesh.com>
---
 target/linux/ath79/dts/qca9563_compex_wpj563.dts | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git a/target/linux/ath79/dts/qca9563_compex_wpj563.dts b/target/linux/ath79/dts/qca9563_compex_wpj563.dts
index ceac53f415..407e912ad2 100644
--- a/target/linux/ath79/dts/qca9563_compex_wpj563.dts
+++ b/target/linux/ath79/dts/qca9563_compex_wpj563.dts
@@ -130,6 +130,14 @@
 	status = "okay";
 };
 
+&usb_phy1 {
+	status = "okay";
+};
+
+&usb1 {
+	status = "okay";
+};
+
 &wmac {
 	status = "okay";
 
-- 
2.34.1

```

**Comment by alex-pnzv** [comment]
@brada4 I have verified that there is indeed 5 volts present on the USB pins.
@xback I created an image with your patch and see that the USB port is now working.

> lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=, Driver=usb-storage, 480M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M

Can you add this patch to the openwrt repository? It would be nice to have this fix in future releases.

Thanks for help, guys!

**Comment by xback** [comment]
@alex-pnzv 
Great,

Thanks for testing.
I'll push patches to openwrt tomorrow, including stable branches.
This fix will pop-up on later service releases then.

Enjoy the board :)

**Comment by xback** [comment]
@alex-pnzv 

Patches pushed to:
- master
- 23.05
- 22.03
- 21.02
