### ISSUE TITLE
USB Stick MT7601 not working after installing drivers (Solved)

### ISSUE THREAD

**Issue by Arku3S** [openwrt/openwrt#13670]
### Describe the bug

After installing the drivers, the USB stick does not work.

### OpenWrt version

LuCI openwrt-22.03 branch (git-23.119.80898-65ef406) / OpenWrt 22.03-SNAPSHOT r20220-92a0dd2447 The official version plus several add-ons and packages downloaded from https://eko.one.pl/

### OpenWrt target/subtarget

MT7601u

### Device

TP-LINK TL-WR1043ND V4

### Image kind

Official downloaded image

### Steps to reproduce

Simply connect the 7601 USB Stick to your router and install the drivers.

### Actual behaviour

It doesn't work and nothing happens.

### Expected behaviour

I expected it to work after installing the drivers.

### Additional info

Here is the solution:
After installing kmod-mt7601u and mt7601u-firmware
The file named mt7601u.bin is in the wrong location.
The wrong location is: "/lib/firmware/Mediatek"
The correct location is "/lib/firmware"
Moving the file to the correct location and restarting the router solves the problem.

Edit.
I found where the problem is:
[Link](https://github.com/openwrt/openwrt/blob/4e5d45f1e6cbc0cfd6018d6dddaa9997067cad09/package/firmware/linux-firmware/mediatek.mk#L3C2-L3C2)

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
You must report your problem to the fork you downloaded from your link. 
https://dl.eko.one.pl/openwrt-22.03/targets/ath79/generic/

**Comment by brada4** [comment]
Firmware was  moved with v19
https://github.com/openwrt/mt76/pull/342

mt76x0u works for me uninterrupted since v18 btw.

**Comment by Arku3S** [comment]
It seems that the firmware path was changed in the latest version 23.05 and I am using 22, so it is not an error.

**Comment by brada4** [comment]
Wrong bug tracker for your problem.
