### ISSUE TITLE
bpf-headers

### ISSUE THREAD

**Issue by oskarirauta** [openwrt/openwrt#13671]
### Describe the bug

With testing-kernel (6.1) selected, bpf header attempts to download 5.1 branch kernel from 6.1 url.
I think that if you use testing kernel, bpf headers from 6.1 should be used, both work; fixing download url for 5.1 kernel, or to change it to download 6.1 kernel.

With 6.1 kernel patches work (while writing this) just fine, though there is some minor offset reported, but if bpf-headers source should be chosen depending on selected kernel version, I think there should directories way they are in targets: patches-5.1 and patches 6.1.

It seems that there is this issue every now and then, because I had this one earlier, resolved it (fixed url that time), and now I had it again. But probably because kernel source file's sum matched, dl url didn't matter until I decided to save some space and remove _some old downloads_..

Maybe someone should take a look at it, severity of issue is not very bad; overcoming it is quite easy to fix.

### OpenWrt version

current git

### OpenWrt target/subtarget

x86/64

### Device

Interceptor 10210U

### Image kind

Self-built image

### Steps to reproduce

build with nearly all?

### Actual behaviour

file for download missing due to wrong url.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by anomeome** [comment]
Seems to happen every time there is a 5.15.x push

**Comment by schm0** [comment]
However, the use of the 6.1 header breaks qosify.
