### ISSUE TITLE
**channels** option from /etc/config/wireless does not work

### ISSUE THREAD

**Issue by xosevp** [openwrt/openwrt#13718]
### Describe the bug

```
root@ap2:/# cat /etc/config/wireless

config wifi-device 'radio0'
        option type 'mac80211'
        option path 'pci0000:00/0000:00:00.0'
        option channel 'auto'
        option channels '36 40 44 48 52 56 60 64 100 104 108 112 116 120 124 128 132 136 140'
        option htmode 'VHT80'
        option country 'ES'
        option band '5g'
        option cell_density '0'

config wifi-iface 'default_radio0'
        option device 'radio0'
        option network 'lan'
        option mode 'ap'
        option ssid 'ap25'
        option key 'passwd'
        option encryption 'psk2+ccmp'
        option ieee80211w '1'

config wifi-device 'radio1'
        option type 'mac80211'
        option path 'platform/ahb/18100000.wmac'
        option channel 'auto'
        option htmode 'HT40'
        option country 'ES'
        option band '2g'

config wifi-iface 'default_radio1'
        option device 'radio1'
        option network 'lan'
        option mode 'ap'
        option ssid 'ap2'
        option key 'passwd'
        option encryption 'psk2+ccmp'
        option ieee80211w '1'
```

And a channel (144 ) **_outside_** of  that list is auto-selected.

Thanks.

### OpenWrt version

r23497-6637af95aa

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link Archer C7 v5

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
It is included with selected channel 140

**Comment by brada4** [comment]
You can use freqlist https://w1.fi/cgit/hostap/tree/hostapd/hostapd.conf#n214 passed as hostapd option, because channel list will include 80mhz starting at ch 140 that include weak ch 144.

**Comment by jow-** [comment]
Configuration issue.

**Comment by raenye** [comment]
@jow- 
Note that `channels` is a valid config option, as per [docs](https://openwrt.org/docs/guide-user/network/wifi/basic).

**Comment by brada4** [comment]
Yes, OP got surprised that 140 80mhz included upper low power channel, router just fulfilled their explicit wish.

**Comment by castillofrancodamian** [comment]
@brada4 @raenye @jow- The same thing happens to me but on another channel. Channel 128 is always selected since it is not included in channels.

```
root@archer_c60:~# cat /etc/config/wireless 

config wifi-device 'radio0'
        option type 'mac80211'
        option path 'pci0000:00/0000:00:00.0'
        option band '5g'
        option cell_density '0'
        option channel 'auto'
        option channels '100 104 108 112 116 120 124'
        option htmode 'VHT80'
        option country 'AR'

config wifi-device 'radio1'
        option type 'mac80211'
        option path 'platform/ahb/18100000.wmac'
        option band '2g'
        option htmode 'HT20'
        option cell_density '0'
        option channel '1'
        option country 'AR'

config wifi-iface '5g_invitados'
        option device 'radio0'
        option mode 'ap'
        option ssid 'Invitados'
        option encryption 'psk2+ccmp'
        option ifname '5g_invitados'
        option key 'pass'
        option network 'wan'

config wifi-iface '2g_invitados'
        option device 'radio1'
        option mode 'ap'
        option ssid 'Invitados'
        option encryption 'psk2+ccmp'
        option ifname '2g_invitados'
        option key 'pass'
        option network 'wan'

config wifi-iface '2g_f'
        option device 'radio1'
        option mode 'ap'
        option ssid 'F'
        option encryption 'psk2+ccmp'
        option ifname '2g_f'
        option key 'pass'
        option network 'lan'
```

```
root@archer_c60:~# iw 5g_invitados info
Interface 5g_invitados
        ifindex 11
        wdev 0x1
        addr 50:c7:bf:75:81:af
        ssid Invitados
        type AP
        wiphy 0
        channel 128 (5640 MHz), width: 80 MHz, center1: 5610 MHz
        txpower 24.00 dBm
        multicast TXQ:
                qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                0       0       0       0       0       0       0       0               0

```

```
root@archer_c60:~# . /etc/openwrt_release && echo $DISTRIB_REVISION
r24187-bb8fd41f9a
root@archer_c60:~# . /etc/openwrt_release && echo $DISTRIB_TARGET
ath79/generic
root@archer_c60:~# cat /tmp/sysinfo/model
TP-Link Archer C60 v1
```

**Comment by brada4** [comment]
@castillofrancodamian @xosevp  same non-issue as repoted initially. Is there something easily skipped over/ misunderstood in documentation when reading/auto-translating in/to Spanish?

**Comment by castillofrancodamian** [comment]
@brada4 When you want to translate with the Google Chrome translator, all the text disappears.

**Comment by brada4** [comment]
I was thinking of documentation here:
https://openwrt.org/docs/guide-user/network/wifi/basic
The idea is if you mention ch 48 in channels - automatic selection will select 20-160MHz channel that includes 48.
As opposed to radio restriction you both kind of implied.
I dont read either from docu link though.

**Comment by castillofrancodamian** [comment]
@brada4 I think I understood but you are not explaining it in the best way.

**Comment by brada4** [comment]
OP problem is that last chunk of 80MHz channel is very low power which implies whole 80MHz channel low power. Using frequency restriction IPO numbers would permit to use 80+40+20 strong smaller bands right before weak one.
All documentation also in hostapd is blurry at best. Likely nothing to do with language, sorry.

**Comment by castillofrancodamian** [comment]
@brada4 I don't see that OP mentioned a power issue. I mentioned my case for having the same result in which a channel is selected that is not manually written in the `channels` option.

**Comment by brada4** [comment]
It is same in all EU...

**Comment by castillofrancodamian** [comment]
@brada4 I am from Argentina (AR). In my case, channel 128 is selected. Is it low power?

**Comment by brada4** [comment]
Compare `iw reg get` global section to the display of LuCI.
https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/tree/db.txt?id=HEAD#n92
You can set min_tx_power to 18 which is soft restriction -i.e prefer DFS channels. In unlucky case your routers wifi adapter does not support radar detection it will be able select IoT teapot class 17 dBm channels (still better than 13dBm in EU)
