### ISSUE TITLE
ASU Fails because of kmod-crypto-gf128

### ISSUE THREAD

**Issue by milouk** [openwrt/openwrt#13730]
### Describe the bug

Im trying to perform a ASU for Xiaomi AX3600 and I get the following error:

`Error: Impossible package selection: kmod-crypto-gf128 version not as requested: 6.1.56-1 vs. 6.1.57-1`

<img width="1552" alt="Screenshot 2023-10-18 at 22 52 22" src="https://github.com/openwrt/openwrt/assets/22796276/a99b3fb0-8e49-4346-8969-9335393a2af4">

However the package is available for 6.1.57-1 https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/kmods/6.1.57-1-0567810dfd9a1152272622ddb29d7220/

### OpenWrt version

SNAPSHOT r24154-6f31941d38

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Xiaomi AX3600

### Image kind

Official downloaded image

### Steps to reproduce

Try to update` kmod-crypto-gf128` to 6.1.57-1

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Any reason to hide the command you used?

**Comment by milouk** [comment]
> Any reason to hide the command you used?

Not really, Its just a huge log and couldn't fit in a single screenshot. I run `auc` followed by a `y` regarding the package upgrade

**Comment by brada4** [comment]
Sometimes snapshot downloads are not completely in sync. Usually that goes away next day. Also luci attended sysupgrade permits editing out (this time transiently) broken packages.
