### ISSUE TITLE
How to switch  Mbed TLS back to wolfSSL or choose OpenSSL，x86-64？

### ISSUE THREAD

**Issue by ilxp** [openwrt/openwrt#13773]
### Describe the bug

the 23.05.0 release：
Switch from wolfssl to mbedtls as default
OpenWrt has transitioned its default cryptographic library from wolfSSL to Mbed TLS. This shift brings several changes and implications:
Size Efficiency: Mbed TLS is considerably smaller, making it an optimal choice for systems where storage space is paramount.
LTS and ABI Stability: Mbed TLS consistently provides updates via its Long Term Support (LTS) branch, ensuring both security and a stable application binary interface (ABI). In contrast, wolfSSL does not offer an LTS release, and its stable ABI is limited to a specific set of functions.
TLS 1.3 Support: Users should be aware that Mbed TLS 2.28 no longer supports TLS 1.3.
While Mbed TLS is now the default, users who have specific needs or preferences can still manually switch back to wolfSSL or choose OpenSSL.。

but，i  want to use  wolfSSL or choose OpenSSL. what firles need to switch back。 thanks！

### OpenWrt version

23.05.0

### OpenWrt target/subtarget

/etc/openwrt_release

### Device

x86

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by raenye** [comment]
This sounds like a forum question, not an issue.

**Comment by jow-** [comment]
Please use forum, mailing lists or IRC for support questions.

**Comment by bam80** [comment]
I have the same question, if somebody asked on the forum (or elsewhere) already, please share the link.
Thanks.
