### ISSUE TITLE
iptables 1.8.8 string extension critical bug

### ISSUE THREAD

**Issue by levshutov** [openwrt/openwrt#13812]
### Describe the bug

iptables 1.8.8 release introduced bug in string extension.

It was added here
https://git.netfilter.org/iptables/commit/?id=68ed965b35cdc7b55d4ebc0ba37c1ac078ccbafb

It was fixed here
https://git.netfilter.org/iptables/commit/?id=da5b32fb4656ab69fe1156eb7e36c7c961839e8a

Fix is included in 1.8.9 release.

### OpenWrt version

r23497-6637af95aa

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Linksys E8450 (UBI)

### Image kind

Official downloaded image

### Steps to reproduce

Adding string rule
```
iptables -A INPUT -m string --string "teststring" --algo bm -j DROP
```

Checheking what we have
```
iptables -S | grep teststring
```

`-A INPUT -m string --string "teststring" --algo bm --to 65535 -j DROP`

Trying to delete it
```
iptables -D INPUT -m string --string "teststring" --algo bm --to 65535 -j DROP
```

### Actual behaviour

`iptables: Bad rule (does a matching rule exist in that chain?).`

### Expected behaviour

Rule must be deleted

### Additional info

The issue was previously reported here https://github.com/openwrt/packages/issues/20576

1.8.8 can be patched to fix the bug
```
diff -ru a/extensions/libxt_string.c b/extensions/libxt_string.c
--- a/extensions/libxt_string.c	2023-02-27 23:12:18.926400273 +0400
+++ b/extensions/libxt_string.c	2023-02-27 23:12:48.774400261 +0400
@@ -81,7 +81,7 @@
 {	
 	/* xt_string does not need \0 at the end of the pattern */
 	if (strlen(s) <= XT_STRING_MAX_PATTERN_SIZE) {
-		memcpy(info->pattern, s, XT_STRING_MAX_PATTERN_SIZE);
+		strncpy(info->pattern, s, XT_STRING_MAX_PATTERN_SIZE);
 		info->patlen = strnlen(s, XT_STRING_MAX_PATTERN_SIZE);
 		return;
 	}
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
If you need to get rid of rule:
```
iptables -L --line-numbers
iptables -D INPUT 123
```
