### ISSUE TITLE
bpf-headers package fails to build with kernel 6.1

### ISSUE THREAD

**Issue by schm0** [openwrt/openwrt#13814]
### Describe the bug

When using kernel 6.1 the bpf-header package fails to build when the recent 5.15 kernel is not present in the dl directory.

### OpenWrt version

r24214+14-e4ebc7b566

### OpenWrt target/subtarget

x86/64

### Device

N/A

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by schuettecarsten** [comment]
https://github.com/openwrt/openwrt/issues/13671
