### ISSUE TITLE
X86 N3160 OpenWRT 23.05.0 Reboot Issue, Not Present in 22.03.5

### ISSUE THREAD

**Issue by ifrvn** [openwrt/openwrt#13867]
### Describe the bug

I'm facing a reboot issue with my N3160 device after installing OpenWRT using the openwrt-23.05.0-x86-64-generic-ext4-combined-efi.img via physdiskwrite. The installation was smooth, but when I issue a "reboot" command, the system gets stuck in a continuous reboot loop and doesn't boot. I can only access the system by performing a cold start after disconnecting the power.

What's worth noting is that this issue is specific to OpenWRT version 23.05.0; it does not occur with version 22.03.5.

I've recorded a video of the problem since there are no error messages displayed. Has anyone encountered a similar issue with OpenWRT 23.05.0 x86-64, or can anyone provide guidance on resolving it?

record file:
https://1drv.ms/v/s!Aova8kpZ93aFgb5GEEa7hqiV4C_Arw?e=BKnXtJ

### OpenWrt version

r23497-6637af95aa

### OpenWrt target/subtarget

x86/64

### Device

SY-Thin Mini N3160

### Image kind

Official downloaded image

### Steps to reproduce

1. Use a PE to install OpenWRT via `physdiskwrite -u openwrt-23.05.0-x86-64-generic-ext4-combined-efi.img`
2. Restart into OpenWRT's terminal
3. Use `reboot` command to restart OpenWRT

### Actual behaviour

it just stuck in a continuous reboot loop.
GRUB interface - choose OpenWRT by default - Booting `OpenWRT' - GRUB interface ...

![image](https://github.com/openwrt/openwrt/assets/21982381/f1dad89c-a226-4fe5-8fa4-6e25be5fe621)

![image](https://github.com/openwrt/openwrt/assets/21982381/dec73f4e-3258-4a93-a20f-6c28d8162f91)

### Additional info

22.03.5 works fine, official image

`openwrt-22.03.5-x86-64-generic-ext4-combined-efi.img`

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Please disable windows fast boot, you can get EFI holding like DEL/F1/F10/F11 along poweron, or use debian install USB to enter EFI setup.
Besides skipping boot popup it also skips resetting all recognized devices at boot.

**Comment by brada4** [comment]
Also any device may be a culprit since you get kernel messages only after i915 modeset settles with your monitor. You can try booting wiht 'nomodeset' to have clearer picture.

**Comment by ifrvn** [comment]
@brada4 Thank you for your reply! Fast Boot is desabled already. Is there any setting I should change?

With `nomodeset` booting, it seems just work without any problem.

![image](https://github.com/openwrt/openwrt/assets/21982381/54077f26-6b8a-4c6e-87a9-eb1ae0dddf45)

**Comment by brada4** [comment]
Ok, looks like video card is the culprit.

Try to shuffle around options to reinit video differently/better, also set boot delay for screen to settle at logo, disabling logo may show which efi drivers init devices and assume others get legacy bios.

CSM enables pxe netboot using BIOS,or old video cards for main display, iscsi disk as bios disk etc exotics even if no EFI module is provided by card.  You need to disable secureboot alongside it, openwrt grub is not signed.

Win10 ? Try other UEFI modes like redhat or 7 if present, 
or changing (minimizing) graphicd stolen RAM

One at the time, once it works revert previously changed options to defaults.

**Comment by ifrvn** [comment]
@brada4 
OS Select provides `UEFI WIN8/WIN10` `Default` and `Yocto Linux`, all comes to the same result. Toggling other settings didn't help neither.

CSM Support couldn't be disabled even video has been set to UEFI Only. This is weird.

Also tried changing Aperture Size etc to minimize value. Not working.

![image](https://github.com/openwrt/openwrt/assets/21982381/c92d842b-60ee-4922-8852-14d53cab79a2)

![image](https://github.com/openwrt/openwrt/assets/21982381/22473944-9dab-42fd-b56b-38f948ea960f)

![image](https://github.com/openwrt/openwrt/assets/21982381/a3c4e509-9152-49d9-8df2-8b9f231945af)

**Comment by brada4** [comment]
Reset all BIOS to defaults, no luck in reconfigurations.

In boot command line (tap "E" when in grib menu) add i915.reset=2 on supposedly failing reboot-boot activity.

> parm:           reset:Attempt GPU resets (0=disabled, 1=full gpu reset, 2=engine reset [default]) (uint)

Make it permanent, whichever works:
Add i915.modeset=0 to /boot/...../grub.cfg line starting with linux (probably both lines, you would want safe mode to boot ok too)

**Comment by ifrvn** [comment]
@brada4 Adding `i915.reset=2` after reboot couldn't boot still.  Adding `i915.modeset=0` did work.

![image](https://github.com/openwrt/openwrt/assets/21982381/bc48a8e9-1f2b-4bc6-a42f-49630c6fc814)

**Comment by brada4** [comment]
Then add global `nomodeset` there first and after that good reboot in grub.cfg, as it was working first time.

**Comment by ifrvn** [comment]
Just like this?

![image](https://github.com/openwrt/openwrt/assets/21982381/db5e777f-a243-4120-a093-04eb7a6a1cc1)

**Comment by brada4** [comment]
Yes, you do not need i915 parameter anymore.

In absence of i915 modeset next would be efi console modeset setting back BIOS resolution, and from CSM it may init 640x480 on VGA. You need desktop linux at hand to see parameters available cs their metainfo are strip-ed from openwrt modules. Combination of shutdown and BIOS/EFI activity driver cannot init card anymore. In principle problem should prevail on similar version of other linux too. 
1/ try snapshot
2/ debian or fedora latest version - like boot after openwrt that is supposed to crash at that boot.

**Comment by ifrvn** [comment]
OK, thank you so much for your patient and detailed explanation. I really appreciate your help!

**Comment by 1425673985** [comment]
Testing comment retrieval
