### ISSUE TITLE
ssh connection problem

### ISSUE THREAD

**Issue by tuftjd** [openwrt/openwrt#13862]
### Describe the bug

I use openvpn in openwrt to connect to servers elsewhere. I can ping the gateway and all servers in the LAN, but I cannot connect to the server via ssh. Then I captured the packet and analyzed it. Only part of the ssh protocol packets were received in openwrt. What is the reason?

### OpenWrt version

R23.7.7 GDQ V2[2023] Compiled by eSir

### OpenWrt target/subtarget

x86/64

### Device

Intel Default string/NUC19D - Intel(R) Celeron(R) CPU J1900 @ 1.99GHz : 4C4T

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
Please use the forum for general support questions. Maybe you do have an MTU issue.

**Comment by tuftjd** [comment]
I checked, it's not an MTU issue,and I'm not even sure what the issue is.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openwrt/openwrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月3日(星期五) 晚上7:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openwrt/openwrt] ssh connection problem (Issue #13862)





 
Please use the forum for general support questions. Maybe you do have an MTU issue.
