### ISSUE TITLE
x86/x64: image increased by 35MB after adding support for Mellanox Spectrum SN2000 Switches

### ISSUE THREAD

**Issue by DazzyWalkman** [openwrt/openwrt#13886]
### Describe the bug

Commit 3004c20614fdb29732f750417a578274a8ed988e pulls in device-specific package mlxsw_spectrum-firmware, size of which is about 30 megabytes, into x64 image profile.
Afterwards, all resulting x64 images built by image builder or buildroot include mlxsw_spectrum-firmware, thus size grow by 30ish megabytes.

### OpenWrt version

r24315-ae500e62e2, or date back to any builds after commit 3004c20614fdb29732f750417a578274a8ed988e

### OpenWrt target/subtarget

x86_64

### Device

Generic x86/64

### Image kind

Self-built image

### Steps to reproduce

Download image builder from https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-imagebuilder-x86-64.Linux-x86_64.tar.xz
Extract and run
`make image`

Similar result can be obtained by using snapshot buildroot, building default image of x86_64.

### Actual behaviour

35 megabytes or so space taken up by the mlxsw spectrum firmware blobs and related device-specfic files.

### Expected behaviour

I am unsure the popularity of mlxsw spectrum device justifying its inclusion into the generic image. 
Even if there is less restriction on space, and (intentionally?) only one generic profile is kept for x86_64, it should better be in a separate device image profile, to save other users' time to explicitly unselect all related packages from image builder or buildroot.

More so for similar devices with large kmods or firmware blobs.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ynezz** [comment]
Fixed via 713dc12960dd6146706a364905904b58d4d586d4
