### ISSUE TITLE
Issues with user/group IDs 65536 and up (= default for package-added users)

### ISSUE THREAD

**Issue by tew42** [openwrt/openwrt#13927]
### Describe the bug

User/group IDs of 65536 and greater have significant issues in usage, but are implemented as default in package installation when new users are created (from Makefile `USERID=username:groupname` without specific IDs, translated into ipkg control file `Require-User: username:groupname`) as per [`user_add()`](https://github.com/openwrt/openwrt/blob/main/package/base-files/files/lib/functions.sh#L418) & [`group_add_next()`](https://github.com/openwrt/openwrt/blob/main/package/base-files/files/lib/functions.sh#L387), called by `default_postinst()`, in `functions.sh`.

### OpenWrt version

23.05.0

### OpenWrt target/subtarget

ath79
x86_64

### Device

Archer A7 v5
Proxmox LXC

### Image kind

Official downloaded image (ath79)
linuxcontainers.org images (x64 LXC)

### Steps to reproduce

Create user with UID/GID of 65536 or greater (installing a "suitable" package, e.g. tang, or manually editing /etc/passwd)

Attempt to set permissions on any file with `chown username filename`

### Actual behaviour

```
root@OpenWRT:~# cat /etc/passwd
username:x:65536:65536:groupname:/var/run/xxx:/bin/false
```

ath79:
```
root@OpenWRT:~# chown username filename
```
x64 LXC:

```
root@OpenWRT:~# chown username filename
chown: filename: Invalid argument
```
both:
```
root@OpenWRT:~# ls -l
-rw-r--r--    1 root     root             4 Nov 10 11:02 filename
```

### Expected behaviour

```
root@OpenWRT:~# cat /etc/passwd
username:x:65536:65536:groupname:/var/run/xxx:/bin/false
```
```
root@OpenWRT:~# chown username filename
```
```
root@OpenWRT:~# ls -l
-rw-r--r--    1 username     root             4 Nov 10 11:02 filename
```

### Additional info

also tested with ramips/mt7621 now (see below) where everything works fine...

Starting services works independently of userid number above/below the threshold - but then obviously those services can run into permission issues. Originally discovered with tang package (openwrt/packages#22634), but quite a few other packages also declare users/groups without explicit IDs

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by tew42** [comment]
Thanks - indeed it works (or doesn't) independent of packages, I just wanted to highlight that it becomes an actual issue due to the package installer defaults.

Anyhow:
```
BusyBox v1.36.1 (2023-10-09 21:45:35 UTC) multi-call binary.
```
and, unsurprisingly / in line with the original report (with "tang" being just one of the generic examples of out-of-bound uids already present)
```
root@OpenWrt-PVE:~# chown 99999 `mktemp -d`
chown: /tmp/tmp.PaHaFI: Invalid argument
root@OpenWrt-PVE:~# chown 65536 `mktemp -d`
chown: /tmp/tmp.NegDnN: Invalid argument
root@OpenWrt-PVE:~# id tang
uid=65536(tang) gid=65536(tang) groups=65536(tang),65536(tang)
```

**Comment by tew42** [comment]
update: I just spun up a snapshot LXC and a 22.03 LXC, same (faulty) behavior

**Comment by tew42** [comment]
Alright, retested with one more architecture now - which works fine?!

So, the chown mktemp only gives insight when there's an error message (LXC case). But in ath79 case, it's insufficient...


on x64 LXC:
```
root@OpenWrt-PVE:/var/run# chown 99999 `mktemp -d`
chown: /tmp/tmp.ckjMfP: Invalid argument
root@OpenWrt-PVE:/var/run# chown 9999 `mktemp -d`
root@OpenWrt-PVE:/var/run#
```

on ath79:
```
root@OpenWrt-ArcherA7:~# chown 99999 `mktemp -d`
root@OpenWrt-ArcherA7:~# mkdir test
root@OpenWrt-ArcherA7:~# chown testuser test
root@OpenWrt-ArcherA7:~# ls -l
drwxr-xr-x    2 root     root             0 Nov 10 16:57 test
root@OpenWrt-ArcherA7:~# id testuser
uid=65536(testuser) gid=65536(testuser) groups=65536(testuser),65536(testuser)
```

ramips/mt7621
```
root@OpenWrt-DAPx1860:~# chown 99999 `mktemp -d`
root@OpenWrt-DAPx1860:~# mkdir test
root@OpenWrt-DAPx1860:~# chown testuser test
root@OpenWrt-DAPx1860:~# ls -l
drwxr-xr-x    2 testuser root           160 Nov 10 16:57 test
root@OpenWrt-DAPx1860:~# id testuser
uid=65536(testuser) gid=65536(testuser) groups=65536(testuser),65536(testuser)
```

**Comment by brada4** [comment]
It is lxc configuration issue. Just map few uid-s above 64k-1 to whatever and your containers will run well.

**Comment by tew42** [comment]
On LXC, sure, and that's not a typical use case anyway. But ath79 is the real issue here as I see it

**Comment by brada4** [comment]
hmm, looks like jffs overlay on squashfs then, no problem in tmpfs. but ramips is more or less same cpu as ath79.

**Comment by brada4** [comment]
Userland chmod does OK, just that filesystem combination does not work out.

is there a difference in `mount` in places containing overlays (modern ramips with lots of flash and ram):
```
mount | grep -e /rom -e /overlay
/dev/root on /rom type squashfs (ro,relatime,errors=continue)
/dev/ubi0_1 on /overlay type ubifs (rw,noatime,assert=read-only,ubi=0,vol=1)
overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)
```

**Comment by tew42** [comment]
not familiar enough with this to understand it, but there does seem to be a distinction between platforms on that front:

ath79
```
root@OpenWrt-ArcherA7:~# mount | grep -e /rom -e /overlay
/dev/root on /rom type squashfs (ro,relatime,errors=continue)
/dev/mtdblock5 on /overlay type jffs2 (rw,noatime)
overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)
```

ramips
```
root@OpenWrt-DAPx1860:~# mount | grep -e /rom -e /overlay
/dev/root on /rom type squashfs (ro,relatime,errors=continue)
/dev/ubi0_1 on /overlay type ubifs (rw,noatime,assert=read-only,ubi=0,vol=1)
overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)

```

**Comment by brada4** [comment]
jffs2 supports only 16bit uid/gid :-( probably reason to bring generated upper users half way down....

**Comment by tew42** [comment]
So potentially like this? #13937

**Comment by brada4** [comment]
I cant grep other 64k on archer c7 ;-) looks like it.
