### ISSUE TITLE
OpenWRT drops packets-OpenWRT malware

### ISSUE THREAD

**Issue by microlaser** [openwrt/openwrt#13928]
### Describe the bug

As you can see below I have a secondary WAN IP that is an intruder on the physical wire in my opinion.  I tried blocking them with iptables but it still shows arp traffic when I ruin tcpdump.  tcpdump drops packets which is unexpected behavior.   I have run "arp -a" so you can see this IP, it looks a lot like a man in the middle like a physical intruder on the wire.  

root@OpenWrt:~# tcpdump -vvi any | grep 76.124.74.1
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
	12:09:07.653473 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has c-76-124-74-1.hsd1.pa.comcast.net tell c-76-124-75-224.hsd1.pa.comcast.net, length 28
12:09:07.669151 ARP, Ethernet (len 6), IPv4 (len 4), Reply c-76-124-74-1.hsd1.pa.comcast.net is-at 00:1c:73:00:00:99 (oui Unknown), length 46
    dns9.quad9.net.53 > c-76-124-75-224.hsd1.pa.comcast.net.39420: [udp sum ok] 24480 q: PTR? 1.74.124.76.in-addr.arpa. 1/0/0 1.74.124.76.in-addr.arpa. PTR c-76-124-74-1.hsd1.pa.comcast.net. (89)
    localhost.53 > localhost.55674: [bad udp cksum 0xfe74 -> 0x672b!] 32536 q: PTR? 1.74.124.76.in-addr.arpa. 1/0/0 1.74.124.76.in-addr.arpa. PTR c-76-124-74-1.hsd1.pa.comcast.net. (89)
12:09:07.894497 IP6 (flowlabel 0x86827, hlim 64, next-header UDP (17) payload length: 97) localhost.53 > localhost.55674: [bad udp cksum 0x0074 -> 0x652c!] 32536 q: PTR? 1.74.124.76.in-addr.arpa. 1/0/0 1.74.124.76.in-addr.arpa. PTR c-76-124-74-1.hsd1.pa.comcast.net. (89)
^C22742 packets captured
24652 packets received by filter
1562 packets dropped by kernel

root@OpenWrt:~# 
root@OpenWrt:~# ifconfig
br-lan    Link encap:Ethernet  HWaddr E8:9F:80:AD:98:E3  
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:2576345 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6076374 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:344768943 (328.7 MiB)  TX bytes:13110543467 (12.2 GiB)

eth0      Link encap:Ethernet  HWaddr E8:9F:80:AD:98:E3  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:128213 errors:0 dropped:0 overruns:0 frame:0
          TX packets:101715 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:55318518 (52.7 MiB)  TX bytes:46582160 (44.4 MiB)

eth1      Link encap:Ethernet  HWaddr E8:9F:80:AD:98:E4  
          inet addr:76.124.75.224  Bcast:76.124.75.255  Mask:255.255.254.0
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:9756708 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2589498 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:471781641 (449.9 MiB)  TX bytes:381320962 (363.6 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:552 errors:0 dropped:0 overruns:0 frame:0
          TX packets:552 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:61272 (59.8 KiB)  TX bytes:61272 (59.8 KiB)

wlan1     Link encap:Ethernet  HWaddr E8:9F:80:AD:98:E5  
          inet6 addr: fe80::ea9f:80ff:fead:98e5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4042 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:1017132 (993.2 KiB)

wlan2     Link encap:Ethernet  HWaddr E8:9F:80:AD:98:E6  
          inet6 addr: fe80::ea9f:80ff:fead:98e6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2516354 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9626218 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:330088190 (314.7 MiB)  TX bytes:13498243957 (12.5 GiB)
root@OpenWrt:~# nslookup myip.opendns.com resolver1.opendns.com
Server:		resolver1.opendns.com
Address:	208.67.222.222#53

Name:      myip.opendns.com
Address 1: 76.124.75.224
*** Can't find myip.opendns.com: No answer

root@OpenWrt:~# arp -a 
IP address       HW type     Flags       HW address            Mask     Device
192.168.1.131    0x1         0x2         a8:b5:7c:e8:30:56     *        br-lan
192.168.1.22     0x1         0x2         64:00:6a:71:4c:ea     *        br-lan
76.124.74.1      0x1         0x2         00:1c:73:00:00:99     *        eth1
192.168.1.245    0x1         0x2         cc:08:fa:89:9b:a9     *        br-lan
192.168.1.9      0x1         0x2         50:23:a2:c3:9e:47     *        br-lan
192.168.1.102    0x1         0x2         f4:a8:0d:69:fb:13     *        br-lan
192.168.1.33     0x1         0x2         14:98:77:7a:97:6f     *        br-lan
192.168.1.103    0x1         0x2         b4:e4:54:05:a9:2d     *        br-lan
192.168.1.199    0x1         0x2         b8:31:b5:66:80:23     *        br-lan
192.168.1.152    0x1         0x2         40:a2:db:d0:aa:c5     *        br-lan
root@OpenWrt:~# 

### OpenWrt version

ipq40xx/generic

### OpenWrt target/subtarget

ipq40xx/generic

### Device

Linksys MR8300 (Dallas)

### Image kind

Official downloaded image

### Steps to reproduce

I believe the police in the United States use this malware.  I am not a criminal, I am a whistleblower.  Run tcpdump and look for activity from a second WAN IP that is not your own using grep.

### Actual behaviour

The kernel drops packets

### Expected behaviour

No packet loss coming from the kernel

### Additional info

I witnessed rwein@ssi-net.com spear phished when I worked at Ssi-net.com and I reported it to the FBI.  I believe that I am being hassled by cops who they have connections too.  

### Diffconfig

```text
root@OpenWrt:~# /scripts/diffconfig.sh
-ash: /scripts/diffconfig.sh: not found
root@OpenWrt:~#
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
Nothing actionable in this ticket.
