### ISSUE TITLE
lantiq: 23.05.0 bricks Easybox 803A

### ISSUE THREAD

**Issue by bodop** [openwrt/openwrt#13934]
### Describe the bug

sysupgrade from 22.03.3 leads to the following output on the serial console

```ROM VER: 1.0.3
CFG 01
Read EEPROMX
 X


U-Boot 2013.10-openwrt4 (May 28 2014 - 21:46:54) ARV752DPW22

Board: Arcadyan ARV752DPW22
SoC:   Lantiq Danube-S v1.5
CPU:   333.333 MHz
IO:    166.667 MHz
BUS:   83.333 MHz
BOOT:  NOR
DRAM:  64 MiB
Flash: 8 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   ltq-eth
Hit any key to stop autoboot:  0
## Booting kernel from Legacy Image at b0040000 ...
   Image Name:   MIPS OpenWrt Linux-5.15.134
   Created:      2023-10-09  21:45:35 UTC
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    2726016 Bytes = 2.6 MiB
   Load Address: 80002000
   Entry Point:  80002000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... LZMA: uncompress or overwrite error 7 - must RESET b
ROM VER: 1.0.3
.
.
.
```

### OpenWrt version

r20028-43d71ad93e

### OpenWrt target/subtarget

lantiq/xway

### Device

Arcor 803

### Image kind

Official downloaded image

### Steps to reproduce

sysupgrade -v openwrt-23.05.0-lantiq-xway-arcadyan_arv752dpw22-squashfs-sysupgrade.bin

### Actual behaviour

Device to not boot into 23.05.0

### Expected behaviour

Device should boot into 23.05.0

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Seems bootloader is defective due to multiple devices with same issues.
https://github.com/openwrt/openwrt/issues/13891

**Comment by bodop** [comment]
Current bootloader fixed the uncompression error. The [device page](https://openwrt.org/toh/astoria/arv752dpw22#u-boot) should be updated, it recommends to use a very old u-boot version.

Like in #13891 the boot process stops a few lines later

```   Uncompressing Kernel Image ... OK

Starting kernel ...

[    0.000000] Linux version 5.15.134 (builder@buildhost) (mips-openwrt-linux-musl-gcc (OpenWrt GCC 12.3.0 r23497-6637af95aa) 12.3.0, GNU ld (GNU Binutils) 2.40.0) #0 SMP Mon Oct 9 21:45:35 2023
[    0.000000] SoC: Danube rev 1.5
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019641 (MIPS 24KEc)
[    0.000000] MIPS: machine is Arcor 803
[    0.000000] Initrd not found or empty - disabling initrd
```

**Comment by brada4** [comment]
cpuid should follow after that line...
from device page regarding unrelated hang - disconnect power for more than a minute and try again...

**Comment by hauke** [comment]
Please try to modify the `loadaddr`in u-boot. It is probably set to `0xb0040000, try setting it to `0xb0060000`.

The boot loader loads the kernel to `loadaddr` and then the kernel loader uncompresses the kernel to `80002000`. If the kernel is too big it will overwite itself while uncompressing.

**Comment by bodop** [comment]
The first error message came from a flashed kernel: Uncompressing from b0040000 to 0x80020000. I am no bootloader expert, but for me this sound safe.

u-boot's default loadaddr is 81000000 I retried again with 23.05.1 and bootm:

```
ARV752DPW22 # tftpboot openwrt-23.05.1-lantiq-xway-arcadyan_arv752dpw22-initramfs-kernel.bin
Using ltq-eth device
TFTP from server 192.168.1.2; our IP address is 192.168.1.1
Filename 'openwrt-23.05.1-lantiq-xway-arcadyan_arv752dpw22-initramfs-kernel.bin'.
Load address: 0x81000000
Loading: #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #############################
done
Bytes transferred = 5196310 (4f4a16 hex)
ARV752DPW22 # bootm
## Booting kernel from Legacy Image at 81000000 ...
   Image Name:   MIPS OpenWrt Linux-5.15.137
   Created:      2023-11-12  15:19:39 UTC
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    5196246 Bytes = 5 MiB
   Load Address: 80002000
   Entry Point:  80002000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK

Starting kernel ...

[    0.000000] Linux version 5.15.137 (builder@buildhost) (mips-openwrt-linux-musl-gcc (OpenWrt GCC 12.3.0 r23619-101988c61a) 12.3.0, GNU ld (GNU Binutils) 2.40.0) #0 SMP Sun Nov 12 15:19:39 2023
[    0.000000] SoC: Danube rev 1.5
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019641 (MIPS 24KEc)
[    0.000000] MIPS: machine is Arcor 803
[    0.000000] Initrd not found or empty - disabling initrd
```

**Comment by bodop** [comment]
[This hint](https://github.com/openwrt/openwrt/issues/14283#issuecomment-1872572959) makes my device boot again with the current snapshot. (OK, the WLAN chip is not recognized, but this seems to be different topic).
