### ISSUE TITLE
WDS master not working anymore

### ISSUE THREAD

**Issue by grosjo** [openwrt/openwrt#13946]
### Describe the bug

Recent git make the WDS master not working

### OpenWrt version

OpenWrt 23.05-SNAPSHOT r23614-f6a9f0c57b

### OpenWrt target/subtarget

23.05 branch

### Device

Comfast WR650v2 
Tested also on other models, same issue

### Image kind

Self-built image (using wpad-mbetls)

### Steps to reproduce

Just upgrade firmware to latest git. The link Master-Client in WDS mode connects but does not transmit the IP packets

### Actual behaviour

 IP transfer not transferring in WDS mode

### Expected behavior

IP transfer in WDS mode

### Additional info

Git from 2 weeks was working fine

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by nbd168** [comment]
Fixed in 46385eb7f88f
