### ISSUE TITLE
[ipq807x] Redmi AX6/Xiaomi AX3600 wan interface dhcp not working

### ISSUE THREAD

**Issue by XiaoliChan** [openwrt/openwrt#13945]
### Describe the bug

DHCP not working anymore with the latest build

The kernel log can't see any exception
![image](https://github.com/openwrt/openwrt/assets/30458572/e0108aca-b89a-4983-9b6d-25b567d964d9)

In the `network` page, it can't get IP address from the upstream
![image](https://github.com/openwrt/openwrt/assets/30458572/85f4167d-bc49-4dd1-84c4-c08e2b40ace8)

I have try to set a static address for the wan interface, still not working.

Updated:
- confirm PR https://github.com/openwrt/openwrt/commit/947b44d9ae17b4d56578c10a5dd675e79e4c621b caused this issue

### OpenWrt version

Main branch

### OpenWrt target/subtarget

IPQ807x

### Device

Redmi AX6/xiaomi ax3600

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
Please add the exact snapshot version

**Comment by XiaoliChan** [comment]
> Please add the exact snapshot version

`SNAPSHOT r24364-79ee0d2cee`

**Comment by XiaoliChan** [comment]
I have three of this router, two routers have no issues with the wan interface(added into br-lan), and one router lost network connection after sysupgrade(even I reflash the firmware)

**Comment by brada4** [comment]
Is the uplink cable 100Mbps? Please show `ip link` and ethtool lan@eth0?
Is it migration or restoring config back? From which version?

**Comment by XiaoliChan** [comment]
> Is the uplink cable 100Mbps? 

Yes, only 100Mbps here

**Comment by XiaoliChan** [comment]
> Please show `ip link` and ethtool lan@eth0? 

- `ip link`
![image](https://github.com/openwrt/openwrt/assets/30458572/7bc8379b-9aaa-4f03-916c-3cc3575423c7)

- `ethtool`
![image](https://github.com/openwrt/openwrt/assets/30458572/5b1109c5-6b43-40ba-a992-8d8a242d2e9a)
![image](https://github.com/openwrt/openwrt/assets/30458572/c33b4ff0-91cb-42dc-afdd-e753a3a24939)

> Is it migration or restoring config back? From which version?

Even I did clean install from sysupgrade

**Comment by XiaoliChan** [comment]
I can confirm the network cable is working, because I plugin it into my notebook and get dhcp ipv4 address

**Comment by robimarko** [comment]
Any chance you can revert commit:
https://github.com/openwrt/openwrt/commit/947b44d9ae17b4d56578c10a5dd675e79e4c621b

To make sure its not the culprit

**Comment by XiaoliChan** [comment]
> To make sure its not the culprit

Sure, I'm going to recompile it

**Comment by robimarko** [comment]
Can I also ask that you post output of:
`cat /sys/kernel/debug/clk/clk_summary`

**Comment by XiaoliChan** [comment]
> Can I also ask that you post output of: `cat /sys/kernel/debug/clk/clk_summary`
[bug-firmware-clk.txt](https://github.com/openwrt/openwrt/files/13325203/bug-firmware-clk.txt)

**Comment by XiaoliChan** [comment]
@robimarko I can confirm that commit cause the issues

**Comment by hnyman** [comment]
Interesting, also ipq806x is suffering from the same symptom: no DHCP on wan.
I compiled r24365-b7cf706539 for ipq806x/R7800, but was left without wan connectivity (unanswered dhcp  broadcast).

The commit 947b44d9ae only affects ipq807x, so the reason for ipq806x might instead be 4fdd5530a7 by @Ansuel 

But interesting that similar symptoms are surfacing for both ipq806x and ipq807x.

**Comment by Ansuel** [comment]
Feeling we are jumping to conclusions here. Think we need to investigate this further with actually reverting the commits

**Comment by Ansuel** [comment]
@XiaoliChan can you do one test for me? Can you verify if each lan port have connection and you can reach the router?

**Comment by XiaoliChan** [comment]
> @XiaoliChan can you do one test for me? Can you verify if each lan port have connection and you can reach the router?

I only can do the test in tomorrow

**Comment by XiaoliChan** [comment]
> Can you verify if each lan port have connection and you can reach the router?

Oh, I can't reach the router, I remember I have a route has plugins each LAN port with devices

**Comment by brada4** [comment]
> network cable is working 

Indeed UP+LOWER_UP says that and mii status confirms 100mbps is negotiated. 

Do you have all ports in a br-lan without VLAN-s? like /etc/config/network , you can keep static public IPs private if you wish.

**Comment by XiaoliChan** [comment]
> Indeed UP+LOWER_UP says that and mii status confirms 100mbps is negotiated.
> 
> Do you have all ports in a br-lan without VLAN-s? like /etc/config/network , you can keep static public IPs private if you wish.

I think this is not the issue here, because when I revert the commit https://github.com/openwrt/openwrt/commit/947b44d9ae17b4d56578c10a5dd675e79e4c621b as @robimarko  said, it works now

**Comment by hnyman** [comment]
Regarding ipq806x/R7800:
> > also ipq806x is suffering from the same symptom: no DHCP on wan.
> > ...
> > so the reason for ipq806x might instead be https://github.com/openwrt/openwrt/commit/4fdd5530a7ffba356ea9768769ed1713beb7445a


> investigate this further with actually reverting the commits

I reverted 4fdd5530a and connectivity of my R7800 is back  with r24365-b7cf706539.

I wonder if it is about the actual source code changes or about the removal of ip-tiny rom device packages. 
(however, ip-tiny was added due to DSA, so it makes sense that it should not be needed for anything else)

**Comment by brada4** [comment]
If you loop br-lan dhcp server with wan dhcp client in a software bridge the result in semi-technical terms becomes "dhcp not working"

**Comment by Ansuel** [comment]
> Regarding ipq806x/R7800:
> > > also ipq806x is suffering from the same symptom: no DHCP on wan.
> > > ...
> > > so the reason for ipq806x might instead be https://github.com/openwrt/openwrt/commit/4fdd5530a7ffba356ea9768769ed1713beb7445a
> 
> 
> > investigate this further with actually reverting the commits
> 
> I reverted 4fdd5530a and connectivity of my R7800 is back  with r24365-b7cf706539.
> 
> I wonder if it is about the actual source code changes or about the removal of ip-tiny rom device packages. 
> (however, ip-tiny was added due to DSA, so it makes sense that it should not be needed for anything else)
> 

Please open a new issue so we don't mix the 2 thing

**Comment by XiaoliChan** [comment]
Looks like we need to revert that PR before find the bug.

**Comment by Ansuel** [comment]
Problem debugged... preparing patch to fix this.

**Comment by Ansuel** [comment]
@XiaoliChan please test https://github.com/openwrt/openwrt/pull/13950

**Comment by XiaoliChan** [comment]
Ah sure, let me recompile the firmware with your patch

**Comment by XiaoliChan** [comment]
> @XiaoliChan please test #13950

Ah sure, let me recompile the firmware with your patch

**Comment by XiaoliChan** [comment]
@Ansuel That patch fixed the weird issues in WAN port on my AX3600

I still need to test the AX6 with full connection, maybe tomorrow
