### ISSUE TITLE
100M LAN no connection to router (AX3600) 1GB works

### ISSUE THREAD

**Issue by stixif** [openwrt/openwrt#13957]
### Describe the bug

100M LAN no connection to router (AX3600) 1GB works
since a patch in "MAIN" in the last 6 days
I have problems with LAN participants that can only do 100Mbit
There are no problems with 1GB

running SNAPSHOT r0-a15eb1c
problem detected here SNAPSHOT r0-79ee0d2
https://github.com/stixif/ipq807x-ax3600-openwrt-builder

but it works on an Dynalink DL-WRX36
https://github.com/stixif/ipq807x-Dynalink-DL-WRX36

### OpenWrt version

r0-79ee0d2

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Xiaomi AX3600

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Try again in few days till fix lands in snapshots.
https://github.com/openwrt/openwrt/issues/13945

**Comment by stixif** [comment]
Ok... but my Problem is not only on WAN... Port2 have the same Issu...

**Comment by brada4** [comment]
Wait for snapshot, the fixed thing is more accurate active port enumeration.

**Comment by stixif** [comment]
now it works! Thanks
