### ISSUE TITLE
23.05 got runtime error

### ISSUE THREAD

**Issue by trombonist852** [openwrt/openwrt#13998]
### Describe the bug

An error message appears when accessing the router login interface.
<img width="1234" alt="微信图片_20231118142417" src="https://github.com/openwrt/openwrt/assets/13253090/14140a32-fba2-4e85-aeaa-223e0736090c">

### OpenWrt version

r0+27300-7fb31f2164

### OpenWrt release

23.05-SNAPSHOT

### OpenWrt target/subtarget

x86/64

### Device

WanYou WanYouChunXiao

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by trombonist852** [comment]
> Invalid Version reported. `r0+27300-7fb31f2164` Is this from a clean repository?
 from immortalwrt at openwrt-23.05


> Invalid Release reported. `23.05-SNAPSHOT` Is this from a clean repository?

yes

Invalid Device reported. WanYou WanYouChunXiao Is this a supported model?


yes it's x86 router

**Comment by brada4** [comment]
Your version tag is from some fork. You should report over there.
Something like luci-compat is missing, but you need to report there to fix their dependencies
