### ISSUE TITLE
Luci nftables page, displaying errors regarding 'iif'

### ISSUE THREAD

**Issue by a904055262** [openwrt/openwrt#14003]
### Describe the bug

raw rule:
iif "pppoe-wan" th dport 54321 @nh,128,32 0xc0a806e2 @nh,72,8 0x6 accept
and display:
Egress device id is pppoe-wanTransport header destination port is 54321 Network header bits 129-161 is 3232237282 Network header bits 73-81 is 6

Egress ??  Ingress？

### OpenWrt version

23.05.2

### OpenWrt release

23.05.2

### OpenWrt target/subtarget

x86_64

### Device

x86_64

### Image kind

Self-built image

### Additional info

![2023-11-19_004600](https://github.com/openwrt/openwrt/assets/3348789/fa46ad56-ff4c-4144-b8c3-44b15138aea7)

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
It is ingress indeed - but in which table it is located. Would make little sense having iif in output table. )and accept is missing or just in different font?

**Comment by brada4** [comment]
ppoe device is dynamic, you shall use iifname. But bug is there.
Minimal example
```
chain luci_bug {
        type filter hook prerouting priority raw; policy accept;
        iif "lo"
}
```
Should be reported in ../luci though

**Comment by a904055262** [comment]
> ppoe device is dynamic, you shall use iifname. But bug is there. Minimal example
> 
> ```
> chain luci_bug {
>         type filter hook prerouting priority raw; policy accept;
>         iif "lo"
> }
> ```
> 
> Should be reported in ../luci though

![Uploading 2023-11-19_004600.jpg…]()

**Comment by a904055262** [comment]
> ppoe device is dynamic, you shall use iifname. But bug is there. Minimal example
> 
> ```
> chain luci_bug {
>         type filter hook prerouting priority raw; policy accept;
>         iif "lo"
> }
> ```
> 
> Should be reported in ../luci though
![2023-11-19_004600](https://github.com/openwrt/openwrt/assets/3348789/fa46ad56-ff4c-4144-b8c3-44b15138aea7)

**Comment by brada4** [comment]
Please report to github.com/openwrt/luci  ....
Your use case requires iifname,  but you can use no-op example code to demo issue over there.
