### ISSUE TITLE
AX101 doesn't work on 23.05 due to outdated iwlwifi driver

### ISSUE THREAD

**Issue by MoetaYuko** [openwrt/openwrt#14025]
### Describe the bug

AX101 doesn't work on 23.05 due to outdated iwlwifi driver:
```
iwlwifi: No config found for PCI dev 54f0/0244, rev=0x370, rfid=0x10c000
iwlwifi: probe of 0000:06:10.0 failed with error -22
```
Specifically, this is due to a misconfiguration, and a fix was introduced in 6.4: https://github.com/torvalds/linux/commit/0aa27be59e01591a2f5b11fc97fd395dad63c5d3, along with a series of other important fixes.

However, 23.05 uses iwlwifi backported from 6.1 and thus doesn't have this fix. The snapshot driver has been updated to 6.5 so it works fine (except for missing firmware, ~I'll create a PR to add that later~ https://github.com/openwrt/openwrt/pull/14026)

Please update iwlwifi for 23.05 to enable AX101.

### OpenWrt version

r23630-842932a63d

### OpenWrt release

23.05.2

### OpenWrt target/subtarget

x86/64

### Device

x86/64

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by hauke** [comment]
Support for this device is included in OpenWrt master. If you create a PR with we backport we can maybe add it.
