### ISSUE TITLE
This platform requires CONFIG_GRUB_SERIAL be set

### ISSUE THREAD

**Issue by very20101** [openwrt/openwrt#14063]
### Describe the bug

Download package
……

make[2] -C feeds/luci/applications/luci-app-firewall download

make[2] -C package/boot/uboot-armsr download

make[2] -C feeds/luci/applications/luci-app-frps download

make[2] -C feeds/luci/applications/luci-app-nft-qos download

ERROR: package/base-files failed to build.

make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on

make[1] target/download

make[2] -C target/linux download

=========================================================

Compile the fireware

……
make[3]: Leaving directory '/workdir/openwrt/package/system/usign'

time: package/system/usign/compile#0.19#0.08#0.23

make[3]: Entering directory '/workdir/openwrt/package/base-files'

/workdir/openwrt/target/linux/armsr/base-files.mk:3: *** This platform requires CONFIG_GRUB_SERIAL be set!. Stop.

make[3]: Leaving directory '/workdir/openwrt/package/base-files'

time: package/base-files/compile#0.66#0.05#0.72

ERROR: package/base-files failed to build.

make[2]: *** [package/Makefile:128: package/base-files/compile] Error 1

make[2]: Leaving directory '/workdir/openwrt'

make[1]: *** [package/Makefile:122: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2

make[1]: Leaving directory '/workdir/openwrt'

make: *** [/workdir/openwrt/include/toplevel.mk:232: world] Error 2

Error: Process completed with exit code 2.

### OpenWrt version

OpenWrt version VERSION_INFO:  useVersionInfo: Author: Daniel Golle<br/>date: 2023-11-25<br/>commit: mediatek: remove DTS property added by mistake<br/>commit hash: 1b70025ad1f5d8dd93e8415de7817d7975d4a8d2  DATE: 2023-11-25

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

armsr/armv8

### Device

Phicomm N1

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by very20101** [comment]
Sorry, I made a mistake. 

OpenWrt version: R23.10.24 (kernel 5.15.139)
Device:  s905d_n1

But I can't get the  snapshot info  due to failed build.

**Comment by hauke** [comment]
This is probably caused by b10768476f9dc5178d0038e3877b14f95184e46e.
@pprindeville Could you please have a look
@very20101  Please post your build configuration. You can use `./scripts/diffconfig.sh`to export a short version.

**Comment by very20101** [comment]
configuration
==========================
CONFIG_TARGET_armsr=y
CONFIG_TARGET_armsr_armv8=y
CONFIG_TARGET_armsr_armv8_DEVICE_generic=y
CONFIG_BIND_ENABLE_DOH=y
CONFIG_BTRFS_PROGS_ZSTD=y
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_MBEDTLS=y
CONFIG_LIBCURL_NGHTTP2=y
CONFIG_LIBCURL_NO_SMB="!"
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_UNIX_SOCKETS=y
CONFIG_LIBSODIUM_MINIMAL=y
CONFIG_LIBSSH2_OPENSSL=y
# CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED is not set
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_IDEA=y
CONFIG_OPENSSL_WITH_MDC2=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SEED=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_OPENSSL_WITH_WHIRLPOOL=y
CONFIG_PACKAGE_TAR_BZIP2=y
CONFIG_PACKAGE_TAR_GZIP=y
CONFIG_PACKAGE_TAR_XZ=y
CONFIG_PACKAGE_TAR_ZSTD=y
CONFIG_PACKAGE_adblock=y
CONFIG_PACKAGE_attr=y
CONFIG_PACKAGE_bash=y
CONFIG_PACKAGE_bind-check=y
CONFIG_PACKAGE_bind-client=y
CONFIG_PACKAGE_bind-ddns-confgen=y
CONFIG_PACKAGE_bind-dig=y
CONFIG_PACKAGE_bind-dnssec=y
CONFIG_PACKAGE_bind-host=y
CONFIG_PACKAGE_bind-libs=y
CONFIG_PACKAGE_bind-nslookup=y
CONFIG_PACKAGE_bind-rndc=y
CONFIG_PACKAGE_bind-server=y
CONFIG_PACKAGE_bind-tools=y
CONFIG_PACKAGE_block-mount=y
CONFIG_PACKAGE_boost=y
CONFIG_PACKAGE_boost-program_options=y
CONFIG_PACKAGE_boost-system=y
CONFIG_PACKAGE_brook=y
CONFIG_PACKAGE_bsdtar=y
CONFIG_PACKAGE_btrfs-progs=y
CONFIG_PACKAGE_bzip2=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_chattr=y
CONFIG_PACKAGE_chinadns-ng=y
CONFIG_PACKAGE_collectd=y
CONFIG_PACKAGE_collectd-mod-cpu=y
CONFIG_PACKAGE_collectd-mod-interface=y
CONFIG_PACKAGE_collectd-mod-iwinfo=y
CONFIG_PACKAGE_collectd-mod-load=y
CONFIG_PACKAGE_collectd-mod-memory=y
CONFIG_PACKAGE_collectd-mod-network=y
CONFIG_PACKAGE_collectd-mod-rrdtool=y
CONFIG_PACKAGE_coreutils=y
CONFIG_PACKAGE_coreutils-base64=y
CONFIG_PACKAGE_coreutils-nohup=y
CONFIG_PACKAGE_coreutils-sort=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_ddns-scripts=y
CONFIG_PACKAGE_ddns-scripts-services=y
CONFIG_PACKAGE_diffutils=y
CONFIG_PACKAGE_dns2socks=y
CONFIG_PACKAGE_dns2tcp=y
CONFIG_PACKAGE_dnscrypt-proxy2=y
# CONFIG_PACKAGE_dnsmasq is not set
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_dnsmasq_full_auth=y
CONFIG_PACKAGE_dnsmasq_full_conntrack=y
CONFIG_PACKAGE_dnsmasq_full_dhcp=y
CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
CONFIG_PACKAGE_dnsmasq_full_dnssec=y
CONFIG_PACKAGE_dnsmasq_full_ipset=y
CONFIG_PACKAGE_dnsmasq_full_nftset=y
CONFIG_PACKAGE_dnsmasq_full_noid=y
CONFIG_PACKAGE_dnsmasq_full_tftp=y
CONFIG_PACKAGE_dosfstools=y
CONFIG_PACKAGE_f2fs-tools=y
CONFIG_PACKAGE_f2fsck=y
CONFIG_PACKAGE_fail2ban=y
CONFIG_PACKAGE_fail2ban-src=y
CONFIG_PACKAGE_fdisk=y
CONFIG_PACKAGE_frpc=y
CONFIG_PACKAGE_frps=y
CONFIG_PACKAGE_gawk=y
CONFIG_PACKAGE_getopt=y
CONFIG_PACKAGE_golang-github-jedisct1-dnscrypt-proxy2-dev=y
# CONFIG_PACKAGE_grub2-efi-arm is not set
CONFIG_PACKAGE_haproxy=y
CONFIG_PACKAGE_hysteria=y
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_ip6tables-extra=y
CONFIG_PACKAGE_ip6tables-mod-nat=y
CONFIG_PACKAGE_ip6tables-nft=y
CONFIG_PACKAGE_ip6tables-zz-legacy=y
CONFIG_PACKAGE_iperf3-ssl=y
CONFIG_PACKAGE_ipset=y
CONFIG_PACKAGE_ipt2socks=y
CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
CONFIG_PACKAGE_iptables-mod-extra=y
CONFIG_PACKAGE_iptables-mod-geoip=y
CONFIG_PACKAGE_iptables-mod-ipmark=y
CONFIG_PACKAGE_iptables-mod-iprange=y
CONFIG_PACKAGE_iptables-mod-nat-extra=y
CONFIG_PACKAGE_iptables-mod-socket=y
CONFIG_PACKAGE_iptables-mod-tproxy=y
CONFIG_PACKAGE_iptables-nft=y
CONFIG_PACKAGE_iptables-zz-legacy=y
CONFIG_PACKAGE_jq=y
CONFIG_PACKAGE_kmod-br-netfilter=y
CONFIG_PACKAGE_kmod-crypto-acompress=y
CONFIG_PACKAGE_kmod-fs-btrfs=y
# CONFIG_PACKAGE_kmod-fs-vfat is not set
CONFIG_PACKAGE_kmod-ifb=m
CONFIG_PACKAGE_kmod-inet-diag=y
CONFIG_PACKAGE_kmod-ip6tables=y
CONFIG_PACKAGE_kmod-ip6tables-extra=y
CONFIG_PACKAGE_kmod-ipt-compat-xtables=y
CONFIG_PACKAGE_kmod-ipt-conntrack=y
CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-extra=y
CONFIG_PACKAGE_kmod-ipt-filter=y
CONFIG_PACKAGE_kmod-ipt-fuzzy=y
CONFIG_PACKAGE_kmod-ipt-geoip=y
CONFIG_PACKAGE_kmod-ipt-iface=y
CONFIG_PACKAGE_kmod-ipt-ipmark=y
CONFIG_PACKAGE_kmod-ipt-iprange=y
CONFIG_PACKAGE_kmod-ipt-ipset=y
CONFIG_PACKAGE_kmod-ipt-lua=y
CONFIG_PACKAGE_kmod-ipt-nat=y
CONFIG_PACKAGE_kmod-ipt-nat-extra=y
CONFIG_PACKAGE_kmod-ipt-nat6=y
CONFIG_PACKAGE_kmod-ipt-offload=y
CONFIG_PACKAGE_kmod-ipt-raw=y
CONFIG_PACKAGE_kmod-ipt-raw6=y
CONFIG_PACKAGE_kmod-ipt-socket=y
CONFIG_PACKAGE_kmod-ipt-tproxy=y
CONFIG_PACKAGE_kmod-ipt-u32=y
CONFIG_PACKAGE_kmod-lib-lzo=y
CONFIG_PACKAGE_kmod-lib-raid6=y
CONFIG_PACKAGE_kmod-lib-textsearch=y
CONFIG_PACKAGE_kmod-lib-xor=y
CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
CONFIG_PACKAGE_kmod-lib-zstd=y
CONFIG_PACKAGE_kmod-nf-conncount=y
CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-ipt6=y
CONFIG_PACKAGE_kmod-nf-nat6=y
CONFIG_PACKAGE_kmod-nf-socket=y
CONFIG_PACKAGE_kmod-nft-bridge=y
CONFIG_PACKAGE_kmod-nft-compat=y
CONFIG_PACKAGE_kmod-nft-netdev=y
CONFIG_PACKAGE_kmod-nft-socket=y
CONFIG_PACKAGE_kmod-nft-xfrm=y
# CONFIG_PACKAGE_kmod-nls-base is not set
# CONFIG_PACKAGE_kmod-nls-cp437 is not set
# CONFIG_PACKAGE_kmod-nls-iso8859-1 is not set
# CONFIG_PACKAGE_kmod-nls-utf8 is not set
CONFIG_PACKAGE_kmod-sched-core=m
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_libarchive=y
CONFIG_PACKAGE_libatomic=y
CONFIG_PACKAGE_libattr=y
CONFIG_PACKAGE_libbpf=y
CONFIG_PACKAGE_libbz2=y
CONFIG_PACKAGE_libcap=y
CONFIG_PACKAGE_libcap-bin=y
CONFIG_PACKAGE_libcap-bin-capsh-shell="/bin/sh"
CONFIG_PACKAGE_libcap-ng=y
CONFIG_PACKAGE_libcares=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libelf=y
CONFIG_PACKAGE_libev=y
CONFIG_PACKAGE_libevent2=y
CONFIG_PACKAGE_libexpat=y
CONFIG_PACKAGE_libfdisk=y
CONFIG_PACKAGE_libffi=y
CONFIG_PACKAGE_libgmp=y
CONFIG_PACKAGE_libiconv-full=y
CONFIG_PACKAGE_libinih=y
CONFIG_PACKAGE_libip4tc=y
CONFIG_PACKAGE_libip6tc=y
CONFIG_PACKAGE_libipset=y
CONFIG_PACKAGE_libiptext=y
CONFIG_PACKAGE_libiptext-nft=y
CONFIG_PACKAGE_libiptext6=y
CONFIG_PACKAGE_libiwinfo=y
CONFIG_PACKAGE_libiwinfo-data=y
CONFIG_PACKAGE_libltdl=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblua5.3=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_liblzma=y
CONFIG_PACKAGE_liblzo=y
CONFIG_PACKAGE_libmount=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnetfilter-conntrack=y
CONFIG_PACKAGE_libnettle=y
CONFIG_PACKAGE_libnfnetlink=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_libparted=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_libpcre=y
CONFIG_PACKAGE_libpcre2=y
CONFIG_PACKAGE_libpython3=y
CONFIG_PACKAGE_libreadline=y
CONFIG_PACKAGE_librrd1=y
CONFIG_PACKAGE_libruby=y
CONFIG_PACKAGE_libsodium=y
CONFIG_PACKAGE_libsqlite3=y
CONFIG_PACKAGE_libssh2=y
CONFIG_PACKAGE_libstdcpp=y
CONFIG_PACKAGE_libtirpc=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libuci-lua=y
CONFIG_PACKAGE_libudns=y
CONFIG_PACKAGE_libunbound=y
CONFIG_PACKAGE_libunbound_dnscrypt=y
CONFIG_PACKAGE_libunbound_ipset=y
CONFIG_PACKAGE_libunbound_libevent=y
CONFIG_PACKAGE_libunbound_libpthread=y
CONFIG_PACKAGE_libunbound_nghttp2=y
CONFIG_PACKAGE_libunbound_pythonmodule=y
CONFIG_PACKAGE_libunbound_subnet=y
CONFIG_PACKAGE_liburcu=y
CONFIG_PACKAGE_libuv=y
CONFIG_PACKAGE_libwebsockets-full=y
CONFIG_PACKAGE_libxtables=y
CONFIG_PACKAGE_libyaml=y
CONFIG_PACKAGE_libzstd=y
CONFIG_PACKAGE_losetup=y
CONFIG_PACKAGE_lsattr=y
CONFIG_PACKAGE_lsblk=y
CONFIG_PACKAGE_lsof=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_lua-neturl=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-adblock=y
CONFIG_PACKAGE_luci-app-advanced=y
CONFIG_PACKAGE_luci-app-amlogic=y
CONFIG_PACKAGE_luci-app-ddns=y
CONFIG_PACKAGE_luci-app-eqos=m
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-frpc=y
CONFIG_PACKAGE_luci-app-frps=y
CONFIG_PACKAGE_luci-app-koolproxyR=y
CONFIG_PACKAGE_luci-app-nft-qos=y
CONFIG_PACKAGE_luci-app-nlbwmon=y
CONFIG_PACKAGE_luci-app-openclash=y
CONFIG_PACKAGE_luci-app-openvpn=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-app-statistics=y
CONFIG_PACKAGE_luci-app-tinyproxy=y
CONFIG_PACKAGE_luci-app-ttyd=y
CONFIG_PACKAGE_luci-app-unbound=y
CONFIG_PACKAGE_luci-app-upnp=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-httpprotoutils=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-ipkg=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-light=y
CONFIG_PACKAGE_luci-lua-runtime=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-theme-argone=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_luci-theme-openwrt-2020=y
CONFIG_PACKAGE_microsocks=y
CONFIG_PACKAGE_miniupnpd-nftables=y
CONFIG_PACKAGE_mosdns=y
CONFIG_PACKAGE_nft-qos=y
CONFIG_PACKAGE_nlbwmon=y
CONFIG_PACKAGE_nmap-full=y
CONFIG_PACKAGE_openssl-util=y
CONFIG_PACKAGE_parted=y
CONFIG_PACKAGE_perl=y
CONFIG_PACKAGE_perl-http-date=y
CONFIG_PACKAGE_perlbase-base=y
CONFIG_PACKAGE_perlbase-bytes=y
CONFIG_PACKAGE_perlbase-charnames=y
CONFIG_PACKAGE_perlbase-class=y
CONFIG_PACKAGE_perlbase-config=y
CONFIG_PACKAGE_perlbase-cwd=y
CONFIG_PACKAGE_perlbase-dynaloader=y
CONFIG_PACKAGE_perlbase-errno=y
CONFIG_PACKAGE_perlbase-essential=y
CONFIG_PACKAGE_perlbase-fcntl=y
CONFIG_PACKAGE_perlbase-file=y
CONFIG_PACKAGE_perlbase-filehandle=y
CONFIG_PACKAGE_perlbase-getopt=y
CONFIG_PACKAGE_perlbase-i18n=y
CONFIG_PACKAGE_perlbase-integer=y
CONFIG_PACKAGE_perlbase-io=y
CONFIG_PACKAGE_perlbase-list=y
CONFIG_PACKAGE_perlbase-locale=y
CONFIG_PACKAGE_perlbase-params=y
CONFIG_PACKAGE_perlbase-posix=y
CONFIG_PACKAGE_perlbase-re=y
CONFIG_PACKAGE_perlbase-scalar=y
CONFIG_PACKAGE_perlbase-selectsaver=y
CONFIG_PACKAGE_perlbase-socket=y
CONFIG_PACKAGE_perlbase-symbol=y
CONFIG_PACKAGE_perlbase-tie=y
CONFIG_PACKAGE_perlbase-time=y
CONFIG_PACKAGE_perlbase-unicode=y
CONFIG_PACKAGE_perlbase-unicore=y
CONFIG_PACKAGE_perlbase-utf8=y
CONFIG_PACKAGE_perlbase-xsloader=y
CONFIG_PACKAGE_pigz=y
CONFIG_PACKAGE_pv=y
CONFIG_PACKAGE_python3-base=y
CONFIG_PACKAGE_python3-ctypes=y
CONFIG_PACKAGE_python3-distutils=y
CONFIG_PACKAGE_python3-email=y
CONFIG_PACKAGE_python3-light=y
CONFIG_PACKAGE_python3-logging=y
CONFIG_PACKAGE_python3-pkg-resources=y
CONFIG_PACKAGE_python3-sqlite3=y
CONFIG_PACKAGE_python3-urllib=y
CONFIG_PACKAGE_resolveip=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-rrdns=y
CONFIG_PACKAGE_rpcd-mod-ucode=y
CONFIG_PACKAGE_rrdtool1=y
CONFIG_PACKAGE_ruby=y
CONFIG_PACKAGE_ruby-bigdecimal=y
CONFIG_PACKAGE_ruby-date=y
CONFIG_PACKAGE_ruby-digest=y
CONFIG_PACKAGE_ruby-enc=y
CONFIG_PACKAGE_ruby-forwardable=y
CONFIG_PACKAGE_ruby-pstore=y
CONFIG_PACKAGE_ruby-psych=y
CONFIG_PACKAGE_ruby-stringio=y
CONFIG_PACKAGE_ruby-yaml=y
CONFIG_PACKAGE_softethervpn-base=y
CONFIG_PACKAGE_softethervpn-server=y
CONFIG_PACKAGE_tar=y
CONFIG_PACKAGE_tc-tiny=m
CONFIG_PACKAGE_tcpdump=y
CONFIG_PACKAGE_tcping=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_tinyproxy=y
CONFIG_PACKAGE_trojan-plus=y
CONFIG_PACKAGE_ttyd=y
CONFIG_PACKAGE_ucode-mod-html=y
CONFIG_PACKAGE_ucode-mod-lua=y
CONFIG_PACKAGE_ucode-mod-math=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_PACKAGE_unbound-anchor=y
CONFIG_PACKAGE_unbound-checkconf=y
CONFIG_PACKAGE_unbound-control=y
CONFIG_PACKAGE_unbound-control-setup=y
CONFIG_PACKAGE_unbound-daemon=y
CONFIG_PACKAGE_unbound-host=y
CONFIG_PACKAGE_unzip=y
CONFIG_PACKAGE_uuidgen=y
CONFIG_PACKAGE_v2dat=y
CONFIG_PACKAGE_vim-fuller=y
CONFIG_PACKAGE_xfs-fsck=y
CONFIG_PACKAGE_xfs-mkfs=y
CONFIG_PACKAGE_xtables-legacy=y
CONFIG_PACKAGE_xtables-nft=y
CONFIG_PACKAGE_xz=y
CONFIG_PACKAGE_xz-utils=y
CONFIG_PACKAGE_yq=y
CONFIG_PACKAGE_zlib=y
CONFIG_PACKAGE_zsh=y
CONFIG_PARTED_READLINE=y
CONFIG_PERL_NOCOMMENT=y
CONFIG_PERL_THREADS=y
CONFIG_SINGBOX_WITH_CLASH_API=y
CONFIG_SINGBOX_WITH_ECH=y
CONFIG_SINGBOX_WITH_GVISOR=y
CONFIG_SINGBOX_WITH_QUIC=y
CONFIG_SINGBOX_WITH_REALITY_SERVER=y
CONFIG_SINGBOX_WITH_UTLS=y
CONFIG_SINGBOX_WITH_WIREGUARD=y
CONFIG_SQLITE3_COLUMN_METADATA=y
CONFIG_SQLITE3_DYNAMIC_EXTENSIONS=y
CONFIG_SQLITE3_FTS3=y
CONFIG_SQLITE3_FTS4=y
CONFIG_SQLITE3_FTS5=y
CONFIG_SQLITE3_RTREE=y
# CONFIG_TARGET_IMAGES_GZIP is not set
# CONFIG_TARGET_ROOTFS_CPIOGZ is not set
# CONFIG_TARGET_ROOTFS_EXT4FS is not set
# CONFIG_TARGET_ROOTFS_INITRAMFS is not set
# CONFIG_TARGET_ROOTFS_SQUASHFS is not set
CONFIG_ZSTD_OPTIMIZE_O3=y
CONFIG_boost-compile-visibility-hidden=y
CONFIG_boost-runtime-shared=y
CONFIG_boost-static-and-shared-libs=y
CONFIG_boost-variant-release=y
==================================

The configuration compiled and built successfully 5 days ago.

**Comment by pprindeville** [comment]
What serial is the console port on?  And what happens when you set `CONFIG_GRUB_SERIAL=ttyS0` (or whatever) and rebuild?

**Comment by hauke** [comment]
These two options are not set:
```
# CONFIG_TARGET_ROOTFS_EXT4FS is not set
# CONFIG_TARGET_ROOTFS_SQUASHFS is not set
```
Then `CONFIG_GRUB_EFI_IMAGES` is not available and you can not set `CONFIG_GRUB_SERIAL`. 

@pprindeville  You should make `CONFIG_GRUB_SERIAL` probably independent of the `GRUB` options. Something like this:
````
	config TARGET_SERIAL
		string "Serial port device"
		depends on TARGET_x86 || TARGET_armsr
		default "ttyS0"
````

**Comment by hauke** [comment]
Please try #14078 It should fix your problem.

**Comment by very20101** [comment]
The problem is still reproduced as CONFIG_TARGET_ROOTFS_EXT4FS be set


2023-11-28T01:18:01.9848198Z make[2]: Entering directory '/workdir/openwrt/scripts/config'
2023-11-28T01:18:01.9848968Z make[2]: 'conf' is up to date.
2023-11-28T01:18:01.9849732Z make[2]: Leaving directory '/workdir/openwrt/scripts/config'
2023-11-28T01:18:03.1281390Z Checking 'rsync'... ok.
2023-11-28T01:18:04.7371225Z time: target/linux/prereq#0.09#0.04#0.13
2023-11-28T01:18:05.4867410Z  make[1] tools/flock/compile
2023-11-28T01:18:07.4142160Z  make[2] -C tools/flock compile
2023-11-28T01:18:07.6469096Z  make[1] tools/download
2023-11-28T01:18:09.5502201Z  make[2] -C tools/bison download
2023-11-28T01:18:09.5514015Z  make[2] -C tools/autoconf-archive download
2023-11-28T01:18:09.5515978Z  make[2] -C tools/cmake download
2023-11-28T01:18:09.5569399Z  make[2] -C tools/cpio download
2023-11-28T01:18:09.5582013Z  make[2] -C tools/bc download
2023-11-28T01:18:09.5598254Z  make[2] -C tools/autoconf download
2023-11-28T01:18:09.5646257Z  make[2] -C tools/dosfstools download
2023-11-28T01:18:09.5666856Z  make[2] -C tools/automake download
2023-11-28T01:18:10.0643122Z  make[2] -C tools/e2fsprogs download
2023-11-28T01:18:10.1122922Z  make[2] -C tools/elfutils download
2023-11-28T01:18:10.1633019Z  make[2] -C tools/expat download
2023-11-28T01:18:10.2016912Z  make[2] -C tools/fakeroot download
2023-11-28T01:18:10.3476346Z  make[2] -C tools/findutils download
2023-11-28T01:18:10.3989529Z  make[2] -C tools/firmware-utils download
2023-11-28T01:18:10.4129816Z  make[2] -C tools/flex download
2023-11-28T01:18:10.6298640Z  make[2] -C tools/gengetopt download
2023-11-28T01:18:10.6350070Z  make[2] -C tools/gnulib download
2023-11-28T01:18:10.6666426Z  make[2] -C tools/libressl download
2023-11-28T01:18:10.8440353Z  make[2] -C tools/libtool download
2023-11-28T01:18:10.9065149Z  make[2] -C tools/lzma download
2023-11-28T01:18:11.0090135Z  make[2] -C tools/m4 download
2023-11-28T01:18:11.1379048Z  make[2] -C tools/make-ext4fs download
2023-11-28T01:18:11.2641858Z  make[2] -C tools/meson download
2023-11-28T01:18:11.3073574Z  make[2] -C tools/missing-macros download
2023-11-28T01:18:11.3495479Z  make[2] -C tools/mkimage download
2023-11-28T01:18:11.4428915Z  make[2] -C tools/mklibs download
2023-11-28T01:18:11.6140651Z  make[2] -C tools/mtd-utils download
2023-11-28T01:18:11.6257066Z  make[2] -C tools/mtools download
2023-11-28T01:18:11.6581144Z  make[2] -C tools/ninja download
2023-11-28T01:18:11.7291754Z  make[2] -C tools/padjffs2 download
2023-11-28T01:18:11.7728174Z  make[2] -C tools/patch-image download
2023-11-28T01:18:11.8163228Z  make[2] -C tools/patchelf download
2023-11-28T01:18:11.9549039Z  make[2] -C tools/pkgconf download
2023-11-28T01:18:12.0216071Z  make[2] -C tools/quilt download
2023-11-28T01:18:12.1617065Z  make[2] -C tools/squashfs4 download
2023-11-28T01:18:12.3550029Z  make[2] -C tools/sstrip download
2023-11-28T01:18:12.5159861Z  make[2] -C tools/zip download
2023-11-28T01:18:12.7534739Z  make[2] -C tools/zlib download
2023-11-28T01:18:12.7888255Z  make[2] -C tools/zstd download
2023-11-28T01:18:12.9668998Z  make[2] -C tools/gmp download
2023-11-28T01:18:13.1612850Z  make[2] -C tools/mpc download
2023-11-28T01:18:13.1648833Z  make[2] -C tools/mpfr download
2023-11-28T01:18:13.2474316Z  make[2] -C tools/libdeflate download
2023-11-28T01:18:13.4871336Z  make[2] -C tools/patch download
2023-11-28T01:18:13.5343567Z  make[2] -C tools/tar download
2023-11-28T01:18:13.6323736Z  make[2] -C tools/xz download
2023-11-28T01:18:13.6693573Z  make[2] -C tools/flock download
2023-11-28T01:18:13.7159155Z  make[2] -C tools/sed download
2023-11-28T01:18:17.1064871Z  make[1] toolchain/download
2023-11-28T01:18:18.9458580Z  make[2] -C toolchain/kernel-headers download
2023-11-28T01:18:18.9502282Z  make[2] -C toolchain/gcc/initial download
2023-11-28T01:18:18.9515005Z  make[2] -C toolchain/gdb download
2023-11-28T01:18:18.9556742Z  make[2] -C toolchain/binutils download
2023-11-28T01:18:18.9568949Z  make[2] -C toolchain/gcc/final download
2023-11-28T01:18:18.9586434Z  make[2] -C toolchain/musl download
2023-11-28T01:18:18.9636012Z  make[2] -C toolchain/fortify-headers download
2023-11-28T01:18:22.3341315Z  make[1] package/download
2023-11-28T01:18:24.2317346Z  make[2] -C package/boot/grub2 download
2023-11-28T01:18:24.2330155Z  make[2] -C package/base-files download
2023-11-28T01:18:24.2377532Z  make[2] -C feeds/luci/applications/luci-app-adblock download
2023-11-28T01:18:24.2422720Z  make[2] -C feeds/luci/applications/luci-app-ddns download
2023-11-28T01:18:24.2475862Z  make[2] -C package/boot/uboot-armsr download
2023-11-28T01:18:24.2489806Z  make[2] -C feeds/luci/collections/luci download
2023-11-28T01:18:24.2586757Z  make[2] -C feeds/luci/applications/luci-app-firewall download
2023-11-28T01:18:24.2669438Z  make[2] -C feeds/luci/applications/luci-app-frpc download
2023-11-28T01:18:25.1274378Z  make[2] -C feeds/luci/applications/luci-app-frps download
2023-11-28T01:18:25.6015808Z  make[2] -C feeds/luci/applications/luci-app-nft-qos download
2023-11-28T01:18:25.6209445Z     ERROR: package/base-files failed to build.
2023-11-28T01:18:29.6220955Z make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
2023-11-28T01:18:29.6275688Z  make[1] target/download
2023-11-28T01:18:31.5179864Z  make[2] -C target/linux download





================================
config file with CONFIG_TARGET_ROOTFS_EXT4FS be set

# Root filesystem images
#
CONFIG_TARGET_ROOTFS_EXT4FS=y
CONFIG_TARGET_EXT4_RESERVED_PCT=0
CONFIG_TARGET_EXT4_BLOCKSIZE_4K=y
# CONFIG_TARGET_EXT4_BLOCKSIZE_2K is not set
# CONFIG_TARGET_EXT4_BLOCKSIZE_1K is not set
CONFIG_TARGET_EXT4_BLOCKSIZE=4096
# CONFIG_TARGET_EXT4_JOURNAL is not set
# CONFIG_TARGET_ROOTFS_SQUASHFS is not set
CONFIG_TARGET_UBIFS_FREE_SPACE_FIXUP=y
CONFIG_TARGET_UBIFS_JOURNAL_SIZE=""
CONFIG_GRUB_EFI_IMAGES=y
CONFIG_GRUB_CONSOLE=y
CONFIG_GRUB_SERIAL="ttyS0"
CONFIG_GRUB_BAUDRATE=115200
# CONFIG_GRUB_FLOWCONTROL is not set
CONFIG_GRUB_BOOTOPTS=""
CONFIG_GRUB_TIMEOUT="5"
CONFIG_GRUB_TITLE="OpenWrt"
# CONFIG_VMDK_IMAGES is not set
# CONFIG_TARGET_IMAGES_GZIP is not set
