### ISSUE TITLE
typo in the 22.03.6 release note

### ISSUE THREAD

**Issue by xlighting2017** [openwrt/openwrt#14139]
### Describe the bug

I presume the version number should be **22**.03 , not   23.03, right?
<img width="1111" alt="image" src="https://github.com/openwrt/openwrt/assets/25970065/b5f69546-b533-4810-b619-6e43720198c2">

### OpenWrt version

22.03.6

### OpenWrt release

22.03.6

### OpenWrt target/subtarget

all

### Device

all

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
The report does not concern openwrt itself but incorrect information on the website: https://openwrt.org/releases/22.03/notes-22.03.6

**Comment by brada4** [comment]
ping @hauke as per wiki history
