### ISSUE TITLE
Build fails with make[2]: *** [package/Makefile:70: package/install] Error 255

### ISSUE THREAD

**Issue by openips** [openwrt/openwrt#14173]
### Describe the bug

with commit 01d1c1ad296cc71f87ea02b01b16a09fe5d933a1 
build fails with log below
```
Configuring dnsmasq-full.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/LEDE/openwrt-master-new'
make[1]: *** [package/Makefile:123: /LEDE/openwrt-master-new/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/LEDE/openwrt-master-new'
make: *** [/LEDE/openwrt-master-new/include/toplevel.mk:232: world] Error 2
```

### OpenWrt version

OpenWrt SNAPSHOT r0+24593-01d1c1ad29

### OpenWrt release

r0+24593-01d1c1ad29

### OpenWrt target/subtarget

x86/64

### Device

Default string Default string

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by openips** [comment]
> Invalid Release reported. `r0+24593-01d1c1ad29` Is this from a clean repository?

master feed

**Comment by jow-** [comment]
The quoted error contains no details, please provide a complete error log.

**Comment by openips** [comment]
> The quoted error contains no details, please provide a complete error log.
full logbelow，please read from tail.
[clash.zip](https://github.com/openwrt/openwrt/files/13623561/clash.zip)
