### ISSUE TITLE
ujail segfault ( error 4 in libubox.so.20220515 )

### ISSUE THREAD

**Issue by systemcrash** [openwrt/openwrt#14171]
### Describe the bug

Is this better put in `openwrt/procd`? Did not find similar reports, so here goes.

Not certain what was happening at the time, but this was logged:

```
Fri Dec  8 01:02:46 2023 user.notice dnsmasq: found already running DHCP-server on interface 'br-lan' refusing to start, use 'option force 1' to override
Fri Dec  8 01:02:46 2023 user.notice dnsmasq: found already running DHCP-server on interface 'br-lan' refusing to start, use 'option force 1' to override
Fri Dec  8 01:02:46 2023 cron.info dnsmasq[1]: exiting on receipt of SIGTERM
Fri Dec  8 01:02:46 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Fri Dec  8 01:02:46 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Fri Dec  8 01:02:46 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Fri Dec  8 01:02:47 2023 kern.info kernel: [96865.948762] ujail[6298]: segfault at 5e ip 00007f073c2fc9fe sp 00007fffeeef03e0 error 4 in libubox.so.20220515[7f073c2fb000+5000]
Fri Dec  8 01:02:47 2023 kern.info kernel: [96865.959042] Code: 38 76 00 00 41 58 ff 25 b8 74 00 00 31 c0 c3 55 48 89 fd 53 48 83 ec 18 40 f6 c6 03 75 0c 48 83 c4 18 5b 5d e9 81 ff ff ff 90 <80> 7d 0e 00 8b 7f 08 89 f3 75 37 40 f6 c6 08 74 07 be 01 00 00 00
Fri Dec  8 01:02:47 2023 daemon.info dnsmasq[1]: started, version 2.86 cachesize 150
Fri Dec  8 01:02:47 2023 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Fri Dec  8 01:02:47 2023 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
```

1 ) yes I'm aware of the other server
2) no I did not manually restart this one

The older libubox.so.20220515 may not warrant attention. If not, please close.

### OpenWrt version

r20134-5f15225c1e

### OpenWrt release

22.03.5

### OpenWrt target/subtarget

x86/64

### Device

innotek GmbH VirtualBox

### Image kind

Official downloaded image

### Steps to reproduce

Leave system running for a while

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
22.03.6 was recently released. Can you try that? It warrants attention for almost half year from now.

**Comment by schm0** [comment]
On latest master, netifd is segfaulting for me.

**Comment by brada4** [comment]
@schm0 netifd sandbox called ujail or netifd alone with ujail disabled? backtrace at least logread level and version tag would be nice.

**Comment by schm0** [comment]
I can't tell.. sorry.
It segfaults when bringing up the bridge ports (libc related)
Reverting the latest netifd commit doesn't fix it.
I'm currently doing a build with netifd, libnl-tiny and ubox changes reverted.
I will report back asap.

**Comment by brada4** [comment]
there is offset into library file in kernel message which together with build number helps to recover libc call which failed.

**Comment by brada4** [comment]
@schm0 neither of your commits are relevant to original post in regard to oldest supported release.

**Comment by schm0** [comment]
sorry, i didn't realize it was about an older openwrt version but checking the issue list there were quite some issues the past week.

**Comment by brada4** [comment]
feel free to gather at least kernel message and open new issue to signal heads up about recent breaking change.
