### ISSUE TITLE
Lags between OpenWRT Router and Vodafone Router

### ISSUE THREAD

**Issue by PenguinsHaveColdFeet** [openwrt/openwrt#14204]
### Describe the bug

Hello,

iam recieving huge lag spike ingame, after a check with WinMTR i've noticed that my OpenWrt Router is losing 10% of Packages for no reason, this was not the case 1 year ago. with current Version 23.05.2, same issue with 22.03.6. And when i bypass the OpenWrt router Loss is at <1%

### OpenWrt version

r23630-842932a63d

### OpenWrt release

23.05.2

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link Archer C7 v5

### Image kind

Official downloaded image

### Steps to reproduce

PC with WinMTR -> OpenWrt Router 192.168.11.1 -> Vodafone Router 192.168.0.1

Start WinMTR with 192.168.0.1 and see Package Loss ov 10%

### Actual behaviour

Package Loss of 10%

### Additional info

|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -  |  %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                            192.168.11.1 -   |10 |  319 |  289 |    0 |    0 |    5 |    0 |
|                             192.168.0.1 -    |3 |  481 |  470 |    0 |    1 |   17 |    1 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
can you try command line mtr from router to both sides? 
is it clean setup or migrated configurations? 
Wired or wireless?
clodflare or waveform speed/latency tests? (not ooka or dslrep)

**Comment by PenguinsHaveColdFeet** [comment]
Hi brada4,

can you try command line mtr from router to both sides?
     I was checking now with 3 devices, all of them are working and router -> router aswell
     Router -> Router
      Host                                                                        Loss%   Snt   Last   Avg  Best  Wrst StDev
      1. 192.168.0.1 (192.168.0.1)                                     0.0%  1018    1.7   1.1   0.6   4.3   0.5
      i think the problem was that i had 0.5 seconds waiting time on WinMTR i had 0% Loss with default mtr 1s delay. But the Wrst Time seemds still a little bit off

is it clean setup or migrated configurations?
     migrated

Wired or wireless?
     wired

clodflare or waveform speed/latency tests? (not ooka or dslrep)
     When i used the cloudflare Test with OpenWRT i get good results, beside that my internet speed is 25% slower, but the Packet Loss Measurement is not working -> Unable to perform measurement: ICE connection timeout!

**Comment by brada4** [comment]
What is the latency grade from either? 
https://www.waveform.com/tools/bufferbloat?test-id=b088c83b-e7e1-4da2-8df4-b4d28c5abac5

And if you connect your computer directly to vodafone CPE? And if you set CPE to passthrough mode (not DMZ, really passthrough that you get public IP address on your OpenWRT/PC)

**Comment by PenguinsHaveColdFeet** [comment]
Not too bad now

Vodafone
https://www.waveform.com/tools/bufferbloat?test-id=3604b235-df4f-4f41-b286-d0d7658700f1

OpenWrt -> Vodafone
https://www.waveform.com/tools/bufferbloat?test-id=d1efd105-850a-424b-ad43-1f72de57c5de

**Comment by brada4** [comment]
Measures you can take (one of):

The latency lies in your CPE+line, if it has any kind of QoS enable it and set up/down limits to 90-95% of subscribed rates.
Best if it permits to add port and/or ip of particular game.

For OpenWRT - you can set br-lan to dhcp client and avoid extra nat and just bridge wifi networks in CPE subnet. You will still have that +2ms latency, just that no CPU used for translating packets and you can use it as reasonable file storage etc.

Though most efficient and controllable is to set CPE to passthrough and run nat and luci-app-nft-qos on OpenWRT.

default fq_codel shaper just sorts packets sending one belonging to most starved flow (think one or more connections in a bucket) first
qos scripts/luci apps would slow down TCP streams below what provider provides thus not filling their router excess buffer and not letting them slow individual packets. one with nft takes shortcut to re-use firewall's packet classification instead of evaluating new classes per packet.

**Comment by PenguinsHaveColdFeet** [comment]
Thanks for the ideas, only option would be to passthrough, since id like to keep the firewall of OpenWrt Active and CPE has no QoS Option.

The lags are now back:

https://www.waveform.com/tools/bufferbloat?test-id=f4d85d58-043e-4612-9da9-f180f4388575


MTR Openwrt -> CPE
192.168.0.1                                                               1.5%   531    1.7   3.7   0.6  36.9   6.9


WinMTR PC->Openwrt->CPE

|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                            192.168.66.1 -   10 |  119 |  108 |    0 |    0 |    9 |    0 |
|                             192.168.0.1 -    2 |  188 |  185 |    0 |    1 |   10 |    1 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

**Comment by PenguinsHaveColdFeet** [comment]
I think I have found the problem with the lag, the OpenWrt router is also connected to the TV via cable, as soon as it is streamed with this, I have the sound-like lags ingame, when the TV is switched off, this is not the case. So QoS based on OpenWrt would be a solution after all

**Comment by brada4** [comment]
That seems textbook bufferbloat.
Install qos script and configure, measure again, maybe reduce total bandwidth if still no fun.

**Comment by brada4** [comment]
Then check how to make CPE pass-through, pay attention to 100.64 public address, you will need to learn which NAT traversal is needed to listen on public address like in-game chats etc.

**Comment by PenguinsHaveColdFeet** [comment]
Welp the TV is stronger than QoS or my QoS Setup skills, anyway thank you very much for your help and support! I learned again alot! Much appreciated!!!

**Comment by brada4** [comment]
You need to apply bandwidth limits on WAN interface, like 700 DOWN 48 UP based on your latest measurement. It is the generic thing to just slow down traffic to avoid buffering in provider's router.
