### ISSUE TITLE
Kernel 6.6.x LTS instead of 6.1 LTS?

### ISSUE THREAD

**Issue by Neustradamus** [openwrt/openwrt#14262]
### Describe the bug

Dear @OpenWrt team,

I think it is time to switch 6.1.x LTS to 6.6.x LTS in master.

Thanks in advance.

### OpenWrt version

snapshot

### OpenWrt release

snapshot

### OpenWrt target/subtarget

*

### Device

*

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by oliv3r** [comment]
Just for passers by dropping this one: http://lists.openwrt.org/pipermail/openwrt-devel/2024-February/042204.html

**Comment by Neustradamus** [comment]
@oliv3r: Thanks for your important comment!

@hauke: Thanks to have looked my ticket and to plan with the latest LTS Kernel: 6.6.x.

And please like LibreOffice, plan RC versions with the real official month release date.
LibreOffice 24.2 has been released the last day of January: 2024-01-31:
- https://blog.documentfoundation.org/blog/2024/01/31/libreoffice-24-2/
