### ISSUE TITLE
System log filled by AP-STA-POLL-OK - device no more available on network

### ISSUE THREAD

**Issue by pesa1234** [openwrt/openwrt#14415]
### Describe the bug

When a device connected to the wifi network is no longer available because it is turned off or out of range, the message AP-STA-POLL-OK appears.
Device seems also available because I see on associated station list

### OpenWrt version

r24846-56ce1a48ce

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

GL.iNet GL-MT6000

### Image kind

Self-built image

### Steps to reproduce

Connect a device via wifi
Disconnect
Wait 5 minutes, message appear every 5 minutes (as the inactivity polling)

### Actual behaviour

When a device connected to the wifi network is no longer available because it is turned off or out of range device seems still connected to network.

### Expected behaviour

When a device is not connected to wifi network, after 5 minutes should disappear from associated stations.

### Additional info

Seems that latest commit on mac80211 or hostapd cause the issue, this evening I'll try to revert some commit.

### Diffconfig

```text
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_glinet_gl-mt6000=y
CONFIG_DEVEL=y
CONFIG_HTOP_LMSENSORS=y
CONFIG_IMAGEOPT=y
CONFIG_IPK_FILES_CHECKSUMS=y
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_MBEDTLS=y
CONFIG_LIBCURL_NGHTTP2=y
CONFIG_LIBCURL_NO_SMB="!"
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_UNIX_SOCKETS=y
CONFIG_LINUX_6_1=y
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_OPTIMIZE_SPEED=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_IDEA=y
CONFIG_OPENSSL_WITH_MDC2=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SEED=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_OPENSSL_WITH_WHIRLPOOL=y
CONFIG_OPENVPN_openssl_ENABLE_FRAGMENT=y
CONFIG_OPENVPN_openssl_ENABLE_LZ4=y
CONFIG_OPENVPN_openssl_ENABLE_LZO=y
CONFIG_OPENVPN_openssl_ENABLE_PORT_SHARE=y
CONFIG_OPENVPN_openssl_ENABLE_SMALL=y
CONFIG_PACKAGE_adblock=y
CONFIG_PACKAGE_avahi-dbus-daemon=y
CONFIG_PACKAGE_blkid=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_coreutils=y
CONFIG_PACKAGE_coreutils-sort=y
CONFIG_PACKAGE_coreutils-stat=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_dbus=y
# CONFIG_PACKAGE_dnsmasq is not set
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_dnsmasq_full_auth=y
CONFIG_PACKAGE_dnsmasq_full_conntrack=y
CONFIG_PACKAGE_dnsmasq_full_dhcp=y
CONFIG_PACKAGE_dnsmasq_full_dnssec=y
CONFIG_PACKAGE_dnsmasq_full_nftset=y
CONFIG_PACKAGE_dnsmasq_full_noid=y
CONFIG_PACKAGE_dnsmasq_full_tftp=y
CONFIG_PACKAGE_f2fs-tools=y
CONFIG_PACKAGE_htop=m
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_ip6tables-nft=y
CONFIG_PACKAGE_iperf3=y
CONFIG_PACKAGE_iptables-mod-ipopt=y
CONFIG_PACKAGE_iptables-nft=y
CONFIG_PACKAGE_irqbalance=m
CONFIG_PACKAGE_kmod-asn1-decoder=y
CONFIG_PACKAGE_kmod-crypto-crc32=y
CONFIG_PACKAGE_kmod-crypto-ecb=y
CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y
CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y
CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y
CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y
CONFIG_PACKAGE_kmod-crypto-md4=y
CONFIG_PACKAGE_kmod-cryptodev=y
CONFIG_PACKAGE_kmod-fs-exfat=y
CONFIG_PACKAGE_kmod-fs-ext4=y
CONFIG_PACKAGE_kmod-fs-f2fs=y
CONFIG_PACKAGE_kmod-fs-ksmbd=y
CONFIG_PACKAGE_kmod-fs-ntfs3=y
CONFIG_PACKAGE_kmod-fs-smbfs-common=y
CONFIG_PACKAGE_kmod-fs-vfat=y
CONFIG_PACKAGE_kmod-ifb=y
CONFIG_PACKAGE_kmod-ip6tables=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-ipopt=y
CONFIG_PACKAGE_kmod-lib-crc16=y
CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-ipt6=y
CONFIG_PACKAGE_kmod-nft-compat=y
CONFIG_PACKAGE_kmod-nls-cp437=y
CONFIG_PACKAGE_kmod-nls-iso8859-1=y
CONFIG_PACKAGE_kmod-nls-utf8=y
CONFIG_PACKAGE_kmod-oid-registry=y
# CONFIG_PACKAGE_kmod-ppp is not set
CONFIG_PACKAGE_kmod-rtl8192c-common=y
CONFIG_PACKAGE_kmod-rtl8192cu=y
CONFIG_PACKAGE_kmod-rtlwifi=y
CONFIG_PACKAGE_kmod-rtlwifi-usb=y
CONFIG_PACKAGE_kmod-sched-cake=y
CONFIG_PACKAGE_kmod-sched-core=y
CONFIG_PACKAGE_kmod-scsi-core=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_kmod-udptunnel4=y
CONFIG_PACKAGE_kmod-udptunnel6=y
CONFIG_PACKAGE_kmod-usb-storage=y
CONFIG_PACKAGE_kmod-wireguard=y
CONFIG_PACKAGE_ksmbd-avahi-service=y
CONFIG_PACKAGE_ksmbd-server=y
CONFIG_PACKAGE_libatomic=y
CONFIG_PACKAGE_libavahi-dbus-support=y
CONFIG_PACKAGE_libbpf=y
CONFIG_PACKAGE_libcap-ng=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libdaemon=y
CONFIG_PACKAGE_libdbus=y
CONFIG_PACKAGE_libelf=y
CONFIG_PACKAGE_libevdev=y
CONFIG_PACKAGE_libexpat=y
CONFIG_PACKAGE_libgd=y
CONFIG_PACKAGE_libgmp=y
CONFIG_PACKAGE_libiperf3=y
CONFIG_PACKAGE_libiptext=y
CONFIG_PACKAGE_libiptext-nft=y
CONFIG_PACKAGE_libiptext6=y
CONFIG_PACKAGE_libjpeg-turbo=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_liblz4=y
CONFIG_PACKAGE_liblzo=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnetfilter-conntrack=y
CONFIG_PACKAGE_libnettle=y
CONFIG_PACKAGE_libnfnetlink=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libnl-core=y
CONFIG_PACKAGE_libnl-genl=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_libopenssl-devcrypto=y
CONFIG_PACKAGE_libopenssl-legacy=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_libpng=y
CONFIG_PACKAGE_libsensors=y
CONFIG_PACKAGE_libsqlite3=y
CONFIG_PACKAGE_libsysfs=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libudev-zero=y
CONFIG_PACKAGE_libusb-1.0=y
CONFIG_PACKAGE_libwebp=y
CONFIG_PACKAGE_libxtables=y
CONFIG_PACKAGE_lm-sensors=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_luci-app-adblock=y
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-irqbalance=m
CONFIG_PACKAGE_luci-app-ksmbd=y
CONFIG_PACKAGE_luci-app-openvpn=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-app-pbr=y
CONFIG_PACKAGE_luci-app-sqm=y
CONFIG_PACKAGE_luci-app-vnstat2=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-lua-runtime=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-wireguard=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
# CONFIG_PACKAGE_odhcp6c is not set
# CONFIG_PACKAGE_odhcpd-ipv6only is not set
CONFIG_PACKAGE_openssl-util=y
CONFIG_PACKAGE_openvpn-openssl=y
CONFIG_PACKAGE_pbr=y
# CONFIG_PACKAGE_ppp is not set
CONFIG_PACKAGE_resolveip=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-ucode=y
CONFIG_PACKAGE_rtl8192cu-firmware=y
CONFIG_PACKAGE_sqm-scripts=y
CONFIG_PACKAGE_sysfsutils=y
CONFIG_PACKAGE_tc-tiny=y
CONFIG_PACKAGE_tcpdump-mini=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_ucode-mod-html=y
CONFIG_PACKAGE_ucode-mod-lua=y
CONFIG_PACKAGE_ucode-mod-math=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhubctl=y
CONFIG_PACKAGE_usbutils=y
CONFIG_PACKAGE_vnstat2=y
CONFIG_PACKAGE_vnstati2=y
CONFIG_PACKAGE_wireguard-tools=y
# CONFIG_PACKAGE_wpad-basic-mbedtls is not set
CONFIG_PACKAGE_wpad-basic-openssl=y
CONFIG_PACKAGE_wsdd2=y
CONFIG_PACKAGE_xtables-nft=y
CONFIG_PACKAGE_zlib=y
# CONFIG_PER_FEED_REPO is not set
CONFIG_SQLITE3_COLUMN_METADATA=y
CONFIG_SQLITE3_DYNAMIC_EXTENSIONS=y
CONFIG_SQLITE3_FTS3=y
CONFIG_SQLITE3_FTS4=y
CONFIG_SQLITE3_FTS5=y
CONFIG_SQLITE3_RTREE=y
CONFIG_STRIP_KERNEL_EXPORTS=y
CONFIG_TARGET_OPTIONS=y
CONFIG_TESTING_KERNEL=y
CONFIG_VERSIONOPT=y
CONFIG_VERSION_BUG_URL=""
CONFIG_VERSION_CODE=""
CONFIG_VERSION_CODE_FILENAMES=y
CONFIG_VERSION_DIST="SmartWRT"
CONFIG_VERSION_FILENAMES=y
CONFIG_VERSION_HOME_URL=""
CONFIG_VERSION_HWREV=""
CONFIG_VERSION_MANUFACTURER=""
CONFIG_VERSION_MANUFACTURER_URL=""
CONFIG_VERSION_NUMBER=""
CONFIG_VERSION_PRODUCT=""
CONFIG_VERSION_REPO=""
CONFIG_VERSION_SUPPORT_URL=""
# CONFIG_PACKAGE_dnsmasq_full_dhcpv6 is not set
# CONFIG_PACKAGE_kmod-crypto-kpp is not set
CONFIG_PACKAGE_kmod-lib-crc-ccitt=y
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Please repeat your problem with openwrt or report issue to your unsupported fork.
> CONFIG_VERSION_DIST="SmartWRT"

**Comment by pesa1234** [comment]
> Please repeat your problem with openwrt or report issue to your unsupported fork.
> 
> > CONFIG_VERSION_DIST="SmartWRT"

I changed only the name, openWRT have same issue

**Comment by brada4** [comment]
Message says STA actively acknowledged inactivity probe frame.

**Comment by pesa1234** [comment]
> Message says STA actively acknowledged inactivity probe frame.

The device is not present at home.
I see it on associated station list.

`Wed Jan 17 16:41:35 2024 daemon.notice hostapd: phy0-ap0: AP-STA-POLL-OK ac:1e:9e:xx:aa:09`

`iw dev phy0-ap0 station dump`
`Station ac:1e:9e:xx:aa:09 (on phy0-ap0)
	inactive time:	112390 ms
	rx bytes:	7670
	rx packets:	19
	tx bytes:	9423
	tx packets:	76
	tx retries:	119
	tx failed:	131
	rx drop misc:	2
	signal:  	-83 [-102, -85, -88, -89] dBm
	signal avg:	-81 [-102, -85, -87, -85] dBm
	tx bitrate:	13.0 MBit/s MCS 1
	tx duration:	592403 us
	rx bitrate:	6.5 MBit/s MCS 0
	rx duration:	28559 us
	last ack signal:-24 dBm
	avg ack signal:	-21 dBm
	airtime weight: 256
	authorized:	yes
	authenticated:	yes
	associated:	yes
	preamble:	short
	WMM/WME:	yes
	MFP:		no
	TDLS peer:	no
	DTIM period:	2
	beacon interval:100
	short preamble:	yes
	connected time:	2663 seconds
	associated at [boottime]:	6243.234s
	associated at:	1705503544351 ms
	current time:	1705506208060 ms`

**Comment by brada4** [comment]
It is 200-250m/yd apart in open air.
Add a checkbox in luci to disassociate on low ack.

**Comment by pesa1234** [comment]
> It is 200-250m/yd apart in open air. Add a checkbox in luci to disassociate on low ack.

It was already checked
![immagine](https://github.com/openwrt/openwrt/assets/6216993/d0ab7cd4-8c90-4804-9217-2266ea2c4c2f)
It is at 10km from my house...

**Comment by brada4** [comment]
Set up monitor station. hostapd saw xiaomi responding 11 seconds ago. 10km cannot happen with normal wlan ack window, no matter antennas.

**Comment by pesa1234** [comment]
> Set up monitor station. hostapd saw xiaomi responding 11 seconds ago. 10km cannot happen with normal wlan ack window, no matter antennas.

Im my opinion there's a bug, after a lost connection seems that not clean associated station...

**Comment by brada4** [comment]
And close theis¡ue as undisclosed fork diff is at fault.

**Comment by pesa1234** [comment]
> And close theis¡ue as undisclosed fork diff is at fault.

Let me check some more days.
The problem seems disappear if I remove:
from `etc/config/wireless` `option noscan '1' ` from radio 2,4ghz
and
from `etc/modules.conf` `options mt7915e wed_enable=Y` on 5ghz

**Comment by brada4** [comment]
None of those can beam wifi ack frame from other place.

**Comment by pesa1234** [comment]
> > And close theis¡ue as undisclosed fork diff is at fault.
> 
> No difference...
> 
> Let me check some more days. The problem seems disappear if I remove: from `etc/config/wireless` `option noscan '1' ` from radio 2,4ghz and from `etc/modules.conf` `options mt7915e wed_enable=Y` on 5ghz



> None of those can beam wifi ack frame from other place.

It is more than 12 hours that by removing that options the problem disappear... Somebody have some suggestion to do some check?

**Comment by brada4** [comment]
Start with clean OpenWRT and figure out exact configuration change that causes adverse behaviour. Mentioning commit reverted and random parameters being rolled back does not reduce search space for culprit.

**Comment by pesa1234** [comment]
> Start with clean OpenWRT and figure out exact configuration change that causes adverse behaviour. Mentioning commit reverted and random parameters being rolled back does not reduce search space for culprit.

I'm sorry you don't think I have a clean openWRT.
Yesterday I had tried removing some latest commits because previously I didn't found that log messages, but without success, I went back to a clean solution.
After that by looking backup history I see that in the beginning I didn't set the option no scan and WED.
Do you want me to post the diffconfig?

After that I try to remove that two settings and after 24 hours without option noscan and WED all is ok.

Thanks

**Comment by brada4** [comment]
There should be no diffconfig or commit whatsoever. Blank image, start AP, connect xiaomi, walk it away. Add 1 of your changes, try again.

**Comment by brada4** [comment]
Does it happen with mbedtls hostapd too? Like v23 completely default....

**Comment by pesa1234** [comment]
I will investigate...

**Comment by brada4** [comment]
You need cable, just in case. The procedure is to remove one wpad, add another, you can do that easiest in firmware-selector.

**Comment by pesa1234** [comment]
@brada4 What do you think if I test now with this: https://github.com/openwrt/openwrt/commit/a28cedbdab96be9bee39bb70098a1508c0252a8a ?

Thanks

**Comment by brada4** [comment]
Seems rather indifferent. 3d5890e2cab3 applies only to non-default fw4 hardware offload, others are certain improvements in generic conditions.

**Comment by pesa1234** [comment]
Let me test more, but seems disappear with latest commit by @nbd168 
```
Fri Jan 19 17:54:08 2024 daemon.notice hostapd: phy0-ap0: AP-STA-CONNECTED 90:de:80:xx:yy:71 auth_alg=open
Fri Jan 19 17:59:26 2024 daemon.notice hostapd: phy0-ap0: AP-STA-DISCONNECTED 90:de:80:xx:yy:71
```

**Comment by pesa1234** [comment]
> Can you check current releases if backport is needed just in case?

Other guys confirm that is present also on snapshot with kernel 5.15, our MT6000 is not released as stable right now so I think backport don't need...

**Comment by pesa1234** [comment]
So, after some days on testing with latest commit on wifi all is ok, that message disappear, so, I close the issue.

**Comment by brada4** [comment]
Luckily short-lived inter-release glitch.

**Comment by pesa1234** [comment]
Yes, thanks, so I hope that I didn't bother the community.

**Comment by termomaks** [comment]
@pesa1234 
I know this issue is closed now but I see a lot of 
`daemon.notice hostapd: phy1-ap0: AP-STA-POLL-OK`
entries in system log.
These were pointed out [here on the forum](https://forum.openwrt.org/t/ipq807x-nss-build/148529/2133?u=sppmaster).
My build is with all today's commits.

**Comment by sppmasterspp** [comment]
> Yes, thanks, so I hope that I didn't bother the community.

@pesa1234
I know this issue is closed now but I see a lot of
daemon.notice hostapd: phy1-ap0: AP-STA-POLL-OK
entries in system log.
These were pointed out [here on the forum](https://forum.openwrt.org/t/ipq807x-nss-build/148529/2133?u=sppmaster).
My build is with all today's commits.
