### ISSUE TITLE
[wiki] Move `LXC in OpenWrt` to virtualization docs

### ISSUE THREAD

**Issue by filimonic** [openwrt/openwrt#14421]
### Describe the bug

Move `https://openwrt.org/lxc_openwrt_host` to `https://openwrt.org/docs/guide-user/virtualization/`

**Comment by musashino205** [comment]
This is not a bug of OpenWrt firmware, please post to the Forum.

**Comment by filimonic** [comment]
Created forum post here https://forum.openwrt.org/t/move-lxc-in-openwrt-to-virtualization-docs/185961?u=filimonic
