### ISSUE TITLE
Incorrect opkg flags in rootfs image

### ISSUE THREAD

**Issue by jck112** [openwrt/openwrt#14427]
### Describe the bug

When creating the rootfs image, the default packages are installed using `opkg` which [adds](https://github.com/openwrt/opkg-lede/blob/d038e5b6d155784575f62a66a8bb7e874173e92e/libopkg/opkg_install.c#L1198) the `user` flag for most packages[^1].

The `user` flag  should only be applied to packages have been installed by the user and thus should not be applied to the default packages that are part of the system.

For example here are the initial package flags (truncated) from a new SNAPSHOT image on a NanoPi R4S:
```
root@OpenWrt:~# opkg status | awk '/Package:|Status:|^$/1'
Package: libc
Status: install hold installed

Package: mkf2fs
Status: install user installed

Package: opkg
Status: install user installed
...
Package: ppp-mod-pppoe
Status: install user installed
```

[^1]: Packages, like `libc`, which [specify flags](https://github.com/openwrt/openwrt/blob/90644fb2d004112c3d877abd94cd5528d7587ee1/package/libs/toolchain/Makefile#L15), like `hold`, do not get the `user` flag added by default.

### OpenWrt version

r24855-3891355015

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

rockchip/armv8

### Device

FriendlyElec NanoPi R4S

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
But they are installed via opkg, unlike libc or kernel meta.

**Comment by jck112** [comment]
All packages (including `libc` and `kernel`) are [installed](https://github.com/openwrt/openwrt/blob/90644fb2d004112c3d877abd94cd5528d7587ee1/package/Makefile#L72) by the host using `opkg`.

Some packages, such as `libc`, specify `PKG_FLAGS` which are written into the package's "control" metadata embedded in its ipk file. Due to a quirk in `opkg` the `user` flag is not applied to these packages on install.

The `user` flag is intended to be automatically applied by `opkg` to all packages installed by the user. This makes it easy for users to differentiate what packages were installed as part of the system or as dependencies for other packages.

Thus I don't believe it is correct for the packages installed as part of the image build to have the `user` flag applied.
