### ISSUE TITLE
r8000 - Packages for block-mount found, but incompatible with the architectures configured

### ISSUE THREAD

**Issue by Mile-Lile** [openwrt/openwrt#14494]
### Describe the bug

root@R8000:~# opkg install block-mount
Unknown package 'block-mount'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libubox20240126 for block-mount
 * pkg_hash_check_unresolved: cannot find dependency libblobmsg-json20240126 for block-mount
 * pkg_hash_fetch_best_installation_candidate: Packages for block-mount found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package block-mount.

### OpenWrt version

r24913-7441c2bef6

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

bcm53xx/generic

### Device

Netgear R8000 (BCM4709)

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Run opkg update again soon Probably mirror is not synced up with latest snapshot.

**Comment by Mile-Lile** [comment]
@brada4 
Thak you for reply. I did what you suggested (tried a couple of times) but I got same message again...
Even if I try to build with luci-app-attendedsysupgrade I get similar message:
![Screenshot_select-area_20240128101233](https://github.com/openwrt/openwrt/assets/12752816/457ef4fa-4031-4535-b396-4c12ab647c0c)
is there I something I could do to provide more info to you?

**Comment by brada4** [comment]
Mirrors are still not in sync. You can check directly here for ubox20240126 
https://downloads.openwrt.org/snapshots/packages/arm_cortex-a9/base/
Enough of crossposting random screenshots. It will resolve by itself with time.
