### ISSUE TITLE
how to add support for xiaomi redmi router ax6s in openwrt21.02?

### ISSUE THREAD

**Issue by hpx502766238** [openwrt/openwrt#14506]
### Describe the bug

,I want to compile a firmware with the “MTK closed source driver”  to get stable performance and newer feature.I need version 21.02 because the mtk-openwrt-feeds only support openwrt21.02,but when I type make menuconfig,there is no target profile for “xiaomi redmi router ax6s".

### OpenWrt version

21.02

### OpenWrt release

21.02

### OpenWrt target/subtarget

MediaTek Ralink ARM/MT7622

### Device

Xiaomi Redmi AX6S

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by hpx502766238** [comment]
mtk-openwrt-feeds:
https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/

**Comment by jow-** [comment]
Not supported by OpenWrt.
