### ISSUE TITLE
qualcommax/ipq807x/ax9000: No Upstream network

### ISSUE THREAD

**Issue by Soromeister** [openwrt/openwrt#14513]
### Describe the bug

There is no Upstream link for the network, basically, both `wan` and `wan6` interfaces are not getting an IP.

This was working for build `r24909-65f599223d`, but somehow broke after this build.

### OpenWrt version

r24939-0b498c3c3f

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Xiaomi AX9000

### Image kind

Official downloaded image

### Steps to reproduce

Simply upgrading to a version higher than `r24909-65f599223d` will have no upstream IP.

### Actual behaviour

No upstream IP (neither `wan` nor `wan6` interfaces get IP).

### Expected behaviour

Upstream IP should be assigned (Both `wan` and `wan6` interfaces should get IP address).

### Additional info

[config.txt](https://github.com/openwrt/openwrt/files/14097532/config.txt)
[kernel.log](https://github.com/openwrt/openwrt/files/14097536/kernel.log)
[system.log](https://github.com/openwrt/openwrt/files/14097538/system.log)

### Diffconfig

```text
-ash: ./scripts/diffconfig.sh: not found
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by yyyzz123** [comment]
There has a fix about it.
https://github.com/openwrt/openwrt/pull/14500

**Comment by Ansuel** [comment]
Fix merged.

**Comment by Soromeister** [comment]
Confirmed it's working. Thanks for fixing.
