### ISSUE TITLE
openwrt.org dokuwiki error / down

### ISSUE THREAD

**Issue by stefanfoulis** [openwrt/openwrt#14576]
### Describe the bug

`openwrt.org/toh/start` and many other locations are showing an error.

```
[Wiki is down: Error: Call to undefined method syntax_plugin_data_table::_buildSQL()](https://forum.openwrt.org/t/wiki-is-down-error-call-to-undefined-method-syntax-plugin-data-table-buildsql/187185)
```

I followed the link for reporting infrastructure errors at https://openwrt.org/wiki/start#contact and ended up on this bug-tracker. I'm not sure this really is the right place to report it, but it since the contact page linked me here :man_shrugging: .
I couldn't find an issue reported here yet, so I created a new one.

There are already some forum posts reporting the issue:

- https://forum.openwrt.org/t/wiki-is-down-error-call-to-undefined-method-syntax-plugin-data-table-buildsql/187185
- https://forum.openwrt.org/t/issues-on-the-main-site-today/187215

**Comment by Snowiiii** [comment]
i get the same error

**Comment by kazin-kharizma** [comment]
I am getting this error as well and its coming at a really bad time.

**Comment by udanfacy22** [comment]
> I am getting this error as well and its coming at a really bad time.

For the time being, until this gets fixed, I suggest using the Internet Wayback Machine to access recent copies of the information on the website. https://web.archive.org/web/20240207025448/https://openwrt.org/

**Comment by stintel** [comment]
Please don't report site issues here. Either report it to the openwrt-adm list or #openwrt-adm on IRC.

**Comment by stefanfoulis** [comment]
thanks for the hint @stintel. It would make sense to update the information at https://openwrt.org/wiki/start#contact then, because there it states that infrastructure outages should be reported here (it links to bugs.openwrt.org, which redirects here).
![image](https://github.com/openwrt/openwrt/assets/14330/b612efee-c563-41bb-a19d-3a6309076f73)
