### ISSUE TITLE
qualcommax/ipq807x/QNAP 301w: LEDs not working, not properly ordered

### ISSUE THREAD

**Issue by sppmasterspp** [openwrt/openwrt#14628]
### Describe the bug

Updating to the latest snapshot (compared to the 2 weeks older build) with sysupgrade keeping the settings leads to LEDs no longer working after sysupgrade.
These can be seen in kernel log

```
[    4.246494] leds-gpio leds: Led green: renamed to green:_1 due to name collision
[    4.248978] leds-gpio leds: Led green: renamed to green:_2 due to name collision
[    4.256345] leds-gpio leds: Led green: renamed to green:_3 due to name collision
[    4.263770] leds-gpio leds: Led green: renamed to green:_4 due to name collision
[    4.271105] leds-gpio leds: Led amber: renamed to amber:_1 due to name collision
[    4.278487] leds-gpio leds: Led green: renamed to green:_5 due to name collision
[    4.285856] leds-gpio leds: Led amber: renamed to amber:_2 due to name collision
[    4.293257] leds-gpio leds: Led green: renamed to green:_6 due to name collision
[    4.300616] leds-gpio leds: Led amber: renamed to amber:_3 due to name collision
[    4.308002] leds-gpio leds: Led green: renamed to green:_7 due to name collision
[    4.315384] leds-gpio leds: Led amber: renamed to amber:_4 due to name collision
[    4.322760] leds-gpio leds: Led green: renamed to green:_8 due to name collision
[    4.330135] leds-gpio leds: Led amber: renamed to amber:_5 due to name collision
```

I played a bit with the LEDs configuration and it seems that LED names were changed (as stated in kernel log due to name collision) and that was the reason they didn't work. I didn't try to reset all settings to deafault to see if they would work without playing with their settings.
Now they are a bit stirred. But switching between the numbers I've found this order of all 9 green coloured LEDs.
I didn't play with amber coloured ones.

![91257b986da805ad2845b2c1e3d199bd5024613b](https://github.com/openwrt/openwrt/assets/46223847/49fc87c2-7d45-4de1-9895-e8b73337b36f)

Previously the device names matched the LED names.

### OpenWrt version

r25275+3-1128290dbf

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

QNAP 301w

### Image kind

Self-built image

### Steps to reproduce

Usual sysupgrade from older snapshot to the latest one keeping the settings.

### Expected behaviour

All the LEDs should work and have names matching device names. This was the case before the latest LED changes for qualcommax.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by musashino205** [comment]
It seems to be due to the lack of ```function``` property in the LED nodes in the dts.

2e659930d3f3e131b28879447d61faf58cf8add7 removes ```label``` property, but b7a7a793b140175cd02a863412b5464cad2269fc didn't add ```function``` property for 301W. Then, there are multiple ```green:```/```red:```/```amber:``` LEDs.

CC: @Ansuel

**Comment by l33tlinuxh4x0r** [comment]
Can confirm that this is a bug on the clean snapshot builds form firmware-selector.openwrt.org

**Comment by termomaks** [comment]
> Can confirm that this is a bug on the clean snapshot builds form firmware-selector.openwrt.org

Let's hope @Ansuel will be able to fix it soon.

**Comment by sppmasterspp** [comment]
> Can confirm that this is a bug on the clean snapshot builds form firmware-selector.openwrt.org

Let's hope @Ansuel will be able to fix it soon.

**Comment by termomaks** [comment]
@Ansuel or @robimarko 
If you have time, can you look at this bug, please.
Thanks.

**Comment by musashino205** [comment]
Can someone test this attached firmware that contains fixes for this issue?
Note: If you use initramfs image, you can test without flashing to NAND.

[openwrt-qualcommax-ipq807x-qnap_301w_ledfix.zip](https://github.com/openwrt/openwrt/files/14623341/openwrt-qualcommax-ipq807x-qnap_301w_ledfix.zip)

**Comment by termomaks** [comment]
I'll try it once the router is idle.
Maybe @l33tlinuxh4x0r can do it earlier than me.
Thanks a lot.

**Comment by sppmasterspp** [comment]
> Can someone test this attached firmware that contains fixes for this issue?
> Note: If you use initramfs image, you can test without flashing to NAND.

I'll try it once the router is idle.
Maybe @l33tlinuxh4x0r can do it earlier than me.
Thanks a lot.

**Comment by sppmasterspp** [comment]
> Can someone test this attached firmware that contains fixes for this issue?
> Note: If you use initramfs image, you can test without flashing to NAND.

I've tested your image and it works OK.
![image](https://github.com/openwrt/openwrt/assets/46223847/d1908bd8-f753-4276-9e29-550aac521cee)

Thanks a lot.

**Comment by robimarko** [comment]
Should be fixed via:
https://github.com/openwrt/openwrt/pull/14910
