### ISSUE TITLE
kexec-tools fails to build with binutils-2.42

### ISSUE THREAD

**Issue by oskarirauta** [openwrt/openwrt#14621]
### Describe the bug

Patch already exists for binutils-2.41 but doesn't apply cleanly;
I made changes by hand and it fixes the build.

Patch is available here: https://www.mail-archive.com/kexec@lists.infradead.org/msg32771.html

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ptpt52** [comment]
same issue.
