### ISSUE TITLE
The 40 MHz mode does not work at 2.4 GHz (GL-INET MT6000)

### ISSUE THREAD

**Issue by Mummify1867** [openwrt/openwrt#14626]
### Describe the bug

Devices are not connecting at the 40 MHz frequency in WiFi 2.4 GHz

### OpenWrt version

r25142-a42075435a

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

GL.iNet GL-MT6000

### Image kind

Official downloaded image

### Steps to reproduce

Configure the 40 MHz mode on the Operating Frequency option on WiFi 2.4 GHz

### Actual behaviour

Devices will connect at a frequency of 20 MHz

### Expected behaviour

Devices will connect at a frequency of 40 MHz

### Additional info

This occurs in all connected devices, whether smartphones or PCs

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
Did you force 40MHz operation?

![image](https://github.com/openwrt/openwrt/assets/2528802/bea726cd-be80-43fa-bd28-ace75078eae1)

**Comment by Mummify1867** [comment]
> Did you force 40MHz operation?
> 
> ![image](https://private-user-images.githubusercontent.com/2528802/304567462-bea726cd-be80-43fa-bd28-ace75078eae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NjQ5ODMsIm5iZiI6MTcwNzg2NDY4MywicGF0aCI6Ii8yNTI4ODAyLzMwNDU2NzQ2Mi1iZWE3MjZjZC1iZTgwLTQzZmEtYmQyOC1hY2U3NTA3OGVhZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMjI1MTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY1NTc0MmU2NzNjNzQ4NDMzNmRlM2FhOTc3MzA5MzU4MmM2NjQwMDk1YjNmMGUyYzYwN2M2ODU3MWIzZDg1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FYaiJNnONLI_5j0xHCofvRupyjGQd3C_CBqErq86OaY)

Use forcing 40 MHz worked. Thanks for the support and sorry, I did not observe this option in OpenWRT settings.
