### ISSUE TITLE
Cannot build Mikrotik RB912 images with Imagebuilder

### ISSUE THREAD

**Issue by pavel-kamaev** [openwrt/openwrt#14714]
### Describe the bug

Imagebuilder fails to build an image with the following error:
```
Unknown package 'yafut'.
...
Collected errors:
 * opkg_install_cmd: Cannot install package yafut.
```

### OpenWrt version

r23630-842932a63d

### OpenWrt release

23.05.2

### OpenWrt target/subtarget

ath79/mikrotik

### Device

MikroTik RouterBOARD 912UAG-2HPnD

### Image kind

Official downloaded image

### Steps to reproduce

```
tar xJf openwrt-imagebuilder-23.05.2-ath79-mikrotik.Linux-x86_64.tar.xz
cd openwrt-imagebuilder-23.05.2-ath79-mikrotik.Linux-x86_64/
make image PROFILE="mikrotik_routerboard-912uag-2hpnd"
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by zekica** [comment]
A workaround for now can be manually building an image for one of these targets from source as it produces the yafut package. Putting it in the packages folder makes imagebuilder work.

**Comment by artmaluk** [comment]
> A workaround for now can be manually building an image for one of these targets from source as it produces the yafut package. Putting it in the packages folder makes imagebuilder work.

Hello. what to do if you create the firmware on https://firmware-selector.openwrt.org? same error
