### ISSUE TITLE
Offlining a core on ipq806x you are unable to bring the core back online

### ISSUE THREAD

**Issue by GXTX** [openwrt/openwrt#14760]
### Describe the bug

After offlining a core on ipq806x you are unable to bring the core back online.

### OpenWrt version

r23711+66-cdc907abed

### OpenWrt release

23.05-SNAPSHOT

### OpenWrt target/subtarget

ipq806x/generic

### Device

R7800

### Image kind

Self-built image

### Steps to reproduce

echo 0 > /sys/devices/system/cpu/cpu1/online
echo 1 > /sys/devices/system/cpu/cpu1/online

### Actual behaviour

```
root@R7800:~# echo 0 > /sys/devices/system/cpu/cpu1/online <-- successfully takes core offline
root@R7800:~# echo 1 > /sys/devices/system/cpu/cpu1/online
ash: write error: I/O error
```

dmesg:
```[261430.588864] CPU1: failed to come online```

### Diffconfig

[diffconfig.txt](https://github.com/openwrt/openwrt/files/14467194/diffconfig.txt)

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Please add diffconfig and describe +66 patches you have in source tree.

**Comment by robimarko** [comment]
Can I ask why are you even trying to do this?

**Comment by GXTX** [comment]
> Can I ask why are you even trying to do this?

It's a feature of Linux (and Windows for that matter), and was just playing around with it. Ideally a Linux based OS should support it. It could also have some real world uses for low power requirements -- by disabling cores during known hours of inactivity.

> describe +66 patches you have in source tree

Enabled NSS cores using community patches from forum.

**Comment by brada4** [comment]
None of your postings explain how non-default cpu hotplug control option suddenly enabled itself.

**Comment by GXTX** [comment]
Thanks!

Made me go and check my colo'ed box, and indeed there appears to be a kernel config for it.
```
CONFIG_HOTPLUG_CPU=y
```

I suppose I was so used to distros just having this enabled by default.
Will close and might report back if I decide to recompile with that enabled.
