### ISSUE TITLE
`sysupgrade -b -` does not work anymore

### ISSUE THREAD

**Issue by rany2** [openwrt/openwrt#14773]
### Describe the bug

It simply creates a file called `-` instead of printing to stdout, this broke my backup scripts.

### OpenWrt version

336a531c15e7fa5f8a42a7b9f2662c249aafce89

### OpenWrt release

336a531c15e7fa5f8a42a7b9f2662c249aafce89

### OpenWrt target/subtarget

N/A

### Device

N/A

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by rany2** [comment]
@rmilecki I've taken a look and I think this commit is to blame, I've linked the line in specific: https://github.com/openwrt/openwrt/commit/e36cc530927c4294c1510d7cdf89f0b9739e6cde#diff-cc3419ad054e045f4f6a07d3b634c844190512ef3779d61f5f188ca5fc439f5eR266

**Comment by csharper2005** [comment]
SNAPSHOT: "Generate archive" action in Luci produces zero length backup.tar.gz. @rany2 Is this the same problem?

**Comment by rany2** [comment]
@csharper2005 Yep, Luci calls cgi-backup which also pipes to stdout: https://github.com/openwrt/cgi-io/blob/901b0f0463c9d16a8cf5b9ed37118d8484bc9176/main.c#L652-L653

**Comment by tones111** [comment]
@jow- 
I manually applied the changes to my r25381 snapshot and I'm able to generate backups now.  Thanks for the quick fix!
