### ISSUE TITLE
wireguard peer update does not work

### ISSUE THREAD

**Issue by js290** [openwrt/openwrt#14849]
### Describe the bug

Updating the peer IP address does not take.  The edit dialogue shows it's been changed, but when the interface is restarted, the old peer IP is used.  On reboot, the old config is restored.

### OpenWrt version

r23497-6637af95aa

### OpenWrt release

23.05.0

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link TL-WR1043ND v3

### Image kind

Official downloaded image

### Steps to reproduce

* Network -> Interfaces -> my_wg_int -> Edit peer and update `Endpoint Host`.  
* Save -> Save -> Restart

### Actual behaviour

* Check Wireguard status and notice it's still trying to connect to old peer IP
* Reboot and notice Wireguard has reverted configs back to old peer IP

### Expected behaviour

* Wireguard should be using the new peer IP
* Wireguard should save the new peer IP on reboot.

### Additional info
According to [WR1043ND doc](https://openwrt.org/toh/TP-Link/tl-wr1043nd), `V3` hardware is supported by `23.05.0` not the newer `23.05.5`.
_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
23.05.2 iis ok
your rootfs is full, you need to reinstall anyway. Tip - auc.

**Comment by jow-** [comment]
Rootfs is full, nothing to fix on our end.
