### ISSUE TITLE
src/gn/command_meta.o编译报错

### ISSUE THREAD

**Issue by jmmes** [openwrt/openwrt#14864]
### Describe the bug

Applying /home/lede/openwrt/feeds/PWpackages/gn/patches/010-gcc.patch using plaintext: 
(Stripping trailing CRs from patch; use --binary to disable.)
patching file build/gen.py
Hunk #1 succeeded at 378 (offset 10 lines).
touch /home/lede/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.prepared1784fd9f4996728c6649589e075d282d_6664517399ebbbc92a37c5bb081b5c53
python3 /home/lede/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/build/gen.py --no-last-commit-position
touch /home/lede/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.configured
MAKEFLAGS="" /home/lede/openwrt/staging_dir/host/bin/ninja  -j1 -C /home/lede/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out
ninja: Entering directory `/home/lede/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out'
[60/287] CXX src/gn/command_meta.o
FAILED: src/gn/command_meta.o 
g++ -MMD -MF src/gn/command_meta.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++20 -Wno-redundant-move -c ../src/gn/command_meta.cc -o src/gn/command_meta.o
In file included from /usr/include/c++/12/string:40,
                 from ../src/base/command_line.h:20,
                 from ../src/gn/command_meta.cc:8:
In static member function 'static constexpr std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)',
    inlined from 'static constexpr void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12/bits/basic_string.h:423:21,
    inlined from 'constexpr std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12/bits/basic_string.tcc:532:22,
    inlined from 'constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12/bits/basic_string.h:2171:19,
    inlined from 'constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::insert(size_type, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12/bits/basic_string.h:1928:22,
    inlined from 'constexpr std::__cxx11::basic_string<_CharT, _Traits, _Allocator> std::operator+(const _CharT*, __cxx11::basic_string<_CharT, _Traits, _Allocator>&&) [with _CharT = char; _Traits = char_traits<char>; _Alloc = allocator<char>]' at /usr/include/c++/12/bits/basic_string.h:3541:36,
    inlined from 'int commands::RunMeta(const std::vector<std::__cxx11::basic_string<char> >&)' at ../src/gn/command_meta.cc:131:23:
/usr/include/c++/12/bits/char_traits.h:431:56: error: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' accessing 9223372036854775810 or more bytes at offsets [2, 9223372036854775807] and 1 may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:69: /home/lede/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.built] Error 1
make[3]: Leaving directory '/home/lede/openwrt/feeds/PWpackages/gn'
time: package/feeds/PWpackages/gn/host-compile#82.43#5.41#98.08
    ERROR: package/feeds/PWpackages/gn [host] failed to build.
make[2]: *** [package/Makefile:127: package/feeds/PWpackages/gn/host/compile] Error 1
make[2]: Leaving directory '/home/lede/openwrt'
make[1]: *** [package/Makefile:123: /home/lede/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lede/openwrt'
make: *** [/home/lede/openwrt/include/toplevel.mk:233: world] Error 2
编译报错，google不到答案，需要帮助！谢谢

### OpenWrt version

23.05

### OpenWrt release

23.05

### OpenWrt target/subtarget

gn

### Device

x86

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Pwpackages feed is not from here, you need to locate place where you got it from.
