### ISSUE TITLE
 v2ray-plugin Go环境出错

### ISSUE THREAD

**Issue by aayyy99** [openwrt/openwrt#14930]
### Describe the bug

尝试更新Go版本为1.22.1后，编译还是使用1.21.7，

### OpenWrt version

. /etc/openwrt_release && echo $DISTRIB_REVISION

### OpenWrt release

. /etc/openwrt_release && echo $DISTRIB_RELEASE

### OpenWrt target/subtarget

. /etc/openwrt_release && echo $DISTRIB_TARGET

### Device

AX6000

### Image kind

Official downloaded image

### Steps to reproduce

Finding targets
go: ../../go.mod requires go >= 1.22 (running go 1.21.7; GOTOOLCHAIN=local)

Building targets
go: ../../go.mod requires go >= 1.22 (running go 1.21.7; GOTOOLCHAIN=local)

make[3]: *** [Makefile:44: /home/imm/x-wrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.15.1/.built] Error 1
make[3]: Leaving directory '/home/imm/x-wrt/feeds/small/v2ray-plugin'
time: package/feeds/small/v2ray-plugin/compile#0.24#0.08#1.15
    ERROR: package/feeds/small/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:129: package/feeds/small/v2ray-plugin/compile] Error 1
make[2]: Leaving directory '/home/imm/x-wrt'
make[1]: *** [package/Makefile:123: /home/imm/x-wrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/imm/x-wrt'
make: *** [/home/imm/x-wrt/include/toplevel.mk:233：world] 错误 2
imm@imm-virtual-machine:~/x-wrt$ go version
go version go1.22.1 linux/amd64
imm@imm-virtual-machine:~/x-wrt$ which go
/snap/bin/go

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
You have to report your problem to fork, looks like https://github.com/x-wrt
