### ISSUE TITLE
Ramips Targets Are Not Building After Kernel Version 6.1

### ISSUE THREAD

**Issue by khanjui** [openwrt/openwrt#14936]
### Describe the bug

See discussion: https://github.com/openwrt/openwrt/issues/14546#issuecomment-2002074867

### OpenWrt version

r25519-7ea82bc17d

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

ramips/mt7621

### Device

Xiaomi Mi Router 4A Gigabit Edition

### Image kind

Official downloaded image

### Steps to reproduce

Latest SNAPSHOT for mt7621 is from 2024-03-12 11:22:23

### Expected behaviour

Should build after getting fixed.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
Only mt7620 compiles correctly, the remaining ones, i.e. mt7621, mt76x8, rt288x, rt305x, rt3883show compilation errors.

**Comment by predators46** [comment]
it's normal if the firmware size is too large

**Comment by namiltd** [comment]
Trying to find the cause, I locally compiled routers that show errors (e.g. tplink_re350-v1) and the local build had no errors.

**Comment by namiltd** [comment]
The issue should not be closed yet because only one subtarget, my7621, has been fixed. mt76x8, rt288x, rt305x and rt3883 still not working.

**Comment by namiltd** [comment]
I just generated a PR https://github.com/openwrt/openwrt/pull/14958 to enable building with kernel 6.1.

**Comment by hauke** [comment]
Fixed in bce7b4f8e5bc01fa29ca45db88bb55bb0d301265
