### ISSUE TITLE
restarts network and reports an error

### ISSUE THREAD

**Issue by lqh280** [openwrt/openwrt#14964]
### Describe the bug

I build openwrt myself, restarts network and reports an error shows:
![3](https://github.com/openwrt/openwrt/assets/52653521/e80ce698-6e47-44e1-8bc9-8a101d1459fb)
After creating a _wifi_ file on DIR _package/base-files/files/sbin_, even if it is empty, the network can be restarted by command:
service network restart
**or**
/etc/init.d/network restart

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r25309-c378927ef8'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r25309-c378927ef8'
DISTRIB_TAINTS='no-all'

### OpenWrt version

r25309-c378927ef8

### OpenWrt release

r25309-c378927ef8

### OpenWrt target/subtarget

x86/64

### Device

X86-64

### Image kind

Self-built image

### Steps to reproduce

service network restart
or
/etc/init.d/network restart

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Error is harmless.

Try this with /etc/init.d/network 
```diff
stop_service() {
---        /sbin/wifi down
+++        [-x /sbin/wifi ] && /sbin/wifi down
        ifdown -a
```
Ill make due PR if you confirm it works

**Comment by lqh280** [comment]
> Invalid Release reported. `r25309-c378927ef8` Is this from a clean repository?

yes, git clone from https://github.com/openwrt/openwrt

**Comment by lqh280** [comment]
**main branches no file wifi**
![2](https://github.com/openwrt/openwrt/assets/52653521/2ca81b28-6436-4098-a56e-ce946858dd2d)
**23.05 branches have file wifi**
![3](https://github.com/openwrt/openwrt/assets/52653521/a8e3bf77-861f-4c88-900f-ef63d07a8a36)

**Comment by brada4** [comment]
Space after square bracket sry

**Comment by brada4** [comment]
it is no longer a dependency of netifd, thus needs conditional guard.
https://github.com/openwrt/openwrt/tree/main/package/network/config/wifi-scripts/files/sbin

**Comment by brada4** [comment]
```
stop_service() {
---        /sbin/wifi down
+++        [ -x /sbin/wifi ] && /sbin/wifi down
        ifdown -a
```

**Comment by brada4** [comment]
It will be fixed soon, if you want message go away you can download raw and replace init.d script by proposed one (maintaining +x attribute)

https://github.com/brada4/openwrt/blob/netif-wifi/package/network/config/netifd/files/etc/init.d/network

**Comment by lqh280** [comment]
> ```diff
> stop_service() {
> ---        /sbin/wifi down
> +++        [ -x /sbin/wifi ] && /sbin/wifi down
>         ifdown -a
> ```

thanks, this code is working.
