### ISSUE TITLE
vim-full: E1187: Failed to source defaults.vim

### ISSUE THREAD

**Issue by 532910** [openwrt/openwrt#15023]
### Describe the bug

```
root@OpenWrt:/# opkg update
root@OpenWrt:/# opkg install vim-full
root@OpenWrt:/# reboot
root@OpenWrt:/# vim
E1187: Failed to source defaults.vim
Press ENTER or type command to continue
```

### OpenWrt version

r23809-234f1a2efa

### OpenWrt release

23.05.3

### OpenWrt target/subtarget

various

### Device

various

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
How comes your opkg produces no output?

**Comment by CapitalF** [comment]
> How comes your opkg produces no output?

He doesn't need to provide output. It's not relevant.

This bug is confirmed.

**Comment by brada4** [comment]
Just that the line would clearly show that issue is in ../packages and no change in this repo can correct it.

**Comment by 532910** [comment]
dup of https://github.com/openwrt/packages/issues/20203
