### ISSUE TITLE
u-boot: LZMA ERROR 1

### ISSUE THREAD

**Issue by namiltd** [openwrt/openwrt#15088]
After installing PR https://github.com/openwrt/openwrt/pull/15078, router does not boot.
It displays message like below and restarts over and over again:
```
## Booting image at bc020000 ...

   Uncompressing Kernel Image ... LZMA ERROR 1 - must RESET board to recover
```
### OpenWrt version

SNAPSHOT

### OpenWrt release

r25830-8d934c1196

### OpenWrt target/subtarget

ramips/mt7620

### Device

TP-Link Archer C5 v4

### Image kind

Self-built image

### Steps to reproduce
config.buildinfo:
```
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7620=y
CONFIG_TARGET_ramips_mt7620_DEVICE_tplink_archer-c5-v4=y
CONFIG_LINUX_6_6=y
CONFIG_PACKAGE_6in4=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_kmod-asn1-decoder=y
CONFIG_PACKAGE_kmod-crypto-geniv=y
CONFIG_PACKAGE_kmod-crypto-sha3=y
CONFIG_PACKAGE_kmod-iptunnel=y
CONFIG_PACKAGE_kmod-iptunnel4=y
CONFIG_PACKAGE_kmod-lib-textsearch=y
CONFIG_PACKAGE_kmod-mtd-rw=y
CONFIG_PACKAGE_kmod-nf-nathelper-extra=y
CONFIG_PACKAGE_kmod-sit=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-light=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-rrdns=y
CONFIG_PACKAGE_rpcd-mod-ucode=y
CONFIG_PACKAGE_ucode-mod-html=y
CONFIG_PACKAGE_ucode-mod-math=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_TESTING_KERNEL=y
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
New PR https://github.com/openwrt/openwrt/commit/0a0d89265ee474d0784f675d65685ed011cc30b3 until the problem is resolved.

**Comment by hauke** [comment]
Did the revert back to mkimage 2024.01 fix the problem?

Did this device ever boot for you with kernel 6.6? Maybe the kernel image is getting too big.

**Comment by namiltd** [comment]
The router starts with the previous version of mkimage, it stops after uploading the new one (with exactly the same configuration).

**Comment by namiltd** [comment]
The reasons are kernel size and dictionary size. After uploading the new mkimage, the kernel size increased only by 2kB but unfortunately it exceeded the limit.
dictionary size: 8388608 bytes, uncompressed size: 11866779 bytes
All I had to do was turn off one of the unused kernel modules, the size dropped by 4kB and the router started working.
This is not an update problem, the problem is kernel growth.
If the problem reoccurs, I will try to set the lzma parameters to make the dictionary size smaller.
