### ISSUE TITLE
tools/cpio fails to build

### ISSUE THREAD

**Issue by cryobry** [openwrt/openwrt#15200]
### Describe the bug

Trying to compile HEAD of 23.05 branch:

```
checking return type of major()... configure: error: cannot determine type
make[3]: *** [Makefile:19: /home/bryan/.local/bin/openwrtbuilder/src/r4s/23.05.3-src/build_dir/host/cpio-2.14/.configured] Error 1
make[3]: Leaving directory '/home/bryan/.local/bin/openwrtbuilder/src/r4s/23.05.3-src/tools/cpio'
time: tools/cpio/compile#0.78#0.80#1.49
    ERROR: tools/cpio failed to build.
make[2]: *** [tools/Makefile:226: tools/cpio/compile] Error 1
make[2]: Leaving directory '/home/bryan/.local/bin/openwrtbuilder/src/r4s/23.05.3-src'
make[1]: *** [tools/Makefile:222: /home/bryan/.local/bin/openwrtbuilder/src/r4s/23.05.3-src/staging_dir/host/stamp/.tools_compile_nyyyyyynnnyyynynyyyyyyynyyynnynyyynynnyyyyyyyyyyyyyyyyynynnyyyyyyy] Error 2
make[1]: Leaving directory '/home/bryan/.local/bin/openwrtbuilder/src/r4s/23.05.3-src'
make: *** [/home/bryan/.local/bin/openwrtbuilder/src/r4s/23.05.3-src/include/toplevel.mk:232: world] Error 2
~/bin/openwrtbuilder

```

`if test x$ac_cv_rettype_major = x ; then` is passing so $ac_cv_rettype_major must be empty during the build.

### OpenWrt version

r0+23835-9b33b74ef7

### OpenWrt release

23.05.3

### OpenWrt target/subtarget

rockchip/armv8

### Device

friendlyarm_nanopi-r4s

### Image kind

Self-built image

### Steps to reproduce

./scripts/feeds update -i -f &&
./scripts/feeds update -a -f &&
./scripts/feeds install -a -f
(I modify .config manually here)
make -j1 V=s defconfig download clean world

### Actual behaviour

cpio configure fails: checking return type of major()... configure: error: cannot determine type

### Expected behaviour

cpio builds correctly

### Additional info

Fedora 40, gcc 14.0.1

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by satmd** [comment]
This is going to be fixed in master by the following commit

```
commit 6fbe36a618566fae2d12486c0aac2a81dc6c8c48
Author: Nick Hainke <vincent@systemli.org>
Date:   Wed Jan 24 13:18:53 2024 +0100

    tools/cpio: update to 2.15

    Release Notes:
    https://lists.gnu.org/archive/html/info-gnu/2024-01/msg00006.html

    Signed-off-by: Nick Hainke <vincent@systemli.org>
```
