### ISSUE TITLE
netifd: new packet steering script slow down wan port

### ISSUE THREAD

**Issue by pesa1234** [openwrt/openwrt#15207]
### Describe the bug

The new packet steering script on Gl.Inet MT6000 slow down the wan speed on ppoe connection to 1.3gb/s
Old packet steering script no issue

### OpenWrt version

r25967-ff814d7c76

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

GL.iNet GL-MT6000

### Image kind

Self-built image

### Steps to reproduce

Enable on wan ppoe connection with link speed more than 1gb/s
Activate packet steering (new script) --> https://github.com/openwrt/openwrt/commit/a205a5734eda4604a19b6cb0f65909ef69730699

### Actual behaviour

Speedtest with new script of packet steering can not reach more than 1.3 gb/s.

![immagine](https://github.com/openwrt/openwrt/assets/6216993/7a2e1c89-c989-44cb-b799-9e7086564e72)
One core reach 100% with routing on ppoe

### Additional info

Reverting to old script and enabling it solve the slow speed WAN port.

This is what I've done for MT6000
https://github.com/openwrt/openwrt/commit/1aa1b9ad26fbb71400e7e4c57455d74f4dfc8aa6

and for luci config
https://github.com/openwrt/luci/commit/f9891ce20bf6555eecd9468cbdead42f04129298

### Diffconfig

```text
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_glinet_gl-mt6000=y
CONFIG_DEVEL=y
CONFIG_BUSYBOX_CUSTOM=y
CONFIG_BUSYBOX_CONFIG_FEATURE_CROND_SPECIAL_TIMES=y
CONFIG_BUSYBOX_CONFIG_FEATURE_SYSLOG_INFO=y
CONFIG_BUSYBOX_CONFIG_FEATURE_TOP_INTERACTIVE=y
CONFIG_BUSYBOX_CONFIG_PKILL=y
CONFIG_GNUTLS_ALPN=y
CONFIG_GNUTLS_ANON=y
CONFIG_GNUTLS_DTLS_SRTP=y
CONFIG_GNUTLS_HEARTBEAT=y
CONFIG_GNUTLS_OCSP=y
CONFIG_GNUTLS_PSK=y
CONFIG_HTOP_LMSENSORS=y
CONFIG_IPK_FILES_CHECKSUMS=y
CONFIG_KEEPALIVED_CHECKSUM_COMPAT=y
CONFIG_KEEPALIVED_FWMARK=y
CONFIG_KEEPALIVED_IP6TABLES=y
CONFIG_KEEPALIVED_IPTABLES=y
CONFIG_KEEPALIVED_LINKBEAT=y
CONFIG_KEEPALIVED_LVS=y
CONFIG_KEEPALIVED_LVS_64BIT_STATS=y
CONFIG_KEEPALIVED_LVS_SYNCD=y
CONFIG_KEEPALIVED_NFTABLES=y
CONFIG_KEEPALIVED_ROUTES=y
CONFIG_KEEPALIVED_SHA1=y
CONFIG_KEEPALIVED_VRRP=y
CONFIG_KEEPALIVED_VRRP_AUTH=y
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_MBEDTLS=y
CONFIG_LIBCURL_NGHTTP2=y
CONFIG_LIBCURL_NO_SMB="!"
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_UNIX_SOCKETS=y
CONFIG_LINUX_6_6=y
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_OPTIMIZE_SPEED=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_IDEA=y
CONFIG_OPENSSL_WITH_MDC2=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SEED=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_OPENSSL_WITH_WHIRLPOOL=y
CONFIG_OPENVPN_openssl_ENABLE_FRAGMENT=y
CONFIG_OPENVPN_openssl_ENABLE_LZ4=y
CONFIG_OPENVPN_openssl_ENABLE_LZO=y
CONFIG_OPENVPN_openssl_ENABLE_PORT_SHARE=y
CONFIG_OPENVPN_openssl_ENABLE_SMALL=y
CONFIG_PACKAGE_adblock=y
CONFIG_PACKAGE_adblock-fast=m
CONFIG_PACKAGE_attr=m
CONFIG_PACKAGE_avahi-dbus-daemon=y
CONFIG_PACKAGE_blkid=y
CONFIG_PACKAGE_btrfs-progs=m
CONFIG_PACKAGE_ca-certificates=m
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_chat=y
CONFIG_PACKAGE_collectd=y
CONFIG_PACKAGE_collectd-mod-cpu=y
CONFIG_PACKAGE_collectd-mod-exec=m
CONFIG_PACKAGE_collectd-mod-interface=y
CONFIG_PACKAGE_collectd-mod-irq=m
CONFIG_PACKAGE_collectd-mod-iwinfo=y
CONFIG_PACKAGE_collectd-mod-load=y
CONFIG_PACKAGE_collectd-mod-memory=y
CONFIG_PACKAGE_collectd-mod-network=y
CONFIG_PACKAGE_collectd-mod-openvpn=m
CONFIG_PACKAGE_collectd-mod-rrdtool=y
CONFIG_PACKAGE_collectd-mod-sensors=y
CONFIG_PACKAGE_collectd-mod-sqm=m
CONFIG_PACKAGE_collectd-mod-thermal=m
CONFIG_PACKAGE_comgt=y
CONFIG_PACKAGE_containerd=m
CONFIG_PACKAGE_coreutils=y
CONFIG_PACKAGE_coreutils-sort=y
CONFIG_PACKAGE_coreutils-stat=y
CONFIG_PACKAGE_coreutils-timeout=m
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_dbus=y
# CONFIG_PACKAGE_dnsmasq is not set
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_dnsmasq_full_auth=y
CONFIG_PACKAGE_dnsmasq_full_conntrack=y
CONFIG_PACKAGE_dnsmasq_full_dhcp=y
CONFIG_PACKAGE_dnsmasq_full_dnssec=y
CONFIG_PACKAGE_dnsmasq_full_nftset=y
CONFIG_PACKAGE_dnsmasq_full_noid=y
CONFIG_PACKAGE_dnsmasq_full_tftp=y
CONFIG_PACKAGE_dockerd=m
CONFIG_PACKAGE_f2fs-tools=y
CONFIG_PACKAGE_hd-idle=m
CONFIG_PACKAGE_htop=m
CONFIG_PACKAGE_inotifywait=m
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_ip6tables-nft=y
CONFIG_PACKAGE_iperf3=y
CONFIG_PACKAGE_iptables-mod-extra=m
CONFIG_PACKAGE_iptables-mod-ipopt=y
CONFIG_PACKAGE_iptables-mod-physdev=m
CONFIG_PACKAGE_iptables-nft=y
CONFIG_PACKAGE_ipvsadm=m
CONFIG_PACKAGE_irqbalance=y
CONFIG_PACKAGE_keepalived=m
CONFIG_PACKAGE_keepalived-sync=m
CONFIG_PACKAGE_kmod-asn1-decoder=y
CONFIG_PACKAGE_kmod-br-netfilter=m
CONFIG_PACKAGE_kmod-crypto-acompress=m
CONFIG_PACKAGE_kmod-crypto-crc32=y
CONFIG_PACKAGE_kmod-crypto-ecb=y
CONFIG_PACKAGE_kmod-crypto-geniv=y
CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y
CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y
CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y
CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y
CONFIG_PACKAGE_kmod-crypto-md4=y
CONFIG_PACKAGE_kmod-crypto-sha3=y
CONFIG_PACKAGE_kmod-cryptodev=y
CONFIG_PACKAGE_kmod-fs-btrfs=m
CONFIG_PACKAGE_kmod-fs-exfat=y
CONFIG_PACKAGE_kmod-fs-ext4=y
CONFIG_PACKAGE_kmod-fs-f2fs=y
CONFIG_PACKAGE_kmod-fs-ksmbd=y
CONFIG_PACKAGE_kmod-fs-netfs=y
CONFIG_PACKAGE_kmod-fs-ntfs3=y
CONFIG_PACKAGE_kmod-fs-smbfs-common=y
CONFIG_PACKAGE_kmod-fs-vfat=y
CONFIG_PACKAGE_kmod-ifb=y
CONFIG_PACKAGE_kmod-ip6tables=y
CONFIG_PACKAGE_kmod-ipt-conntrack=m
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-extra=m
CONFIG_PACKAGE_kmod-ipt-ipopt=y
CONFIG_PACKAGE_kmod-ipt-ipset=m
CONFIG_PACKAGE_kmod-ipt-nat=m
CONFIG_PACKAGE_kmod-ipt-nat6=m
CONFIG_PACKAGE_kmod-ipt-physdev=m
CONFIG_PACKAGE_kmod-lib-crc16=y
CONFIG_PACKAGE_kmod-lib-lzo=m
CONFIG_PACKAGE_kmod-lib-raid6=m
CONFIG_PACKAGE_kmod-lib-xor=m
CONFIG_PACKAGE_kmod-lib-zlib-deflate=m
CONFIG_PACKAGE_kmod-lib-zlib-inflate=m
CONFIG_PACKAGE_kmod-lib-zstd=m
# CONFIG_PACKAGE_kmod-libphy is not set
CONFIG_PACKAGE_kmod-macvlan=m
CONFIG_PACKAGE_kmod-mii=m
CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-ipt6=y
CONFIG_PACKAGE_kmod-nf-ipvs=m
CONFIG_PACKAGE_kmod-nf-nat6=m
CONFIG_PACKAGE_kmod-nft-compat=y
CONFIG_PACKAGE_kmod-nls-cp437=y
CONFIG_PACKAGE_kmod-nls-iso8859-1=y
CONFIG_PACKAGE_kmod-nls-ucs2-utils=y
CONFIG_PACKAGE_kmod-nls-utf8=y
CONFIG_PACKAGE_kmod-oid-registry=y
# CONFIG_PACKAGE_kmod-phy-aquantia is not set
CONFIG_PACKAGE_kmod-rtl8192c-common=y
CONFIG_PACKAGE_kmod-rtl8192cu=y
CONFIG_PACKAGE_kmod-rtlwifi=y
CONFIG_PACKAGE_kmod-rtlwifi-usb=y
CONFIG_PACKAGE_kmod-sched-cake=y
CONFIG_PACKAGE_kmod-sched-core=y
CONFIG_PACKAGE_kmod-scsi-core=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_kmod-udptunnel4=y
CONFIG_PACKAGE_kmod-udptunnel6=y
CONFIG_PACKAGE_kmod-usb-net=m
CONFIG_PACKAGE_kmod-usb-net-cdc-eem=m
CONFIG_PACKAGE_kmod-usb-net-cdc-ether=m
CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=m
CONFIG_PACKAGE_kmod-usb-net-cdc-subset=m
CONFIG_PACKAGE_kmod-usb-net-huawei-cdc-ncm=m
CONFIG_PACKAGE_kmod-usb-net-ipheth=m
CONFIG_PACKAGE_kmod-usb-net-rndis=m
CONFIG_PACKAGE_kmod-usb-storage=y
CONFIG_PACKAGE_kmod-usb-wdm=m
CONFIG_PACKAGE_kmod-veth=m
CONFIG_PACKAGE_kmod-wireguard=y
CONFIG_PACKAGE_ksmbd-avahi-service=y
CONFIG_PACKAGE_ksmbd-server=y
CONFIG_PACKAGE_libatomic=y
CONFIG_PACKAGE_libattr=m
CONFIG_PACKAGE_libavahi-client=m
CONFIG_PACKAGE_libavahi-dbus-support=y
CONFIG_PACKAGE_libbpf=y
CONFIG_PACKAGE_libbz2=m
CONFIG_PACKAGE_libcap=m
CONFIG_PACKAGE_libcap-ng=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libdaemon=y
CONFIG_PACKAGE_libdbus=y
CONFIG_PACKAGE_libelf=y
CONFIG_PACKAGE_libevdev=y
CONFIG_PACKAGE_libexif=m
CONFIG_PACKAGE_libexpat=y
CONFIG_PACKAGE_libffmpeg-audio-dec=m
CONFIG_PACKAGE_libflac=m
CONFIG_PACKAGE_libgd=y
CONFIG_PACKAGE_libgmp=y
CONFIG_PACKAGE_libgnutls=m
CONFIG_PACKAGE_libid3tag=m
CONFIG_PACKAGE_libimobiledevice=m
CONFIG_PACKAGE_libinotifytools=m
CONFIG_PACKAGE_libip4tc=m
CONFIG_PACKAGE_libip6tc=m
CONFIG_PACKAGE_libiperf3=y
CONFIG_PACKAGE_libipset=m
CONFIG_PACKAGE_libiptext=y
CONFIG_PACKAGE_libiptext-nft=y
CONFIG_PACKAGE_libiptext6=y
CONFIG_PACKAGE_libjpeg-turbo=y
CONFIG_PACKAGE_libkmod=m
CONFIG_PACKAGE_libltdl=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_liblz4=y
CONFIG_PACKAGE_liblzma=m
CONFIG_PACKAGE_liblzo=y
CONFIG_PACKAGE_libmagic=m
CONFIG_PACKAGE_libmount=m
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnetfilter-conntrack=y
CONFIG_PACKAGE_libnettle=y
CONFIG_PACKAGE_libnfnetlink=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libnl-core=y
CONFIG_PACKAGE_libnl-genl=y
CONFIG_PACKAGE_libnl-route=m
CONFIG_PACKAGE_libogg=m
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_libopenssl-devcrypto=y
CONFIG_PACKAGE_libopenssl-legacy=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_libplist=m
CONFIG_PACKAGE_libpng=y
CONFIG_PACKAGE_libpopt=m
CONFIG_PACKAGE_libqrencode=m
CONFIG_PACKAGE_libreadline=m
CONFIG_PACKAGE_librrd1=y
CONFIG_PACKAGE_libseccomp=m
CONFIG_PACKAGE_libsensors=y
CONFIG_PACKAGE_libsmartcols=m
CONFIG_PACKAGE_libsqlite3=y
CONFIG_PACKAGE_libsysfs=y
CONFIG_PACKAGE_libtasn1=m
CONFIG_PACKAGE_libtirpc=m
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libudev-zero=y
CONFIG_PACKAGE_liburing=m
CONFIG_PACKAGE_libusb-1.0=y
CONFIG_PACKAGE_libusbmuxd=m
CONFIG_PACKAGE_libvorbis=m
CONFIG_PACKAGE_libwebp=y
CONFIG_PACKAGE_libxml2=m
CONFIG_PACKAGE_libxtables=y
CONFIG_PACKAGE_lm-sensors=y
CONFIG_PACKAGE_lsblk=m
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_luci-app-adblock=y
CONFIG_PACKAGE_luci-app-adblock-fast=m
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-hd-idle=m
CONFIG_PACKAGE_luci-app-irqbalance=y
CONFIG_PACKAGE_luci-app-keepalived=m
CONFIG_PACKAGE_luci-app-ksmbd=y
CONFIG_PACKAGE_luci-app-minidlna=m
CONFIG_PACKAGE_luci-app-openvpn=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-app-pbr=y
CONFIG_PACKAGE_luci-app-samba4=m
CONFIG_PACKAGE_luci-app-sqm=y
CONFIG_PACKAGE_luci-app-statistics=y
CONFIG_PACKAGE_luci-app-upnp=m
CONFIG_PACKAGE_luci-app-vnstat2=y
CONFIG_PACKAGE_luci-app-wifischedule=m
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-lua-runtime=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-3g=y
CONFIG_PACKAGE_luci-proto-ipv6=m
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-proto-wireguard=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_minidlna=m
CONFIG_PACKAGE_miniupnpd-nftables=m
CONFIG_PACKAGE_openssl-util=y
CONFIG_PACKAGE_openvpn-openssl=y
CONFIG_PACKAGE_pbr=y
CONFIG_PACKAGE_qrencode=m
CONFIG_PACKAGE_resolveip=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-ucode=y
CONFIG_PACKAGE_rrdtool1=y
CONFIG_PACKAGE_rsync=m
CONFIG_PACKAGE_rtl8192cu-firmware=y
CONFIG_PACKAGE_runc=m
CONFIG_PACKAGE_samba4-libs=m
CONFIG_PACKAGE_samba4-server=m
CONFIG_PACKAGE_sqm-scripts=y
CONFIG_PACKAGE_sudo=m
CONFIG_PACKAGE_sysfsutils=y
CONFIG_PACKAGE_tc-tiny=y
CONFIG_PACKAGE_tcpdump-mini=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_tini=m
CONFIG_PACKAGE_ucode-mod-html=y
CONFIG_PACKAGE_ucode-mod-lua=y
CONFIG_PACKAGE_ucode-mod-math=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhubctl=y
CONFIG_PACKAGE_usbids=y
CONFIG_PACKAGE_usbmuxd=m
CONFIG_PACKAGE_usbutils=y
CONFIG_PACKAGE_vnstat2=y
CONFIG_PACKAGE_vnstati2=y
CONFIG_PACKAGE_wifischedule=m
CONFIG_PACKAGE_wireguard-tools=y
# CONFIG_PACKAGE_wpad-basic-mbedtls is not set
CONFIG_PACKAGE_wpad-basic-openssl=y
CONFIG_PACKAGE_wsdd2=y
CONFIG_PACKAGE_xtables-nft=y
CONFIG_PACKAGE_zlib=y
CONFIG_SAMBA4_SERVER_AVAHI=y
CONFIG_SAMBA4_SERVER_NETBIOS=y
CONFIG_SAMBA4_SERVER_VFS=y
CONFIG_SAMBA4_SERVER_WSDD2=y
CONFIG_SQLITE3_COLUMN_METADATA=y
CONFIG_SQLITE3_DYNAMIC_EXTENSIONS=y
CONFIG_SQLITE3_FTS3=y
CONFIG_SQLITE3_FTS4=y
CONFIG_SQLITE3_FTS5=y
CONFIG_SQLITE3_RTREE=y
CONFIG_STRIP_KERNEL_EXPORTS=y
CONFIG_TARGET_OPTIMIZATION="-O2 -pipe -mcpu=cortex-a53"
CONFIG_TARGET_OPTIONS=y
CONFIG_TESTING_KERNEL=y
# CONFIG_PACKAGE_dnsmasq_full_dhcpv6 is not set
# CONFIG_PACKAGE_kmod-crypto-kpp is not set
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by Xploder** [comment]
Can confirm that the new packet steering is far worse with PPPoE compared to the old script on MT-6000 Snapshot

**Comment by nbd168** [comment]
I will run some tests, maybe there is a problem with flow offloading and PPPoE

**Comment by brada4** [comment]
Yep. Need to relocate mss fix down as in fw4 git head and 
https://github.com/openwrt/firewall4/pull/26 and still watch conntrack -E if each packet does not bounce offload out and in.

**Comment by nbd168** [comment]
I've done a lot of performance measurements related to this issue on my MT7622 board.
I think the main issue is not really the load distribution, but the fact that tons of CPU cycles are being wasted on segmenting large packets assembled by GRO. So while one core only lightly loaded by the receive path, the other core that gets the steered packets is overloaded by having to perform data copy + checksum on most of the packets it gets.
Based on that, I believe the proper solution is to stick with the current script (since it significantly reduces scheduling overhead), and to get rid of the GRO/GSO overhead. I'm almost done with the kernel patches for this, my preliminary tests show very promising results.

**Comment by nbd168** [comment]
Finished the change for kernels 6.1 and 6.6 in my staging tree at https://git.openwrt.org/?p=openwrt/staging/nbd.git;a=summary
Please test.

**Comment by pesa1234** [comment]
> Finished the change for kernels 6.1 and 6.6 in my staging tree at https://git.openwrt.org/?p=openwrt/staging/nbd.git;a=summary Please test.

Yes sure I'll let you know. Thanks

**Comment by pesa1234** [comment]
> Finished the change for kernels 6.1 and 6.6 in my staging tree at https://git.openwrt.org/?p=openwrt/staging/nbd.git;a=summary Please test.

![immagine](https://github.com/openwrt/openwrt/assets/6216993/fa3b9d2b-d2b1-4373-b174-9f4cfe99dcf7)
 and the link speed hangs to : 1129.10 Mbps

**Comment by brada4** [comment]
Can you add cpubdetail so we see pink softirq ie nft/qdisc out of red anything in kernel?

**Comment by brada4** [comment]
> segmenting large packets assembled by GRO. 

I thought its just dev_weight

**Comment by pesa1234** [comment]
> Can you add cpubdetail so we see pink softirq ie nft/qdisc out of red anything in kernel?

I didn't understand your question

**Comment by rany2** [comment]
> > Can you add cpubdetail so we see pink softirq ie nft/qdisc out of red anything in kernel?
> 
> I didn't understand your question

In htop, go to "Setup (F2)" > (Left sidebar) Display options > Global options > Enable "Detailed CPU time"

**Comment by nbd168** [comment]
@pesa1234 until now I had not realized you were running speedtest on the device directly. That explains why my changes did not help at all in your test. My changes significantly improve routing performance, but leave local-rx unaffected.
Going back to the approach of the previous packet steering script will improve your local speedtest case, but might make routing performance worse. I could change my script to include a mode similar to the previous one, but I'm not sure how useful that would be in practice

**Comment by brada4** [comment]
@pesa1234  You can reduce load from local traffic slightly
vi /usr/share/firewall4/templates/ruleset.uc
iifname "lo" -> iif "lo"
oifname "lo" -> oif "lo"

Like in https://github.com/openwrt/firewall4/commit/a5553dae70439c7e4fa910490fcf12a1ffff5bd2
takes out interface enumeration before conntrack engine. this has no impact on forwarded traffic, only on local.

**Comment by brada4** [comment]
```
cp  /usr/share/firewall4/templates/ruleset.uc  /usr/share/firewall4/templates/ruleset.uc_old
vi  /usr/share/firewall4/templates/ruleset.uc
/iifname
position cursor over "name" part and delete characters with x
repeat for oif(name)
Esc:wq
root@openwrt # fw4 check
r@o# service firewall restart
```
Not primary use of "router" btw, thus slightly unoptimal.

**Comment by brada4** [comment]
@pesa1234 also worth unhiding kernel threads 
![image](https://github.com/openwrt/openwrt/assets/16061801/04e65fb6-5c9c-4635-8690-74a392f4712d)
(TUF-AX6000 doing gigabit from wan to wifi using fast.com no offloads)

**Comment by nbd168** [comment]
Another thing you can try for local speedtest is this: Check if the load distribution or performance changes if you write `256` to `/sys/class/net/eth0/queues/rx-0/rps_flow_cnt` and `/sys/class/net/eth1/queues/rx-0/rps_flow_cnt`

**Comment by Xploder** [comment]
This is with the new changes from @nbd168 's staging repo, same build as @pesa1234 is using and just a 500mbit WAN load (not local). It's definitely not working as intended on MT6000.

Loads are virtually the same as without packet steering.

![image](https://github.com/openwrt/openwrt/assets/3930461/e9ac3890-60e9-4391-88f7-f2299401a2c1)

**Comment by pesa1234** [comment]
> Another thing you can try for local speedtest is this: Check if the load distribution or performance changes if you write `256` to `/sys/class/net/eth0/queues/rx-0/rps_flow_cnt` and `/sys/class/net/eth1/queues/rx-0/rps_flow_cnt`

`echo 256 > /sys/class/net/eth1/queues/rx-0/rps_flow_cnt `--> 2.5gbps
![immagine](https://github.com/openwrt/openwrt/assets/6216993/c3218a43-061f-4ceb-823d-3bf46d8a8231)

**Comment by brada4** [comment]
Do the firewall thing for local tests. Should half pink part avoiding needless per-packet examination.

**Comment by nbd168** [comment]
@Xploder those results still matches the intention of the new script. The script tries to make one CPU responsible for NAPI polling, and one for the rest of the packet processing. Different CPUs are assigned for different devices.
The relatively high load for 500 Mbps is not necessarily an indication of how much traffic it is able to handle that way. The effects of GRO are highly nonlinear. When significantly below the CPU load limit, you typically see only very few packets processed per polling interval, so scheduling overhead absolutely dominates. When reaching the limit, each poll is able to aggregate more packets, drastically reducing the per-packet CPU overhead.
What I found in cases with very high CPU load is that this strategy typically performs better than spreading load across more CPUs, since it reduces scheduling overhead when more devices (ethernet, WLAN, etc.) are involved.

**Comment by brada4** [comment]
I cannot squeeze any anomaly with new script, just bounces 40-60% all CPUs, like with old one, disabling steering altogether 1st core is a bit more loaded, but no difference in throughput or latency.

**Comment by brada4** [comment]
> same CPU

same core (the one with 2 hyperthreads, whatever the modern name is) better, shares uppermost caches, does not bounce cached pages aside etc.

**Comment by nbd168** [comment]
I just pushed some changes to the packet steering script in my staging tree.
If you set `option packet_steering 2`, it will steer packets to all CPUs (like the old script did).
If you set `option steering_flows 128`, it will steer up to 128 locally received flows per device to the CPU receiving them. (using `rps_flow_cnt`, which I posted earlier).

**Comment by pesa1234** [comment]
> I just pushed some changes to the packet steering script in my staging tree. If you set `option packet_steering 2`, it will steer packets to all CPUs (like the old script did). If you set `option steering_flows 128`, it will steer up to 128 locally received flows per device to the CPU receiving them. (using `rps_flow_cnt`, which I posted earlier).

Thank you! In the next days I'll let you know.
To set-up in Luci this is the small improvement https://github.com/openwrt/luci/commit/30377780f8844780b99b17928e3b834dacff085e

**Comment by nbd168** [comment]
Please import the updated versions of those commits from my staging tree - I fixed some typo regressions in the code. I will push the changes to main soon.

**Comment by brada4** [comment]
If you have queues > nproc the "other queue" is sometimes on same CPU. Seems nginx reuseport uses just 1st tx queue per CPU. No idea though if hitting same CPU twice is cause of asymmetry.

**Comment by pesa1234** [comment]
https://github.com/openwrt/openwrt/commit/98834a4c3f81c6e4f20329ff266f9bd85731d114 - https://github.com/openwrt/openwrt/commit/b5c53848c3792355a2dd4ff0e06bf4d230e1f5fb - https://github.com/openwrt/openwrt/commit/c4d394c6cc0facba94fda5f1cc886edaf342be3a and https://github.com/openwrt/openwrt/commit/7ebcf2fb9c5db8b75666761f5e767c91abb1f437 solve the issue and works as expected, close.
Thanks @nbd168

**Comment by Djfe** [comment]
further things just got improved on main and on the release branch ☺️
https://github.com/openwrt/openwrt/commit/67a4aeef6c63e5836bd6b82faf6cc15934869efb
https://github.com/openwrt/openwrt/commit/acce25b789d40f2d88a2326a7d9921bd1743fe54
