### ISSUE TITLE
After upgrading to the new version, the wan port cannot receive data.

### ISSUE THREAD

**Issue by liumingan** [openwrt/openwrt#15279]
### Describe the bug

After upgrading to the new version, the wan port cannot receive data.

### OpenWrt version

SNAPSHOT (r26043-1991bfb814)

### OpenWrt release

ramips/mt7621

### OpenWrt target/subtarget

# /etc/config/network uci del network.wan uci del network.wan6 uci add_list network.@device[0].ports='wan' uci set network.lan6=interface uci set network.lan6.proto='dhcpv6' uci set network.lan6.device='br-lan' uci set network.lan6.reqaddress='try' uci set network.lan6.reqprefix='auto' uci set network.lan.ipaddr='192.168.10.2' uci set network.lan.gateway='192.168.10.1' uci add_list network.lan.dns='192.168.10.1' uci set network.lan.ip6assign='64' uci set network.lan.ip6hint='1' uci add_list network.lan.ip6class='lan6' uci set network.globals.ula_prefix='fd00:0:0::/48' uci commit network

### Device

Phicomm K2P / Phicomm KE 2P

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
If you delete wan network it stops handling data until you reset the device
