### ISSUE TITLE
mbedtls 3.6.0 shadowsocks error on MBEDTLS_CIPHER_MODE_CFB

### ISSUE THREAD

**Issue by suyuan168** [openwrt/openwrt#15330]
### Describe the bug

https://github.com/openwrt/openwrt/commit/adc29202c2044ad039f2904b822c6a6fe84ac984
mbedtls: Remove Kconfig options removed from mbedtls 3.6.0
These options are not available in mbedtls 3.6.0 and selecting them
causes an error.

The last two upgrades resulted in a lot of dependencies on MBEDTLS_CIPHER_MODE_CFB
The software cannot be compiled normally, such as shadowsocks. I need to return mbedtls: Update to 2.28.8.

### OpenWrt version

new

### OpenWrt release

new

### OpenWrt target/subtarget

new

### Device

new

### Image kind

Self-built image

### Steps to reproduce

https://github.com/shadowsocks/shadowsocks-libev
The last two upgrades resulted in a lot of dependencies on MBEDTLS_CIPHER_MODE_CFB
The software cannot be compiled normally, such as shadowsocks. I need to return mbedtls: Update to 2.28.8.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by msdos03** [comment]
How did you solve this?
