### ISSUE TITLE
ramips/mt7621: SamKnows Whitebox 8: both phy0 and phy1 identified as 5Ghz

### ISSUE THREAD

**Issue by nunojpg** [openwrt/openwrt#15391]
### Describe the bug

/etc/config/wireless have both radio0 and radio1 set to band "5g".
iw phy phy0 info shows support for 5GHz .
iw phy phy1 info shows support for 5GHz AND 2.4GHz.
DTS at: target/linux/ramips/dts/mt7621_samknows_whitebox-v8.dts

phy1 does not support 5GHz in reality.

### OpenWrt version

master (r26182-49a64c9541)

### OpenWrt release

master (SNAPSHOT)

### OpenWrt target/subtarget

ramips/mt7621

### Device

SamKnows Whitebox 8

### Image kind

Self-built image

### Expected behaviour

There should be a wireless radio configured by default to 2.4GHz.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
Add to mt7621_samknows_whitebox-v8.dts line 132 (block &pcie1 mt76@0,0):
```
		ieee80211-freq-limit = <2400000 2500000>;
```
and recompile.

**Comment by nunojpg** [comment]
Yes, same in 23.05.03.

**Comment by namiltd** [comment]
So if this line helps, a patch is needed for both branches: main and 23.05.

**Comment by nunojpg** [comment]
All great. You want me to open the PR?

**Comment by namiltd** [comment]
PRs done.

**Comment by hauke** [comment]
Could someone with a  SamKnows Whitebox 8 please post the `dmesg` and `iwinfo` output. 
This  page says it uses MediaTek MT7612E and MediaTek MT7603E, see https://openwrt.org/toh/samknows/sk-wb8
The MT7603E is a 2.4 GHz only device and should not use 5GHz.
