### ISSUE TITLE
Netgear WAX 206 - mt7530 not supported - Kernel 6.6.30

### ISSUE THREAD

**Issue by gca31** [openwrt/openwrt#15419]
### Describe the bug

I was testing the snapshot r26207-ce4da3cf41 (Kernel 6.6.30) and got this from the logs : kern.err kernel: [    2.368508] mt7530-mdio mdio-bus:00: chip 0 can't be supported
So no lan available (lan1/2/3/4) with this snapshot
I reverted to Kernel 6.1.81 snapshot r25559-6da3c9ddbc and lan is available

### OpenWrt version

r26207-ce4da3cf41

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Netgear WAX206

### Image kind

Official downloaded image

### Steps to reproduce

Downloadthe snapshot and proceed to a fresh install or a sysupgrade on a Netgear WAX206
The device will boot but can not be accessed through Lan. UART/TTY is needed to find out the kernel error on the mt7530 

### Actual behaviour

No lan available (Lan 1/2/3/4)

### Expected behaviour

Lan up and running !

### Additional info

Logread and dimes available there:
[PB WAX206 Kernel 6.6.30.pdf](https://github.com/openwrt/openwrt/files/15238773/PB.WAX206.Kernel.6.6.30.pdf)

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
Change file mt7622-netgear-wax206.dts:
```
		switch@0 {
			compatible = "mediatek,mt7531";
			#interrupt-cells = <1>;
			interrupt-controller;
			interrupt-parent = <&pio>;
			interrupts = <53 IRQ_TYPE_LEVEL_HIGH>;
			reg = <0>;
```
to
```
		switch@1f {
			compatible = "mediatek,mt7531";
			#interrupt-cells = <1>;
			interrupt-controller;
			interrupt-parent = <&pio>;
			interrupts = <53 IRQ_TYPE_LEVEL_HIGH>;
			reg = <31>;
```
