### ISSUE TITLE
Rockchip: Nanopi R4S, LAN port dead after switching to Kernel 6.6

### ISSUE THREAD

**Issue by teqlee** [openwrt/openwrt#15461]
### Describe the bug

After switching to Kernel 6.6, the Nanopi R4S Lan led not light up, can't get ip from lan port. Tested with latest snapshot build.

### OpenWrt version

r26281-0162174e7e

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

target/rockchip

### Device

Nanopi R4S

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by teqlee** [comment]
@1715173329 please notice.

**Comment by 1715173329** [comment]
"If there are no logs, no relevant screenshots that cannot be used, it is suggested to go find a fortune teller on the street."

**Comment by teqlee** [comment]
It seems the problem is overclocking, in version 6.1 the cpu was overclocked to 2.0ghz (from 1.8ghz) without any problem, but version 6.6 seems to not like overclocking, 4/5 starts LAN port is not working. When not overclocked everything works normally.

**Comment by smallprogram** [comment]
@teqlee Hi, how did you solve this problem? I have the same problem.
