### ISSUE TITLE
OpenWrt cannot install ca-certificates

### ISSUE THREAD

**Issue by yeyos1** [openwrt/openwrt#15489]
### Describe the bug

Please tell me how to install the system root certificate in the openwrt system. My ca certificate is in pem format.

### OpenWrt version

R23.8.5-D (2023-09-27)

### OpenWrt release

R23.8.5-D (2023-09-27)

### OpenWrt target/subtarget

R23.8.5-D (2023-09-27)

### Device

x86_64

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
Use the mailing list, IRC channels or forum for support requests.

**Comment by ynezz** [comment]
> Official downloaded image

Where did you downloaded such image?
