### ISSUE TITLE
btrfs raid1 failed to mount

### ISSUE THREAD

**Issue by poromony** [openwrt/openwrt#15492]
### Describe the bug

I used btrfs-progs to create a btrfs-raid1 with sda1 & sdb1, and they worked well. But when OP restarted, I could not mount them, the system log : 

[   96.813777] BTRFS: device fsid 659e588a-6d8d-4eec-bbb1-af8f33e44708 devid 1 transid 10 /dev/sda1 scanned by mount (3346)
Wed May 15 00:54:35 2024 kern.info kernel: [   96.815165] BTRFS info (device sda1): first mount of filesystem 659e588a-6d8d-4eec-bbb1-af8f33e44708
Wed May 15 00:54:35 2024 kern.info kernel: [   96.816059] BTRFS info (device sda1): using crc32c (crc32c-generic) checksum algorithm
Wed May 15 00:54:35 2024 kern.info kernel: [   96.816850] BTRFS info (device sda1): using free space tree
Wed May 15 00:54:35 2024 kern.err kernel: [   96.818414] BTRFS error (device sda1): devid 2 uuid 228e4f85-b72a-40e1-baf1-cbf66570330e is missing
Wed May 15 00:54:35 2024 kern.err kernel: [   96.819283] BTRFS error (device sda1): failed to read the system array: -2
Wed May 15 00:54:35 2024 kern.err kernel: [   96.820514] BTRFS error (device sda1): open_ctree failed

### OpenWrt version

r26308-4341901f05

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

x86/64

### Device

VMware, Inc. VMware Virtual Platform

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by cryobry** [comment]
Did you run `btrfs device scan` first?

**Comment by poromony** [comment]
Thank you for your reply

> Did you run `btrfs device scan` first?

I tried again:
(1)Creat btrfs-raid1 array by /dev/sdc1 /dev/sdd1:
The system log : 

root@OpenWrt:~# mkfs.btrfs -f -m raid1 -d raid1 /dev/sdc1 /dev/sdd1
btrfs-progs v5.16.1
See http://btrfs.wiki.kernel.org for more information.

NOTE: several default settings have changed in version 5.15, please make sure
      this does not affect your deployments:
      - DUP for metadata (-m dup)
      - enabled no-holes (-O no-holes)
      - enabled free-space-tree (-R free-space-tree)

Label:              (null)
UUID:               728b9590-69e4-422d-b6dd-207e7645efe7
Node size:          16384
Sector size:        4096
Filesystem size:    16.00GiB
Block group profiles:
  Data:             RAID1             1.00GiB
  Metadata:         RAID1           256.00MiB
  System:           RAID1             8.00MiB
SSD detected:       no
Zoned device:       no
Incompat features:  extref, skinny-metadata, no-holes
Runtime features:   free-space-tree
Checksum:           crc32c
Number of devices:  2
Devices:
   ID        SIZE  PATH
    1     8.00GiB  /dev/sdc1
    2     8.00GiB  /dev/sdd1

root@OpenWrt:~# btrfs device scan
Scanning for Btrfs filesystems
root@OpenWrt:~# btrfs fi show
Label: none  uuid: 728b9590-69e4-422d-b6dd-207e7645efe7
        Total devices 2 FS bytes used 192.00KiB
        devid    1 size 8.00GiB used 1.26GiB path /dev/sdc1
        devid    2 size 8.00GiB used 1.26GiB path /dev/sdd1

(2) AFTER reboot, the btrts-raid1 array lost,
The system log : 

Wed May 22 23:07:06 2024 kern.info kernel: [   16.813714] BTRFS: device fsid 728b9590-69e4-422d-b6dd-207e7645efe7 devid 1 transid 9 /dev/sdc1 scanned by block (2267)
Wed May 22 23:07:06 2024 kern.info kernel: [   16.814122] BTRFS info (device sdc1): first mount of filesystem 728b9590-69e4-422d-b6dd-207e7645efe7
Wed May 22 23:07:06 2024 kern.info kernel: [   16.814294] BTRFS info (device sdc1): using crc32c (crc32c-generic) checksum algorithm
Wed May 22 23:07:06 2024 kern.info kernel: [   16.814439] BTRFS info (device sdc1): using free space tree
Wed May 22 23:07:06 2024 kern.err kernel: [   16.815216] BTRFS error (device sdc1): devid 2 uuid bf0c3d88-a80e-4ab2-a243-eb9e7befb6bd is missing
Wed May 22 23:07:06 2024 kern.err kernel: [   16.815378] BTRFS error (device sdc1): failed to read the system array: -2
Wed May 22 23:07:06 2024 kern.err kernel: [   16.815853] BTRFS error (device sdc1): open_ctree failed
Wed May 22 23:07:06 2024 kern.info kernel: [   16.816295] BTRFS: device fsid 728b9590-69e4-422d-b6dd-207e7645efe7 devid 2 transid 9 /dev/sdd1 scanned by block (2267)
Wed May 22 23:07:06 2024 kern.info kernel: [   16.816645] BTRFS info (device sdd1): first mount of filesystem 728b9590-69e4-422d-b6dd-207e7645efe7
Wed May 22 23:07:06 2024 kern.info kernel: [   16.816809] BTRFS info (device sdd1): using crc32c (crc32c-generic) checksum algorithm
Wed May 22 23:07:06 2024 kern.info kernel: [   16.816956] BTRFS info (device sdd1): using free space tree
Wed May 22 23:07:06 2024 kern.err kernel: [   16.817435] BTRFS error (device sdd1): devid 1 uuid d6d50b98-fedf-442b-ac03-b143ee97f130 is missing
Wed May 22 23:07:06 2024 kern.err kernel: [   16.817602] BTRFS error (device sdd1): failed to read the system array: -2
Wed May 22 23:07:06 2024 kern.err kernel: [   16.818038] BTRFS error (device sdd1): open_ctree failed


So I run "btrfs device scan", 
The system log : 

Wed May 22 23:22:51 2024 kern.info kernel: [  151.910599] BTRFS: device fsid 728b9590-69e4-422d-b6dd-207e7645efe7 devid 2 transid 11 /dev/sdd1 scanned by btrfs (10403)
Wed May 22 23:22:51 2024 kern.info kernel: [  151.911028] BTRFS: device fsid 728b9590-69e4-422d-b6dd-207e7645efe7 devid 1 transid 11 /dev/sdc1 scanned by btrfs (10403)

But the previously set mount point is invalid and I had to manually mount the partition.

**Comment by cryobry** [comment]
That's apparently normal, you need to run `btrfs device scan` after reboot
and then manually mount the btrfs volume.

https://forum.openwrt.org/t/better-btrfs-support/165327

**Comment by poromony** [comment]
> That's apparently normal, you need to run `btrfs device scan` after reboot and then manually mount the btrfs volume. https://forum.openwrt.org/t/better-btrfs-support/165327

Thanks ~

**Comment by g6094199** [comment]
> That's apparently normal, you need to run `btrfs device scan` after reboot
> and then manually mount the btrfs volume.
> 
> https://forum.openwrt.org/t/better-btrfs-support/165327
> […](#)

sorry, but i never had a an OS where this behavior was "normal". btrfs support is simply still broken in 2026 in openwrt.
see:

https://github.com/openwrt/openwrt/issues/6795
https://github.com/openwrt/openwrt/issues/7176
https://github.com/openwrt/openwrt/issues/9620


https://forum.openwrt.org/t/possible-bug-btrfs-raid-mdraid-uuid-bug-on-kirkwood/243828/
