### ISSUE TITLE
mt7986-wo-firmware

### ISSUE THREAD

**Issue by xh0823** [openwrt/openwrt#15570]
### Describe the bug

mkdir -p /home/xy/openwrt/openwrt/bin/targets/mediatek/filogic/packages /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/ipkg-aarch64_cortex-a53/eip197-mini-firmware /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo
install -d -m0755 /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/ipkg-aarch64_cortex-a53/eip197-mini-firmware/lib/firmware/inside-secure/eip197_minifw
install -m0644 /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/inside-secure/eip197_minifw/ifpp.bin /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/inside-secure/eip197_minifw/ipue.bin /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/ipkg-aarch64_cortex-a53/eip197-mini-firmware/lib/firmware/inside-secure/eip197_minifw
find /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/ipkg-aarch64_cortex-a53/eip197-mini-firmware -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
: /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/ipkg-aarch64_cortex-a53/eip197-mini-firmware
install -d -m0755 /home/xy/openwrt/openwrt/bin/packages/aarch64_cortex-a53/base/tmp
mkdir -p /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/ipkg-aarch64_cortex-a53/eip197-mini-firmware/CONTROL
(cd /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/ipkg-aarch64_cortex-a53/eip197-mini-firmware/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
/home/xy/openwrt/openwrt/staging_dir/host/bin/fakeroot /home/xy/openwrt/openwrt/staging_dir/host/bin/bash /home/xy/openwrt/openwrt/scripts/ipkg-build -m "" /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/ipkg-aarch64_cortex-a53/eip197-mini-firmware /home/xy/openwrt/openwrt/bin/packages/aarch64_cortex-a53/base
Packaged contents of /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/ipkg-aarch64_cortex-a53/eip197-mini-firmware into /home/xy/openwrt/openwrt/bin/packages/aarch64_cortex-a53/base/eip197-mini-firmware_20240220-r1_aarch64_cortex-a53.ipk
rm -rf /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/.pkgdir/eip197-mini-firmware.installed /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/.pkgdir/eip197-mini-firmware
mkdir -p /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/.pkgdir/eip197-mini-firmware
install -d -m0755 /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/.pkgdir/eip197-mini-firmware/lib/firmware/inside-secure/eip197_minifw
install -m0644 /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/inside-secure/eip197_minifw/ifpp.bin /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/inside-secure/eip197_minifw/ipue.bin /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/.pkgdir/eip197-mini-firmware/lib/firmware/inside-secure/eip197_minifw
touch /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/.pkgdir/eip197-mini-firmware.installed
mkdir -p /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
SHELL= flock /home/xy/openwrt/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/.pkgdir/mt7986-wo-firmware/. /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.mt7986-wo-firmware_installed
echo "mt7986-wo-firmware" >> /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/linux-firmware.default.install
mkdir -p /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
SHELL= flock /home/xy/openwrt/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/xy/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-firmware-20240220/.pkgdir/eip197-mini-firmware/. /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.eip197-mini-firmware_installed
echo "eip197-mini-firmware" >> /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/linux-firmware.default.install
make[3]: Leaving directory '/home/xy/openwrt/openwrt/package/firmware/linux-firmware'
time: package/firmware/linux-firmware/compile#14.86#2.30#16.09
make[2]: Leaving directory '/home/xy/openwrt/openwrt'
make[1]: *** [package/Makefile:167: /home/xy/openwrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xy/openwrt/openwrt'
make: *** [/home/xy/openwrt/openwrt/include/toplevel.mk:233: world] Error 2

### OpenWrt version

aarch64_cortex-a53

### OpenWrt release

mt7986

### OpenWrt target/subtarget

mt7986

### Device

tp-6088

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Should not be too hard to make properly formatted issue with genuine outputs from your system and relevant logs (attaching more context)
you talk wo firmware when all your spaghetti is about eip197?
