### ISSUE TITLE
 kernel not read correct MAC from OEM partitions

### ISSUE THREAD

**Issue by notthesun** [openwrt/openwrt#15587]
### Describe the bug

after each reboot the mac address of the interfaces changes randomly

### OpenWrt version

r26436-7514d9bb6f

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

Cudy WR3000 v1

### Image kind

Official downloaded image

### Steps to reproduce

Simply reboot the router and check mac address

### Additional info

to solve the problem need to set mac address manually

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
Which interface does the lan/wan/wifi report concern?

**Comment by brada4** [comment]
You also see random MACs assigned in `dmesg` and device names related.

**Comment by john-tho** [comment]
Have a look at https://github.com/openwrt/openwrt/pull/15515:
u-boot in the M3000 (from same manufacturer) would not read env, and was storing a random MAC to Linux DTS each boot for the `ethernet0 = &gmac0;` alias. Linux prioritises DTS MAC addresses `mac-address`, `local-mac-address`, `address` over nvmem.
Possible the same is happening here: https://github.com/openwrt/openwrt/blob/6510eb3b5d612ea7a70c4a8d9b83639e3b46e221/target/linux/mediatek/dts/mt7981b-cudy-wr3000-v1.dts#L14

**Comment by Braccoz** [comment]
can confirm the issue persists in trunk as of build r26937-7ca4190c18
