### ISSUE TITLE
why there no libx264 option  to select

### ISSUE THREAD

**Issue by fareign** [openwrt/openwrt#15687]
### Describe the bug

<img width="729" alt="微信图片_20240612003600" src="https://github.com/openwrt/openwrt/assets/15459/940738b9-df18-4ff9-9d6c-a5f1caa185c4">

I reinstall feeds ../scripts/feeds install libx264
 and still no menu

### OpenWrt version

23.05

### OpenWrt release

snap

### OpenWrt target/subtarget

make menuconfig

### Device

rpi cm4

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by fareign** [comment]
> Invalid Release reported. `snap` Is this from a clean repository?

I buidl from master yesterday.use office config.

**Comment by fareign** [comment]
I read the Makefile ,can not find anything wrong,so I want some help.thanks.

**Comment by fareign** [comment]
> You must enable BUILD_PATENTED ( disabled by default ) to build those packages. You can see it clearly in those Makefiles about dependency on BUILD_PATENTED.

thanks，solved

**Comment by raenye** [comment]
> thanks，solved

Then this issue can be closed?
