### ISSUE TITLE
winner h616 , h618

### ISSUE THREAD

**Issue by amirhosseinchoghaei** [openwrt/openwrt#15817]
### Describe the bug

Why openwrt don't support allwinner h616 & h618 for orange pi zero 2
Please Support this Board With Wireless 
thanks .

### OpenWrt version

23.05

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

Cortex-A53

### Device

OrangePi zero 2

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by pkgadd** [comment]
This is no bug, but a(n inactionable) feature request, please don't file it as such.

Hardware support happens (or not) if one of its users who own said devices provide the patches to support it. Given that sunxi has relatively good mainline support, there's nothing between it getting support, apart from someone -you- putting in the required development, it won't magically happen by itself.
