### ISSUE TITLE
After flasing Archer C6U (EU) ver.1 - Bootloop

### ISSUE THREAD

**Issue by robinson-28** [openwrt/openwrt#15895]
### Describe the bug

U-Boot 1.1.3 (Dec 13 2021 - 15:33:52)

Board: Ralink APSoC DRAM:  128 MB
relocate_code Pointer at: 87f58000

Config XHCI 40M PLL
******************************
Software System Reset Occurred
******************************
flash manufacture id: 20, device id 40 18
Warning: un-recognized chip ID, please update bootloader!
*** Warning - bad CRC, using default environment

============================================
Ralink UBoot Version: 5.0.0.0
--------------------------------------------
ASIC MT7621A DualCore (MAC to MT7530 Mode)
DRAM_CONF_FROM: Auto-Detection
DRAM_TYPE: DDR3
DRAM bus: 16 bit
Xtal Mode=3 OCP Ratio=1/3
Flash component: SPI Flash
Date:Dec 13 2021  Time:15:33:52
============================================
THIS IS uboot
icache: sets:256, ways:4, linesz:32 ,total:32768
dcache: sets:256, ways:4, linesz:32 ,total:32768

##### The CPU freq = 880 MHZ ####
estimate memory size =128 Mbytes

Press '4' or 't' to break the booting process

Press 'x' to enter recovery web server                                                                                                                       0
nm_init:791
nm_initFwupPtnStruct:276
nm_lib_readPtnTable:738
[NM_Debug](nm_lib_readPtnTable) 00743: NM_PTN_TABLE_BASE = 0xfe0000
[NM_Debug](nm_lib_readPtnFromNvram) 00569: partition_used_len = 920, requried len = 8192
[NM_Debug](nm_lib_readPtnTable) 00751: Reading Partition Table from NVRAM ... OK

[NM_Debug](nm_lib_readPtnTable) 00759: Parsing Partition Table ... OK

[NM_Debug](nm_lib_readPtnFromNvram) 00569: partition_used_len = 2, requried len = 3
factory boot check integer ok.

3: System Boot system code via Flash.
## Booting image at bc040000 ...
   Image Name:   MIPS OpenWrt Linux-6.6.36
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    3307811 Bytes =  3.2 MB
   Load Address: 80001000
   Entry Point:  80001000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK
No initrd
[NM_Debug](nm_lib_readPtnFromNvram) 00569: partition_used_len = 2, requried len = 3
[NM_Error](nm_api_checkTestMode) 00417: factory boot check testmode flag is not 1.

## Giving linux memsize in MB, 128

Starting kernel ...

[    0.000000] Linux version 6.6.36 (builder@buildhost) (mipsel-openwrt-linux-musl-gcc (OpenWrt GCC 13.3.0 r26870-4a2f712f85) 13.3.0, GNU ld (GNU Binutils) 2.42) #0 SMP Sat Jul  6 03:22:37 2024
[    0.000000] SoC Type: MediaTek MT7621 ver:1 eco:3
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 0001992f (MIPS 1004Kc)
[    0.000000] MIPS: machine is TP-Link Archer C6U v1
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] VPE topology {2,2} total 4
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] percpu: Embedded 12 pages/cpu s18848 r8192 d22112 u49152
[    0.000000] Kernel command line: console=ttyS0,115200 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Writing ErrCtl register=00005090
[    0.000000] Readback ErrCtl register=00005090
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32480
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 117484K/131072K available (8174K kernel code, 638K rwdata, 1736K rodata, 1280K init, 227K bss, 13588K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 256
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] clocksource: GIC: mask: 0xffffffffffffffff max_cycles: 0xcaf478abb4, max_idle_ns: 440795247997 ns
[    0.000005] sched_clock: 64 bits at 880MHz, resolution 1ns, wraps every 4398046511103ns
[    0.008069] Calibrating delay loop... 586.13 BogoMIPS (lpj=2930688)
[    0.066224] pid_max: default: 32768 minimum: 301
[    0.079620] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.086859] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.103439] RCU Tasks Trace: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1.
[    0.111615] rcu: Hierarchical SRCU implementation.
[    0.116313] rcu:     Max phase no-delay instances is 1000.
[    0.122379] smp: Bringing up secondary CPUs ...
[    0.127737] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.127765] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.127780] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.127829] CPU1 revision is: 0001992f (MIPS 1004Kc)
[    0.181821] Synchronize counters for CPU 1: done.
[    0.214366] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.214387] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.214400] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.214432] CPU2 revision is: 0001992f (MIPS 1004Kc)
[    0.273369] Synchronize counters for CPU 2: done.
[    0.304049] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.304070] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.304083] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.304119] CPU3 revision is: 0001992f (MIPS 1004Kc)
[    0.358561] Synchronize counters for CPU 3: done.
[    0.388428] smp: Brought up 1 node, 4 CPUs
[    0.399444] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.409254] futex hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    0.420052] pinctrl core: initialized pinctrl subsystem
[    0.428139] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.434804] thermal_sys: Registered thermal governor 'step_wise'
[    0.457674] clocksource: Switched to clocksource GIC
[    0.472574] NET: Registered PF_INET protocol family
[    0.477670] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.486345] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.494652] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.502325] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.509930] TCP bind hash table entries: 1024 (order: 2, 16384 bytes, linear)
[    0.517044] TCP: Hash tables configured (established 1024 bind 1024)
[    0.523502] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.529995] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.537921] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.543546] PCI: CLS 0 bytes, default 32
[    0.551289] workingset: timestamp_bits=14 max_order=15 bucket_order=1
[    0.558886] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.564628] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.580456] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.591319] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.597272] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.603274] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.609472] mt7621-pci 1e140000.pcie: host bridge /pcie@1e140000 ranges:
[    0.616113] mt7621-pci 1e140000.pcie:   No bus range found for /pcie@1e140000, using [bus 00-ff]
[    0.624900] mt7621-pci 1e140000.pcie:      MEM 0x0060000000..0x006fffffff -> 0x0060000000
[    0.633008] mt7621-pci 1e140000.pcie:       IO 0x001e160000..0x001e16ffff -> 0x0000000000
[    0.997670] mt7621-pci 1e140000.pcie: pcie2 no card, disable it (RST & CLK)
[    1.004571] mt7621-pci 1e140000.pcie: PCIE0 enabled
[    1.009451] mt7621-pci 1e140000.pcie: PCIE1 enabled
[    1.014419] PCI coherence region base: 0x60000000, mask/settings: 0xf0000002
[    1.021570] mt7621-pci 1e140000.pcie: PCI host bridge to bus 0000:00
[    1.027880] pci_bus 0000:00: root bus resource [bus 00-ff]
[    1.033286] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff]
[    1.040138] pci_bus 0000:00: root bus resource [io  0x0000-0xffff]
[    1.046295] pci 0000:00:00.0: [0e8d:0801] type 01 class 0x060400
[    1.052243] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    1.058475] pci 0000:00:00.0: reg 0x14: [mem 0x60300000-0x6030ffff]
[    1.064715] pci 0000:00:00.0: supports D1
[    1.068651] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    1.075133] pci 0000:00:01.0: [0e8d:0801] type 01 class 0x060400
[    1.081156] pci 0000:00:01.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    1.087341] pci 0000:00:01.0: reg 0x14: [mem 0x60310000-0x6031ffff]
[    1.093655] pci 0000:00:01.0: supports D1
[    1.097573] pci 0000:00:01.0: PME# supported from D0 D1 D3hot
[    1.105564] pci 0000:01:00.0: [14c3:7603] type 00 class 0x028000
[    1.111599] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff]
[    1.117964] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    1.124326] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
[    1.129530] pci 0000:00:00.0:   bridge window [io  0x0000-0x0fff]
[    1.135538] pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
[    1.142312] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    1.149167] pci 0000:02:00.0: [14c3:7663] type 00 class 0x000280
[    1.155128] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit pref]
[    1.162322] pci 0000:02:00.0: reg 0x18: [mem 0x00000000-0x00003fff 64bit pref]
[    1.169511] pci 0000:02:00.0: reg 0x20: [mem 0x00000000-0x00000fff 64bit pref]
[    1.176757] pci 0000:02:00.0: supports D1 D2
[    1.180969] pci 0000:02:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[    1.187533] pci 0000:02:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s PCIe x1 link at 0000:00:01.0 (capable of 4.000 Gb/s with 5.0 GT/s PCIe x1 link)
[    1.202637] pci 0000:00:01.0: PCI bridge to [bus 02-ff]
[    1.207851] pci 0000:00:01.0:   bridge window [io  0x0000-0x0fff]
[    1.213863] pci 0000:00:01.0:   bridge window [mem 0x60100000-0x602fffff pref]
[    1.221061] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02
[    1.227679] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    1.234196] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    1.241149] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000]
[    1.247708] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000]
[    1.254594] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff]
[    1.261355] pci 0000:00:01.0: BAR 9: assigned [mem 0x60100000-0x602fffff pref]
[    1.268529] pci 0000:00:00.0: BAR 1: assigned [mem 0x60300000-0x6030ffff]
[    1.275242] pci 0000:00:01.0: BAR 1: assigned [mem 0x60310000-0x6031ffff]
[    1.282010] pci 0000:00:00.0: BAR 7: assigned [io  0x0000-0x0fff]
[    1.288055] pci 0000:00:01.0: BAR 7: assigned [io  0x1000-0x1fff]
[    1.294079] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff]
[    1.300855] pci 0000:00:00.0: PCI bridge to [bus 01]
[    1.305737] pci 0000:00:00.0:   bridge window [io  0x0000-0x0fff]
[    1.311814] pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
[    1.318562] pci 0000:02:00.0: BAR 0: assigned [mem 0x60100000-0x601fffff 64bit pref]
[    1.326225] pci 0000:02:00.0: BAR 2: assigned [mem 0x60200000-0x60203fff 64bit pref]
[    1.333945] pci 0000:02:00.0: BAR 4: assigned [mem 0x60204000-0x60204fff 64bit pref]
[    1.341633] pci 0000:00:01.0: PCI bridge to [bus 02]
[    1.346517] pci 0000:00:01.0:   bridge window [io  0x1000-0x1fff]
[    1.352595] pci 0000:00:01.0:   bridge window [mem 0x60100000-0x602fffff pref]
[    1.361409] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    1.377151] printk: console [ttyS0] disabled
[    1.382308] 1e000c00.uartlite: ttyS0 at MMIO 0x1e000c00 (irq = 18, base_baud = 3125000) is a 16550A
[    1.391385] printk: console [ttyS0] enabled
[    1.391385] printk: console [ttyS0] enabled
[    1.399672] printk: bootconsole [early0] disabled
[    1.399672] printk: bootconsole [early0] disabled
[    1.414261] spi-mt7621 1e000b00.spi: sys_freq: 220000000
[    1.421228] spi-nor spi0.0: XM25QH128C (16384 Kbytes)
[    1.426479] 5 fixed-partitions partitions found on MTD device spi0.0
[    1.432912] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions
[    1.440256] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions
[    1.447893] Creating 5 MTD partitions on "spi0.0":
[    1.452691] 0x000000000000-0x000000040000 : "u-boot"
[    1.459385] 0x000000040000-0x000000fa0000 : "firmware"
[    1.470408] 0x000000fa0000-0x000000fb0000 : "config"
[    1.476745] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions
[    1.484492] 0x000000fb0000-0x000000ff0000 : "tplink"
[    1.490723] 0x000000ff0000-0x000001000000 : "radio"
[    1.496951] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions
[    1.640993] mt7530-mdio mdio-bus:1f: MT7530 adapts as multi-chip module
[    1.655953] mtk_soc_eth 1e100000.ethernet eth0: mediatek frame engine at 0xbe100000, irq 19
[    1.667535] mtk_soc_eth 1e100000.ethernet eth1: mediatek frame engine at 0xbe100000, irq 19
[    1.677756] i2c_dev: i2c /dev entries driver
[    1.685850] NET: Registered PF_INET6 protocol family
[    1.693845] Segment Routing with IPv6
[    1.697591] In-situ OAM (IOAM) with IPv6
[    1.701653] NET: Registered PF_PACKET protocol family
[    1.706758] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    1.720200] 8021q: 802.1Q VLAN Support v1.8
[    1.755268] mt7530-mdio mdio-bus:1f: MT7530 adapts as multi-chip module
[    1.788756] mt7530-mdio mdio-bus:1f: configuring for fixed/rgmii link mode
[    1.796585] mt7530-mdio mdio-bus:1f: Link is Up - 1Gbps/Full - flow control rx/tx
[    1.798689] mt7530-mdio mdio-bus:1f lan1 (uninitialized): PHY [mt7530-0:01] driver [MediaTek MT7530 PHY] (irq=21)
[    1.817716] mt7530-mdio mdio-bus:1f lan2 (uninitialized): PHY [mt7530-0:02] driver [MediaTek MT7530 PHY] (irq=22)
[    1.830769] mt7530-mdio mdio-bus:1f lan3 (uninitialized): PHY [mt7530-0:03] driver [MediaTek MT7530 PHY] (irq=23)
[    1.843817] mt7530-mdio mdio-bus:1f lan4 (uninitialized): PHY [mt7530-0:04] driver [MediaTek MT7530 PHY] (irq=24)
[    1.856341] mtk_soc_eth 1e100000.ethernet eth0: entered promiscuous mode
[    1.863251] DSA: tree 0 setup
[    1.867268] clk: Disabling unused clocks
[    1.871763] MTD: Couldn't look up '': -22
[    1.876535] /dev/root: Can't open blockdev
[    1.880717] VFS: Cannot open root device "" or unknown-block(0,0): error -6
[    1.887702] Please append a correct "root=" boot option; here are the available partitions:
[    1.896032] 1f00             256 mtdblock0
[    1.896045]  (driver?)
[    1.902579] 1f01           15744 mtdblock1
[    1.902590]  (driver?)
[    1.909115] 1f02              64 mtdblock2
[    1.909127]  (driver?)
[    1.915628] 1f03             256 mtdblock3
[    1.915636]  (driver?)
[    1.922237] 1f04              64 mtdblock4
[    1.922249]  (driver?)
[    1.928779] List of all bdev filesystems:
[    1.932772]  squashfs
[    1.932777]
[    1.936510] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    1.944751] Rebooting in 1 seconds..

### OpenWrt version

r26870-4a2f712f85

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

ramips/mt7621

### Device

Archer C6U

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robinson-28** [comment]
Yes, from clean repository.
https://firmware-selector.openwrt.org/?version=SNAPSHOT&target=ramips%2Fmt7621&id=tplink_archer-c6u-v1

**Comment by brada4** [comment]
Does release work?

**Comment by robinson-28** [comment]
No, this release does not work. Also earlier.
