### ISSUE TITLE
Missing collectd from X86-64 snapshot packages repository

### ISSUE THREAD

**Issue by w1zz4** [openwrt/openwrt#15907]
### Describe the bug

Looks likes collectd is missing from X86-64 snapshot packages repository at https://downloads.openwrt.org/snapshots/targets/x86/64/packages/

Last time my buildbot was able to complete successfully is june 14th.

### OpenWrt version

r26592-83311b7470

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

x86/64

### Device

QEMU Standard PC (Q35 + ICH9, 2009)

### Image kind

Self-built image

### Steps to reproduce

Trying to use imagebuilder to buid latest snapshot with collectd 

### Actual behaviour

Unknown package 'collectd'.
Unknown package 'collectd-mod-mqtt'.
Unknown package 'collectd-mod-memory'.
Unknown package 'collectd-mod-interface'.
Unknown package 'collectd-mod-load'.
Unknown package 'collectd-mod-uptime'.
Unknown package 'collectd-mod-ping'.
Unknown package 'collectd-mod-cpu'.

### Expected behaviour

Download and makes packages into build

### Diffconfig

```text
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_MULTI_PROFILE=y
CONFIG_TARGET_DEVICE_x86_64_DEVICE_generic=y
CONFIG_TARGET_DEVICE_PACKAGES_x86_64_DEVICE_generic=""
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
CONFIG_DEVEL=y
CONFIG_TARGET_PER_DEVICE_ROOTFS=y
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by dannil** [comment]
https://github.com/openwrt/packages/issues/24539#issuecomment-2217240922 it should re-appear by itself.
