### ISSUE TITLE
OPKG uninstall Luci-pppoe package deletes  whole Luci Interface

### ISSUE THREAD

**Issue by palbiez** [openwrt/openwrt#15925]
### Describe the bug

Hi all,
I wanted to uninstall onto my D-Link 1325 Wifi Dump AP the unused PPPOE packages. 
I uninstalled via luci.

After uninstalling luci-proto-ppp incl. ununsed packages the whole Luci will be removed. 

Before (from my second AP) this packages are installed
`root@dapx1860:~# opkg list-installed
base-files - 1554-r23809-234f1a2efa
busybox - 1.36.1-1
ca-bundle - 20230311-1
cgi-io - 2022-08-10-901b0f04-21
dnsmasq - 2.90-2
dropbear - 2022.82-6
firewall4 - 2023-09-01-598d9fbb-1
fstools - 2023-02-28-bfe882d5-1
fwtool - 2019-11-12-8f7fe925-1
getrandom - 2022-08-13-4c7b720b-2
hostapd-common - 2023-09-08-e5ccbfc6-6
iw - 5.19-1
iwinfo - 2023-07-01-ca79f641-1
jansson4 - 2.14-3
jshn - 2023-05-23-75a3b870-1
jsonfilter - 2024-01-23-594cfa86-1
kernel - 5.15.150-1-bee655e7f41679981b85a223f3aba35b
kmod-cfg80211 - 5.15.150+6.1.24-3
kmod-crypto-acompress - 5.15.150-1
kmod-crypto-aead - 5.15.150-1
kmod-crypto-ccm - 5.15.150-1
kmod-crypto-cmac - 5.15.150-1
kmod-crypto-crc32c - 5.15.150-1
kmod-crypto-ctr - 5.15.150-1
kmod-crypto-gcm - 5.15.150-1
kmod-crypto-gf128 - 5.15.150-1
kmod-crypto-ghash - 5.15.150-1
kmod-crypto-hash - 5.15.150-1
kmod-crypto-hmac - 5.15.150-1
kmod-crypto-manager - 5.15.150-1
kmod-crypto-null - 5.15.150-1
kmod-crypto-rng - 5.15.150-1
kmod-crypto-seqiv - 5.15.150-1
kmod-crypto-sha512 - 5.15.150-1
kmod-gpio-button-hotplug - 5.15.150-3
kmod-hwmon-core - 5.15.150-1
kmod-leds-gpio - 5.15.150-1
kmod-lib-crc-ccitt - 5.15.150-1
kmod-lib-crc32c - 5.15.150-1
kmod-lib-lzo - 5.15.150-1
kmod-mac80211 - 5.15.150+6.1.24-3
kmod-mt76-connac - 5.15.150+2023-09-11-f1e1e67d-1
kmod-mt76-core - 5.15.150+2023-09-11-f1e1e67d-1
kmod-mt7915-firmware - 5.15.150+2023-09-11-f1e1e67d-1
kmod-mt7915e - 5.15.150+2023-09-11-f1e1e67d-1
kmod-nf-conntrack - 5.15.150-1
kmod-nf-conntrack6 - 5.15.150-1
kmod-nf-flow - 5.15.150-1
kmod-nf-log - 5.15.150-1
kmod-nf-log6 - 5.15.150-1
kmod-nf-nat - 5.15.150-1
kmod-nf-reject - 5.15.150-1
kmod-nf-reject6 - 5.15.150-1
kmod-nfnetlink - 5.15.150-1
kmod-nft-core - 5.15.150-1
kmod-nft-fib - 5.15.150-1
kmod-nft-nat - 5.15.150-1
kmod-nft-offload - 5.15.150-1
kmod-ppp - 5.15.150-1
kmod-pppoe - 5.15.150-1
kmod-pppox - 5.15.150-1
kmod-slhc - 5.15.150-1
kmod-thermal - 5.15.150-1
libblobmsg-json20230523 - 2023-05-23-75a3b870-1
libc - 1.2.4-4
libgcc1 - 12.3.0-4
libiwinfo-data - 2023-07-01-ca79f641-1
libiwinfo-lua - 2023-07-01-ca79f641-1
libiwinfo20230701 - 2023-07-01-ca79f641-1
libjson-c5 - 0.16-3
libjson-script20230523 - 2023-05-23-75a3b870-1
liblua5.1.5 - 5.1.5-11
liblucihttp-ucode - 2023-03-15-9b5b683f-1
liblucihttp0 - 2023-03-15-9b5b683f-1
libmbedtls12 - 2.28.7-2
libmnl0 - 1.0.5-1
libnftnl11 - 1.2.6-1
libnl-tiny1 - 2023-07-27-bc92a280-1
libpthread - 1.2.4-4
libubox20230523 - 2023-05-23-75a3b870-1
libubus-lua - 2023-06-05-f787c97b-1
libubus20230605 - 2023-06-05-f787c97b-1
libuci20130104 - 2023-08-10-5781664d-1
libuclient20201210 - 2023-04-13-007d9454-1
libucode20230711 - 2023-11-07-a6e75e02-1
libustream-mbedtls20201210 - 2023-02-25-498f6e26-1
logd - 2022-08-13-4c7b720b-2
lua - 5.1.5-11
luasocket - 3.1.0-1
luci - git-23.051.66410-a505bb1
luci-app-firewall - git-24.067.01746-69867db
luci-app-opkg - git-24.043.63812-c89a68b
luci-app-usteer - git-24.046.68798-598d231
luci-base - git-24.073.29889-cd7e519
luci-light - git-23.024.33244-34dee82
luci-mod-admin-full - git-19.253.48496-3f93650
luci-mod-network - git-24.075.44893-ac63bea
luci-mod-status - git-24.064.82650-3cbf270
luci-mod-system - git-24.067.01860-7a82b2f
luci-proto-ipv6 - git-23.355.78874-80140aa
luci-proto-ppp - git-21.158.38888-88b9d84
luci-ssl - git-23.035.26083-7550ad6
luci-theme-bootstrap - git-24.072.69878-ca51167
mtd - 26
netifd - 2024-01-04-c18cc79d-1
nftables-json - 1.0.8-1
odhcp6c - 2023-05-12-bcd28363-20
odhcpd-ipv6only - 2023-10-24-d8118f6e-1
openwrt-keyring - 2022-03-25-62471e69-2
opkg - 2022-02-24-d038e5b6-2
ppp - 2.4.9.git-2021-01-04-4
ppp-mod-pppoe - 2.4.9.git-2021-01-04-4
procd - 2023-06-25-2db83655-2
procd-seccomp - 2023-06-25-2db83655-2
procd-ujail - 2023-06-25-2db83655-2
prometheus-node-exporter-lua - 2024.06.16-2
prometheus-node-exporter-lua-nat_traffic - 2024.06.16-2
prometheus-node-exporter-lua-netstat - 2024.06.16-2
prometheus-node-exporter-lua-openwrt - 2024.06.16-2
prometheus-node-exporter-lua-wifi - 2024.06.16-2
prometheus-node-exporter-lua-wifi_stations - 2024.06.16-2
px5g-mbedtls - 10
rpcd - 2023-07-01-c07ab2f9-1
rpcd-mod-file - 2023-07-01-c07ab2f9-1
rpcd-mod-iwinfo - 2023-07-01-c07ab2f9-1
rpcd-mod-luci - 20240305-1
rpcd-mod-rrdns - 20170710
rpcd-mod-ucode - 2023-07-01-c07ab2f9-1
rssileds - 4
ubi-utils - 2.1.5-1
ubox - 2022-08-13-4c7b720b-2
ubus - 2023-06-05-f787c97b-1
ubusd - 2023-06-05-f787c97b-1
uci - 2023-08-10-5781664d-1
uclient-fetch - 2023-04-13-007d9454-1
ucode - 2023-11-07-a6e75e02-1
ucode-mod-fs - 2023-11-07-a6e75e02-1
ucode-mod-html - 1
ucode-mod-math - 2023-11-07-a6e75e02-1
ucode-mod-nl80211 - 2023-11-07-a6e75e02-1
ucode-mod-rtnl - 2023-11-07-a6e75e02-1
ucode-mod-ubus - 2023-11-07-a6e75e02-1
ucode-mod-uci - 2023-11-07-a6e75e02-1
ucode-mod-uloop - 2023-11-07-a6e75e02-1
uhttpd - 2023-06-25-34a8a74d-2
uhttpd-mod-lua - 2023-06-25-34a8a74d-2
uhttpd-mod-ubus - 2023-06-25-34a8a74d-2
urandom-seed - 3
urngd - 2023-11-01-44365eb1-1
usign - 2020-05-23-f1f65026-1
usteer - 2022-08-18-7d2b17c9-1
wireless-regdb - 2024.01.23-1
wpad - 2023-09-08-e5ccbfc6-6
`

After uninstalling  luci-proto-ppp ppp pppoe packages Luci is missing

`root@DAP1325:/tmp/log# opkg list-installed
base-files - 1554-r23809-234f1a2efa
busybox - 1.36.1-1
ca-bundle - 20230311-1
dnsmasq - 2.90-2
dropbear - 2022.82-6
firewall4 - 2023-09-01-598d9fbb-1
fstools - 2023-02-28-bfe882d5-1
fwtool - 2019-11-12-8f7fe925-1
getrandom - 2022-08-13-4c7b720b-2
hostapd-common - 2023-09-08-e5ccbfc6-6
iw - 5.19-1
iwinfo - 2023-07-01-ca79f641-1
jansson4 - 2.14-3
jshn - 2023-05-23-75a3b870-1
jsonfilter - 2024-01-23-594cfa86-1
kernel - 5.15.150-1-75c6644de129a09956bae3c06995c6f8
kmod-cfg80211 - 5.15.150+6.1.24-3
kmod-crypto-acompress - 5.15.150-1
kmod-crypto-aead - 5.15.150-1
kmod-crypto-ccm - 5.15.150-1
kmod-crypto-cmac - 5.15.150-1
kmod-crypto-crc32c - 5.15.150-1
kmod-crypto-ctr - 5.15.150-1
kmod-crypto-gcm - 5.15.150-1
kmod-crypto-gf128 - 5.15.150-1
kmod-crypto-ghash - 5.15.150-1
kmod-crypto-hash - 5.15.150-1
kmod-crypto-hmac - 5.15.150-1
kmod-crypto-manager - 5.15.150-1
kmod-crypto-null - 5.15.150-1
kmod-crypto-rng - 5.15.150-1
kmod-crypto-seqiv - 5.15.150-1
kmod-crypto-sha512 - 5.15.150-1
kmod-gpio-button-hotplug - 5.15.150-3
kmod-leds-gpio - 5.15.150-1
kmod-lib-crc-ccitt - 5.15.150-1
kmod-lib-crc32c - 5.15.150-1
kmod-lib-lzo - 5.15.150-1
kmod-mac80211 - 5.15.150+6.1.24-3
kmod-mt76-core - 5.15.150+2023-09-11-f1e1e67d-1
kmod-mt7603 - 5.15.150+2023-09-11-f1e1e67d-1
kmod-nf-conntrack - 5.15.150-1
kmod-nf-conntrack6 - 5.15.150-1
kmod-nf-flow - 5.15.150-1
kmod-nf-log - 5.15.150-1
kmod-nf-log6 - 5.15.150-1
kmod-nf-nat - 5.15.150-1
kmod-nf-reject - 5.15.150-1
kmod-nf-reject6 - 5.15.150-1
kmod-nfnetlink - 5.15.150-1
kmod-nft-core - 5.15.150-1
kmod-nft-fib - 5.15.150-1
kmod-nft-nat - 5.15.150-1
kmod-nft-offload - 5.15.150-1
kmod-ppp - 5.15.150-1
kmod-pppoe - 5.15.150-1
kmod-pppox - 5.15.150-1
kmod-slhc - 5.15.150-1
libblobmsg-json20230523 - 2023-05-23-75a3b870-1
libc - 1.2.4-4
libgcc1 - 12.3.0-4
libiwinfo-data - 2023-07-01-ca79f641-1
libiwinfo-lua - 2023-07-01-ca79f641-1
libiwinfo20230701 - 2023-07-01-ca79f641-1
libjson-c5 - 0.16-3
libjson-script20230523 - 2023-05-23-75a3b870-1
liblua5.1.5 - 5.1.5-11
libmbedtls12 - 2.28.7-2
libmnl0 - 1.0.5-1
libnftnl11 - 1.2.6-1
libnl-tiny1 - 2023-07-27-bc92a280-1
libpthread - 1.2.4-4
libubox20230523 - 2023-05-23-75a3b870-1
libubus-lua - 2023-06-05-f787c97b-1
libubus20230605 - 2023-06-05-f787c97b-1
libuci20130104 - 2023-08-10-5781664d-1
libuclient20201210 - 2023-04-13-007d9454-1
libucode20230711 - 2023-11-07-a6e75e02-1
libustream-mbedtls20201210 - 2023-02-25-498f6e26-1
logd - 2022-08-13-4c7b720b-2
lua - 5.1.5-11
luasocket - 3.1.0-1
luci-app-firewall - git-24.067.01746-69867db
mtd - 26
netifd - 2024-01-04-c18cc79d-1
nftables-json - 1.0.8-1
odhcp6c - 2023-05-12-bcd28363-20
odhcpd-ipv6only - 2023-10-24-d8118f6e-1
openwrt-keyring - 2022-03-25-62471e69-2
opkg - 2022-02-24-d038e5b6-2
procd - 2023-06-25-2db83655-2
procd-seccomp - 2023-06-25-2db83655-2
procd-ujail - 2023-06-25-2db83655-2
prometheus-node-exporter-lua - 2024.06.16-2
prometheus-node-exporter-lua-openwrt - 2024.06.16-2
prometheus-node-exporter-lua-wifi - 2024.06.16-2
prometheus-node-exporter-lua-wifi_stations - 2024.06.16-2
px5g-mbedtls - 10
rpcd - 2023-07-01-c07ab2f9-1
rpcd-mod-file - 2023-07-01-c07ab2f9-1
rpcd-mod-iwinfo - 2023-07-01-c07ab2f9-1
rpcd-mod-ucode - 2023-07-01-c07ab2f9-1
swconfig - 12
ubox - 2022-08-13-4c7b720b-2
ubus - 2023-06-05-f787c97b-1
ubusd - 2023-06-05-f787c97b-1
uci - 2023-08-10-5781664d-1
uclient-fetch - 2023-04-13-007d9454-1
ucode - 2023-11-07-a6e75e02-1
ucode-mod-fs - 2023-11-07-a6e75e02-1
ucode-mod-math - 2023-11-07-a6e75e02-1
ucode-mod-nl80211 - 2023-11-07-a6e75e02-1
ucode-mod-rtnl - 2023-11-07-a6e75e02-1
ucode-mod-ubus - 2023-11-07-a6e75e02-1
ucode-mod-uci - 2023-11-07-a6e75e02-1
ucode-mod-uloop - 2023-11-07-a6e75e02-1
uhttpd - 2023-06-25-34a8a74d-2
uhttpd-mod-lua - 2023-06-25-34a8a74d-2
uhttpd-mod-ubus - 2023-06-25-34a8a74d-2
urandom-seed - 3
urngd - 2023-11-01-44365eb1-1
usign - 2020-05-23-f1f65026-1
usteer - 2022-08-18-7d2b17c9-1
wireless-regdb - 2024.01.23-1
wpad - 2023-09-08-e5ccbfc6-6
`

Please check and verify. I can't find any syslog for OPKG at the moment so I can't post it here.

### OpenWrt version

r23809-234f1a2efa

### OpenWrt release

23.05.3

### OpenWrt target/subtarget

ramips/mt76x8

### Device

D-Link DAP-1325 A1

### Image kind

Official downloaded image

### Steps to reproduce

Uninstall  luci-proto-ppp ppp pppoe via luci

### Actual behaviour

Luci is uninstalled

### Expected behaviour

Luci won't uninstalled only PPP package for luci uninstalled

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by pkgadd** [comment]
That is not a bug, but expected and intended behaviour. luci/ luci-ssl is a metapackage depending on luci-proto-ppp, you can't have the former without the later (but as being an empty metapackage, removing the former won't actually remove the webinterface either).

**Comment by jow-** [comment]
It will just remove empty meta collection packages.
