### ISSUE TITLE
OpenWrt creates a device for unchecked local VLAN 

### ISSUE THREAD

**Issue by cmonty14** [openwrt/openwrt#15964]
### Describe the bug

Following the [Security Considerations with VLANs](https://openwrt.org/docs/guide-user/network/dsa/dsa-mini-tutorial#security_considerations_with_vlans) I defined this _Bridge VLAN filtering_:
![Bildschirmfoto vom 2024-07-17 18-27-14](https://github.com/user-attachments/assets/e1c27503-7a8d-4e59-8e61-48f18ec68a39)

### OpenWrt version

r23809-234f1a2efa

### OpenWrt release

23.05.3

### OpenWrt target/subtarget

ramips/mt7621

### Device

MikroTik RouterBOARD 760iGS

### Image kind

Official downloaded image

### Steps to reproduce

1. LuCI > Network > Interfaces > Devices
2. Configure LAN bridge: br-lan
3. Bridge VLAN filtering
4. Add new VLAN ID 999, uncheck local, set Untagged + Is Primary VLAN

This creates following config in _/etc/config/network_:
```
config bridge-vlan
	option device 'br-lan'
	option vlan '999'
	option local '0'
	list ports 'lan4:u*'
	list ports 'lan5:u*'
	list ports 'sfp:u*'
```

### Actual behaviour

According to Wiki, "VLAN 999 is not used anywhere else and is only there for added security", however I can see br-lan.999 in the device list and I can assign an interface to it.
![Bildschirmfoto vom 2024-07-17 18-39-11](https://github.com/user-attachments/assets/627ccda4-a239-4fec-85b3-ed28f885ce3d)

### Expected behaviour

There must be **no** device `br-lan.999`.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Do you see it in brctl or it is some usermode logic only?

**Comment by cmonty14** [comment]
Just to be clear about the information you request, can you please specify the command syntax?
And what do you mean with "usermode logic"?

**Comment by brada4** [comment]
I mean uci luci has setting in all corners but what is in `brctl show` configured in kernel.

**Comment by cmonty14** [comment]
> I mean uci luci has setting in all corners but what is in `brctl show` configured in kernel.

Actually I don't say there's an issue with the bridge.
Anyway, here's the requested output:
![Bildschirmfoto vom 2024-07-19 07-31-00](https://github.com/user-attachments/assets/8a54dfb7-673e-459f-ad24-56e4f2b59490)

What I say is that there's an device `br-lan.999` that should not exist.

**Comment by brada4** [comment]
Post text output.
And from
```
bridge vlan show
```

**Comment by cmonty14** [comment]
> Post text output. And from
> 
> ```
> bridge vlan show
> ```

Command `bridge` does not exist.

**Comment by brada4** [comment]
It is how it works, the interface is disconnected from host.
`bridge` command is in package `ip-bridge`

**Comment by cmonty14** [comment]
> It is how it works, the interface is disconnected from host.

How do you identify this?

Here's the output of `bridge vlan show`:
```
root@rb760igs:~# bridge vlan show
port              vlan-id  
sfp               10
                  20
                  30
                  40
                  100
                  999 PVID Egress Untagged
lan3              10
                  20
                  30
                  40
                  100 PVID Egress Untagged
lan4              10
                  20
                  30
                  40
                  100
                  999 PVID Egress Untagged
lan5              10
                  20
                  30
                  40
                  100
                  999 PVID Egress Untagged
br-lan            10
                  20
                  30
                  40
                  100
```

**Comment by brada4** [comment]
But wire is down, openwrt is not connected.

**Comment by cmonty14** [comment]
> But wire is down, openwrt is not connected.

This is a screenshot of the last 2 interfaces on my device:
![image](https://github.com/user-attachments/assets/4cb61809-6c14-4268-a9ab-174351a9e2fa)
Besides the missing IPv6 adress, I cannot detect any other difference.
Therefore I don't see the expected "openwrt is not connected".
Please advise.

**Comment by brada4** [comment]
Please share /etc/config/network. You knowingly assigned IP address to interface, does not look like unchecked.

**Comment by cmonty14** [comment]
> You knowingly assigned IP address to interface, does not look like unchecked.

This is correct.
Means, I can create an interface for device br-lan.999.

But this contradicts the statement in [Wiki](https://openwrt.org/docs/guide-user/network/dsa/dsa-mini-tutorial#security_considerations_with_vlans) saying:
"Note: Because local is not checked for VLAN 90, OpenWrt won't even create a device for it and there should be no interface for it, unlike the other VLANs."

So let me make clear:

- I add a VLAN ID with local unchecked
- OpenWrt creates a device
- I can create an interface for this device

The last 2 steps **must not be possible**. 

Do we have a common understanding of this issue?

**Comment by brada4** [comment]
You have to post in forums/documentation regarding false statement.

**Comment by cmonty14** [comment]
> You have to post in forums/documentation regarding false statement.

Why do you think the statement is false?
If I add a VLAN ID **with local unchecked**, and OpenWrt creates a device, what's the difference to  adding a VLAN ID **with local checked**?

Nobody has proved yet that this is an issue with LuCI.

**Comment by cmonty14** [comment]
This issue is not reproducable with OpenWrt 23.05.4

**Comment by cmonty14** [comment]
The issue is not reproducible with latest OpenWrt release.

**Comment by peterwillcn** [comment]
ok
