### ISSUE TITLE
[23.05] x86_64: unable to use Docker due to missing KERNEL_EXT4_FS_SECURITY feature

### ISSUE THREAD

**Issue by odkrys** [openwrt/openwrt#15970]
### Describe the bug

https://forum.openwrt.org/t/docker-pull-fails-failed-to-register-layer-operation-not-supported/138253

I did a clean update from 21.02.6 to 23.05.4. But docker doesn't work. The problem appears to have existed since version 22.x. I don't know why the issue wasn't resolved.

https://github.com/MichaIng/DietPi/issues/7102
https://cloud.google.com/container-optimized-os/docs/concepts/supported-filesystems?hl=en

### OpenWrt version

r24012-d8dd03c46f

### OpenWrt release

23.05.4

### OpenWrt target/subtarget

x86/64

### Device

mini pc

### Image kind

Official downloaded image

### Steps to reproduce

docker pull blah/blah

### Actual behaviour

docker: failed to register layer: lsetxattr security.capability /usr/sbin/nginx: operation not supported.

### Additional info
```
# CONFIG_KERNEL_EXT4_FS_POSIX_ACL is not set
# CONFIG_KERNEL_EXT4_FS_SECURITY is not set
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Your test case does not exist.
As for why - because you did not submit a PR?

**Comment by odkrys** [comment]
I also had the problem. I just downgraded docker and dockerd to version 20.10.17 in the 21.02 repository.

**Comment by odkrys** [comment]
I verified this myself today by building an image with the above two kernel flags and it fixed the docker pull issue. A PR is needed.

**Comment by joez** [comment]
The `dockerd` package has an option for this (`feeds/packages/utils/dockerd/Config.in`), just enable it and build the firmware by yourself

```
	config DOCKER_STO_EXT4
		bool "Enables support for ext3 or ext4 as the backing filesystem"
		default n
		select KERNEL_EXT4_FS_POSIX_ACL
		select KERNEL_EXT4_FS_SECURITY
```

**Comment by ynezz** [comment]
FYI https://github.com/openwrt/openwrt/pull/16181 once merged should fix this in snapshots and in upcoming next release, but unfortunately the changes are a bit invasive, so unlikely to be backported into 23.05 release, so this will remain broken. Anyway, help with testing welcome!
