### ISSUE TITLE
WiFi Broken on Linksys MX8500

### ISSUE THREAD

**Issue by OpenWRT-fanboy** [openwrt/openwrt#16049]
### Describe the bug

Despite recently becoming officially supported in SNAPSHOT, WiFi on Linksys MX8500 does not work at all.

### OpenWrt version

all SNAPSHOT

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Linksys MX8500

### Image kind

Official downloaded image

### Steps to reproduce

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=9bdaebaff323e554046ce354092832c956b2ad5e

### Actual behaviour

ath11k c000000.wifi: failed to fetch board data for bus=ahb,qmi-chip-id=0,qmi-board-id=255,variant=Linksys-MX8500 from ath11k/IPQ8074/hw2.0/board-2.bin
ath11k c000000.wifi: failed to fetch board data for bus=ahb,qmi-chip-id=0,qmi-board-id=255 from ath11k/IPQ8074/hw2.0/board-2.bin
ath11k c000000.wifi: failed to fetch board data for bus=ahb,qmi-chip-id=0,qmi-board-id=255 from ath11k/IPQ8074/hw2.0/board-2.bin
ath11k c000000.wifi: failed to fetch board.bin from IPQ8074/hw2.0
ath11k c000000.wifi: qmi failed to fetch board file: -12
ath11k c000000.wifi: failed to load board data file: -12

### Expected behaviour

no error messages if proper board-2.bin is loaded

### Additional info

merging this PR will fix the WiFi 2G and 5G bands:

https://github.com/openwrt/firmware_qca-wireless/pull/37

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by randyg503** [comment]
bot is incorrect, this impacts all MX8500 SNAPSHOTs
