### ISSUE TITLE
Explanation for my IP ban

### ISSUE THREAD

**Issue by Kcajminer2312** [openwrt/openwrt#16055]
### Describe the bug

This is not a bug repoort, I have been IP banned after I deleted my account and created it again
is there anyway of me contacting slh or peter sherman

slh ip banned me, but did not give me time to read there message
I want my account back
I left myself, I was not banned
so why did I get banned

### OpenWrt version

N\A

### OpenWrt release

N\A

### OpenWrt target/subtarget

N\A

### Device

N\A

### Image kind

Self-built image

### Steps to reproduce

N\A

### Actual behaviour

N\A

### Expected behaviour

N\A

### Additional info

N\A

### Diffconfig

```text
N\A
```

### Terms

- [ ] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by vincejv** [comment]
Did you try OFTC Irc? They are online there

**Comment by thess** [comment]
Not a dev issue - User has been banned from forum.
