### ISSUE TITLE
uhttpd is not reloaded when certificate has changed

### ISSUE THREAD

**Issue by bidord** [openwrt/openwrt#16075]
### Describe the bug

Calling `/etc/init.d/uhttpd reload` after a change to the certificate file used by `uhttpd` has no effect.

In particular, if `uhttpd` uses an ACME certificate and that certificate is automatically renewed: `uhttpd` has to be manually restarted for the renewal to be effective.

`/etc/init.d/uhttpd reload` is [triggered by acme.renew event](https://github.com/openwrt/openwrt/blob/d604b2699b6015f99ff194b34f532958bde7d442/package/network/services/uhttpd/files/uhttpd.init#L273) but it has no effect.

### OpenWrt version

r23497-6637af95aa

### OpenWrt release

23.05.0

### OpenWrt target/subtarget

ipq806x/generic

### Device

Netgear Nighthawk X4S R7800

### Image kind

Official downloaded image

### Steps to reproduce

For convenience, here is a simple way to reproduce that does not require ACME or an actual certificate renewal. This should work with any certificate (including self-signed):

- Make a change to your certificate (here, we are just appending a blank line to the file to make it look like it has changed):

  ```sh
  UHTTPD_CERT=$(uci get uhttpd.main.cert)
  cp "$UHTTPD_CERT" "$UHTTPD_CERT.orig"
  echo "" >> "$UHTTPD_CERT"
  ```

- Reload uhttpd. Compare its PID before and after to see if service has actually been restarted:

  ```sh
  pidof uhttpd
  /etc/init.d/uhttpd reload
  pidof uhttpd
  ```

- Cleanup:

  ```sh
  mv "$UHTTPD_CERT.orig" "$UHTTPD_CERT"
  ```

### Actual behaviour

uhttpd has not been restarted.

### Expected behaviour

uhttpd should have been restarted.

### Additional info

If you try this with a different certificate (not just an extra blank line), you will also notice that HTTPS is still using the old certificate.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by httpstorm** [comment]
@bidord 
Whatever code is responsible for reloading the `uhttpd` configuration should use `restart` instead of `reload`.
``` bash
# I use this script as a workaround
# /etc/hotplug.d/acme/20-uhttpd 
if [ "$ACTION" = renewed ]; then
	# reload config
	/etc/init.d/uhttpd restart
fi
```

**Comment by Spudz76** [comment]
This matches the behavior of most httpd's, you have to use `restart` even with nginx for example, `reload` is not supposed to load new certs because it shouldn't be able to read the privileged files (key mostly) after it has dropped its privileges.  So the acme hook should be fixed to use `restart` probably.

**Comment by httpstorm** [comment]
@Spudz76 
That's interesting to know. I use the [httpstorm](https://httpstorm.com) web server which is able to add new certificates using `reload` and there is no need to restart it, even though it also drops privileges.

**Comment by httpstorm** [comment]
@bidord 
> But wouldn't fixing the init script so that reload is able to detect a certificate change be an even better approach?

Seems reasonable.

**Comment by Spudz76** [comment]
Yes nginx on Debian-based distros, where keys belong in `/etc/ssl/private/` and that entire subtree is not accessible by anyone but root.  nginx with less-secured keys might work but I thought it does not even attempt to read them on HUP signal.  I know in my acme/certbot hooks on real websites I have to use `restart` is all.  Have never desired anything beyond self-signed on an appliance.

I was mostly saying "this is not surprising, but a reload doing a restart would be".
