### ISSUE TITLE
WRT1900 / WRT1200AC v2 softoffload does not work

### ISSUE THREAD

**Issue by ja16779** [openwrt/openwrt#16184]
### Describe the bug

I have a par of linksys router wrt1900 / wrt 1200 and the softoffloading does not work, when enable the pages does not open, ever the ping answer

### OpenWrt version

r24012-d8dd03c46f

### OpenWrt release

23.05.4

### OpenWrt target/subtarget

mvebu/cortexa9

### Device

Linksys WRT1900AC v2

### Image kind

Official downloaded image

### Steps to reproduce

enable firewall soft offload

### Actual behaviour

Forwarding stops

### Expected behaviour

Accelerated forwarding happens

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by anomeome** [comment]
Forum [thread](https://forum.openwrt.org/t/wrt1200ac-does-not-work-softoffloading/207507) with WIP link which is the apparent resolution.

**Comment by brada4** [comment]
In the forum thread @jow- was mentioned as knowledgeable on subject. Essence - when dsa user ports are excluded from soft offload abusing latest fw4 code - offloaded forwarding starts to happen. Which avoids and softly points to a bug or shortage in particular DSA driver set.

**Comment by brada4** [comment]
Steps to reproduce:
enable firewall soft offload
Actual behaviour:
Forwarding stops
Expected behaviour:
Accelerated forwarding happens

**Comment by brada4** [comment]
You can avoid suspected buggy DSA driver using latest firewall4 code
https://forum.openwrt.org/t/wrt1200ac-does-not-work-softoffloading/207507/12?u=brada4
I.e. offload discharges to bridge interface additionally keeping LAN ARP and wifi roaming undisturbed by itself, still doing heaviest packet re-addressing part fast.
