### ISSUE TITLE
RPI-5 memory leak

### ISSUE THREAD

**Issue by AQPSal** [openwrt/openwrt#16192]
### Describe the bug

It takes about 48 hours to use all of my rpi-5 4GB and router reboots. Log is lost upon reboot.

I tried to identify the application causing the leak but I am not knowledgeable enough to figure it out. While I only noticed this week, it has been happening since June (must have updated the router with a new snapshot around then). Please let me know what information you would need to diagnose.

![Untitled](https://github.com/user-attachments/assets/91476192-924c-4dee-b183-4dcc050e18e4)

### OpenWrt version

r27143-0b7d99147b

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

bcm27xx/bcm2712

### Device

Raspberry Pi 5 Model B Rev 1.0

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Basic router functions fit into 64MB RAM
Forum is a better place to dismantle heap if packages. Graph looks like garbage-collecting java (not avail for openwrt but may be present in container) or a memory leak yielding widely logged crash

**Comment by AQPSal** [comment]
> Basic router functions fit into 64MB RAM Forum is a better place to dismantle heap if packages. Graph looks like garbage-collecting java (not avail for openwrt but may be present in container) or a memory leak yielding widely logged crash

Its an image of the collectd memory tab showing the progressive use of memory. When rebooted, the system uses less than 100MBs. PS AUX, htop does not reveal any culprits

**Comment by brada4** [comment]
>  identify the application causing the leak but I am not knowledgeable enough to figure it

Bug tracker is not a support forum. Here you have to clearly identify bug source.

**Comment by AQPSal** [comment]
> > identify the application causing the leak but I am not knowledgeable enough to figure it
> 
> Bug tracker is not a support forum. Here you have to clearly identify bug source.

I see your point. I'll bring it up in the forum. Thx.

**Comment by Noltari** [comment]
@AQPSal my RPi 5 (8G) has been running 24/7 for the past months without this issue, so it must be specific to any of the packages that you have installed on your device.
Therefore, I don't think that this is issue is related to the RPi 5.

**Comment by brada4** [comment]
Xref: https://forum.openwrt.org/t/continuous-ram-memory-consumption-increase-over-time/207942
brief: agh glitch

**Comment by AQPSal** [comment]
In my case I found the issue seems to be caused by collectd (by way of installing programs one by one) - I am not sure which plugin or if it is the app itself. This repo may not be the ideal place report this; nevertheless, leaving the information here just in case.
