### ISSUE TITLE
wpad-mbedtls breaks network config

### ISSUE THREAD

**Issue by grosjo** [openwrt/openwrt#16197]
### Describe the bug

  Compile your rom with wpad-mbedtls
  Device boots only once (fresh config). Second time, network config is considered invalid

### OpenWrt version

Latest git

### OpenWrt release

Latest git

### OpenWrt target/subtarget

ath9k

### Device

Comcast WR650v2

### Image kind

Self-built image

### Steps to reproduce

1 - Build with wpad-basic-mbedtls
2 - Confirm it works
3 - Switch to wpad-mbedtls
4 - It boots only once (existing config is refused at next boot)

### Actual behaviour

Config considered broken and device netwoirk not starting

### Expected behaviour

Saved config from first reboot should be working

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
What is in actual /etc/config/wireless ?

**Comment by grosjo** [comment]
There is no config, as the rom boots only once, from a clean install (no config files), a simple reboot crashes teh device

**Comment by grosjo** [comment]
No, device does not start in safemod

The only way to make it start after that, it to re-install a fresh rom

I always the initial few pigns on 192.168.1.1 but once the system starts, it seems reading the config and fails

**Comment by brada4** [comment]
You did not pust two diffconfigs with working and not working configurations, nor any version tags. How do you think this report is actionable in any way?

**Comment by grosjo** [comment]
Because there is not config diff, as their is not config

Only way to start is a fresh install (no config), but one restart and the device fails

**Comment by grosjo** [comment]
> @grosjo do not build with wpad-mbedtls, install it later, that way you will be able to boot into failsafe mode, isn't it?

Hi @romanovj , not the " failsafe mode" does not work (this is not new, never worked for me on any of my devices)

**Comment by DazzyWalkman** [comment]
I have similar experience, caused by the too big firmware leaving not enough flash space to properly initialize overlayfs. I'm not sure you've come across the same situation though.

**Comment by brada4** [comment]
Simple `df` will confirm it, overlay has to have 200-300kb for detected configuration, then 3x flash blocks sized 4k-128k (check /proc/mtd for actual value)

**Comment by grosjo** [comment]
Recent git has not the pb anymore
