### ISSUE TITLE
a266230 is breaking mediatek builds

### ISSUE THREAD

**Issue by LuisMitaHL** [openwrt/openwrt#16214]
### Describe the bug

Hi,
a2662309aae1655966d7d8f31b71ddc6edbede87 is breaking Mediatek builds.
Reverting the commit fix the problem

### OpenWrt version

a2662309aae1655966d7d8f31b71ddc6edbede87

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

Cudy TR3000

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
See https://github.com/openwrt/openwrt/pull/16211

**Comment by robimarko** [comment]
Fixed via:
https://github.com/openwrt/openwrt/commit/963be1423f64156fa66a8a94cf0207ce2945bf34
