### ISSUE TITLE
ERROR: target/linux failed to build.

### ISSUE THREAD

**Issue by snakwu** [openwrt/openwrt#16258]
### Describe the bug

rm -f /home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/generic-kernel.bin
cp /home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/bzImage /home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/generic-kernel.bin
cp /home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/generic-kernel.bin /home/snakwu/openwrt/openwrt/bin/targets/x86/64/openwrt-x86-64-generic-kernel.bin
[ -f /home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/generic-kernel.bin -a -f /home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/root.squashfs ]
dd if=/home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/root.squashfs >> /home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-x86-64-generic-squashfs-rootfs.img.gz
107904+1 records in
107904+1 records out
55247222 bytes (55 MB, 53 MiB) copied, 0.163623 s, 338 MB/s
dd if=/home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-x86-64-generic-squashfs-rootfs.img.gz of=/home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-x86-64-generic-squashfs-rootfs.img.gz.new bs=4294967296 conv=sync
dd: memory exhausted by input buffer of size 4294967296 bytes (4.0 GiB)
make[5]: *** [Makefile:154: /home/snakwu/openwrt/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-x86-64-generic-squashfs-rootfs.img.gz] Error 1
make[5]: Leaving directory '/home/snakwu/openwrt/openwrt/target/linux/x86/image'
make[4]: *** [Makefile:24: install] Error 2
make[4]: Leaving directory '/home/snakwu/openwrt/openwrt/target/linux/x86'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/home/snakwu/openwrt/openwrt/target/linux'
time: target/linux/install#90.52#6.73#66.84
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:32: target/linux/install] Error 1
make[2]: Leaving directory '/home/snakwu/openwrt/openwrt'
make[1]: *** [target/Makefile:26: /home/snakwu/openwrt/openwrt/staging_dir/target-x86_64_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/snakwu/openwrt/openwrt'
make: *** [/home/snakwu/openwrt/openwrt/include/toplevel.mk:248: world] Error 2

### OpenWrt version

linux-x86_64

### OpenWrt release

linux-x86_64

### OpenWrt target/subtarget

linux-x86_64/

### Device

linux-x86_64/

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by neheb** [comment]
```
dd: memory exhausted by input buffer of size 4294967296 bytes (4.0 GiB)
```

I question how you did this.
