### ISSUE TITLE
MTD: Please consider backporting the support for Winbond W25N04KV spi nand, it's already in main kernel 6.9.

### ISSUE THREAD

**Issue by Rimits** [openwrt/openwrt#16259]
### Describe the bug
U-boot (the version bundled with openwrt snapshot) already supports this nand chip, but the kernel 6.6 doesn't.
The patch for W25N04KV is alredy in the mainline kernel 6.9. 
[https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/drivers/mtd/nand/spi/winbond.c?h=v6.11-rc4&qt=grep&q=winbond](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/drivers/mtd/nand/spi/winbond.c?h=v6.11-rc4&qt=grep&q=winbond)

Please consider backporting it. Thanks.

### OpenWrt version

snapshot

### OpenWrt release

snapshot

### OpenWrt target/subtarget

mediatek/filogic

### Device

modified mt7986 router XD

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
Here you go: https://github.com/openwrt/openwrt/pull/16272

**Comment by hauke** [comment]
Do you have a device with this chip?

**Comment by Rimits** [comment]
My router was modified with this chip,so it didn't really count.
But the u-boot support is added by ```./openwrt/package/boot/uboot-mediatek/patches/100-22-mtd-spi-nand-backport-from-upstream-kernel.patch```
Maybe the author of this patch knows some models that use this chip.
Since u-boot support is added, why not adding the kernel support to make devices with this chip really work.

**Comment by namiltd** [comment]
Chip added, topic to close,
