### ISSUE TITLE
KuWfi  (YunCore) AX835 LEDs not working

### ISSUE THREAD

**Issue by matlab22** [openwrt/openwrt#16292]
### Describe the bug

I can not configure the LED behavior of the AX835 router. I can set them up using LUCI but no LED is turning on when expected.

![Screenshot 2024-08-30 232857](https://github.com/user-attachments/assets/623879d7-6768-453f-b25d-c16422685e09)

### OpenWrt version

r24012-d8dd03c46f

### OpenWrt release

23.05.4

### OpenWrt target/subtarget

mediatek/filogic

### Device

YunCore AX835

### Image kind

Official downloaded image

### Steps to reproduce

```
root@OpenWrt:/#ls/sys/class/leds/ 
blue:wifi5   green:wifi2  hwwatchdog   mt76-phy0    mt76-phy1    red:system
root@OpenWrt:/# echo 0 > /sys/class/leds/blue:wifi5/brightness
root@OpenWrt:/# echo 1 > /sys/class/leds/blue:wifi5/brightness
root@OpenWrt:/# echo 1 > /sys/class/leds/green:wifi2/brightness
root@OpenWrt:/# echo 1 > /sys/class/leds/blue:wifi5/brightness
root@OpenWrt:/# echo 1 > /sys/class/leds/green:wifi2/brightness
root@OpenWrt:/# echo 1 > /sys/class/leds/hwwatchdog/brightness
root@OpenWrt:/# echo 1 > /sys/class/leds/mt76-phy0/brightness
root@OpenWrt:/# echo 1 > /sys/class/leds/mt76-phy1/brightness
root@OpenWrt:/# echo 1 > /sys/class/leds/red:system/brightness
```
nothing is turned on.
I also tried:
```
echo none > /sys/class/leds/red:system/trigger
echo 1 > /sys/class/leds/red:system/brightness
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by Neustradamus** [comment]
@yogo1212: Can you check this ticket?

**Comment by yogo1212** [comment]
hwwatchdog is not a led.
mt76-phy0 and mt76-phy1 are not wired to anything, afaik.
green behaves normally after setting its trigger to `none`.

blue and red light up briefly after setting brightness to 1 but go back to being dark immediately afterwards.
i'm sure this was working at some point in my staging branch.
@matlab22 can you test whether there is blinking for you as well?

@Neustradamus you appear to be very interested - are you using ax835 as well?

**Comment by yogo1212** [comment]
another issue (regular resets) is forcing me to look back into device support for the yuncore ax835.

the problem lies with the [voltage regulator](https://github.com/openwrt/openwrt/blob/main/target/linux/mediatek/dts/mt7981b-yuncore-ax835.dts#L33).

i suspect gpio really controls a "switch" and there's a transistor of some kind sitting behind that gpio. the regulator doesn't trigger it. maybe it's not a FET and there's not enough current. pulling the pin up using gpio does enable the functioning of all LEDs (regardless of how they're driven).

**Comment by yogo1212** [comment]
there is no voltage at all

**Comment by yogo1212** [comment]
found it!

Documentation/devicetree/bindings/regulator/fixed-regulator.yaml
```
  enable-active-high:
    description:
      Polarity of GPIO is Active high. If this property is missing,
      the default assumed is Active low.
    type: boolean

**Comment by yogo1212** [comment]
positive test - https://github.com/openwrt/openwrt/pull/16839

**Comment by Neustradamus** [comment]
@matlab22: Can you check the @yogo1212 PR?
- https://github.com/openwrt/openwrt/pull/16839

**Comment by matlab22** [comment]
LEDs are working on r28009-11ba2b141f thank you :)
