### ISSUE TITLE
ath10k-ct fails to build due to unselected mac80211 debugfs option

### ISSUE THREAD

**Issue by Olipro** [openwrt/openwrt#16302]
### Describe the bug

When building with the Candelatech `ath10k-ct` packages, because warnings are treated as errors, the build will fail if `mac80211` does not have the `debugfs` option enabled since the `ath10k-ct` package has a C header file containing a `#warning` line that detects the option isn't selected.

This can of course be trivially worked around by enabling the debugfs option for `mac80211` in the `menuconfig`

The warning states that you are encouraged to enable this option, however, doing so is not mandatory.

Therefore, in terms of fixing the problem, either warnings should not be treated as errors, or the package should require the mac80211 debugfs option to be selected.

### OpenWrt version

c6f04f718ec89561f2261f2388857baa126eaa50

### OpenWrt release

c6f04f718ec89561f2261f2388857baa126eaa50

### OpenWrt target/subtarget

ipq806x/R7800

### Device

N/A, this is bug is at build time.

### Image kind

Self-built image

### Steps to reproduce

Choose one of the `ath10k-ct` wifi firmwares without enabling the debugfs option for `mac80211` and attempt to build

### Actual behaviour

build fails due to a `#warning` in the `ath10k-ct`'s `wmi.h` that detects the debugfs option not being turned on due to warnings treated as errors.

### Expected behaviour

build doesn't fail.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
Can you provide the required diffconfig so I can reproduce this?

**Comment by robimarko** [comment]
Ok, simply disabling mac80211 debugfs support is enough.
