### ISSUE TITLE
x86/64: CPU never reaches minimum frequency (AMD Ryzen 7 5800U)

### ISSUE THREAD

**Issue by graysky2** [openwrt/openwrt#16313]
### Describe the bug

When booted into OpenWrt, the CPU freq never hits the minimum frequency of 400 MHz which it does under Arch Linux (dual booting on the same hardware).  Both distros run the 6.6.48 kernel and have the same scaling_governor settings:
```
# cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
powersave
# cat /sys/devices/system/cpu/amd_pstate/status
active
# cat /sys/devices/system/cpu/cpufreq/policy0/scaling_driver
amd-pstate-epp
```

On Arch: 400 MHz
On OpenWrt: 1,384 MHz

### OpenWrt version

r27283-85f0128851

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

x86/64

### Device

HC Technology.,Ltd. HCAR5000-MI

### Image kind

Official downloaded image

### Steps to reproduce

1. Boot image
2. Confirm scaling governor, p-state driver (see above)
3. Run `cat /sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq`

### Actual behaviour

CPU never throttles down to the minimum frequency

### Expected behaviour

The CPU should idle at minimum frequency

### Additional info

I ever tried resetting to factory settings (stock `/etc/config/network`) and disabled all interfaces, and daemons and confirmed with `htop` that the CPU was as idle, but still the CPU would not throttle down to the minimum frequency.

Interestingly, if I `echo disable > /sys/devices/system/cpu/amd_pstate/status` I am able to hit the lowest frequency of 400 MHz under OpenWrt. I think that establishes two things:

- The processor is physically able to idle at 400 MHz under OpenWrt
- Something is likely wrong with the way the amd p-state governor operates under OpenWrt

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jisakiel** [comment]
As I mentioned on https://github.com/openwrt/openwrt/pull/16317#issuecomment-3868261748 I believe the pull that fixed this got lost by a refresh https://github.com/openwrt/openwrt/commit/805b5d893c424719d845d2840bdd3e41932582f5 .

EDIT: nvm, NO_HZ seems there even if some settings were dropped along the way https://github.com/openwrt/openwrt/blame/main/target/linux/x86/config-6.12#L326 . My bad!
