### ISSUE TITLE
Scammy spam commenters 

### ISSUE THREAD

**Issue by jaknz** [openwrt/openwrt#16392]
### Describe the bug

You’ve got some scammy spam crypto comments, and there seems to be no way to report them. 

E.g. 
https://github.com/openwrt/openwrt/pull/3996

### OpenWrt version

N/A

### OpenWrt release

N/A

### OpenWrt target/subtarget

N/A

### Device

N/A

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by champtar** [comment]
Thanks for reporting, don't hesitate to report again if you see some more
