### ISSUE TITLE
bpf-headers: build failure since kernel 5.15 support dropped by openwrt

### ISSUE THREAD

**Issue by alanswanson** [openwrt/openwrt#16431]
### Describe the bug

Openwrt build fails with bpf-headers as its makefile is now unable to find its hard-coded 5.15 kernel headers after kernel 5.15 was dropped for all targets today.

```
make[3]: Entering directory '/srv/openwrt/git/package/kernel/bpf-headers'
Makefile:18: /srv/openwrt/git/include/kernel-5.15: No such file or directory
make[3]: *** No rule to make target '/srv/openwrt/git/include/kernel-5.15'.  Stop.
make[3]: Leaving directory '/srv/openwrt/git/package/kernel/bpf-headers'
time: package/kernel/bpf-headers/compile#0.08#0.03#0.12
    ERROR: package/kernel/bpf-headers failed to build.
make[2]: *** [package/Makefile:177: package/kernel/bpf-headers/compile] Error 1
```

Required as dependency for qosify via kmod-sched-bpf.

### OpenWrt version

git

### OpenWrt release

git

### OpenWrt target/subtarget

.

### Device

.

### Image kind

Self-built image

### Steps to reproduce

Enable qosify/kmod-sched-bpf in configuration.

### Actual behaviour

Build error.

### Expected behaviour

Build successful.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by nbd168** [comment]
Fixed in 86251a7034942ecd7cc2cbfeb0625c0475bc0780
