### ISSUE TITLE
Mt7621 Builds Are Failing

### ISSUE THREAD

**Issue by khanjui** [openwrt/openwrt#16455]
### Describe the bug

https://buildbot.openwrt.org/images/#/builders/61

Failing for 5 days now.

### OpenWrt version

.

### OpenWrt release

.

### OpenWrt target/subtarget

mt7621

### Device

.

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
Fixed: https://github.com/openwrt/openwrt/commit/746e894877e5130a7d5227cd90f90dfe18cc274b
