### ISSUE TITLE
All radios on AX6S/AX3200 don't work because of 6GHz

### ISSUE THREAD

**Issue by HW-OLE** [openwrt/openwrt#16468]
### Describe the bug

After doing a sysupgrade to the newest SNAPSHOT all of my radios won't come up and the frequency is reported as 6GHz, although this device doesn't support it. I suspect it's a issue in the mt76 driver because Mediatek now maybe seems to offer a mt7622 with WiFI 7 (source: https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/+log)

### OpenWrt version

r27563-7850e19767

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Xiaomi Redmi Router AX6S

### Image kind

Official downloaded image

### Steps to reproduce

Just create a 5GHz radio and notice it won't come up, it'll show the following

### Actual behaviour

All radios don't come up and the frequency shows that it's operating at 6GHz although this Device doesn't have 6.x GHz

### Expected behaviour

The radios come up normally and the radio shows a frequency in the 5GHz range because it's actually operating in that range

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by HW-OLE** [comment]
![Bildschirmfoto_2024-09-23_21-04-20](https://github.com/user-attachments/assets/ee0551f0-bcbf-48c9-898c-445f8927ae0a)
Sorry for editing but I had to blur sensible information

**Comment by rany2** [comment]
> source: https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/+log)

Can't reproduce on my Redmi AX6S on latest SNAPSHOT. Just to confirm, you're not applying any of the MTK patches you linked to?

**Comment by HW-OLE** [comment]
No I didn't Just pure Stock OpenWRT. Will reflash the factory one tomorrow and start from Scratch

**Comment by HW-OLE** [comment]
OK, the fix was fairly easy. I just had to recreate all of the SSIDs and now it's just working fine

**Comment by jkasten2** [comment]
I have a Linksys E8450 (has the  MT7915E chip) with OpenWrt 24.10.2 and ran into this issue as well. I had to set the "Country Code" from "driver default" to my country (US in my case) in order to avoid this bug.
