### ISSUE TITLE
请问openwrt怎么设置纯IPV6方式？

### ISSUE THREAD

**Issue by xibeilang0616** [openwrt/openwrt#16465]
### OpenWrt version

23.05-SNAPSHOT

### OpenWrt release

23.05-SNAPSHOT

### OpenWrt target/subtarget

IPV4&IPV6

### Device

CMCC rax3000m

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
English?

**Comment by xibeilang0616** [comment]
> English?

I'm Chinese, I don't speak English

**Comment by brada4** [comment]
Probably you should ask your general question at immortalwrt chat then?
(google translation indicates it is not a bug report, it is a general usage question)

**Comment by jow-** [comment]
Please use the forums or mailing lists for support questions. Also please ask your questions in english.
