### ISSUE TITLE
Network/Switch menu missing on Netgear WAX206

### ISSUE THREAD

**Issue by marcusathalide** [openwrt/openwrt#16528]
### Describe the bug

I have recently in installed 23.05.4 on a WAX206. Unfortunately I was not able to find the Network/Switch menu to configure VLANs. It seems that current configuration is missing to trigger the display of the menu.

### OpenWrt version

r24012-d8dd03c46f

### OpenWrt release

23.05.4

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Netgear WAX206

### Image kind

Official downloaded image

### Steps to reproduce

No special procedure. After installation the menu point is missing (Network/Switch).

### Expected behaviour

Menu Switch is diplay in Network tab to allow VLAN configuration. 

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
This is a DSA device, it has no dedicated switch menu. You can configure VLANs in the br-lan device settings.

**Comment by marcusathalide** [comment]
Thanks for the hint. I was not aware of that. :)
