### ISSUE TITLE
Create a release of version 23.05.5 on GitHub

### ISSUE THREAD

**Issue by Slava-Shchipunov** [openwrt/openwrt#16562]
Hi! Please create a release of 23.05.5 here on github - I need it to automatically trigger the build of amnezia wireguard packages in my repository https://github.com/Slava-Shchipunov/awg-openwrt

**Comment by robimarko** [comment]
Done:
https://github.com/openwrt/openwrt/releases/tag/v23.05.5

**Comment by Slava-Shchipunov** [comment]
> Done:
> https://github.com/openwrt/openwrt/releases/tag/v23.05.5

Please, can you also mark it as latest?

**Comment by robimarko** [comment]
Done
