### ISSUE TITLE
ramips: ER605 - LEDs not correctly configured on SNAPSHOT

### ISSUE THREAD

**Issue by GoetzGoerisch** [openwrt/openwrt#16596]
### Describe the bug

Installing ER605v2 with SNAPSHOT brings the device up with an invalid LED config.

Kernel_log
```
[    6.088339] leds-gpio leds: Led green:status renamed to green:status_1 due to name collision
[    6.097217] leds-gpio leds: Led green:status renamed to green:status_2 due to name collision
```

Therefore now the following LED configuration is active:
- Status LED is ON
- USB LED is ON

Default on 23.05 is:
- Status LED is ON
- System LED is ON

23.05.5 Nameing:

```
green:power
green:system
green:usb
```

Custom config 23.05.5
```
config led
	option sysfs 'green:system'
	option trigger 'heartbeat'
```

### OpenWrt version

r27648-71da76158e

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

ramips/mt7621

### Device

TP-Link ER605 v2

### Image kind

Official downloaded image

### Steps to reproduce

- upgrade 23.05.5 to SNAPSHOT

### Actual behaviour

- default LED behaviour changes:

   - Status LED is ON
   - USB LED is ON

### Expected behaviour

- default LED behaviour:

   - Status LED is ON
   - System LED is ON

### Additional info

Custom configurations of the LEDs are not working anymore.

From the kernel log:

```
[    6.088339] leds-gpio leds: Led green:status renamed to green:status_1 due to name collision
[    6.097217] leds-gpio leds: Led green:status renamed to green:status_2 due to name collision
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by GoetzGoerisch** [comment]
Ping @Djfe

**Comment by namiltd** [comment]
```
		led_power: power {
			color = <LED_COLOR_ID_GREEN>;
			function = LED_FUNCTION_STATUS;
			gpios = <&gpio 12 GPIO_ACTIVE_LOW>;
			default-state = "on";
		};

		led_system: system {
			color = <LED_COLOR_ID_GREEN>;
			function = LED_FUNCTION_STATUS;
			gpios = <&gpio 7 GPIO_ACTIVE_HIGH>;
			default-state = "keep";
		};
```
Both leds are defined as LED_FUNCTION_STATUS
They should be differentiated, e.g. added to one: function-enumerator = <0>;

**Comment by GoetzGoerisch** [comment]
@namiltd thanks for pointing out.
So it was wrong in 5.15 already but worked.

I'm still unfamiliar with dts files.


Would this work:

```
	leds {
		compatible = "gpio-leds";

		led_usb: usb {
			color = <LED_COLOR_ID_GREEN>;
			function = LED_FUNCTION_USB;
			gpios = <&gpio 11 GPIO_ACTIVE_HIGH>;
		};

		led_power: power {
			color = <LED_COLOR_ID_GREEN>;
			function = LED_FUNCTION_POWER;
			gpios = <&gpio 12 GPIO_ACTIVE_LOW>;
			default-state = "on";
		};

		led_system: system {
			color = <LED_COLOR_ID_GREEN>;
			function = LED_FUNCTION_CPU;
			gpios = <&gpio 7 GPIO_ACTIVE_HIGH>;
			default-state = "keep";
		};
	};
```
