### ISSUE TITLE
rockchip/armv8: missing kmods on latest snapshot

### ISSUE THREAD

**Issue by FrozenGamesYT** [openwrt/openwrt#16600]
### Describe the bug

there are missing kmod packages in the kmod repository

### OpenWrt version

r27659-664b8ffb0a

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

rockchip/armv8

### Device

FriendlyElec NanoPi R5C

### Image kind

Official downloaded image

### Steps to reproduce

Build/flash SNAPSHOT onto rockchip based router/ap and run opkg update and search mt7921u for example

### Actual behaviour

Missing few kmod packages regarding mediatek (could be more maybe not sure)

### Expected behaviour

show kmod drivers for devices

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by leobsky** [comment]
All the wireless kmod driver are not being build on the rockchip target because this error on the backports 6.11.2
```
openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/mac80211-regular/backports-6.11/drivers/net/wireless/ath/wil6210/wmi.c: In function 'wmi_set_cqm_rssi_config':
openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/mac80211-regular/backports-6.11/drivers/net/wireless/ath/wil6210/wmi.c:4033:23: error: implicit declaration of function '__struct_size'; did you mean 'struct_size'? [-Werror=implicit-function-declaration]
 4033 |                       __struct_size(cmd), WMI_SET_LINK_MONITOR_EVENTID,
      |                       ^~~~~~~~~~~~~
      |                       struct_size
```
