### ISSUE TITLE
openwrt使用c语言调用用cgo生成的so时，编译通过，但是运行失败

### ISSUE THREAD

**Issue by rrrrrrrrrrrrush** [openwrt/openwrt#16718]
### Describe the bug

<img width="762" alt="go线程启动报错" src="https://github.com/user-attachments/assets/fc0a0241-b89b-4262-bb57-4e97b9760b47">

### OpenWrt version

r15812+882-46b6ee7ffc

### OpenWrt release

r15812+882-46b6ee7ffc

### OpenWrt target/subtarget

r15812+882-46b6ee7ffc

### Device

GL.iNet GL-XE3000

### Image kind

Official downloaded image

### Steps to reproduce

cgo的so：
package main

import "c"

 func main() {}

//export test
func test() int{
        return 2
}

//CGO_ENABLED=1 GOOS=linux GOARCH=arm64  go build -o libtest.so -buildmode=c-shared main.go

c的调用也是include一下生成的.h文件链接编译一下
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>

#include "test.h"

int main()
{
    
    if(handlePacket()==2){
    printf("successsssssssss");

}

    while (1)
    {
        printf("30sec");
        sleep(30);
    }

    // return 0;
}

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
> unsupported fork.

You falsely marked the checkbox. Contacrt wherever you got your s(ftware from.
