### ISSUE TITLE
No VLAN for TP-Link TL-WR802N

### ISSUE THREAD

**Issue by adrai** [openwrt/openwrt#16792]
### Describe the bug

Is it just me, or can't we make a VLAN setup with the TP-Link TL-WR802N? I would like to have different SSIDs, mapped to different VLANs.

<img width="977" alt="image" src="https://github.com/user-attachments/assets/7f992e0b-44bd-4b7a-9d02-b61bd511302b">

Also only VLAN ids between 0-15 are accepted:
<img width="262" alt="image" src="https://github.com/user-attachments/assets/9dc65aee-5ff5-4680-98c2-cb39a71a5031">

### OpenWrt version

r24012-d8dd03c46f

### OpenWrt release

23.05.4

### OpenWrt target/subtarget

ramips/mt76x8

### Device

TP-Link TL-WR802N v4

### Image kind

Official downloaded image

### Steps to reproduce

Try to define a VLAN and map that to a SSID...?

### Actual behaviour

There seems to be no way right now to accomplish this.

There is no checkbox to enable VLAN functionality in the Switch menu.

### Expected behaviour

Would be nice if configuring VLANs and mapping them to different SSIDs would work.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Initial image is likely luci issue, the other is that it correctly exposes hw limitation.

**Comment by adrai** [comment]
Do you want me to open a new issue in the luci repository?
Or there anything else I need to provide?

**Comment by brada4** [comment]
Better open, core system functions withour web ui.

**Comment by adrai** [comment]
https://github.com/openwrt/luci/issues/7359
