### ISSUE TITLE
24.10-SNAPSHOT imagebuilder contains MAIN SNAPSHOT usign key instead of 24.10 release usign key

### ISSUE THREAD

**Issue by KA2107** [openwrt/openwrt#16850]
Buildbot generated imagebuilder (example: https://downloads.openwrt.org/releases/24.10-SNAPSHOT/targets/mediatek/filogic/openwrt-imagebuilder-24.10-SNAPSHOT-mediatek-filogic.Linux-x86_64.tar.zst) contains the usign key for main / master snapshot builds instead of the 24.10 release usign key https://git.openwrt.org/?p=keyring.git;a=commit;h=fbae29d730f81c892f52e0ff00fe867444aeeae6 .

**Comment by ynezz** [comment]
Thanks a lot for the report!
