### ISSUE TITLE
Meraki  MR18: opkg_install_cmd: Cannot install package nu801

### ISSUE THREAD

**Issue by jhatala-myth** [openwrt/openwrt#16857]
### Describe the bug

Cant't build image for Meraki MR18 due to a missing package nu801, which is responsible  for  LED indicator 

```bash
Collected errors:
 * opkg_install_cmd: Cannot install package nu801.
 * opkg_install_cmd: Cannot install package nu801.
make[2]: *** [Makefile:189: package_install] Error 255
make[1]: *** [Makefile:144: _call_image] Error 2
make: *** [Makefile:262: image] Error 2
```

Latest available package --> releases/19.07.3/targets/ar71xx/tiny/

```bash
Package: kmod-leds-nu801
Version: 4.14.180-1
Depends: kernel (=4.14.180-1-114d5676c49eba1190f3a23a556ce343)
License: GPL-2.0
Section: kernel
Architecture: mips_24kc
Installed-Size: 105
Filename: kmod-leds-nu801_4.14.180-1_mips_24kc.ipk
Size: 845
SHA256sum: 7a45c9e2882cd0147d22016a94d35aee754867f55863dc643168c59fa704a919
Description:  Kernel module for the nu801 LED driver used on the Meraki MR18
```

### OpenWrt version

r23630-842932a63d

### OpenWrt release

23.05.2, 23.05.5

### OpenWrt target/subtarget

ath79/nand

### Device

Meraki MR18

### Image kind

Self-built image

### Steps to reproduce

make image PROFILE="meraki_mr18"

### Actual behaviour

Collected errors:
 * opkg_install_cmd: Cannot install package nu801.
 * opkg_install_cmd: Cannot install package nu801.
make[2]: *** [Makefile:189: package_install] Error 255
make[1]: *** [Makefile:144: _call_image] Error 2
make: *** [Makefile:262: image] Error 2

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
AFAIK, it was replaced with the userspace GPIO driver:
https://github.com/openwrt/openwrt/blob/main/package/system/gpio-cdev/nu801/Makefile

But, I think that one is not being built since its not marked as non-shared but at the same time depends on certain targets, so phase2 is not building it.
