### ISSUE TITLE
apk: sysupgrade: saving of installed packages using -k argument doesn't work due to hardcoded opkg functionality

### ISSUE THREAD

**Issue by KA2107** [openwrt/openwrt#16947]
### Describe the bug

sysupgrade: Fails on firmware with APK when -k parameter is used

### OpenWrt version

r28072-b902284290

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

GL.iNet GL-MT6000

### Image kind

Official downloaded image

### Steps to reproduce

1. Build a new image using Imagebuilder
2. Use SCP or SFTP or FTP to copy the built image to /tmp inside the running OpenWrt system
3. Use "sysupgrade -k -v" option to trigger the sysupgrade

### Actual behaviour

**After "sysupgrade -u -k -v" or "sysupgrade -k -v", device got reset to default config.
After "sysupgrade -u -v", the existing config was retained, so the "-u" parameter is not causing this issue.**

```
# sysupgrade -u -k -v openwrt-mediatek-filogic-glinet_gl-mt6000-squashfs-sysupgrade.bin
verifying sysupgrade tar file integrity
Wed Nov 13 12:03:50 CST 2024 upgrade: Saving config files...
find: /usr/lib/opkg/info: No such file or directory
etc/config/attendedsysupgrade
etc/config/bcp38
etc/config/ddns
etc/config/dhcp
etc/config/dnsproxy
etc/config/dropbear
etc/config/firewall
etc/config/fstab
etc/config/https-dns-proxy
etc/config/irqbalance
etc/config/luci
etc/config/network
etc/config/nextdns
etc/config/qosify
etc/config/sqm
etc/config/stubby
etc/config/system
etc/config/ttyd
etc/config/ubootenv
etc/config/ucitrack
etc/config/uhttpd
etc/config/unbound
etc/config/vnstat
etc/config/wireless
etc/config/zerotier
etc/crontabs/root
etc/dropbear/authorized_keys
etc/dropbear/dropbear_ed25519_host_key
etc/dropbear/dropbear_rsa_host_key
etc/fw_env.config
etc/group
etc/passwd
etc/rc.local
etc/shadow
etc/shells
etc/sysctl.conf
etc/sysupgrade.conf
etc/tailscale/derpmap.cached.json
etc/tailscale/tailscaled.state
etc/uhttpd.crt
etc/uhttpd.key
etc/vsftpd.conf
Wed Nov 13 12:03:51 CST 2024 upgrade: Commencing upgrade. Closing all shell sessions.
Command failed: Connection failed
```

### Expected behaviour

**After sysupgrade, device is expected to reload the existing config instead of resetting to default config.**

### Additional info

https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164/70
https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164/73
https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164/74

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jhol** [comment]
The current design takes an approach of reading the package list from the internal opkg state file: `/usr/lib/opkg/info`, which obviously no longer exists.

There is a somewhat similar file in apk: `/lib/apk/db/installed`. This contains a variety of information about installed packages. If understand the list of installed packages can be filtered out like this:  `sed -n s/P://p /lib/apk/db/installed`  i.e. every line beginning with `P:` is the name of an installed package.

**Comment by jhol** [comment]
`apk info -vv` also lists the installed packages. One might argue that this is a safer/saner approach to collecting the package list.

**Comment by jhol** [comment]
> `/etc/apk/world` already contains the list of installed packages, right? We can either use that file or the output of `apk info -vv` command.

Looking it it, they're not quite the same. `apk info -vv` lists all installed packages whereas `/etc/apk/world` is a subset of those packages that were explicitly requested to be installed, not necessarily including dependencies.

The Alpine manual has [interesting information](https://docs.alpinelinux.org/user-handbook/0.1a/Working/apk.html#_world) about this:

> The packages you want to have explicitly installed are listed in the "world file", available in `/etc/apk/world`. It is safe to edit it by hand. If you’ve edited it by hand, you may run `apk add` with no arguments to bring the package selection to a consistent state.

Previously, sysupgrade had no facility to synchronise the installed packages with the backup after restoration. It could only list the packages (if I understand correctly).

So I think the `-k` option can be retired completely. `/etc/apk/world` should be included in the backup (and maybe other files in `/etc/apk`?), optional (?) functionality should be added to run `apk add` after restoration.

**Comment by jhol** [comment]
> So I think the `-k` option can be retired completely. `/etc/apk/world` should be included in the backup (and maybe other files in `/etc/apk`?), optional (?) functionality should be added to run `apk add` after restoration.

I tried adding this to my deployment script ([deploy-wrt](https://github.com/jhol/deploy-wrt/blob/master/deploy_wrt.py)), and it seems to work well!

**Comment by robimarko** [comment]
https://github.com/openwrt/openwrt/pull/17123 implements the existing format
