### ISSUE TITLE
apk: package is not being included by default in firmware images produced by ASU

### ISSUE THREAD

**Issue by 5gfreak** [openwrt/openwrt#16969]
### Describe the bug

On  Openwrt SNAPSHOT (r28085-6720c4ccba) opkg is missing
no packages can be installed, and opkg update ends with opkg not found

### OpenWrt version

 r28085-6720c4ccba

### OpenWrt release

Snapshot

### OpenWrt target/subtarget

 qualcommax/ipq807x

### Device

Zbtlink ZBT-Z800AX

### Image kind

Official downloaded image

### Steps to reproduce

opkg is missing from the system

### Actual behaviour

system reports opkg not found

### Expected behaviour

in order to install packages manually opkg is required

### Additional info

no additional info

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
Its not a bug, package manager [was switched](https://lists.openwrt.org/pipermail/openwrt-devel/2024-November/043378.html) from opkg to apk https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164

**Comment by 5gfreak** [comment]
root@OpenWrt:~# apk update
-ash: apk: not found

it works neither
is there any simple installation instructions?

**Comment by 5gfreak** [comment]
and it is a valid release from https://firmware-selector.openwrt.org/?version=SNAPSHOT&target=qualcommax%2Fipq807x&id=zbtlink_zbt-z800ax

**Comment by 5gfreak** [comment]
I don't find any apk file on this image, or any package with this name
the only folder is on root etc apk but how can this be started?

**Comment by namiltd** [comment]
Did you download the images or compile them yourself? If you compiled them yourself, include the configuratin,

**Comment by 5gfreak** [comment]
I have downloaded it from https://firmware-selector.openwrt.org/?version=SNAPSHOT&target=qualcommax%2Fipq807x&id=zbtlink_zbt-z800ax

**Comment by robimarko** [comment]
This looks like another ASU issue since using the same image builder version locally includes APK just fine in the sysupgrade image:
```
[robimarko@fedora squashfs-root]$ find . -name "apk"
./etc/apk
./lib/apk
./run/apk
./usr/bin/apk
```

**Comment by vincejv** [comment]
is this really an ASU/Firmware selector issue? Seems like `make defconfig` is not installing `apk-ssl` or `apk-mbedtls` by default hence the missing apk binaries and library..

make defconfig generates the following for me, idk why, maybe as a work around, you can add either apk-mbedtls or openssl packages in asu, but not sure/how if that would work.
```
#
# Base system
#
CONFIG_PACKAGE_apk-mbedtls=m
CONFIG_PACKAGE_apk-openssl=m
CONFIG_PACKAGE_base-files=y
CONFIG_PACKAGE_block-mount=m
CONFIG_PACKAGE_blockd=m
```

**Comment by robimarko** [comment]
No, the root cause is OpenWrt itself which recently stopped including some packages including procd and apk/opkg in the `DEFAULT_PACKAGES` variable thus the `default_packages` list in `profiles.json` lacks APK in ASU.

For more details:
https://github.com/openwrt/asu/issues/1084
