### ISSUE TITLE
23.05.05 for Rockchip/R2S does not boot

### ISSUE THREAD

**Issue by roastduckkiller** [openwrt/openwrt#17011]
### Describe the bug

Download following firmware:
https://downloads.openwrt.org/releases/23.05.5/targets/rockchip/armv8/openwrt-23.05.5-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz

Burn to SD card. Nanopi R2S is a brand new box with USB C port. 
The R2S box would not boot, the sys LED (red) in always on, and network LED is off all time.

However the FriendlyWrt image does work on the box, which means the hardware seems ok.
Since the system wouldn't boot, Openwrt version, release and target/subtarget information provided as I could find.

### OpenWrt version

openwrt-23.05.5-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade

### OpenWrt release

openwrt-23.05.5-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade

### OpenWrt target/subtarget

openwrt-23.05.5-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade

### Device

Rockchip/FriendlyArm Nanopi R2S

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Works better if you read the guide and gunzip  compressed file.

**Comment by roastduckkiller** [comment]
> Works better if you read the guide and gunzip compressed file.

Thanks for the reply. gunzip actually got error message.  
gunzip openwrt-23.05.5-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz
gunzip: openwrt-23.05.5-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz: trailing garbage ignored
gunzip: openwrt-23.05.5-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img does not boot.

So I just use balenaEtcher to burn SD card.

**Comment by brada4** [comment]
Try 23.05.0, 22.03.7 and SNAPSHOT via firmware-selector.openwrt.org , if any boots sysupgrade to 23.05.5.
For most people it boots just fine.

**Comment by roastduckkiller** [comment]
For now, i will use FriendlyWrt, but Official OpenWrt image is always my 1st choice. Will check back to later build works or not. Thanks all for your help.
