### ISSUE TITLE
MT7615d is made error for openwrt-23.05.5

### ISSUE THREAD

**Issue by azx123123** [openwrt/openwrt#17028]
### Describe the bug

![Image_1420538284125241](https://github.com/user-attachments/assets/6afcbe1a-f2dc-46b5-abfc-d91b5710e6ad)

### OpenWrt version

23.05.5

### OpenWrt release

release/23.05.5

### OpenWrt target/subtarget

ramips/mt7621

### Device

phicomm k2p

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Are you compiling OpenWRT? Looks like you stuffed mediatek proprietary driver on top of OpenWRT?

**Comment by castiel652** [comment]
> Are you compiling OpenWRT? Looks like you stuffed mediatek proprietary driver on top of OpenWRT?

Yes he did.
This can be closed now.

**Comment by azx123123** [comment]
yes.I use the mt7615d from the lede's repository.I copy the mt folder to the source.But it's ok to be compled with lede's source.

**Comment by LGA1150** [comment]
This package is not maintained by OpenWrt. Please complain to the package maintainer, not here.
