### ISSUE TITLE
apk: Re-installing a package with a config in /etc/config breaks uci

### ISSUE THREAD

**Issue by totkeks** [openwrt/openwrt#17033]
### Describe the bug

When re-installing a package that comes with a config file in `/etc/config`, in my case `stubby`, then a backup of the existing config file is created with the name `/etc/config/stubby.apk-new`.

After that happened, most of my `uci` commands failed with `invalid argument`, especially `uci commit` and `reload_config`. Thus, removing any ability to make changes to any services.

After removing the `stubby.apk-new` file, uci returned to normal behavior.

According to the IRC, this is normal behavior for `apk` to backup files and the error lies within `uci` as it doesn't know about this behavior and assumes the `opkg` way, which was just a `.opkg` extension.

### OpenWrt version

r28091-77cfe8fd15

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

Bananapi BPI-R4

### Image kind

Official downloaded image

### Steps to reproduce

- `apk add stubby`
- `apk del stubby`
- `apk add stubby`
- `uci commit`

### Actual behaviour

`uci commit` fails with `invalid argument`.

### Expected behaviour

`uci commit` succeeds without error.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by efahl** [comment]
Just repeating myself from IRC for background:

 - It looks like the `.apk-new` is well entrenched as an apk convention, so should not be changed.

 - The behavior is nothing new, just that `apk` uses a suffix with a dash in the name, so `uci`'s error is different than when using `opkg`.

 - This affects a lot of scripts in `/lib/` that do a bare `uci commit`, as that iterates all of the files in `/etc/config/` and fails.

Looks like possible solutions would be:
 - Hack `uci` or the `/lib/` scripts to ignore `/etc/config/*.apk-new` files
 - Modify packages' default `postinst` to rename any `pkg.apk-new` file as `pkg.apk` or `pkg.apk_new` or whatever
 - ???

**Comment by hnyman** [comment]
> assumes the opkg way, which was just a .opkg 

Was it?

Or was it actually-opkg ????

```

root@router4:~# ls -l /etc/config/ | grep opkg
-rw-r--r--    1 root     root           339 Mar  7  2024 irqbalance-opkg
-rw-r--r--    1 root     root          4922 May 25  2023 luci_statistics-opkg
-rw-r--r--    1 root     root          4998 Aug 18  2022 usteer-opkg
```

I think it is the dot, not hyphen, that is causing trouble.

**Comment by efahl** [comment]
> Or was it actually `-opkg` with dash / hyphen????

You are correct, I was fumble-fingering the names...  It was always `-opkg` for those.

I think it's the dash-after-dot that's causing `uci` to fail.

**Comment by vincejv** [comment]
I'm sure this will get fixed eventually (take your time), given there are plenty of solutions in place but hope this gets traction so issues like the one below

- https://github.com/openwrt/packages/issues/22850

won't fly under the radar across several stable releases, i seldom use package manager logs & pre/post install scripts as one of the first line of troubleshooting steps when there are configuration issues with syntax or whatever.

**Comment by hnyman** [comment]
The problematic `".apk-new"` ending is a separate literal defined in 4 actual places (in 3 files) in apk source code, plus a few comments.

https://gitlab.alpinelinux.org/search?search=.apk-new&nav_source=navbar&project_id=5&group_id=2&search_code=true&repository_ref=master

It would be relatively easy to define   `#define PKG_NEWCFGFILE_FMT  ".apk-new"`  in `apk_package.h` right next to the already existing `#define PKG_FILE_FMT   PKG_VER_FMT ".apk"`
and replace the 4 occurences of literal `".apk-new"` in code with the defined `PKG_NEWCFGFILE_FMT`.   That `apk_package.h` gets directly/indirectly included by all those 3 files that use the string. 

That no-op change might be suggested to upstream, and we might just carry a patch to change that one define of `".apk-new"` to `"-apk-new"`.  Or there might be an optional upstream configuration option for apk compile config, or something...
Any thoughts, @aparcar @Ansuel  ?

**Comment by efahl** [comment]
Very "low friction", I like it.  

Did you find any non-repo docs that reference the suffix?  Modern AI-based web search sucks so bad that it's almost impossible to find stuff any more, and I haven't seen anything related to it.

**Comment by hnyman** [comment]
I made Pr #17051 on this topic

**Comment by hnyman** [comment]
I tested with your "stubby" example, and sure, there seems to be trouble, if there is file with a dot in /etc/config.

My PR #17051 mentioned above should cure that.

Documentation for devs about the problem:

```
 OpenWrt SNAPSHOT, r28183-a4bd42b790
 -----------------------------------------------------
root@router1:~# apk update
...
OK: 8991 distinct packages available

root@router1:~# apk add stubby
(1/3) Installing getdns (1.7.3-r2)
Executing getdns-1.7.3-r2.post-install
(2/3) Installing libyaml (0.2.5-r1)
Executing libyaml-0.2.5-r1.post-install
(3/3) Installing stubby (0.4.3-r1)
Executing stubby-0.4.3-r1.post-install
OK: 34 MiB in 320 packages

root@router1:~# ls -l /etc/config/st*
-rw-------    1 root     root          2964 Nov 24 08:45 /etc/config/stubby

root@router1:~# apk del stubby
(1/3) Purging stubby (0.4.3-r1)
Executing stubby-0.4.3-r1.pre-deinstall
(2/3) Purging getdns (1.7.3-r2)
Executing getdns-1.7.3-r2.pre-deinstall
(3/3) Purging libyaml (0.2.5-r1)
Executing libyaml-0.2.5-r1.pre-deinstall
OK: 34 MiB in 317 packages
root@router1:~# ls -l /etc/config/st*
ls: /etc/config/st*: No such file or directory

root@router1:~# apk add stubby
(1/3) Installing getdns (1.7.3-r2)
Executing getdns-1.7.3-r2.post-install
(2/3) Installing libyaml (0.2.5-r1)
Executing libyaml-0.2.5-r1.post-install
(3/3) Installing stubby (0.4.3-r1)
Executing stubby-0.4.3-r1.post-install
OK: 34 MiB in 320 packages
root@router1:~# ls -l /etc/config/st*
-rw-------    1 root     root          2964 Nov 24 08:45 /etc/config/stubby
root@router1:~# uci commit
root@router1:~# apk del stubby
(1/3) Purging stubby (0.4.3-r1)
Executing stubby-0.4.3-r1.pre-deinstall
(2/3) Purging getdns (1.7.3-r2)
Executing getdns-1.7.3-r2.pre-deinstall
(3/3) Purging libyaml (0.2.5-r1)
Executing libyaml-0.2.5-r1.pre-deinstall
OK: 34 MiB in 317 packages
root@router1:~# ls -l /etc/config/st*
ls: /etc/config/st*: No such file or directory

root@router1:~# echo "#test" > /etc/config/stubby
root@router1:~# ls -l /etc/config/st*
-rw-r--r--    1 root     root             5 Nov 24 15:43 /etc/config/stubby

root@router1:~# apk add stubby
(1/3) Installing getdns (1.7.3-r2)
Executing getdns-1.7.3-r2.post-install
(2/3) Installing libyaml (0.2.5-r1)
Executing libyaml-0.2.5-r1.post-install
(3/3) Installing stubby (0.4.3-r1)
stubby-0.4.3-r1: installing file to etc/config/stubby.apk-new
Executing stubby-0.4.3-r1.post-install
OK: 34 MiB in 320 packages
root@router1:~# ls -l /etc/config/st*
-rw-r--r--    1 root     root             5 Nov 24 15:43 /etc/config/stubby
-rw-------    1 root     root          2964 Nov 24 08:45 /etc/config/stubby.apk-new
root@router1:~# apk del stubby
(1/3) Purging stubby (0.4.3-r1)
Executing stubby-0.4.3-r1.pre-deinstall
(2/3) Purging getdns (1.7.3-r2)
Executing getdns-1.7.3-r2.pre-deinstall
(3/3) Purging libyaml (0.2.5-r1)
Executing libyaml-0.2.5-r1.pre-deinstall
OK: 34 MiB in 317 packages
root@router1:~# ls -l /etc/config/st*
-rw-r--r--    1 root     root             5 Nov 24 15:43 /etc/config/stubby
root@router1:~# apk add stubby
(1/3) Installing getdns (1.7.3-r2)
Executing getdns-1.7.3-r2.post-install
(2/3) Installing libyaml (0.2.5-r1)
Executing libyaml-0.2.5-r1.post-install
(3/3) Installing stubby (0.4.3-r1)
stubby-0.4.3-r1: installing file to etc/config/stubby.apk-new
Executing stubby-0.4.3-r1.post-install
OK: 34 MiB in 320 packages
root@router1:~# ls -l /etc/config/st*
-rw-r--r--    1 root     root             5 Nov 24 15:43 /etc/config/stubby
-rw-------    1 root     root          2964 Nov 24 08:45 /etc/config/stubby.apk-new
root@router1:~# uci commit
uci: Invalid argument
root@router1:~# mv /etc/config/stubby.apk-new /etc/config/stubby-apk-new
root@router1:~# uci commit

root@router1:~# apk del stubby
(1/3) Purging stubby (0.4.3-r1)
Executing stubby-0.4.3-r1.pre-deinstall
(2/3) Purging getdns (1.7.3-r2)
Executing getdns-1.7.3-r2.pre-deinstall
(3/3) Purging libyaml (0.2.5-r1)
Executing libyaml-0.2.5-r1.pre-deinstall
OK: 34 MiB in 317 packages
root@router1:~# uci commit
root@router1:~# apk add stubby
(1/3) Installing getdns (1.7.3-r2)
Executing getdns-1.7.3-r2.post-install
(2/3) Installing libyaml (0.2.5-r1)
Executing libyaml-0.2.5-r1.post-install
(3/3) Installing stubby (0.4.3-r1)
stubby-0.4.3-r1: installing file to etc/config/stubby.apk-new
Executing stubby-0.4.3-r1.post-install
OK: 34 MiB in 320 packages
root@router1:~# ls -l /etc/config/st*
-rw-r--r--    1 root     root             5 Nov 24 15:43 /etc/config/stubby
-rw-------    1 root     root          2964 Nov 24 08:45 /etc/config/stubby-apk-new
-rw-------    1 root     root          2964 Nov 24 08:45 /etc/config/stubby.apk-new
root@router1:~# uci commit
uci: Invalid argument

root@router1:~# mv /etc/config/stubby.apk-new /etc/config/stubby_apk-new
root@router1:~# ls -l /etc/config/st*
-rw-r--r--    1 root     root             5 Nov 24 15:43 /etc/config/stubby
-rw-------    1 root     root          2964 Nov 24 08:45 /etc/config/stubby-apk-new
-rw-------    1 root     root          2964 Nov 24 08:45 /etc/config/stubby_apk-new
root@router1:~# uci commit
```

I did not see any change in /tmp/.uci, so I am a bit unsure from where the actual problem arises.  My guess is that uci onsiders that xxx.XXXX file to be a temp file to be somehow handled in commit. (Didn't go through uci code, though.)

**Comment by robimarko** [comment]
Fixed by https://github.com/openwrt/openwrt/commit/3929ef4c21844189d5db8d14e7e6dc6ba983d571
