### ISSUE TITLE
Baby jumbo frames mtu 1508 not working on GL-INET MT-6000

### ISSUE THREAD

**Issue by lwbnet** [openwrt/openwrt#17069]
### Describe the bug

Trying to enable mtu 1508 on the physical WAN interface does not work.

I can successfully enable 1500 on the pppoe-wan virtual interface, but the physical wan port isn't working with mtu 1508 (baby jumbo frames).

### OpenWrt version

r15812+1077-46b6ee7ffc

### OpenWrt release

21.02-SNAPSHOT

### OpenWrt target/subtarget

mediatek/mt7986

### Device

GL.iNet GL-MT6000

### Image kind

Official downloaded image

### Steps to reproduce

root@GL-MT6000:~# ifconfig eth1 mtu 1508
ifconfig: SIOCSIFMTU: Invalid argument

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
gl.inet firmware issues must be reported to gl.inet. Or in other words can not be fixed from here.

You should install OpenWRT from firmware-selector.openwrt.org, mediatek/mt7986 switch can do 9000 but the soc side port something like 2.1k frames ermm and SoC is supported since OpenWRT 23.
