### ISSUE TITLE
mvebu does not boot

### ISSUE THREAD

**Issue by borkra** [openwrt/openwrt#17075]
### Describe the bug

Router does not boot

### OpenWrt version

master

### OpenWrt release

master

### OpenWrt target/subtarget

mvebu

### Device

WRT1900ACv2

### Image kind

Self-built image

### Steps to reproduce

Turn the power on

### Actual behaviour

Router does not start

### Expected behaviour

Router starting

### Additional info

/bin/sh: can't open '/etc/preinit': No such file or directory
open: No such file or directory
open: No such file or directory

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
Please post the whole bootlog, otherwise its impossible to even guess.

How did you acquire the image that was flashed?

**Comment by borkra** [comment]
I built the image myself. 

/etc/preinit is not installed on the image, even though /sbin/init requires it.

You do not need bootlog for this, just look in the ./build_dir/target-arm_cortex-a9+neon_musl_eabi/root-mvebu after build it's not there

**Comment by borkra** [comment]
Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 6.6.63 (boris@boris-pc) (arm-openwrt-linux-muslgnueabi-gcc (OpenWrt GCC 14.2.0 r28116-cd92cbddf8) 14.2.0, GNU ld (GNU Binutils) 2.42) #0 SMP Mon Nov 25 11:20:59 2024
[    0.000000] CPU: ARMv7 Processor [414fc091] revision 1 (ARMv7), cr=50c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Linksys WRT1900AC v2
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000]   HighMem  empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000] percpu: Embedded 12 pages/cpu s18452 r8192 d22508 u49152
[    0.000000] Kernel command line: console=ttyS0,115200 root=/dev/mtdblock7 ro rootdelay=1 rootfstype=jffs2 earlyprintk mtdparts=armada-nand:2048K(uboot)ro,256K(u_env),256K(s_env),1m@9m(devinfo),40m@10m(kernel),34m@16m(rootfs),40m@50m(alt_kernel),34m@56m(alt_rootfs),80m@10m(ubifs),-@90m(syscfg)
[    0.000000] Bootloader command line (ignored): console=ttyS0,115200 root=/dev/mtdblock7 ro rootdelay=1 rootfstype=jffs2 earlyprintk mtdparts=armada-nand:2048K(uboot)ro,256K(u_env),256K(s_env),1m@9m(devinfo),40m@10m(kernel),34m@16m(rootfs),40m@50m(alt_kernel),34m@56m(alt_rootfs),80m@10m(ubifs),-@90m(syscfg)
[    0.000000] Unknown kernel command line parameters "earlyprintk mangled_fs=jffs2 mtdparts=armada-nand:2048K(uboot)ro,256K(u_env),256K(s_env),1m@9m(devinfo),40m@10m(kernel),34m@16m(rootfs),40m@50m(alt_kernel),34m@56m(alt_rootfs),80m@10m(ubifs),-@90m(syscfg)", will be passed to user space.
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 130048
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 508460K/524288K available (6144K kernel code, 632K rwdata, 2168K rodata, 1024K init, 231K bss, 15828K reserved, 0K cma-reserved, 0K highmem)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=2.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] L2C: DT/platform modifies aux control register: 0x06070000 -> 0x16070000
[    0.000000] L2C-310 enabling early BRESP for Cortex-A9
[    0.000000] L2C-310 full line of zeros enabled for Cortex-A9
[    0.000000] L2C-310 D prefetch enabled, offset 1 lines
[    0.000000] L2C-310 dynamic clock gating enabled, standby mode enabled
[    0.000000] L2C-310 Coherent cache controller enabled, 16 ways, 1024 kB
[    0.000000] L2C-310 Coherent: CACHE_ID 0x410054c9, AUX_CTRL 0x56070001
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] sched_clock: 64 bits at 800MHz, resolution 1ns, wraps every 4398046511103ns
[    0.000011] clocksource: arm_global_timer: mask: 0xffffffffffffffff max_cycles: 0xb881274fa3, max_idle_ns: 440795210636 ns
[    0.000025] Switching to timer-based delay loop, resolution 1ns
[    0.000153] Ignoring duplicate/late registration of read_current_timer delay
[    0.000156] clocksource: armada_370_xp_clocksource: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 76450417870 ns
[    0.000297] Calibrating delay loop (skipped), value calculated using timer frequency.. 1600.00 BogoMIPS (lpj=8000000)
[    0.000304] CPU: Testing write buffer coherency: ok
[    0.000317] CPU0: Spectre v2: using BPIALL workaround
[    0.000321] pid_max: default: 32768 minimum: 301
[    0.002836] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.002841] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.005454] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.005728] RCU Tasks Trace: Setting shift to 1 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=2.
[    0.005769] Setting up static identity map for 0x100000 - 0x100054
[    0.005844] mvebu-soc-id: MVEBU SoC ID=0x6820, Rev=0x4
[    0.005924] mvebu-pmsu: Initializing Power Management Service Unit
[    0.006001] rcu: Hierarchical SRCU implementation.
[    0.006003] rcu: 	Max phase no-delay instances is 1000.
[    0.006140] smp: Bringing up secondary CPUs ...
[    0.006297] Booting CPU 1
[    0.006417] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.006423] CPU1: Spectre v2: using BPIALL workaround
[    0.006470] smp: Brought up 1 node, 2 CPUs
[    0.006474] SMP: Total of 2 processors activated (3200.00 BogoMIPS).
[    0.006478] CPU: All CPU(s) started in SVC mode.
[    0.009154] VFP support v0.3: implementor 41 architecture 3 part 30 variant 9 rev 4
[    0.009207] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.009215] futex hash table entries: 512 (order: 3, 32768 bytes, linear)
[    0.009264] pinctrl core: initialized pinctrl subsystem
[    0.010120] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.010641] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.011122] thermal_sys: Registered thermal governor 'step_wise'
[    0.011271] cpuidle: using governor ladder
[    0.011431] mvebu-pmsu: CPU hotplug support is currently broken on Armada 38x: disabling
[    0.011436] mvebu-pmsu: CPU idle is currently broken on Armada 38x: disabling
[    0.016247] cryptd: max_cpu_qlen set to 1000
[    0.018777] SCSI subsystem initialized
[    0.018952] usbcore: registered new interface driver usbfs
[    0.018967] usbcore: registered new interface driver hub
[    0.018984] usbcore: registered new device driver usb
[    0.019761] clocksource: Switched to clocksource arm_global_timer
[    0.023468] NET: Registered PF_INET protocol family
[    0.023569] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.024061] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.024072] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.024078] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.024099] TCP bind hash table entries: 4096 (order: 4, 65536 bytes, linear)
[    0.024161] TCP: Hash tables configured (established 4096 bind 4096)
[    0.024386] MPTCP token hash table entries: 512 (order: 1, 8192 bytes, linear)
[    0.024519] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.024534] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.024773] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.024792] PCI: CLS 0 bytes, default 64
[    0.025781] workingset: timestamp_bits=30 max_order=17 bucket_order=0
[    0.030095] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.030099] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.033925] armada-38x-pinctrl f1018000.pinctrl: registered pinctrl driver
[    0.034534] gpio gpiochip0: Static allocation of GPIO base is deprecated, use dynamic allocation.
[    0.034616] debugfs: Directory 'f1018100.gpio' with parent 'regmap' already present!
[    0.034848] gpio gpiochip1: Static allocation of GPIO base is deprecated, use dynamic allocation.
[    0.034937] debugfs: Directory 'f1018140.gpio' with parent 'regmap' already present!
[    0.035188] mvebu-pcie soc:pcie: host bridge /soc/pcie ranges:
[    0.035209] mvebu-pcie soc:pcie:      MEM 0x00f1080000..0x00f1081fff -> 0x0000080000
[    0.035224] mvebu-pcie soc:pcie:      MEM 0x00f1040000..0x00f1041fff -> 0x0000040000
[    0.035236] mvebu-pcie soc:pcie:      MEM 0x00f1044000..0x00f1045fff -> 0x0000044000
[    0.035248] mvebu-pcie soc:pcie:      MEM 0x00f1048000..0x00f1049fff -> 0x0000048000
[    0.035259] mvebu-pcie soc:pcie:      MEM 0xffffffffffffffff..0x00fffffffe -> 0x0100000000
[    0.035271] mvebu-pcie soc:pcie:       IO 0xffffffffffffffff..0x00fffffffe -> 0x0100000000
[    0.035283] mvebu-pcie soc:pcie:      MEM 0xffffffffffffffff..0x00fffffffe -> 0x0200000000
[    0.035294] mvebu-pcie soc:pcie:       IO 0xffffffffffffffff..0x00fffffffe -> 0x0200000000
[    0.035305] mvebu-pcie soc:pcie:      MEM 0xffffffffffffffff..0x00fffffffe -> 0x0300000000
[    0.035317] mvebu-pcie soc:pcie:       IO 0xffffffffffffffff..0x00fffffffe -> 0x0300000000
[    0.035328] mvebu-pcie soc:pcie:      MEM 0xffffffffffffffff..0x00fffffffe -> 0x0400000000
[    0.035336] mvebu-pcie soc:pcie:       IO 0xffffffffffffffff..0x00fffffffe -> 0x0400000000
[    0.035600] mvebu-pcie soc:pcie: PCI host bridge to bus 0000:00
[    0.035606] pci_bus 0000:00: root bus resource [bus 00-ff]
[    0.035613] pci_bus 0000:00: root bus resource [mem 0xf1080000-0xf1081fff] (bus address [0x00080000-0x00081fff])
[    0.035619] pci_bus 0000:00: root bus resource [mem 0xf1040000-0xf1041fff] (bus address [0x00040000-0x00041fff])
[    0.035625] pci_bus 0000:00: root bus resource [mem 0xf1044000-0xf1045fff] (bus address [0x00044000-0x00045fff])
[    0.035631] pci_bus 0000:00: root bus resource [mem 0xf1048000-0xf1049fff] (bus address [0x00048000-0x00049fff])
[    0.035635] pci_bus 0000:00: root bus resource [mem 0xe0000000-0xe7ffffff]
[    0.035640] pci_bus 0000:00: root bus resource [io  0x1000-0xeffff]
[    0.035696] pci 0000:00:01.0: [11ab:6820] type 01 class 0x060400
[    0.035861] pci 0000:00:02.0: [11ab:6820] type 01 class 0x060400
[    0.036809] PCI: bus0: Fast back to back transfers disabled
[    0.036814] pci 0000:00:01.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    0.036821] pci 0000:00:02.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    0.036880] pci 0000:01:00.0: [11ab:2a55] type 00 class 0x020000
[    0.036897] pci 0000:01:00.0: reg 0x10: [mem 0x40000000-0x400fffff 64bit pref]
[    0.036909] pci 0000:01:00.0: reg 0x18: [mem 0x40100000-0x401fffff 64bit pref]
[    0.036973] pci 0000:01:00.0: supports D1 D2
[    0.036977] pci 0000:01:00.0: PME# supported from D0 D1 D3hot D3cold
[    0.037083] PCI: bus1: Fast back to back transfers disabled
[    0.037088] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    0.037152] pci 0000:02:00.0: [11ab:2a55] type 00 class 0x020000
[    0.037172] pci 0000:02:00.0: reg 0x10: [mem 0x42000000-0x420fffff 64bit pref]
[    0.037186] pci 0000:02:00.0: reg 0x18: [mem 0x42100000-0x421fffff 64bit pref]
[    0.037272] pci 0000:02:00.0: supports D1 D2
[    0.037275] pci 0000:02:00.0: PME# supported from D0 D1 D3hot D3cold
[    0.037299] pci 0000:02:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s PCIe x1 link at 0000:00:02.0 (capable of 4.000 Gb/s with 5.0 GT/s PCIe x1 link)
[    0.037405] PCI: bus2: Fast back to back transfers disabled
[    0.037409] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02
[    0.037425] pci 0000:00:01.0: BAR 8: assigned [mem 0xe0000000-0xe01fffff]
[    0.037431] pci 0000:00:02.0: BAR 8: assigned [mem 0xe0200000-0xe03fffff]
[    0.037438] pci 0000:01:00.0: BAR 0: assigned [mem 0xe0000000-0xe00fffff 64bit pref]
[    0.037448] pci 0000:01:00.0: BAR 2: assigned [mem 0xe0100000-0xe01fffff 64bit pref]
[    0.037458] pci 0000:00:01.0: PCI bridge to [bus 01]
[    0.037463] pci 0000:00:01.0:   bridge window [mem 0xe0000000-0xe01fffff]
[    0.037474] pci 0000:02:00.0: BAR 0: assigned [mem 0xe0200000-0xe02fffff 64bit pref]
[    0.037485] pci 0000:02:00.0: BAR 2: assigned [mem 0xe0300000-0xe03fffff 64bit pref]
[    0.037495] pci 0000:00:02.0: PCI bridge to [bus 02]
[    0.037500] pci 0000:00:02.0:   bridge window [mem 0xe0200000-0xe03fffff]
[    0.037794] mv_xor f1060800.xor: Marvell shared XOR driver
[    0.100260] mv_xor f1060800.xor: Marvell XOR (Descriptor Mode): ( xor cpy intr )
[    0.100417] mv_xor f1060900.xor: Marvell shared XOR driver
[    0.160238] mv_xor f1060900.xor: Marvell XOR (Descriptor Mode): ( xor cpy intr )
[    0.160418] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    0.160808] printk: console [ttyS0] disabled
[    0.181021] f1012000.serial: ttyS0 at MMIO 0xf1012000 (irq = 40, base_baud = 12500000) is a 16550A
[    0.181042] printk: console [ttyS0] enabled
[    1.305243] loop: module loaded
[    1.309488] ahci-mvebu f10a8000.sata: supply ahci not found, using dummy regulator
[    1.317184] ahci-mvebu f10a8000.sata: supply phy not found, using dummy regulator
[    1.324750] ahci-mvebu f10a8000.sata: supply target not found, using dummy regulator
[    1.332631] ahci-mvebu f10a8000.sata: AHCI 0001.0000 32 slots 2 ports 6 Gbps 0x3 impl platform mode
[    1.341730] ahci-mvebu f10a8000.sata: flags: 64bit ncq sntf led only pmp fbs pio slum part sxs 
[    1.351027] scsi host0: ahci-mvebu
[    1.354957] scsi host1: ahci-mvebu
[    1.358492] ata1: SATA max UDMA/133 mmio [mem 0xf10a8000-0xf10a9fff] port 0x100 irq 41
[    1.366471] ata2: SATA max UDMA/133 mmio [mem 0xf10a8000-0xf10a9fff] port 0x180 irq 41
[    1.375031] nand: device found, Manufacturer ID: 0x01, Chip ID: 0xf1
[    1.381428] nand: AMD/Spansion S34ML01G2
[    1.385367] nand: 128 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    1.393162] Bad block table found at page 65472, version 0x01
[    1.399262] Bad block table found at page 65408, version 0x01
[    1.405334] 10 fixed-partitions partitions found on MTD device pxa3xx_nand-0
[    1.412431] Creating 10 MTD partitions on "pxa3xx_nand-0":
[    1.417940] 0x000000000000-0x000000200000 : "u-boot"
[    1.423208] 0x000000200000-0x000000240000 : "u_env"
[    1.428249] 0x000000240000-0x000000280000 : "s_env"
[    1.433307] 0x000000900000-0x000000a00000 : "devinfo"
[    1.438700] 0x000000a00000-0x000003200000 : "kernel1"
[    1.444085] 0x000001000000-0x000003200000 : "rootfs1"
[    1.449450] 0x000003200000-0x000005a00000 : "kernel2"
[    1.454831] 0x000003800000-0x000005a00000 : "ubi"
[    1.459857] 0x000005a00000-0x000008000000 : "syscfg"
[    1.465080] 0x000000280000-0x000000900000 : "unused_area"
[    1.473318] mv88e6085 f1072004.mdio-mii:00: switch 0x1760 detected: Marvell 88E6176, revision 1
[    1.489069] mvneta_bm f10c8000.bm: Buffer Manager for network controller enabled
[    1.498115] mvneta f1070000.ethernet eth0: Using hardware mac address 14:91:82:2e:43:99
[    1.506460] orion-ehci f1058000.usb: EHCI Host Controller
[    1.511902] orion-ehci f1058000.usb: new USB bus registered, assigned bus number 1
[    1.519552] orion-ehci f1058000.usb: irq 44, io mem 0xf1058000
[    1.549768] orion-ehci f1058000.usb: USB 2.0 started, EHCI 1.00
[    1.555971] hub 1-0:1.0: USB hub found
[    1.559788] hub 1-0:1.0: 1 port detected
[    1.564224] usbcore: registered new interface driver usb-storage
[    1.570455] i2c_dev: i2c /dev entries driver
[    1.578245] orion_wdt: Initial timeout 171 sec
[    1.582951] sdhci: Secure Digital Host Controller Interface driver
[    1.589157] sdhci: Copyright(c) Pierre Ossman
[    1.593665] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.599506] leds-gpio: probe of gpio-leds failed with error -2
[    1.608866] marvell-cesa f1090000.crypto: CESA device successfully registered
[    1.616913] NET: Registered PF_INET6 protocol family
[    1.622585] Segment Routing with IPv6
[    1.626286] In-situ OAM (IOAM) with IPv6
[    1.630284] NET: Registered PF_PACKET protocol family
[    1.635423] 8021q: 802.1Q VLAN Support v1.8
[    1.639694] Registering SWP/SWPB emulation handler
[    1.655828] mv88e6085 f1072004.mdio-mii:00: switch 0x1760 detected: Marvell 88E6176, revision 1
[    1.675546] hwmon hwmon2: temp1_input not attached to any thermal zone
[    1.703316] ata1: SATA link down (SStatus 0 SControl 300)
[    1.708524] hwmon hwmon3: temp1_input not attached to any thermal zone
[    1.718878] ata2: SATA link down (SStatus 0 SControl 300)
[    1.739219] hwmon hwmon4: temp1_input not attached to any thermal zone
[    1.771792] hwmon hwmon5: temp1_input not attached to any thermal zone
[    1.803874] hwmon hwmon6: temp1_input not attached to any thermal zone
[    2.506468] mv88e6085 f1072004.mdio-mii:00: configuring for fixed/sgmii link mode
[    2.518997] mv88e6085 f1072004.mdio-mii:00: Link is Up - 1Gbps/Full - flow control off
[    2.606717] mv88e6085 f1072004.mdio-mii:00 lan4 (uninitialized): PHY [mv88e6xxx-0:00] driver [Marvell 88E1540] (irq=60)
[    2.716709] mv88e6085 f1072004.mdio-mii:00 lan3 (uninitialized): PHY [mv88e6xxx-0:01] driver [Marvell 88E1540] (irq=61)
[    2.826709] mv88e6085 f1072004.mdio-mii:00 lan2 (uninitialized): PHY [mv88e6xxx-0:02] driver [Marvell 88E1540] (irq=62)
[    2.936709] mv88e6085 f1072004.mdio-mii:00 lan1 (uninitialized): PHY [mv88e6xxx-0:03] driver [Marvell 88E1540] (irq=63)
[    3.044620] mv88e6085 f1072004.mdio-mii:00 wan (uninitialized): PHY [mv88e6xxx-0:04] driver [Marvell 88E1540] (irq=64)
[    3.058899] mvneta f1070000.ethernet eth0: entered promiscuous mode
[    3.065222] DSA: tree 0 setup
[    3.068514] usb_phy_generic usb3_1-phy: dummy supplies not allowed for exclusive requests
[    3.076895] xhci-hcd f10f8000.usb3: xHCI Host Controller
[    3.082248] xhci-hcd f10f8000.usb3: new USB bus registered, assigned bus number 2
[    3.089835] xhci-hcd f10f8000.usb3: hcc params 0x0a000990 hci version 0x100 quirks 0x0000000000000010
[    3.099123] xhci-hcd f10f8000.usb3: irq 45, io mem 0xf10f8000
[    3.104977] xhci-hcd f10f8000.usb3: xHCI Host Controller
[    3.110328] xhci-hcd f10f8000.usb3: new USB bus registered, assigned bus number 3
[    3.117864] xhci-hcd f10f8000.usb3: Host supports USB 3.0 SuperSpeed
[    3.124515] hub 2-0:1.0: USB hub found
[    3.128319] hub 2-0:1.0: 1 port detected
[    3.132462] usb usb3: We don't know the algorithms for LPM for this host, disabling LPM.
[    3.140809] hub 3-0:1.0: USB hub found
[    3.144612] hub 3-0:1.0: 1 port detected
[    3.149037] UBI: auto-attach mtd7
[    3.152386] ubi0: attaching mtd7
[    3.247263] ubi0: scanning is finished
[    3.255326] ubi0: attached mtd7 (name "ubi", size 34 MiB)
[    3.260766] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    3.267671] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    3.274508] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    3.281503] ubi0: good PEBs: 272, bad PEBs: 0, corrupted PEBs: 0
[    3.287534] ubi0: user volume: 2, internal volumes: 1, max. volumes count: 128
[    3.294789] ubi0: max/mean erase counter: 37/24, WL threshold: 4096, image sequence number: 453483670
[    3.304052] ubi0: available PEBs: 0, total reserved PEBs: 272, PEBs reserved for bad PEB handling: 20
[    3.313318] ubi0: background thread "ubi_bgt0d" started, PID 618
[    3.313760] block ubiblock0_0: created from ubi0:0(rootfs)
[    3.324871] ubiblock: device ubiblock0_0 (rootfs) set to be root filesystem
[    3.331982] clk: Disabling unused clocks
[    3.336029] Waiting 1 sec before mounting root device...
[    4.411873] VFS: Mounted root (squashfs filesystem) readonly on device 254:0.
[    4.419626] Freeing unused kernel image (initmem) memory: 1024K
[    4.425708] Run /sbin/init as init process
/bin/sh: can't open '/etc/preinit': No such file or directory
open: No such file or directory
open: No such file or directory

**Comment by robimarko** [comment]
Please post your diffconfig as well

**Comment by borkra** [comment]
The problem is `base-files` package now depend on `KERNEL_NAMESPACES` config but nobody force selects it. Probably need to use `select` not `depend`

**Comment by robimarko** [comment]
It is selected by default if small-flash is not set, then `KERNEL_NAMESPACES` is not selected but base-files also wont pull-in ujail

**Comment by borkra** [comment]
Unfortunatly, that is not, that is how base-files look in menuconfig. 
If SMALL_FLASH or KERNEL_NAMESPACES not selected base_files is off and no  mention of ujail

![image](https://github.com/user-attachments/assets/f758e106-34ce-4429-afc9-a426cca08590)

**Comment by borkra** [comment]
DEFAULT_base-files does not build base-fies

**Comment by borkra** [comment]
Here is final definition of base-file config, as you can see SMALL_FLASH or KERNEL_NAMESPACES required

```
	config PACKAGE_base-files
		tristate "base-files................................... Base filesystem for OpenWrt"
		default y if DEFAULT_base-files
		default m if ALL||ALL_NONSHARED
		depends on !(!SMALL_FLASH) || KERNEL_NAMESPACES
		select PACKAGE_busybox if !SELINUX && PACKAGE_busybox-selinux<PACKAGE_base-files
		select PACKAGE_busybox-selinux if SELINUX
		select PACKAGE_fstools
		select PACKAGE_fwtool
		select PACKAGE_jsonfilter
		select PACKAGE_libc
		select PACKAGE_netifd
		select PACKAGE_openwrt-keyring if SIGNED_PACKAGES
		select PACKAGE_procd if !SELINUX && PACKAGE_procd-selinux<PACKAGE_base-files
		select PACKAGE_procd-seccomp if USE_SECCOMP
		select PACKAGE_procd-selinux if SELINUX
		select PACKAGE_procd-ujail if !SMALL_FLASH
		select PACKAGE_ubi-utils if NAND_SUPPORT
		select PACKAGE_usign if SIGNED_PACKAGES
		help
		 This package contains a base filesystem and system scripts for OpenWrt.
```

**Comment by robimarko** [comment]
Please post your diffconfig

**Comment by borkra** [comment]
Commit that broke it is: ac640718aa0ceae55969bb9e7e45d00bb7bc228a by @ynezz
