### ISSUE TITLE
24.10.0-rc1 unable to find kernel modules from downloads.openwrt.org

### ISSUE THREAD

**Issue by kuanyili** [openwrt/openwrt#17146]
### Describe the bug

This bug potentially affects **ALL** future point/tagged releases.

Kernel modules are now put only in `kmods` and not in `packages` under `targets`, which is nice.

We can compare output from different branches and point releases:

- https://downloads.openwrt.org/snapshots/targets/x86/64/packages/
- https://downloads.openwrt.org/releases/24.10-SNAPSHOT/targets/x86/64/packages/
- https://downloads.openwrt.org/releases/24.10.0-rc1/targets/x86/64/packages/
- https://downloads.openwrt.org/releases/23.05-SNAPSHOT/targets/x86/64/packages/
- https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/packages/

However, `FeedSourcesAppendOPKG`, `FeedSourcesAppendAPK`, and `FeedSourcesAppend` only append `kmods` feed to

1. `/etc/opkg/distfeeds.conf` (OPKG)
2. `/etc/apk/repositories.d/distfeeds.list` (APK)
3. ImageBuilder `repositories.conf` (OPKG)
4. ImageBuilder `repositories` (APK)

for snapshot builds:

- https://github.com/openwrt/openwrt/blob/main/include/feeds.mk#L35
- https://github.com/openwrt/openwrt/blob/main/include/feeds.mk#L49
- https://github.com/openwrt/openwrt/blob/openwrt-24.10/include/feeds.mk#L35
- https://github.com/openwrt/openwrt/blob/openwrt-24.10/include/feeds.mk#L49
- https://github.com/openwrt/openwrt/blob/openwrt-23.05/include/feeds.mk#L31

Thus new point releases like 24.10.0-rc1 won't be able to find kernel modules from downloads.openwrt.org.

### OpenWrt version

r28158-d276b4c91a

### OpenWrt release

24.10.0-rc1

### OpenWrt target/subtarget

x86/64

### Device

QEMU Standard PC (Q35 + ICH9, 2009)

### Image kind

Official downloaded image

### Steps to reproduce

- download 24.10.0-rc1 ImageBuilder: https://downloads.openwrt.org/releases/24.10.0-rc1/targets/x86/64/openwrt-imagebuilder-24.10.0-rc1-x86-64.Linux-x86_64.tar.zst
- build image: `make image PROFILE=generic`

### Actual behaviour

```log
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-nf-conntrack-netlink for libnetfilter-conntrack3
 * pkg_hash_fetch_best_installation_candidate: Packages for libnetfilter-conntrack3 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-core for nftables-json
 * pkg_hash_fetch_best_installation_candidate: Packages for nftables-json found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-core for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-fib for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-offload for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-nat for firewall4
 * pkg_hash_fetch_best_installation_candidate: Packages for firewall4 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package firewall4.
 * opkg_install_cmd: Cannot install package kmod-amazon-ena.
 * opkg_install_cmd: Cannot install package kmod-amd-xgbe.
 * opkg_install_cmd: Cannot install package kmod-bnx2.
 * opkg_install_cmd: Cannot install package kmod-button-hotplug.
 * opkg_install_cmd: Cannot install package kmod-dwmac-intel.
 * opkg_install_cmd: Cannot install package kmod-e1000.
 * opkg_install_cmd: Cannot install package kmod-e1000e.
 * opkg_install_cmd: Cannot install package kmod-forcedeth.
 * opkg_install_cmd: Cannot install package kmod-fs-vfat.
 * opkg_install_cmd: Cannot install package kmod-igb.
 * opkg_install_cmd: Cannot install package kmod-igc.
 * opkg_install_cmd: Cannot install package kmod-ixgbe.
 * opkg_install_cmd: Cannot install package kmod-nft-offload.
 * opkg_install_cmd: Cannot install package kmod-r8169.
 * opkg_install_cmd: Cannot install package kmod-tg3.
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-core for nftables-nojson
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for nftables-json:
 *      kmod-nft-core
 * opkg_install_cmd: Cannot install package nftables.
 * pkg_hash_check_unresolved: cannot find dependency kmod-ppp for ppp
 * pkg_hash_fetch_best_installation_candidate: Packages for ppp found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package ppp.
 * pkg_hash_check_unresolved: cannot find dependency kmod-pppoe for ppp-mod-pppoe
 * pkg_hash_fetch_best_installation_candidate: Packages for ppp-mod-pppoe found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package ppp-mod-pppoe.
make[2]: *** [Makefile:228: package_install] Error 255
make[1]: *** [Makefile:155: _call_image] Error 2
make: *** [Makefile:331: image] Error 2
```

### Expected behaviour

Successful build

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by efahl** [comment]
It appears that the kmods feed is not being put into the distfeeds.conf for the 24.10.0 builds, not just imagebuilder.  This is from a fresh install minutes ago.

Is there a bug in the filter at https://github.com/openwrt/openwrt/blob/openwrt-24.10/include/feeds.mk#L40

```
$ wget https://downloads.openwrt.org/releases/24.10.0-rc1/targets/x86/64/openwrt-24.10.0-rc1-x86-64-generic-squashfs-combined-efi.img.gz
$ sysupgrade ...
<reboots>

$ cat /etc/opkg/distfeeds.conf
src/gz openwrt_core https://downloads.openwrt.org/releases/24.10.0-rc1/targets/x86/64/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10.0-rc1/packages/x86_64/base
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.0-rc1/packages/x86_64/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.0-rc1/packages/x86_64/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10.0-rc1/packages/x86_64/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10.0-rc1/packages/x86_64/telephony
```

**Comment by efahl** [comment]
I _think_ this says "only add it for versions ending in "SNAPSHOT", and built by a buildbot.  Not sure though...  Definitely needs a "prefix >= 24" check, too.

```
$(if $(filter %SNAPSHOT-y,$(VERSION_NUMBER)-$(CONFIG_BUILDBOT))
```

**Comment by kuanyili** [comment]
23.05-SNAPSHOT also doesn't have kernel modules in `packages`.

https://downloads.openwrt.org/releases/23.05-SNAPSHOT/targets/x86/64/packages/

There might be a change of behavior from CI (buildbot) side at some point. If this is the case, 23.05.6 will also be affected, not just 24.10.x. 

We should probably append `kmods` feed no matter what?

**Comment by efahl** [comment]
> There might be a change of behavior from CI (buildbot) side at some point. If this is the case, 23.05.6 will also be affected, not just 24.10.x.

Yeah, that is indeed the case.  Here's how I handled it in the ASU server, but it's ugly as sin and it would be nice if there were a "buildbot/CI version" somewhere to make this logic cleaner.

https://github.com/openwrt/asu/blob/07ef08e9db8ccd13e439b8338150f32b1594447b/asu/util.py#L390

**Comment by Ansuel** [comment]
We will tag a new -rc2 later today to handle this.

**Comment by zebulon30** [comment]
Hi all,
In OpenWrt 24.10.0-rc2 r28161-ea17e958b9, I can't install the kmod-usb-storage-uas.

root@OpenWrt:~# opkg install kmod-usb-storage-uas
Unknown package 'kmod-usb-storage-uas'.
Collected errors:
 * opkg_install_cmd: Cannot install package kmod-usb-storage-uas.
root@OpenWrt:~# 

I think there are a lot of missing modules.

**Comment by robimarko** [comment]
What is the target you are using?

**Comment by zebulon30** [comment]
mediatek/filogic

**Comment by robimarko** [comment]
Then its weird as uas is there along with all kmods:
https://downloads.openwrt.org/releases/24.10.0-rc2/targets/mediatek/filogic/kmods/6.6.63-1-56564de2705a53e5f6456d5babec92a2/

UAS:
https://downloads.openwrt.org/releases/24.10.0-rc2/targets/mediatek/filogic/kmods/6.6.63-1-56564de2705a53e5f6456d5babec92a2/kmod-usb-storage-uas_6.6.63-r1_aarch64_cortex-a53.ipk

**Comment by efahl** [comment]
Does the `kmods` feed appear in distfeeds for your install?  Should look like third line here on the file from my x86 install...
```
$ cat /etc/opkg/distfeeds.conf
src/gz openwrt_core https://downloads.openwrt.org/releases/24.10.0-rc2/targets/x86/64/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10.0-rc2/packages/x86_64/base
src/gz openwrt_kmods https://downloads.openwrt.org/releases/24.10.0-rc2/targets/x86/64/kmods/6.6.63-1-fdf628e4ac1bbb67c9c54e22238868e0
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.0-rc2/packages/x86_64/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.0-rc2/packages/x86_64/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10.0-rc2/packages/x86_64/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10.0-rc2/packages/x86_64/telephony
```

**Comment by zebulon30** [comment]
No, it doesn't : 

```
root@OpenWrt:~# cat /etc/opkg/distfeeds.conf
src/gz openwrt_core https://downloads.openwrt.org/releases/24.10.0-rc2/targets/mediatek/filogic/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/base
# src/gz openwrt__alpine_fan_control https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/_alpine_fan_control
# src/gz openwrt__amneziawg https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/_amneziawg
# src/gz openwrt__podkop https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/_podkop
# src/gz openwrt__ruantiblock https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/_ruantiblock
# src/gz openwrt__xwrt_packages https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/_xwrt_packages
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/telephony
root@OpenWrt:~# 
```

**Comment by efahl** [comment]
Aha.  Add this, do `opkg update` and see if it picks it up:
```
src/gz openwrt_kmods https://downloads.openwrt.org/releases/24.10.0-rc2/targets/mediatek/filogic/kmods/6.6.63-1-56564de2705a53e5f6456d5babec92a2
```

**Comment by zebulon30** [comment]
Nop !

```
root@OpenWrt:~# opkg update
Downloading https://fantastic-packages.github.io/packages/releases/24.10/packages/aarch64_cortex-a53/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/fantastic_packages_luci
Downloading https://fantastic-packages.github.io/packages/releases/24.10/packages/aarch64_cortex-a53/luci/Packages.sig
Signature check passed.
Downloading https://fantastic-packages.github.io/packages/releases/24.10/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/fantastic_packages_packages
Downloading https://fantastic-packages.github.io/packages/releases/24.10/packages/aarch64_cortex-a53/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/mediatek/filogic/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/targets/mediatek/filogic/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/aarch64_cortex-a53/telephony/Packages.sig
Signature check passed.
root@OpenWrt:~# 
```


So openwrt_kmods is missing in my installation.

I get the bin here : https://drive.google.com/drive/folders/1HM5eIGm5_RZi0NcXG8tagRKGu9joLTEo

**Comment by robimarko** [comment]
Where did you get that binary from?

Because when I unpack the official OpenWrt image, and check `distfeeds.conf` the kmods feed is clearly listed:
`src/gz openwrt_kmods https://downloads.openwrt.org/releases/24.10.0-rc2/targets/mediatek/filogic/kmods/6.6.63-1-56564de2705a53e5f6456d5babec92a2`

**Comment by efahl** [comment]
And I'm not seeing any evidence in the opkg update output that it read the line that you just added to `/etc/opkg/distfeed.conf`...

**Comment by zebulon30** [comment]
OK, so where/how can I get an official 24.10.0 for my routeur (ASUS TUF AX4200) ? Thanks.
I'm an old professional web developer but a beginner with all these things.

**Comment by robimarko** [comment]
Like with all OpenWrt releases on downloads.openwrt.org:
https://downloads.openwrt.org/releases/24.10.0-rc2/targets/mediatek/filogic/

**Comment by zebulon30** [comment]
I saw that the file for me  is at a size of 9260.3 KB. The unoffical version is 32 MB so I suppose the unofficial version embed a lot of things ?

**Comment by zebulon30** [comment]
I installed the official 24.10.0-rc2 and the main difference with the unofficial one is the web interface.
It is more coloful, menu is left instead of top, and it is different. It has a Dashboard, a Services menu and inside the Services menu a lot of applications (Podkop, Dynamic DNS, NextDNS, BandwithMonitor, ...).

**Comment by zebulon30** [comment]
Yes, I found all this stuff. It was the openwrt2020 theme.
I'm starting to understand how all of this fits together.
Thank you all for your help.
Have a good day.
