### ISSUE TITLE
wifi-scripts: ucode implementation - only first interface starts

### ISSUE THREAD

**Issue by rmandrad** [openwrt/openwrt#17159]
### Describe the bug

mediatek/filogic bananapi4

iw dev

phy#0
        Interface phy0.1-ap0
                ifindex 15
                wdev 0x6
                addr xxx9
                type AP
                multicast TXQ:
                        qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                        0       0       0       0       0       0       0       0               0
                Radios: 1
        Interface phy0.2-ap0
                ifindex 14
                wdev 0x5
                addr xxx
                type AP
                multicast TXQ:
                        qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                        0       0       0       0       0       0       0       0               0
                Radios: 2
        Interface phy0.0-ap0
                ifindex 12
                wdev 0x3
                addr xxx
                ssid love
                type AP
                channel 6 (2437 MHz), width: 40 MHz, center1: 2447 MHz
                txpower 23.00 dBm
                multicast TXQ:
                        qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                        0       0       233     0       0       0       0       61697           264
                Radios: 0

Only phy0.0-ap0 starts

phy0.1-ap0 error at start

`Wed Dec  4 05:11:57 2024 daemon.notice netifd: radio1 (7492): wifi-scripts: Tearing down phy0
Wed Dec  4 05:11:57 2024 daemon.notice hostapd: Set new config for phy phy0.1:
Wed Dec  4 05:11:57 2024 daemon.notice hostapd: Remove interface 'phy0.1'
Wed Dec  4 05:11:57 2024 daemon.notice hostapd: phy0.1-ap0: interface state DISABLED->DISABLED
Wed Dec  4 05:11:57 2024 daemon.notice hostapd: phy0.1-ap0: AP-DISABLED
Wed Dec  4 05:11:57 2024 daemon.notice hostapd: phy0.1-ap0: CTRL-EVENT-TERMINATING
Wed Dec  4 05:11:57 2024 daemon.err hostapd: rmdir[ctrl_interface=/var/run/hostapd]: Permission denied
Wed Dec  4 05:11:57 2024 daemon.err hostapd: hostapd_free_hapd_data: Interface phy0.1-ap0 wasn't started
Wed Dec  4 05:11:57 2024 daemon.notice hostapd: nl80211: deinit ifname=phy0.1-ap0 disabled_11b_rates=0
Wed Dec  4 05:11:57 2024 kern.info kernel: [  575.681181] mt7996e 0000:01:00.0 phy0.1-ap0: left allmulticast mode
Wed Dec  4 05:11:57 2024 kern.info kernel: [  575.687511] mt7996e 0000:01:00.0 phy0.1-ap0: left promiscuous mode
Wed Dec  4 05:11:57 2024 kern.info kernel: [  575.693799] br-lan: port 5(phy0.1-ap0) entered disabled state
Wed Dec  4 05:11:57 2024 daemon.notice wpa_supplicant[2367]: Set new config for phy phy0.1
Wed Dec  4 05:11:57 2024 daemon.notice netifd: Wireless device 'radio1' is now down
Wed Dec  4 05:11:57 2024 daemon.notice netifd: radio1 (7512): wifi-scripts: Starting
Wed Dec  4 05:11:57 2024 daemon.notice hostapd: Set new config for phy phy0.1:
Wed Dec  4 05:11:57 2024 daemon.notice wpa_supplicant[2367]: Set new config for phy phy0.1
Wed Dec  4 05:11:57 2024 daemon.notice netifd: radio1 (7512): command failed: Not supported (-95)
Wed Dec  4 05:11:57 2024 daemon.notice hostapd: Set new config for phy phy0.1: /var/run/hostapd-phy0.1.conf
Wed Dec  4 05:11:57 2024 daemon.notice hostapd: Restart interface for phy phy0.1
Wed Dec  4 05:11:58 2024 daemon.notice hostapd: Configuration file: data: driver=nl80211 logger_syslog=127 logger_syslog_level=0 logger_stdout=127 logger_stdout_level=0 country_code=GB ieee80211h=1 ieee80211d=1 spectrum_mgmt_required=0 supported_rates=240 360 480 540 basic_rates=240 beacon_int=100 mbssid=0 noscan=0 airtime_mode=0 rssi_reject_assoc_rssi=0 rssi_ignore_probe_request=0 acs_exclude_dfs=0 enable_background_radar=1 min_tx_power=0 hw_mode=a ieee80211n=1 ht_coex=0 ht_capab=[HT40+][LDPC][SHORT-GI-20][SHORT-GI-40][TX-STBC][MAX-AMSDU-7935][RX-STBC1] ieee80211ac=1 vht_oper_chwidth=2 vht_oper_centr_freq_seg0_idx=50 vht_capab= he_bss_color=128 he_spr_sr_control=3 ieee80211ax=1 he_oper_chwidth=2 he_oper_centr_freq_seg0_idx=50 he_su_beamformer=1 he_su_beamformee=1 he_mu_beamformer=1 he_twt_required=0 he_default_pe_duration=4 he_rts_threshold=1023 he_mu_edca_qos_info_param_count=0 he_mu_edca_qos_info_q_ack=0 he_mu_edca_qos_info_queue_request=0 he_mu_edca_qos_info_txop_request=0 he_mu_edca_ac_be_aifsn=8 he_mu_edca_ac_be_aci=0 he
Wed Dec  4 05:11:58 2024 kern.info kernel: [  576.155877] br-lan: port 5(phy0.1-ap0) entered blocking state
Wed Dec  4 05:11:58 2024 kern.info kernel: [  576.161660] br-lan: port 5(phy0.1-ap0) entered disabled state
Wed Dec  4 05:11:58 2024 kern.info kernel: [  576.167445] mt7996e 0000:01:00.0 phy0.1-ap0: entered allmulticast mode
Wed Dec  4 05:11:58 2024 kern.info kernel: [  576.174128] mt7996e 0000:01:00.0 phy0.1-ap0: entered promiscuous mode
Wed Dec  4 05:11:58 2024 daemon.notice hostapd: phy0.1-ap0: interface state UNINITIALIZED->COUNTRY_UPDATE
Wed Dec  4 05:11:58 2024 daemon.notice hostapd: phy0.1-ap0: interface state COUNTRY_UPDATE->HT_SCAN
Wed Dec  4 05:11:58 2024 daemon.notice netifd: Wireless device 'radio1' is now up
Wed Dec  4 05:11:58 2024 daemon.notice netifd: radio1 (7512): wifi-scripts: Configuring 'phy0' txantenna: 4294967295, rxantenna: 4294967295 distance: 0
Wed Dec  4 05:11:58 2024 daemon.notice netifd: radio1 (7512): wifi-scripts: network is not present in the schema
Wed Dec  4 05:11:58 2024 daemon.notice netifd: radio1 (7512): wifi-scripts: Preparing interface: phy0.1-ap0 with MAC: 46:eb:49:35:dd:39
Wed Dec  4 05:11:58 2024 daemon.notice hostapd: phy0.1-ap0: interface state HT_SCAN->DFS
Wed Dec  4 05:11:58 2024 daemon.notice hostapd: phy0.1-ap0: DFS-CAC-START freq=5500 chan=100 sec_chan=1, width=2, seg0=50, seg1=0, cac_time=60s
Wed Dec  4 05:11:58 2024 daemon.err hostapd: 160 MHz: HT40 channel band is not in 160 MHz band
Wed Dec  4 05:11:58 2024 daemon.err hostapd: Can't set freq params
Wed Dec  4 05:11:58 2024 daemon.err hostapd: DFS start_dfs_cac() failed, -1
Wed Dec  4 05:11:58 2024 daemon.err hostapd: Interface initialization failed
Wed Dec  4 05:11:58 2024 daemon.notice hostapd: phy0.1-ap0: interface state DFS->DISABLED
Wed Dec  4 05:11:58 2024 daemon.notice hostapd: phy0.1-ap0: AP-DISABLED
`
phy0.2-ap0 error at start

`Wed Dec  4 05:11:11 2024 daemon.notice netifd: radio2 (7439): wifi-scripts: Tearing down phy0
Wed Dec  4 05:11:11 2024 daemon.notice hostapd: Set new config for phy phy0.2:
Wed Dec  4 05:11:11 2024 daemon.notice wpa_supplicant[2367]: Set new config for phy phy0.2
Wed Dec  4 05:11:11 2024 daemon.notice netifd: Wireless device 'radio2' is now down
Wed Dec  4 05:11:11 2024 daemon.notice netifd: radio2 (7454): wifi-scripts: Starting
Wed Dec  4 05:11:11 2024 daemon.notice hostapd: Set new config for phy phy0.2:
Wed Dec  4 05:11:11 2024 daemon.notice wpa_supplicant[2367]: Set new config for phy phy0.2
Wed Dec  4 05:11:11 2024 daemon.notice netifd: radio2 (7454): command failed: Not supported (-95)
Wed Dec  4 05:11:11 2024 daemon.notice hostapd: Set new config for phy phy0.2: /var/run/hostapd-phy0.2.conf
Wed Dec  4 05:11:11 2024 daemon.notice hostapd: Restart interface for phy phy0.2
Wed Dec  4 05:11:12 2024 daemon.notice hostapd: Configuration file: data: driver=nl80211 logger_syslog=127 logger_syslog_level=0 logger_stdout=127 logger_stdout_level=0 country_code=GB ieee80211h=0 ieee80211d=1 spectrum_mgmt_required=0 supported_rates=240 360 480 540 basic_rates=240 beacon_int=100 mbssid=0 noscan=0 airtime_mode=0 rssi_reject_assoc_rssi=0 rssi_ignore_probe_request=0 acs_exclude_dfs=0 min_tx_power=0 hw_mode=a op_class=137 he_bss_color=128 he_spr_sr_control=3 ieee80211ax=1 he_oper_chwidth=0 he_oper_centr_freq_seg0_idx=0 he_su_beamformer=1 he_su_beamformee=1 he_mu_beamformer=1 he_twt_required=0 he_default_pe_duration=4 he_rts_threshold=1023 he_mu_edca_qos_info_param_count=0 he_mu_edca_qos_info_q_ack=0 he_mu_edca_qos_info_queue_request=0 he_mu_edca_qos_info_txop_request=0 he_mu_edca_ac_be_aifsn=8 he_mu_edca_ac_be_aci=0 he_mu_edca_ac_be_ecwmin=9 he_mu_edca_ac_be_ecwmax=10 he_mu_edca_ac_be_timer=255 he_mu_edca_ac_bk_aifsn=15 he_mu_edca_ac_bk_aci=1 he_mu_edca_ac_bk_ecwmin=9 he_mu_edca_ac_bk_ecwmax=10 he_mu_edca_ac_bk_
Wed Dec  4 05:11:12 2024 kern.info kernel: [  530.486244] br-lan: port 7(phy0.2-ap0) entered blocking state
Wed Dec  4 05:11:12 2024 kern.info kernel: [  530.492001] br-lan: port 7(phy0.2-ap0) entered disabled state
Wed Dec  4 05:11:12 2024 kern.info kernel: [  530.497763] mt7996e 0000:01:00.0 phy0.2-ap0: entered allmulticast mode
Wed Dec  4 05:11:12 2024 kern.info kernel: [  530.504447] mt7996e 0000:01:00.0 phy0.2-ap0: entered promiscuous mode
Wed Dec  4 05:11:12 2024 daemon.notice hostapd: phy0.2-ap0: interface state UNINITIALIZED->COUNTRY_UPDATE
Wed Dec  4 05:11:12 2024 daemon.err hostapd: nl80211: kernel reports: invalid channel definition
Wed Dec  4 05:11:12 2024 daemon.err hostapd: Could not set channel for kernel driver
Wed Dec  4 05:11:12 2024 daemon.err hostapd: Interface initialization failed
Wed Dec  4 05:11:12 2024 daemon.notice hostapd: phy0.2-ap0: interface state COUNTRY_UPDATE->DISABLED
Wed Dec  4 05:11:12 2024 daemon.notice hostapd: phy0.2-ap0: AP-DISABLED
Wed Dec  4 05:11:12 2024 daemon.err hostapd: phy0.2-ap0: Unable to setup interface.
Wed Dec  4 05:11:12 2024 daemon.notice hostapd: nl80211: deinit ifname=phy0.2-ap0 disabled_11b_rates=0
Wed Dec  4 05:11:12 2024 kern.info kernel: [  530.512400] mt7996e 0000:01:00.0 phy0.2-ap0: left allmulticast mode
Wed Dec  4 05:11:12 2024 kern.info kernel: [  530.518698] mt7996e 0000:01:00.0 phy0.2-ap0: left promiscuous mode
Wed Dec  4 05:11:12 2024 kern.info kernel: [  530.524962] br-lan: port 7(phy0.2-ap0) entered disabled state
Wed Dec  4 05:11:12 2024 daemon.err hostapd: rmdir[ctrl_interface=/var/run/hostapd]: Permission denied
Wed Dec  4 05:11:12 2024 daemon.notice hostapd: phy0.2-ap0: CTRL-EVENT-TERMINATING
Wed Dec  4 05:11:12 2024 daemon.err hostapd: hostapd_free_hapd_data: Interface phy0.2-ap0 wasn't started
Wed Dec  4 05:11:12 2024 daemon.notice hostapd: hostapd.add_iface failed for phy phy0.2 ifname=phy0.2-ap0
Wed Dec  4 05:11:12 2024 daemon.notice netifd: Wireless device 'radio2' is now up
Wed Dec  4 05:11:12 2024 daemon.notice netifd: radio2 (7454): wifi-scripts: Configuring 'phy0' txantenna: 4294967295, rxantenna: 4294967295 distance: 0
Wed Dec  4 05:11:12 2024 daemon.notice netifd: radio2 (7454): wifi-scripts: network is not present in the schema
`
/etc/config/wireless

`config wifi-device 'radio0'
        option type 'mac80211'
        option path 'soc/11300000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
        option radio '0'
        option htmode 'HE40'
        option country 'GB'
        option band '2g'
        option channel '6'
        option log_level '0'
        option cell_density '3'
        option doth '1'
        list hostapd_options 'rnr=1'
        list hostapd_options 'mld_ap=0'
        option noscan '1'

config wifi-iface 'default_radio0'
        option device 'radio0'
        option network 'lan'
        option mode 'ap'
        option ssid 'love'
        option encryption 'sae-mixed'
        option mbo '0'
        option key 'xxx'
        option ocv '1'
        option ieee80211r '1'
        option ft_over_ds '0'
        option pmk_r1_push '1'
        option ieee80211k '1'
        option time_advertisement '2'
        option time_zone 'GMT0BST,M3.5.0/1,M10.5.0'
        option wnm_sleep_mode '1'
        option wnm_sleep_mode_no_keys '1'
        option bss_transition '1'
        option proxy_arp '1'

config wifi-device 'radio1'
        option type 'mac80211'
        option path 'soc/11300000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
        option radio '1'
        option htmode 'HE160'
        option channel '100'
        option country 'GB'
        option band '5g'
        option log_level '0'
        option background_radar '1'
        option cell_density '3'
        option doth '1'
        list hostapd_options 'rnr=1'
        list hostapd_options 'mld_ap=0'

config wifi-iface 'default_radio1'
        option device 'radio1'
        option network 'lan'
        option mode 'ap'
        option ssid 'love'
        option encryption 'sae-mixed'
        option mbo '0'
        option key 'xxx'
        option ocv '1'
        option ieee80211r '1'
        option ft_over_ds '0'
        option pmk_r1_push '1'
        option ieee80211k '1'
        option time_advertisement '2'
        option time_zone 'GMT0BST,M3.5.0/1,M10.5.0'
        option wnm_sleep_mode '1'
        option wnm_sleep_mode_no_keys '1'
        option bss_transition '1'
        option proxy_arp '1'

config wifi-device 'radio2'
        option type 'mac80211'
        option path 'soc/11300000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
        option radio '2'
        option band '6g'
        option channel '53'
        option htmode 'EHT320'
        option country 'GB'
        option log_level '0'
        option background_radar '0'
        option cell_density '3'
        option doth '0'
        list hostapd_options 'unsol_bcast_probe_resp_interval=20'
        list hostapd_options 'mld_ap=0'

config wifi-iface 'default_radio2'
        option device 'radio2'
        option network 'lan'
        option mode 'ap'
        option ssid 'love'
        option beacon_prot '1'
        option encryption 'sae'
        option sae_pwe '2'
        option key 'xxx'
        option ieee80211w '2'
        option mbo '1'
        option ocv '0'
        option ieee80211r '1'
        option ft_over_ds '0'
        option ieee80211k '1'
        option time_advertisement '2'
        option time_zone 'GMT0BST,M3.5.0/1,M10.5.0'
        option wnm_sleep_mode '1'
        option wnm_sleep_mode_no_keys '1'
        option bss_transition '1'
        option pmk_r1_push '1'
        option proxy_arp '1'

ping @blogic 

### OpenWrt version

r28268-d4d161b8f3

### OpenWrt release

6.6.63-12

### OpenWrt target/subtarget

mediatek/filogic

### Device

Bananapi BPI-R4

### Image kind

Self-built image

### Steps to reproduce

build wifi-scripts with new ucode based scripts

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
Could you, please, format code blocks,?
