### ISSUE TITLE
imagebuilder: "Cannot install package kmod-mt7921u"

### ISSUE THREAD

**Issue by nerdhardest** [openwrt/openwrt#17165]
### Describe the bug

Output from imagebuilder 24.10.0-rc1.

### OpenWrt version

24.10.0-rc1

### OpenWrt release

24.10.0-rc1

### OpenWrt target/subtarget

glinet_gl-ar750s-nor-nand

### Device

glinet_gl-ar750s-nor-nand

### Image kind

Official downloaded image

### Steps to reproduce

Try to build image for "24.10.0-rc1-ath79-nand" and include package "kmod-mt7921u".

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
Ignore the bot, it has certain versioning and model expectations.

But can you please include the log that captures the error

**Comment by nerdhardest** [comment]
Sounds like KA2107 is correct; this is likely a duplicate of 17146.

I'll wait for -rc2 to try again.

Thx.

**Comment by hauke** [comment]
fixed in ea17e958b9933aaf3e4a390073025aa226fe91b7
