### ISSUE TITLE
[24.10.0-rc2] Lost wifi on upgrade because device path has changed

### ISSUE THREAD

**Issue by MatMaul** [openwrt/openwrt#17174]
### Describe the bug

I did a sysupgrade from 23.05.5 to 24.10.0-rc2 and lost wifi on the way.

After checking `/etc/config/wireless` it seems the wifi device paths have changed from `platform/18000000.wifi` to `platform/soc/18000000.wifi`, but a migration seems missing somewhere.

New `wifi-device` has been created with the new path instead of updating the paths of the existing ones.
After deleting new entries and updating the paths in the original ones, everything was back to working state.

### OpenWrt version

r28161-ea17e958b9

### OpenWrt release

24.10.0-rc2

### OpenWrt target/subtarget

mediatek/filogic

### Device

Cudy WR3000 v1

### Image kind

Self-built image

### Additional info

I am not sure it's relevant but in case of, here is my build command line:
`make image PROFILE=cudy_wr3000-v1 PACKAGES="-wpad-basic-mbedtls wpad-mbedtls luci-ssl luci-app-tinyproxy kmod-batman-adv luci-app-sqm luci-app-uhttpd qrencode htop iperf3 irqbalance kmod-tun kmod-tcp-bbr luci-mod-rpc luci-app-opkg luci-proto-batman-adv luci-theme-material openssh-sftp-server coreutils-mktemp fping bash tcpdump nextdns luci-app-nextdns privoxy"`

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by gabrielambuehl** [comment]
Updated my mt3000 from 24.10.0-rc2 to  OpenWrt 24.10-SNAPSHOT, r28179-aa1241e979 just now, can confirm that the issue is fixed.
