### ISSUE TITLE
[24.10.0-rc2] Netgear RAX120v2 `Web-UI-Factory` image does not works

### ISSUE THREAD

**Issue by zsh** [openwrt/openwrt#17213]
### Describe the bug

The image downloaded from https://downloads.openwrt.org/releases/24.10.0-rc2/targets/qualcommax/ipq807x/openwrt-24.10.0-rc2-qualcommax-ipq807x-netgear_rax120v2-squashfs-web-ui-factory.img doesn't works when upload to via netgear stock UI.

It was [reported](https://forum.openwrt.org/t/adding-openwrt-support-for-netgear-rax120-nighthawk-ax12/75592/488) that `AgustinLorenzo 2024-05-15 Web-UI factory image` works fine.

### OpenWrt version

r28161-ea17e958b9

### OpenWrt release

24.10.0-rc2

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Netgear RAX120v2

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
This was already fixed via:
https://github.com/openwrt/openwrt/commit/863d1a634e88b6db497622e5f007acca1adad60b

It will be part of RC3
