### ISSUE TITLE
Snapshot error:  /etc/rc.d/S96led: sh: write error: Invalid argument

### ISSUE THREAD

**Issue by edrikk** [openwrt/openwrt#17269]
### Describe the bug

With the recent LED changes committed to Snapshot/main the log shows the message:

Sat Dec 14 12:42:08 2024 daemon.notice procd: /etc/rc.d/S96led: sh: write error: Invalid argument

This is seen on Xioami Redmi AX6S devices and Xiaomi Redmi AX3600 samples.

### OpenWrt version

r28330-15e173bf7e

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Xiaomi Redmi Router AX6S

### Image kind

Self-built image

### Steps to reproduce

Install latest snapshot such as https://github.com/openwrt/openwrt/commit/15e173bf7e873d004d6c665ee81d54a10ce1f868
View log file searching for "error" or "S96"

### Actual behaviour

Error message:  daemon.notice procd: /etc/rc.d/S96led: sh: write error: Invalid argument

### Expected behaviour

No error

### Diffconfig

```text
firmware-selector build.
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by edrikk** [comment]
@blogic ping for awareness

**Comment by blogic** [comment]
@edrikk fix is in main branch now, Thanks!

**Comment by edrikk** [comment]
Fixed.  Thank you!
