### ISSUE TITLE
GitHub repository for atf-builds is missing

### ISSUE THREAD

**Issue by BKPepe** [openwrt/openwrt#17268]
### Describe the bug

In OpenWrt 22.03 and OpenWrt 23.05, there is package arm-trusted-firmware-rockchip. This package is downloaded fron GitHub repository, which is no longer publicly available. You can check it by this: https://github.com/atf-builds

While downloading, it says that it is not found:
```
curl -f --connect-timeout 20 --retry 5 --location https://github.com/atf-builds/atf/releases/download/v2.3/atf-v2.3.tar.gz?/atf-v2.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) The requested URL returned error: 404
Download failed.
```

Luckily, the tarball is downloaded by Sources CDN OpenWrt, but would good to have available original sources for it.

### OpenWrt version

22.03 and 23.05

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ynezz** [comment]
Should be fixed, thanks a lot for reporting!
