### ISSUE TITLE
Proton VPN via Wireguard

### ISSUE THREAD

**Issue by Jaeg3rr** [openwrt/openwrt#17288]
Hello,

as the title above says I am trying to get the Proton VPN working with the wireguard VPN protocol. I have used it with openVPN but I have experienced network timeouts for my wifi connection as i was using PBR to route all my PC traffic directly to my ISP and all other devices that are connected to the network via WiFi to go through VPN.

Now I have switched to Wireguard VPN protovol but i have no network acces on my wifi AP. I have only network on my PC as it is routed via the PBR to my ISP directly.

Here is my configuration: 
![Untitled8](https://github.com/user-attachments/assets/eb5461ce-b031-4a2d-9a53-b6306e04985e)
![Untitled7](https://github.com/user-attachments/assets/fb765faf-047f-40e0-9063-c8046b8c06eb)
![Untitled6](https://github.com/user-attachments/assets/61dcec90-9cc1-4aad-aa1e-ff7ee4ef7a88)
![Untitled5](https://github.com/user-attachments/assets/e3ab96f3-dd5b-4ab2-84c6-9fc4ccaa72ad)
![Untitled4](https://github.com/user-attachments/assets/97c6c42a-722a-4a58-8fd1-22c7e4a12321)
![Untitled3](https://github.com/user-attachments/assets/ddccbc67-bfdc-4a28-987d-c9acaa807fc0)
![Untitled2](https://github.com/user-attachments/assets/ea079eb1-1a7e-42c4-888c-44a0277ac6ef)
![Untitled](https://github.com/user-attachments/assets/a1d3417e-5eca-407d-bbfb-45fa2618378a)

And Logs
![image](https://github.com/user-attachments/assets/bd26e426-a05f-49dd-ae07-83b23fee27dc)

Best regards,

**Comment by brada4** [comment]
Hello,
please fill the issue template , and use code boxes to format text configurations.  3rd fw zone rule makes no sense at all

**Comment by SirNewis** [comment]
Hello, 

yes i know it doesn't make sense but i found it on some forum as a fix for someone also wirh no network access.

I configured it now as it should be but still no network access:
![image](https://github.com/user-attachments/assets/f1d63b77-cabc-4cf7-9902-bda0c8929ce3)

**Comment by brada4** [comment]
You ¡hould close your usage questions, they are not bugs warranting code change to fix.

**Comment by brada4** [comment]
Check in openwrt forum for living person to assist you.
