### ISSUE TITLE
hostapd: invalid key_mgmt 'SAE'

### ISSUE THREAD

**Issue by attila-lendvai** [openwrt/openwrt#17306]
### Describe the bug

# symptom

in my config i have:
```
uci set wireless.lan0.encryption='sae-mixed'
```

in the log i see:
```
daemon.err hostapd: Line 51: invalid key_mgmt 'SAE'
```

# analysis

credit goes [here](https://gist.github.com/est31/d92d17acbb4ea152296f9b38764cd791):

as per the [hostapd source](https://w1.fi/cgit/hostap/tree/hostapd/config_file.c#n678) it only recognizes `SAE` when `CONFIG_SAE=y`.

~~but [in the makefile](https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=package/network/services/hostapd/Makefile#l102) it's only enabled for the `wpad-mesh` variant.~~

**EDIT: i have updated the links to the latest versions of the sources, and the Makefile enables `CONFIG_SAE` for all three ssl lib variants, so i will have to double check whether `wpad` really fails and installing `wpad-mesh` solves the issue.**

installing `wpad-mesh` instead of `wpad` fixes the problem.

# proposed fix

please also enable `CONFIG_SAE=y` for the full wpad package.

### OpenWrt version

r28161-ea17e958b9

### OpenWrt release

24.10.0-rc2

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link TL-WDR4300 v1

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
The parameter name is "encryption" , there is no 1:1 match with hostapd parameters.
The hostap source you selected pertains OpenWRT v18 from five years ago.

**Comment by attila-lendvai** [comment]
> The parameter name is "encryption" , there is no 1:1 match with hostapd parameters. The hostap source you selected pertains OpenWRT v18 from five years ago.

i'm not sure which parameter you mean, so, to clarify:

i have set my config with luci (and then copied it into `uci` calls). then i have upgraded my `wpad` package to the full package because of some other error (iirc it was to handle `bss_transition='1'`). and that's when i saw the `daemon.err hostapd: Line 51: invalid key_mgmt 'SAE'` error.

**Comment by brada4** [comment]
Can you trigger any error from luci? Openwrt 18 needs 4x upgrade of your scripts.

**Comment by attila-lendvai** [comment]
> Can you trigger any error from luci? Openwrt 18 needs 4x upgrade of your scripts.

sorry for not being clear! i'm doing everything on `OpenWrt 24.10.0-rc2 r28161-ea17e958b9`.

the document i'm linking to is several years old, but it contained the right solution for me: to install `wpad-mesh` instead of `wpad`, which is supposed to be a full wpad in 24.10, at least AFAIU.

**Comment by brada4** [comment]
wpa3 is supported in all wpad hostap supplicant packages. Just rolled through installing them all and ap started up every time.
mixed m{de will not work for 11s mesh

**Comment by attila-lendvai** [comment]
# double checked, it's reproducible

i'm still getting this in the log, and wifi doesn't come up:

```
Fri Dec 20 17:39:04 2024 daemon.err hostapd: Line 51: invalid key_mgmt 'SAE'
```

```
root      1473  0.0  1.0   2936  1228 ?        S    17:38   0:00 /sbin/ujail -t 5 -n hostapd -U network -G network -C /etc/capabilities/wpad.json -c -- /usr/sb
network   1479  0.0  2.3   4284  2820 ?        S    17:38   0:00  \_ /usr/sbin/hostapd -s -g /var/run/hostapd/global
```

```
# opkg list-installed | grep wpad
wpad - 2024.09.15~5ace39b0-r1
```

```
# cat /etc/openwrt_release 
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='24.10.0-rc2'
DISTRIB_REVISION='r28161-ea17e958b9'
DISTRIB_TARGET='ath79/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='OpenWrt 24.10.0-rc2 r28161-ea17e958b9'
DISTRIB_TAINTS=''
```

# causality?

the following fixes the issue (error from the log disappears, and wifi comes up. no reboot necessary):

```
# opkg remove wpad
# opkg install wpad-mesh
# /etc/init.d/wpad restart
```

and the following brings back the error in the log and brings down wifi (without reboot):

```
# opkg remove wpad-mesh-mbedtls
# opkg install wpad
Installing wpad (2024.09.15~5ace39b0-r1) to root...
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mips_24kc/base/wpad_2024.09.15~5ace39b0-r1_mips_24kc.ipk
Configuring wpad.
# /etc/init.d/wpad restart
```

this is my `/etc/config/wireless`:

```

config wifi-device 'radio0'
	option type 'mac80211'
	option path 'platform/ahb/18100000.wmac'
	option band '2g'
	option channel '8'
	option htmode 'HT40'
	option disabled '0'
	option cell_density '0'
	option country 'HU'

config wifi-device 'radio1'
	option type 'mac80211'
	option path 'pci0000:00/0000:00:00.0'
	option band '5g'
	option channel '120'
	option htmode 'HT40'
	option disabled '0'
	option cell_density '0'
	option country 'HU'

config wifi-iface 'lan0'
	option device 'radio0'
	option mode 'ap'
	option network 'lan'
	option ssid 'L15'
	option encryption 'sae-mixed'
	option key 'xxx'
	option ocv '0'
	option ieee80211r '1'
	option ieee80211k '1'
	option bss_transition '1'
	option mobility_domain '1f39'
	option ft_over_ds '0'

config wifi-iface 'lan1'
	option device 'radio1'
	option mode 'ap'
	option network 'lan'
	option ssid 'L15'
	option encryption 'sae-mixed'
	option key 'xxx'
	option ocv '0'
	option ieee80211r '1'
	option mobility_domain '1f39'
	option ft_over_ds '0'

config wifi-iface 'guest0'
	option device 'radio0'
	option mode 'ap'
	option network 'guest'
	option ssid 'L15 Guest'
	option encryption 'none'

config wifi-iface 'guest1'
	option device 'radio1'
	option mode 'ap'
	option network 'guest'
	option ssid 'L15 Guest'
	option encryption 'none'

```

let me know if you need any more info.

**Comment by attila-lendvai** [comment]
one more thing: notice that it's `wpad` (i.e. no `-mbedtls` suffix), and `wpad-mesh-mbedtls`, with suffix. not sure if this means anything.

```
# opkg remove wpad
Removing package wpad from root...
# opkg install wpad-mesh
Installing wpad-mesh-mbedtls (2024.09.15~5ace39b0-r1) to root...
Downloading https://downloads.openwrt.org/releases/24.10.0-rc2/packages/mips_24kc/base/wpad-mesh-mbedtls_2024.09.15~5ace39b0-r1_mips_24kc.ipk
Configuring wpad-mesh-mbedtls.
# service wpad restart
```

BTW, as expected, this fixed my wifi just now, still without any reboots.

**Comment by brada4** [comment]
wpad should be equal to wpad-mbedtls historically wpad-full-XXX @nbd168 ?

**Comment by hauke** [comment]
This is intentional. hostapd needs a full crypto library like mebdtls, wolfssl or OpenSSL for SAE. You should install `wpad-mbedtls` instead.

**Comment by attila-lendvai** [comment]
> This is intentional. hostapd needs a full crypto library like mebdtls, wolfssl or OpenSSL for SAE. You should install `wpad-mbedtls` instead.

@hauke thanks for clarifying that!

the package descriptions could be adjusted for a bit more clarity, though. the description of every `wpad` package variants says:

> This package contains a full featured...

i wrongly assumed that the `wpad-[cryptolib]` variants are there for some package manager automatism to pick the right crypto library.
