### ISSUE TITLE
NAT configuration does not save Settings via LUCI web Interface

### ISSUE THREAD

**Issue by jazzyshk** [openwrt/openwrt#17341]
### Describe the bug

![IMG_7580](https://github.com/user-attachments/assets/7c74001e-cbe5-480f-bd23-eda694a88f37)

If I try to change Software or Hardware NAT setting, it only keeps rotating the circle in the save button, but it does not change anything in the configuration.

### OpenWrt version

r28202-8667ca841b

### OpenWrt release

24.10.0-rc3

### OpenWrt target/subtarget

mediatek/filogic

### Device

Xiaomi Redmi Router AX6000 (OpenWrt U-Boot layout)

### Image kind

Official downloaded image

### Steps to reproduce

Open the Firewall configuration after a factory reset and try to change Routing/NAT Offloading setting there, it will stuck after pushing the save button.

### Additional info

If I set it up in rc2 version first and then update to rc3 while maintaining the settings, the settings will be maintained.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
Fixed in https://github.com/openwrt/luci/commit/8a422af6a0e97cdb7b3df1049898731a4b2d153d
The change will be included in the next rc version.
