### ISSUE TITLE
Typo and invalid configuration option in LuCi config page for 2.4g wireless

### ISSUE THREAD

**Issue by JustAnotherEndUser** [openwrt/openwrt#17354]
### Describe the bug

In LuCi wireless config, there are AX references in 2.4Ghz radio area.  Both in the description and drop-down.

![image](https://github.com/user-attachments/assets/0d3541b0-4f5f-42b7-89a3-88588c54da0e)

### OpenWrt version

r24106-10cc5fcd00

### OpenWrt release

23.05.5

### OpenWrt target/subtarget

ipq807x/generic

### Device

Dynalink DL-WRX36

### Image kind

Official downloaded image

### Steps to reproduce

Navigate to the Network>Wireless configuration page via LuCi.  I'm not sure if this is a typo, or would actually set conflicting / non-valid options.

### Actual behaviour

"AX" is select-able in the Wireless 2.4 setup, with channels 1-11.

### Expected behaviour

I would not expect AX to be a select-able configuration option for the 2.4g radio. 

### Additional info

See screenshot.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by namiltd** [comment]
Where is the typo? The AX standard also works on the 2.4GHz band.

**Comment by JustAnotherEndUser** [comment]
@namiltd - Apologies, my error.
