### ISSUE TITLE
It is said that this performance is very good

### ISSUE THREAD

**Issue by shuangqiao999** [openwrt/openwrt#17415]
https://github.com/FDio/vpp
Can this be integrated into OpenWRT?

**Comment by vincejv** [comment]
> It is said

says who? where's the data, cpu usage, and most importantly RAM and Flash storage impact.

**Comment by neheb** [comment]
No

**Comment by shuangqiao999** [comment]
> > It is said
> 
> says who? where's the data, cpu usage, and most importantly RAM and Flash storage impact.

https://turbock79.cn/?p=318

**Comment by ynezz** [comment]
This is bug tracker, this [is not a bug](https://openwrt.org/bugs#bug_or_no_bug), see https://openwrt.org/contact for discussion about new features.
