### ISSUE TITLE
slow single-threaded file transfer from/to device

### ISSUE THREAD

**Issue by psyborg55** [openwrt/openwrt#215]
noticed this quite some time ago.

uploading firmware from luci takes some time and the upload speed to device is maxed at about 2MB/s

just tried scping file from device and could not get more than 1.2 MB/s

not sure about ssh but at least other firmwares with non-luci web interfaces allow the image to be uploaded in a second, typically somewhere around 8MB/s (it could be more but my images are not bigger than 8MB)

**Comment by bittu072** [comment]
Hi,
Try to find the directory with the max space on the device and copy file there using 'sftp'. I am using it and it is fast enough.
'sftp root@ip_of_device'
After entering password, you should be inside the device and try
'put your_filename destination_path'
