### ISSUE TITLE
Buildroot flock broken on nfs4

### ISSUE THREAD

**Issue by iandall** [openwrt/openwrt#244]
Attempting to build buildroot (recent git pull) on an NFS verion 4 mounted file system and it fails with flock EBADF. It turns out that nfs support for flock(2) is emulated with fcntl(2) and the semantics are not quite the same. I can remount the filesystem with nfs3 and -o local_lock=flock which is a work around.

However, the flock(1) command from util-linux (https://www.kernel.org/pub/linux/utils/util-linux/v2.28/) works fine. It includes the code:
```
           case EBADF:             /* since Linux 3.4 (commit 55725513) */
                      /* Probably NFSv4 where flock() is emulated by fcntl().
                       * Let's try to reopen in read-write mode.
                       */
                      if (!(open_flags & O_RDWR) &&
                          type != LOCK_SH &&
                          filename &&
                          access(filename, R_OK | W_OK) == 0) {

                              close(fd);
                              open_flags = O_RDWR;
                              fd = open_file(filename, &open_flags);

                              if (open_flags & O_RDWR)
                                      break;
                      }
```
The question is, why can't we use the host systems /usr/bin/flock if it is available, instead of building our own?

If not, can we update to include the above code?

**Comment by mkresin** [comment]
25.11.2016 12:10, Ian Dall:
> The question is, why can't we use the host systems /usr/bin/flock if it
> is available, instead of building our own?

Not every system has flock installed or it might have a different 
feature set on different platforms (MacOS for example)

> If not, can we update to include the above code?

Better use this:

https://git.lede-project.org/5d0b180f798ca53cc04be4cec82c7c56b6c25d97

Stumbled over the same issue and wrote a patch for OpenWrts flock.
