### ISSUE TITLE
Broken wifi packets on UnifiAP AC LR using OpenWRT"

### ISSUE THREAD

**Issue by dpatrakov** [openwrt/openwrt#262]
I am using ubiquity UnifiAP AC LR and my wireless configuration for trunk is:

```
config wifi-device  radio0
        option type     mac80211
        option channel  36
        option hwmode   11a
        option path     'pci0000:00/0000:00:00.0'
        option htmode   VHT80

config wifi-iface
        option device   radio0
        option network  lan
        option mode     monitor
        option ssid     openwrt
        option encryption none

config wifi-device  radio1
        option type     mac80211
        option channel  11
        option hwmode   11g
        option path     'platform/qca956x_wmac'
        option htmode   HT20

config wifi-iface
        option device   radio1
        option network  lan
        option mode     monitor
        option ssid     openwrt
        option encryption none
```

I installed the packages kmod-ath10k and ath10k-firmware-qca988x in order to get the 5GHz phy working.

Capturing with tcpdump for viewing with Wireshark: tcpdump –vvv –i wlan0 –w /tmp/dump.pcap  

wireshark show following error “[Malformed Packet: IEEE 802.11]” 
2,4 GHz - malformed packet Action
5 GHz – malformed : Probe Request, Probe Response, QOS CF-Pool, Qos Data, Reassociation Response etc.

Attached file, where packets are marked as malformed. Too much malformed packets with protocol version != 0.

[dump.zip](https://github.com/openwrt/openwrt/files/634048/dump.zip)

**Comment by nbd168** [comment]
That's normal. Monitor mode by default also captures packets that could not be received properly due to weak signal, interference, noise, etc.
Nothing to worry about...
