### ISSUE TITLE
openwrt 15.05 dnsmasq-2.73 patch failed

### ISSUE THREAD

**Issue by qianguozheng** [openwrt/openwrt#289]
make[3]: Entering directory `/data/richard/1505/openwrt/package/network/services/dnsmasq'
. /data/richard/1505/openwrt/include/shell.sh; xzcat /data/richard/1505/openwrt/dl/dnsmasq-2.73.tar.xz | tar -C /data/richard/1505/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/dnsmasq-nodhcpv6/dnsmasq-2.73/.. -xf - 

Applying ./patches/100-fix-dhcp-no-address-warning.patch using plaintext: 
patching file src/dhcp.c
Hunk #1 FAILED at 146.
Hunk #2 FAILED at 272.
Hunk #3 FAILED at 295.
Hunk #4 FAILED at 315.
4 out of 4 hunks FAILED -- saving rejects to file src/dhcp.c.rej
Patch failed!  Please fix ./patches/100-fix-dhcp-no-address-warning.patch!
make[3]: *** [/data/richard/1505/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/dnsmasq-nodhcpv6/dnsmasq-2.73/.prepared_0abe410168c45d4d978474b97b0e6589] Error 1
make[3]: Leaving directory `/data/richard/1505/openwrt/package/network/services/dnsmasq'
make[2]: *** [package/network/services/dnsmasq/compile] Error 2
make[2]: Leaving directory `/data/richard/1505/openwrt'
make[1]: *** [/data/richard/1505/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/data/richard/1505/openwrt'
make: *** [world] Error 2

**Comment by LipkeGu** [comment]
currently we have dnsmasq 2.76...

```
#
# Copyright (C) 2006-2016 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=dnsmasq
PKG_VERSION:=2.76
PKG_RELEASE:=6
...
```
