### ISSUE TITLE
busybox: Please add add/del-user applet to the base system

### ISSUE THREAD

**Issue by LipkeGu** [openwrt/openwrt#294]
It would be nice when we habe the adduser and deluser applets as part of the base system. this is needed for things like samba to create shares which are only for a user. To create a samba user we need adduser and deluser. Busybox gives us these applets.
```
root@FB7360:~# smbpasswd -a lipkegu
User lipkegu not found or invalid in /etc/passwd
Could not find user 'lipkegu' in /etc/passwd
```

**Comment by chris5560** [comment]
user/group management is implemented inside /lib/functions.sh
There are functions like user_add, group_add and much more

**Comment by wongsyrone** [comment]
If you know the format, you can simply edit them via editors.
