### ISSUE TITLE
branch naming

### ISSUE THREAD

**Issue by axet** [openwrt/openwrt#30]
Hello!

Great move! Nice to see you on github.com. Can you please you same branch naming vs packages.git and openwrt.git ?

openwrt.git have named branches yet packages.git numeric.

**Comment by fsl-jyt** [comment]
Hello!
I have rename my openwrt-patchwork to openwrt. Jonas give me some advise for layerscape: add ls1043ardb 64b target support patches. I will with my colleagues spend some time to update our patch and then submit again.
