### ISSUE TITLE
Target by ramips mt7621

### ISSUE THREAD

**Issue by nnluc073** [openwrt/openwrt#34]
I can't choose ubiquiti router x from mt7621 option. If I choose default i'll can't use sysupgrade to upgrade because Image checksum hash has been wrong!

Help me!

**Comment by JayBG** [comment]
A quick check due to missing build option for the GLi GL_MT-300A revealed that the profiles directories for the ramips Mediatek processors contain only the default profiles.
The profiles exist in the git.openwrt.org repo.
