### ISSUE TITLE
ag71xx_main.c : netdev : tx timeout and crash eth0 when WNR2200 boot with cable plugged in

### ISSUE THREAD

**Issue by carl-** [openwrt/openwrt#35]
https://github.com/openwrt/openwrt/blob/master/target/linux/ar71xx/files/drivers/net/ethernet/atheros/ag71xx/ag71xx_main.c#L466
change this line back to CC (15.05.1)version would solve this problem

**Comment by psyborg55** [comment]
i've discovered same issue on AR9531 target. DHCP did not assign an address. booting without cable and attaching it later works as expected. kernel log:

>     [    0.000000] Linux version 4.4.14 (ubuntu@ubuntu) (gcc version 5.3.0 (OpenWrt GCC 5.3.0 49934) ) #17 Mon Sep 26 21:11:33 UTC 2016
    [    0.000000] MyLoader: sysp=eb171b51, boardp=48c6c569, parts=8bb656e2
    [    0.000000] bootconsole [early0] enabled
    [    0.000000] CPU0 revision is: 00019374 (MIPS 24Kc)
    [    0.000000] SoC: Qualcomm Atheros QCA9533 ver 1 rev 1
    [    0.000000] Determined physical RAM map:
    [    0.000000]  memory: 02000000 @ 00000000 (usable)
    [    0.000000] Initrd not found or empty - disabling initrd
    [    0.000000] No valid device tree found, continuing without
    [    0.000000] Zone ranges:
    [    0.000000]   Normal   [mem 0x0000000000000000-0x0000000001ffffff]
    [    0.000000] Movable zone start for each node
    [    0.000000] Early memory node ranges
    [    0.000000]   node   0: [mem 0x0000000000000000-0x0000000001ffffff]
    [    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000001ffffff]
    [    0.000000] On node 0 totalpages: 8192
    [    0.000000] free_area_init_node: node 0, pgdat 803bd710, node_mem_map 81000000
    [    0.000000]   Normal zone: 64 pages used for memmap
    [    0.000000]   Normal zone: 0 pages reserved
    [    0.000000]   Normal zone: 8192 pages, LIFO batch:0
    [    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
    [    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
    [    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
    [    0.000000] pcpu-alloc: [0] 0 
    [    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 8128
    [    0.000000] Kernel command line:  board=TL-MR22U  console=ttyATH0,115200 rootfstype=squashfs,jffs2 noinitrd
    [    0.000000] PID hash table entries: 128 (order: -3, 512 bytes)
    [    0.000000] Dentry cache hash table entries: 4096 (order: 2, 16384 bytes)
    [    0.000000] Inode-cache hash table entries: 2048 (order: 1, 8192 bytes)
    [    0.000000] Writing ErrCtl register=00000000
    [    0.000000] Readback ErrCtl register=00000000
    [    0.000000] Memory: 28004K/32768K available (2703K kernel code, 141K rwdata, 712K rodata, 276K init, 193K bss, 4764K reserved, 0K cma-reserved)
    [    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
    [    0.000000] NR_IRQS:51
    [    0.000000] Clocks: CPU:550.000MHz, DDR:400.000MHz, AHB:200.000MHz, Ref:25.000MHz
    [    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6950037990 ns
    [    0.000010] sched_clock: 32 bits at 275MHz, resolution 3ns, wraps every 7809031678ns
    [    0.008229] Calibrating delay loop... 366.18 BogoMIPS (lpj=1830912)
    [    0.071059] pid_max: default: 32768 minimum: 301
    [    0.076072] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
    [    0.083053] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
    [    0.093501] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
    [    0.104767] NET: Registered protocol family 16
    [    0.111051] MIPS: machine is TP-LINK TL-MR22U v1
    [    0.348014] clocksource: Switched to clocksource MIPS
    [    0.354841] NET: Registered protocol family 2
    [    0.360435] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
    [    0.367804] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
    [    0.374575] TCP: Hash tables configured (established 1024 bind 1024)
    [    0.381409] UDP hash table entries: 256 (order: 0, 4096 bytes)
    [    0.387584] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
    [    0.394550] NET: Registered protocol family 1
    [    0.399256] PCI: CLS 0 bytes, default 32
    [    0.400369] futex hash table entries: 256 (order: -1, 3072 bytes)
    [    0.424855] squashfs: version 4.0 (2009/01/31) Phillip Lougher
    [    0.431087] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
    [    0.444312] io scheduler noop registered
    [    0.448532] io scheduler deadline registered (default)
    [    0.454198] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
    [    0.481595] serial8250.0: ttyS0 at MMIO 0x18020000 (irq = 11, base_baud = 1562500) is a 16550A
    [    0.494091] m25p80 spi0.0: found s25fl064k, expected m25p80
    [    0.500053] m25p80 spi0.0: s25fl064k (8192 Kbytes)
    [    0.506347] 5 tp-link partitions found on MTD device spi0.0
    [    0.512282] Creating 5 MTD partitions on "spi0.0":
    [    0.517336] 0x000000000000-0x000000020000 : "u-boot"
    [    0.524265] 0x000000020000-0x00000014d484 : "kernel"
    [    0.531408] 0x00000014d484-0x0000007f0000 : "rootfs"
    [    0.538494] mtd: device 2 (rootfs) set to be root filesystem
    [    0.544533] 1 squashfs-split partitions found on MTD device rootfs
    [    0.551089] 0x000000560000-0x0000007f0000 : "rootfs_data"
    [    0.558648] 0x0000007f0000-0x000000800000 : "art"
    [    0.565402] 0x000000020000-0x0000007f0000 : "firmware"
    [    0.593981] libphy: ag71xx_mdio: probed
    [    1.190979] ag71xx ag71xx.0: connected to PHY at ag71xx-mdio.1:04 [uid=004dd042, driver=Generic PHY]
    [    1.201443] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode:MII
    [    1.209037] NET: Registered protocol family 17
    [    1.213844] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
    [    1.227324] 8021q: 802.1Q VLAN Support v1.8
    [    1.232359] bootconsole [early0] disabled
    [    1.239343] Warning: unable to open an initial console.
    [    1.245514] VFS: Mounted root (squashfs filesystem) readonly on device 31:2.
    [    1.247405] Freeing unused kernel memory: 276K (803db000 - 80420000)
    [    2.392654] init: Console is alive
    [    2.392928] init: - watchdog -
    [    3.599976] usbcore: registered new interface driver usbfs
    [    3.600092] usbcore: registered new interface driver hub
    [    3.600207] usbcore: registered new device driver usb
    [    3.606778] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
    [    3.608586] ehci-platform: EHCI generic platform driver
    [    3.608704] ehci-platform ehci-platform: EHCI Host Controller
    [    3.608745] ehci-platform ehci-platform: new USB bus registered, assigned bus number 1
    [    3.610912] ehci-platform ehci-platform: irq 3, io mem 0x1b000000
    [    3.628037] ehci-platform ehci-platform: USB 2.0 started, EHCI 1.00
    [    3.629079] hub 1-0:1.0: USB hub found
    [    3.629271] hub 1-0:1.0: 1 port detected
    [    3.632812] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
    [    3.634592] ohci-platform: OHCI generic platform driver
    [    3.643355] init: - preinit -
    [    4.262142] random: procd urandom read with 7 bits of entropy available
    [    6.587281] jffs2: notice: (686) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
    [    6.589386] mount_root: overlay filesystem has not been fully initialized yet
    [    6.592561] mount_root: switching to jffs2 overlay
    [    6.635384] procd: - early -
    [    6.635520] procd: - watchdog -
    [    7.388223] procd: failed to set stdio
    [    7.388333] procd: - ubus -
    [    7.547654] procd: - init -
    [    8.350301] Loading modules backported from Linux version wt-2016-05-12-0-g7a54796
    [    8.350326] Backport generated by backports.git backports-20160216-0-ge3c56e4
    [    8.359044] nf_conntrack version 0.5.0 (441 buckets, 1764 max)
    [    8.401491] xt_time: kernel timezone is -0000
    [    8.423678] ip_tables: (C) 2000-2006 Netfilter Core Team
    [    8.474046] PPP generic driver version 2.4.2
    [    8.477121] NET: Registered protocol family 24
    [    8.532183] usbcore: registered new interface driver rt2800usb
    [    8.545720] usbcore: registered new interface driver ath9k_htc
    [    8.563104] ath: EEPROM regdomain: 0x0
    [    8.563130] ath: EEPROM indicates default country code should be used
    [    8.563140] ath: doing EEPROM country->regdmn map search
    [    8.563164] ath: country maps to regdmn code: 0x3a
    [    8.563176] ath: Country alpha2 being used: US
    [    8.563186] ath: Regpair used: 0x3a
    [    8.574841] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
    [    8.578636] ieee80211 phy0: Atheros AR9531 Rev:1 mem=0xb8100000, irq=47
    [   19.911668] device eth0 entered promiscuous mode
    [   20.431668] eth0: link up (100Mbps/Full duplex)
    [   20.431747] br-lan: port 1(eth0) entered forwarding state
    [   20.431821] br-lan: port 1(eth0) entered forwarding state
    [   22.432983] br-lan: port 1(eth0) entered forwarding state
    [   22.502309] device wlan0 entered promiscuous mode
    [   22.539366] br-lan: port 2(wlan0) entered forwarding state
    [   22.539457] br-lan: port 2(wlan0) entered forwarding state
    [   24.538032] br-lan: port 2(wlan0) entered forwarding state
    [   46.058013] ------------[ cut here ]------------
    [   46.058073] WARNING: CPU: 0 PID: 0 at net/sched/sch_generic.c:306 dev_watchdog+0x1dc/0x260()
    [   46.058088] NETDEV WATCHDOG: eth0 (ag71xx): transmit queue 0 timed out
    [   46.058098] Modules linked in: ath9k ath9k_htc ath9k_common rt2800usb rt2800lib pppoe ppp_async iptable_nat ath9k_hw ath rt2x00usb rt2x00lib pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv4 mac80211 iptable_raw iptable_mangle iptable_filter ipt_REJECT ipt_MASQUERADE ip_tables cfg80211 xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_CT x_tables slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_log_common nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack crc_itu_t crc_ccitt compat ledtrig_usbdev ohci_platform ohci_hcd ehci_platform ehci_hcd gpio_button_hotplug usbcore nls_base usb_common
    [   46.058317] CPU: 0 PID: 0 Comm: swapper Not tainted 4.4.14 #17
    [   46.058329] Stack : 8037bda4 00000000 00000001 803d0000 803be3f8 803be083 8035d4e8 00000000
    [   46.058329] 	  80423790 803bc7dc 00000200 00100000 00000100 800a61c4 80362b2c 803c0000
    [   46.058329] 	  00000003 803bc7dc 80360f38 803b9c2c 00000100 800a4190 00000006 00000000
    [   46.058329] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    [   46.058329] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    [   46.058329] 	  ...
    [   46.058454] Call Trace:
    [   46.058476] [<800713b4>] show_stack+0x50/0x84
    [   46.058500] [<80080fb8>] warn_slowpath_common+0xa0/0xd0
    [   46.058519] [<80081014>] warn_slowpath_fmt+0x2c/0x38
    [   46.058536] [<8027fb68>] dev_watchdog+0x1dc/0x260
    [   46.058566] [<800af2d8>] call_timer_fn.isra.5+0x24/0x80
    [   46.058585] [<800af554>] run_timer_softirq+0x1ac/0x1f4
    [   46.058608] [<80083414>] __do_softirq+0x164/0x290
    [   46.058644] [<8006a008>] plat_irq_dispatch+0xbc/0xf4
    [   46.058654] 
    [   46.058666] ---[ end trace 8d90bdf73e155ec0 ]---
    [   46.058678] eth0: tx timeout
    [   53.679643] random: nonblocking pool is initialized
    [   96.058019] eth0: tx timeout
    [  127.470103] eth0: link down
    [  127.470216] br-lan: port 1(eth0) entered disabled state
    [  128.471554] eth0: link up (100Mbps/Full duplex)
    [  128.471634] br-lan: port 1(eth0) entered forwarding state
    [  128.471712] br-lan: port 1(eth0) entered forwarding state
    [  130.468025] br-lan: port 1(eth0) entered forwarding state
    [  162.470103] eth0: link down
    [  162.470218] br-lan: port 1(eth0) entered disabled state
    [  163.471547] eth0: link up (100Mbps/Full duplex)
    [  163.471628] br-lan: port 1(eth0) entered forwarding state
    [  163.471705] br-lan: port 1(eth0) entered forwarding state
    [  165.468026] br-lan: port 1(eth0) entered forwarding state
    [  194.058026] eth0: tx timeout
    [  209.058045] eth0: tx timeout

**Comment by psyborg55** [comment]
replacing tplink u-boot with self-compiled one from pepe2k sources makes eth working fine again.
