### ISSUE TITLE
Samba package update request

### ISSUE THREAD

**Issue by amanzone** [openwrt/openwrt#350]
Hello and thanks for the outstanding job you're doing.

As far as I can understand the samba-server package does not allow the use of the tdbsam backend (I imagine only the smbpasswd backend is allowed).
Do you think it would be possible to include support for the tdbsam backend?

Thank you in advance your your reply.

Regards,
A.

**Comment by ZacWolf** [comment]
Windows 10 requires Samba 4.4 minimum (SMB3) for browsing of Samba Server shares via the File Explorer. Is there any roadmap to upgrade Samba to the latest 4.6.4 version, as prior versions of Samba Server means Windows 10 has to use SMB1, which makes it susceptible to the 

THANKS!
