### ISSUE TITLE
Newbie question regarding profiles

### ISSUE THREAD

**Issue by LeosSire** [openwrt/openwrt#365]
I have recently compiled OpenWRT a fresh using system build. I set the target etc... for my Nexx WT3020 for ramips MT7620n and I'm fine with all that. Using 'make menuconfig' I selected all the required packages. 

But when I compile there are only a few vmlimux compiled files. Nothing matching the WT3020 8M profile name I know I need. 

From the mt7620 precompiled list of images (link below) there are a number giving the options for which specific router I have. (I have downloaded this and installed and it works fine!)
[https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/ ]

I have downloaded and installed the patch to include the correct profile from Changeset 42983. 
(All packages are up to date, before anyone asks)

I am just struggling to get it to compile the profile I need. I can't see where I specify the profile of WT3020 in 'make menuconfig'.

I ran a 'make' after downloading the 'config.diff' from the '/mt7620' online directory and running 'make defconfig' but this caused an issue as what isn't directly required for the firmware is set to compile but not include setting, aka "<M>". And this results in trying to compile unsupported unwanted code and it crashes (I have a previous post on this)

I have been searching the wiki and google in general to no avail. Its been a month now so I'm asking the wider community.

Apologies in advance if this is not the correct location to ask this question, but i'm starting to go a little crazy. 

Thank you

**Comment by ProtoFoo** [comment]
> But when I compile there are only a few vmlimux compiled files. Nothing matching the WT3020 8M profile name I know I need.

Did you turn [debug logging](https://wiki.openwrt.org/doc/howto/build#spotting_build_errors) on?
> make V=s 2>&1 | tee build.log | grep -i error

Did you check the [build troubleshooting section](https://wiki.openwrt.org/doc/howto/build#factorybin_and_-sysupgradebin_images_for_my_device_do_not_get_generated) in the wiki? It seems you may have selected too much stuff to be included in your image. The wiki says this:
> If running make does not yield images for one (or even all) of the boards linked to the device profile that you have selected, than you probably have selected/enabled too much stuff, resulting in an image that would be too big to be flashed onto your device. Please note that the OpenWRT buildroot will currently (september 2015) not display any warning or error message if an image cannot be created because it would be too big for its designated target board.
