### ISSUE TITLE
When the router is in monitor mode ,After a certain time ,have not received the data phy interface

### ISSUE THREAD

**Issue by zimiao815** [openwrt/openwrt#381]
my openwrt :CC15.05----3.18.21 and 3.18.29
Compex wpj531 QCA9531  and  Don't know the manufacturer QCA9344
                           
#iw phy phy0 interface add  mon0 type monitor
#ifconfig mon0 up
#tcpdump -i mon0

wifi packets can be received,After a certain time ,have not received the data ?  Until  need to reboot
How can I solve?
Thank you very much!

**Comment by zimiao815** [comment]
up up

**Comment by zimiao815** [comment]
I found the wireless receiving interrupt stopped
cat /proc/interrupts----interrupt of ath9k is no changed 
Who knows why? 
Thank you very much

**Comment by nbd168** [comment]
This is fixed in current LEDE versions, OpenWrt needs a backport of the mac80211 package.

**Comment by zimiao815** [comment]
Can you tell me the website or url  of the patch  ,I didn't find it
Thank you very much

**Comment by zimiao815** [comment]
@nbd168 
[https://downloads.lede-project.org/releases/17.01.1/targets/ar71xx/generic/wpj531-16M-squashfs-sysupgrade.bin](url)  of Tue Apr 18 04:38:32 2017
I download and test the firmware，but i get same results： RX bytes is equit。

**_root@LEDE:/sys/kernel/debug/ieee80211/phy0/ath9k# ifconfig mon0**
mon0      Link encap:UNSPEC  HWaddr 04-F0-21-1A-11-B8-77-75-00-00-00-00-00-00-00-00
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4695 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:**1758160** (1.6 MiB)  TX bytes:0 (0.0 B)

**root@LEDE:/sys/kernel/debug/ieee80211/phy0/ath9k# ifconfig mon0**
mon0      Link encap:UNSPEC  HWaddr 04-F0-21-1A-11-B8-77-9A-00-00-00-00-00-00-00-00
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4695 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:**1758160** (1.6 MiB)  TX bytes:0 (0.0 B)_
