### ISSUE TITLE
Packages and Packages.gz have different content

### ISSUE THREAD

**Issue by jwfang** [openwrt/openwrt#440]
same as:
https://bugs.lede-project.org/index.php?do=details&task_id=675

eg:
https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/packages/base/Packages
https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/packages/base/Packages.gz

**Comment by m4ci3k2** [comment]
Same as in LEDE, your ISP/system is at fault, the files are the same.

```
$ wget -q https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/packages/base/Packages
$ wget -q -O- https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/packages/base/Packages.gz | gunzip > Packages.fromgz
$ diff -u Packages Packages.fromgz
$ echo $?
0
```
