### ISSUE TITLE
ImageBuilder + ChaosCalmer branch + logd package separation = failure

### ISSUE THREAD

**Issue by ghost** [openwrt/openwrt#441]
Hi,
I am trying to get ImageBuilder up and running from github openwrt chaos_calmer git branch and commit 8a170b96 (CC: ubox: turn logd into a separate package) cause me troubles.

My use case is pre-configure firmware for TL-WR740N with a working network config, for individual "customers" with a web form that call ImageBuilder under the hood. 15.05.1 release is very great but was released before TP-Link's v5.1 and v6 ha(za)rdware revisions and no more <=v5.0 are shipped nowadays.

I manage to start from source (9a1fd3e), make menuconfig, select "Build the OpenWRT Image Builder", deselect "Include package repositories", make the whole thing (11Gig stuff), tar xf ImageBuilder*, put my custom extra_files, go for

> make PROFILE=TLWR740 PACKAGES="$PACKAGES" FILES="extra_files/"

and the build fail with 

> opkg_install_cmd: Cannot install package logd

$PACKAGES is a variable in my calling script for additional stuff like luci and *-fr things but not "logd". logd is coming from include/target.mk:15 DEFAULT_PACKAGES variable.

Undoing the one-line change in include/target.mk from 8a170b96 allows me to build firmware. I don't really know if they will be usable right now. (if you have warns here, let me know like... the recent kernel change could hurt ?).

Warm applauses for great work you've done,
Ludovic

**Comment by lpouzenc** [comment]
Please find the whole output of the quoted make command here : [ImageBuilder-make-log.txt](https://github.com/openwrt/openwrt/files/891007/ImageBuilder-make-log.txt)
