### ISSUE TITLE
Ubiquiti EdgeRouter X

### ISSUE THREAD

**Issue by adrienb4** [openwrt/openwrt#46]
Hi

I woul'd like to say, if it's possible to port Ubiquiti Edge Router X to OpenWRT 15.05 ?
Or when you plan to release the new version of OpenWRT ?

Thank

**Comment by arevindh** [comment]
+1

**Comment by adrienb4** [comment]
I come back to you for this issue.
I can't use dev version for in my production network.
Does anybody port the ubiquiti EdgeRouter to OpenRT ?

Thank

Adrien

**Comment by alex-eri** [comment]
+1
I will try on er-lite. Maybe portable to er-x.
