### ISSUE TITLE
Problem with signal strength in TP-LINK TL-WDR3600

### ISSUE THREAD

**Issue by Andre11s** [openwrt/openwrt#461]
Hi!

I have a problem with my TP-LINK TL-WDR3600 devices. They have openwrt firmware and the problem is that the command ''iw dev wlan0 station dump'' the values given by the ''avg signal'' are higher than 0 dB.
It also occurs with the command ''iw dev wlan0 link''.

I working with damaged routers, but I think the problem is in the AP firmware

Is it possible that this is a firmware bug? Any ideas? 
I found a similar ticket here: https://dev.openwrt.org/ticket/20343

Here are more details of my internal data device.

Thank's! 

----

Linux version 3.10.49 (bb@builder1) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r42625) )

----

system type             : Atheros AR9344 rev 2
machine                 : TP-LINK TL-WDR3600/4300/4310
processor               : 0
cpu model               : MIPS 74Kc V4.12
BogoMIPS                : 278.93
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0600, 0x0630, 0x0ba8]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp dsp2
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by fortecs16** [comment]
Anybody could see something of this? 

Thank you! 👍
