### ISSUE TITLE
Where to find obfsproxy package?

### ISSUE THREAD

**Issue by targetnull** [openwrt/openwrt#48]
Hi,

I'm trying to run openvpn+obfsproxy on openwrt 15.05, but the `obfsproxy` package is nowhere to be found. I have run `opkg update`, but `opkg list|grep obfsproxy` shows nothing. It seems that the package is removed in the latest version?

I find an available package in [14.04-oldpackage](https://downloads.openwrt.org/barrier_breaker/14.07/x86/generic/packages/oldpackages/), and it worked, but the client couldn't connect(the TCP connection was always reset). I'm not sure whether it is because of my configuration or the package(although I doubt my configuration), so I want to test it with the latest package to make sure that the package is OK. Where can I find the latest package?

I'm using it on x86-generic as a server, the client is a PC running windows xp, and the openvpn is working OK currently, so the only problem is setting up obfsproxy.

Thanks.
Tgn

**Comment by KanjiMonster** [comment]
There is no latest package, it was unmaintained and for 15.05 oldpackages was not built again (there were no changes anyway). As you can see, it didn't work properly, and it would require someone to take over maintainership first to take care of it and fix issues before it can appear again.
