### ISSUE TITLE
Massive slowdown when using luci with HTTPS

### ISSUE THREAD

**Issue by Pietia10** [openwrt/openwrt#482]
Hi,
When you install luci without encryption support with
opkg install luci
it's fast however when you install with encryption support with
opkg install luci-ssl
it's damn slow CPU 100 % and interface laggy as hell.
Browser:latest chrome.

Is there any workaround besides disabling ssl in luci?

**Comment by gileri** [comment]
Crypto is hard, especially on embedded CPUs without hardware crypto functions. It seem normal that HTTPS is slower.
