### ISSUE TITLE
ath9k wds mode station break off 

### ISSUE THREAD

**Issue by ycsunjane** [openwrt/openwrt#488]
wds ap: 

        config wifi-device 'radio0'
                option type 'mac80211'
                option hwmode '11g'
                option path 'platform/ar933x_wmac'
                option distance '3000'
                option txpower '18'
                option country '00'
                option channel '1'
                option htmode 'HT40'

        config wifi-iface
                option device 'radio0'
                option network 'lan'
                option mode 'ap'
                option encryption 'psk2'
                option key '12345600'
               option max_inactivity '20'
                option wds '1'
                option ssid 'LK-M2-Jianxi'

wds station: 

        config wifi-device 'radio0'
                option type 'mac80211'
                option channel '1'
                option hwmode '11g'
                option path 'platform/ar933x_wmac'
                option htmode 'HT20'
                option distance '3000'
                option txpower '19'
               option country '00'

        config wifi-iface
                option device 'radio0'
                option network 'lan'
                option encryption 'psk2'
                option key '12345600'
                option max_inactivity '20'
                option wds '1'
                option mode 'sta'
                option ssid 'LK-M2-Jianxi'

 When the station break off, ping can not reach ap. wifi still connect. kernel have no error info. iwinfo signal still change.

ap with the other station still alive.

Use wpa_cli scan command, will awake station, and ping alive.
wifi command also work.

/proc/interrupts ath9k still alive.

**Comment by psyborg55** [comment]
does it happen if both points match htmode?
