### ISSUE TITLE
OpenWRT - Compiling from source Fail - barrier_breaker. 

### ISSUE THREAD

**Issue by ashish-bhangale** [openwrt/openwrt#506]
Hi,

I was trying to compile OpenWRT barrier_breaker from source and receiving the following error:

> include/toplevel.mk:160: recipe for target 'world' failed make: *** [world] Error 1

The util-linux and linux package download url is dead fixed the issue by adding these following packages into dl directory. 

https://www.kernel.org/pub/linux/utils/util-linux/v2.24/util-linux-2.24.1.tar.xz
https://github.com/jslink/openwrt-trunk-dl/raw/master/linux-3.10.49.tar.xz

Please fix the broken url link in the source code.

Thanks!!

**Comment by wigyori** [comment]
Hi,

Please note that the BB branch is closed for good. For historical reasons, thanks for providing the URLs here.

Regards,
-w-
