### ISSUE TITLE
hotplug: scripts in /etc/hotplug.d/block are NOT called when USB storage is plugged in 

### ISSUE THREAD

**Issue by forever8938** [openwrt/openwrt#5065]
I believe I've installed required packages because I can already mount USB storage using these commands:
```
  block detect | uci import fstab
  uci set fstab.@mount[-1].enabled='1'
  uci set fstab.@mount[-1].target='/mnt/sda1'
  uci commit fstab
  service fstab boot
```
Now I want to run these commands whenever USB storage in plugged in. So I created /etc/hotplug.d/block/99-my-action to do that.
```
root@OpenWrt:/etc/hotplug.d/block# ls
00-media-change  10-mount         99-my-action
root@OpenWrt:/etc/hotplug.d/block# cat 99-my-action 
logger -t hotplug "/etc/hotplug.d/block/99-my-action"
root@OpenWrt:/etc/hotplug.d/block# 
```

You can see aside from my script, there are already some scripts in the folder, but NONE of them is called when USB storage is plugged in. I confirmed that by printing log in each of the scripts.
```
root@OpenWrt:/etc/hotplug.d/block# logread  | grep "my-action"
root@OpenWrt:/etc/hotplug.d/block# 
```

**Additional information**
openwrt version: 19.07.7 stable and 21.02.1 stable
device: newifi-d2
filesystem and overlay: I believe this is not related because /etc/hotplug.d/iface DOES get called when WAN is up or down.

**Comment by wulfy23** [comment]
was there an issue template you could use?

you have not;
+ stated your openwrt version
+ stated your device / filesystem type or whether an overlay is in use

were you able to label your bug report?

**Comment by forever8938** [comment]
@wulfy23 Sorry about that. I've providec additional information, please confirm.

**Comment by wulfy23** [comment]
much better... thankyou for supplying those details...

all I can add to this is I have a block hotplug script also on master/ext4-nooverlay and it runs perfectly ok

I will have a chance to retest it when 21.02.2 comes out... if there are issues, I will report them here

**Comment by forever8938** [comment]
I tested again and it works on both versions mentioned above. Could be my mistake. So let me close the issue for now. Sorry for inconvenience.

BTW, /etc/hotplug.d/block scripts are also called during boot time. In that case, logs are not seen, probably because it happens even before logger service is started. I confirmed that by printing logs to a file.
