### ISSUE TITLE
How to remove "from" IPV6 default route?

### ISSUE THREAD

**Issue by qiuzi** [openwrt/openwrt#5092]
@nbd168 
I use the bridge redirection route to surf the Internet. There is no problem with ipv4 routing, but ipv6 has "from" parameters that affect ipv6 routing and forwarding. Where should I modify to remove the "from" effect?

`default from xx:xx:xx::3 via fe80::1 dev br-wan proto static metric 640 pref medium`

**Comment by jow-** [comment]
Netifd is responsible for installing source based IPv6 routes and rules. The `from` ensures that the correct egress is used based on the source prefix on multi homed systems.
