### ISSUE TITLE
Missing OVA file in VM setup guide

### ISSUE THREAD

**Issue by goldseven** [openwrt/openwrt#510]
On the [OpenWrt on VMware HowTo](https://wiki.openwrt.org/doc/howto/vmware)

> you can download an OVA image from the following location: https://dl.dropboxusercontent.com/u/7976972/openwrt15cc.ova

But I get a 404 on the URL when trying to download it. Could the link be updated?

**Comment by BartoszKaszewczuk** [comment]
Has there been any progress with this? OVA file still 404s.

**Comment by qq8554650** [comment]
google openwrt15cc.ova
http://tyeken8.com/openwrt15cc.ova
if you can't download,please contact 8554650@qq.com
