### ISSUE TITLE
FS#133 - Netgear r8000 cannot use 802.1x encryption

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5206]
*github-import:*

Github issue #305 reported by https://github.com/Halry

My android phone can't connect to it.(tested on nexus 6p and samsung s7 edge)
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 IEEE 802.1X: Sending EAP Packet (identifier 247)
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 WPA: sending 1/4 msg of 4-Way Handshake
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 WPA: received EAPOL-Key frame (2/4 Pairwise)
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 WPA: sending 3/4 msg of 4-Way Handshake
Sun Aug 28 16:28:46 2016 daemon.info hostapd: wlan2: STA 94:fe:22:11:22:33 IEEE 802.11: disassociated
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 WPA: event 2 notification
Sun Aug 28 16:29:00 2016 daemon.info hostapd: wlan1: STA 94:fe:22:11:22:33 IEEE 802.11: associated
Sun Aug 28 16:29:00 2016 daemon.info hostapd: wlan1: STA 94:fe:22:11:22:33 IEEE 802.11: disassociated
Sun Aug 28 16:29:11 2016 daemon.info hostapd: wlan1: STA 94:fe:22:11:22:33 IEEE 802.11: associated
Sun Aug 28 16:29:11 2016 daemon.info hostapd: wlan1: STA 94:fe:22:11:22:33 IEEE 802.11: disassociated

However,Windows can connect to it.

Here are some my nexus 6p's dmesg:
CFG80211-ERROR wl_cfg80211_disconnect:Reason 17

**Comment by aparcar** [comment]
This issue is an import of an import, I'd close it for now. If it affects you still please comment
