### ISSUE TITLE
FS#97 - dnsmasq doesn't receive updated dns servers when running inside ujail

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5221]
*dangowrt:*

Bind-mounting /tmp/resolv.conf.auto apparently doesn't forward inotify events arriving from the kernel when resolv.conf.auto was changed (e.g. upstream DNS servers were received by a DHCP client or pppd). Restarting dnsmasq or running it without ujail solves the issue.

**Comment by dave14305** [comment]
Fixed by cd48d8d3420dd4df03daaa548227ceb487ba7104
