### ISSUE TITLE
i suggest that change c imp to glibc in Raspberry Devices(2~3b

### ISSUE THREAD

**Issue by Student414** [openwrt/openwrt#527]

**Comment by 805447391** [comment]
because most softwares are base on glibc, like jdk and node prebuild version, and Raspberry has so many memory and cpu mips than normal device like mt7620 serials. building with glibc isn't a bad thing, right ?

**Comment by Student414** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
