### ISSUE TITLE
FS#222 - providing pre-built images for extroot for devices with 4MiB of storage

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5275]
*bobafetthotmail:*

Currently, the only way to be able to make extroot (use an external drive as overlay) for 4MiB devices is to build an image with the Image Builder as they can't fit the packages needed in the jffs.

For most linux users this isn't a major issue as the Image Builder runs on Linux and with a couple commands you build all, but it's still time-consuming.

For everyone else this is an issue, as they need to get a linux system, learn how to use the Image Builder, and so on.

I'm asking if it is possible to make pre-built images with the right packages to allow extroot on 4 MiB devices.

The packages I thing we need in these pre-built images are all is needed by the device to be able to format and check its own drive, because again most users don't have access to a linux system to format a drive with ext4 or whatever.

It seems e2fsprogs is too big to fit with the other packages required, currently only f2fs filesystem tools are split and can be used in 4MiB devices for extroot.

These are the packages that currently should allow building an extrootable image that fits on 4MiB storage:

blkid block-mount kmod-fs-f2fs kmod-usb-storage kmod-usb-uhci kmod-usb-ohci mkf2fs f2fsck

(of course no luci is included).

**Comment by jow-** [comment]
Nowadays there's [ASU](https://sysupgrade.openwrt.org/) which can be used to obtain customized images.
