### ISSUE TITLE
OpenWrt-ImageBuilder-ramips-rt305x.Linux-x86_64 is trying to rebuild kernel

### ISSUE THREAD

**Issue by abhijit-mahajani-imgtec** [openwrt/openwrt#53]
I have downloaded https://downloads.openwrt.org/snapshots/trunk/ramips/rt305x/OpenWrt-SDK-ramips-rt305x_gcc-5.3.0_musl-1.1.14.Linux-x86_64.tar.bz2
and after extraction, tried to build using 
`make image PROFILE=Default`

But getting following error

cp /home/abhijit/work/imagebuilder-upstream/OpenWrt-ImageBuilder-ramips-rt305x.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/linux-ramips_rt305x/vmlinux /home/abhijit/work/imagebuilder-upstream/OpenWrt-ImageBuilder-ramips-rt305x.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/linux-ramips_rt305x/vmlinux-3g-6200n
mipsel-openwrt-linux-musl-cpp -nostdinc -x assembler-with-cpp -I/home/abhijit/work/imagebuilder-upstream/OpenWrt-ImageBuilder-ramips-rt305x.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/linux-ramips_rt305x/linux-4.4.14/arch/mips/boot/dts -I/home/abhijit/work/imagebuilder-upstream/OpenWrt-ImageBuilder-ramips-rt305x.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/linux-ramips_rt305x/linux-4.4.14/arch/mips/boot/dts/include -undef -D__DTS__  -o /home/abhijit/work/imagebuilder-upstream/OpenWrt-ImageBuilder-ramips-rt305x.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/linux-ramips_rt305x/3G-6200N.dtb.tmp ../dts/3G-6200N.dts
bash: mipsel-openwrt-linux-musl-cpp: command not found
make[3]: **\* [install] Error 127
make[3]: Leaving directory `/home/abhijit/work/imagebuilder-upstream/OpenWrt-ImageBuilder-ramips-rt305x.Linux-x86_64/target/linux/ramips/image'
make[2]: *** [build_image] Error 2
make[2]: Leaving directory`/home/abhijit/work/imagebuilder-upstream/OpenWrt-ImageBuilder-ramips-rt305x.Linux-x86_64'
make[1]: **\* [_call_image] Error 2
make[1]: Leaving directory `/home/abhijit/work/imagebuilder-upstream/OpenWrt-ImageBuilder-ramips-rt305x.Linux-x86_64'
make: **\* [image] Error 2

**Comment by imKota** [comment]
+
