### ISSUE TITLE
FS#331 - mac80211 / warning / ieee80211_ibss_leave / r2449

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5368]
*bittorf:*

spotted on TP-Link 4900 v1 with LEDE r2449 (selfcompiled):

<code>
[ 2860.974569] ------------[ cut here ]------------
[ 2860.979191] WARNING: at compat-wireless-2016-10-08/net/mac80211/ibss.c:1082
[ 2860.986142] Modules linked in: ath9k ath9k_common iptable_nat ath9k_hw ath snd_usb_audio nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 mac80211 ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_id xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_NETMAP xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda snd_usbmidi_lib nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack macvlan iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables compat em_nbyte sch_dsmark sch_pie sch_codel sch_gred sch_htb em_cmp cls_basic act_ipt sch_red sch_prio em_meta act_police em_text sch_tbf sch_sfq sch_fq act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_hfsc sch_ingress ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6table_filter ip6_tables x_tables ipip tunnel4 ip_tunnel tun snd_compress snd_pcm_oss snd_mixer_oss snd_pcm snd_timer snd_rawmidi snd_seq_device snd_hwdep snd soundcore nls_utf8 zram lz4_decompress lz4_compress lzo_compress lzo_decompress zsmalloc usb_storage gpio_keys leds_gpio ehci_fsl ehci_platform ehci_hcd scsi_mod fsl_mph_dr_of mbcache button_hotplug input_core usbcore nls_base usb_common crc16 crc32c_generic crypto_hash [last unloaded: sd_mod]
[ 2861.124825] CPU: 0 PID: 8624 Comm: kworker/u2:0 Not tainted 4.4.36 #0
[ 2861.131337] Workqueue: phy1 ieee80211_ibss_leave [mac80211]
[ 2861.136903] task: c783b840 ti: c68a4000 task.ti: c68a4000
[ 2861.142292] NIP: c99ab128 LR: c99ab354 CTR: 00000000
[ 2861.147247] REGS: c68a5b10 TRAP: 0700   Not tainted  (4.4.36)
[ 2861.152982] MSR: 00029000 <CE,EE,ME>  CR: 28072422  XER: 20000000
[ 2861.159082]
[ 2861.159082] GPR00: c99ab004 c68a5bc0 c783b840 00000000 c68a5bf4 00000000 00000001 00000000
[ 2861.159082] GPR08: c724b114 00000001 c99f97f6 00000000 000000ff 00000000 c003c474 c790bfe0
[ 2861.159082] GPR16: c6f0f070 00000fff 00000fff c70b2138 c6ae5800 c6e30b40 00000000 00000087
[ 2861.159082] GPR24: 00000000 c68a5c68 c724b114 00000000 c6e30b40 c6e7a3d8 c6f25420 c6f0f070
[ 2861.188805] NIP [c99ab128] ieee80211_get_vht_mask_from_cap+0x1964/0x1c64 [mac80211]
[ 2861.196468] LR [c99ab354] ieee80211_get_vht_mask_from_cap+0x1b90/0x1c64 [mac80211]
[ 2861.204025] Call Trace:
[ 2861.206481] [c68a5bc0] [c99ab004] ieee80211_get_vht_mask_from_cap+0x1840/0x1c64 [mac80211] (unreliable)
[ 2861.215884] [c68a5c60] [c99ab414] ieee80211_get_vht_mask_from_cap+0x1c50/0x1c64 [mac80211]
[ 2861.224156] [c68a5d30] [c99ab9d0] ieee80211_ibss_rx_queued_mgmt+0x264/0x370 [mac80211]
[ 2861.232081] [c68a5e20] [c99acc44] ieee80211_ibss_leave+0x768/0x1770 [mac80211]
[ 2861.239307] [c68a5e80] [c00379f8] process_one_work+0x208/0x380
[ 2861.245135] [c68a5ea0] [c0037de0] worker_thread+0x270/0x48c
[ 2861.250704] [c68a5ef0] [c003c53c] kthread+0xc8/0xcc
[ 2861.255580] [c68a5f40] [c000cb3c] ret_from_kernel_thread+0x5c/0x64
[ 2861.261752] --- interrupt: 0 at   (null)
[ 2861.261752]     LR =   (null)
[ 2861.268618] Instruction dump:
[ 2861.271578] 38810034 387e0510 7f984800 419e024c 4bf410ed 2f830000 40be0030 3d40c9a0
[ 2861.279336] 394a97f6 3b600001 892a0003 69290001 <0f090000> 2f890000 41be01d0 39200001
[ 2861.287267] ---[ end trace a37b58c3292c2cbf ]---

</code>

**Comment by aparcar** [comment]
The release is is EOL, please comment if this affects you with currently supported releases.
