### ISSUE TITLE
FS#386 - Config option "list channels" doesn't work

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5419]
*D-Albers:*

Hi,

the option "list channels" is not working.

Patch which implements the function: https://patchwork.ozlabs.org/patch/536533/

LEDE version: SNAPSHOT r2790-08d73bf

Device: Archer C5

<code>config wifi-device 'radio0'
	option type 'mac80211'
	option hwmode '11a'
	option path 'pci0000:01/0000:01:00.0'
	option country 'DE'
	option htmode 'VHT80'
	option txpower '12'
	option channel 'auto'

config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'yyy'
	option encryption 'psk2+ccmp'
	option key 'xxx'
	option disabled '1'

config wifi-device 'radio1'
	option type 'mac80211'
	option hwmode '11g'
	option path 'platform/qca955x_wmac'
	option channel 'auto'
	option country 'DE'
	option txpower '20'
	option htmode 'HT40'
	list channels 13
        list channels 12

config wifi-iface 'default_radio1'
	option device 'radio1'
	option network 'lan'
	option mode 'ap'
	option encryption 'psk2+ccmp'
	option key 'xxx'
	option ssid 'yyy'</code>
 
Ends with a 2.4GHz wlan which is not
visible and iwinfo shows the following information:

Mode: Master  Channel: unknown (2.407 GHz)

<code>root@lede:~# iwinfo wlan1 freqlist
  2.412 GHz (Channel 1)
  2.417 GHz (Channel 2)
  2.422 GHz (Channel 3)
  2.427 GHz (Channel 4)
  2.432 GHz (Channel 5)
  2.437 GHz (Channel 6)
  2.442 GHz (Channel 7)
  2.447 GHz (Channel 8)
  2.452 GHz (Channel 9)
  2.457 GHz (Channel 10)
  2.462 GHz (Channel 11)
  2.467 GHz (Channel 12)
  2.472 GHz (Channel 13)</code>

A part of the syslog with a bunch of error messages is attached.

Fell free to ask, if something is missing.

**Comment by KanjiMonster** [comment]
Referenced patch applied in d293f33558e3d0a08135c48c8d8bcd079e4fd69b (17.01+).
