### ISSUE TITLE
FS#514 - Any files copied to flash gone after reboot17.01.0-rc2 x86-geode-combined-squashfs.img

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5529]
*bluewavenet:*

PCEngines Alix with lede-17.01.0-rc2-r3131-42f3c1f-x86-geode-combined-squashfs.img

Boots fine. 

Any software installed or files copied to flash disappear after reboot.

However LAN ethernet IP address is (usually)remembered but did get reset on one occasion. 
But WiFi config of a USB dongle is always lost.

The board has a Lexar 16GB UDMA7 CF card. This config works fine with OpenWrt CC. 

Reflashing, changing the flash card etc makes no difference.

**Comment by aparcar** [comment]
This issue is for a EOL release, please comment if this bug still affects you in currently supported releases.
