### ISSUE TITLE
FS#1087 - LEDE snaphost: sunxi cortex-a7, BanaPi target: USB not powered

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5612]
*Menion:*

Hi all
With snapshot r5117-fbde9ac, at least on a bananapi (cortex-a7) the USB ports are down, apparently there is some problem with VBUS (maybe DT problem?)
Here the dmesg after boot

<code>
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.9.57 (buildbot@builds) (gcc version 5.5.0 (LEDE GCC 5.5.0 r5092-0d5c1d7) ) #0 SMP PREEMPT Wed Oct 18 21:26:15 2017
[    0.000000] CPU: ARMv7 Processor [410fc074] revision 4 (ARMv7), cr=30c5387d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt:Machine model: LeMaker Banana Pi
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 261738
[    0.000000] free_area_init_node: node 0, pgdat c0689140, node_mem_map ef7fa000
[    0.000000]   Normal zone: 1536 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 196608 pages, LIFO batch:31
[    0.000000]   HighMem zone: 65130 pages, LIFO batch:15
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: Using PSCI v0.1 Function IDs from DT
[    0.000000] percpu: Embedded 14 pages/cpu @ef7c2000 s25036 r8192 d24116 u57344
[    0.000000] pcpu-alloc: s25036 r8192 d24116 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 260202
[    0.000000] Kernel command line: console=ttyS0,115200 earlyprintk root=/dev/mmcblk0p2 rootwait
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 1030724K/1046952K available (4564K kernel code, 254K rwdata, 1384K rodata, 304K init, 282K bss, 16228K reserved, 0K cma-reserved, 260520K highmem)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0xf0800000 - 0xff800000   ( 240 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xf0000000   ( 768 MB)
[    0.000000]     pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
[    0.000000]     modules : 0xbf000000 - 0xbfe00000   (  14 MB)
[    0.000000]       .text : 0xc0008000 - 0xc047d4b0   (4566 kB)
[    0.000000]       .init : 0xc05fe000 - 0xc064a000   ( 304 kB)
[    0.000000]       .data : 0xc064a000 - 0xc0689a40   ( 255 kB)
[    0.000000]        .bss : 0xc068b000 - 0xc06d1874   ( 283 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000]  RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=2.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] arm_arch_timer: Architected cp15 timer(s) running at 24.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000007] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.000019] Switching to timer-based delay loop, resolution 41ns
[    0.000528] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.000769] clocksource: hstimer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 12741736309 ns
[    0.000939] Console: colour dummy device 80x30
[    0.000973] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=240000)
[    0.000988] pid_max: default: 32768 minimum: 301
[    0.001112] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001123] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001736] CPU: Testing write buffer coherency: ok
[    0.002074] /cpus/cpu@0 missing clock-frequency property
[    0.002095] /cpus/cpu@1 missing clock-frequency property
[    0.002108] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.002131] Setting up static identity map for 0x400082c0 - 0x40008318
[    0.170429] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.170531] Brought up 2 CPUs
[    0.170553] SMP: Total of 2 processors activated (96.00 BogoMIPS).
[    0.170561] CPU: All CPU(s) started in HYP mode.
[    0.170567] CPU: Virtualization extensions available.
[    0.181241] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 4
[    0.181967] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.181997] futex hash table entries: 512 (order: 3, 32768 bytes)
[    0.182161] pinctrl core: initialized pinctrl subsystem
[    0.183759] NET: Registered protocol family 16
[    0.184099] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.186420] No ATAGs?
[    0.252339] reg-fixed-voltage usb0-vbus: could not find pctldev for node /soc@01c00000/pinctrl@01c20800/usb0_vbus_pin@0, deferring probe
[    0.252404] reg-fixed-voltage usb1-vbus: could not find pctldev for node /soc@01c00000/pinctrl@01c20800/usb1_vbus_pin@0, deferring probe
[    0.252440] reg-fixed-voltage usb2-vbus: could not find pctldev for node /soc@01c00000/pinctrl@01c20800/usb2_vbus_pin@0, deferring probe
[    0.253608] reg-fixed-voltage gmac-3v3: could not find pctldev for node /soc@01c00000/pinctrl@01c20800/gmac_power_pin@0, deferring probe
[    0.254616] SCSI subsystem initialized
[    0.254990] libata version 3.00 loaded.
[    0.255707] usbcore: registered new interface driver usbfs
[    0.255854] usbcore: registered new interface driver hub
[    0.256010] usbcore: registered new device driver usb
[    0.256383] Linux video capture interface: v2.00
[    0.256631] pps_core: LinuxPPS API ver. 1 registered
[    0.256641] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.256729] PTP clock support registered
[    0.257496] Advanced Linux Sound Architecture Driver Initialized.
[    0.258937] clocksource: Switched to clocksource arch_sys_counter
[    0.260189] simple-framebuffer 7fe79000.framebuffer: framebuffer at 0x7fe79000, 0x178e00 bytes, mapped to 0xf0900000
[    0.260208] simple-framebuffer 7fe79000.framebuffer: format=x8r8g8b8, mode=656x536x32, linelength=2880
[    0.267397] Console: switching to colour frame buffer device 82x33
[    0.273147] simple-framebuffer 7fe79000.framebuffer: fb0: simplefb registered!
[    0.285894] NET: Registered protocol family 2
[    0.286811] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.286911] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.287040] TCP: Hash tables configured (established 8192 bind 8192)
[    0.287131] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.287195] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.287430] NET: Registered protocol family 1
[    0.287817] kvm [1]: 8-bit VMID
[    0.287830] kvm [1]: IDMAP page: 40009000
[    0.287838] kvm [1]: HYP VA range: c0000000:ffffffff
[    0.288171] kvm [1]: Hyp mode initialized successfully
[    0.288246] kvm [1]: vgic-v2@1c84000
[    0.288431] kvm [1]: vgic interrupt IRQ16
[    0.288462] kvm [1]: virtual timer IRQ20
[    0.290814] No memory allocated for crashlog
[    0.291097] workingset: timestamp_bits=30 max_order=18 bucket_order=0
[    0.301800] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.314490] bounce: pool size: 64 pages
[    0.314510] io scheduler noop registered
[    0.314518] io scheduler deadline registered
[    0.314823] io scheduler cfq registered (default)
[    0.315575] sun4i-usb-phy 1c13400.phy: could not find pctldev for node /soc@01c00000/pinctrl@01c20800/usb0_id_detect_pin@0, deferring probe
[    0.320516] sun7i-a20-pinctrl 1c20800.pinctrl: initialized sunXi PIO driver
[    0.422164] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.428293] console [ttyS0] disabled
[    0.448607] 1c28000.serial: ttyS0 at MMIO 0x1c28000 (irq = 45, base_baud = 1500000) is a U6_16550A
[    1.110648] console [ttyS0] enabled
[    1.138088] 1c28c00.serial: ttyS1 at MMIO 0x1c28c00 (irq = 46, base_baud = 1500000) is a U6_16550A
[    1.170870] 1c29c00.serial: ttyS2 at MMIO 0x1c29c00 (irq = 47, base_baud = 1500000) is a U6_16550A
[    1.229167] loop: module loaded
[    1.234708] libphy: Fixed MDIO Bus: probed
[    1.239475] sun7i-dwmac 1c50000.ethernet: PTP uses main clock
[    1.245231] sun7i-dwmac 1c50000.ethernet: no reset control found
[    1.252200] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.258730] ehci-platform: EHCI generic platform driver
[    1.264410] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    1.270651] ohci-platform: OHCI generic platform driver
[    1.276342] usbcore: registered new interface driver usb-storage
[    1.282746] mousedev: PS/2 mouse device common for all mice
[    1.289486] i2c /dev entries driver
[    1.295415] sunxi-wdt 1c20c90.watchdog: Watchdog enabled (timeout=16 sec, nowayout=0)
[    1.305385] sunxi-mmc 1c0f000.mmc: Got CD GPIO
[    1.389162] sunxi-mmc 1c0f000.mmc: base:0xf08db000 irq:28
[    1.395627] sun4i-ss 1c15000.crypto-engine: no reset control found
[    1.403543] sun4i-ss 1c15000.crypto-engine: Die ID 0
[    1.414955] NET: Registered protocol family 10
[    1.424080] NET: Registered protocol family 17
[    1.428624] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    1.441620] can: controller area network core (rev 20120528 abi 9)
[    1.448031] NET: Registered protocol family 29
[    1.452516] 8021q: 802.1Q VLAN Support v1.8
[    1.456824] Registering SWP/SWPB emulation handler
[    1.471934] sun7i-dwmac 1c50000.ethernet: PTP uses main clock
[    1.477695] sun7i-dwmac 1c50000.ethernet: no reset control found
[    1.491416] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.502100] mmc0: new high speed SDHC card at address b368
[    1.518287] mmcblk0: mmc0:b368       3.75 GiB
[    1.523991]  mmcblk0: p1 p2
[    1.599006] sun7i-dwmac 1c50000.ethernet: Ring mode enabled
[    1.604587] sun7i-dwmac 1c50000.ethernet: DMA HW capability register supported
[    1.611833] sun7i-dwmac 1c50000.ethernet: Normal descriptors
[    1.625337] libphy: stmmac: probed
[    1.628759] sun7i-dwmac 1c50000.ethernet (unnamed net_device) (uninitialized): PHY ID 001cc915 at 0 IRQ POLL (stmmac-0:00) active
[    1.640432] sun7i-dwmac 1c50000.ethernet (unnamed net_device) (uninitialized): PHY ID 001cc915 at 1 IRQ POLL (stmmac-0:01)
[    1.654246] hctosys: unable to open rtc device (rtc0)
[    1.660155] vcc3v0: disabling
[    1.663134] vcc5v0: disabling
[    1.666099] usb0-vbus: disabling
[    1.669415] usb1-vbus: disabling
[    1.672648] usb2-vbus: disabling
[    1.675876] ALSA device list:
[    1.678840]   No soundcards found.
[    1.684092] EXT4-fs (mmcblk0p2): couldn't mount as ext3 due to feature incompatibilities
[    1.693047] EXT4-fs (mmcblk0p2): couldn't mount as ext2 due to feature incompatibilities
[    1.705706] EXT4-fs (mmcblk0p2): mounted filesystem without journal. Opts: (null)
[    1.713316] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.720717] Freeing unused kernel memory: 304K
[    1.725156] This architecture does not have kernel memory protection.
[    1.808884] init: Console is alive
[    1.812591] init: - watchdog -
[    1.991859] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    2.109062] ahci-sunxi 1c18000.sata: controller can't do PMP, turning off CAP_PMP
[    2.116602] ahci-sunxi 1c18000.sata: forcing PORTS_IMPL to 0x1
[    2.122530] ahci-sunxi 1c18000.sata: AHCI 0001.0100 32 slots 1 ports 3 Gbps 0x1 impl platform mode
[    2.131547] ahci-sunxi 1c18000.sata: flags: ncq sntf pm led clo only pio slum part ccc
[    2.140601] scsi host0: ahci-sunxi
[    2.144486] ata1: SATA max UDMA/133 mmio [mem 0x01c18000-0x01c18fff] port 0x100 irq 33
[    2.480406] ata1: SATA link down (SStatus 0 SControl 300)
[    2.497140] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    2.514855] init: - preinit -
[    2.661278] random: jshn: uninitialized urandom read (4 bytes read)
[    2.692999] random: jshn: uninitialized urandom read (4 bytes read)
[    2.715326] random: jshn: uninitialized urandom read (4 bytes read)
[    2.738512] Generic PHY stmmac-0:00: attached PHY driver [Generic PHY] (mii_bus:phy_addr=stmmac-0:00, irq=-1)
[    2.850208] sun7i-dwmac 1c50000.ethernet eth0: RX IPC Checksum Offload disabled
[    2.857528] sun7i-dwmac 1c50000.ethernet eth0: No MAC Management Counters available
[    2.865213] sun7i-dwmac 1c50000.ethernet eth0: PTP not supported by HW
[    2.873355] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    5.973285] mount_root: mounting /dev/root
[    5.980967] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    6.013747] random: fast init done
[    6.249292] random: crng init done
[    6.398432] urandom-seed: Seeding with /etc/urandom.seed
[    6.439739] procd: - early -
[    6.442722] procd: - watchdog -
[    7.304303] procd: - watchdog -
[    7.307745] procd: - ubus -
[    7.362615] procd: - init -
[    7.508699] kmodloader: loading kernel modules from /etc/modules.d/*
[    7.518215] tun: Universal TUN/TAP device driver, 1.6
[    7.523343] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    7.536218] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    7.547403] nat46: module (version 683fbd2b765506332a1af141545652bf58f03166) loaded.
[    7.559700] ip6_tables: (C) 2000-2006 Netfilter Core Team
[    7.579497] nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
[    7.608815] sunxi-rtc 1c20d00.rtc: rtc core: registered rtc-sunxi as rtc0
[    7.615784] sunxi-rtc 1c20d00.rtc: RTC enabled
[    7.634093] Loading modules backported from Linux version wt-2017-10-06-0-ga7a22fbbd1f0
[    7.642374] Backport generated by backports.git v4.14-rc2-1-6-gedfb595c
[    7.651300] ip_tables: (C) 2000-2006 Netfilter Core Team
[    7.683086] xt_time: kernel timezone is -0000
[    7.721723] PPP generic driver version 2.4.2
[    7.727180] NET: Registered protocol family 24
[    7.738129] usbcore: registered new interface driver rtl8xxxu
[    7.766983] usbcore: registered new interface driver rt2800usb
[    7.777447] usbcore: registered new interface driver ath9k_htc
[    7.783580] kmodloader: done loading kernel modules from /etc/modules.d/*
[   10.097688] Generic PHY stmmac-0:00: attached PHY driver [Generic PHY] (mii_bus:phy_addr=stmmac-0:00, irq=-1)
[   10.110360] sun7i-dwmac 1c50000.ethernet eth0: RX IPC Checksum Offload disabled
[   10.117709] sun7i-dwmac 1c50000.ethernet eth0: No MAC Management Counters available
[   10.125620] sun7i-dwmac 1c50000.ethernet eth0: PTP not supported by HW
[   10.132954] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   10.148402] br-lan: port 1(eth0.2) entered blocking state
[   10.153968] br-lan: port 1(eth0.2) entered disabled state
[   10.160321] device eth0.2 entered promiscuous mode
[   10.165148] device eth0 entered promiscuous mode
[   10.174920] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   10.235364] IPv6: ADDRCONF(NETDEV_UP): eth0.3: link is not ready
[   10.498273] IPv6: ADDRCONF(NETDEV_UP): tayga-nat64: link is not ready
[   10.566999] IPv6: ADDRCONF(NETDEV_CHANGE): tayga-nat64: link becomes ready
[   14.329769] sun7i-dwmac 1c50000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
[   14.337986] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   14.345064] br-lan: port 1(eth0.2) entered blocking state
[   14.350507] br-lan: port 1(eth0.2) entered forwarding state
[   14.356467] IPv6: ADDRCONF(NETDEV_CHANGE): eth0.3: link becomes ready
[   14.363451] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready

</code>

**Comment by ynezz** [comment]
Should be fixed.
