### ISSUE TITLE
make defconfig fails as well as make prereq on Manjaro Gellivara/Arch linux

### ISSUE THREAD

**Issue by zor1984qq** [openwrt/openwrt#563]
make defconfig
Checking 'working-make'... ok.
Checking 'case-sensitive-fs'... ok.
Checking 'gcc'... ok.
Checking 'working-gcc'... ok.
Checking 'g++'... ok.
Checking 'working-g++'... ok.
Checking 'ncurses'... ok.
Checking 'zlib'... ok.
Checking 'libssl'... failed.
Checking 'perl-thread-queue'... ok.
Checking 'tar'... ok.
Checking 'find'... ok.
Checking 'bash'... ok.
Checking 'patch'... ok.
Checking 'diff'... ok.
Checking 'cp'... ok.
Checking 'seq'... ok.
Checking 'awk'... ok.
Checking 'grep'... ok.
Checking 'getopt'... ok.
Checking 'stat'... ok.
Checking 'md5sum'... ok.
Checking 'unzip'... ok.
Checking 'bzip2'... ok.
Checking 'wget'... ok.
Checking 'perl'... ok.
Checking 'python'... ok.
Checking 'svn'... ok.
Checking 'git'... ok.
Checking 'file'... ok.
Checking 'openssl'... ok.
Checking 'ldconfig-stub'... ok.

Build dependency: Please install the openssl library (with development headers)

Prerequisite check failed. Use FORCE=1 to override.
make: *** [/home/sergey/git/openwrt/include/toplevel.mk:153: staging_dir/host/.prereq-build] Ошибка 1
I have an openssl installed already and the fork of your project called LEDE https://git.lede-project.org/?p=source.git have no such problem so I arise these issue again here cause I have no account on your main development bug tracker.
pacman -Q openssl
openssl 1.1.0.f-2
pacman -Ss openssl
Assuming Arch wiki told to me there is no split packages live *-dev.* in Arch world.
core/openssl 1.1.0.f-2 [installed]
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
core/openssl-1.0 1.0.2.l-1 [installed]
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
Strangely I have both installed and I don't know if I am in need to remove 1.0 or doing anything else.

So I am stuck with these.
Feeds updated and installed.
Tried to update submodules from another topic, these command not giving any output.
git submodule --help 2>&1 | grep -- --recursive
       git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
       git submodule [--quiet] foreach [--recursive] <command>
       git submodule [--quiet] sync [--recursive] [--] [<path>...]
       status [--cached] [--recursive] [--] [<path>...]
           If --recursive is specified, this command will recurse into nested submodules, and show their status as well.
       update [--init] [--remote] [-N|--no-fetch] [--[no-]recommend-shallow] [-f|--force] [--checkout|--rebase|--merge] [--reference <repository>] [--depth <depth>] [--recursive] [--jobs <n>] [--]
           If --recursive is specified, this command will recurse into the registered submodules, and update any nested submodules within.
       foreach [--recursive] <command>
           submodule before evaluating the command. If --recursive is given, submodules are traversed recursively (i.e. the given shell command is evaluated in nested submodules as well). A non-zero
       sync [--recursive] [--] [<path>...]
           If --recursive is specified, this command will recurse into the registered submodules, and sync any nested submodules within.
       --recursive

**Comment by debianxfce** [comment]
Debian has clear libs and dev packages. Here is how to build openwrt with Debian testing:
https://www.youtube.com/watch?v=kYVUpZRp5S8
