### ISSUE TITLE
FS#666 - "Wireless is disabled or not associated" when channel mode "auto"

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5659]
*Maenne79:*

Supply the following if possible:
 - Device problem occurs on Banana Pi R1
 - Software versions: all

When I set the channel mode to "auto", then the message appears "Wireless is disabled or not associated" and the WLAN does'nt work.
I set the channel manually, then WLAN works fine.

The problem is already known with OpenWrt:
https://dev.openwrt.org/changeset/32630

**Comment by eurika404** [comment]
idk what happen with my modem 
![idk](https://user-images.githubusercontent.com/97332735/179056886-2b5c5075-9b42-4e98-858b-941a07ebf20b.jpg)
i will make some tutorial in my site [eurika](https://eurika.my.id) & [sikeplu](http://sikeplu.tech/)
