### ISSUE TITLE
FS#672 - Netgear WNR2000v3 - Looses always settings after power loss, nothig is been saved

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5664]
*lmtiaxkb:*

Device: Netgear WNR2000v3

Problem there since: 15.05.1. It was not there on 15.05 or previous releases.

Problem still there on 17.01 stable ( https://downloads.lede-project.org/releases/17.01.0/targets/ar71xx/generic/lede-17.01.0-r3205-59508e3-ar71xx-generic-wnr2000v3-squashfs-sysupgrade.bin )

The most simple way to make a example of this issue: Install 15.05.1 stable or 17.01 stable and open 192.168.1.1. It tells you that there is no password set. Go to settings, set a password. Open browser again. It asks you now for the password. Power off the device. Wait 2-3 seconds. Power it on. Password is now lost and device have again factory settings.

This makes lede on this device somehow useless. Would be great if someone could fix this problem.

Forum talk about this issue: https://forum.lede-project.org/t/netgear-wnr2000v3-not-saving-settings-after-reboot-with-rc2/1736/11

Bugreport about this issue on openwrt: https://dev.openwrt.org/ticket/22172

**Comment by aparcar** [comment]
This issue is for a EOL release, please comment if this bug still affects you in currently supported releases.
