### ISSUE TITLE
 Unable to compile uboot-envtools: unknown type name 'uint8_t'

### ISSUE THREAD

**Issue by michael-dev** [openwrt/openwrt#57]
make[3]: Entering directory '/opt/openwrt/stage2/trunk-devel/build_dir/target-powerpc_8540_glibc-2.22/u-boot-2015.10'
HOSTCC tools/env/fw_env.o
tools/env/fw_env.c:57:2: error: unknown type name 'uint8_t'
uint8_t mtd_type; /* type of the MTD device */
^

workaround:

cat ~/stage2/trunk-devel/package/boot/uboot-envtools/patches/400-fix-stdtype.patch
```
--- u-boot-2015.10/tools/env/fw_env.c.orig      2016-07-21 14:33:13.842378135 +0200
+++ u-boot-2015.10/tools/env/fw_env.c   2016-07-21 14:33:56.291010273 +0200
@@ -22,9 +22,9 @@
 #include <sys/ioctl.h>
 #include <sys/stat.h>
 #include <unistd.h>
+#include <stdint.h>
 
 #ifdef MTD_OLD
-# include <stdint.h>
 # include <linux/mtd/mtd.h>
 #else
 # define  __user       /* nothing */

```

**Comment by wigyori** [comment]
Should be fixed in d6c4db5.

Thanks,
-w-
