### ISSUE TITLE
FS#727 - USB not working on TL-WDR4900  v1.x

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5707]
*kokaracha:*

USB ports are empty but hub is deteched periodically.

dmesg | grep -i usb
[    0.029483] usbcore: registered new interface driver usbfs
[    0.029537] usbcore: registered new interface driver hub
[    0.029580] usbcore: registered new device driver usb
[    2.075954] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    2.104850] fsl-ehci fsl-ehci.0: new USB bus registered, assigned bus number 1
[    2.138024] fsl-ehci fsl-ehci.0: USB 2.0 started, EHCI 1.00
[    2.144048] hub 1-0:1.0: USB hub found
[    2.535450] usb 1-1: new high-speed USB device number 2 using fsl-ehci
[    2.728493] hub 1-1:1.0: USB hub found
[    3.511480] usb 1-1: USB disconnect, device number 2
[    3.814034] usb 1-1: new high-speed USB device number 3 using fsl-ehci
[    3.952117] hub 1-1:1.0: USB hub found
[    4.484403] usb 1-1: USB disconnect, device number 3
[    4.730021] usb 1-1: new high-speed USB device number 4 using fsl-ehci
[    4.868111] hub 1-1:1.0: USB hub found
[    5.265649] usb 1-1: USB disconnect, device number 4
[    5.510021] usb 1-1: new high-speed USB device number 5 using fsl-ehci
[    6.098025] usb 1-1: device not accepting address 5, error -71
[    6.398018] usb 1-1: new high-speed USB device number 7 using fsl-ehci

[  986.577885] usb 1-1: USB disconnect, device number 124
[  986.821924] usb 1-1: new high-speed USB device number 125 using fsl-ehci
[  986.960029] hub 1-1:1.0: USB hub found
[  991.933221] usb 1-1: USB disconnect, device number 125
[  992.177825] usb 1-1: new high-speed USB device number 126 using fsl-ehci
[  992.315980] hub 1-1:1.0: USB hub found
[ 1001.763764] usb 1-1: USB disconnect, device number 126
[ 1002.009660] usb 1-1: new high-speed USB device number 127 using fsl-ehci
[ 1002.159774] hub 1-1:1.0: USB hub found
[ 1006.033730] usb 1-1: USB disconnect, device number 127
[ 1006.281597] usb 1-1: new high-speed USB device number 2 using fsl-ehci
[ 1006.419736] hub 1-1:1.0: USB hub found
[ 1009.824073] usb 1-1: USB disconnect, device number 2
[ 1010.076110] usb 1-1: new high-speed USB device number 3 using fsl-ehci

cat /sys/kernel/debug/usb/devices 

T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480  MxCh= 1
B:  Alloc=  0/800 us ( 0%), #Int=  1, #Iso=  0
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev= 4.04
S:  Manufacturer=Linux 4.4.61 ehci_hcd
S:  Product=Freescale On-Chip EHCI Host Controller
S:  SerialNumber=fsl-ehci.0
C:* #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=  0mA
I:* If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub
E:  Ad=81(I) Atr=03(Int.) MxPS=   4 Ivl=256ms

T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#= 88 Spd=480  MxCh= 4
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=05e3 ProdID=0608 Rev=85.36
S:  Product=USB2.0 Hub
C:* #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=100mA
I:* If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub
E:  Ad=81(I) Atr=03(Int.) MxPS=   1 Ivl=256ms

lsusb -v

Bus 001 Device 090: ID 05e3:0608 Genesys Logic, Inc. Hub
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 Unused
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x05e3 Genesys Logic, Inc.
  idProduct          0x0608 Hub
  bcdDevice           85.36
  iManufacturer           0 
  iProduct                1 USB2.0 Hub
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           25
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12
Hub Descriptor:
  bLength               9
  bDescriptorType      41
  nNbrPorts             4
  wHubCharacteristic 0x00e9
    Per-port power switching
    Per-port overcurrent protection
    TT think time 32 FS bits
    Port indicators
  bPwrOn2PwrGood       50 * 2 milli seconds
  bHubContrCurrent    100 milli Ampere
  DeviceRemovable    0x00
  PortPwrCtrlMask    0xff
 Hub Port Status:
   Port 1: 0000.0100 power
   Port 2: 0000.0100 power
   Port 3: 0000.0100 power
   Port 4: 0000.0100 power
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 Unused
  bDeviceProtocol         0 Full speed (or root) hub
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0001
  Self Powered

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 Unused
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x1d6b Linux Foundation
  idProduct          0x0002 2.0 root hub
  bcdDevice            4.04
  iManufacturer           3 Linux 4.4.61 ehci_hcd
  iProduct                2 Freescale On-Chip EHCI Host Controller
  iSerial                 1 fsl-ehci.0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           25
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval              12
Hub Descriptor:
  bLength               9
  bDescriptorType      41
  nNbrPorts             1
  wHubCharacteristic 0x0009
    Per-port power switching
    Per-port overcurrent protection
    TT think time 8 FS bits
  bPwrOn2PwrGood       10 * 2 milli seconds
  bHubContrCurrent      0 milli Ampere
  DeviceRemovable    0x00
  PortPwrCtrlMask    0xff
 Hub Port Status:
   Port 1: 0000.0503 highspeed power enable connect
Device Status:     0x0001
  Self Powered

**Comment by Djfe** [comment]
stale @hauke 
WDR4900v1 running OpenWRT Release 22, Gluon22 to be specific (empty usb ports like OP):

```
# dmesg | grep -i usb
[    4.783996] usbcore: registered new interface driver usbfs
[    4.789558] usbcore: registered new interface driver hub
[    4.794918] usbcore: registered new device driver usb
[    4.842892] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.884060] fsl-ehci fsl-ehci.0: new USB bus registered, assigned bus number 1
[    4.927359] fsl-ehci fsl-ehci.0: USB 2.0 started, EHCI 1.00
[    4.933462] hub 1-0:1.0: USB hub found
[    4.955962] usbcore: registered new interface driver usb-storage
[    4.963728] usbcore: registered new interface driver uas
[    5.257385] usb 1-1: new high-speed USB device number 2 using fsl-ehci
[    5.481116] hub 1-1:1.0: USB hub found
[   16.350214] hso: drivers/net/usb/hso.c: Option Wireless
[   16.355619] usbcore: registered new interface driver hso
[   16.380857] usbcore: registered new interface driver ipheth
[   16.418030] pegasus: v0.9.3 (2013/04/25), Pegasus/Pegasus II USB Ethernet driver
[   16.425557] usbcore: registered new interface driver pegasus
[   16.435608] usbcore: registered new interface driver r8152
[   16.452736] usbcore: registered new interface driver ums-alauda
[   16.461351] usbcore: registered new interface driver ums-cypress
[   16.469865] usbcore: registered new interface driver ums-datafab
[   16.478348] usbcore: registered new interface driver ums-freecom
[   16.486958] usbcore: registered new interface driver ums-isd200
[   16.495676] usbcore: registered new interface driver ums-jumpshot
[   16.504302] usbcore: registered new interface driver ums-karma
[   16.513076] usbcore: registered new interface driver ums-sddr09
[   16.521636] usbcore: registered new interface driver ums-sddr55
[   16.530423] usbcore: registered new interface driver ums-usbat
[   16.544523] usbcore: registered new interface driver usbserial_generic
[   16.551134] usbserial: USB Serial support registered for generic
[   16.588083] usbcore: registered new interface driver asix
[   16.596485] usbcore: registered new interface driver ax88179_178a
[   16.605067] usbcore: registered new interface driver cdc_eem
[   16.613746] usbcore: registered new interface driver cdc_ether
[   16.623380] usbcore: registered new interface driver cdc_ncm
[   16.631433] usbcore: registered new interface driver cdc_subset
[   16.664296] usbcore: registered new interface driver dm9601
[   16.679725] usbcore: registered new interface driver ftdi_sio
[   16.685526] usbserial: USB Serial support registered for FTDI USB Serial Device
[   16.982920] usbcore: registered new interface driver MOSCHIP usb-ethernet driver
[   17.007289] usbcore: registered new interface driver pl2303
[   17.012947] usbserial: USB Serial support registered for pl2303
[   17.022208] usbcore: registered new interface driver rndis_host
[   17.031364] usbcore: registered new interface driver smsc95xx
# uptime
 11:25:17 up 1 day, 17:58,  load average: 0.11, 0.05, 0.06
```

The largest dmesg timevalue is 145336.082474 for comparison to 986.577885 from above
