### ISSUE TITLE
FS#747 - default dns service doesn't provide qname minimization

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5724]
*dsvensson:*

Supply the following if possible:
 
- Device problem occurs on

All

 - Software versions of LEDE release, packages, etc.

All

 - Steps to reproduce

* Perform a DNS resolution

qname minimization reduces the amount of information to sent via each lookup, this is to my knowledge not supported by dnsmasq which is the default DNS resolver in LEDE. It would be nice if support was added to it, or if it was replaced by some other name server that tries to reduce the amount of information leaked to foreign servers.

The spec:
https://tools.ietf.org/html/draft-ietf-dnsop-qname-minimisation-09

Unbound plugs this leak, does it lack anything that LEDE uses?

**Comment by jow-** [comment]
Not applicable to dnsmasq / stub forwarder use case.
