### ISSUE TITLE
FS#752 - mtk7688 radio in client mode throwing kernel stack traces about once a minute

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5727]
*russell:*

Supply the following if possible:
 - Device problem occurs on

AsiaRF AWM688, based on the mtk7688 SoC, similar to the LinkIt 7688

 - Software versions of LEDE release, packages, etc.

current HEAD (21c2e93e67bc44c1b72dbbe2dc9f9451d44f81a0)

 - Steps to reproduce

Put your wifi interface into station mode, with something like this:

<code>
uci set wireless.@wifi-iface[0].mode=sta
uci set wireless.@wifi-iface[0].network=wan
uci set wireless.@wifi-iface[0].ssid="<yournetworkssid>"
uci set wireless.@wifi-iface[0].encryption=<yournetworkencryption>
uci set wireless.@wifi-iface[0].key=<yournetworkkey>
uci set network.wan.ifname=''
uci commit wireless
uci commit network
/etc/init.d/network restart
</code>

The stack traces look like this:

<code>
[  381.712245] ------------[ cut here ]------------
[  381.721603] WARNING: CPU: 0 PID: 0 at compat-wireless-2017-01-31/net/mac80211/tx.c:4230 ieee80211_csa_is_complete+0x4d4/0x668 [mac80211]()
[  381.746243] Modules linked in: pppoe ppp_async snd_usb_audio pppox ppp_generic pl2303 nf_conntrack_ipv6 mmc_spi iptable_nat ipt_REJECT ipt_MASQUERADE ftdi_sio cp210x ch341 xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG usbserial usbmon ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda spidev snd_usbmidi_lib slhc pwm_mediatek of_mmc_spi nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc7 crc_itu_t crc_ccitt snd_soc_simple_card snd_soc_ralink_i2s snd_soc_wm8960 i2c_mt7621 snd_soc_core ralink_gdma virt_dma mt76x2e mt7603e i2c_dev mt76 mac80211 cfg80211 compat ledtrig_oneshot ledtrig_heartbeat ledtrig_gpio ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables snd_pcm_dmaengine snd_compress snd_pcm_oss snd_mixer_oss snd_pcm snd_timer snd_rawmidi snd_seq_device snd_hwdep snd input_core soundcore vfat fat nls_utf8 nls_iso8859_1 nls_cp437 regmap_spi regmap_mmio regmap_i2c i2c_core regmap_core lzo_decompress lzo_compress mmc_block usb_storage mtk_sd mmc_core leds_gpio ohci_platform ohci_hcd ledtrig_transient ehci_platform sd_mod scsi_mod ehci_hcd gpio_button_hotplug usbcore nls_base usb_common
[  381.997790] CPU: 0 PID: 0 Comm: swapper Tainted: G        W       4.4.61 #0
[  382.011576] Stack : 8035bff4 00000000 00000001 803a0000 803a10dc 803a0d63 8033d94c 00000000
          803f3438 8380de90 00000000 82d2b630 00000001 8004ae6c 80342e54 803a0000
          00000003 8380de90 80341258 8380dd74 00000001 80048dd8 83012b40 00000000
          8039fe50 00000000 00000000 00000000 00000000 00000000 00000000 00000000
          00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
          ...
[  382.082022] Call Trace:
[  382.086872] [<8001486c>] show_stack+0x50/0x84
[  382.095501] [<8002544c>] warn_slowpath_common+0xa0/0xd0
[  382.105857] [<80025504>] warn_slowpath_null+0x18/0x24
[  382.115987] [<832aa34c>] ieee80211_csa_is_complete+0x4d4/0x668 [mac80211]
[  382.129537] 
[  382.132479] ---[ end trace cedc8f2cca6a57da ]---
[  448.821439] ------------[ cut here ]------------
[  448.830796] WARNING: CPU: 0 PID: 0 at compat-wireless-2017-01-31/net/mac80211/tx.c:4230 ieee80211_csa_is_complete+0x4d4/0x668 [mac80211]()
[  448.855431] Modules linked in: pppoe ppp_async snd_usb_audio pppox ppp_generic pl2303 nf_conntrack_ipv6 mmc_spi iptable_nat ipt_REJECT ipt_MASQUERADE ftdi_sio cp210x ch341 xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG usbserial usbmon ums_usbat ums_sddr55 ums_sddr09 ums_karma ms_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda spidev snd_usbmidi_lib slhc pwm_mediatek of_mmc_spi nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc7 crc_itu_t crc_ccitt snd_soc_simple_card snd_soc_ralink_i2s snd_soc_wm8960 i2c_mt7621 snd_soc_core ralink_gdma virt_dma mt76x2e mt7603e i2c_dev mt76 mac80211 cfg80211 compat ledtrig_oneshot ledtrig_heartbeat ledtrig_gpio ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables snd_pcm_dmaengine snd_compress snd_pcm_oss snd_mixer_oss snd_pcm snd_timer snd_rawmidi snd_seq_device snd_hwdep snd input_core soundcore vfat fat nls_utf8 nls_iso8859_1 nls_cp437 regmap_spi regmap_mmio regmap_i2c i2c_core regmap_core lzo_decompress lzo_compress mmc_block usb_storage mtk_sd mmc_core leds_gpio ohci_platform ohci_hcd ledtrig_transient ehci_platform sd_mod scsi_mod ehci_hcd gpio_button_hotplug usbcore nls_base usb_common
[  449.106963] CPU: 0 PID: 0 Comm: swapper Tainted: G        W       4.4.61 #0
[  449.120752] Stack : 8035bff4 00000000 00000001 803a0000 803a10dc 803a0d63 8033d94c 00000000
          803f3438 8380de90 00000000 82d2b630 00000001 8004ae6c 80342e54 803a0000
          00000003 8380de90 80341258 8380dd74 00000001 80048dd8 831a7852 00000000
          8039fe50 00000000 00000000 00000000 00000000 00000000 00000000 00000000
          00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
          ...
[  449.191202] Call Trace:
[  449.196044] [<8001486c>] show_stack+0x50/0x84
[  449.204680] [<8002544c>] warn_slowpath_common+0xa0/0xd0
[  449.215034] [<80025504>] warn_slowpath_null+0x18/0x24
[  449.225170] [<832aa34c>] ieee80211_csa_is_complete+0x4d4/0x668 [mac80211]
[  449.238722] 
[  449.241679] ---[ end trace cedc8f2cca6a57db ]---
</code>

The line number is a bit off, but it looks like maybe ieee80211_csa_is_complete is complaining because vif->type == station mode isn't handled.  I don't know what "csa" means here.

**Comment by RussellSenior** [comment]
This looks old and resolved, please close
