### ISSUE TITLE
FS#591 - Include branch info in subject from 'lede-commits'

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5753]
*None:*

Please include the branch being committed to as part of the subject. As it currently stands emails are received:

[source]  ubox: update to the latest version
[source]  bcm53xx: include Broadcom PHY driver in the kernel

However there's no clue in the subject that the ubox commit is for 'master' (and of interest to me) whilst the 'bcm53xx' is a commit to '17.01' (and of much less interest to me)

It's driving me (even more) insane :-)

**Comment by aparcar** [comment]
This issue is for a EOL release, please comment if this bug still affects you in currently supported releases.
