### ISSUE TITLE
FS#797 - Asus RT-N12 rev. D1: Wireless not detected

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5757]
*qwertychouskie:*

The wireless system is not detected in LEDE.  It seems to work fine with DD-WRT: http://www.dd-wrt.com/phpBB2/viewtopic.php?p=934736

Supply the following if possible:
 - Device problem occurs on: ASUS RT-N12 D1
 - Software versions of LEDE release, packages, etc.: Latest release
 - Steps to reproduce: Install LEDE, open LuCi, see no wireless interfaces

**Comment by Djfe** [comment]
This is a 8/32 device with an unsupported broadcom wifi chip. I don't see any value in keeping this open @hauke

**Comment by hauke** [comment]
The wifi IP core is probably unsupported.
