### ISSUE TITLE
FS#850 - Comfast CF-CU715N crashes (rt5370)

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5794]
*murix:*

My TP Link WR1043v1 is running LEDE 17.01.2, I use a Comfast CF-CU715N for create a second link in different channel. But the Comfast CF-CU715N which is based in RT5730 (kmod-rt2800-usb).

Linux version 4.4.71 (buildbot@builds-02.infra.lede-project.org) (gcc version 5.4.0 (LEDE GCC 5.4.0 r3101-bce140e) ) #0 Wed Jun 7 19:24:41 2017

Follow the trace
[ 3779.373114] ------------[ cut here ]------------
[ 3779.378077] WARNING: CPU: 0 PID: 3780 at compat-wireless-2017-01-31/net/mac80211/main.c:1218 0x80d812bc [mac80211@80d80000+0x60780]()
[ 3779.390203] Have pending ack frames!
[ 3779.393808] Modules linked in: tun rt2800usb rt2800lib rt2x00usb rt2x00lib crc_itu_t ath9k ath9k_common pppoe ppp_async iptable_nat ath9k_hw ath pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 mac80211 ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_CT slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc_ccitt compat ledtrig_usbport ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables ehci_platform ehci_hcd gpio_button_hotplug usbcore nls_base usb_common
[ 3779.462604] CPU: 0 PID: 3780 Comm: kworker/0:0 Not tainted 4.4.71 #0
[ 3779.469029] Workqueue: usb_hub_wq 0x81b84534 [usbcore@81b80000+0x1c1f0]
[ 3779.475697] Stack : 00000010 00000020 ff000000 800a71dc 00000000 00000000 00000000 00000000
[ 3779.475697]    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 3779.475697]    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 3779.475697]    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 3779.475697]    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 3779.475697]    ...
[ 3779.511770] Call Trace:[<800a71dc>] 0x800a71dc
[ 3779.516275] [<80071a50>] 0x80071a50
[ 3779.519791] [<80071a50>] 0x80071a50
[ 3779.523320] [<80081804>] 0x80081804
[ 3779.526864] [<80d812bc>] 0x80d812bc [mac80211@80d80000+0x60780]
[ 3779.532852] [<80d81284>] 0x80d81284 [mac80211@80d80000+0x60780]
[ 3779.538814] [<80081860>] 0x80081860
[ 3779.542361] [<80d812bc>] 0x80d812bc [mac80211@80d80000+0x60780]
[ 3779.548319] [<801a5fac>] 0x801a5fac
[ 3779.551922] [<80d81254>] 0x80d81254 [mac80211@80d80000+0x60780]
[ 3779.557887] [<80ca8520>] 0x80ca8520 [rt2x00usb@80ca8000+0x1ce0]
[ 3779.563892] [<80ca9344>] 0x80ca9344 [rt2x00usb@80ca8000+0x1ce0]
[ 3779.569848] [<8009908c>] 0x8009908c
[ 3779.573405] [<81b8cdf8>] 0x81b8cdf8 [usbcore@81b80000+0x1c1f0]
[ 3779.579325] [<801ff960>] 0x801ff960
[ 3779.582861] [<801fe224>] 0x801fe224
[ 3779.586396] [<801ffa00>] 0x801ffa00
[ 3779.589942] [<801febb0>] 0x801febb0
[ 3779.593477] [<801fc1ec>] 0x801fc1ec
[ 3779.596999] [<801fc138>] 0x801fc138
[ 3779.600534] [<81b8b1e0>] 0x81b8b1e0 [usbcore@81b80000+0x1c1f0]
[ 3779.606449] [<81b8b894>] 0x81b8b894 [usbcore@81b80000+0x1c1f0]
[ 3779.612344] [<81b81858>] 0x81b81858 [usbcore@81b80000+0x1c1f0]
[ 3779.618244] [<81b83bd4>] 0x81b83bd4 [usbcore@81b80000+0x1c1f0]
[ 3779.624179] [<81b84a8c>] 0x81b84a8c [usbcore@81b80000+0x1c1f0]
[ 3779.630134] [<800930b8>] 0x800930b8
[ 3779.633685] [<80093ecc>] 0x80093ecc
[ 3779.637206] [<80093c1c>] 0x80093c1c
[ 3779.640735] [<80093c1c>] 0x80093c1c
[ 3779.644267] [<80098284>] 0x80098284
[ 3779.647790] [<800981ac>] 0x800981ac
[ 3779.651330] [<80060878>] 0x80060878
[ 3779.654856]
[ 3779.656362] ---[ end trace 69bc4427c2b074d4 ]---
[ 3799.640894] usb 1-1: new high-speed USB device number 3 using ehci-platform
[ 3799.940887] usb 1-1: reset high-speed USB device number 3 using ehci-platform
[ 3800.102090] ieee80211 phy2: rt2x00_set_rt: Info - RT chipset 5390, rev 0502 detected
[ 3800.143725] ieee80211 phy2: rt2x00_set_rf: Info - RF chipset 5370 detected
[ 3800.161898] ieee80211 phy2: Selected rate control algorithm 'minstrel_ht'
[ 3800.180473] ieee80211 phy2: rt2x00lib_request_firmware: Info - Loading firmware file 'rt2870.bin'
[ 3800.237431] ieee80211 phy2: rt2x00lib_request_firmware: Info - Firmware detected - version: 0.36

**Comment by ynezz** [comment]
Old.
