### ISSUE TITLE
FS#853 - Change dnsmasq domain and local options to lists

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5798]
*cimbalo:*

On LEDE 17.01 'domain' and 'local' options in dnsmasq configuration doesn't correctly support lists values as per dnsmasq capabilities.

====Steps to reproduce====
<code>
#/etc/config/dhcp
[...]
config dnsmasq
        list domain 'example1.com,192.168.0.0/24'
        list domain 'example2.com,192.168.1.0/24'
        list local '/example1.com/'
        list local '/example2.com/'
[...]
</code>
$ uci commit dhcp
$ /etc/init.d/dnsmasq restart

====Actual results====
<code>
#/var/etc/dnsmasq.conf.cfg02411c
[...]
domain=example1.com,192.168.0.0/24 example2.com,192.168.1.0/24
local=/example1.com/ /example2.com/
[...]</code>

====Expected results====
<code>#/var/etc/dnsmasq.conf.cfg02411c
[...]
domain=example1.com,192.168.0.0/24
domain=example2.com,192.168.1.0/24
local=/example1.com/
local=/example2.com/
[...]</code>

====Workaround====
Replace append_parm with config_list_foreach [[https://github.com/lede-project/source/blob/master/package/network/services/dnsmasq/files/dnsmasq.init#L816-L817|here]] resolve the issue.
I'm attaching a patch for the 17.01 dnsmasq init script but it will break old uci configuration that use 'option' instead of 'list'.
Do you have any suggestion on how to migrate old configuration and set those parameters as lists in uci web interface?

**Comment by aparcar** [comment]
This issue is for a EOL release, please comment if this bug still affects you in currently supported releases.
