### ISSUE TITLE
FS#868 - Snapshot directory contains stray/obsolete directories

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5802]
*diizzyy:*

Please remove obsolete directories in the snapshot directory (packages)

aarch64_armv8-a/
arm_cortex-a53_neon-vfpv4/
arm_cortex-a7/
i386_geode/
powerpc_440/

**Comment by Djfe** [comment]
@hauke the only one of these folders that remains isn't stray/obsolete anymore, I think:
https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7/
so this can be closed

**Comment by hauke** [comment]
The obsolete directories i were removed some time ago.
