### ISSUE TITLE
FS#901 - USB not working on MikroTik hAP ac 

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5846]
*rmounce:*

Only affecting hAP ac / RB962UiGS-5HacT2HnT

Tested with LEDE trunk in April, no relevant commits to device since.

GPIO to control USB power works, and USB controller appears in dmesg on boot. Upon connecting any device, it is not recognised and there are no kernel messages. Same devices work (albeit via internal hub) on Archer C7 v2 using same SoC.

Bug independently verified by another user, not a hardware defect with a single unit.

I am aware of the irony that I contributed the support for this device, and reported USB as working. I was only looking for the controller to be recognised and neglected to test with an actual USB device until after this was merged. My bad. Logging as a bug so that anyone who finds it not working can at least see a record and know to direct their blame towards me :)

**Comment by Djfe** [comment]
@rmounce do you still have the device? Is usb still broken in release/snapshot?

**Comment by rmounce** [comment]
@Djfe according to https://github.com/openwrt/openwrt/commit/c2140e32ce32b9cc60f7d408e20bdf45dce6a634 it should be working with the ath79 target. I no longer use the device.

**Comment by Djfe** [comment]
That was quick, thanks :)
@hauke pls close this issue

**Comment by hauke** [comment]
The new device tree (c2140e32ce32b9cc60f7d408e20bdf45dce6a634) defines:
````

		usb_power {
			gpio-export,name = "usb-power";
			gpio-export,output = <0>;
			gpios = <&gpio 13 GPIO_ACTIVE_HIGH>;
		};
````This should fix the problem.
