### ISSUE TITLE
FS#985 - DIR-320 B1 dont save it's settings after power off

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#5918]
*silentcat:*

Supply the following if possible:
 - Device problem occurs on DIR-320 B1 (NRU)
 - Software versions of LEDE release, packages, etc. 17.01.2
 - Steps to reproduce
   Just Install LEDE 17.01.2 configure it. And get electrical plug off. Plug in and device settings are default.

**Comment by Djfe** [comment]
stale @hauke 
If anyone actually experiences this bug again, then they can open a new issue. If this weren't fixed, then there would probably be another issue about it on here or posts about it on the forum.
