### ISSUE TITLE
FS#1071 - Sysupgrade fails when kernel console is disabled

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6005]
*xback:*

Hardware used:
- Gateworks Ventana imx6 board (GW5200)

Synopsis:

Running sysupgrade with a valid image fails if the kernel console is disabled in u-boot (setenv console ; saveenv; reset)
As soon as sysupgrade starts, the board reboots immediately.

The detected reboot reason displayed is exactly the same in both cases.

Reset cause: WDOG
 WDOG1 Reset cause: SFTW
 WDOG2 Reset cause: POR

Basically:
- Kernel console enabled  (console = ttymxc1) --> sysupgrade runs normally and succeeds
- Kernel console disabled (console =        ) --> The board reboots within 1 second as soon as sysupgrade starts

Rationale for disabling kernel console:

- This board exposes 2 UART ports for user applications (ttymxc0,  ttymxc1)
- ttymxc1 is shared with the kernel console and needs to be disabled so it does not interfere with the peripheral communication
- Both ports are used in my case (ttymxc0: GPS received  ;  ttymxc1: Iridium modem)

**Comment by ynezz** [comment]
Too old.

**Comment by plan44** [comment]
Thanks @xback, @abatyiev, @rondom and all others involved for this analysis and finally solution! 😄  Finding this discussion was the happy end after two days of unsuccessfully trying to make sense why /sbin/upgraded did not find stage2 in my target (rv1106 based Luckfox 86panel). The chd('/dev') escaped me, but that target by accident also had a nonfunctional /dev/console…
