### ISSUE TITLE
FS#1102 - Kernel crash on mt7621 at mm/slub.c

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6025]
*pparent76:*

I have recurrent crashes when using my wg3526 based on mt76 for long time. The wifi 2.4 ghz is activated (mt7603 driver), but 5ghz is not.

<code>
<4>[19202.879743] ------------[ cut here ]------------
<4>[19202.884402] WARNING: CPU: 3 PID: 0 at mm/slub.c:3843 ksize+0xe0/0xf8
<4>[19202.890789] Modules linked in: xt_coova pppoe ppp_async rtl8192cu rtl8192c_common rtl_usb pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY slhc rtlwifi nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt em_cmp em_nbyte sch_dsmark sch_pie act_ipt sch_codel sch_gred em_meta sch_teql cls_basic sch_prio em_text sch_sfq act_police sch_fq sch_red
<4>[19202.961498]  act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress mt7603e ledtrig_usbport mt76 mac80211 cfg80211 compat xt_set ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables tun mmc_block usb_storage mtk_sd mmc_core leds_gpio xhci_mtk xhci_plat_hcd xhci_pci xhci_hcd ahci libahci libata sd_mod scsi_mod gpio_button_hotplug ext4 jbd2 mbcache usbcore nls_base usb_common crc32c_generic [last unloaded: xt_coova]<4>[19203.032447] CPU: 3 PID: 0 Comm: swapper/3 Tainted: G        W       4.9.54 #0
<4>[19203.039549] Stack : 00000000 00000000 80557b2a 00000041 80406a24 00000000 00000000 80550000
<4>[19203.047897]         8fc5499c 804ebea7 80482c5c 00000003 00000000 80553824 02080020 8fd3705c
<4>[19203.056241]         804e95fc 8006b878 00000001 80550000 804f1fa4 804f1fa8 80487844 8fc21ce0
<4>[19203.064589]         00000003 800a9fd0 02080020 8fd3705c 0000329a 00000007 8f21db00 00c21ce0
<4>[19203.072937]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[19203.081299]         ...
<4>[19203.083744] Call Trace:
<4>[19203.086218] [<8000f814>] show_stack+0x54/0x88
<4>[19203.090590] [<801df1cc>] dump_stack+0x8c/0xd0
<4>[19203.094939] [<8002bdc4>] __warn+0xe4/0x118
<4>[19203.099026] [<8002be8c>] warn_slowpath_null+0x1c/0x30
<4>[19203.104081] [<800e882c>] ksize+0xe0/0xf8
<4>[19203.107999] [<802d90d0>] pskb_expand_head+0x98/0x23c
<4>[19203.112958] [<8032aa28>] ip_forward+0x374/0x45c
<4>[19203.117474] [<803294c8>] ip_rcv+0x2b8/0x320
<4>[19203.121653] [<802e98d0>] __netif_receive_skb_core+0x718/0x970
<4>[19203.127384] [<802eb7bc>] process_backlog+0x9c/0x160
<4>[19203.132248] [<802eb55c>] net_rx_action+0x138/0x2fc
<4>[19203.137033] [<8002f924>] __do_softirq+0x294/0x2e0
<4>[19203.141726] [<8002fc18>] irq_exit+0x7c/0x98
<4>[19203.145913] [<8020e3d0>] plat_irq_dispatch+0xb4/0xdc
<4>[19203.150866] [<8000a968>] except_vec_vi_end+0xb8/0xc4
<4>[19203.155842] [<80064fc4>] cpu_startup_entry+0x104/0x170
<4>[19203.161091] ---[ end trace 09207f98d12feebb ]---
<4>[19203.165803] Kernel bug detected[#1]:
<1>[19203.165897] CPU 3 Unable to handle kernel paging request at virtual address 00004000, epc == 800eb628, ra == 800eb5ac
<4>[19203.179938] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W       4.9.54 #0
<4>[19203.187042] task: 804ebfa0 task.stack: 804dc000
<4>[19203.191547] $ 0   : 00000000 80550000 81026b40 00000001
<4>[19203.196767] $ 4   : 00000000 81026b53 000f0000 811da600
<4>[19203.201984] $ 8   : 804f0000 80584864 8fc0df54 8fc0df54
<4>[19203.207198] $12   : 11000000 ffffffff 00000000 0000002d
<4>[19203.212415] $16   : 8eaaa600 8ffa1308 8ffa1000 0000007d
<4>[19203.217631] $20   : 000000ca 0000003f 8ffa1308 00000018
<4>[19203.222846] $24   : 00000000 8000c30c                  
<4>[19203.228063] $28   : 804dc000 8fc0de3c ffffffff 802d5e00
<4>[19203.233278] Hi    : 00000003
<4>[19203.236139] Lo    : 00000000
<4>[19203.239036] epc   : 800e9b90 kfree+0x78/0x1a4
<4>[19203.243394] ra    : 802d5e00 __kfree_skb+0x14/0xa4
<4>[19203.248157] Status: 11008403      KERNEL EXL IE 
<4>[19203.252333] Cause : 50800034 (ExcCode 0d)
<4>[19203.256319] PrId  : 0001992f (MIPS 1004Kc)
<4>[19203.260389] Modules linked in: xt_coova pppoe ppp_async rtl8192cu rtl8192c_common rtl_usb pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY slhc rtlwifi nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt em_cmp em_nbyte sch_dsmark sch_pie act_ipt sch_codel sch_gred em_meta sch_teql cls_basic sch_prio em_text sch_sfq act_police sch_fq sch_red
<4>[19203.330928]  act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress mt7603e ledtrig_usbport mt76 mac80211 cfg80211 compat xt_set ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables tun mmc_block usb_storage mtk_sd mmc_core leds_gpio xhci_mtk xhci_plat_hcd xhci_pci xhci_hcd ahci libahci libata sd_mod scsi_mod gpio_button_hotplug ext4 jbd2 mbcache usbcore nls_base usb_common crc32c_generic [last unloaded: xt_coova]Process swapper/0 (pid: 0, threadinfo=804dc000, task=804ebfa0, tls=00000000)
<4>[19203.408441] Stack : 000000ca 0000003f 8ffa1308 00000018 8ef712d8 802b0400 0003000f 802b2240
<4>[19203.416786]         8e245c60 8eaa10c0 00000000 aef74b40 00000001 8ffa14b8 000000c9 802b2658
<4>[19203.425131]         803f7afc 8149e440 802e6138 00000001 0000012b 80510000 804df9c0 00000001
<4>[19203.433476]         8fdc7900 00000001 80580000 0000000f 00030000 9bfe8000 01000000 00000010
<4>[19203.441822]         30000000 8009483c 0e245ca0 01000000 0f2d4480 00000004 00000040 804df9c0
<4>[19203.450167]         ...
<4>[19203.452603] Call Trace:
<4>[19203.455038] [<800e9b90>] kfree+0x78/0x1a4
<4>[19203.459038] [<802d5e00>] __kfree_skb+0x14/0xa4
<4>[19203.463475] [<802b0400>] fe_txd_unmap+0xd4/0xec
<4>[19203.467986] [<802b2658>] fe_poll+0x134/0x700
<4>[19203.472243] [<802eb55c>] net_rx_action+0x138/0x2fc
<4>[19203.477022] [<8002f924>] __do_softirq+0x294/0x2e0
<4>[19203.481705] [<8002fc18>] irq_exit+0x7c/0x98
<4>[19203.485882] [<8020e3d0>] plat_irq_dispatch+0xb4/0xdc
<4>[19203.490831] [<8000a968>] except_vec_vi_end+0xb8/0xc4
<4>[19203.495777] [<8000c324>] r4k_wait_irqoff+0x18/0x20
<4>[19203.500572] [<80064fc4>] cpu_startup_entry+0x104/0x170
<4>[19203.505712] [<80513be4>] start_kernel+0x47c/0x49c
<4>[19203.510392] Code: 30630001  24030001  38630001 <00030336> 8c430000  7c630380  10600003  00000000  10000002 
<4>[19203.520132] 
<4>[19203.521619] Oops[#2]:
<4>[19203.521836] ---[ end trace 09207f99d12feebb ]---

===================================
Time: 1508726234.629265
<0>[19203.526701] Kernel panic - not syncing: Fatal exception in interrupt</code>

<code><4>[82713.077406] Stack : 00000000 00000000 80557b2a 00000041 80406a24 00000000 00000000 80550000
<4>[82713.085754]         804ec2bc 804ebea7 80482c5c 00000000 00000000 80553824 00000054 8f295a00
<4>[82713.094099]         00000000 8006b878 00000001 80550000 804f1fa4 804f1fa8 80487844 8fc0dd90
<4>[82713.102444]         00000003 800a9fd0 00000054 8f295a00 0000f7f3 00000007 00000000 00c0dd90
<4>[82713.110789]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[82713.119130]         ...
<4>[82713.121567] Call Trace:
<4>[82713.124029] [<8000f814>] show_stack+0x54/0x88
<4>[82713.128386] [<801df1cc>] dump_stack+0x8c/0xd0
<4>[82713.132727] [<8002bdc4>] __warn+0xe4/0x118
<4>[82713.136803] [<8002be8c>] warn_slowpath_null+0x1c/0x30
<4>[82713.141876] [<8f28c124>] mt7603_mac_fill_rx+0x2b0/0x3a8 [mt7603e]
<4>[82713.147957] [<8f28ae30>] mt7603_queue_rx_skb+0x9c/0xe4 [mt7603e]
<4>[82713.153958] [<8f284d6c>] mt76_dma_attach+0xa9c/0xc94 [mt76]
<4>[82713.159601] ---[ end trace 30529a2ab5a2f517 ]---
<4>[82713.164302] ------------[ cut here ]------------
<4>[82713.169064] WARNING: CPU: 0 PID: 0 at backports-2017-10-06/net/mac80211/rx.c:4321 ieee80211_rx_napi+0xa8/0x964 [mac80211]
<4>[82713.180018] Modules linked in: xt_coova pppoe ppp_async rtl8192cu rtl8192c_common rtl_usb pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY slhc rtlwifi nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt em_cmp em_nbyte sch_dsmark sch_pie act_ipt sch_codel sch_gred em_meta sch_teql cls_basic sch_prio em_text sch_sfq act_police sch_fq sch_red
<4>[82713.250675]  act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress mt7603e ledtrig_usbport mt76 mac80211 cfg80211 compat xt_set ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables tun mmc_block usb_storage mtk_sd mmc_core leds_gpio xhci_mtk xhci_plat_hcd xhci_pci xhci_hcd ahci libahci libata sd_mod scsi_mod gpio_button_hotplug ext4 jbd2 mbcache usbcore nls_base usb_common crc32c_generic [last unloaded: xt_coova]<4>[82713.321600] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W       4.9.54 #0
<4>[82713.328698] Stack : 00000000 00000000 80557b2a 00000041 80406a24 00000000 00000000 80550000
<4>[82713.337045]         804ec2bc 804ebea7 80482c5c 00000000 00000000 80553824 00000001 8f295a00
<4>[82713.345391]         00000000 8006b878 00000001 80550000 804f1fa4 804f1fa8 80487844 8fc0dd38
<4>[82713.353736]         00000003 800a9fd0 00000001 8f295a00 0000f997 00000007 00000008 00c0dd38
<4>[82713.362081]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[82713.370424]         ...
<4>[82713.372859] Call Trace:
<4>[82713.375308] [<8000f814>] show_stack+0x54/0x88
<4>[82713.379658] [<801df1cc>] dump_stack+0x8c/0xd0
<4>[82713.383995] [<8002bdc4>] __warn+0xe4/0x118
<4>[82713.388071] [<8002be8c>] warn_slowpath_null+0x1c/0x30
<4>[82713.393195] [<8f325b94>] ieee80211_rx_napi+0xa8/0x964 [mac80211]
<4>[82713.399231] [<8f2858b4>] mt76_rx_complete+0x88/0x118 [mt76]
<4>[82713.404794] [<8f284e7c>] mt76_dma_attach+0xbac/0xc94 [mt76]
<4>[82713.410438] ---[ end trace 30529a2bb5a2f517 ]---
<4>[82715.996390] ------------[ cut here ]------------
<4>[82716.001062] WARNING: CPU: 3 PID: 0 at mm/slub.c:3843 ksize+0xe0/0xf8
<4>[82716.007380] Modules linked in: xt_coova pppoe ppp_async rtl8192cu rtl8192c_common rtl_usb pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY slhc rtlwifi nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt em_cmp em_nbyte sch_dsmark sch_pie act_ipt sch_codel sch_gred em_meta sch_teql cls_basic sch_prio em_text sch_sfq act_police sch_fq sch_red
<4>[82716.078197]  act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress mt7603e ledtrig_usbport mt76 mac80211 cfg80211 compat xt_set ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables tun mmc_block usb_storage mtk_sd mmc_core leds_gpio xhci_mtk xhci_plat_hcd xhci_pci xhci_hcd ahci libahci libata sd_mod scsi_mod gpio_button_hotplug ext4 jbd2 mbcache usbcore nls_base usb_common crc32c_generic [last unloaded: xt_coova]<4>[82716.149239] CPU: 3 PID: 0 Comm: swapper/3 Tainted: G        W       4.9.54 #0
<4>[82716.156343] Stack : 00000000 00000000 80557b2a 00000041 80406a24 00000000 00000000 80550000
<4>[82716.164705]         8fc5499c 804ebea7 80482c5c 00000003 00000000 80553824 8f3a4000 8edd5c80
<4>[82716.173065]         00000000 8006b878 00000001 80550000 804f1fa4 804f1fa8 80487844 8fc21940
<4>[82716.181427]         00000003 800a9fd0 8f3a4000 8edd5c80 0000fb43 00000007 8e826084 00c21940
<4>[82716.189786]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[82716.198143]         ...
<4>[82716.200587] Call Trace:
<4>[82716.203059] [<8000f814>] show_stack+0x54/0x88
<4>[82716.207424] [<801df1cc>] dump_stack+0x8c/0xd0
<4>[82716.211774] [<8002bdc4>] __warn+0xe4/0x118
<4>[82716.215861] [<8002be8c>] warn_slowpath_null+0x1c/0x30
<4>[82716.220915] [<800e882c>] ksize+0xe0/0xf8
<4>[82716.224832] [<802d90d0>] pskb_expand_head+0x98/0x23c
<4>[82716.229996] [<8f329150>] ieee80211_probereq_get+0xb48/0x190c [mac80211]
<4>[82716.236678] [<80064264>] __wake_up_common+0x64/0xb4
<4>[82716.241619] ---[ end trace 30529a2cb5a2f517 ]---
<4>[82716.246369] Kernel bug detected[#1]:
<1>[82716.246495] CPU 3 Unable to handle kernel paging request at virtual address 00004000, epc == 800eb628, ra == 800eb5ac
<4>[82716.260496] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W       4.9.54 #0
<4>[82716.267598] task: 804ebfa0 task.stack: 804dc000
<4>[82716.272101] $ 0   : 00000000 80550000 81026960 00000001
<4>[82716.277321] $ 4   : 00000000 81026973 000f0000 811cb400
<4>[82716.282538] $ 8   : 804f0000 801eb464 8fc0df54 8fc0df54
<4>[82716.287752] $12   : 11000000 00000000 00000000 00000005
<4>[82716.292968] $16   : 8d488000 8f295540 8ff23064 8f295b7c
<4>[82716.298183] $20   : 00000002 8f295b78 00000000 00000009
<4>[82716.303399] $24   : 00000000 8000c30c                  
<4>[82716.308613] $28   : 804dc000 8fc0de9c 802044f7 802d5e00
<4>[82716.313831] Hi    : 00000004
<4>[82716.316692] Lo    : 00000000
<4>[82716.319581] epc   : 800e9b90 kfree+0x78/0x1a4
<4>[82716.323940] ra    : 802d5e00 __kfree_skb+0x14/0xa4
<4>[82716.328701] Status: 11008403      KERNEL EXL IE 
<4>[82716.332884] Cause : 50800034 (ExcCode 0d)
<4>[82716.336872] PrId  : 0001992f (MIPS 1004Kc)
<4>[82716.340942] Modules linked in: xt_coova pppoe ppp_async rtl8192cu rtl8192c_common rtl_usb pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY slhc rtlwifi nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt em_cmp em_nbyte sch_dsmark sch_pie act_ipt sch_codel sch_gred em_meta sch_teql cls_basic sch_prio em_text sch_sfq act_police sch_fq sch_red
<4>[82716.411537]  act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress mt7603e ledtrig_usbport mt76 mac80211 cfg80211 compat xt_set ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables tun mmc_block usb_storage mtk_sd mmc_core leds_gpio xhci_mtk xhci_plat_hcd xhci_pci xhci_hcd ahci libahci libata sd_mod scsi_mod gpio_button_hotplug ext4 jbd2 mbcache usbcore nls_base usb_common crc32c_generic [last unloaded: xt_coova]Process swapper/0 (pid: 0, threadinfo=804dc000, task=804ebfa0, tls=00000000)
<4>[82716.489176] Stack : 00000002 8f2955b0 8f295540 8ff23064 8f2955b0 8f2849f0 9bfe8000 8006d534
<4>[82716.497539]         8fc35480 00000001 00000000 00000000 00000000 00000000 00000070 804f0000
<4>[82716.505899]         00010000 8d488000 8df26790 00000001 8f295540 00000001 ffffffff 00000002
<4>[82716.514260]         00000000 804de040 00000100 0000000a 00000018 8f28ab70 80580000 80580000
<4>[82716.522625]         00000004 8006c99c 8f296188 8054121c 804e95fc 8003020c 00000006 8020f290
<4>[82716.530989]         ...
<4>[82716.533431] Call Trace:
<4>[82716.535883] [<800e9b90>] kfree+0x78/0x1a4
<4>[82716.539897] [<802d5e00>] __kfree_skb+0x14/0xa4
<4>[82716.544372] [<8f2849f0>] mt76_dma_attach+0x720/0xc94 [mt76]
<4>[82716.549930] Code: 30630001  24030001  38630001 <00030336> 8c430000  7c630380  10600003  00000000  10000002 
<4>[82716.559695] 
<4>[82716.561183] Oops[#2]:
<4>[82716.561433] ---[ end trace 30529a2db5a2f517 ]---

===================================
Time: 1508284734.35088</code>

**Comment by lynxis** [comment]
I'm closing this issue for now (because of inactivity) and a 5 year old issue.
Hopefully this issue has been already fixed by the current mt76 version.

If this issue is still exists for the latest release please reopen it.
