### ISSUE TITLE
FS#1113 - Unknown symbol zlib_inflate

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6035]
*ffix:*

I've experienced a strange issue with zlib_inflate on x84_64 system.
There is no zlib_inflate-related symbols at /proc/kallsyms and modules like btrfs couldn't be loaded.

17.01 branch and the current master branch, both are affected.

Steps to reproduce:
1. Use attached config file (zlib_inflate-test-config). It's almost default but I've set CONFIG_PACKAGE_kmod-fs-btrfs=y and some other options.
2. Compile LEDE:
<code>make defconfig && make -j $(nproc)</code>
3. Run qemu:
<code>qemu-system-x86_64 -curses -kernel bin/targets/x86/64/lede-x86-64-ramfs.bzImage</code>
4. Try to load btrfs module:
<code>root@LEDE:/# modprobe btrfs
[   23.345891] btrfs: Unknown symbol zlib_inflateInit2 (err 0)
[   23.347096] btrfs: Unknown symbol zlib_inflate (err 0)
[   23.347673] btrfs: Unknown symbol zlib_inflate_workspacesize (err 0)
[   23.348293] btrfs: Unknown symbol zlib_inflateEnd (err 0)</code>

It's not btrfs related but any module with zlib_inflate in it's dependency list.

**Comment by aparcar** [comment]
This issue is for a EOL release, please comment if this bug still affects you in currently supported releases.
