### ISSUE TITLE
FS#1148 - AR7 images for Fritz!Box 7170 build but do not boot

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6076]
*Styx85:*

Hi there,
I'm trying to get the latest LEDE with Kernel 4.9 up and running with an old Fritz!Box 7170 (ar7/EVA).
The images build fine but they are not booting at all.

Is someone able to help? I have tried to collect the "internet knowledge" about this device in this [[https://github.com/Styx85/OpenWRT-LEDE-for-Fritz-Box-FON-WLAN-7170|github]].
I also found some very old OpenWRT patches ([[https://dev.openwrt.org/ticket/2561|1]])([[https://dev.openwrt.org/ticket/9420|2]]) for whom I don't know if they were ever integrated in master. 
I'm not a developer myself, so I don't even know how to integrate patches to try them out.

I also created a [[https://forum.lede-project.org/t/avm-fritz-box-fon-wlan-7170-support-working-image/8304|forum thread]] if anyone has some more tips or ideas.

**Comment by Djfe** [comment]
The last build was years ago, this device is not being build anymore. This can be closed, I think @hauke

**Comment by hauke** [comment]
This device was never supported. If you or someone else want to add support for this device please create a pull request.
