### ISSUE TITLE
FS#1209 - WiFi random disconnection on WRT3200ACM

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6151]
*Zurd:*

Router: Linksys WRT3200ACM

LEDE: Powered by LuCI lede-17.01 branch (git-17.290.79498-d3f0685) / LEDE Reboot 17.01.4 r3560-79f57e422d

Kernel: 4.4.92

Forum thread: https://forum.openwrt.org/viewtopic.php?pid=369295#p369295

mwlwifi version: kmod-mwlwifi - 4.4.92+10.3.4.0.git-2017-06-06-1

Wireless radio0 is working perfectly fine but not on radio1 or radio2. There's random disconnection, can happen 3 times a day or once per 3 day. Only solution is to reboot the router. See the forum thread for more information.

**Comment by aparcar** [comment]
This issue is for a EOL release, please comment if this bug still affects you in currently supported releases.
