### ISSUE TITLE
FS#1347 - Asus WL500GP V2 reboots when you`re trying to send file

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6267]
*dormancygrace:*

Supply the following if possible:
 - Device problem occurs on
 - Software versions of OpenWrt/LEDE release, packages, etc.
 - Steps to reproduce
   
I`m using Asus WL500GP V2 with Huawei E3372s with HiLink fw (I tested stick fw too). I`ve tried all LEDE versions. You can reproduce easily, just try to attach file to letter, or send file to cloud. 99% that router will reboot.

**Comment by lynxis** [comment]
The router only contains 32MB RAM. I would guess it's due OOM (out-of-memory). I don't see how we can fix it. The current recommendation for OpenWrt is at least 64MB
