### ISSUE TITLE
FS#1394 - Add support for OWE encryption

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6329]
*charlemagnelasse:*

The WPA3 standard requires opportunistic wireless encryption (OWE) support (with optional OWE transition) for "open" APs. This is supported by hostapd trunk after enabling CONFIG_OWE and then setting OWE instead of WPA-PSK.

**Comment by aaaaalbert** [comment]
I'm suggesting to **close this issue**: OWE seems to be implemented since probably 18c6c93a3b83831a1e7d7d80c22c477412c56cb4 (2018). Evidence in this screenshot from OpenWrt 22.03.2: ![screenshot](https://user-images.githubusercontent.com/3806695/199057780-8e03f50e-3d78-4ad6-9807-f6696d0a8ec0.png)
