### ISSUE TITLE
FS#1444 - Activate CONFIG_ATH9K_HWRNG in Kernel 4.9

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6406]
*biergaizi:*

Since Linux 4.5, ath9k can be used as a random number generator using ADC register as a source of entropy. It is well-known that insufficient entropy is often a problem on routers and weakens security, using ath9k as a random number generator can greatly boost the available entropy on the routers without the need of additional measures such as haveged.

**Comment by KanjiMonster** [comment]
Closing the issue as the mentioned PR has been merged with https://github.com/openwrt/openwrt/commit/a4c0767fbc50ea50f1f0c5adfa35d1c8d347462b.
