### ISSUE TITLE
FS#873 - problems of mt7628 wifi driver on miwifi nano

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6661]
*nqsnqs:*

 I started using lede on my miwifi nano since the release of version 17.01.1. All function works well except its wireless function. 

What makes it a problem is its stability. After a random period of time(ranging from a quarter of an hour to half of a day), it suddenly disconnected. If you try to reconnect, my device shows something like "setting the network address"(varing from devices to devices). After reboot, I found something like "deauthenticated due to inactivity (timer DEAUTH/REMOVE)".  Unfortunately, I haven't found a way to reproduce the problem till now.

I thought there might be bugs on its wireless driver because on another firmware(http://downloads.pandorabox.com.cn/pandorabox/Xiaomi-Mini-R1CL/firmware/PandoraBox-ralink-mt7628-xiaomi-r1cl-squashfs-sysupgrade-r1752-20151201.bin) which is a variant of Openwrt, it works well.

There are many other problems like the inability to set channel to auto and the txpower option is of no use. But for my daily use, they may not so important compared to the connectivity problem.

Sorry for my bad English and thank you for fixing it.

**Comment by aparcar** [comment]
This issue is for a EOL release, please comment if this bug still affects you in currently supported releases.
