### ISSUE TITLE
FS#3564 - Too many connections and router ceases to pass traffic

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6679]
*binhouse:*

I'm on a Ubiquiti Edgerouter-X (ER-X) with the latest version of OpenWRT, 19.07.  Too many connections and the router ceases to pass traffic.  Cannot access the router itself either.  Lights blink but nothing happens.  Requires a hard reset.  Busy torrents will crash the router within minutes.  Regular light web browsing traffic requires at least daily resets.

**Comment by ynezz** [comment]
Try to reproduce it with latest [22.03-rc2](https://downloads.openwrt.org/releases/22.03.0-rc2/targets/) or [development snapshot](https://downloads.openwrt.org/snapshots/targets/) and report back, we can re-open the ticket.
