### ISSUE TITLE
FS#1750 - Provide notification channel for release announcements

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6711]
*azrdev:*

After installing OpenWrt on any device, I have to actively monitor the project website to know whenever a new release is available, potentially fixing security issues with my installation.

I propose creating a release-announce mailinglist used only for that purpose, readable & subscribable for everyone.

There might already be other channels offering more push-like notifications, but I didn't find any ones that are officially sanctioned  thus reliably complete.

**Comment by KanjiMonster** [comment]
An annouce mailinglist now exists: https://lists.openwrt.org/mailman/listinfo/openwrt-announce
