### ISSUE TITLE
FS#1772 - sunxi: broken sysupgrade

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6727]
*Menion:*

Hi all
With both trunk (even pre 18.06.x) 18.06.x the sysupgrade for sunxi target (verified with BananaPi and new Orange Pi PC2) does not work
Tested with both ext4 and squashfs upgrade (of course only ext4 to ext4 and squashfs to squashfs) creating a dummy file under /usr/bin that remains after reboot
First log attempting to upgrade img.gz

//**root@MenionRouter:/# sysupgrade -v /tmp/openwrt-sunxi-cortexa53-sun50i-h5-orange
pi-pc2-squashfs-sdcard.img.gz
Image metadata not found
Reading partition table from bootdisk...

gzip: stdout: Broken pipe
Reading partition table from image...
Saving config files...
/etc/config/.system.uci-AHDKKD
/etc/config/adblock
/etc/config/adblock-opkg
/etc/config/ddns
/etc/config/dhcp
/etc/config/dropbear
/etc/config/firewall
/etc/config/luci
/etc/config/luci-opkg
/etc/config/minidlna
/etc/config/mwan3
/etc/config/network
/etc/config/nlbwmon
/etc/config/ntpclient
/etc/config/openvpn
/etc/config/openvpn-opkg
/etc/config/openvpn_recipes
/etc/config/rpcd
/etc/config/squid
/etc/config/stunnel
/etc/config/system
/etc/config/ucitrack
/etc/config/ucitrack-opkg
/etc/config/uhttpd
/etc/config/uhttpd-opkg
/etc/config/upnpd
/etc/config/upnpd-opkg
/etc/config/wifi_schedule
/etc/config/wireless
/etc/dropbear/dropbear_rsa_host_key
/etc/easy-rsa/android.ovpn
/etc/easy-rsa/keys/01.pem
/etc/easy-rsa/keys/02.pem
/etc/easy-rsa/keys/ca.crt
/etc/easy-rsa/keys/ca.key
/etc/easy-rsa/keys/dh2048.pem
/etc/easy-rsa/keys/index.txt
/etc/easy-rsa/keys/index.txt-opkg
/etc/easy-rsa/keys/index.txt.attr
/etc/easy-rsa/keys/index.txt.attr.old
/etc/easy-rsa/keys/index.txt.old
/etc/easy-rsa/keys/my-Ros.crt
/etc/easy-rsa/keys/my-Ros.csr
/etc/easy-rsa/keys/my-Ros.key
/etc/easy-rsa/keys/my-Ros.p12
/etc/easy-rsa/keys/my-android.crt
/etc/easy-rsa/keys/my-android.csr
/etc/easy-rsa/keys/my-android.key
/etc/easy-rsa/keys/my-android.p12
/etc/easy-rsa/keys/my-lavoro.crt
/etc/easy-rsa/keys/my-lavoro.csr
/etc/easy-rsa/keys/my-lavoro.key
/etc/easy-rsa/keys/my-lavoro.p12
/etc/easy-rsa/keys/my-server.crt
/etc/easy-rsa/keys/my-server.csr
/etc/easy-rsa/keys/my-server.key
/etc/easy-rsa/keys/serial
/etc/easy-rsa/keys/serial-opkg
/etc/easy-rsa/keys/serial.old
/etc/easy-rsa/lavoro.ovpn
/etc/easy-rsa/openssl-1.0.0.cnf
/etc/easy-rsa/openssl-1.0.cnf
/etc/easy-rSending TERM to remaining processes ... sleep sleep ubusd askfirst logd rpcd monitor ovsdb-server monitor ovs-vswitchd netifd odhcpd minidlna uhttpd nlbwmon openvpn openvpn squid ntpd acpid hostapd hostapd miniupnpd miniupnpd[5112]: shutting down MiniUPnPd
sh dnsmasq sh
acpid: exiting
[  175.976969] device wlan0 left promiscuous mode
[  175.982039] br-lan: port 3(wlan0) entered disabled state
[  176.032358] device wlan1 left promiscuous mode
[  176.036984] br-lan: port 2(wlan1) entered disabled state
Sending KILL to remaining processes ... squid
Switching to ramdisk...
Performing system upgrade...
Reading partition table from bootdisk...
/usr/bin/zcat: exec: line 51: gzip: not found
[  181.207511] kvm: exiting hardware virtualization
0+0 records in
0+0 records out
Reading partition table from image...
Invalid partition table on /tmp/image.bs
[  181.217810] reboot: Restarting system**//

As you can see it seems that gzip is missing from the ramdisk, so the upgrade aborts. After having seen this, I first uncrompress the img.gz to img and tried again:

//**root@MenionRouter:/# sysupgrade -v /tmp/openwrt-sunxi-cortexa53-sun50i-h5-orange
pi-pc2-squashfs-sdcard.img
Reading partition table from bootdisk...
cat: write error: Broken pipe
Reading partition table from image...
Saving config files...
/etc/config/.system.uci-AHDKKD
/etc/config/adblock
/etc/config/adblock-opkg
/etc/config/ddns
/etc/config/dhcp
/etc/config/dropbear
/etc/config/firewall
/etc/config/luci
/etc/config/luci-opkg
/etc/config/minidlna
/etc/config/mwan3
/etc/config/network
/etc/config/nlbwmon
/etc/config/ntpclient
/etc/config/openvpn
/etc/config/openvpn-opkg
/etc/config/openvpn_recipes
/etc/config/rpcd
/etc/config/squid
/etc/config/stunnel
/etc/config/system
/etc/config/ucitrack
/etc/config/ucitrack-opkg
/etc/config/uhttpd
/etc/config/uhttpd-opkg
/etc/config/upnpd
/etc/config/upnpd-opkg
/etc/config/wifi_schedule
/etc/config/wireless
/etc/dropbear/dropbear_rsa_host_key
/etc/easy-rsa/android.ovpn
/etc/easy-rsa/keys/01.pem
/etc/easy-rsa/keys/02.pem
/etc/easy-rsa/keys/ca.crt
/etc/easy-rsa/keys/ca.key
/etc/easy-rsa/keys/dh2048.pem
/etc/easy-rsa/keys/index.txt
/etc/easy-rsa/keys/index.txt-opkg
/etc/easy-rsa/keys/index.txt.attr
/etc/easy-rsa/keys/index.txt.attr.old
/etc/easy-rsa/keys/index.txt.old
/etc/easy-rsa/keys/my-Ros.crt
/etc/easy-rsa/keys/my-Ros.csr
/etc/easy-rsa/keys/my-Ros.key
/etc/easy-rsa/keys/my-Ros.p12
/etc/easy-rsa/keys/my-android.crt
/etc/easy-rsa/keys/my-android.csr
/etc/easy-rsa/keys/my-android.key
/etc/easy-rsa/keys/my-android.p12
/etc/easy-rsa/keys/my-lavoro.crt
/etc/easy-rsa/keys/my-lavoro.csr
/etc/easy-rsa/keys/my-lavoro.key
/etc/easy-rsa/keys/my-lavoro.p12
/etc/easy-rsa/keys/my-server.crt
/etc/easy-rsa/keys/my-server.csr
/etc/easy-rsa/keys/my-server.key
/etc/easy-rsa/keys/serial
/etc/easy-rsa/keys/serial-opkg
/etc/easy-rsa/keys/serial.old
/etc/easy-rsa/lavoro.ovpn
/etc/easy-rsa/openssl-1.0.0.cnf
/etc/easy-rsa/opensslSending TERM to remaining processes ... sleep sleep ubusd askfirst logd rpcd monitor ovsdb-server monitor ovs-vswitchd netifd odhcpd minidlna uhttpd nlbwmon openvpn openvpn squid ntpd acpid hostapd hostapd miniupnpd miniupnpd[5126]: shutting down MiniUPnPd
sh sh dnsmasq
acpid: exiting
[   92.437752] device wlan1 left promiscuous mode
[   92.442327] br-lan: port 2(wlan1) entered disabled state
[   92.448910] device wlan0 left promiscuous mode
[   92.453768] br-lan: port 3(wlan0) entered disabled state
Sending KILL to remaining processes ... squid
Switching to ramdisk...
Performing system upgrade...
Reading partition table from bootdisk...
cat: write error: Broken pipe
Reading partition table from image...
1016+0 records in
1016+0 records out
Writing image to /dev/mmcblk0p1...
cat: write error: Broken pipe
40960+0 records in
20+0 records out
Writing image to /dev/mmcblk0p2...
38223+1 records in
18+1 records out
Writing new UUID to /dev/mmcblk0...
4+0 records in
4+0 records out
Upgrade completed
Rebooting system...
umount: can't unmount /dev: Resource busy
umount: can't unmount /tmp: Resource busy**//

Here something happen, but I get this write error due to broken pipe happening randomly in one or more of the mmc write. The result is a working SD card, I see the config being restored (even if with timestamp issue)

//**[    9.963481] mount_root: switching to f2fs overlay
- config restore -
tar: etc/config/.system.uci-AHDKKD: time stamp 2017-08-21 21:02:25 is 1503349334.873834079 s in the future
tar: etc/config/adblock: time stamp 2018-03-02 18:15:32 is 1520014521.872032829 s in the future
tar: etc/config/adblock-opkg: time stamp 2018-02-24 14:13:16 is 1519481585.871617621 s in the future
tar: etc/config/ddns: time stamp 2018-03-02 08:48:43 is 1519980512.871290329 s in the future**//

But the temp file written in the overlay is still there:

//**root@MenionRouter:/# cd /usr/bin
root@MenionRouter:/usr/bin# ls foo
foo
root@MenionRouter:/usr/bin#**//

So apparently there are two issue (maybe correlated): there is no gzip in the ramdisk which prevent img.gz to work and the overlay filesystem that won't get reset
Bye

**Comment by ynezz** [comment]
Too old.
