### ISSUE TITLE
FS#1844 - R7800 ipv6 connectivity

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6777]
*mario-ragucci-sp:*

Hello,

ipv6 does not work properly on my Netgear R7800. I am running OpenWrt 18.6.1. The device gets a ipv6 address assigned, but I cannot ping any ipv6 address. Furthermore, I get the following error:
# ping6 google.de
PING google.de (2607:f8b0:4000:817::2003): 56 data bytes
ping6: sendto: Permission denied

After running the command
# tcpdump -i eth0 -vv
for some time, ipv6 connectivity works, I am able to ping an ipv6 address, also pinging from another host and establishing v6 connections is working. 
# ping6 google.de
PING google.de (2607:f8b0:4000:817::2003): 56 data bytes
64 bytes from 2607:f8b0:4000:817::2003: seq=0 ttl=51 time=118.360 ms
64 bytes from 2607:f8b0:4000:817::2003: seq=1 ttl=51 time=118.626 ms

However, after some time, this is not working anymore and I have to restart the tcpdump command.

This must be a device specific issue, since my other Netgear Router (WNDR3700) running 18.06.1 is working flawlessly.

**Comment by aparcar** [comment]
This issue is for a EOL release, please comment if this bug still affects you in currently supported releases.
