### ISSUE TITLE
FS#1868 - kmod-netem: Unable to handle kernel NULL pointer dereference at virtual address 00000078

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6786]
*LGA1150:*

Device is WRT1900ACv2, kernel version is 4.14.71
It is simple to reproduce, just invoke netem such as `tc qdisc add dev eth1 root netem delay 100ms`, it will crash immediately

**Comment by ynezz** [comment]
Try to reproduce it with latest [22.03-rc2](https://downloads.openwrt.org/releases/22.03.0-rc2/targets/) or [development snapshot](https://downloads.openwrt.org/snapshots/targets/) and report back, we can re-open the ticket.
