### ISSUE TITLE
FS#1908 - Editing an Existing Task, At Least the Tags and Title, or Seperating the Tags

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6821]
*moriel5:*

When posting a feature request for the NETGEAR DM200 on OpenWRT, I have tagged it incorrectly (adding commas in between tags, since I am used to doing this on other systems similar to Flyspray), and then I saw that I cannot edit my own post.
Also, I wanted to fix the title (capitalizing letters where necessary, and likewise, the opposite).

Can editing existing tasks one had authored be possible in the future, or at least improving the tagging system, to enable fixing such mistakes?

**Comment by KanjiMonster** [comment]
This is a bug report for the obsoleted flyspray instance itself, so does not apply here.
