### ISSUE TITLE
FS#1914 - lua tonumber get wrong value

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6825]
*ptpt52:*

on x86_64
build base openwrt current master HEAD

problem:

lua -e 'print("42949672961111"+1)'
1112
lua -e 'print("42949672951111"+1)'
42949672951112

lua tonumber get wrong.

problem not happens on arm/mips but only x86_64
x86_generic not tested

**Comment by hauke** [comment]
The problem was fixed. For me it works in a x86/64 image:
````
root@OpenWrt:/# lua -e 'print("42949672961111"+1)'
42949672961112
root@OpenWrt:/# lua -e 'print("42949672951111"+1)'
42949672951112
root@OpenWrt:/# lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio (double int32)
````

I used this configuration:
````
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_lua5.3=y
````

It was probably fixed here: 4bb9af48ca36605424c57b6af27dd5e5c827395f
