### ISSUE TITLE
FS#2112 - Ralink MT7620a + MT7610e evaluation board

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6962]
*dbrb2:*

I have a device that identifies as a MT7620A + MT7610e EVB: 

<code>
cat /proc/cpuinfo
system type             : MediaTek MT7620A ver:2 eco:6
machine                 : Ralink MT7620a + MT7610e evaluation board
processor               : 0
cpu model               : MIPS 24KEc V5.0
BogoMIPS                : 385.84
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
</code>

I have been trying to load various openWrt releases onto it. None have been successful, and using the latest release that seems to match this hardware:

https://downloads.openwrt.org/releases/18.06.2/targets/ramips/mt7620/openwrt-18.06.2-ramips-mt7620-mt7620a_mt7610e-squashfs-sysupgrade.bin

I can see, from dmesg, that there is a problem with SPI: 

<code>Loading: Got ARP REPLY, set server/gtwy eth addr (1c:39:47:da:8f:4b)
Got it
#################################################################
	 #################################################################
	 #################################################################
	 #################################################################
	 #################################################################
	 #################################################################
	 #################################################################
	 #################################################################
	 #################################################################
	 #################################################################
	 #################################################################
	 ######################################################
done
Bytes transferred = 3932340 (3c00b4 hex)
NetBootFileXferSize= 003c00b4
Automatic boot of image at addr 0x80A00000 ...
## Booting image at 80a00000 ...
   Image Name:   MIPS OpenWrt Linux-4.14.95
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    1437278 Bytes =  1.4 MB
   Load Address: 80000000
   Entry Point:  80000000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK
No initrd
## Giving linux memsize in MB, 128

Starting kernel ...

[    0.000000] Linux version 4.14.95 (buildbot@builds-03.infra.lede-project.org) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r7627-753531d)) #0 Mon Jan 28 08:54:32 2019
[    0.000000] Board has DDR2
[    0.000000] Analog PMU set to hw control
[    0.000000] Digital PMU set to hw control
[    0.000000] SoC Type: MediaTek MT7620A ver:2 eco:6
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019650 (MIPS 24KEc)
[    0.000000] MIPS: machine is Ralink MT7620A evaluation board
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 08000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] random: get_random_bytes called from 0x8042472c with crng_init=0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32512
[    0.000000] Kernel command line: console=ttyS0,57600 rootfstype=squashfs,jffs2
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=0003f200
[    0.000000] Readback ErrCtl register=0003f200
[    0.000000] Memory: 125216K/131072K available (3590K kernel code, 178K rwdata, 464K rodata, 176K init, 214K bss, 5856K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 256
[    0.000000] CPU Clock: 580MHz
[    0.000000] clocksource: systick: mask: 0xffff max_cycles: 0xffff, max_idle_ns: 583261500 ns
[    0.000000] systick: enable autosleep mode
[    0.000000] systick: running - mult: 214748, shift: 32
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6590553264 ns
[    0.000012] sched_clock: 32 bits at 290MHz, resolution 3ns, wraps every 7405115902ns
[    0.015477] Calibrating delay loop... 385.84 BogoMIPS (lpj=1929216)
[    0.087712] pid_max: default: 32768 minimum: 301
[    0.097140] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.110157] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.129997] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.149480] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.161658] pinctrl core: initialized pinctrl subsystem
[    0.173277] NET: Registered protocol family 16
[    0.184832] rt2880-pinmux pinctrl: error claiming hogs: -22
[    0.195821] rt2880-pinmux pinctrl: could not claim hogs: -22
[    0.207099] rt2880-pinmux: probe of pinctrl failed with error -22
[    0.220550] Can't analyze schedule() prologue at 8037d498
[    0.231473] mt7620-pci 10140000.pcie: could not find pctldev for node /pinctrl/pcie, deferring probe
[    0.266577] rt2880_gpio 10000600.gpio: registering 24 gpios
[    0.277609] rt2880_gpio 10000600.gpio: registering 24 irq handlers
[    0.293963] clocksource: Switched to clocksource systick
[    0.305616] NET: Registered protocol family 2
[    0.315188] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.328966] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.341553] TCP: Hash tables configured (established 1024 bind 1024)
[    0.354324] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.365831] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.378529] NET: Registered protocol family 1
[    0.389802] rt-timer 10000100.timer: maximum frequency is 1220Hz
[    0.402541] Crashlog allocated RAM at address 0x3f00000
[    0.414676] workingset: timestamp_bits=30 max_order=15 bucket_order=0
[    0.433435] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.444930] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.474961] io scheduler noop registered
[    0.482605] io scheduler deadline registered (default)
[    0.493790] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.508955] of_serial 10000c00.uartlite: could not find pctldev for node /pinctrl/uartlite, deferring probe
[    0.528624] cacheinfo: Failed to find cpu0 device node
[    0.538715] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.551498] spi-rt2880 10000b00.spi: could not find pctldev for node /pinctrl/spi, deferring probe
[    0.569831] libphy: Fixed MDIO Bus: probed
[    0.578410] mtk_soc_eth 10100000.ethernet: could not find pctldev for node /pinctrl/ephy, deferring probe
[    0.597719] rt2880_wdt 10000120.watchdog: Initialized
[    0.609110] NET: Registered protocol family 10
[    0.628789] Segment Routing with IPv6
[    0.636102] NET: Registered protocol family 17
[    0.644844] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    0.670578] 8021q: 802.1Q VLAN Support v1.8
[    0.679558] mt7620-pci 10140000.pcie: could not find pctldev for node /pinctrl/pcie, deferring probe
[    0.697775] of_serial 10000c00.uartlite: could not find pctldev for node /pinctrl/uartlite, deferring probe
[    0.717130] spi-rt2880 10000b00.spi: could not find pctldev for node /pinctrl/spi, deferring probe
[    0.734937] mtk_soc_eth 10100000.ethernet: could not find pctldev for node /pinctrl/ephy, deferring probe
[    0.755186] Warning: unable to open an initial console.
[    0.766222] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    0.781014] Please append a correct "root=" boot option; here are the available partitions:
[    0.797592] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    0.814958] Rebooting in 1 seconds..
</code>

This seems very similar to the issue reported here: 

https://bugs.openwrt.org/index.php?do=details&task_id=1515&opened=1266&status%5B0%5D=

Though that was for slightly different hardware. 

Any ideas...?

**Comment by 981213** [comment]
Someone needs to add proper device supports for new devices. EVB firmware not guaranteed to work on a random router.
