### ISSUE TITLE
FS#2371 - Multicast/IGMP/DSA Issues

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7217]
*tiagogaspar8:*

 - Device problem occurs on

Linksys WRT3200ACM

 - Software versions of OpenWrt/LEDE release, packages, etc.

Latest trunk (with 4.19 kernel)

I have enabled DSA in my router with the kernel version 4.14, and it worked well, but since the kernel was bumped to 4.19 DSA has been giving some issues, namely:

 - When I add a interface, for example a DHCP client and select for the interface wan.12 OpenWRT crashes and bootloops until it reboots to the last system. After some testing I found out that if I added a interface connected to wan and thern connect the mentioned DHCP client interface to wan.12 the system doesn't crash

 -When I have the system working and connect a IPTV STB to the lan interface, with the exact configuration as in kernel 4.14 the TV works for a while but then image stops. After some testing found out that only the channel that stopped wouldn't work, while other channels worked, until they stopped working (the same issue as the first channel) and it goes on and on and on until either something (I don't know what) times out or I restart the router.

This only happened after the kernel 4.14 bump, and I believe this issue also happens with Turris omnia devices.
If you need I'm currently able to test patches as you need.
My question is, Is this a OpenWRT bug or a device drive issue that must be reported to the kernel develp team?
Either way I'm posting the same in the forums.

**Comment by tiagogaspar8** [comment]
This can be closed
