### ISSUE TITLE
FS#2596 - Support using environment variable CCACHE_DIR to determine the CCACHE_DIR to use for a build

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7424]
*mike-meshplusplus:*

Right now, the CCACHE_DIR is set unconditionally to ${STAGING_DIR}/ccache.

This is great if you're going to have a single build tree, but for large team that are working closely together on an OpenWRT based firmware, where multiple development branches might be in use simultaneously, this is wasteful.

At least in my environment, I want to set the ccache directory to be outside of the build tree, so that multiple build trees can share a cache.

Because OpenWRT sets this variable unconditionally, instead of respecting the external environment's CCACHE_DIR, or even allowing for the path to be set in .config, I have to patch the build tree to set the CCACHE_DIR that I want to use.

**Comment by Ansuel** [comment]
This was handled a lot of time ago! We can close this
