### ISSUE TITLE
FS#2675 - small fix for WPA3

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7478]
*Josh4300:*

There is a error in readme for 19.07:

<code>
Highlights in OpenWrt 19.07
   * WPA3 configuration support
     * Install wpad-openssl or wpad-wolfssl for WPA3 support
                               ^^^^^^^^^^^^
</code>

this is incorrect. I wasted some hours trying to get WPA3 to work with wpad-wolfssl and failed, apparently WPA3 only works with wpad-openssl.

**please remove mention of wpad-woflssl for WPA3 in readme.**

Others have encountered the same problem, based on the same mistake in readme:

[1]

https://forum.openwrt.org/t/problems-trying-out-wpa3/49249/3

wolfssl didn't work -> "I have changed to use wpad-openssl and it seems to work."

[2]

https://forum.openwrt.org/t/wpa3-wolfssl-fail-openssl-success/50161

wolfssl - fails, openssl - works

[3]

https://forum.openwrt.org/t/no-option-in-gui-to-set-wpa3-auth/45652/6

"It seems like wpad-openssl is working in general better then wpad-wolfssl"

[4]

https://forum.openwrt.org/t/wpa3-support-in-openwrt/10554/115

"many reports of better success on openssl rather than wolfssl"

**Comment by 981213** [comment]
WPA3 on wpad-wolfssl works now. Closing this ancient issue.
