### ISSUE TITLE
FS#2696 - [ramips/mt7621] Sysupgrade not working for master images

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7491]
*Borromini:*

Recent builds from master seem to have broken sysupgrade on mt7621. I have observed this on the following devices:
- DIR-860L rev B1
- DIR-878 rev A1 (pull request [[https://github.com/openwrt/openwrt/pull/2588|here]])

It first happened on the DIR-878 A1, where I flashed the author's image and was unable to switch to either newer master builds or 19.07 builds. I then verified this on the DIR-860L, and it showed the same behaviour.

Sysupgrade does not show any errors. It closes all pending sessions and seems to proceed normally, but after a reboot the firmware has not been upgraded.

**Comment by Djfe** [comment]
@Borromini this is fixed, right?
Atleast I can confirm, that I recently flashed a DIR-860L rev B1 using sysupgrade with a recent firmware and it worked.

**Comment by Borromini** [comment]
Yes this can be closed, I sysupgraded my DIR-860L B1 just yesterday (both before and after 22.03 images).

**Comment by Borromini** [comment]
@openwrt-bot Please close.

**Comment by Djfe** [comment]
@hauke in response to your answer on IRC:
I have no clue, which commit fixed it (I tried looking for a commit).
Neither OP nor me can reproduce this in the current release, so it's definitely fixed.
