### ISSUE TITLE
FS#2700 - nettle fails to compile on ARMEB

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7492]
*neheb:*

https://downloads.openwrt.org/snapshots/faillogs/armeb_xscale/base/nettle/compile.txt

This also prevents dnsmasq from being compiled.

The error is here: https://github.com/gnutls/nettle/blob/master/arm/memxor.asm#L148

Passing --disable-assembler works, but is probably not ideal.

**Comment by KanjiMonster** [comment]
This was fixed with https://github.com/openwrt/openwrt/commit/c2ef6c2148079eeed4076de9062e86c5e0ba9c3e.
