### ISSUE TITLE
FS#2792 - lantiq DSL statuistics and diagnostics do not report G.INP Retransmission counters

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7595]
*moeller0:*

OpenWrt 19.07.1 on BT HomeHub5A (lantiq vrx200) the dsl stats report tool (ltq-vdsl-app_4.17.18.6-2_mips_24kc.ipk) and the matching kerel module (kmod-ltq-vdsl-vr9-mei_4.14.167+1.5.17.6-4_mips_24kc.ipk) do not report ITU G.998.4 Retransmission counts (on lines using G.INP retransmissions. It turns out that adding:
CONFIGURE_ARGS += \                                                                                                                 
        --enable-dsl-pm-retx-counters \                                                                                             
        --enable-dsl-pm-retx-thresholds    

to openwrt/package/kernel/lantiq/ltq-vdsl/Makefile and openwrt/package/network/config/ltq-vdsl-app/Makefile and rebuilding yields a working ReTx counter report:

root@BTHH5A:~# . /lib/functions/lantiq_dsl.sh ; dsl_cmd rtsg 0
nReturn=0 nDirection=0 nRxCorruptedTotal=0 nRxUncorrectedProtected=0 nRxRetransmitted=0 nRxCorrected=0 nTxRetransmitted=3
root@ BTHH5A:~# . /lib/functions/lantiq_dsl.sh ; dsl_cmd rtsg 1
nReturn=0 nDirection=1 nRxCorruptedTotal=7114893 nRxUncorrectedProtected=6171968 nRxRetransmitted=0 nRxCorrected=942925 nTxRetransmitted=9228892

At least in Germany the incumbent uses G.998.4 Retransmission, not only do deal with impulse noise, but also as a diagnostic counters for its Dynamik Link/Spektrum Management tool that based on these and other counters will limit the maximum perissable Sync for each line to optimize lik stability. It would be really great if stock OpenWrt builds would alow to report these values and I would like to propose to change the makefiles as shown above.

**Comment by xdarklight** [comment]
As far as I can tell this has been fixed with 48162e4c0c85a7f64d9007565bf5be2c7ace3ada which will go into OpenWrt 22.x

**Comment by moeller0** [comment]
Can be closed then!
