### ISSUE TITLE
FS#2809 - brcm63xx: ssb: b43-pci-bridge: wifi broken: Speedport W 303V Type B

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7608]
*everloop2:*

Device problem occurs on: [[https://openwrt.org/toh/t-com/spw303v-b|Speedport W 303V Type B]]

Software versions of OpenWrt/LEDE release: since kernel 4.x (OpenWrt 15.05)

bootlog:

<code>
PCI: Enabling device 0000:00:01.0 (0000 -> 0002)
ssb: Found chip with id 0x4322, rev 0x01 and package 0x09
ssb: WARNING: Using fallback SPROM failed (err -2)
ssb: Failed to register PCI version of SSB with error -2
b43-pci-bridge: probe of 0000:00:01.0 failed with error -2
</code>

[[https://openwrt.org/toh/t-com/spw303v-b#openwrt_snapshot_08012020|full bootlog]]

tried fixes:

  * build/enable all SSB kernel and OpenWrt modules
  * test all compatible broadcom wifi modules/versions supported by OpenWrt

**Comment by Djfe** [comment]
duplicate of #7609
