### ISSUE TITLE
FS#2874 - No squashfs image for tplink tiny

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7662]
*howard0su:*

Check http://downloads.openwrt.org/snapshots/targets/ath79/tiny/ here. All tplink models only have initramfs images, while other models have the right images.

pqi_air-pen-initramfs-kernel.bin	
pqi_air-pen-squashfs-sysupgrade.bin
pqi_air-pen.json	
tplink_tl-mr10u-initramfs-kernel.bin	
tplink_tl-mr3020-v1-initramfs-kernel.bin	
tplink_tl-mr3040-v2-initramfs-kernel.bin
tplink_tl-mr3220-v1-initramfs-kernel.bin

**Comment by 981213** [comment]
Not a bug.
