### ISSUE TITLE
FS#2886 - Netgear R6260: mtd partition "factory" seem wrong

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7668]
*damien:*

* Board: [[https://openwrt.org/toh/hwdata/netgear/netgear_r6260|R6260]]

* Problems:
After building OpenWrt from git and flash my new R6260 board, wireless
is unusable.
There no data at the start of factory partition (/dev/mtd5).

* Workaround:
Moving forward the factory partition at the first useful byte
(from 0x4600000 to 0x4620000) make wireless work. ([[https://github.com/openwrt/openwrt/blob/master/target/linux/ramips/dts/mt7621_netgear_sercomm_chj.dtsi#L145|defined here]])

**Comment by Djfe** [comment]
@hauke this was fixed by https://github.com/openwrt/openwrt/pull/10038 and can be closed.
