### ISSUE TITLE
FS#2889 - TP-Link TL-WR841 snpshot ath79 kernel 5.4 error : ag71xx: probe of 19000000.eth failed with error -2

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7674]
*sapino:*

problem is : Failed to connect to the switch !
 only happen with kernel 5.4, kernel 4.19 is fine

<code>U-Boot 1.1.4 (Nov 16 2009 - 09:06:24)

AP93 (ar7240) U-boot
DRAM:
sri
#### TAP VALUE 1 = 8, 2 = 8
32 MB
id read 0x100000ff
flash size 4194304, sector count = 64
Flash:  4 MB
Using default environment

Hn:    serial
Out:   serial
Err:   serial
Net:   ag7240_enet_initialize...
No valid address in Flash. Using fixed address
: cfg1 0xf cfg2 0x7014
dth0: 00:03:7f:09:0b:ad
eth0 up
No valid address in Flash. Using fixed address
: cfg1 0xf cfg2 0x7214
eth1: 00:03:7f:09:0b:ad
ATHRS26: resetting s26
ATHRS26: s26 reset done
eth1 up
eth0, eth1
Autobooting in 1 seconds
## Booting image at 9f020000 ...
   Uncompressing Kernel Image ... @K

Starting kernel ...

OpenWrt kernel loader for AR7XXX/AR9XXX
Copyright (C) 2011 Gabor Juhos <juhosg@openwrt.org>
Looking for OpenWrt image... found at 0xbf022000
Decompressing kernel... done!
Ptarting kernel at 80060000...

Linux version 5.4.22 (huhu@bikom) (gcc version 8.3.0 (OpenWrt GCC 8.3.0 r11816-d5ede68f8b)) #0 Thu Mar 5 11:53:50 2020
printk: bootconsole [early0] enabled
CPU0 revision is: 00019374 (MIPS 24Kc)
LIPS: machine is TP-Link TL-WR841N/ND v5/v6
SoC: Atheros AR7240 rev 2
Initrd not found or empty - disabling initrd
Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
Zone ranges:
  Normal   [mem 0x0000000000000000-0x0000000001ffffff]
Movable zone start for each node
Early memory node ranges
  node   0: [mem 0x0000000000000000-0x0000000001ffffff]
Initmem setup node 0 [mem 0x0000000000000000-0x0000000001ffffff]
Built 1 zonelists, mobility grouping on.  Total pages: 8128
Kernel command line: console=ttyS0,115200 rootfstype=squashfs,jffs2
Dentry cache hash table entries: 4096 (order: 2, 16384 bytes, linear)
Inode-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
Writing ErrCtl register=00000000
Readback ErrCtl regist"er=00000000
mem auto-init: stack:off, heap alloc:off, heap free:off
Memory: 27372K/32768K available (3175K kernel code, 134K rwdata, 372K rodata, 1176K init, 182K bss, 5396K reserved, 0K cma-reserved)
SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
NR_IRQS: 51
random: get_random_bytes called from 0x803fa9ac with crng_init=0
CPU clock: 400.000 MHz
clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 9556302233 ns
sched_clock: 32 bits at 200MHz, resolution 5ns, wraps every 10737418237ns
Calibrating delay loop... 265.42 BogoMIPS (lpj=1327104)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
futex hash table entries: 256 (order: -1, 3072 bytes, linear)
pinctrl core: initialized pinctrl subsystem
NET: Registered protocol family 16
PCI host bridge /ahb/apb/pcie-controller@180c0000 ranges:
 MEM 0x0000000010000000..0x0000000013ffffff
  IO 0x0000000000000000..0x0000000000000000
PCI host bridge to bus 0000:00
pci_bus 0000:00: root bus resource [mem 0x10000000-0x13ffffff]
pci_bus 0000:00: root bus resource [io  0x0000]
pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
pci 0000:00:00.0: [168c:002a] type 00 class 0x028000
pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x0000ffff 64bit]
pci 0000:00:00.0: supports D1
pci 0000:00:00.0: PME# supported from D0 D1 D3hot
pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
pci 0000:00:00.0: BAR 0: assigned [mem 0x10000000-0x1000ffff 64bit]
clocksource: Switched to clocksource MIPS
NET: Registered protocol family 2
tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
TCP: Hash tables configured (established 1024 bind 1024)
UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
NET: Registered protocol family 1
PCI: CLS 0 bytes, default 32
workingset: timestamp_bits=30 max_order=13 bucket_order=0
squashfs: version 4.0 (2009/01/31) Phillip Lougher
jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
pinctrl-single 18040028.pinmux: 64 pins, size 8
Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
printk: console [ttyS0] disabled
18020000.uart: ttyS0 at MMIO 0x18020000 (irq = 9, base_baud = 12500000) is a 16550A
printk: console [ttyS0] enabled
printk: console [ttyS0] enabled
printk: bootconsole [early0] disabled
printk: bootconsole [early0] disabled
spi-nor spi0.0: s25sl032p (4096 Kbytes)
3 fixed-partitions partitions found on MTD device spi0.0
Creating 3 MTD partitions on "spi0.0":
0x000000000000-0x000000020000 : "u-boot"
0x000000020000-0x0000003f0000 : "firmware"
2 tplink-fw partitions found on MTD device firmware
Creating 2 MTD partitions on "firmware":
0x000000000000-0x000000136bf2 : "kernel"
0x000000136bf4-0x0000003d0000 : "rootfs"
mtd: device 3 (rootfs) set to be root filesystem
0 squashfs-split partitions found on MTD device rootfs
0x000000370000-0x0000003d0000 : "rootfs_data"
0x0000003f0000-0x000000400000 : "art"
libphy: Fixed MDIO Bus: probed
ag71xx: probe of 19000000.eth failed with error -2
ag71xx: probe of 1a000000.eth failed with error -2
NET: Registered protocol family 17
8021q: 802.1Q VLAN Support v1.8
VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
Freeing unused kernel memory: 1176K
This architecture does not have kernel memory protection.
Run /sbin/init as init process
random: fast init done
init: Console is alive
init: - watchdog -
hmodloader: loading kernel modules from /etc/modules-boot.d/*
kmodloader: done loading kernel modules from /etc/modules-boot.d/*
init: - preinit -
random: jshn: uninitialized urandom read (4 bytes read)
random: jshn: uninitialized urandom read (4 bytes read)
random: jshn: uninitialized urandom read (4 bytes read)
Failed to connect to the switch. Use the "list" command to see which switches are available.
Failed to connect to the switch. Use the "list" command to see which switches are available.
Failed to connect to the switch. Use the "list" command to see which switches are available.
Failed to connect to the switch. Use the "list" command to see which switches are available.
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
trandom_read: 2 callbacks suppressed
random: procd: uninitialized urandom read (4 bytes read)
jffs2: notice: (362) jffs2_build_xattr_subsystem: complete building xattr subsystem, 15 of xdatum (0 unchecked, 8 orphan) and 17 of xref (8 dead, 0 orphan) found.
mount_root: switching to jffs2 overlay
`verlayfs: upper fs does not support tmpfile.
urandom-seed: Seeding with /etc/urandom.seed
procd: - early -
procd: - watchdog -
procd: - watchdog -
procd: - ubus -
random: ubusd: uninitialized urandom read (4 bytes read)
random: ubusd: uninitialized urandom read (4 bytes read)
random: ubusd: uninitialized urandom read (4 bytes read)
procd: - init -
Please press Enter to activate this console.
kmodloader: loading kernel modules from /etc/modules.d/*
tun: Universal TUN/TAP device driver, 1.6
Loading modules backported from Linux version v5.4-rc8-0-gaf42d3466bdc
Backport generated by backports.git v5.4-rc8-1-0-g368e8c51
xt_time: kernel timezone is -0000
ath: phy0: Ignoring endianness difference in EEPROM magic bytes.
ieee80211 phy0: Atheros AR9280 Rev:2 mem=0xb0000000, irq=14
kmodloader: done loading kernel modules from /etc/modules.d/*
urngd: v1.0.2 started.
random: crng init done
random: 1 urandom warning(s) missed due to ratelimiting

</code>

**Comment by 981213** [comment]
It's already fixed.
