### ISSUE TITLE
FS#1449 - mt7621 - zbt3526 - mtk_soc_eth -> port 3 link up & down all the time :(

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7701]
*camel:*

current runknothing installed only use newest trunk from 20.3.2018

<code>
Tue Mar 20 03:10:54 2018 kern.info kernel: [ 1503.788203] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:10:56 2018 kern.info kernel: [ 1506.347573] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:11:04 2018 kern.info kernel: [ 1513.895790] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:11:08 2018 kern.info kernel: [ 1517.832424] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:11:13 2018 kern.info kernel: [ 1522.910834] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:11:15 2018 kern.info kernel: [ 1525.401597] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:11:21 2018 kern.info kernel: [ 1530.798474] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:11:23 2018 kern.info kernel: [ 1533.389966] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:12:53 2018 kern.info kernel: [ 1623.131837] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:12:57 2018 kern.info kernel: [ 1626.897454] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:13:20 2018 kern.info kernel: [ 1650.086813] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:13:22 2018 kern.info kernel: [ 1652.596397] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:14:10 2018 kern.info kernel: [ 1699.974606] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:14:12 2018 kern.info kernel: [ 1702.533339] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:14:24 2018 kern.info kernel: [ 1714.114599] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:14:28 2018 kern.info kernel: [ 1717.966606] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:14:34 2018 kern.info kernel: [ 1724.591850] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:14:37 2018 kern.info kernel: [ 1727.206909] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:15:10 2018 kern.info kernel: [ 1759.837908] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:15:12 2018 kern.info kernel: [ 1762.372712] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:15:37 2018 kern.info kernel: [ 1787.098031] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:15:41 2018 kern.info kernel: [ 1790.955159] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:15:43 2018 kern.info kernel: [ 1792.826106] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:15:45 2018 kern.info kernel: [ 1795.329556] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Tue Mar 20 03:16:25 2018 kern.info kernel: [ 1835.067930] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Tue Mar 20 03:16:28 2018 kern.info kernel: [ 1837.877538] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
</code>

that is new .. not sure, but i guess, that was not existing on images from february ..

**Comment by ynezz** [comment]
Try to reproduce it with latest [22.03-rc2](https://downloads.openwrt.org/releases/22.03.0-rc2/targets/) or [development snapshot](https://downloads.openwrt.org/snapshots/targets/) and report back, we can re-open the ticket.
