### ISSUE TITLE
FS#2986 - Functionality broken by migration to DSA for Ubiquiti ER-X

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7756]
*mar-kolya:*

Supply the following if possible:
 - Ubiquiti ER-X
 - Trunk
 - Build trunk of Openwrt and try to configure vlan enabled interfaces on an embedded switch.

Hi.

I have Ubiquiti ER-X which I have been using for quite a while and it was working just fine.
I was using it to route traffic from external internet connections to a 'trunk' port connected to a different OpenWrt device used as access point. So to clarify: I have one of the swich ports configured as 'tagged' ('tunk') for multiple vlans.

Unfortunately commit 30644bc579e771e4b6dcc165ca966124e0259e1e that switched this device to use DSA for switch configuration have completely broken this setup.

And I'm not talking abut soft bricking - that was to be expected. Unfortunately DSA doesn't provide functionality that was available in swconfig for years. Namely it seems to be impossible to configure switch ports to be 'tagged'.

It looks like DSA is considered to be 'the future' but unfortunately it doesn't see to be ready for prime time - it seems to be impossible to use DSA enabled devices in configurations that were perfectly possible before.

**Comment by ynezz** [comment]
Try to reproduce it with latest [22.03-rc2](https://downloads.openwrt.org/releases/22.03.0-rc2/targets/) or [development snapshot](https://downloads.openwrt.org/snapshots/targets/) and report back, we can re-open the ticket.
