### ISSUE TITLE
FS#2987 - LEDs for WLAN and DSL do not work right.

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7757]
*jospezial:*

Supply the following if possible:
 - Device problem occurs on VGV7510KW22 (o2 Box 6431)
 - Software versions of OpenWrt: Trunk, snapshots,releases
 - Steps to reproduce:
After boot the WLAN LED does not switch on when WLAN is running.
wifi down and wifi up then the WLAN LED does switch on.
After restarting the LED service the the WLAN LED and DSL LED does not switch back on.

<code>/etc/init.d/led restart
setting up led wifi
setting up led dsl
setting up led internet</code>

Internet LED works as expected.
My workaround for some years was to use netdev wlan0 as trigger.
After setting this I can't change it back to the default setting phy0radio as this is not available in LUCI.

**Comment by maurerle** [comment]
Unfortunately, the previous PR only fixed the WAN LED - so the wifi LED needed some rework too, but works now.
It is fixed in https://github.com/openwrt/openwrt/pull/11749 which is already merged
