### ISSUE TITLE
FS#2996 - nanopi air cannot start in kernel 5.4.31

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7765]
*luckybike:*

device: nanopi air
steps:
  1. "git check" to get the last trunk
  2. "make menuconfig" select the device "nanopi air"
  3. then "make" to get the rom and dd it into TF card
  4. power on and you will see stop at "Starting kernel ..."

here is my system log:
<code>
U-Boot SPL 2020.01 (Apr 09 2020 - 20:09:21 +0000)
DRAM: 512 MiB
Trying to boot from MMC1

U-Boot 2020.01 (Apr 09 2020 - 20:09:21 +0000) Allwinner Technology

CPU:   Allwinner H3 (SUN8I 1680)
Model: FriendlyARM NanoPi NEO
DRAM:  512 MiB
MMC:   mmc@1c0f000: 0
Loading Environment from FAT... *** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   phy interface0

Error: ethernet@1c30000 address not set.
No ethernet found.

starting USB...
Bus usb@1c1a000: USB EHCI 1.00
Bus usb@1c1a400: USB OHCI 1.0
Bus usb@1c1d000: USB EHCI 1.00
Bus usb@1c1d400: USB OHCI 1.0
scanning bus usb@1c1a000 for devices... 1 USB Device(s) found
scanning bus usb@1c1a400 for devices... 1 USB Device(s) found
scanning bus usb@1c1d000 for devices... 1 USB Device(s) found
scanning bus usb@1c1d400 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
377 bytes read in 2 ms (183.6 KiB/s)
## Executing script at 43100000
3078032 bytes read in 142 ms (20.7 MiB/s)
19497 bytes read in 3 ms (6.2 MiB/s)
## Booting kernel from Legacy Image at 42000000 ...
   Image Name:   ARM OpenWrt Linux-5.4.31
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    3077968 Bytes = 2.9 MiB
   Load Address: 40008000
   Entry Point:  40008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 43000000
   Booting using the fdt blob at 0x43000000
EHCI failed to shut down host controller.
   Loading Kernel Image
   Using Device Tree in place at 43000000, end 43007c28

Starting kernel ...
</code>

**Comment by ynezz** [comment]
Too old.
