### ISSUE TITLE
FS#3023 - Warning CPU

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7786]
*compassnet:*

Device: Mikrotik RB750Gr3
Software: OpenWrt 19.07.2 (with no default package updates yet)
Installed Packages: installed_packages.txt (attached)
How to reproduce: Unknown
Consequence: None. The device continues to operate normally.

I have removed personal information and some garbage from the log files.

Compass.

**Comment by 981213** [comment]
Duplicated with #7775
