### ISSUE TITLE
FS#3041 - ramips/mt7621/newifi d2: The Transmission's settings error

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7797]
*vvs888:*

 - ramips/mt7621/newifi d2
 - SNAPSHOT r13046-df27e949fb
 - There is an error in the Transmission's settings in Luci. It is impossible to select and to change the value of Run daemon as user and Run daemon as group.

**Comment by 981213** [comment]
This bug belongs to LuCI or the community package feed.
