### ISSUE TITLE
FS#3125 - uclibc++ doesn't build when generated file names are too long

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7878]
*wt:*

I was having trouble building uClibc++ in Openwrt. I figured out that the problem was that the LIBSUP_DEP variable, which is a filename that gets created during the build, was too long for my file system. The name generated was over 150 char long and my fs has a limit of 143. I guess this because I have an encrypted homedir. Anyway, I analyzed the build system of uClibc++, and it seems to vary with the file location for libsupc++.a which is used to extract a bunch of symbols and create the static lib.

I had configured my build to build for a Turris Omnia.

Software versions: master branch of OpenWrt

Steps to reproduce:
1. Configure to build image for Turris Omnia.
2. Build with: `make package/libs/uclibc++/compile -j1 V=sc`

My proposed fix: https://bugs.busybox.net/show_bug.cgi?id=12951

If this patch get's accepted upstream, we should add a patch to package/libs/uclibc++/patches/ for this.

**Comment by ynezz** [comment]
Fixed in OpenWRT 21.02 by https://github.com/openwrt/openwrt/commit/f5db80a3ab387cc840f5602cc81d3c2028cb7401. This issue is not present in OpenWRT 22.03 or later, as uclibc++ has been removed https://github.com/openwrt/openwrt/commit/6b2ed6101e4c97691ba3aa94f25895be536b3870.
