### ISSUE TITLE
FS#3153 - feeds/packages/utils/zstd fails to compile if python3-distutils is not installed

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#7901]
*txt.file:*

====Device problem occurs on====
build server

====Software versions of OpenWrt/LEDE release, packages, etc.====
OpenWrt master as of r13499-7b4877c204

====Steps to reproduce====

  - install debian 10 amd64 & OpenWrt build requirements
  - git clone git://git.openwrt.org/openwrt/openwrt.git
  - select ath79-generic as target & select btrfs with zstd support
  - compile & wait
  - get output similar to attached meson-log.txt

====Solutions to solve problem====
  * install "python3-distutils" on the host
  * zstd package checks if python3-distutils is installed and provides proper "missing dependency"-error

**Comment by neheb** [comment]
@aparcar this is no longer an issue.
