### ISSUE TITLE
Hard-coded IPv4 addresses of ds-lite package...

### ISSUE THREAD

**Issue by tahiro86j** [openwrt/openwrt#80]
This is genuinely being my opinion (for political correctness), but I think the package `ds-lite` should be renamed to `ipip6` and its hard-coded IPv4 addresses (192.0.0.1, 192.0.0.2) for two endpoints should be removed, and instead be turned into user-defined options. This is mostly because the implementation of DS-Lite (as documented in [RFC6333](https://tools.ietf.org/html/rfc6333)) is based on IPv4-over-IPv6 tunnel and the such tunnels are referred to as `ipip6` in most linux-based distributions.

Since alteration of `ds-lite` with `ipip6` would require a substitute package with the same name (so that there is virtually no confusion), my proposal is to prepare a package named `ds-lite` which now behaves like a wrapper to `ipip6`.

I do already have a working code for `ipip6` (entirely based on the shell-script provided by the `ds-lite` package) so if the above proposal seems welcomed after observing the responses to this issue, I'm ready to submit a pull-request.

**Comment by tahiro86j** [comment]
Some might ask why this is necessary, and/or if you are curious about the backgrounds, please continue reading this additional post.

I am a happy user of OpenWrt in East Japan, whose internet connectivity is widely based on the service called "Flets's Hikari Next" by NTT-East.

The infrastructure provided by the service is rather interesting, in that the service alone merely provides the access-line, hence the L1 and L2. Although it does provide L3 via IPv6, you are given no connectivity to the WAN/Internet. By default, it's a local-WAN or Wide-Area-LAN based on IPv6. 

Getting access to the web on this service is possible by either one of the following "commercial" options;
a.)IPv4 via PPPoE
b.)DS-Lite

Primary use of such system (I imagine) is to replace the copper-line based PSTN (both analog and ISDN) by VoIP and imaginably, the monthly fee of its "Lite" service is now getting as low as those copper-line based services. There is another "interesting" use of the service, however, and this will be the main focus in this post (will be mentioned soon).

Some interesting parts of  this "Lite" service are;
a.)They are cheaper than the regular service, priced around $30/mo (around JPY3,000/mo).
***For comparison, the regular service is priced around $50/mo (around JPY5,000/mo) with unlimited download/upload.
b.)Traffic in excess of 500MBytes/mo involving PPPoE will be charged for on the pay-as-you-go basis.
c-1.)Traffic via IPv6 with no involvement of PPPoE counts only 40MBytes/mo towards the monthly use.
c-2.)Subscribers are able to establish connections with other subscribers of both "Lite" and regular via IPv6, and DDNS mechanism is made available for easing (Prefixes are "semi-static", they explain). 

Now, that I knew about the service and my parents has a semi-empty house some 40km outside of central Tokyo (and we used to have an ADSL line there, effectively working at Down:1.3Mbps/Up:700kbps and this was too slow), I somehow wanted to get that house online at speeds exceeding 30Mbps Up/Down. The idea of getting the two houses linked up via IPv4/IPv6 tunnel was the way to go.

**Comment by tahiro86j** [comment]
Since the issue seems to gather no attention, I'm silently making the modified script available under the repository [openwrt_v6tunnel](https://github.com/tahiro86j/openwrt_v6tunnel). As long as the rights of the script are claimed by any of the OpenWrt developers, I'll be more than happy to move the ownership of the script to the official repository of OpenWrt.
Cheers.

**Comment by KanjiMonster** [comment]
Well, DS-Lite is more than just an ip4-in-ip6 tunnel, RFC6333 defines the endpoints as 192.0.0.1 and 192.0.0.2 (although with a SHOULD, not a MUST), and also has additional implications like NAT being done on the AFTR. It might make sense to allow user configuration of the AFTR/B4 addresses, but RFC6333 / RFC7335 limit it to 192.0.0.0/29. There does not seem to be any DHCP option to allow auto-configuration of these addresses.

So having a separate protocol is the way to go IMHO.
