### ISSUE TITLE
FS#3195 - ramips/mt7621/zbt3526 -> boot failure with kernel 5.4

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8022]
*camel:*

Supply the following if possible:
 - Device problem occurs on: ZBT 3526-16MB + 32 MB
 - Software versions of OpenWrt/LEDE: current trunk (kernel 5.4)
 - Steps to reproduce: when i update the firmware, i see that there is a network after reboot for ~10sec, and then it is gone, and is not accessable, seeems to be, that something is crashing.
i can only hard-reset - nothing else.

any idea ?
maybe it is related also like the other bugs reported ? for bootloop or hanging/crashing mt7621 ?

**Comment by 981213** [comment]
Closed as requested.
