### ISSUE TITLE
FS#3205 - Kernel trace: drivers/reset/core.c:556 __reset_control_get_internal+0x15c/0x190

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8032]
*mpratt14:*

Seems to occur at least on all ar934x on ath79 target, both on kernel 4 and testing kernel 5

Experienced by me while porting ENS202EXT to ath79
My pull request:
https://github.com/openwrt/openwrt/pull/3014

Experienced by @rogerpueyo while porting MikroTik SXT Lite5 (SXT 5nD r2) to ath79
Forum post:
https://forum.openwrt.org/t/porting-the-mikrotik-sxt-lite5-sxt-5nd-r2-from-ar71xx-to-ath79/66592

may effect many more

Full kernel log:
https://gist.github.com/mpratt14/e9195a555f54e098fff6c21ad5c1bb36

<code>
[    1.161884] ------------[ cut here ]------------
[    1.166682] WARNING: CPU: 0 PID: 1 at drivers/reset/core.c:556 __reset_control_get_internal+0x15c/0x190
[    1.176216] Modules linked in:
[    1.179327] CPU: 0 PID: 1 Comm: swapper Not tainted 5.4.48 #0
[    1.185164] Stack : 80640000 805dfdf8 00000000 00000000 805defc8 83c2795c 83c282fc 80615d03
[    1.193661]         805819c4 00000001 807732d8 00000001 00000000 00000001 83c27910 712127d8
[    1.202152]         00000000 00000000 807a0000 0000005e 61696e74 00000000 2e342e34 38202330
[    1.210643]         0000005e 8cc27632 00000000 0002bc7f 00000000 00000009 00000000 802d7130
[    1.219135]         00000009 00000001 00000000 83c82a10 00000000 802ee410 00000000 80770000
[    1.227627]         ...
[    1.230121] Call Trace:
[    1.232637] [<80069934>] show_stack+0x30/0x100
[    1.237187] [<8007e7f8>] __warn+0xc0/0x10c
[    1.241360] [<8007e8a0>] warn_slowpath_fmt+0x5c/0xac
[    1.246414] [<802d7130>] __reset_control_get_internal+0x15c/0x190
[    1.252605] [<802d72a4>] __of_reset_control_get+0x140/0x1fc
[    1.258273] [<802d762c>] __devm_reset_control_get+0x70/0x108
[    1.264054] [<803538a8>] ag71xx_mdio_probe+0xbc/0x208
[    1.269221] [<80301cdc>] platform_drv_probe+0x40/0x94
[    1.274358] [<802ffe30>] really_probe+0x104/0x358
[    1.279145] [<802fdf20>] bus_for_each_drv+0x70/0xb0
[    1.284108] [<802ffce8>] __device_attach+0xdc/0x118
[    1.289072] [<802fee58>] bus_probe_device+0x9c/0xb8
[    1.294033] [<802fc22c>] device_add+0x3e4/0x608
[    1.298655] [<80368abc>] of_platform_device_create_pdata+0xa8/0x150
[    1.305026] [<80368ca4>] of_platform_bus_create+0x134/0x224
[    1.310692] [<80368f10>] of_platform_populate+0x78/0xec
[    1.316019] [<80355bd8>] ag71xx_probe+0x6e4/0x98c
[    1.320814] [<80301cdc>] platform_drv_probe+0x40/0x94
[    1.325952] [<802ffe30>] really_probe+0x104/0x358
[    1.330741] [<80300578>] device_driver_attach+0x70/0x98
[    1.336056] [<80300600>] __driver_attach+0x60/0x100
[    1.341017] [<802fde60>] bus_for_each_dev+0x68/0xa4
[    1.345979] [<802ff1cc>] bus_add_driver+0x1f0/0x200
[    1.350944] [<80300c6c>] driver_register+0x84/0x148
[    1.355912] [<80651920>] ag71xx_module_init+0x2c/0x50
[    1.361046] [<80060a1c>] do_one_initcall+0x7c/0x1dc
[    1.366010] [<8063de10>] kernel_init_freeable+0x158/0x23c
[    1.371512] [<804f50d8>] kernel_init+0x10/0xf0
[    1.376032] [<80064d98>] ret_from_kernel_thread+0x14/0x1c
[    1.381534] ---[ end trace f4d8db1ba0a810bb ]---
</code>

**Comment by mpratt14** [comment]
@aparcar this can be closed 😃 

migration failed to grab the link from last post

the commit that fixed it is this

https://github.com/openwrt/openwrt/commit/cea169702c33b472eeade5f084c74ac6ed01440e
