### ISSUE TITLE
FS#3238 - kmod-mt7601u

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8106]
*sentensos:*

MT7601u driver don't work as AP in OpenWrt, works perfectly in windows 10.
 - x86
 - Any OpenWrt build (stable/snapshot) 
 - After installing all packages (kmod-mt7601u, hostapd) usb-wifi adapter based on mt7601u work as scan, and can connect, but does not work as AP at all.

https://forum.openwrt.org/t/mt7601-usb-dongle/66925 - forum thread

**Comment by 981213** [comment]
Won't fix. The upstream linux driver simply doesn't support AP mode at all. It's not an OpenWrt bug.
