### ISSUE TITLE
FS#3262 - pcduino(sunxi/cortexa8)  kernel panic on openwrt snapshots 20

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8132]
*leigingban:*

Supply the following if possible:
 - Device problem occurs on pcduino [target/linux/sunxi/cortexa8]
 - Software versions of OpenWrt/LEDE release, packages, etc.
 - Steps to reproduce

******************************************************************
   
U-Boot SPL 2020.04 (Jul 31 2020 - 21:50:38 +0000)
DRAM: 1024 MiB
CPU: 1008000000Hz, AXI/AHB/APB: 3/2/2
Trying to boot from MMC1

U-Boot 2020.04 (Jul 31 2020 - 21:50:38 +0000) Allwinner Technology

CPU:   Allwinner A10 (SUN4I)
Model: LinkSprite pcDuino
I2C:   ready
DRAM:  1 GiB
MMC:   mmc@1c0f000: 0
Loading Environment from FAT... *** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   eth0: ethernet@1c0b000
starting USB...
Bus usb@1c14000: USB EHCI 1.00
Bus usb@1c14400: USB OHCI 1.0
Bus usb@1c1c000: USB EHCI 1.00
Bus usb@1c1c400: USB OHCI 1.0
scanning bus usb@1c14000 for devices... 1 USB Device(s) found
scanning bus usb@1c14400 for devices... 1 USB Device(s) found
scanning bus usb@1c1c000 for devices... 1 USB Device(s) found
scanning bus usb@1c1c400 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
377 bytes read in 1 ms (368.2 KiB/s)
## Executing script at 43100000
3308120 bytes read in 265 ms (11.9 MiB/s)
22889 bytes read in 5 ms (4.4 MiB/s)
## Booting kernel from Legacy Image at 42000000 ...
   Image Name:   ARM OpenWrt Linux-5.4.52
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    3308056 Bytes = 3.2 MiB
   Load Address: 40008000
   Entry Point:  40008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 43000000
   Booting using the fdt blob at 0x43000000
EHCI failed to shut down host controller.
   Loading Kernel Image
   Using Device Tree in place at 43000000, end 43008968

Starting kernel ...
 
******************************************************************

kernel panic

**Comment by ynezz** [comment]
Old, missing the actual kernel panic, so nothing actionable.
