### ISSUE TITLE
FS#3266 - Multicast does not work over bridge with AP/VLAN interfaces

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8135]
*whooo:*

Devices:
MikroTik RouterBOARD wAP G-5HacT2HnD with OpenWRT r13630-635f111148
EnGenius EAP1300 with OpenWRT r14017-c90db26e05

I have a wifi setup with EAP and dynamic vlan assigment from a radius server.
Clients can connect and both unicast and broadcast (DHCP) works fine, but multicast does not, so IPv6 SLAAC does not work for example.
On the APs I can see the multicast packets being sent out on the the AP/VLAN interfaces (tcpdump -n -i wlan1.10 multicast), but none of the three clients (linux laptop and two iOS devices) receives them.
I have tried enabling multicast_to_unicast, multicast_snooping and hairpin_mode by hand in sysfs, doesn't make any difference, also tried disabling multicast_router.
It sometimes works on the MikroTik device, but mostly does not.

My wireless config (it's the same on both devices for both radios):
config wifi-iface 'myssid_5'
        option mode 'ap'
        option ssid 'myssid'
        option hidden '1'
        option encryption 'wpa3-mixed'
        option auth_server 'authserver'
        option auth_secret 'secret'
        option dynamic_vlan '2'
        option vlan_tagged_interface 'eth0'
        option max_inactivity '1800'
        option device 'radio0'
        option mobility_domain 'f1f1'
        option nasid 'mynasid'
        option pmk_r1_push '1'
        option ieee80211r '1'
        option rsn_preauth '0'
        option isolate '1'
        option vlan_bridge 'br-vlan'
        option vlan_naming '0'
        option ieee80211w '1'
        list r0kh '....'
        list r0kh '....'
        list r0kh '....'
        list r0kh '....'
        list r1kh '....'
        list r1kh '....'
        list r1kh '....'
        list r1kh '....'

**Comment by russoisraeli** [comment]
Similar issue on GL-B1300 (GL.iNet).

Device is configured as an AP with multiple bridged VLANs.
The observed behaviour (via tcpdump) is that when SLAAC is used, the wireless client sends a Router Solicitation, it never gets from the bridge interface (ath* -> br* -> eth*) to the ethernet (VLAN) interface (and then never comes to the wired server).
The server eventually sends the (periodic) Router Advertisement, which actually gets through the other way (eth* -> br* -> ath*), and the client gets autoconfigured.

root@GL-B1300-Living:~# cat /etc/openwrt_release 
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='Chaos Calmer'
DISTRIB_REVISION='e7067e3+r49254'
DISTRIB_CODENAME='chaos_calmer'
DISTRIB_TARGET='ipq/ipq40xx'
DISTRIB_DESCRIPTION='OpenWrt Chaos Calmer 15.05.1'
DISTRIB_TAINTS='busybox'

root@GL-B1300-Living:~# cat /etc/openwrt_version
15.05.1


root@GL-B1300-Living:~# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: miireg: <> mtu 0 qdisc noop state DOWN mode DEFAULT group default qlen 1
    link/generic 
3: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT group default qlen 1
    link/gre 0.0.0.0 brd 0.0.0.0
4: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
5: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether b6:60:94:a0:d8:54 brd ff:ff:ff:ff:ff:ff
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
7: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br-lan state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3b brd ff:ff:ff:ff:ff:ff
8: teql0: <NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 100
    link/void 
9: wifi0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 2699
    link/ieee802.11 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
10: soc0: <> mtu 0 qdisc noop state DOWN mode DEFAULT group default qlen 1
    link/ieee802.11 
11: wifi1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 2699
    link/ieee802.11 94:83:c4:11:55:3b brd ff:ff:ff:ff:ff:ff
12: soc1: <> mtu 0 qdisc noop state DOWN mode DEFAULT group default qlen 1
    link/ieee802.11 
13: br-DMZ: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
14: eth0.6@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-DMZ state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
15: br-DMZ_v6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
16: eth0.16@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-DMZ_v6 state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
17: br-LAN_v6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
18: eth0.17@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-LAN_v6 state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
19: br-WiFi_v6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
20: eth0.18@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-WiFi_v6 state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
21: br-Wireless: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
22: eth0.8@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-Wireless state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
23: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
24: eth0.7@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
25: eth0.19@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
28: ath0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-Wireless state UP mode DEFAULT group default 
    link/ether 94:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
29: ath01: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-Wireless state UP mode DEFAULT group default 
    link/ether 9a:83:c4:11:55:3a brd ff:ff:ff:ff:ff:ff
30: ath1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-Wireless state UP mode DEFAULT group default 
    link/ether 94:83:c4:11:55:3b brd ff:ff:ff:ff:ff:ff
31: ath11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-Wireless state UP mode DEFAULT group default 
    link/ether 9a:83:c4:11:55:3b brd ff:ff:ff:ff:ff:ff
32: ath12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-WiFi_v6 state UP mode DEFAULT group default 
    link/ether 9e:83:c4:11:55:3b brd ff:ff:ff:ff:ff:ff

root@GL-B1300-Living:~# brctl show
bridge name	bridge id		STP enabled	interfaces
br-DMZ		7fff.9483c411553a	no		eth0.6
br-DMZ_v6		7fff.9483c411553a	no		eth0.16
br-LAN_v6		7fff.9483c411553a	yes		eth0.17
br-WiFi_v6		7fff.9483c411553a	no		ath12
							eth0.18
br-Wireless		7fff.9483c411553a	no		ath0
							ath01
							ath1
							ath11
							eth0.8
br-lan		7fff.9483c411553a	no		eth0.7
							eth1


Please let me know if you need any other information.

**Comment by russoisraeli** [comment]
<img width="826" alt="Screen Shot 2023-03-03 at 9 31 50 AM" src="https://user-images.githubusercontent.com/8259296/222747125-422310b2-1fb2-4652-9ce8-e467c7938de7.png">
<img width="897" alt="Screen Shot 2023-03-03 at 9 32 35 AM" src="https://user-images.githubusercontent.com/8259296/222747129-fae961f6-d75d-4559-83de-fb35bd455de0.png">

**Comment by nbd168** [comment]
This sounds very much like an issue in the Linux bridge layer which got fixed years ago. Feel free to open up a new ticket, or reopen if it's still reproducible with a recent version of OpenWrt.
