### ISSUE TITLE
FS#3289 - MT6720a Slowness in 2.4Ghz band

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8158]
*ajaikumarnadar:*

Device: MI R3

https://openwrt.org/toh/xiaomi/mir3

I am using a Openwrt fork, X-WRT in my MI R3. Whenever i use 2.4Ghz band connection, I am getting really slow speeds... I.e if i have bandwidth of 10 mbps upload and download speed then i am only half the speed. However, I have fixed the download speed by changing the 2.4ghz channel to 13 but still there are some packet losses which can be seen and still the upload speed doesn't cross 5mbps... 

I have attached speedtest screenshot for your reference. This speedtest has been done while no one was using my bandwidth and that too in the morning.

**Comment by 981213** [comment]
Won't fix. MT7620 wifi driver is known to be problematic and that's not something the community can solve without the help from MTK. (MTK is probably not interested in this EOL chip at all.)
