### ISSUE TITLE
FS#3301 - Cannot satisfy dependency on iptables-mod-tproxy

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8167]
*lowsfer:*

One example is iptables-mod-tproxy. It is available in 19.07.0, but not in 19.07.1. This causes dependency issue when installing some packages.
How to reproduce:
<code># opkg install shadowsocks-libev-ss-rules
Installing shadowsocks-libev-ss-rules (3.2.5-5) to root...
Downloading http://downloads.openwrt.org/releases/19.07.1/packages/aarch64_cortex-a53/packages/shadowsocks-libev-ss-rules_3.2.5-5_aarch64_cortex-a53.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocks-libev-ss-rules:
 *      iptables-mod-tproxy
 * opkg_install_cmd: Cannot install package shadowsocks-libev-ss-rules.</code>

I reproduced it on aarch64_coretex_a53, but I see it's missing for other platforms like a72 and x86_64, too.

It was reported here: https://github.com/openwrt/packages/issues/11457
But was closed and the maintainer said it belongs here.

**Comment by ynezz** [comment]
Too old and probably not a bug.
