### ISSUE TITLE
FS#3311 - vlan(NETWORK -> SWITCH) menu missing on luci -> mt7621(ZBT3526) - trunk

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8173]
*camel:*

vlan menu missing on luci -> mt7621(ZBT3526) - trunk

that was on 2020-01 working ?
why is it now gone ?
also in /etc/config, there are no entries for vlan

i compared to the old version from 20020-01 ..

and there is 1 file missing: (or more ?)
# cat /lib/network/switch.sh

#!/bin/sh
# Copyright (C) 2009 OpenWrt.org

setup_switch_dev() {
        local name
        config_get name "$1" name
        name="${name:-$1}"
        [ -d "/sys/class/net/$name" ] && ip link set dev "$name" up
        swconfig dev "$name" load network
}

setup_switch() {
        config_load network
        config_foreach setup_switch_dev switch
}

**Comment by 981213** [comment]
This bug report is probably outdated as we are using DSA now. Closed.
