### ISSUE TITLE
FS#3325 - MT7628an: lose radio whilst downloading jarge data

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8184]
*smithsj121:*

Using a GL.inet MT300N-V2

For simple browsing this setup works well.
If I downlaod a large file, for example a Debina DVD, a few seconds varying to a few minutes into the download, the PC disconnect and the SSID vanishes in list. The PC cannot reconnect.

If I connect over WAN and resrart the radio under network wireless, I can reconnect.

Typically the download is occuring at 60mbits and the PC is connect at 144mbits. Mean Score 14-15.
If I use traffic shaping tbf  on the output of the wireless interface, and throttle back to 35mbits (with occassional peak over 40mbits as tokens allow). I have very reliable wifi.

I cannot replicate on GL.iNET stick firmware using the closed source driver.

I am using a 2.1a power supply, so I think this is OK.
I am have replicated on multiple devices, so I do not think this is hhardware.
I live on a UK estate of multiple blocks of flats (arond about 16 blocks of 8 flats each). 2.4GHz wifi is very busy. After some grief discussion on forum, I believe the cause is wireless environmant.

The MT300N-V2 and PC are about 0.75m apart.

WAN: connection ethernet -> ISP @ 120mbits
LAN: LAN switch port, with wireless bridge. PSK V2, Cipher auto, 20MHz width.

Given I think cause is environment, I think recreation might be tuff.
What tracing can I do to help?
I have nohup running, so I can run logread to a usb stick to get ths output?
Will this help?

git status shows I am up to date, I cloned 2020-09-01 not great with git so not sure how to get mroe info about version.

Thanks for your help
Simon

**Comment by hauke** [comment]
Should be fixed in 76b1e564d202c09d0035315eb6e958a9b0dd4491 for OpenWrt 22.03 and was fixed earlier in more recent versions.
