### ISSUE TITLE
FS#3348 - libustream: package/install file conflicts

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8204]
*mpratt14:*

Reproduce the problem:
selecting `luci-ssl-openssl`

<code>
Collected errors:
 * check_data_file_clashes: Package libustream-openssl20200215 wants to install file /media/builds/github-openwrt/openwrt/build_dir/target-mips_24kc_musl/root-ath79/lib/libustream-ssl.so
        But that file is already provided by package  * libustream-wolfssl20200215
 * opkg_install_cmd: Cannot install package libustream-openssl20200215.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 *      luci-proto-ppp
 * opkg_install_cmd: Cannot install package luci.
 * check_data_file_clashes: Package libustream-openssl20200215 wants to install file /media/builds/github-openwrt/openwrt/build_dir/target-mips_24kc_musl/root-ath79/lib/libustream-ssl.so
        But that file is already provided by package  * libustream-wolfssl20200215
 * opkg_install_cmd: Cannot install package luci-ssl-openssl.
pts (1.4.0-9) to root...
</code>

<code>
make[1]: *** [package/Makefile:68: package/install] Error 255
make[1]: Leaving directory '/media/builds/github-openwrt/openwrt'
make: *** [/media/builds/github-openwrt/openwrt/include/toplevel.mk:236: package/install] Error 2
Command exited with non-zero status 2
</code>

**Comment by KanjiMonster** [comment]
duplicate of https://github.com/openwrt/openwrt/issues/8203
