### ISSUE TITLE
FS#3381 - Trunk don't initialize pci cards at mt7621

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8245]
*AelxG:*

Trunk does not initialize pci adapter cards properly.

I'm using unielec mt7621 board with kind of Atheros miniPCIe cards? in this test installed AR9287 adapter.

Here is lspci and part of dmesg output from 19.07.4:
<code>
root@OpenWrt:~# lspci -v
02:00.0 Network controller: Qualcomm Atheros AR9287 Wireless Network Adapter (PCI-Express) (rev 01)
        Subsystem: Qualcomm Atheros Device 30a4
        Flags: fast devsel, IRQ 255
        Memory at 60200000 (64-bit, non-prefetchable) [disabled] [size=64K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable- Count=1/1 Maskable- 64bit-
        Capabilities: [60] Express Legacy Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Virtual Channel
        Capabilities: [160] Device Serial Number 00-15-17-ff-ff-24-14-12
        Capabilities: [170] Power Budgeting <?>

[    2.261556] pci 0000:02:00.0: [168c:002e] type 00 class 0x028000
[    2.261628] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x0000ffff 64bit]
[    2.261756] pci 0000:02:00.0: supports D1
[    2.261764] pci 0000:02:00.0: PME# supported from D0 D1 D3hot</code>

Here is lspci and part of dmesg output from trunk:

<code>02:00.0 Ethernet controller: Qualcomm Atheros AR5008 Wireless Network Adapter (rev 01)
        Flags: fast devsel, IRQ 255
        Memory at 60200000 (64-bit, non-prefetchable) [disabled] [size=64K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable- Count=1/1 Maskable- 64bit-
        Capabilities: [60] Express Legacy Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Virtual Channel
        Capabilities: [160] Device Serial Number 00-00-00-00-00-00-00-00
        Capabilities: [170] Power Budgeting <?>

[    1.604742] pci 0000:02:00.0: [168c:ff1c] type 00 class 0x020000
[    1.610801] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x0000ffff 64bit]
[    1.617717] pci 0000:02:00.0: supports D1
[    1.621723] pci 0000:02:00.0: PME# supported from D0 D1 D3hot</code>

You may see the the trunk cannot see correct PCI ID and some pci parameters like device serial numbers. Also any wifi modules does not work (mac80211, etc).

**Comment by ynezz** [comment]
According to https://github.com/openwrt/openwrt/issues/7862 it should be fixed.
