### ISSUE TITLE
FS#3411 - The firewall refuses any connection when i add more than 24 DHCPs

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8269]
*markxsq:*

Supply the following if possible:
 - Device problem occurs on
 - Software versions of OpenWrt/LEDE release, packages, etc.
 - Steps to reproduce
   

And the DHCP Server doesn't work any more!

My route is below:

主机名	OpenWrt
型号	UBNT-ERX
架构	MediaTek MT7621 ver:1 eco:3
固件版本	OpenWrt 19.07.4 r11208-ce6496d796 / LuCI openwrt-19.07 branch git-20.247.75781-0d0ab01
内核版本	4.14.195
本地时间	2020-10-27 10:04:52

**Comment by ynezz** [comment]
Try to reproduce it with latest [22.03-rc2](https://downloads.openwrt.org/releases/22.03.0-rc2/targets/) or [development snapshot](https://downloads.openwrt.org/snapshots/targets/) and report back, we can re-open the ticket.
