### ISSUE TITLE
FS#3417 -  /etc/config/luci seems to be corrupt, unable to find section 'main'

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8289]
*ThinkPadX220:*

Supply the following if possible:
 - Device problem occurs on
 - Software versions of OpenWrt/LEDE release, packages, etc.
 - Steps to reproduce
   

OpenWRT 19.07.4 on xRX200 rev 1.2 (BT Home Hub 5A) with all packages up to date.
After running the router for a while I'll try to login to the page and get this error:
/usr/lib/lua/luci/dispatcher.lua:426: /etc/config/luci seems to be corrupt, unable to find section 'main'

This would normally be accompanied with the 5GHz channel set to 149 (which is a paid-for channel in the UK).
Checking /etc/config/luci looks fine to me and sometimes service rcpd restart works but other times it leaves Luci in an unusable state.

**Comment by zorun** [comment]
Probably the same (old) issue as #8048 (FS#3177), closing
