### ISSUE TITLE
FS#3441 - Menuconfig misbehaviour: wpad-mesh-wolfssl disappears depending on wpad-basic state

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8312]
*ilario:*

====Premise:====

I am on OpenWrt 19.07.4 and menuconfig is behaving weirdly in a case.
I was trying to document how to select wpad-mesh-wolfssl and deselect wpad-basic for LibreMesh compilation and found something that looks like a bug in some Config.in file used by menuconfig.
Original bug reported on LibreMesh issues list here:
https://github.com/libremesh/lime-web/issues/125

====Getting there:====

Selecting at the same time wpad-basic and wpad-mesh-wolfssl causes a clash of files installation in the compilation process. For this reason the deselection of wpad-basic has been suggested in LibreMesh compilation instructions.

wpad-mesh-wolfssl can be selected in menuconfig and wpad-basic deselected, until here everything ok.

====Issue:====

Then when closing and opening again menuconfig, wpad-mesh-wolfssl is not visible.

Screenshot: https://user-images.githubusercontent.com/1329018/98670652-4877ca80-2353-11eb-9d7f-96b5c5d718fd.png

But when wpad-basic (or something else) is selected, wpad-mesh-wolfssl appears and is actually selected (as it should be).

Screenshot: https://user-images.githubusercontent.com/1329018/98670749-7230f180-2353-11eb-9d44-2d6a9bcb3c78.png

The wpad-mesh-wolfssl package is categorized as being inside wpad-mesh-openssl, which makes no sense.

Screenshot: https://user-images.githubusercontent.com/1329018/98670837-9b518200-2353-11eb-8cf0-f490182b4ee2.png

And all of this happens even if the definitions of wpad-basic, wpad-mesh-openssl and wpad-mesh-wolfssl are substantially identical (extracted from https://github.com/openwrt/openwrt/blob/openwrt-19.07/package/network/services/hostapd/Makefile ):

wpad-basic
  [identical part removed]
  VARIANT:=wpad-basic

wpad-mesh-openssl
  [identical part removed]
  DEPENDS+=@PACKAGE_kmod-cfg80211 @(!TARGET_uml||BROKEN)
  PROVIDES+=wpa-supplicant-mesh wpad-mesh
  DEPENDS+=+libopenssl
  VARIANT:=wpad-mesh-openssl

wpad-mesh-wolfssl
  [identical part removed]
  DEPENDS+=@PACKAGE_kmod-cfg80211 @(!TARGET_uml||BROKEN)
  PROVIDES+=wpa-supplicant-mesh wpad-mesh
  DEPENDS+=+libwolfssl
  VARIANT:=wpad-mesh-wolfssl

This looks like a bug in some of the Config.in files used by make menuconfig.
Just to support this, I exchanged the order in which wpad-mesh-openssl and wpad-mesh-wolfssl are defined in `tmp/.config-package.in` and now wpad-mesh-wolfssl and wpad-mesh-openssl are at the same hierarchical level. There's clearly a bug around.

Thanks!

**Comment by ilario** [comment]
Thanks @openwrt-bot!
@aparcar do you know if this is fixed in 21.02?

**Comment by aparcar** [comment]
Inverting the order of openssl and wolfssl (aka wolfssl first) fixes the subcategory issues. Not sure what's the base for that.

Overall wired that we have `wpad` and `wpad-basic` but not `wpad-mesh`. 

@nbd168 ideas for this?

**Comment by ilario** [comment]
With OpenWrt 22.03.0-rc4 is even worse as I cannot manage to deselect wpad-basic-wolfssl (even if in menuconfig it looks like I managed to deselect it, it is still active in .config),

**Comment by ilario** [comment]
I am still having problems with this on v22.03.3.
To reproduce:
create a `.config` file with only this line:

`CONFIG_PACKAGE_wpad-openssl=y`

run `make defconfig`

check the content of the `.config` file. You will find something like this:

```
$ grep -i wpad .config
CONFIG_DEFAULT_wpad-basic-wolfssl=y
# CONFIG_PACKAGE_wpad is not set
# CONFIG_PACKAGE_wpad-basic is not set
# CONFIG_PACKAGE_wpad-basic-openssl is not set
CONFIG_PACKAGE_wpad-basic-wolfssl=y
# CONFIG_PACKAGE_wpad-mesh-openssl is not set
# CONFIG_PACKAGE_wpad-mesh-wolfssl is not set
# CONFIG_PACKAGE_wpad-mini is not set
CONFIG_PACKAGE_wpad-openssl=m
# CONFIG_PACKAGE_wpad-wolfssl is not set
```

as you can see, `wpad-openssl` has been deselected and `wpad-basic-wolfssl` has been selected (twice).

Is there a way for having the full wpad-openssl compiled in the firmware using the buildroot?

**Comment by ilario** [comment]
Selecting a package with a dependency from wpad-openssl (this package: https://github.com/libremesh/network-profiles/blob/master/calafou/outdoor-crypt/Makefile ) seems that managed to keep wpad-openssl selected.

**Comment by ilario** [comment]
In these days I compiled images with wpad-mesh-openssl on OpenWrt 23.05.5 and did not observe any issue.
So either it has been solved or it happens with wpad-mesh-wolfssl but not with wpad-mesh-openssl...
If noone else report this as broken, I think you can close this issue. Thanks!
