### ISSUE TITLE
FS#3338 - TL-WR841N v13 (ramips) unstable Ethernet and WiFi in 19.07.4

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8314]
*platofff:*

I am using default build of OpenWRT 19.07.4 for TL-WR841N v13 without any additional packages. I have Ethernet PPPoE from provider, some ethernet and WiFi WPA2 clients. WiFi and Ethernet are unstable: they can disappear for 30-60 seconds without any serious reason. On 18.06.8 there wasn't those problems. I attached system log. Thanks for help.

**Comment by hauke** [comment]
Should be fixed in 76b1e564d202c09d0035315eb6e958a9b0dd4491 for OpenWrt 22.03 and was fixed earlier in more recent versions.
