### ISSUE TITLE
FS#3447 - Missing kmods for mt7621 in repo

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8318]
*hhejkhalkfahjahsf:*

*** Failed to download the package list from https://downloads.openwrt.org/snaps                                                                       hots/targets/ramips/mt7621/kmods/5.4.75-1-878d1c290479417154653dd2ca7e6dbd/Packa                                                                       ges.gz

**Comment by 981213** [comment]
Not a bug. The snapshot package feed is always updating with the master branch.
