### ISSUE TITLE
FS#3474 - 802.11r - Fast transitioning not working for 2nd SSID

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8345]
*buletti:*

**Description:**

I have 3 WIFI access points (2x Netgear WNDR4300, 1x Netgear WNDR3700v2) running 19.07.4 r11208-ce6496d796. Each of those APs has a 2.4 and a 5 GHz band. For each of the 2 radios I have defined 2 SSIDs: Home-net and Guest-net.

So each AP has a total of 4 WIFI interfaces:
  * Home-net @ 2.4 GHz
  * Home-net @ 5 GHz
  * Guest-net @ 2.4 GHz
  * Guest-net @ 5 GHz

All the WIFI interfaces of the same SSID are bridged together into a separate VLAN.

802.11r is configured identically on all 4 WIFI interfaces. I'm using a very simple FT config that generates the keys locally based on the pre-shared key and I let most of the required settings to be generated automatically.

Now, my problem is that fast-transitioning works for the Home-net, but not for the Guest-net.
Home-net roaming is really working great and as expected. I can fast-transition between the radio cells of the same AP (2.4GHz <=> 5GHz) as well as fast-transition between the cells of the different APs.

However fast-transitioning of the Guest-net on the other hand is not working at all. Even though it is essentially using the same configuration as the Home-net.
I already tried to provide explicit values for some of the relevant, generated 802.11r settings like NASID and Mobility-Domain, but that does not seem to make any difference.
I also did a test to see what happens, if I delete the 2 working Home-net interfaces. Well, once they are deleted, fast transitioning via the 2 remaining Guest-net interfaces started to work. I could easily roam between the 2.4 and 5 GHz networks of the modified AP.
Given the fact that the previously defunct Guest-net network becomes functional tells me that my network configuration and my 802.11r configuration are not the problem here.

**How to reproduce:**

//precondition//: a dual band AP with 19.07.04
1. set up 2 wifi networks for each radio
2. enable hostapd debug mode for both radios
3. connect with a mobile device to the first SSID and try to roam between the bands
4. check the systemlog for FT messages
//result//: fast transitioning is working for the first SSID
5. connect with a mobile device to the second SSID and try to roam between the bands
6. check the systemlog for FT messages
//result//: fast transitioning is not working for the second SSID
//expected result//: fast transitioning is working for both/all SSIDs.

**wireless config**
<code>
config wifi-device 'radio0'
	option type 'mac80211'
	option hwmode '11g'
	option path 'platform/ar934x_wmac'
	option country 'DE'
	option legacy_rates '0'
	option htmode 'HT20'
	option log_level '1'
	option channel '11'
	option txpower '17'

config wifi-device 'radio1'
	option type 'mac80211'
	option hwmode '11a'
	option path 'pci0000:00/0000:00:00.0'
	option country 'DE'
	option legacy_rates '0'
	option htmode 'HT40'
	option log_level '1'
	option channel '36'    

## home-net 2.4 GHz
config wifi-iface 'default_radio0'
	option device 'radio0'
	option mode 'ap'
	option network 'WIFI-HOME'
	option encryption 'psk2+ccmp'
	option key '***redacted***'
	option ssid 'home-net'
	option macfilter 'allow'
	list maclist '***redacted***'
	option wpa_disable_eapol_key_retries '1'
	option ieee80211r '1'
	option ft_psk_generate_local '1'
	option ft_over_ds '0'
	option max_inactivity '30'

## home-net 5 GHz
config wifi-iface 'default_radio1'
	option device 'radio1'
	option mode 'ap'
	option network 'WIFI-HOME'
	option encryption 'psk2+ccmp'
	option key '***redacted***'
	option ssid 'home-net'
	option macfilter 'allow'
	list maclist '***redacted***'
	option wpa_disable_eapol_key_retries '1'
	option ieee80211r '1'
	option ft_psk_generate_local '1'
	option ft_over_ds '0'
	option max_inactivity '30'

## guest-net 2.4 GHz
config wifi-iface 'wifinet2'
	option device 'radio0'
	option mode 'ap'
	option network 'WIFI-GUEST'
	option encryption 'psk2+ccmp'
	option key '***redacted***'
	option ssid 'guest-net'
	option wpa_disable_eapol_key_retries '1'
	option ieee80211r '1'
	option ft_psk_generate_local '1'
	option ft_over_ds '0'
	option max_inactivity '30'

## guest-net 5 GHz
config wifi-iface 'wifinet3'
	option device 'radio1'
	option mode 'ap'
	option network 'WIFI-GUEST'
	option encryption 'psk2+ccmp'
	option key '***redacted***'
	option ssid 'guest-net'
	option wpa_disable_eapol_key_retries '1'
	option ieee80211r '1'
	option ft_psk_generate_local '1'
	option ft_over_ds '0'
	option max_inactivity '30'</code>

**Comment by evilbulgarian** [comment]
Also running into this on wndr3800's.

**Comment by user8446** [comment]
Confirming this bug still existing in the current 22.03.3 stable release. 

The VLAN is irrevelant. Fast transition only works on the 1st SSID. On a 2nd SSID on the same radio it doesn't.

**Comment by hackrevdd** [comment]
Confirming this bug for 23.05.0-rc2 (r23228-cd17d8df2a) on a wax206 also :-(

**Comment by mgbarton** [comment]
Sadly this bug still exists in 22.05-rc2, testing on a Belkin RT3200.

**Comment by user8446** [comment]
I just tried with 23.05.0 stable release and on the 2nd SSID FT appears to be working but the logs are not as verbose as the main SSID:

```
Tue Oct 17 16:38:58 2023 daemon.err hostapd: nl80211: kernel reports: key addition failed
Tue Oct 17 16:38:58 2023 daemon.info hostapd: phy1-ap1: STA ##:##:##:##:##:## IEEE 802.11: associated (aid 1)
Tue Oct 17 16:38:58 2023 daemon.notice hostapd: phy1-ap1: AP-STA-CONNECTED ##:##:##:##:##:## auth_alg=ft 
```

I also used Ubuquiti's WiFiman Android app and it was showing the toast roaming indicator switching AP to AP.

The WiFiAnalyzer Android app also is showing FT for the 2nd SSID:

```
[WPA2-PSK+FT/PSK-CCMP]
[RSN-PSK+FT/PSK-CCMP][ESS]
```

Can you all test as well? I did change to the full `hostapd-mbedtls` from the basic one for the 802.11k neighbor report but that shouldn't make a difference.

**Comment by hackrevdd** [comment]
Yes, 23.05.0 fixed this bug for me too (devices are 3 Netgear wax206). Did a walk-around over 3 roaming-zones with both 2.4 Ghz and 5 Ghz WLANs. First and second SSID definitely works now.
