### ISSUE TITLE
FS#1955 - Ubiquiti EdgeRouter X initramfs-factory.tar

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8443]
*kroeckx:*

On https://openwrt.org/toh/ubiquiti/ubiquiti_edgerouter_x_er-x_ka there is an explanation of how to install OpenWRT on an EdgeRouter X using the tools that are standard installed on it and are used by Ubiquiti to upgrade the firmware. It seems as part of the build process a openwrt-ramips-mt7621-ubnt-erx-initramfs-factory.tar file is generated that can be used for that. But it seems you can not download it from the official site, you need to build it yourself. On the official site is an openwrt-18.06.1-ramips-mt7621-ubnt-erx-initramfs-kernel.bin file. I think that file can be used for installing using tftp, but it can't be used with the Ubiquiti tools. Can the initramfs-factory.tar be made available to download?

**Comment by ynezz** [comment]
See #5090
