### ISSUE TITLE
FS#500 - firewall3: missing targets with IPv6 NAT

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8534]
*josephcsible:*

When the kmod-ipt-nat6 package is installed, running /etc/init.d/firewall reload or /etc/init.d/firewall restart produces warnings that targets are missing:
<code> * Populating IPv6 nat table
   * Zone 'lan'
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_lan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_lan_rule'
   * Zone 'wan'
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_wan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_wan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_rule'</code>
I tested this on an Archer C7 v2 running LEDE 17.01.0rc2.

**Comment by ynezz** [comment]
@hnyman I assume this is too old, right? Anyway, try to reproduce it with the latest release and feel free to ask for issue reopening if the problem is still present, thanks.

**Comment by Magissia** [comment]
@ynezz I can reproduce the issue as is on OpenWRT 22.03 just by installing the kmod-ipt-nat6 package.
Unsure why it was closed as "compelted".

Use case is using ULA on multi-homed networks and/or when the ISP doesn't provide a static range.
