### ISSUE TITLE
FS#3537 - ramips-mt7621: rcu_sched self-detected stall on CPU

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8565]
*dfberger:*

Model: UBNT-ERX
Architecture: MediaTek MT7621 ver:1 eco:3
Firmware Version: OpenWrt 19.07.5 r11257-5090152ae3 / LuCI openwrt-19.07 branch git-20.341.57626-51f55b5
Kernel Version: 4.14.209

<code>
Dec 26 04:25:15 portcullis kernel: [ 2585.035949] INFO: rcu_sched self-detected stall on CPU
Dec 26 04:25:15 portcullis kernel: [ 2585.046207] #0111-...: (1 GPs behind) idle=fa2/140000000000001/0 softirq=140901/140903 fqs=2999
Dec 26 04:25:15 portcullis kernel: [ 2585.055938] INFO: rcu_sched detected stalls on CPUs/tasks:
Dec 26 04:25:15 portcullis kernel: [ 2585.063154] #011 (t=6002 jiffies g=43502 c=43501 q=1838)
Dec 26 04:25:15 portcullis kernel: [ 2585.084122] NMI backtrace for cpu 1
Dec 26 04:25:15 portcullis kernel: [ 2585.091055] CPU: 1 PID: 6770 Comm: kworker/1:1 Not tainted 4.14.209 #0
Dec 26 04:25:15 portcullis kernel: [ 2585.104071] Workqueue: events_power_efficient 0x8f270cac [nf_flow_table@8f270000+0x3370]
Dec 26 04:25:15 portcullis kernel: [ 2585.120162] Stack : 00000000 00000000 804d7568 8fc0bd24 00000000 00000000 00000000 00000000
Dec 26 04:25:15 portcullis kernel: [ 2585.136792]         00000000 00000000 00000000 00000000 00000000 00000001 8fc0bce0 53261630
Dec 26 04:25:15 portcullis kernel: [ 2585.153422]         8fc0bd78 00000000 00000000 00003ff0 00000038 8049da98 00000007 00000000
Dec 26 04:25:15 portcullis kernel: [ 2585.170054]         00000000 80550000 00019687 00000000 8fc0bcc0 00000000 00000000 00000001
Dec 26 04:25:15 portcullis kernel: [ 2585.186686]         80554500 8054c0cc 000000e0 80550000 00000003 802ae190 00000004 806b0004
Dec 26 04:25:15 portcullis kernel: [ 2585.203314]         ...
Dec 26 04:25:15 portcullis kernel: [ 2585.208170] Call Trace:
Dec 26 04:25:15 portcullis kernel: [ 2585.208185] [<8049da98>] 0x8049da98
Dec 26 04:25:15 portcullis kernel: [ 2585.219960] [<802ae190>] 0x802ae190
Dec 26 04:25:15 portcullis kernel: [ 2585.226888] [<8000c1a0>] 0x8000c1a0
Dec 26 04:25:15 portcullis kernel: [ 2585.233814] [<8000c1a8>] 0x8000c1a8
Dec 26 04:25:15 portcullis kernel: [ 2585.240741] [<804868d4>] 0x804868d4
Dec 26 04:25:15 portcullis kernel: [ 2585.247669] [<80072c54>] 0x80072c54
Dec 26 04:25:15 portcullis kernel: [ 2585.254594] [<8048d8f4>] 0x8048d8f4
Dec 26 04:25:15 portcullis kernel: [ 2585.261522] [<80008f30>] 0x80008f30
Dec 26 04:25:15 portcullis kernel: [ 2585.268451] [<80008f30>] 0x80008f30
Dec 26 04:25:15 portcullis kernel: [ 2585.275376] [<8048d9e0>] 0x8048d9e0
Dec 26 04:25:15 portcullis kernel: [ 2585.282304] [<80086558>] 0x80086558
Dec 26 04:25:15 portcullis kernel: [ 2585.289233] [<800859a8>] 0x800859a8
Dec 26 04:25:15 portcullis kernel: [ 2585.296175] [<8f270000>] 0x8f270000 [nf_flow_table@8f270000+0x3370]
Dec 26 04:25:15 portcullis kernel: [ 2585.308690] [<8f270000>] 0x8f270000 [nf_flow_table@8f270000+0x3370]
Dec 26 04:25:15 portcullis kernel: [ 2585.321147] [<80089118>] 0x80089118
Dec 26 04:25:15 portcullis kernel: [ 2585.328076] [<8009a168>] 0x8009a168
Dec 26 04:25:15 portcullis kernel: [ 2585.335003] [<80332644>] 0x80332644
Dec 26 04:25:15 portcullis kernel: [ 2585.341930] [<80079328>] 0x80079328
Dec 26 04:25:15 portcullis kernel: [ 2585.348859] [<800735e0>] 0x800735e0
Dec 26 04:25:15 portcullis kernel: [ 2585.355785] [<8025bd98>] 0x8025bd98
Dec 26 04:25:15 portcullis kernel: [ 2585.362712] [<8025bc44>] 0x8025bc44
Dec 26 04:25:15 portcullis kernel: [ 2585.369641] [<8025be04>] 0x8025be04
Dec 26 04:25:15 portcullis kernel: [ 2585.376569] [<800735e0>] 0x800735e0
Dec 26 04:25:15 portcullis kernel: [ 2585.383494] [<804a475c>] 0x804a475c
Dec 26 04:25:15 portcullis kernel: [ 2585.390421] [<8025b4c0>] 0x8025b4c0
Dec 26 04:25:15 portcullis kernel: [ 2585.397362] [<80007488>] 0x80007488
Dec 26 04:25:15 portcullis kernel: [ 2585.404285]
Dec 26 04:25:15 portcullis kernel: [ 2585.407315] #0111-...: (1 GPs behind) idle=fa2/140000000000001/0 softirq=140901/140903 fqs=2999
Dec 26 04:25:15 portcullis kernel: [ 2585.424318] #011(detected by 2, t=6038 jiffies, g=43502, c=43501, q=1838)
Dec 26 04:25:15 portcullis kernel: [ 2585.437422] Sending NMI from CPU 2 to CPUs 1:
Dec 26 04:25:15 portcullis kernel: [ 2585.446128] NMI backtrace for cpu 1
Dec 26 04:25:15 portcullis kernel: [ 2585.453060] CPU: 1 PID: 6770 Comm: kworker/1:1 Not tainted 4.14.209 #0
Dec 26 04:25:15 portcullis kernel: [ 2585.466048] Workqueue: events_power_efficient 0x8f270cac [nf_flow_table@8f270000+0x3370]
Dec 26 04:25:15 portcullis kernel: [ 2585.482140] task: 8f056c60 task.stack: 8fe7e000
Dec 26 04:25:15 portcullis kernel: [ 2585.491139] $ 0   : 00000000 00000001 00000000 00000000
Dec 26 04:25:15 portcullis kernel: [ 2585.501534] $ 4   : 00000006 00080000 00036fb8 00036fb8
Dec 26 04:25:15 portcullis kernel: [ 2585.511929] $ 8   : 0000ffff ffff0000 00000002 fffffffe
Dec 26 04:25:15 portcullis kernel: [ 2585.522324] $12   : 80553530 00000040 ffffffff 00000206
Dec 26 04:25:15 portcullis kernel: [ 2585.532719] $16   : 8f3a297c 81224320 8054c1e8 00080000
Dec 26 04:25:15 portcullis kernel: [ 2585.543114] $20   : 805ab344 8f3a297c 80550000 8056dba0
Dec 26 04:25:15 portcullis kernel: [ 2585.553511] $24   : 3b9aca00 00000000
Dec 26 04:25:15 portcullis kernel: [ 2585.563911] $28   : 8fe7e000 8fe7fdc8 8f270000 8006be90
Dec 26 04:25:15 portcullis kernel: [ 2585.574324] Hi    : 00000133
Dec 26 04:25:15 portcullis kernel: [ 2585.580041] Lo    : 33333380
Dec 26 04:25:15 portcullis kernel: [ 2585.585760] epc   : 8006bf2c 0x8006bf2c
Dec 26 04:25:15 portcullis kernel: [ 2585.593380] ra    : 8006be90 0x8006be90
Dec 26 04:25:15 portcullis kernel: [ 2585.600997] Status: 11007c03#011KERNEL EXL IE
Dec 26 04:25:15 portcullis kernel: [ 2585.609320] Cause : 50800400 (ExcCode 00)
Dec 26 04:25:15 portcullis kernel: [ 2585.617285] PrId  : 0001992f (MIPS 1004Kc)
Dec 26 04:25:15 portcullis kernel: [ 2585.625423] CPU: 1 PID: 6770 Comm: kworker/1:1 Not tainted 4.14.209 #0
Dec 26 04:25:15 portcullis kernel: [ 2585.638413] Workqueue: events_power_efficient 0x8f270cac [nf_flow_table@8f270000+0x3370]
Dec 26 04:25:15 portcullis kernel: [ 2585.654499] Stack : 00000000 00000000 804d7568 8fc0bd64 00000000 00000000 00000000 00000000
Dec 26 04:25:15 portcullis kernel: [ 2585.671127]         00000000 00000000 00000000 00000000 00000000 00000001 8fc0bd20 53261630
Dec 26 04:25:15 portcullis kernel: [ 2585.687754]         8fc0bdb8 00000000 00000000 00004c50 00000038 8049da98 00000007 00000000
Dec 26 04:25:15 portcullis kernel: [ 2585.704382]         00000000 80550000 0009bdcd 00000000 8fc0bd00 00000000 00000000 00000001
Dec 26 04:25:15 portcullis kernel: [ 2585.721009]         804dee64 8053f420 804dca54 80550000 00000003 802ae190 00000004 806b0004
Dec 26 04:25:15 portcullis kernel: [ 2585.737636]         ...
Dec 26 04:25:15 portcullis kernel: [ 2585.742490] Call Trace:
Dec 26 04:25:15 portcullis kernel: [ 2585.742501] [<8049da98>] 0x8049da98
Dec 26 04:25:15 portcullis kernel: [ 2585.754275] [<802ae190>] 0x802ae190
Dec 26 04:25:15 portcullis kernel: [ 2585.761202] [<8000c1a0>] 0x8000c1a0
Dec 26 04:25:15 portcullis kernel: [ 2585.768130] [<8000c1a8>] 0x8000c1a8
Dec 26 04:25:15 portcullis kernel: [ 2585.775054] [<804868d4>] 0x804868d4
Dec 26 04:25:15 portcullis kernel: [ 2585.781981] [<8000c264>] 0x8000c264
Dec 26 04:25:15 portcullis kernel: [ 2585.788910] [<8048d8d4>] 0x8048d8d4
Dec 26 04:25:15 portcullis kernel: [ 2585.795835] [<80009044>] 0x80009044
Dec 26 04:25:15 portcullis kernel: [ 2585.802763] [<80009054>] 0x80009054
Dec 26 04:25:15 portcullis kernel: [ 2585.809714] [<80059f4c>] 0x80059f4c
Dec 26 04:25:15 portcullis kernel: [ 2585.816642] [<800a1740>] 0x800a1740
Dec 26 04:25:15 portcullis kernel: [ 2585.823569] [<80085e60>] 0x80085e60
Dec 26 04:25:15 portcullis kernel: [ 2585.830501] [<80011860>] 0x80011860
Dec 26 04:25:15 portcullis kernel: [ 2585.837450] [<8f270000>] 0x8f270000 [nf_flow_table@8f270000+0x3370]
Dec 26 04:25:15 portcullis kernel: [ 2585.849909] [<80074180>] 0x80074180
Dec 26 04:25:15 portcullis kernel: [ 2585.856849] [<8f270000>] 0x8f270000 [nf_flow_table@8f270000+0x3370]
Dec 26 04:25:15 portcullis kernel: [ 2585.869309] [<800742b4>] 0x800742b4
Dec 26 04:25:15 portcullis kernel: [ 2585.876241] [<80074358>] 0x80074358
Dec 26 04:25:15 portcullis kernel: [ 2585.883167] [<80332644>] 0x80332644
Dec 26 04:25:15 portcullis kernel: [ 2585.890095] [<80078510>] 0x80078510
Dec 26 04:25:15 portcullis kernel: [ 2585.897024] [<800735e0>] 0x800735e0
Dec 26 04:25:15 portcullis kernel: [ 2585.903949] [<800735e0>] 0x800735e0
Dec 26 04:25:15 portcullis kernel: [ 2585.910876] [<8025bd98>] 0x8025bd98
Dec 26 04:25:15 portcullis kernel: [ 2585.917803] [<8025bc44>] 0x8025bc44
Dec 26 04:25:15 portcullis kernel: [ 2585.924730] [<8025be04>] 0x8025be04
Dec 26 04:25:15 portcullis kernel: [ 2585.931658] [<800735e0>] 0x800735e0
Dec 26 04:25:15 portcullis kernel: [ 2585.938586] [<804a475c>] 0x804a475c
Dec 26 04:25:15 portcullis kernel: [ 2585.945512] [<8025b4c0>] 0x8025b4c0
Dec 26 04:25:15 portcullis kernel: [ 2585.952450] [<80007488>] 0x80007488
Dec 26 04:25:15 portcullis kernel: [ 2585.959376]
</code>

**Comment by ynezz** [comment]
Try to reproduce it with latest [22.03-rc2](https://downloads.openwrt.org/releases/22.03.0-rc2/targets/) or [development snapshot](https://downloads.openwrt.org/snapshots/targets/) and report back, we can re-open the ticket.
