### ISSUE TITLE
FS#3539 - ramips/mt7620 snapshot does not boot

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8576]
*reiffert:*

It's happening on
- ramips/mt7620 D-Link DWR 960 with the snapshot of 2020/12/26
- r14281 from 2020/08/26 is working good.

- Steps to reproduce:

Install the factory image onto the stock firmware - or - install the sysupgrade onto the running r14281.

- Findings:

The snapshot version is booted when attempting to get into JBOOT but doesn't come up automatically.

Please guide/advise. Thank you.
Thomas

- Console output:

1. Regular/Working:
CDG56CDL_0T3 Jboot B972
JRecovery Version R1.2 2016/11/15 14:11
spi device id: ef 40 18 0 0 (40180000)
SPI FLASH: W25Q128FV 16M
.
....................
Starting kernel @ 80000000 ...

2. Bricked state, regular boot:
CDG56CDL_0T3 Jboot B972
JRecovery Version R1.2 2016/11/15 14:11
spi device id: ef 40 18 0 0 (40180000)
SPI FLASH: W25Q128FV 16M
.
.<nothing from here>

3. Bricked state, booting into JBOOT (Hold reset button, power on)
CDG56CDL_0T3 Jboot B972
JRecovery Version R1.2 2016/11/15 14:11
spi device id: ef 40 18 0 0 (40180000)
SPI FLASH: W25Q128FV 16M
.
Reset button had been pressed.    <Release Reset button here>
....................
Starting kernel @ 80000000 ...
and the snapshot is booted

4. JBOOT in working state:

CDG56CDL_0T3 Jboot B972
JRecovery Version R1.2 2016/11/15 14:11
spi device id: ef 40 18 0 0 (40180000)
SPI FLASH: W25Q128FV 16M
.
Reset button had been pressed.
Reset button had been pressed
IP = 192.168.123.254 NA = XX:XX:XX:XX:XX:XX

mtd layout on working r14281 (2020/08/26):
root@OpenWrt:~# cat /proc/mtd 
dev:    size   erasesize  name
mtd0: 00010000 00001000 "jboot"
mtd1: 00fe0000 00001000 "firmware"
mtd2: 001fc82e 00001000 "kernel"
mtd3: 00de37d2 00001000 "rootfs"
mtd4: 00b4d000 00001000 "rootfs_data"
mtd5: 00010000 00001000 "config"
root@OpenWrt:~#

**Comment by CHKDSK88** [comment]
@aparcar 

With https://github.com/openwrt/openwrt/pull/4249 and https://github.com/openwrt/openwrt/pull/4255 this was resolved.

This issue could be closed.
