### ISSUE TITLE
FS#3552 - Linksys RE6500 bootloops with latest snapshots

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8577]
*bjonglez:*

The RE6500 was working fine on an old 19.07 snapshot: OpenWrt 19.07-SNAPSHOT r10578-b3d70f628b

I sysupgraded to latest snapshot and it does not come up. Judging from the LEDs, it seems to bootloop.

Booting the latest snapshot initramfs through TFTP works. I sysupgraded again from the initramfs, and it still bootloops.

Possibly related to FS#3539. I will try to get a serial output to see what happens.

**Comment by arinc9** [comment]
@vemek we could enable lzma compression for this device. I had the same issue on GB-PC1 & GB-PC2 which have 32MB flash. Are you able to compile an image yourself? I can send a patch for you to test.

**Comment by vemek** [comment]
@arinc9 absolutely, I can test that 👍

**Comment by arinc9** [comment]
I won't have time to properly put up a patch, let me explain so you can manually do it.

Find re6500 section at target/linux/ramips/image/mt7621.mk

Copy `$(Device/uimage-lzma-loader)` under dsa-migration option. Check other devices for an example.

Compile and see if sysupgrade installation boots.

**Comment by vemek** [comment]
Hey @arinc9 - that worked perfectly once I added LZMA compression! 🚀 Thanks for that and for the improvements to the mt7621 stuff! Do you have time to open a one-liner patch for that target config? I can do it otherwise - though I don't have context on what size limit is being hit without it.

**Comment by arinc9** [comment]
I'm still on an ongoing Eurotrip so I'm going to leave it to you to deal with patching. I don't know what to say about the size limit on the patch log but just saying that it would exceed size limit without lzma compression is good enough in my book.
