### ISSUE TITLE
FS#3569 - R7800: WDS-client / AP "Failed to set beacon parameters" 

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8595]
*Razerwire:*

Dear Sir/Madam, 

Using the R7800 running on 19.0.7.5 as a wireless-repeater (WDS-client / virtual radio as AP) the latter (AP radio) on 5Ghz  will fail to bringup the radio:
//Sun Jan  3 21:51:15 2021 daemon.err hostapd: Failed to set beacon parameters
Sun Jan  3 21:51:21 2021 daemon.err hostapd: Failed to set beacon parameters
Sun Jan  3 21:51:27 2021 daemon.err hostapd: Failed to set beacon parameters
Sun Jan  3 21:51:33 2021 daemon.err hostapd: Failed to set beacon parameters
Sun Jan  3 21:51:39 2021 daemon.err hostapd: Failed to set beacon parameters
Sun Jan  3 21:51:45 2021 daemon.err hostapd: Failed to set beacon parameters//

Mind you, I've configured the repeater twice from scratch however the issue persists.

Oddly enough the issue only affects 5Ghz, the 2.4Gzh radio function fine as WDS-client/repeater.  

Excerpts of logs from the R7800 running as repeater are attached, as well as a copy of the WiFi config, are attached,

**Comment by Djfe** [comment]
@hauke this is a duplicate of #6089 Please close it
