### ISSUE TITLE
FS#3598 - Trival Relay (trelay) should set up the relayed port into promiscuous mode

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8627]
*wrobelda:*

Supply the following if possible:
 - Device problem occurs on
//VirtIO NIC//
 - Software versions of OpenWrt/LEDE release, packages, etc.
//OpenWrt 19.07.6 r11278
kmod-trelay - 4.14.215+0.1-2//

 - Steps to reproduce
Set up trival relay, /etc/config/trelay:

//config trelay
	option enabled	1
	option dev1	eth0
	option dev2	wlan0   //

The relay works only if eth0 is put in promiscuous mode. This can be easily handled by updating /etc/init.d/trelay to set it up automatically:

//	ip link set dev "$dev1" up
        ip link set dev "$dev1" promisc on
	ip link set dev "$dev2" up //

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.

**Comment by Tungsteno74** [comment]
Hi,
with snapshot r19801-230c9da963 do not work with promiscuous mode ON. Works only with a client maccaddr in the Station (AP)  section.
Another problem is that do not work as repeater (bridge wifi-to-wifi).
