### ISSUE TITLE
FS#3599 - TP-Link Archer C7 v2 - Wireless module 2.4GHz stop working when Xbox One S connect

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8628]
*Boia11:*

Supply the following if possible:
 - Device: TP-Link Archer C7 v2(ath79)
 - Software versions of OpenWrt: OpenWrt 19.07.6 r11278-8055e38794 / LuCI openwrt-19.07 branch git-21.022.31068-7129723
 - Steps to reproduce: 
   * Turn On XBox One S
   * Wireless module 2.4GHz stop working...devices disconnect and can't reconnect to the router
   * Reboot or only restart 2.4GHz module from webGUI-Network-Wireless
Now I try to disable option "Disassociate On Low Acknowledgement"

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
