### ISSUE TITLE
FS#3600 - [odhcp6c] prefix exclude sanity check fails for prefix length > 64

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8629]
*oofnikj:*

odhcp6c fails to request a delegated prefix when the server returns an excluded prefix of length > 64.

According to [[https://tools.ietf.org/html/rfc6603#section-4.2|RFC 6603]]:

>   o  prefix-len: The length of the excluded prefix in bits.  The
prefix-len MUST be between 'OPTION_IAPREFIX prefix-length'+1 and
128.

However, values for excluded prefix length > 64 fail sanity, resulting in odhcp6c dropping the PD from the request.

The following patch fixes the issue.

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
