### ISSUE TITLE
FS#3602 - odhcpd seems to not respond to requests sent on dynamicly created interfaces

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8634]
*Newy:*

Supply the following if possible:
 - Device problem occurs on
 - Software versions of OpenWrt/LEDE release, packages, etc.
 - Steps to reproduce
   
 18.06.5, r789

on x86 ( VIA Samuel 2 )

odhcpd seems to not respond to requests sent on dynamicly created interfaces ppp1, ppp2 ... etc. I have ensured that ipv6 comms are occuring over the pppoe links and that link local addresses are in communication but no further negotioation happens.
I'm guessing i'm the only person trying to use pppoe to a downstream router using openwrt, but it'd be nice if it worked !
Cheers.

**Comment by ynezz** [comment]
Try to reproduce with latest release and feel free to ask for issue reopening if the problem is still present, thanks.
