### ISSUE TITLE
FS#3605 - 5Ghz performance of 19.07.6 with TP-Link Archer C6 is very bad

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8637]
*NilsRo:*

After installing OpenWrt on TP-Link Archer C6 V2 EU I ran into issues with 5Ghz performance. This is already described on the official OpenWrt page of the device but I could not find a ticket for it. So I like to create one.

Behaviour: max. 5Ghz performance is round about 150Mbit - 200Mbit. This is not the case for stock firmware.
OpenWrt 19.07.6

Reproduction should be easy as it is still noted as a general issue in the device page and it is constantly slow.

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
