### ISSUE TITLE
FS#3610 - qos-scripts: default classifications overrides previous classifications

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8641]
*AIexBV:*

My understanding is, that the default classification is intended to classifiy not yet classified packets. But default classification ignores/overrides all previous classifications set by the CONNMARK restore.

Refering the attached screenshot, the CONNMARK restore with mask 0xf. Later on the default classification masks against 0xf0. That leads to a missmatch between the CONNTRACK restore and the default classification. So all CONNTRACK marked packets will be overriden by the default rules.
Actually that means that the default classification can not be used.

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
