### ISSUE TITLE
FS#3613 - Overestimated entropy in urgnd

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8644]
*kroeckx:*

I was looking at the entropy collected by the jitterentropy library that urngd is using. I've filed a bug against the library at https://github.com/smuellerDD/jitterentropy-library/issues/21

What I'm seeing it that is overestimates the amount of entropy collected. On my desktop machine this is at least a factor of 100. I've not looked at any of my devices using OpenWRT yet, but I expect it to be worse there.

Urngd has an oversampling factor, which is currently set to 2, meaning the factor is 2 time smaller. The oversampling in urngd currently collects twice as many bytes (64), and then tells the kernel that it contains 32 byte / 256 bit of entropy. The library also supports oversampling itself, it's a parameter to the jent_entropy_collector_alloc function.

I suggest that you set the oversampling factor to at least 1000.

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.

**Comment by champtar** [comment]
@kroeckx could you check this is still relevant ?
