### ISSUE TITLE
FS#3615 - Kirkwood: the build stops for input when make with V=s or V=sc

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8646]
*builker:*

When building Kirkwood images off the trunk, r15696-17fa01bb79, make -j1 V=s or make -j1 V=sc stops. A <return> can get it going. Without V=s or V=sc, the build doesn't stop for input. Please find the make.log below.
<code>
make[5]: Entering directory '/home/builder/openwrt/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.95'
Makefile:632: include/config/auto.conf: No such file or directory
Makefile:678: include/config/auto.conf.cmd: No such file or directory
make -f ./Makefile syncconfig
make -f ./scripts/Makefile.build obj=scripts/basic
rm -f .tmp_quiet_recordmcount
make -f ./scripts/Makefile.build obj=scripts/kconfig syncconfig
  gcc -Wp,-MD,scripts/kconfig/.conf.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89  -O2 -I/home/builder/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes   -I/home/builder/openwrt/staging_dir/host/include  -c -o scripts/kconfig/conf.o scripts/kconfig/conf.c
  gcc -Wp,-MD,scripts/kconfig/.confdata.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89  -O2 -I/home/builder/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes   -I/home/builder/openwrt/staging_dir/host/include  -c -o scripts/kconfig/confdata.o scripts/kconfig/confdata.c
  gcc -Wp,-MD,scripts/kconfig/.expr.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89  -O2 -I/home/builder/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes   -I/home/builder/openwrt/staging_dir/host/include  -c -o scripts/kconfig/expr.o scripts/kconfig/expr.c
  flex -oscripts/kconfig/lexer.lex.c -L scripts/kconfig/lexer.l
  bison -o scripts/kconfig/parser.tab.c --defines=scripts/kconfig/parser.tab.h -t -l scripts/kconfig/parser.y
  gcc -Wp,-MD,scripts/kconfig/.lexer.lex.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89  -O2 -I/home/builder/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes   -I/home/builder/openwrt/staging_dir/host/include -I ./scripts/kconfig -c -o scripts/kconfig/lexer.lex.o scripts/kconfig/lexer.lex.c
  gcc -Wp,-MD,scripts/kconfig/.parser.tab.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89  -O2 -I/home/builder/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes   -I/home/builder/openwrt/staging_dir/host/include -I ./scripts/kconfig -c -o scripts/kconfig/parser.tab.o scripts/kconfig/parser.tab.c
  gcc -Wp,-MD,scripts/kconfig/.preprocess.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89  -O2 -I/home/builder/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes   -I/home/builder/openwrt/staging_dir/host/include  -c -o scripts/kconfig/preprocess.o scripts/kconfig/preprocess.c
  gcc -Wp,-MD,scripts/kconfig/.symbol.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89  -O2 -I/home/builder/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes   -I/home/builder/openwrt/staging_dir/host/include  -c -o scripts/kconfig/symbol.o scripts/kconfig/symbol.c
  gcc   -o scripts/kconfig/conf scripts/kconfig/conf.o scripts/kconfig/confdata.o scripts/kconfig/expr.o scripts/kconfig/lexer.lex.o scripts/kconfig/parser.tab.o scripts/kconfig/preprocess.o scripts/kconfig/symbol.o -L/home/builder/openwrt/staging_dir/host/lib 
scripts/kconfig/conf  --syncconfig Kconfig
net/sched/Kconfig:45: warning: menuconfig statement without prompt
*
* Restart config...
*
*
* I2C Hardware Bus support
*
*
* PC SMBus host controller drivers
*
ALI 1535 (I2C_ALI1535) [N/m/y/?] n
ALI 1563 (I2C_ALI1563) [N/m/y/?] n
ALI 15x3 (I2C_ALI15X3) [N/m/y/?] n
AMD 756/766/768/8111 and nVidia nForce (I2C_AMD756) [N/m/y/?] n
AMD 8111 (I2C_AMD8111) [N/m/y/?] n
Intel 82801 (ICH/PCH) (I2C_I801) [N/m/y/?] n
Intel SCH SMBus 1.0 (I2C_ISCH) [N/m/y/?] n
Intel PIIX4 and compatible (ATI/AMD/Serverworks/Broadcom/SMSC) (I2C_PIIX4) [N/m/y/?] n
Nvidia nForce2, nForce3 and nForce4 (I2C_NFORCE2) [N/m/y/?] n
NVIDIA GPU I2C controller (I2C_NVIDIA_GPU) [N/m/y/?] n
SiS 5595 (I2C_SIS5595) [N/m/y/?] n
SiS 630/730/964 (I2C_SIS630) [N/m/y/?] n
SiS 96x (I2C_SIS96X) [N/m/y/?] n
VIA VT82C586B (I2C_VIA) [N/m/y/?] n
VIA VT82C596/82C686/82xx and CX700/VX8xx/VX900 (I2C_VIAPRO) [N/m/y/?] n
*
* I2C system bus drivers (mostly embedded / system-on-chip)
*
CBUS I2C driver (I2C_CBUS_GPIO) [N/m/y/?] n
Synopsys DesignWare Platform (I2C_DESIGNWARE_PLATFORM) [N/m/y/?] n
Synopsys DesignWare PCI (I2C_DESIGNWARE_PCI) [N/m/y/?] n
EMMA Mobile series I2C adapter (I2C_EMEV2) [N/m/y/?] n
GPIO-based bitbanging I2C (I2C_GPIO) [M/n/y/?] m
  GPIO-based fault injector (I2C_GPIO_FAULT_INJECTOR) [N/y/?] n
Marvell mv64xxx I2C Controller (I2C_MV64XXX) [Y/n/m/?] y
OpenCores I2C Controller (I2C_OCORES) [N/m/y/?] n
PCA9564/PCA9665 as platform device (I2C_PCA_PLATFORM) [N/m/y/?] n
Intel PXA2XX I2C adapter (I2C_PXA) [M/n/y/?] m
Intel PXA2XX I2C Slave comms support (I2C_PXA_SLAVE) [N/y/?] (NEW) 
</code>

**Comment by CHKDSK88** [comment]
@aparcar 
Fixed by: https://github.com/openwrt/openwrt/commit/8d766aa669702f8291a95f985a0b4dd16b1cca2d

Could be closed.
