### ISSUE TITLE
FS#3620 - Remote desktop unusable with software flow offloading

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8649]
*2MEX2:*

I have latest stable OpenWrt 19.07.6 r11278 installed to my TP-Link TL-WDR4900 v1.
I have a port forward to a Windows RDP or using TeamViewer remote management.
When the Software flow offloading ENABLED, Windows RDP or TeamViewer remote management connection become slow and laggy.

If I disable everything works quickly without lags.

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
