### ISSUE TITLE
FS#3622 - TP-Link Archer A7 v5: No LAN LED activity 

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8653]
*BOFH2k:*

Device: TP-Link Archer A7 (DE) V5
Software: OpenWRT 19.07.6 r11278-8055e38794

None of the LAN LEDs on the device seem to function, just the ones for 2,4 and 5 GHz Wifi.
According to the switch0 section in LuCI, there is a 1000baseT full-duplex link on LAN1 and WAN and - apart from the corresponding LAN LEDs - the router functions just fine.

The Archer A7 replaces a TP-Link TL-WDR4900 v1 (with imported 19.07.6 backup of latter config, I had to reassign the Wireless deifinitions via ssh), where the LEDs flashed on LAN packet activity (WAN and LAN1 connected). The LED configuration section in LuCi is empty (standard).

Could this issue be connected to the config import?
Just let me know if there is any info I could provide, to aid in analyzing the issue further.

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
