### ISSUE TITLE
FS#2628 - Kernel warning / crash on ramips: eth0 (mtk_soc_eth): transmit queue 0 timed out

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8660]
*jarekera:*

Model ZBT-WG3526 (16M)
Architecture - MediaTek MT7621 ver:1 eco:3
Firmware version - OpenWrt 19.07-SNAPSHOT r10731-e68d589e7b / LuCI openwrt-19.07 branch git-19.326.61751-179c5e8
Kernel version- 4.14.155

<code>
 Mon Nov 25 10:11:25 2019 kern.info kernel: [  106.762093] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
Mon Nov 25 10:11:25 2019 kern.info kernel: [  106.770348] br-VLAN8: port 2(wlan1) entered blocking state
Mon Nov 25 10:11:25 2019 kern.info kernel: [  106.775981] br-VLAN8: port 2(wlan1) entered forwarding state
Mon Nov 25 10:11:25 2019 kern.info kernel: [  106.784594] br-VLAN6: port 3(wlan1-1) entered blocking state
Mon Nov 25 10:11:25 2019 kern.info kernel: [  106.790393] br-VLAN6: port 3(wlan1-1) entered disabled state
Mon Nov 25 10:11:25 2019 kern.info kernel: [  106.796955] device wlan1-1 entered promiscuous mode
Mon Nov 25 10:11:25 2019 kern.info kernel: [  106.803794] IPv6: ADDRCONF(NETDEV_UP): wlan1-1: link is not ready
Mon Nov 25 10:11:25 2019 kern.info kernel: [  106.810026] br-VLAN6: port 3(wlan1-1) entered blocking state
Mon Nov 25 10:11:25 2019 kern.info kernel: [  106.815820] br-VLAN6: port 3(wlan1-1) entered forwarding state
Mon Nov 25 10:11:25 2019 kern.info kernel: [  107.343567] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1-1: link becomes ready
Mon Nov 25 11:10:20 2019 kern.info kernel: [ 3641.266434] nf_conntrack: default automatic helper assignment has been turned off for security reasons and CT-based  firewall rule not found. Use the iptables CT target to attach helpers instead.
Mon Nov 25 11:37:14 2019 kern.info kernel: [ 5255.651116] TCP: request_sock_TCP: Possible SYN flooding on port 88. Sending cookies.  Check SNMP counters.
Mon Nov 25 11:41:29 2019 kern.warn kernel: [ 5510.958004] ------------[ cut here ]------------
Mon Nov 25 11:41:29 2019 kern.warn kernel: [ 5510.962647] WARNING: CPU: 1 PID: 0 at net/sched/sch_generic.c:320 0x8038e1c0
Mon Nov 25 11:41:29 2019 kern.info kernel: [ 5510.969709] NETDEV WATCHDOG: eth0 (mtk_soc_eth): transmit queue 0 timed out
Mon Nov 25 11:41:29 2019 kern.warn kernel: [ 5510.976660] Modules linked in: qcserial pppoe ppp_async option cdc_mbim usb_wwan sierra_net sierra rndis_host qmi_wwan pppox ppp_generic nf_nat_pptp nf_conntrack_pptp nf_conntrack_ipv6 mt76x2e mt76x2_common mt76x02_lib mt7603e mt76 mac80211 iptable_nat ipt_REJECT ipt_MASQUERADE huawei_cdc_ncm cfg80211 cdc_ncm cdc_ether xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_FLOWOFFLOAD xt_DSCP xt_CT xt_CLASSIFY wireguard usbserial usbnet usblp ts_fsm ts_bm slhc nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_redirect nf_nat_proto_gre nf_nat_masquerade_ipv4 nf_nat_irc nf_conntrack_ipv4 nf_nat_ipv4
Mon Nov 25 11:41:29 2019 kern.warn kernel: [ 5511.047339]  nf_nat_h323 nf_nat_amanda nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_rtcache nf_conntrack_proto_gre nf_conntrack_irc nf_conntrack_h323 nf_conntrack_broadcast ts_kmp nf_conntrack_amanda nf_conntrack iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt compat cdc_wdm cdc_acm fuse ledtrig_usbport xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT
Mon Nov 25 11:41:29 2019 kern.warn kernel: [ 5511.118581]  x_tables nf_reject_ipv6 ip6_udp_tunnel udp_tunnel tun vfat fat nls_utf8 nls_iso8859_1 nls_cp437 uas mmc_block usb_storage mtk_sd mmc_core leds_gpio xhci_plat_hcd xhci_pci xhci_mtk xhci_hcd ahci libahci libata ehci_platform sd_mod scsi_mod ehci_hcd gpio_button_hotplug ext4 mbcache jbd2 usbcore nls_base usb_common mii crc32c_generic
Mon Nov 25 11:41:29 2019 kern.warn kernel: [ 5511.149081] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 4.14.155 #0
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.155177] Stack : 00000000 00000000 00000000 8fe6d540 00000000 00000000 00000000 00000000
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.163556]         00000000 00000000 00000000 00000000 00000000 00000001 8fc0bd60 ac07f582
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.171942]         8fc0bdf8 00000000 00000000 000093c8 00000038 8049e458 00000008 00000000
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.180305]         00000000 80550000 00024659 00000000 8fc0bd40 00000000 00000000 8050c830
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.188647]         8038e1c0 00000140 00000001 8fe6d540 00000000 802b02b8 00000004 805b0004
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.196980]         ...
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.199415] Call Trace:
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.199535] [<8049e458>] 0x8049e458
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.205440] [<8038e1c0>] 0x8038e1c0
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.208923] [<802b02b8>] 0x802b02b8
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.212412] [<800101a0>] 0x800101a0
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.215881] [<800101a8>] 0x800101a8
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.219354] [<804873a4>] 0x804873a4
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.222825] [<800759a0>] 0x800759a0
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.226315] [<800325b8>] 0x800325b8
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.229802] [<8038e1c0>] 0x8038e1c0
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.233316] [<80032640>] 0x80032640
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.236785] [<800d20e8>] 0x800d20e8
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.240287] [<8038e1c0>] 0x8038e1c0
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.243757] [<8009d860>] 0x8009d860
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.247237] [<8038e014>] 0x8038e014
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.250711] [<8008c3dc>] 0x8008c3dc
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.254181] [<80063108>] 0x80063108
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.257662] [<8008c698>] 0x8008c698
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.261136] [<8007cfe8>] 0x8007cfe8
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.264627] [<804a5240>] 0x804a5240
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.268102] [<80036f74>] 0x80036f74
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.271573] [<8025daf0>] 0x8025daf0
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.275054] [<8000b488>] 0x8000b488
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.278548]
Mon Nov 25 11:41:30 2019 kern.warn kernel: [ 5511.280144] ---[ end trace f0b0ca1dd55db7a7 ]---
Mon Nov 25 11:41:30 2019 kern.err kernel: [ 5511.284782] mtk_soc_eth 1e100000.ethernet eth0: transmit timed out
Mon Nov 25 11:41:30 2019 kern.info kernel: [ 5511.291016] mtk_soc_eth 1e100000.ethernet eth0: dma_cfg:80000065
Mon Nov 25 11:41:30 2019 kern.info kernel: [ 5511.297053] mtk_soc_eth 1e100000.ethernet eth0: tx_ring=0, base=0dc00000, max=0, ctx=1789, dtx=1789, fdx=1788, next=1789
Mon Nov 25 11:41:30 2019 kern.info kernel: [ 5511.307977] mtk_soc_eth 1e100000.ethernet eth0: rx_ring=0, base=0db60000, max=0, calc=893, drx=894
Mon Nov 25 11:41:30 2019 kern.info kernel: [ 5511.321091] mtk_soc_eth 1e100000.ethernet: 0x100 = 0x6060000c, 0x10c = 0x80818
Mon Nov 25 11:41:30 2019 kern.info kernel: [ 5511.334877] mtk_soc_eth 1e100000.ethernet: PPE started

</code>

**Comment by rozhuk-im** [comment]
Got similar issue with DIR-506L: http://netlab.dhis.org/wiki/hardware:d-link:dir-506l
Happen only on boot or on network settings change.

Workaround 1: unplug net cable untill device started
Workaround 2: remove switch from existing network configuration or build f/w without defined switch in 02_network and reset config on/after update

**Comment by Camis** [comment]
Router crashes every 1-3 days or so, unresponsive. Sometimes it will reset itself after this error. This problem has been occurring since early version 19.07.



```
Model	Netgear R6220
Architecture	MediaTek MT7621 ver:1 eco:3
Firmware Version	OpenWrt 19.07.8 r11364-ef56c85848 / LuCI openwrt-19.07 branch git-21.279.78820-fde7889
Kernel version-  4.14.241
```

```
[76219.076181] ------------[ cut here ]------------
[76219.085402] WARNING: CPU: 1 PID: 0 at net/sched/sch_generic.c:320 0x8038f110
[76219.099443] NETDEV WATCHDOG: eth0 (mtk_soc_eth): transmit queue 0 timed out
[76219.113310] Modules linked in: pppoe ppp_async pppox ppp_generic nf_conntrack_ipv6 mt76x2e mt76x2_common mt76x02_lib mt7603e mt76 mac80211 iptable_nat ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_FLOWOFFLOAD xt_CT wireguard slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc_ccitt compat ledtrig_usbport nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 ip6_udp_tunnel udp_tunnel leds_gpio xhci_plat_hcd xhci_pci xhci_mtk xhci_hcd gpio_button_hotplug
[76219.255846]  usbcore nls_base usb_common
[76219.263689] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 4.14.241 #0
[76219.275803] Stack : 00000000 00000000 00000000 87f25340 00000000 00000000 00000000 00000000
[76219.292434]         00000000 00000000 00000000 00000000 00000000 00000001 87c0bd60 53261610
[76219.309066]         87c0bdf8 00000000 00000000 000071f0 00000038 804a02f8 00000008 00000000
[76219.325698]         00000000 80550000 00040609 00000000 87c0bd40 00000000 00000000 8050f6e4
[76219.342330]         8038f110 00000140 00000001 87f25340 00000000 802af880 00000004 806b0004
[76219.358963]         ...
[76219.363820] Call Trace:
[76219.363836] [<804a02f8>] 0x804a02f8
[76219.375609] [<8038f110>] 0x8038f110
[76219.382539] [<802af880>] 0x802af880
[76219.389470] [<8000c1a0>] 0x8000c1a0
[76219.396402] [<8000c1a8>] 0x8000c1a8
[76219.403329] [<80580000>] 0x80580000
[76219.410257] [<80489024>] 0x80489024
[76219.417189] [<80071eb0>] 0x80071eb0
[76219.424119] [<8002e788>] 0x8002e788
[76219.431048] [<8038f110>] 0x8038f110
[76219.437980] [<8002e810>] 0x8002e810
[76219.444914] [<877c1b04>] 0x877c1b04 [mt7603e@877c0000+0x9100]
[76219.456337] [<800553e8>] 0x800553e8
[76219.463264] [<8038f110>] 0x8038f110
[76219.470195] [<8038ef64>] 0x8038ef64
[76219.477128] [<80088a48>] 0x80088a48
[76219.484055] [<80088d04>] 0x80088d04
[76219.490982] [<800795a8>] 0x800795a8
[76219.497917] [<804a7108>] 0x804a7108
[76219.504847] [<80033154>] 0x80033154
[76219.511777] [<8025c6f0>] 0x8025c6f0
[76219.518711] [<80007488>] 0x80007488
[76219.525636] 
[76219.528692] ---[ end trace 911f450294183722 ]---
```

**Comment by ynezz** [comment]
Try to reproduce it with latest [22.03-rc2](https://downloads.openwrt.org/releases/22.03.0-rc2/targets/) or [development snapshot](https://downloads.openwrt.org/snapshots/targets/) and report back, we can re-open the ticket.
