### ISSUE TITLE
FS#3629 - Not able to Flash Current OpenWRT 19.07.7 on Archer A7 v5

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8666]
*skom91:*

I have a TP-Link Archer A7 v5. I already had OpenWrt installed on it, but for testing a flashed back the Stock Firmware [1.1.0 Build 20201120 rel.50399(4555)]

After that i was not able to Flash the OpenWrt Firmware. I Have a serial console with the following output:
<code>1.1.0 Build 20201120 rel.50399	
upgrade firmware...	
true	
file_len:4491641
md5 verify ok!
[Error]sysmgr_proinfo_buildStruct():  605 @ unknown id(device_name), skip it.
[Error]sysmgr_proinfo_buildStruct():  605 @ unknown id(hw_id), skip it.
[Error]sysmgr_proinfo_buildStruct():  605 @ unknown id(oem_id), skip it.
[Error]sysmgr_proinfo_buildStruct():  605 @ unknown id(country), skip it.
[Error]sysmgr_proinfo_buildStruct():  605 @ unknown id(hw_ver), skip it.
--------------------------------------------------------------------
      vendorName : TP-Link
       vendorUrl : www.tp-link.com
     productName : Archer A7
 productLanguage : EU
       productId : 00070005
      productVer : ff050000
       specialId : 45550000
           hwlId : 
           oemId : 
--------------------------------------------------------------------
Firmwave supports, check OK.
 (curFw_ver, newFw_ver) == (1.1, 1.0) [NM_Error](nm_checkSoftVer) 00848: Firmwave not supports, check failed.

[NM_Error](nm_checkUpdateContent) 01084: software version dismatched
[NM_Error](nm_buildUpgradeStruct) 01188: checkUpdateContent failed.

check firmware error!
[NM_Error](nvrammanager_verifyFirmware) 00476: upgradeFirmware failed
</code>

Is this maby because of the Version that is named in the Firmware and can this be fixed?

Thank you for your work!

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
