### ISSUE TITLE
FS#3636 - missing /etc/tor/data crash tor service : TOR do not start because of a missing required folder

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8672]
*erdoukki:*

In All 19.07.x versions :

Feb 21 09:51:19 LPM procd: Instance tor::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Feb 21 09:52:49 LPM procd: Instance tor::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

root@LPM:~# tor
Feb 21 10:51:51.580 [notice] Tor 0.4.4.5 running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1j, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Feb 21 10:51:51.580 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 21 10:51:51.580 [notice] Read configuration file "/etc/tor/torrc".
Feb 21 10:51:51.591 [warn] Skipping obsolete configuration option "AllowInvalidNodes".
Feb 21 10:51:51.592 [warn] Skipping obsolete configuration option "TransListenAddress".
Feb 21 10:51:51.592 [warn] Skipping obsolete configuration option "DNSListenAddress".
Feb 21 10:51:51.593 [warn] Skipping obsolete configuration option "SocksListenAddress".
Feb 21 10:51:51.608 [notice] You configured a non-loopback address '10.4.2.1:9050' for SocksPort. This allows everybody on your local network to use your machine as a proxy. Make sure this is what you wanted.
Feb 21 10:51:51.609 [notice] Opening Socks listener on 127.0.0.1:9050
Feb 21 10:51:51.610 [notice] Opened Socks listener on 127.0.0.1:9050
Feb 21 10:51:51.611 [notice] Opening Socks listener on 10.4.2.1:9050
Feb 21 10:51:51.611 [notice] Opened Socks listener on 10.4.2.1:9050
Feb 21 10:51:51.612 [notice] Opening DNS listener on 127.0.0.1:9053
Feb 21 10:51:51.612 [notice] Opened DNS listener on 127.0.0.1:9053
Feb 21 10:51:51.612 [notice] Opening Transparent pf/netfilter listener on 127.0.0.1:9040
Feb 21 10:51:51.612 [notice] Opened Transparent pf/netfilter listener on 127.0.0.1:9040
Feb 21 10:51:51.613 [warn] /etc/tor/data/ is not owned by this user (tor, 52) but by root (0). Perhaps you are running Tor as the wrong user?
Feb 21 10:51:51.613 [notice] Closing partially-constructed Socks listener on 127.0.0.1:9050
Feb 21 10:51:51.613 [notice] Closing partially-constructed Socks listener on 10.4.2.1:9050
Feb 21 10:51:51.614 [notice] Closing partially-constructed DNS listener on 127.0.0.1:9053
Feb 21 10:51:51.614 [notice] Closing partially-constructed Transparent pf/netfilter listener on 127.0.0.1:9040
Feb 21 10:51:51.615 [warn] Failed to parse/validate config: Couldn't create private data directory "/etc/tor/data/"
Feb 21 10:51:51.616 [err] Reading config failed--see warnings above.

FIXME : 
mkdir /etc/tor/data/
chown tor:tor /etc/tor/data/
service tor restart
--> OK

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
