### ISSUE TITLE
FS#3642 - ip2d fails to configure and run on install

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8679]
*nelgin:*

Supply the following if possible:
 - Device problem occurs on
 - Software versions of OpenWrt/LEDE release, packages, etc.
 - Steps to reproduce
   

Running on a Netgear R6220
Firmware OpenWrt 19.07.2 r10947-65030d81f3 / LuCI openwrt-19.07 branch git-21.054.03371-3b137b5

Using the LuCI web interface to install i2pd I received the postinstall messages.

mkdir: can't create directory '': No such file or directory
ln: /certificates/certificates: File exists
ln: /tunnels.conf: File exists
chown: : No such file or directory
chown: : No such file or directory

If I also try to start with service i2pd start then I get the same thing.

# service i2pd start
mkdir: can't create directory '': No such file or directory
ln: /certificates/certificates: File exists
ln: /tunnels.conf: File exists
chown: : No such file or directory
chown: : No such file or directory

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
