### ISSUE TITLE
FS#3652 - Dir 859 stranger 2.4GHz Wi-Fi

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8686]
*vct186:*

I have a dir-859 running Openwrt 19.07.7, this run stable this version and the older's, but the 2.4GHz Wi-Fi speed in most conditions is capped around 30Mb/s download speed, upload is good, i've tryed changing all wireless options in luci, like tx power or channel Bandwidth, but the result is same, i atually using channel 1@20MHz, i have another router TP-LINK TL-WR740N running DD-WRT and it can provide more than 45Mb/s over 2.4GHz@20MHz, and the DD-WRT running on same dir-859 can provide same speed's than 740n on 2.4GHz, the dir-859 can reach 40Mb/s if i run speedtest on nearest servers, but a toronto server or any server with more latency is capped to around 30Mb/s, and i only have 2.4Ghz devices :/

The dir-859 speedtest on fdcservers.net toronto: https://www.speedtest.net/my-result/a/7089190072.png

The TL-WR740N on same server: https://www.speedtest.net/my-result/a/7089192985.png

tell me the config files or log's that i have to send.

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
