### ISSUE TITLE
FS#3617 - ntpd-busybox default doesn't work with /etc/config/system configured to use the ntp client

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8806]
*andrewhodel:*

19.07.4

Specify no busybox options in menuconfig and include an /etc/config/system ntp configuration in buildroot/files/

NTP doesn't work, even though ntp exists via busybox.  If you call ntpd and tell it to query a nameserver directly, it does get a result and set the time.

You must install ntpd, it should automatically work with busybox's ntpd.

Bringing in ntpd also brings in:

CONFIG_PACKAGE_libmbedtls=y
# CONFIG_LIBMBEDTLS_DEBUG_C is not set
# CONFIG_PACKAGE_libnss is not set
# CONFIG_PACKAGE_libopenssl is not set
CONFIG_PACKAGE_libopenssl=y

#
# Build Options
#
# CONFIG_OPENSSL_OPTIMIZE_SPEED is not set
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
# CONFIG_OPENSSL_NO_DEPRECATED is not set
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y

#
# Protocol Support
#
CONFIG_OPENSSL_WITH_TLS13=y
# CONFIG_OPENSSL_WITH_DTLS is not set
# CONFIG_OPENSSL_WITH_NPN is not set
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_CMS=y

#
# Algorithm Selection
#
# CONFIG_OPENSSL_WITH_EC2M is not set
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM=y
CONFIG_OPENSSL_WITH_PSK=y

#
# Less commonly used build options
#
# CONFIG_OPENSSL_WITH_ARIA is not set
# CONFIG_OPENSSL_WITH_CAMELLIA is not set
# CONFIG_OPENSSL_WITH_IDEA is not set
# CONFIG_OPENSSL_WITH_SEED is not set
# CONFIG_OPENSSL_WITH_SM234 is not set
# CONFIG_OPENSSL_WITH_BLAKE2 is not set
# CONFIG_OPENSSL_WITH_MDC2 is not set
# CONFIG_OPENSSL_WITH_WHIRLPOOL is not set
# CONFIG_OPENSSL_WITH_COMPRESSION is not set
# CONFIG_OPENSSL_WITH_RFC3779 is not set

#
# Engine/Hardware Support
#
CONFIG_OPENSSL_ENGINE=y
# CONFIG_OPENSSL_ENGINE_BUILTIN is not set
# CONFIG_OPENSSL_WITH_GOST is not set
# CONFIG_PACKAGE_libopenssl-afalg_sync is not set
# CONFIG_PACKAGE_libopenssl-conf is not set
# CONFIG_PACKAGE_libopenssl-devcrypto is not set
# CONFIG_PACKAGE_libwolfssl is not set

#
@@ -4161,7 +4082,8 @@ CONFIG_PACKAGE_libmbedtls=y
CONFIG_PACKAGE_libblobmsg-json=y
# CONFIG_PACKAGE_libbsd is not set
# CONFIG_PACKAGE_libcanfestival is not set
# CONFIG_PACKAGE_libcap is not set
CONFIG_PACKAGE_libcap=y
# CONFIG_PACKAGE_libcap-bin is not set
# CONFIG_PACKAGE_libcares is not set
# CONFIG_PACKAGE_libcgroup is not set
# CONFIG_PACKAGE_libcharset is not set
@@ -4232,10 +4154,10 @@ CONFIG_LIBCURL_PROXY=y
# CONFIG_PACKAGE_libev is not set
# CONFIG_PACKAGE_libevdev is not set
CONFIG_PACKAGE_libevent2=y
# CONFIG_PACKAGE_libevent2-core is not set
CONFIG_PACKAGE_libevent2-core=y
# CONFIG_PACKAGE_libevent2-extra is not set
# CONFIG_PACKAGE_libevent2-openssl is not set
# CONFIG_PACKAGE_libevent2-pthreads is not set
CONFIG_PACKAGE_libevent2-pthreads=y
# CONFIG_PACKAGE_libevhtp is not set
# CONFIG_PACKAGE_libexif is not set
# CONFIG_PACKAGE_libexpat is not set
@@ -5294,9 +5216,9 @@ CONFIG_LLDPD_WITH_CUSTOM=y
# CONFIG_PACKAGE_htpdate is not set
# CONFIG_PACKAGE_linuxptp is not set
# CONFIG_PACKAGE_ntp-keygen is not set
# CONFIG_PACKAGE_ntp-utils is not set
CONFIG_PACKAGE_ntp-utils=y
# CONFIG_PACKAGE_ntpclient is not set
# CONFIG_PACKAGE_ntpd is not set
CONFIG_PACKAGE_ntpd=y
# CONFIG_PACKAGE_ntpdate is not set

**Comment by ynezz** [comment]
OpenWrt 19.07 [release is EOL](https://lists.infradead.org/pipermail/openwrt-announce/2022-April/000027.html), try to reproduce the issue with [latest supported release](https://openwrt.org/releases/start) and feel free to ask for issue reopening if the problem is still present, thanks.
