### ISSUE TITLE
TLS Server Hello selects no cipher suite at uhttpd startup

### ISSUE THREAD

**Issue by cyounkins** [openwrt/openwrt#9247]
Symptoms: Firefox shows the error "Cannot communicate securely with peer: no common encryption algorithm(s). Error code: SSL_ERROR_NO_CYPHER_OVERLAP".

When: At boot, or after `kill`ing `uhttpd`

Hardware: Ubiquiti EdgeRouter X
Firmware: OpenWrt 21.02.1 r16325-88151b8303 / LuCI openwrt-21.02 branch git-21.295.67054-13df80d

------

The issue fixes itself after some time (2-3 minutes). It seems to fix itself faster when the WAN cable is connected, but is not necessary.

Because the error message is unusual and the state can persist for minutes, I thought the device was totally broken.

While the clock at boot may be off, the issue can be reproduced after time sync. Time sync does not seem to be the cause.

While the problem primarily affects Firefox for unknown reasons, I have seen Chrome complain at the same time about "malformed data".

Packet capture reveals that initially no cipher suites are selected in the TLS Server Hello:

<img width="693" alt="Screen Shot 2022-02-15 at 1 17 39 PM" src="https://user-images.githubusercontent.com/346185/154126440-6c07c0b8-3b1f-4c0c-9f72-7657980a13ec.png">

And when it fixes itself, a suite is selected:

<img width="688" alt="Screen Shot 2022-02-15 at 1 20 22 PM" src="https://user-images.githubusercontent.com/346185/154126540-8caf564e-8d4d-474c-b16c-023d1991e2b4.png">

----

I thought low system entropy may be the cause, but the issue is reproducible by killing `uhttpd` even when `/proc/sys/kernel/random/entropy_avail` > 1000

TODO:
* Packet capture any differences between Firefox and Chrome

Forum discussion on this issue: https://forum.openwrt.org/t/firefox-ssl-error-no-cypher-overlap-wolfssl-update-strategy/113210

**Comment by ynezz** [comment]
> Firmware: OpenWrt 21.02.1 r16325-88151b8303 / LuCI openwrt-21.02 branch git-21.295.67054-13df80d

Would it be possible to reproduce it with [21.02-SNAPSHOT](https://downloads.openwrt.org/releases/21.02-SNAPSHOT/) which is almost 21.02.2 and should contain wolfssl 5.1.1 (you're using 4.8.1).

**Comment by cyounkins** [comment]
I was not able to reproduce it with the linked snapshot "OpenWrt 21.02-SNAPSHOT r16485-59e7ae8d65" so I'll close this for now. If someone is able to reproduce with 21.02.2 or later, please re-open.
