### ISSUE TITLE
please support rockchip RK3568 soc！！！！

### ISSUE THREAD

**Issue by byronlili** [openwrt/openwrt#9263]
many many thanks

**Comment by svlobanov** [comment]
Is your board supported by armbian? If yes, you can try to boot armvirt/64 kernel+initrd using uboot+dts from armbian

**Comment by ysc3839** [comment]
@svlobanov No. But there's Debian-based OS for this chip.
https://wiki.radxa.com/Rock3/dev

**Comment by svlobanov** [comment]
> @svlobanov No. But there's Debian-based OS for this chip. https://wiki.radxa.com/Rock3/dev

Looks like it uses k4.19 from vendor, I can't find kernel mainline status for RK3568. If it works only on k4.19, then a lot of development and upstreaming is required to support RK3568 based boards in OpenWrt

**Comment by Lactococcuslactis** [comment]
you can install it in docker
