### ISSUE TITLE
How could I enable Intel SGX into my openwrt build image

### ISSUE THREAD

**Issue by leyao-daily** [openwrt/openwrt#9268]
Is there any notes for it? Or should I recognize the SGX as a 3rd application and cross-compile it into openwrt image?

**Comment by jow-** [comment]
This functionality is not supported by OpenWrt.

**Comment by leyao-daily** [comment]
Sorry, maybe I make a mistake. What I mean is that if i have some 3rd libraries and applications, and I want to build them into my openwrt image, how could I achieve this?

**Comment by bobafetthotmail** [comment]
this is a bug tracker, ask development questions in the forum
