### ISSUE TITLE
[21.0.2] Activity based LEDs not functional on Asus RT-AC56U

### ISSUE THREAD

**Issue by JustAnotherEndUser** [openwrt/openwrt#9307]
Version 21.02 on Asus RT-AC56U
Minor bug.  Only the power LED is functional.  None of the other status or activity based  LEDs light up.  Manually modifying LED settings from admin interface toggled them on ( when set to always on ) but had no effect when set to activity.  Note that issue only occurred after flashing to OpenWRT for testing.  LEDs were functional on previous firmware.  Thank you.

**Comment by pepe2k** [comment]
@JustAnotherEndUser is the `kmod-ledtrig-activity` package installed on your device? Could you provide uci configuration for `system` (`usi show system`)?

Cheers,
Piotr

**Comment by JustAnotherEndUser** [comment]
@pepe2k  , You are brilliant !   After updating the package list then manually installing kmod-ledtrig-activity package and re-configuring the individual settings for each LED  it is now working as expected. 
 I am new to OpenWRT, only having had installed it on an old router for testing purposes.  I wasn't aware of the need to manually install the Kmod package.  Thank you for replying to the solution.  Also thanks to @aparcar for adding the label to the post.  
 Cheers!

**Comment by neheb** [comment]
@JustAnotherEndUser do you still use this device?
