### ISSUE TITLE
Forum: At the release page the new release 21.02.2 is missing

### ISSUE THREAD

**Issue by dmuiX** [openwrt/openwrt#9310]
Not sure if this is the right place as it is more about the wiki than the code: 
At the release page the new release 21.02.2 is missing
https://openwrt.org/releases/21.02/start
But if you have a look at the download/file system page there is a new release: https://downloads.openwrt.org/releases/21.02.2/targets/

**Comment by ynezz** [comment]
This is not a bug, release is ready, when it's ready :-) In other words, until announced officially it's not ready for prime time yet.

**Comment by dmuiX** [comment]
So 21.02.2 is not a release then. Why do you put it on the release download page then!?

**Comment by aparcar** [comment]
It's not yet officially announced, please give it a bit more time!

**Comment by dmuiX** [comment]
I've already installed on my device :D. The time will tell if I find some errors^^
