### ISSUE TITLE
Error: ipv4: FIB table does not exist.

### ISSUE THREAD

**Issue by predators46** [openwrt/openwrt#9365]
Hy @feckert 

is this an iproute2 bug? I see this when I go to MWAN Status - Troubleshooting. and I see this warning in system.log. is this normal i should ignore it? I'm using yk-1 openwrt 21.02.2

`Tue Mar  1 05:03:56 2022 daemon.err uhttpd[972]: Error: ipv4: FIB table does not exist.
Tue Mar  1 05:03:56 2022 daemon.err uhttpd[972]: Dump terminated
Tue Mar  1 05:03:56 2022 daemon.err uhttpd[972]: Error: ipv4: FIB table does not exist.
Tue Mar  1 05:03:56 2022 daemon.err uhttpd[972]: Dump terminated
Tue Mar  1 05:03:56 2022 daemon.err uhttpd[972]: Error: ipv4: FIB table does not exist.`

**Comment by feckert** [comment]
I have no idea what you mean by a `FIB` table.

**Comment by predators46** [comment]
> I have no idea what you mean by a `FIB` table.

this error occurs when i finish installing mwan3 and go to MWAN Status - Troubleshooting and to system.log this error is there

**Comment by predators46** [comment]
@feckert 

as I suspected iproute2

https://lore.kernel.org/all/LaklAOJ--3-1@tutanota.com/T/

**Comment by champtar** [comment]
The iptables-legacy warning can usually be ignored, I might have time to fix it before branching but no promise

**Comment by MichaelWoodc** [comment]
2025 and I had a similar error, this was one of the only places I found with a similar enough error code and details about  iproute2 and MWAN, so here's what I had going on incase anybody stumbles across this:

```
root@OpenWrt:~# /etc/init.d/mwan3 restart
Error: ipv6: FIB table does not exist.
Dump terminated
Error: ipv6: FIB table does not exist.
Dump terminated
Error: ipv6: FIB table does not exist.
Dump terminated
```
It was quite puzzling.  wan worked just fine, and if I brought wanb up forcefully, it would work just fine, but then wan would go offline, and vice versa.

It was a game of digital whac-a-mole that kept going on until I forced the tables to exist, and then forced openwrt to use them.  First, I created tables in the iproute2 rt_tables file, then I seeded them which took care most of the error messages:
```
ip route add default via 10.0.0.1 dev wan table 220
ip route add default via 10.0.0.1 dev wan table 221
ip route add default via 10.1.1.1 dev lan4 table 222
```
but it seems that I had to make some rules for both of the interfaces to show up as online and stay online:
```
ip rule add from 10.0.0.246/32 table 221
ip rule add from 10.1.1.3/32 table 222
```

after that, I can finally surf the web with mwan3 working properly.

**Comment by soisoy** [comment]
Thank you for your hints @MichaelWoodc - I was seeing similar messages in my logs. I suspect the logs are the output of `ip -4 route list table [table_number]` and `ip -6 route list table [table_number]`.

I was able to ensure that the table was created by assigning a missing ipv4 or ipv6 address to the interface (even if it didn't require or have use for one - a link local or private address was fine). In the case of ipv6, setting `ip6assign` on the interface was an easy fix for me that is durable across reboots.

```
uci set network.ifname.ip4table='table_name_or_number'
uci set network.ifname.ip6assign='64'
uci add_list network.ifname.ip6class='local'
uci set network.ifname.ip6table='table_name_or_number'
```
