### ISSUE TITLE
[wiki, image builder] Undocumented shell command

### ISSUE THREAD

**Issue by o-alquimista** [openwrt/openwrt#9371]
The shell command below is at https://openwrt.org/docs/guide-user/additional-software/imagebuilder?rev=1639962402#restricting_root_access (currently with revision 1639962402)
> touch /etc/environment

I have no idea why this is needed. I went through all those commands but skipped this one. Everything still worked as expected.

**Comment by ynezz** [comment]
Hi, this is bug tracker, use [documentation forum](https://forum.openwrt.org/c/documentation/10) for such topics.
