### ISSUE TITLE
Feature Freeze

### ISSUE THREAD

**Issue by aparcar** [openwrt/openwrt#9394]
Dear all,

as discussed during our last member meeting, there is now a feature freeze in place! Please don't commit any major changes until the planed branch around March 20th.

After the branch heavy changes (i.e. Kernel 5.15) can be merged, for now we should work on bugs and finish up `firewall4` support.

March 20th is **not** the release date of 22.0x, after the branch we'll give it more time to stabilize.

**Comment by predators46** [comment]
Mwan3 openwrt snapshoot

`Warning: iptables-legacy tables present, use iptables-legacy to see them`
