### ISSUE TITLE
Lan Speed on Linksys EA8300 (Dallas)

### ISSUE THREAD

**Issue by cbholm** [openwrt/openwrt#9418]
I have a 1000 / 1000 Mbit FIber, if i check the on the wan side i get 900 / 900 sometimes 950/950 but if i do the same test on the Lan side (Not wifi) i only get 700 / 600 or less. 

I found out if I disable "Routing/NAT Offloading" the throughput will only be 500/500 
Experimental feature. Not fully compatible with QoS/SQM.
Software flow offloading

Software based offloading for routing/NAT
Hardware flow offloading

Requires hardware NAT support. Implemented at least for mt7621

OpenWrt info
<html>
<body>

Hostname | Local Net
-- | --
Model | Linksys EA8300 (Dallas)
Architecture | ARMv7 Processor rev 5 (v7l)
Target Platform | ipq40xx/generic
Firmware Version | OpenWrt 21.02.2 r16495-bf0c965af0 / LuCI openwrt-21.02 branch git-22.046.85957-59c3392
Kernel Version | 5.4.179

</body>
</html>
I had tested before with older Version on a Netgear WNDR3700 V2 (Openvrt V 19.07) then I got 900 /900, I don't have the Netgear any more.

**Comment by ynezz** [comment]
Not a bug.
