### ISSUE TITLE
Need Firmware Tool to do CE and FCC for AR9331 Modules

### ISSUE THREAD

**Issue by Ritesh236** [openwrt/openwrt#9490]
Hello Team,

We are using AR9331 Module into one of our Wi-Fi based product in which we are using 4.X.XX Kernel version with OpenWRT Build SYstem.

So, Now, We have requirement of CE and FCC certification for which we need following things for AR9331 chipset support

- Firmware Tool with details and command lists
- Document and Procedure like how to test it
- Changes required into Kernel and OpenWRT Build System
- So, Can anyone help us to get required tool and document which will be helpful for us to move further for certification perspective?

Regards,
Ritesh Prajapati

**Comment by pepe2k** [comment]
Hi Ritesh,

I'm afraid you would need to use QSDK (or the older one LSDK) from Qualcomm, with closed sources Wi-Fi drivers. In most cases that means you need to contact with your local Qualcomm distributor for help (which will probably require you to sign NDA to get access to all the software and documentation from Qualcomm).

Cheers,
Piotr

**Comment by Ritesh236** [comment]
@pepe2k ,

Thanks for your prompt response regarding it.

We have already checked with our module vendor but they don't have much details regarding software which we need. So,, Now, We need to contact Qualcomm to get things as per requirements.

Let me know if you have any direct contact which can help us to get firmware or tools as per requirements.

**Comment by pepe2k** [comment]
> Do you have any updates or details as per last updates i have sent?

No, sorry.

**Comment by Ritesh236** [comment]
@pepe2k ,

Thanks for providing response from your end.
