### ISSUE TITLE
iptables-nft

### ISSUE THREAD

**Issue by bugme2** [openwrt/openwrt#9503]
Show firewall (iptables) after installing iptables-nft, this is redundant.
![Screenshot_2022-03-19-19-23-09-14_11d59881ebb69c15251b128bef75a7ea](https://user-images.githubusercontent.com/40169265/159119087-41ba59ec-1307-4871-bbb8-8ad40420ef4e.jpg)

**Comment by champtar** [comment]
nft as shipped by OpenWrt will not print rules created by iptables-nft correctly, so it make sense to me to also have a iptables status page
