### ISSUE TITLE
[WISH] Make a live webpage that looks and works like LuCi that users can translate and see the result at the same time

### ISSUE THREAD

**Issue by Umeaboy** [openwrt/openwrt#9520]
I'd like to see a demo version of LuCi that can be translatable in real time so you can see the results.
I know we have Weblate to translate with and that's a nice way, but to actually see what you're translating would make it easier to finish the UI quicker since you see where it belongs.
Screenshots in Weblate would also be great, but it seems like nobody can add a screenshot.

**Comment by ynezz** [comment]
This is bug tracker and this is not a bug, for feature requests use other communication channels, like forum for example.
