### ISSUE TITLE
firewall4: option 'extra' is not supported by fw4

### ISSUE THREAD

**Issue by PussAzuki** [openwrt/openwrt#9532]
```
config rule
	option name 'Allow-protocol-59'
	option src 'wan'
	option proto '59'
	option target 'ACCEPT'
	option extra '-m length --length 40'
```

I use 6in4 tunnels, and then I searched for [these rules](https://openwrt.org/docs/guide-user/network/ipv6_ipv4_transitioning#firewall) that might be needed.

When reloading fw4, it throws `Section @rule[8] (Allow-protocol-59) option 'extra' is not supported by fw4`

**Comment by jow-** [comment]
Correct, these are iptables specific arguments which will not work with nftables.

**Comment by royujjal** [comment]
Any alternatives or is there any plan to supports extra in nftables also?
