### ISSUE TITLE
Feature Request: Mac Address

### ISSUE THREAD

**Issue by Che15ea** [openwrt/openwrt#9551]
Is it possible to add a permanent/random mac address changing function for Openwrt as WiFi client, WiFi Access Point and Ethernet client?
Thank you

**Comment by pepe2k** [comment]
@Che15ea 
Please, check our Wiki:
- https://openwrt.org/docs/guide-user/network/wifi/basic#common_options1 option: `macaddr`
- https://openwrt.org/docs/guide-user/base-system/basic-networking option: `macaddr`
