### ISSUE TITLE
how to remove X-Frame-Options: SAMEORIGIN  in luci response header 

### ISSUE THREAD

**Issue by 0neday** [openwrt/openwrt#9552]
I am using iframe on homeassistant recently, and I found this error 
![微信截图_20220326085513.png](https://s2.loli.net/2022/03/26/pcqOVfX8l3KbCyW.png)

I check openwrt, and found luci response header
 ![xframe.PNG](https://s2.loli.net/2022/03/26/eH1zsKr2MTxFG3V.png)

so, how to remove  X-Frame-Options?

**Comment by 0neday** [comment]
edit `/usr/lib/lua/luci/http.lua` and commit x-frame code 

```
                    --  if not context.headers["x-frame-options"] then
                    --          header("X-Frame-Options", "SAMEORIGIN")
                    --  end

```
, and then work fine.

**Comment by TheRealMaN** [comment]
removed X-Frame-Options, but still can't get it to work inside iframe, Authorization form appeared, but
after I hit "login" button" with username and password, login page just reloads and doesn't actually enter to router interface, in Chrome network tab I get 403 error form path "luci/", without iframe, all works right
