### ISSUE TITLE
unifi-6-lr snapshot build is broken for Mar 25th and 26th

### ISSUE THREAD

**Issue by petkan** [openwrt/openwrt#9557]
The aforementioned builds invariably go into boot loop, regardless of being sysupgrade-ed or flashed over OEM's firmware.  Build from source (the master branch) also gets into a boot loop.  Unfortunately i don't have serial console attached to the AP, so i can't tell what's the reason.  I've tested on two devices with the same result.  

thanks,
Petko

**Comment by dangowrt** [comment]
This might be the culprit. Can you try reverting this part of the commit below:
https://github.com/openwrt/openwrt/commit/ab143647efef2a13bcce2f28a2797899fbc83946#diff-7459a1ac2725159ef9860e1e81354a98bdcadaa8dfd45198fe2c76ca7e695031
