### ISSUE TITLE
Luci Attended-Sysupgrade: Resource not Found error

### ISSUE THREAD

**Issue by t3dium** [openwrt/openwrt#9559]
I'm trying to update openwrt in case it fixes #9539, but attended sysupgrade stopped working, and gives a "not found error" I was able to use it in the past..

screenshot of error:
![image](https://user-images.githubusercontent.com/83690012/160259183-7f56bb96-47d3-4800-9d9b-2625e5f676bc.png)

when pinging the sysupgrade domain, no issues there:
![image](https://user-images.githubusercontent.com/83690012/160259188-90d8144f-2e8f-4fab-b377-8b6e0be4aa0c.png)

**Comment by ynezz** [comment]
https://github.com/openwrt/luci is the correct place.

**Comment by Hielyr** [comment]
> https://github.com/openwrt/luci is the correct place.

Y'know, I don't think it is. 

I have this same error and if https://github.com/openwrt/luci is the correct address for Attended Sysupgrade, why does https://sysupgrade.openwrt.org/ still exist and have this text on the page?

> This server listens for requests to build custom OpenWrt sysupgrade images. It starts an ImageBuilder process for the specified target, incorporates any requested packages, and returns that image to the requestor.
