### ISSUE TITLE
kernel 5.15 for x86_64?

### ISSUE THREAD

**Issue by trippleflux** [openwrt/openwrt#9571]
Is there any chances for the x86_64 platform using kernel 5.15?

**Comment by aparcar** [comment]
I'll take care of that.

**Comment by ynezz** [comment]
> Is there any chances for the x86_64 platform using kernel 5.15?

It's in my [staging tree](https://git.openwrt.org/?p=openwrt/staging/ynezz.git;a=shortlog;h=refs/heads/staging)
