### ISSUE TITLE
Disable IPv6 cause - nft_reject_ipv6.ko' is missing

### ISSUE THREAD

**Issue by kofec** [openwrt/openwrt#9580]
Openwrt 22_03 - branch
ERROR: module '/home/user/openwrt_22_03/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/linux-5.10.108/net/ipv6/netfilter/nft_reject_ipv6.ko' is missing.
make[3]: *** [modules/netfilter.mk:1105: /home/user/openwrt_22_03/bin/targets/bcm27xx/bcm2708/packages/kmod-nft-core_5.10.108-1_arm_arm1176jzf-s_vfp.ipk] Error 1

**Comment by sebastian-de** [comment]
Disabling IPv6 is considered unsupported, see https://lists.openwrt.org/pipermail/openwrt-devel/2022-March/038249.html
CONFIG_IPV6 will probably be dropped in a future release.

**Comment by kofec** [comment]
Thanks for information.So closing
