### ISSUE TITLE
openwrt on xiaomi-4a-gigabit will infinite restart

### ISSUE THREAD

**Issue by EpicDogger** [openwrt/openwrt#9652]
<img width="559" alt="0d8e6020fdac5929242506ee14e0abc" src="https://user-images.githubusercontent.com/103055796/161786642-9a56c037-105e-4688-8549-f003f08aed75.png">
this is the router information on breed

**Comment by bill888uk** [comment]
flash chip ID 1c7118 is for EN25QX128A 
https://github.com/openwrt/openwrt/issues/9442

**Comment by Ansuel** [comment]
Closing this as it's a duplicate of #9442
