### ISSUE TITLE
does openwrt support asus-86u ?

### ISSUE THREAD

**Issue by kadisi** [openwrt/openwrt#9671]
i found that  openwrt now support asus-ac87u, does it support asus-ac86u ?

**Comment by pepe2k** [comment]
@kadisi you can always check list of supported hardware in OpenWrt's Wiki Table of Hardware: https://openwrt.org/toh/start?dataflt%5BBrand*%7E%5D=asus, your device is not on the list.

And please, next time use our forum for such general questions: https://forum.openwrt.org.
