### ISSUE TITLE
Redmi AX6s  error: recursive dependency detected!

### ISSUE THREAD

**Issue by zfgeng** [openwrt/openwrt#9684]
zfgeng@LAPTOP-R6CB4TRA:~/openwrt$ make menuconfig
Collecting package info: done
tmp/.config-package.in:102171:error: recursive dependency detected!
tmp/.config-package.in:102171:  symbol PACKAGE_iptables-legacy is selected by PACKAGE_iptables-nft
tmp/.config-package.in:102978:  symbol PACKAGE_iptables-nft is selected by PACKAGE_opennds
tmp/.config-package.in:101201:  symbol PACKAGE_opennds depends on PACKAGE_iptables-legacy
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

**Comment by kyoto44** [comment]
Got the same error on AX6S...

**Comment by dchard** [comment]
Exactly the same on my end:

```
tmp/.config-package.in:102820:error: recursive dependency detected!
tmp/.config-package.in:102820:  symbol PACKAGE_iptables-legacy is selected by PACKAGE_iptables-nft
tmp/.config-package.in:103627:  symbol PACKAGE_iptables-nft is selected by PACKAGE_opennds
tmp/.config-package.in:101850:  symbol PACKAGE_opennds depends on PACKAGE_iptables-legacy
```
