### ISSUE TITLE
valgrind not working when using sstrip

### ISSUE THREAD

**Issue by regae** [openwrt/openwrt#9710]
valgrind always gives 0 of all heap summary even though there is obviously a leak.
when toolchain (libc.so) is stripped using strip --strip-all, valgrind is working as expected.
can someone confirm this issue? or is it just in my build environments?

openwrt branch 22.03

**Comment by jow-** [comment]
Yes. You need to use an unstripped libc.so for valgrind to be able to hook malloc/free and equivalent memory management functions. This is a known limitation. Solution is either replacing `/lib/libc.so` on target (`scp build_dir/toolchain-*/musl/lib/libc.so root@192.168.1.1:/lib/libc.so`) or uploading an unstripped musl library and executing it directly:

```
$ scp build_dir/toolchain-*/musl/lib/libc.so root@192.168.1.1:/tmp/
$ ssh root@192.168.1.1
$ valgrind /tmp/libc.so /usr/sbin/leaking_program
```
