### ISSUE TITLE
openwrt 21.02.2 - factory | dev/root changing from rw to ro

### ISSUE THREAD

**Issue by pclinuxer** [openwrt/openwrt#9719]
Hello:

Installed openwrt 21.02.2 to a WD-My Book Live 1Tb drive.
Uneventful, no major issues save what I am reporting here.

Took a look at `dmesg` half way through checking out the UI, and it read:

```
[    0.907630] EXT4-fs (sda2): warning: mounting unchecked fs, running e2fsck is recommended
[    5.802598] EXT4-fs (sda1): warning: mounting unchecked fs, running e2fsck is recommended
```
This is probably due to the _plug/unplug/plug_ dance you have to do till you manage to get everything done and install a shutdown script more or less like this: `sync && sleep 2 && hdparm -Y /dev/sda && sleep 3 && halt`

Once the script is done and the light goes `blue`, you have ~ 15s to cut off power to the unit before it starts booting again. For the time being I think it may be enough so as to avoid damage the drive if/when you have to take it off-line.

But I digress ...

The thing is that `/dev/sda2` is mounted and cannot be unmounted.

```
root@OpenWrt:~# umount /dev/sda2
umount: can't unmount /dev/sda2: Invalid argument
root@OpenWrt:~# 
```
`/dev/sda1` is also mounted but _can_ be unmounted.

```
root@OpenWrt:~# umount /dev/sda1
root@OpenWrt:~# 
```
Once unmounted we fix it:

```
root@OpenWrt:~# e2fsck /dev/sda1
e2fsck 1.45.6 (20-Mar-2020)
/dev/sda1 was not cleanly unmounted, check forced.     <---- see what I mean?
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/sda1: 15/16 files (0.0% non-contiguous), 4100/8192 blocks
root@OpenWrt:~#
```
Then check it is OK:

```
root@OpenWrt:~# e2fsck /dev/sda1
e2fsck 1.45.6 (20-Mar-2020)
/dev/sda1: clean, 15/16 files, 4100/8192 blocks
root@OpenWrt:~# 
```
But it cannot be mounted again as it is not in `fstab`:
(no idea how to fix that, save with a reboot) 

```
root@OpenWrt:~# mount /dev/sda1
mount: can't find /dev/sda1 in /etc/fstab
root@OpenWrt:~# 
```
A reboot later, `dmesg` says nothing about `/dev/sda1`, so it must be healthy:

```
root@OpenWrt:~# dmesg | grep -i e2fsck
[    0.876095] EXT4-fs (sda2): warning: mounting unchecked fs, running e2fsck is recommended
root@OpenWrt:~# 
```
But `/dev/sda2`, holding the `root` file system has _not_ been fixed.
ie: not healthy

Not good ...

```
root@OpenWrt:~# blkid
--- snip ---
/dev/sda2: LABEL="rootfs" UUID="ff313567-e9f1-5a5d-9895-3ba130b4a864" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="228c756a-02"
--- snip ---
root@OpenWrt:~# 
```
I tried to see if it could be unmounted via the UI.
ie: `Mount  Points` -> `Mounted file systems`

But it was not there to unmount.

So I enabled it under `Mount Points` -> `/dev/sda2` -> `Edit` -> `General Settings` and then enabled `Run filesystem check` under `Advanced Settings`.

Cannot say what could have happened.
But after rebooting, the `rootfs` went from `rw` to `ro`, sure sign of some file system corruption puting it in `ro` mode.

I have read elsewhere about this happening but on a router, not on a `My Book Live.` 

There was no way I could solve this, tried all the available recovery options.

When I took out the drive to write the openwrt image file again on my box, I first tried to see if the problem could be fixed via `gparted` or `gdisks` but no dice.

Mainly because both the drive and _all_ filesystems on it were found to be healthy by _both_ utilities.

I'm reporting it because it would seem to be a bug of some sort.
But it is up to you. 

Thanks in advance,

Best,

PCL

**Comment by pepe2k** [comment]
@pclinuxer if I'm correct here, you are using extroot on the HDD and trying to unmount the root filesystem when it's running from the same disk? How could that ever work?

**Comment by pclinuxer** [comment]
Hello:

> installed OpenWrt directly on the HDD ...
Yes.
> ... trying to unmount the root filesystem
No, I did not try.
I set Run filesystem check under Advanced Settings to enabled for that partition.
But as result, the filesystem ended up as RO.
Or so it seems to me.

In any case, it was solved by taking the drive out and reinstalling OpenWRT.
Then I followed the directions in the post below so that every time the system boots, it will check and repair the disk.

https://github.com/openwrt/openwrt/issues/9719

Thanks for your input.

Best,

PCL

**Comment by pepe2k** [comment]
@pclinuxer 

> > ... trying to unmount the root filesystem
> No, I did not try.

Yes, you did.

> I was making the point that it could not be unmounted.

But you could re-mount it as `ro`.

> What I did was set `Run filesystem check` under `Advanced Settings` to _enabled_ for that partition.

Assuming your filesystem wasn't already corrupted at the moment when you were changing this setting, this should work.
You can always check content of the `/etc/config/fstab` for information about configured mount points and other related options (the filesystem check is also configured here, see: https://openwrt.org/docs/guide-user/storage/fstab).

> Maybe the filesystem was already corrupted at that point, hence the `ro`?.

Yes, that could be the reason, check your logs.

> In any case, this was solved by taking the drive out and reinstalling OpenWRT.

Or you could simply check and fix filesystem on that disk under desktop PC running any Linux distro.
