### ISSUE TITLE
libgcc_s.so.1: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by predators46** [openwrt/openwrt#9727]
Hy @neheb 

Can you help me. i made xmrig miner package and got error

undefined reference to symbol '_Unwind_Resume@@GCC_3.0'

libgcc_s.so.1: error adding symbols: DSO missing from command line

**Comment by ynezz** [comment]
This is bug tracker, for support requests and general questions please use [forums](https://forum.openwrt.org/c/devel/8) or IRC instead.

**Comment by neheb** [comment]
@predators46 static linking., probably need TARGET_LDFLAGS += $(if $(CONFIG_USE_GLIBC),-lc -lgcc_eh)

**Comment by predators46** [comment]
> 

Hy 

> @predators46 static linking., probably need TARGET_LDFLAGS += $(if $(CONFIG_USE_GLIBC),-lc -lgcc_eh)

Hy @neheb  @ynezz 

Thank you. do i just copy and add this in the makefile? i use cmake

**Comment by neheb** [comment]
yes.

**Comment by predators46** [comment]
I've tried it but it doesn't work

[Makefile.txt](https://github.com/openwrt/openwrt/files/8504057/Makefile.txt)

**Comment by predators46** [comment]
@neheb 

i wear musl
