### ISSUE TITLE
kernel: DSA config with mv88e6321

### ISSUE THREAD

**Issue by amandaW008** [openwrt/openwrt#9734]
Hi all,
I'm working on a custom board with a 88e6321. Port 5 is directly connected per RGMII to the CPU,  port 4 is connected to RJ45. port 0 is connected to a switch  through SGMII. 
here are my qustions:
1) I want to use  port 0 which connected to a switch just as a normal port to connect with out side through port 4, how do I config this in the dts?
2)if DSA  conifgs successful ,and I add a PHY  on other port,  can I read/wirte the registers of PHY easier than using Phywand?
Thanks in advance.

**Comment by pepe2k** [comment]
@amandaW008 please, use our forum (https://forum.openwrt.org), Wiki (https://openwrt.org) or mailing lists (https://lists.openwrt.org) for general support/functionality question/research.
