### ISSUE TITLE
wolfssl 5.20 caused compile error under 19.07

### ISSUE THREAD

**Issue by manjuprajna** [openwrt/openwrt#9739]
after commit 9ce6aa9d8d8a1147dcf03cb509cafb5fa7339a91 , 

/home/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/include/fort                                                                                                                                                             ify/stdio.h:114:3: warning: format not a string literal, argument types not chec                                                                                                                                                             ked [-Wformat-nonliteral]
   __r = __orig_sprintf(__s, __f, __builtin_va_arg_pack());
   ^~~
wolfcrypt/src/port/devcrypto/devcrypto_aes.c: In function 'wc_AesCtrEncrypt':
wolfcrypt/src/port/devcrypto/devcrypto_aes.c:211:9: error: redeclaration of 'ret                                                                                                                                                             ' with no linkage
     int ret;
         ^~~
wolfcrypt/src/port/devcrypto/devcrypto_aes.c:208:9: note: previous declaration o                                                                                                                                                             f 'ret' was here
     int ret;
         ^~~
make[6]: *** [Makefile:5924: wolfcrypt/src/port/devcrypto/src_libwolfssl_la-devc                                                                                                                                                             rypto_aes.lo] Error 1
make[6]: Leaving directory '/home/openwrt/build_dir/target-mips_24kc_musl                                                                                                                                                             /wolfssl-5.2.0-stable'
make[5]: *** [Makefile:6445: all-recursive] Error 1

@cotequeiroz pls check and fix it.

**Comment by ynezz** [comment]
Fixed via ecbbb373ed
