### ISSUE TITLE
does openwrt 21.02 support rtl8811cu?

### ISSUE THREAD

**Issue by youkechat** [openwrt/openwrt#9752]
I use https://github.com/brektrou/rtl8821CU compile for openwrt21.02, it can identify rtl8811cu wifi card, but enable this wifi use luci, all network will down

**Comment by drws** [comment]
Does the card definitely have RTL8811CU chip (which one is it)?

**Comment by youkechat** [comment]
comcast CF-811AC

**Comment by pepe2k** [comment]
@youkechat read this comment from our Forum, it's still valid: https://forum.openwrt.org/t/how-to-add-drivers-for-rtl8811cu-to-openwrt/59984/2?u=pepe2k
