### ISSUE TITLE
firewall4: negative netmask not working

### ISSUE THREAD

**Issue by janh** [openwrt/openwrt#9764]
firewall3 allowed to use negative netmasks, as in this example:

```
config rule
	option target 'ACCEPT'
	option src 'wan'
	option dest 'lan'
	option family 'ipv6'
	option proto 'tcp'
	option dest_ip '::1:0123:4567:89ab:cdef/-56'
	option dest_port '443'
```

This no longer works with firewall4. `/etc/init.d/firewall reload` prints the following error:
```
/proc/self/fd/0:165:13-43: Error: Could not resolve hostname: Try again
```

The same rule works fine when the full netmask is specified explicitly (`::1:0123:4567:89ab:cdef/::ff:ffff:ffff:ffff:ffff`).

(Tested with OpenWrt 22.03.0-rc1)

**Comment by ptpt52** [comment]
mark

**Comment by janh** [comment]
@jow: It looks like [your recent commit](https://git.openwrt.org/?p=project/firewall4.git;a=commit;h=c22eeeff1ef0884fd3c76f4ff2c72caa9de82fd5) was intended to fix this, but it doesn't work properly.

`/etc/init.d/firewall reload` now prints a different error:
```
/proc/self/fd/0:107:61-63: Error: syntax error, unexpected tcp, expecting comma
```
The corresponding line in `fw4 print` is this:
```
ip6 daddr ::1:123:4567:89ab:cdef/::ff:ffff:ffff:ffff:ffff tcp dport 443 counter jump accept_to_lan comment "!fw4: @rule[10]"
```

When the full netmask is specified the rule is slightly different and there is no error:
```
ip6 daddr & ::ff:ffff:ffff:ffff:ffff == ::1:123:4567:89ab:cdef tcp dport 443 counter jump accept_to_lan comment "!fw4: @rule[10]"
```

**Comment by notgood** [comment]
As this issue breaks existing configs, can it be labeled for openwrt-22.03 please?

**Comment by jow-** [comment]
Please test the firewall bump commit at https://git.openwrt.org/49e6daa8
