### ISSUE TITLE
kmod-mt76x2u snapshot package not support netgear A6210 USB wifi

### ISSUE THREAD

**Issue by youkechat** [openwrt/openwrt#9770]
detail was here, https://forum.openwrt.org/t/openwrt-not-support-netgear-a6210/126000/7, but I think this was driver bug or compatible problem, So I made a issue here

openwrt version: OpenWrt SNAPSHOT r19519-39799974a3 / LuCI Master git-22.089.43958-7110635
model: friendlyelec nanopi r4s
architecture: armv8 processor rev4
kernel version:5.10.112-1-d6ca1fc39c57d2c317b777327099b930
kmod-mt76x2u version: 5.10.112+2022-04-23-a666d563-4

I have tried many Operating frequency combination, but none works, what's mean device not active?

![image](https://user-images.githubusercontent.com/60725793/164983224-b4eebb98-1120-4da0-9344-47520fb70d7e.png)

lsmode
```
root@OpenWrt:~# lsmod | grep mt
cfg80211              319488  5 mt76x2_common,mt76x02_usb,mt76x02_lib,mt76,mac80211
mac80211              565248  4 mt76x2u,mt76x02_usb,mt76x02_lib,mt76
mt76                   53248  5 mt76x2u,mt76x2_common,mt76x02_usb,mt76x02_lib,mt76_usb
mt76_usb               24576  2 mt76x2u,mt76x02_usb
mt76x02_lib            57344  3 mt76x2u,mt76x2_common,mt76x02_usb
mt76x02_usb            20480  1 mt76x2u
mt76x2_common          24576  1 mt76x2u
mt76x2u                24576  0
```

dmesg
```
root@OpenWrt:~# dmesg | fgrep -i firmware
[    0.000000] psci: PSCIv1.1 detected in firmware.
[29861.090870] mt76x2u 6-1:1.0: Firmware Version: 0.0.00
```

dmesg | fgrep -i mt76x2u
```
root@OpenWrt:~# dmesg | fgrep -i mt76x2u
[    6.617349] usbcore: registered new interface driver mt76x2u
[29860.889775] mt76x2u 6-1:1.0: ASIC revision: 76120044
[29860.921153] mt76x2u 6-1:1.0: ROM patch build: 20141115060606a
[29861.090870] mt76x2u 6-1:1.0: Firmware Version: 0.0.00
[29861.091764] mt76x2u 6-1:1.0: Build: 1
[29861.092668] mt76x2u 6-1:1.0: Build Time: 201607111443____
```

**Comment by Boos4721** [comment]
<a href="https://ibb.co/hXRNWCd"><img src="https://i.ibb.co/wJNqWYQ/i-Shot2022-04-25-13-33-06.png" alt="i-Shot2022-04-25-13-33-06" border="0" /></a>

**Comment by youkechat** [comment]
after install wpad-basic-wolfssl, A6210 ap mode enabled
