### ISSUE TITLE
SDK staging_dir target missing dev files

### ISSUE THREAD

**Issue by ptpt52** [openwrt/openwrt#9784]
dev files is missing in SDK
like:
`staging_dir/target-*/usr/include/`
is empty

what if I build an app, which depends on `uci.h` via SDK

**Comment by jow-** [comment]
Since a couple of OpenWrt releases already we ship a lean SDK without any package specific development headers or libraries. To make `<uci.h>` available in SDK, you do need to follow these steps:
```
./scripts/feeds update base
./scripts/feeds install libuci
make menuconfig # enable libuci
make package/uci/compile
make package/yourapp/compile
```
