### ISSUE TITLE
[documentation] GnuPG signing key for v22.03.0 missing

### ISSUE THREAD

**Issue by o-alquimista** [openwrt/openwrt#9814]
The key used to sign the currently available RC of v22.03.0 is missing from the [documentation](https://openwrt.org/docs/guide-user/security/signatures#gnupg_key_fingerprints), without which we cannot verify the downloaded `sha256sum` file.

[This](https://downloads.openwrt.org/releases/22.03.0-rc1/targets/ramips/mt7621/) is the target I'm trying to get.

**Comment by ynezz** [comment]
Should be fixed https://openwrt.org/docs/guide-user/security/signatures#pgp_key_for_2203_release_builds
