### ISSUE TITLE
DDNS Luci Information Page Labels

### ISSUE THREAD

**Issue by IvoKvesic** [openwrt/openwrt#9823]
The Luci Information page under heading **Services** uses column labels (in the last text column on the right) **Last Update** and **Next Update**. However the date/time values shown correspond to the *check* date/time and not *update* date/time. Propose to change the word **Update** to **Check**.

**Comment by pepe2k** [comment]
@IvoKvesic please report this on the LuCi project issue tracker: https://github.com/openwrt/luci/issues

Cheers,
Piotr
