### ISSUE TITLE
openwrt-22.03 bricks Samknows SK-WB8

### ISSUE THREAD

**Issue by isidorosss** [openwrt/openwrt#9824]
openwrt-22.03.0-rc1-ramips-mt7621-samknows_whitebox-v8-squashfs-sysupgrade.bin seems that bricks Samknows SK-WB8 (ramips/mt7621).
I flashed it on luci while on 21.02.2 and bricked it once. Then i unbricked it and flashed 21.02.3 then i tried one more time to flash 22.03 and bricked it again.
I'm pasting the code below.

```
## Booting image at bce30000 ...
Bad Magic Number,85190320
```

whole debug log here: https://wtools.io/paste-code/bB8c

**Comment by pepe2k** [comment]
@isidorosss I don't know this device but looking at your logs clearly shows that the U-Boot is trying to boot from a wrong address/offset, see:

Booting from 0xbce30000 fails:
```
## Booting image at bce30000 ...
Bad Magic Number,85190320
```

Booting from 0xbc050000 works:
```
## Booting image at bc050000 ...
   Image Name:   MIPS OpenWrt Linux-5.4.188
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    2381084 Bytes =  2.3 MB
   Load Address: 80001000
   Entry Point:  80001000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK
No initrd
## Transferring control to Linux (at address 80001000) ...
## Giving linux memsize in MB, 128
```
And at least once the image with 5.10 kernel (22.03 image?) was almost booted:
```
## Booting image at bc050000 ...
   Image Name:   MIPS OpenWrt Linux-5.10.111
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    2694082 Bytes =  2.6 MB
   Load Address: 80001000
   Entry Point:  80001000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... LZMA ERROR 1 - must RESET board to recover
```
The `LZMA ERROR 1` could be related to kernel size and probably this board would require similar change as introduced in e83f7e5d76ebf74aa0a1f686d2941950fa5f22e2 and 12f3d1466ad783fded1747fa2ee521a9bea1ff73.

Cheers,
Piotr

**Comment by pepe2k** [comment]
@isidorosss I pushed a fix, to master and 22.03 branches. Could you try in a few days (when new images become available) a 22.03 snapshot from here: https://downloads.openwrt.org/releases/22.03-SNAPSHOT/targets/ramips/mt7621/ and let me know if it fixes the problem? Thanks!

Cheers,
Piotr

**Comment by isidorosss** [comment]
@pepe2k I confirm that when a new snapshot is available, i'll check if everything works well on the device during the next days. Thanks a lot for the help Piotr!

**Comment by isidorosss** [comment]
@pepe2k Hey Piotr! I flashed successfully OpenWrt 22.03-SNAPSHOT r19340-1c6a179e1a / LuCI openwrt-22.03 branch .
Everything seems to work fine! Thanks a lot!
![image](https://user-images.githubusercontent.com/35171656/168429532-2ff955cd-ddd4-4be6-a26b-866188849fa4.png)

**Comment by pepe2k** [comment]
@isidorosss thanks for the feedback!
