### ISSUE TITLE
openwrt 21.02 xiaomi_mi-router-ac2100 when finished build,there is a warning

### ISSUE THREAD

**Issue by Bruce6709** [openwrt/openwrt#9826]
openwrt 21.02 xiaomi_mi-router-ac2100 when finished build,there is a warning
WARNING: Applying padding in /workdir/openwrt/bin/packages/mipsel_24kc/packages/Packages to workaround usign SHA-512 bug!

But in the end the firmware is generated
![image](https://user-images.githubusercontent.com/102840341/166341197-3f800b9c-cd6b-40b0-93fd-8cb9d7b26be6.png)

**Comment by pepe2k** [comment]
@Bruce6709 this is intentional, see: https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=e1f588e446c7ceb696b644b37aeab9b3476e2a57
