### ISSUE TITLE
After I chose 'ISOLATE Clients', the AP can still access each other.

### ISSUE THREAD

**Issue by Tonkercke** [openwrt/openwrt#9832]
My router sets two LAN interfaces, one is LAN, the other is LAN2, and the assigned IP address is 192.168.2.1 and 192.168.3.1, and then two WiFi APs are set. Choose 'ISOLATE Clients'. When the previous version of OpenWrt 21.02.2, the device connected to LAN2 cannot use LAN's IP address to log in to the LUCI console interface, which shows that Isolate Clients is effective. However, after upgrading to OpenWRT 21.02.3, the device connected to LAN2 can log in to the LUCI console with LAN's IP address. This shows that Isolate Clients is invalid.

I don't know how to solve this problem, I hope to reply, thank you! 
![122](https://user-images.githubusercontent.com/67683757/166712235-5cdeae5f-d79e-4fd0-a6da-c54062eed996.PNG)

**Comment by pepe2k** [comment]
@Tonkercke `Isolate Clients` option purpose is for isolating wireless clients connected to the AP from each other, please see:
- https://openwrt.org/docs/guide-user/network/wifi/guestwifi/extras#isolating_clients
- https://openwrt.org/docs/guide-user/network/wifi/basic#common_options1

If you still think this is a bug, please report it on the LuCi project issue tracker instead:
https://github.com/openwrt/luci/issues

Cheers,
Piotr
