### ISSUE TITLE
openwrt.org: Blurry logo on HiDPI screen

### ISSUE THREAD

**Issue by paulmenzel** [openwrt/openwrt#9838]
https://openwrt.org/ includes a logo in the navigation bar, which is blurry on HiDPI screens.

     <img id="dw__logo" class="pull-left h-100 mr-4" alt="OpenWrt Wiki" src="/_media/logo.png">

    $ md5sum logo.png
    74efdc45034ff7374c6135c5e2c89e21  logo.png
    $ file logo.png
    logo.png: PNG image data, 137 x 42, 8-bit/color RGBA, non-interlaced

Is an SVG version available? If yes, could that be used instead?

**Comment by davidschlachter** [comment]
This one: https://github.com/openwrt/branding/blob/master/logo/openwrt_logo_text_horizontal_white_and_blue.svg

**Comment by paulmenzel** [comment]
Awesome. Is this the right issue tracker for Web site related issues, or is there another way to contact the Web masters?

**Comment by pepe2k** [comment]
@paulmenzel I think it will be better to ask about this on the forum (maybe here: https://forum.openwrt.org/c/site-feedback/3?) or the mailing list.

Cheers,
Piotr
