### ISSUE TITLE
Add GCC 8 or later support

### ISSUE THREAD

**Issue by Hi-hass** [openwrt/openwrt#9868]
I am trying to install homeassistant and it returns:
`gcc: error: unrecognized command line option '-ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/Python-3.10.4=Python-3.10.4'
it looks need a new version`   
  
This error seems to require a new version of GCC

**Comment by lucize** [comment]
please see this https://github.com/lmahmutov/SGW-Homeassistant
it's hard to add it to default openwrt, because of specific Python HA requires, that are conflicting with existing packages, but for sure the owner and I will be updating this
