### ISSUE TITLE
How to submit a patch to maintainer-tools.git

### ISSUE THREAD

**Issue by graysky2** [openwrt/openwrt#9919]
I would like to submit a patch to `update_kernel.sh` in maintainer-tools but since it is not hosted on github, I linked my PR below.

@rsalvaterra 

https://gist.github.com/graysky2/9b1f0f5f812613dfeebe9ae8568e06f5

**Comment by pepe2k** [comment]
@graysky2 `maintainer-tools` is hosted on the main Git repository: https://git.openwrt.org/?p=maintainer-tools.git;a=summary

You can submit your patch to the devel mailing list (https://lists.infradead.org/mailman/listinfo/openwrt-devel), with a prefix like `[PATCH maintainer-tools] ...`

Cheers,
Piotr
