### ISSUE TITLE
bcm27xx after kernel 5.15 poe hat fan not work when install kmod-pwm-raspberrypi-poe module

### ISSUE THREAD

**Issue by SquallATF** [openwrt/openwrt#9926]
@Noltari
Only the `kmod-pwm-raspberrypi-poe` module poe hat fan will not work, the `kmod-hwmon-pwmfan` module is also required, may be should add kmod-hwmon-pwmfan to the dependencies.

https://github.com/raspberrypi/linux/blob/fb2bb1ca79f20afbe008b90f5f93ccf3374b488d/arch/arm/boot/dts/overlays/rpi-poe-overlay.dts#L10-L20

https://github.com/raspberrypi/linux/blob/fb2bb1ca79f20afbe008b90f5f93ccf3374b488d/drivers/hwmon/pwm-fan.c#L524-L527

**Comment by Noltari** [comment]
> @Noltari
> 
> Only the `kmod-pwm-raspberrypi-poe` module poe hat fan will not work, the `kmod-hwmon-pwmfan` module is also required, may be should add kmod-hwmon-pwmfan to the dependencies.
> 
> 
> 
> https://github.com/raspberrypi/linux/blob/fb2bb1ca79f20afbe008b90f5f93ccf3374b488d/arch/arm/boot/dts/overlays/rpi-poe-overlay.dts#L10-L20
> 
> 
> 
> https://github.com/raspberrypi/linux/blob/fb2bb1ca79f20afbe008b90f5f93ccf3374b488d/drivers/hwmon/pwm-fan.c#L524-L527

Thanks for reporting this @SquallATF,
It should be fixed with cecb0ccfbf08c7fbcc74da860df1e20016a4b9de

**Comment by SquallATF** [comment]
Thanks
