### ISSUE TITLE
Is HW NAT on MT7621A works with PPPoE in 21

### ISSUE THREAD

**Issue by cooltronicpl** [openwrt/openwrt#9932]
I have dramatically high CPU usage on OpenWRT, around 100% on 600 Mbit/s PPPoE link.

Is Hardware NAT offloading is supported in 21 OpenWRT with PPPoE connection, is 100% usage of CPU is okay, is it HW NAT working correctly?

**Comment by Matthaiks** [comment]
Nope, but it does work fine in soon-to-be-released 22.03.

**Comment by Matthaiks** [comment]
22.03-snapshot-r19378-9f415792e1 works fine. 

 21.02 does not support HWNAT with PPPoE. 19.07 supports it but HWNAT may affect the router's stability.

**Comment by jow-** [comment]
Please use the forum for support questions.
