### ISSUE TITLE
Always true condition in `rtl83xx/dsa.c`

### ISSUE THREAD

**Issue by qarmin** [openwrt/openwrt#9953]
https://github.com/openwrt/openwrt/blob/064e7e57b483e6879de0facef4f1fce86ec4ad47/target/linux/realtek/files-5.10/drivers/net/dsa/rtl83xx/dsa.c#L549

Any number is bigger than 52 or smaller than 55

**Comment by jow-** [comment]
@bkobl @dangowrt - any idea? Seems to have been introduced with 51c8f766124487f6e84076c272645e5f29d32f5e

**Comment by bkobl** [comment]
Yes, this should be && not ||. But I am not sure it is worth the effort to fix it. There are no RTL931x devices in master, so this is of no consequence and for the next feature updates foreseen with more support for the RTL931x the code already fixes this, by distinguishing the MAC-SerDes and SerDes-Media link states, which is a much better solution:
https://github.com/bkobl/openwrt/blob/f16b0b026a79d773598eb3aec9dda0e93900d648/target/linux/realtek/files-5.10/drivers/net/dsa/rtl83xx/dsa.c#L482

**Comment by dangowrt** [comment]
@bkobl Will you open a PR once the code in your repo is ready to be considered for merging to master?

**Comment by bkobl** [comment]
Yes, absolutely. I want to have full support for the XS1930 so that others like you can do the RTL931x testing and at that point I want to create  the PR.

**Comment by Djfe** [comment]
Just fishing through old issues, what's the status here. Can this be closed? :)

**Comment by MaZderMind** [comment]
This code still exist and is probably still broken. I can open a PR for it but I don't have a `rtl93xx` device.
