### ISSUE TITLE
firewall: move custom input_rule, forwarding_rule and output_rule chains

### ISSUE THREAD

**Issue by ne20002** [openwrt/openwrt#9958]
I wonder why the custom _input_rule_, _forwarding_rule_ and _output_rule_ chains are placed as first in the firewall's INPUT, OUTPUT and FORWARD chains.
For me it looks like due to this placing, those chains' filter are also applied to all pakets allready belonging to cstate REALTED,ESTABLISHED state.
 
![grafik](https://user-images.githubusercontent.com/39007279/170871126-09c8a23b-52dc-4a41-87de-2f83b3edaffa.png)

This seems to be unneccessary, as pakets of already related/established connection shouldn't be needed to be filtered again. 

Is there a way to place the custom chains **after** cstate REALTED,ESTABLISHED rule?

**Comment by jow-** [comment]
It is intentional to allow creating user rules that do match already established flows (e.g. time based ones, those should also affect already established flows). There is no option to change that.

**Comment by ne20002** [comment]
Hi @jow- 
I do understand this intention but I believe to have at least an option to choose wether to put the custom chain before or after the related/established chains would be handy.

E.g.: I just added BCP83 which I believe is a usefull filter. But I don't see why this filtering needs to be applied before related/established. It is just consuming cpu when every and each packet is processed in the filter.
Same applies for IPTV ... it's just a huge amount of packtes which do not need to run through the filter.

It's maybe not an issue as soon as offloading is working again ... (btw, how would offloading would work with time based filters?)
