### ISSUE TITLE
Document miniupnpd option 'external_iface6'

### ISSUE THREAD

**Issue by j9brown** [openwrt/openwrt#9989]
Related to: https://openwrt.org/docs/guide-user/firewall/upnp/miniupnpd

The document describes 'external_iface' but is missing 'external_iface6' which is also supported by the scripts.  It's important for users to know to set both when they have multiple gateways.

**Comment by Ansuel** [comment]
Tell me if I should add additional stuff to the option in the wiki.

**Comment by j9brown** [comment]
That was quick, thanks!
